### ISSUE TITLE
[Bug]: Explo hardsuits teleport to AI core when the AI tried to eject them from the suit storage

### ISSUE THREAD

**Issue by Liver-1** [BeeStation/BeeStation-Hornet#10022]
### BYOND Version

515.1614

### Round Date

13/10/2023

### Round ID

46225

### Test merges

The following pull requests are currently test merged:
[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#9899: 'Refactor preference loading, add extensive logging' by itsmeow at commit 9a37c28ad1](https://www.github.com/beestation/beestation-hornet/pull/9899)

Local commit: cb7540adbc88f4302ee18089f3ed98d5f807f3cf
TGS version: 5.16.1
DMAPI version: 5.6.1

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Protect Command Roles From Traitor: 1
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 15 of 27 roundtypes
Allow Midround Antagonists: 7 of 27 roundtypes

### Describe the bug

When I clicked on the explo hardsuit storage, opened it, and then clicked the icon for hardsuits as AI (trying to be helpful to the explos), I noticed that the suits teleported to my core.

### What did you expect?

I expected the suits to be ejected at the storage cases

### Reproducible steps

1. Start shift as ai
2. open hardsuit storage in explo
3. click the harsuit to release it

**Comment by Marshmellow105** [comment]
'How do you steal a hardsuit if you don't have hands???'
'I DONT KNOW??????'

**Comment by Tsar-Salat** [comment]
I have an idea for this, I'll have it up soon

**Comment by Harranhall** [comment]
I noticed this happens with mining stuff in those same suit storage thingies

**Comment by Tsar-Salat** [comment]
> same suit storage thingies

See pr I linked above. 

All SSUs are missing an adjacency check. They try to put an item in your hand, and when that fails because the user is an AI, it will drop the suit at your feet, regardless of distance.

I fixed it in that PR, just gotta wait till it gets merged
