### ISSUE TITLE
[Bug] Sound from west(left) side is weirdly silent

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#10035]
I don't get the reason, but the sound from the western side from your character is weirdly silent. 

Let's say there are 4 airlocks to 4 directions from your character. 
* North: fine
* South: fine
* East: a little bit louder than north/south, but fine
* West: doesn't make any sound.

I am not sure if it's only me.

**Comment by HowToLoLu** [comment]
I was unable to reproduce this.

Have you tried enabling mono audio and seeing if the sound itself is just wierd on your headphones? I've had audio degradation from bad headsets before due to continously dropping them.

**Comment by EvilDragonfiend** [comment]
ah, if it's only me, then not that important. I will find a way to fix it. thanks
