### ISSUE TITLE
Multilingual doesn't work for Ethereals, they don't get an extra langauge UNLESS foreigner

### ISSUE THREAD

**Issue by TheMaggotGuy** [BeeStation/BeeStation-Hornet#10046]
Issue reported from  Round ID: 46292 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

The Issue:

Multilingual does not appear to do anything for ethereals.

What I expect to happen: I expect to get a third language in addition to Voltaic and Common. This does not happen.

Steps to reproduce:

1. Make Ethereal Character
2. Take Multilingual trait
3. Get shipped to station for job
4. Open language menu
5. Only 2 languages, no extra language.

**Comment by TheMaggotGuy** [comment]
very very weirdly it *does* work if you pick foreigner?? for some reason??

**Comment by tontyGH** [comment]
Not able to reproduce this
