### ISSUE TITLE
[Bug]: Character Preferences saving error

### ISSUE THREAD

**Issue by Shiraizawa** [BeeStation/BeeStation-Hornet#10062]
### BYOND Version

514.1589

### Round Date

2023.10.21

### Round ID

46317

### Test merges

- #9124
- #9501
- #9604
- #10034 
- #10060

### Describe the bug

Joined spessgame then hit Setup Character and got greeted with an
"Failed to save your datumized character preferences. Please inform the server operator or a maintainer of this error."
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/48320612/ce9118ce-8094-4faa-a25d-645c0ac7820a)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/48320612/f06896b0-57a8-4448-a09a-f04495d3ffa0)

Changing between my character slots, it triggers the same message and I noticed that everytime I switch on my Mushroom person, their Mushroom Cap sprite changes to a new one.

Switching between characters fast enough results in: 
"A SQL error occurred during this operation, check the server logs"
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/48320612/c98b34d5-3fdc-462a-b6ca-2fb1f8941e73)

### What did you expect?

I expected not seeing this error

### Reproducible steps

1. Join
2. Hit Setup Character
3. Suffer

**Comment by Shiraizawa** [comment]
Ok new Info, If I change something on a Non-Mushroom person then Saving succeeds and works for any characters other than the Mushroom. Changing to the Mushroom will instantly result in the Failure and clicking on any other character will fail the saving until a feature of that non-mushroom character gets changed, then saving works fine again. 

@DrDuckedGoose Your child is acting up..

**Comment by DrDuckedGoose** [comment]
Addressed.
Thanks for letting me know.

**Comment by itsmeow** [comment]
Testmerge issue.
