### ISSUE TITLE
[Bug]: The monkey AI can TAKE components out of the genetics pod while inside

### ISSUE THREAD

**Issue by Tsar-Salat** [BeeStation/BeeStation-Hornet#10091]
### Describe the bug

When I did the mokey inside the genetics pod, I noticed them REMOVING its stock parts. Though it didnt deconstruct the machine, this is obviously not intended behavior.

### What did you expect?

I expected monkeys not to break something for once. Typical AI behavior should have them unable to perform actions a human wouldnt be able to besides those specifically outlined in their code (ventcrawling).

### Reproducible steps

1. monkey
2. genetics pod
3. watch as the AI begins scooping out the contents(stock parts) like they scoop out my dreams

**Comment by Tsar-Salat** [comment]
Im half blaming myself, half-blaming the stupid monkey AI for breaking every month.

Caused by #9314

**Comment by Fronsis** [comment]
> Im half blaming myself, half-blaming the stupid monkey AI for breaking every month.
> 
> Caused by #9314
> 
> I'll have a fix up soon

![image (2)](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/423d7a7c-adc4-4cc4-ac93-e72c9fbeaae2)

Just for evidence sake, but machines do seem to remain operational so hmm duplication glitch :trollface:

**Comment by Harranhall** [comment]
What happens if you decon the machines after this? Does it spit out all the parts?

**Comment by itsmeow** [comment]
Monkeys also love triggering ui_interact which runtimes.
