### ISSUE TITLE
[Bug]: Ciggarette pack is invisible when closed

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#10098]
### Round Date

2023/10/27

### Round ID

46399

### Test merges

[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#9337: 'Inventory adjustments' by Rukofamicom at commit 757482b284](https://www.github.com/beestation/beestation-hornet/pull/9337)
[#10059: 'MC Diagnostic Mode' by PowerfulBacon at commit ef589b82e2](https://www.github.com/beestation/beestation-hornet/pull/10059)

### Describe the bug

Basically, when you purchase a pack of Robust ciggies(the red ones) the sprite works fine, however the moment you open it, for example,to put the zippo in or to take a ciggie out and then you close the box the sprite becomes invisible, i haven't tried it with other brands

The sprites stays visible if you leave the pack ''open'' it only stays invisible when it's fully closed, in hand, on the floor, on bagpack, etc

### What did you expect?

I expected to see the ciggie box-closed sprite!

### Reproducible steps

1. Purchase Robust packet
2. Take one ciggie out to smoke
3. Close the packet
4. Sprite becomes invisible
5. If you want to see it you need to leave the packet with the lid open, otherwise it remains 100% invisible

**Comment by JikkaJoestar** [comment]
can confirm, I have reproduced it

**Comment by JikkaJoestar** [comment]
The linked PR did not fix the issue.

**Comment by Tsar-Salat** [comment]
> The linked PR did not fix the issue.

The linked pr didn't get merged
