### ISSUE TITLE
[New Feature]: Remove janky PREVENT_CLICK_UNDER on windows, but disallow the grilles themselves from being hit

### ISSUE THREAD

**Issue by Tsar-Salat** [BeeStation/BeeStation-Hornet#10096]
### Describe the feature request

All full-tile windows in the game utilize the PREVENT_CLICK_UNDER_1 flag, this exists primarily, I believe, so players cannot destroy the grille underneath while the window still exists. 

While this is an important behavior, PREVENT_CLICK_UNDER_1 effects *everything* on the tile, including pipes and unrelated structures.

Windows should have the same behavior, sans windows, that walls have. Its incredibly annoying to accidentally construct something on windows and have to deconstruct the whole tile, whilst on a wall you can immediately target what you are aiming for.

**Comment by itsmeow** [comment]
How does one even click something underneath another thing?

**Comment by Tsar-Salat** [comment]
> How does one even click something underneath another thing?

Alt+clicking, then selecting...?
