### ISSUE TITLE
[Bug]: Deepfrying bluespace capsules seals the contents inside them

### ISSUE THREAD

**Issue by JixS4v** [BeeStation/BeeStation-Hornet#10125]
### Round Date

N/A

### Round ID

N/A

### Describe the bug

When testing if I could eat "unique" items by deepfrying them inside a BS capsule, I found out you can't eat it after doing so, permanently sealing the contents of the latter inside it, since you can't open it either.

### What did you expect?

I expected the bluespace capsule to be able to be eaten, or it not being able to be deepfried.

### Reproducible steps

1. Put item you want to seal into BS capsule
2. Close BS capsule
3. Deepfry BS capsule
4. Try eating/opening

**Comment by Tsar-Salat** [comment]
Yeah, I have a fix going up for deepfrying in general.

Thanks for testing this

**Comment by EvilDragonfiend** [comment]
@Rukofamicom

**Comment by Rukofamicom** [comment]
why did I get an @ for this.

**Comment by EvilDragonfiend** [comment]
because it's your code?

**Comment by Rukofamicom** [comment]
Deep frying is not my code.

If there's some snowflake code behind deepfrying that breaks because a new item is added, that's the fault of whoever made frying.
