### ISSUE TITLE
Don't seem to have a chat window since switching drives/OS

### ISSUE THREAD

**Issue by Dankseed** [BeeStation/BeeStation-Hornet#1015]
Issue reported from  Round ID: 10401 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1503

For some reason, only on beestation codebase, my chat does not load in. I can still hear and talk to other people, but there is just a blank white box where the chat window normally is. Anyone have any ideas?

**Comment by eLeCtrOssSnake** [comment]
Does problem persist?
Did you try relogging?

**Comment by Dankseed** [comment]
It has been over the course of multiple days, I have tried everything I can think of. It works in all tg servers, yet neither of Bee's.

**Comment by eLeCtrOssSnake** [comment]
Idk, I have this problem when I switch to finnish keyboard layout(start game with it or press t on it) and then I need to reconnect in order to get it back.

**Comment by ike709** [comment]
Clear cache. Also try the verb that reloads chat.

**Comment by Dankseed** [comment]
Did both, also changed around my IE settings a million times, even tried to
run in compatibility mode. No dice.

**Comment by ike709** [comment]
If you're on Win10 it's probably BYOND's hardware acceleration issue.

**Comment by eLeCtrOssSnake** [comment]
But he said that it happeneds only on bee.

**Comment by Dankseed** [comment]
I have tried all of the suggested solutions, no dice. :( I seriously have
no idea.

**Comment by ike709** [comment]
@eLeCtrOssSnake Doesn't matter.

@Dankseed If you're on win10:

1. Open BYOND
2. Click the gear in the top right
3. Preferences > Games >Untick "Use graphics Hardware..."
4. Clear cache, then click Okay.
5. Restart BYOND. Like the actual process. Don't just minimize then maximize it.
6. Repeat step 3, except tick it again. Clear cache again.
7. Try playing on bee.

**Comment by ike709** [comment]
Ever since a recent win10 update, BYOND's hardware acceleration has been finnicky. Something to do with DirectX, I don't remember. It's especially bad if you have any screen capture programs running. Fraps, OBS, ShareX, Gyazo... Disable all of those and give it another go.

**Comment by yorii** [comment]
@Dankseed What version of windows were you on? Is this still an active issue?
