### ISSUE TITLE
[Bug]: Ash drakes endlessly mauling corpses

### ISSUE THREAD

**Issue by benbot16** [BeeStation/BeeStation-Hornet#10162]
### BYOND Version

515.1614

### Round Date

2023/11/9

### Round ID

46552

### Test merges

- #9124 
- #10059 
- #9501

### Describe the bug

Ash drakes don't stop attacking dead bodies, and will randomly start attacking bodies that are already dead. They'll even do this while being shot at (said ash drake in the picture was shot 30 times with a PKA from 3 tiles away while this occurred).

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/9423435/115d0b19-5e77-4369-8a87-dcc408f03a6a)

### What did you expect?

Ash drakes should defend themselves instead of endlessly attacking bodies.

### Reproducible steps

1. Throw corpse at ash drake
2. Wait for ash drake to start attacking the corpse (may take time or require the drake to be damaged, unsure what triggers it)
3. Shoot the ash drake until it dies

Alternatively:
1. Die to ash drake
2. Spawn as new character
3. Do something that should draw aggro
4. The drake won't aggro properly

This hasn't been tested with other megafauna, but when I have time I can test it.

**Comment by Rukofamicom** [comment]
@mystery3525 

Did you just spawn dead bodies for your PR testing evidence? This should have been apparent when testing your PR: https://github.com/BeeStation/BeeStation-Hornet/pull/9807

There's a variable to fix this on mobs that tells them what state of being they will continue to attack. Will get this tomorrow.

**Comment by Fronsis** [comment]
Seems like this applies to every megafauna that gibs bodies, saw reports of Bubblegum doing it too, they got locked permanently attacking said body

**Comment by Rukofamicom** [comment]
Yes it would be. 

Took longer than I'd liked but I'm about to have a fix for this up.
