### ISSUE TITLE
[Bug]: Borg Alarm Monitor Doesn't Work

### ISSUE THREAD

**Issue by Alpkant** [BeeStation/BeeStation-Hornet#10177]
### BYOND Version

514.1589

### Round Date

12/11/2023

### Describe the bug

When I am cyborg and after some problems around the station i check my station alarm program from my hud, it always shows nominal. It never shows the alarms. It is not due to new test merges i think. This problem is happening to me for a long time.

### What did you expect?

I expected when we have air alarms or fire alarms, it should show in cyborg alarm program.

### Reproducible steps

1. Be a borg
2. Ensure that there is a breach in hallways or fire alarm triggered
3. Check your station alerts, you will see all systems nominal. No alarm!

**Comment by Nakalon** [comment]
Will check this tomorrow. If I can fix it I'll add it to my ongoing PR.
