### ISSUE TITLE
[Bug]: Unable to move after being freezed by Blue Watcher

### ISSUE THREAD

**Issue by Nakalon** [BeeStation/BeeStation-Hornet#10188]
### Round Date

17/11/2023

### Round ID

46632

### Test merges

The following pull requests are currently test merged:
[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10059: 'MC Diagnostic Mode' by PowerfulBacon at commit ef589b82e2](https://www.github.com/beestation/beestation-hornet/pull/10059)
[#9501: 'Psyphoza - Species Addition ' by DrDuckedGoose at commit 08abcc4434](https://www.github.com/beestation/beestation-hornet/pull/9501)

### Describe the bug

I was in lavaland, got shot by a Blue Watcher, which froze me solid. I was being draged by someone else. I unfroze but was still unable to move. I was an IPC.

### What did you expect?

I expected to be able to move after thawing.

### Reproducible steps

1. Have someone drag you
2. Get frozen by Blue Watcher
3. Try to move after unthawing.

**Comment by Miliviu** [comment]
This Bug was solved with #10297, this Issue should be closed :)

**Comment by Penwin0** [comment]
Thanks for letting us know!
