### ISSUE TITLE
[Bug]: Polymorphing Force Ghosts When Changing Into Borg

### ISSUE THREAD

**Issue by ShadowSlimeBeestation** [BeeStation/BeeStation-Hornet#10180]
### Round Date

2023/11/14

### Round ID

46606

### Describe the bug

When the staff of change bolt turns someone into a borg, it'll instantly ghost them. 

### What did you expect?

I expected people to remain in their body when hit with the staff of change. 

### Reproducible steps

1. Grab a staff of change/wand of polymorph
2. Use it on any player until they change into a borg

**Comment by Tsar-Salat** [comment]
Yeah, force converting a borg as cult does this too. 

I fixed this in #9824 by making it pull the ghost back in immediately. It's a bandaid, but it works.

Perhaps a similiar solution could work here.
