### ISSUE TITLE
[Bug]: Exploration lags you out randomly for the rest of the round.

### ISSUE THREAD

**Issue by Nakalon** [BeeStation/BeeStation-Hornet#10203]
### Round Date

16/11/2023

### Test merges

[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10059: 'MC Diagnostic Mode' by PowerfulBacon at commit ef589b82e2](https://www.github.com/beestation/beestation-hornet/pull/10059)
[#9501: 'Psyphoza - Species Addition ' by DrDuckedGoose at commit 08abcc4434](https://www.github.com/beestation/beestation-hornet/pull/9501)

### Describe the bug

I don't have a round number because this happened about 3 times (the times I played explo) (the date is also a rough estimate) and this is also known to "have happened since, and before".

Upon arriving at an explo objective the game starts lagging considerably more than it was before.

The lag is not internet style, more like hardware lag.

The lag will remain for the rest of the round.

In one round, the admin Marshmellow deleted my character and had me respawn and that fixed it.

This happened with a blob type objective. I don't remember if it happens with the others.

### What did you expect?

I expected not to lag.

### Reproducible steps

1 - Go to Blob type explo objective
2 - Play around a bit. Lag should happen instantly but I'm not sure.
3 - Congratulations you're lagging.

**Comment by PowerfulBacon** [comment]
This is most likely due to the exploration UI, however I haven't heard of it continuing to lag after being closed (however it may be possible with zombie windows if it is somehow still updating in the background)

**Comment by PowerfulBacon** [comment]
#10183 Linked issue?

**Comment by Nakalon** [comment]
> #10183 Linked issue?

Don't think so!

This is a very heavy lag, not exponentially, that happens usually the moment you land. I think its tied to the custom landing process but I've only ever seen it with Blob enemies.
