### ISSUE TITLE
[Bug]: Returning from Ninja Dojo can send you to the atmos gas chambers

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#10210]
### Round Date

2023/11/22

### Round ID

46699

### Test merges

[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

When returning from the ninja dojo you have a chance to be dropped at the atmos gas chambers making you well... very hard to be rescued/revived!
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/d9542407-83ad-4d11-acc1-4234b544a2d0)

### What did you expect?

I expected to return to a safe turf!

Pinging @PowerfulBacon since they reworked the dojo-return and so he doesn't forget! cheers!

### Reproducible steps

1. Be ninja
2. Grab a target(or multiple since RNG)
3. Swap your ghost to the targets and see how you have a chance to be dropped there when returning
4. Death!

**Comment by HowToLoLu** [comment]
And this *has* happened several times; the bug has been here for at least a year I think.

**Comment by Fronsis** [comment]
> And this _has_ happened several times; the bug has been here for at least a year I think.

Huh really? Under what context? because iirc Bacon recently(a couple of months?) pushed so people could leave the Dojo after 10? minutes, before that they were stuck forever in the Dojo

**Comment by HowToLoLu** [comment]
I've seen people mention this once or twice in discord recently, and it also is an issue with contractors since they use the exact same code for finding turf. That's how I landed in an N2 chamber a year ago when being put back on the station, and the other day someone ended up in a mix chamber.
