### ISSUE TITLE
[Bug]: Stack of pancakes cannot be consumed

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#10222]
### Round Date

2023-11-24

### Round ID

46723

### Describe the bug

Stack of pancakes cannot be consumed.

### What did you expect?

They should be able to be consumed.

### Reproducible steps

1. Acquire a stack of pancackes. (I got them from a vend-a-tray)
2. Attempt to eat the stack of pancakes (I am full)
3. I am unable to eat the pancakes and recieve no message in the chat when clicking on my sprite. No interactions work with the stack to convvert it into a single pancake for production.

**Comment by Tsar-Salat** [comment]
Fails edibility? I included a unit test in the Grown pr that should prevent these regressions in the future.

I'll look at making a specific fix
