### ISSUE TITLE
[Bug]: Force cryo fails if player is buckled

### ISSUE THREAD

**Issue by JixS4v** [BeeStation/BeeStation-Hornet#10233]
### Round Date

2023/11/28

### Describe the bug

Tried to forcecryo someone, the cloud passed over and didn't work, forcecryo stopped working for everyone.

### What did you expect?

I expected forcecryo to work

### Reproducible steps

1. Buckle someone
2. Forcecryo them through smiting
3. ???
4. Forcecryo doesn't work again for the round

**Comment by itsmeow** [comment]
We need the Round ID

**Comment by JixS4v** [comment]
Managed to replicate during round 46780
