### ISSUE TITLE
[Bug]: Size of Botanical Chem dispenser fluctuates during dispensing animation

### ISSUE THREAD

**Issue by PsionTarrasque** [BeeStation/BeeStation-Hornet#10242]
### Round Date

2023/29/11

### Round ID

46783

### Test merges

BYOND Version: 515.1614
Server revision compiled on: 2023-11-29T08:26:20+00:00
Master commit: [1338a86c381798d6b066c9c46f89a97bcc099489](https://www.github.com/beestation/beestation-hornet/commit/1338a86c381798d6b066c9c46f89a97bcc099489)
The following pull requests are currently test merged:
[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

During the animation for dispensing fluid, the Botanical Chem Dispenser flashes between two sizes. Also, the beaker is off-center in the large (default) state
![Beeg](https://github.com/BeeStation/BeeStation-Hornet/assets/100320883/0b7e22a3-ba48-41df-9e0f-feba12c9cccd)
Large, the default state

![Smol2](https://github.com/BeeStation/BeeStation-Hornet/assets/100320883/fe1d83c8-0061-4565-b7c2-f93814606889)
The mid-dispense state

### What did you expect?

I expected it to remain the same size during the animation

### Reproducible steps

1. Place beaker into Botanical Chem Dispenser
2. Put fluid into chem dispenser

**Comment by Tsar-Salat** [comment]
yeah... conversion to update_appearance probably did this. I'll see if i can find a fix.
