### ISSUE TITLE
Golem Mining IDs linked to account with infinite money

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#10259]
Issue reported from  Round ID: 46814 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Golem mining IDs are linked to a so called "Shared Mining Account", which houses about 200.000 credits that can be freely withdrawn. Very weird!

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/76008882/9a0ad0f6-204e-403a-bf48-3a2ceeadeda0)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/76008882/17046e9d-e704-4451-a563-3c4de9d5dcb8)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/76008882/c3cd5659-1bc1-4764-9c84-a9f8a049cf31)

**Comment by EvilDragonfiend** [comment]
It is intended. All golem's ID cards are linked to a single account which is very vulnerable. Golems do not have personal economy freedom.

**Comment by EvilDragonfiend** [comment]
Although it is true that there is no checking account owner, but it is the same issue to all accounts. Not sure when I will change that.
