### ISSUE TITLE
Seniormin Doesn't Have Mentor Panel Access

### ISSUE THREAD

**Issue by oo7craigmc** [BeeStation/BeeStation-Hornet#10260]
Issue reported from  Round ID: 46817 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Halp.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/48850629/52fac56b-66bb-4260-94f5-d0c0f187d2a5)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/48850629/3e693b16-c12b-45e8-8a5a-38ee0d62169f)

**Comment by itsmeow** [comment]
Did you join the game deadminned? If so, you probably won't get a mentor datum assigned to you

**Comment by oo7craigmc** [comment]
Nope.
I was adminned the whole time.
