### ISSUE TITLE
[Bug]: Supply Console bug

### ISSUE THREAD

**Issue by ClownMoff** [BeeStation/BeeStation-Hornet#10270]
### Round Date

2023/12/04

### Round ID

46837

### Describe the bug

When updating the cargo shuttle computer spectrum to board with a multitool, it doesn't change the lists of orders avaiable
![imagen](https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/9c05d3ad-0968-4d29-9941-3e75b3924343)
![imagen](https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/d4123004-800e-4069-8e11-d9dbd9476b62)

### What did you expect?

I expected the supply console to change to broad mode

### Reproducible steps

Go to the supply console, change it to broad, observe how it doesnt update

**Comment by Dejaku51** [comment]
What did you expect?
