### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#10284]
### BYOND Version

514.1589

### Round Date

2023/06/12

### Round ID

46861

### Test merges

[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

Planting C4 on someone shows no message.

### What did you expect?

That people get notified from planting C4 on a person

### Reproducible steps

Plant C4 on someone, there is no indication that it's happening.

**Comment by NotACoderSorry** [comment]
It’s not a bug but a very poor feature that should probably change. X4 and breaching charges share the same behaviour too.
