### ISSUE TITLE
[Bug]: Delta CMO office missing the stamp

### ISSUE THREAD

**Issue by JixS4v** [BeeStation/BeeStation-Hornet#10293]
### Round Date

2023/12/08

### Round ID

46886

### Describe the bug

No stamp in the CMO's office on delta

### What did you expect?

I expected a stamp

**Comment by HowToLoLu** [comment]
6 years and Delta hasn't had a CMO stamp. Incredible (I'm adding it right now)

**Comment by aramix273** [comment]
recalling from memory, metastation might also have the same problem after the medbay rework that occurred on both meta and delta

**Comment by HowToLoLu** [comment]
> recalling from memory, metastation might also have the same problem after the medbay rework that occurred on both meta and delta

Turns out Meta *is* missing that. I missed that while making the fix, so thanks for pointing it out.
