### ISSUE TITLE
[Bug]: Tesla coil lightning doesn't target mechs

### ISSUE THREAD

**Issue by boombaklops** [BeeStation/BeeStation-Hornet#10298]
### Round Date

forgor

### Round ID

forgor

### Describe the bug

There was a round where a roboticist and I tried to test the durability of a gygax with tesla coil lightning, only to find that it would never get hit. We tried it at least 5 times, even removing all nearby machines to prevent RNG. Also, the result was the same whether or not the gygax had a pilot.

### What did you expect?

I expect mechs to get hit by lightning.

### Reproducible steps

1. Prepare a tesla coil.
2. Park a gygax nearby.
3. Pulse the tesla coil wire.

**Comment by NotACoderSorry** [comment]
Mechs are insulated. This is intended behaviour.

**Comment by boombaklops** [comment]
well i'll be damned. i'll close this if someone can confirm it.
