### ISSUE TITLE
[New Feature]: swarm type antags (like spiders and swarmers) to be unaffected by ghost respawn timeout

### ISSUE THREAD

**Issue by kiekatz** [BeeStation/BeeStation-Hornet#10290]
### Describe the feature request

I'd like it if [mass antag roles such as swarmers, spiders,blob spores portal carps not be affected by the ghost respawn limiter. they are weak antags rellying on their sheer numbers and having those be limited after their first death just makes go loud be a terrible tactic... "we took the risk we got many spawners now... and we still die cuz ghosts cant enter them... risk punished... better just play carefully and slowly and boringly"... also for any future antags that'd be added maybe it'd be a rule if they relly on numbers plug the. ignore ghost respawn]

**Comment by Tsar-Salat** [comment]
The problem is ghosts metaknowledge the fuck out of these roles, and being able to diagnose it occurring gets 10 times worse when they can respond and go back to their previous position instantly.

These antags *should* have to wait for reinforcements

**Comment by kiekatz** [comment]
the antags in question...spiders...blobzombies(spore strain)...swarmers...spacedragon's carps who's sole job is guarding a gate

i dont see much of tactical gameplay on those... they are designed to be numerous... most are pathetically weak. its often i see a gate get fucked with 5 carps ready to spawn cuz all ghosts did their turn or spiders grow greatly... first generaton dies... and oh wow we got 6 eggsacs but no spiders cuz all ghosts are on cooldown... SHAME WE WENT AGRESSIVE FOR THOSE 6 EGGS IT WAS NOT WORTH IT... or blob zombies strain literally having its only advantage being SWARMS of bloberzombies. by the time the timer drops its all over

**Comment by PowerfulBacon** [comment]
Swarmers: No
Spiders: No
Blob Spores: Yes
Portal Carps: Yes

Any antagonists that exist with the sole purpose to run into combat and die can be cleared of the ghost respawn timer, any antagonists that should stay alive and play tactically should not.
