### ISSUE TITLE
[Bug]: Emissives make nightmares incapable of hiding properly in the dark without jaunting.

### ISSUE THREAD

**Issue by NotACoderSorry** [BeeStation/BeeStation-Hornet#10311]
### Round Date

2023/12/14

### Round ID

46959

### Test merges

#9124

### Describe the bug

Emissives from the eyes reveal the nightmare’s tile when wearing a darkness removing HUD like mesons, and removes their ability to be stealthy while on foot. This is also present with darkness, but at least that way it’s moody and hard to see.

### What did you expect?

A nightmare standing in the dark to not be visible at a distance  without night or thermal vision.

### Reproducible steps

Spawn nightmare in darkness
Spawn mesons
Look at nightmare from a distance with and without the mesons

**Comment by PowerfulBacon** [comment]
Is the nightmare wearing mesons or the player observing the nightmare?

**Comment by NotACoderSorry** [comment]
> Is the nightmare wearing mesons or the player observing the nightmare?

Player observing the nightmare.
