### ISSUE TITLE
You can curbstomp yourself

### ISSUE THREAD

**Issue by Guestratem** [BeeStation/BeeStation-Hornet#1031]
## Round ID:
10510

## Testmerges
no testmerges active

## Reproduction:
you can curbstomp yourself that's really it, I have a fair idea where the issue is its in the checks again, being the ultimate bug bear for me.

**Comment by eLeCtrOssSnake** [comment]
That's cursed. Will investigate today.

**Comment by qwertyquerty** [comment]
Feature
