### ISSUE TITLE
[Bug]: You can intentionally get stuck in the heretic sacrifice minigame

### ISSUE THREAD

**Issue by aramix273** [BeeStation/BeeStation-Hornet#10328]
### BYOND Version

514.1589

### Round Date

-

### Round ID

-

### Test merges

idk, works on a local server at the date of this bug report

### Describe the bug

if you are in a body bag (and I assume any other similar situation, should you be able to also pull it to the heretic minigame)
the game will fail to pull you back to the station upon the end of the minigame, leaving you stuck there
what you can do now is, I don't know, build a quantum pad or something, if those even work on centcom z-level
no clue if this affects the heretic's progression and how so

https://github.com/BeeStation/BeeStation-Hornet/assets/27755442/9c20972e-438a-4abd-8b10-c0aa5cd60b42

relevant runtime
```
[17:39:32] Runtime in sacrifice_knowledge.dm,382: list index out of bounds
  proc name: return target (/datum/heretic_knowledge/hunt_and_sacrifice/proc/return_target)
  usr: Guest-X(Aniya Jewell)
  usr.loc: (Central Primary Hallway (144, 111, 2))
  src: Heartbeat of the Mansus (/datum/heretic_knowledge/hunt_and_sacrifice)
  call stack:
  Heartbeat of the Mansus (/datum/heretic_knowledge/hunt_and_sacrifice): return target(Mckenna Rosensteel (as Captain... (/mob/living/carbon/human))
  /datum/callback (/datum/callback): Invoke()
  world: push usr(Unknown (/mob/living/carbon/human), /datum/callback (/datum/callback))
  /datum/callback (/datum/callback): InvokeAsync()
  Timer (/datum/controller/subsystem/timer): fire(0)
  Timer (/datum/controller/subsystem/timer): ignite(0)
  Master (/datum/controller/master): RunQueue()
  Master (/datum/controller/master): Loop()
  Master (/datum/controller/master): StartProcessing(0)

```

### What did you expect?

what I'd expect to work different are... multiple things:
- hands should damage you in second phase even when lying down (would prevent replication as described below)
- or the teleport should work regardless of being in a body bag or not

### Reproducible steps

can also check the video above
a precondition is obviously that a heretic will sacrifice you
1. get a body bag
2. get sacrificed, alive too, so you can get sent to hands minigame area
3. survive through first phase
4. wait until second phase comes, indicated by "the worst is behind you" message
5. rest and uncuff yourself, now that hands don't hurt you in this phase
6. get up, place a body bag and close yourself in it
7. wait until the vignette around the screen disappears, indicating that the minigame is over
8. you are now helstuck

**Comment by JixS4v** [comment]
Apparently fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/10324
