### ISSUE TITLE
[Bug]: Clicking on backpack/pockets doesn't register

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#10338]
### BYOND Version

514.1589

### Round Date

2023/12/18

### Round ID

47017

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 347bf8b17f](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

Sometimes, randomly, you will be unable to click on your backpack or pockets. Clicks don't register and nothing happens. It seems to randomly go away by itself after a few minutes.

### What did you expect?

I expected to be able to use my backpack/pockets.

### Reproducible steps

Unknown.

**Comment by PowerfulBacon** [comment]
Are you a psychoza?

**Comment by AnCopper** [comment]
> Are you a psychoza?

No. Human. This bug has existed for years at this point on all servers. It wouldn't surprise me if it was a Byond bug.
