### ISSUE TITLE
[Bug]: Colorblind persists after revival

### ISSUE THREAD

**Issue by RussianGenCoke** [BeeStation/BeeStation-Hornet#10335]
### BYOND Version

514.1589

### Round Date

2023/12/17

### Round ID

47003

### Test merges

- [#9124: 'Enable serverside 515.1614' by Crossedfall at commit 347bf8b17f](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

When I got revived I was still colorblind, I noticed color did not return to me until I went blind again (welding mask)

### What did you expect?

I expected to not be colorblind.

### Reproducible steps

1. Die
2. Get revived
3. Wait a minute or two.

I do not know if headwear is the issue, I used to be able to fix this bug by removing my hat but now it seems like only going blind again fixes this.

**Comment by PsionTarrasque** [comment]
I also noticed this problem when a sanity-destruction anomaly hit my borg. It continued until the end of the round.
![BnW](https://github.com/BeeStation/BeeStation-Hornet/assets/100320883/563f9307-39b5-450a-8a36-84a56bc1c45e)
