### ISSUE TITLE
[Bug]: Can't Click to Pick up Exploration Radio Key

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#10347]
### BYOND Version

514.1589

### Round Date

2023/12/19

### Round ID

Null

### Test merges

#9124

### Describe the bug

When I left click on an Exploration Radio Key, I noticed that I can't pick it up. I have to right click, select it and click on "Pick Up" to actually pick it up.

### What did you expect?

I expected to be able to pick up the Exploration Radio Key.

### Reproducible steps

1. Use a screwdriver on an Exploration Radio headset to extract the Radio Key.
2. Attempt to pick up the Radio Key using left click.

**Comment by Miliviu** [comment]
I have been trying to replicate this error, I have been unable, is it still happening to you?

**Comment by MarkusLarsson421** [comment]
I'll give it a try.

**Comment by MarkusLarsson421** [comment]
> I have been trying to replicate this error, I have been unable, is it still happening to you?

It only happens to the Exploration radio headsets spawned on the shuttle. This does not happen to ones your character spawns with or other headsets spawned in lockers or bought through vending machines.
