### ISSUE TITLE
[Bug]: Creating a Teleporter eats your Bluespace Crystals

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#10345]
### BYOND Version

514.1589

### Round Date

2023/12/19

### Round ID

47031

### Test merges

#9124

### Describe the bug

When I constructed a teleporter on the Exploration shuttle I noticed that the Teleporter Hub kept eating my Bluespace Crystals. I put in a pair of two and they vanished, still requiring me to insert another two Bluespace Crystals. I attempted it four times using a variation of regular Bluespace Crystals and Artificial Bluespace Crystals with no luck. Additionally when I crowbared it to start over, it would only return one out of two glass sheets that I had put in it. 

### What did you expect?

I expected the machine to be constructed without eating a bunch our precious Bluespace Crystals and not refuse to be constructed.

### Reproducible steps

1. Construct a machine frame, wire it and wrench it.
2. Add in the Teleporter Hub board.
3. Add in the required components.
4. Watch as it still wants more Bluespace Crystals.

I was unable to reproduce this on my local test server, so this may be related to the test merge or there are steps that I am unaware of and missing.

**Comment by Tsar-Salat** [comment]
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/2b08c167-21f7-4851-9358-fb7c5a5c513b)

Unable to replicate on latest branch

**Comment by MarkusLarsson421** [comment]
It's weird. An admin observed it, but I don't remember who it was. They eventually spawned in the Teleport Station after I had magically fed it 8 Bluespace Crystals. Perhaps someone can find out, given the round ID up above.

**Comment by Tsar-Salat** [comment]
In a debug environment, one usually has a max stack of minerals to work with, which is what prevented me from correctly reproducing the issue.

Apologies, the fix pr is now up.
