### ISSUE TITLE
[Bug]: Unable to add resources to complete constructions

### ISSUE THREAD

**Issue by JReese3** [BeeStation/BeeStation-Hornet#10350]
### BYOND Version

515.1614

### Round Date

2023/12/19

### Round ID

47035

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 347bf8b17f](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

When I created a console It kept failing to finish the screen with 2 sheets of glass but consumed the resource after about 6 attempts the glass was finally added, When I created a Golem shell and added 10 Plastitanium to finish it the result was the same I was unable to finish the golem shell. I also did not get a message about the steps that failed.
![Material-addition-woes](https://github.com/BeeStation/BeeStation-Hornet/assets/103800684/6c855651-db94-4f07-be47-163159fda4f9)

May also be impacting RPED,  This was unclear, I had to use the RPED a couple times to work in a couple instances.

### What did you expect?

I expect the add materials step to use the resources and complete the step, not eat the resources and fail to progress.

### Reproducible steps

Build any construction that requires a material addition
Complete all steps until the addition part
Add material and watch as step fails to complete in most instances

**Comment by EvilDragonfiend** [comment]
identified. going to be fixed soon.
