### ISSUE TITLE
[Bug]: Plasmamen heretics do not have living hearts

### ISSUE THREAD

**Issue by autocephalophagy** [BeeStation/BeeStation-Hornet#10360]
### Describe the bug

Spawning in as a plasmaman heretic does not give you a living heart. I'm considering it a bug/oversight because the admins seemed surprised by it and gave me one through commands, so it doesn't seem like intentional game design.

### What did you expect?

I expected to spawn with a living heart. Instead I couldn't transmute or sacrifice anything and wound up killing the wrong person. Losing the living heart should be a downside to dying and getting cloned, not something that cripples the role from the start.

**Comment by Miliviu** [comment]
https://github.com/BeeStation/BeeStation-Hornet/issues/9119

Yup! Upstream issue!
