### ISSUE TITLE
[Bug]: Purple/black tiles in Lavaland

### ISSUE THREAD

**Issue by Aligotess13** [BeeStation/BeeStation-Hornet#10365]
### BYOND Version

515.1621

### Round Date

2023/12/20

### Round ID

47045

### Test merges

#9124: 'Enable serverside 515.1614' by Crossedfall at commit 347bf8b17f
#10276: 'Floor Resprite - The Sequel' by DrDuckedGoose at commit 9e0547f242

### Describe the bug

When I was observing Lavaland, I noticed black and purple tiles on the floor. They disappeared when dug up into ashen sand.
![Screenshot (161)](https://github.com/BeeStation/BeeStation-Hornet/assets/89031914/f2497c7b-a503-4581-873f-4de8e9776a3c)

### What did you expect?

I expected there to be normal ash floors throughout Lavaland.

### Reproducible steps

Perhaps they can be spotted throughout Lavaland.

**Comment by DrDuckedGoose** [comment]
This should be resolved, let me know if it isn't

**Comment by Aligotess13** [comment]
Yeah, it seems to be fixed :)
