### ISSUE TITLE
[New Feature]: Stop cremators from instantly RRing living players

### ISSUE THREAD

**Issue by boombaklops** [BeeStation/BeeStation-Hornet#10374]
### Describe the feature request

I present this video.

https://github.com/BeeStation/BeeStation-Hornet/assets/116023863/2b65c3e7-6492-4643-abf5-540e6878605e

I thought my death was funny, but I'm sure the novelty would quickly wear off if it kept happening. Adding a way to resist out of the cremator or making them work like a lethal version of hardsuit storage decontamination would be nice.

**Comment by zeskorion** [comment]
i've wanted this for awhile. My solution would be to apply intense heat until husked, and then dust the target. unlock and release after five minutes or so if they survive
