### ISSUE TITLE
[Bug]: 'Anti-glow' mutation actually makes you glow like 'Glowy'

### ISSUE THREAD

**Issue by Marshmellow105** [BeeStation/BeeStation-Hornet#10383]
### BYOND Version

514.1589

### Round Date

2023/12/23

### Round ID

47068

### Test merges

#10378
#9124

### Describe the bug

Geneticist combines 'glowy' and 'void magnet' to make the 'anti glow' mutation. The 'anti glow' mutation then functions as if it was just the 'glowy' mutation and emits a soft light rather than darkness.

### What did you expect?

I expected anti glow to not glow

### Reproducible steps

1. Make antiglow
2. Give yourself said antiglow
3. Emit light instead of darkness

**Comment by HowToLoLu** [comment]
I noticed this when I made #9340; though wasn't sure if it was still an active issue. The main reason from what I can gather is that the color itself is treated as the brightness/voidness(?) when mixing color stuff; which ends up making (127,127,127) do absolutely nothing. Glow is also the same way.

**Comment by HowToLoLu** [comment]
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/9f0e8b12-56b0-4d60-98cb-3b6dc8d41e0f)
Three people with anti-glow, from right to left their mut colors are 000000, 7F7F7F, and FFFFFF

**Comment by Tsar-Salat** [comment]
Glow is so dumb conceptually. Wouldnt a mutation called "Glow" make you biolumenscent like a Jellyfish or something? Instead its the same as a flashlight in your pocket that you cant turn off.

I know what would make the lame mutation better, make it have an emissive layer, dependent on species. Lizards could have glowy spines, moths could have glowy fur(fluff or whatever that is), etc.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/34d617ef-71dc-4a93-ba14-6f76994606cd)

Image being a lizard with ya spines all glowy and cool n shit. Instead we got pocket flashlight. Yay.

**Comment by PowerfulBacon** [comment]
It should make your limbs have an emissive overlay instead
