### ISSUE TITLE
[Bug]: Mindbreaker toxin doesn't prevent RDS hallucinations

### ISSUE THREAD

**Issue by ToasterBan** [BeeStation/BeeStation-Hornet#10399]
### BYOND Version

514.1598

### Round Date

2023/12/26

### Round ID

47109

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 347bf8b17f](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

Had RDS as a roundstart quirk, took mindbreaker, hallucinations still happened

### What did you expect?

not hallucinations to happen

### Reproducible steps

1. Get RDS
2. Take Mindbreaker
3. Wait for a hallucination

**Comment by EvilDragonfiend** [comment]
It's intended. Mindbreaker toxin does kinda reversed effect to RDS

**Comment by EvilDragonfiend** [comment]
Oh my mistake. Yeah it shouldn't happen.
