### ISSUE TITLE
[Bug]: Reebe lighting overlay isn't generated

### ISSUE THREAD

**Issue by JixS4v** [BeeStation/BeeStation-Hornet#10392]
### Round Date

N/A

### Round ID

N/A

### Describe the bug

Reebe doesn't let you see more than 3 tiles in front of you. It's not like the light decays, it's just blacked out. Calling generate_lighting_overlay on the area fixes it.

### What did you expect?

I expected visibility to work on reebe

### Reproducible steps

Force clock cult, spawn yourself in naked

**Comment by JixS4v** [comment]
Seems to happen for the whole centcom Z

**Comment by Eric-01** [comment]
Add the holodeck and the CTF minigame to the list.

**Comment by itsmeow** [comment]
Who did this

**Comment by HowToLoLu** [comment]
> Add the holodeck and the CTF minigame to the list.

Those are meant to not have dynamic lighting in code; they just get baked with fullbright;

Reebe on the other hand should have either dynamic lighting or fullbright.

(Confirmed this on a local server on the latest commits, the line in the middle is a sign of not being fullbright)

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/1d4337c5-2338-428e-9595-bda644a9a38a)

**Comment by Eric-01** [comment]
HowToLoLu, even if the holodeck and CTF minigame are supposed to be fully bright, they are still affected by this bug, and it manifests itself in the same way as it does on Reebe. The regressor is probably the same.

**Comment by HowToLoLu** [comment]
> HowToLoLu, even if the holodeck and CTF minigame are supposed to be fully bright, they are still affected by this bug, and it manifests itself in the same way as it does on Reebe. The regressor is probably the same.

Sorry about that, found that out after someone on discord mentioned it; they indeed are broken as well. 

Unfortunately the regressor affecting the other areas is a bit more complex as someone decided to put a variable for power systems in the middle of it all.
