### ISSUE TITLE
[Bug]: Dog treats are ERRORs

### ISSUE THREAD

**Issue by May-Rai** [BeeStation/BeeStation-Hornet#10391]
### BYOND Version

514.1589

### Round Date

2023/12/24

### Round ID

47083

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 347bf8b17f](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10378: 'Revert "Minor refactor to machine construction + Fake Computer Toy"' by EvilDragonfiend at commit 48953205fc](https://www.github.com/beestation/beestation-hornet/pull/10378)

### Describe the bug

When arrived at Dog's Heaven, noticed that all dog treats are ERRORs
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/95033055/66f4ac3b-b7c2-4e42-8d66-1d4ee6327cf6)

### What did you expect?

Dog treats should have their own sprite, instead of ERRORs

### Reproducible steps

1. Go to Dog's Heaven
2. See Dog Treats as ERRORs

**Comment by EvilDragonfiend** [comment]
Map loading might have been scuffed but no idea
