### ISSUE TITLE
[Bug]: agent ID removes numbers from the end of your name

### ISSUE THREAD

**Issue by boombaklops** [BeeStation/BeeStation-Hornet#10401]
### BYOND Version

515.1614

### Round Date

2023/26/12

### Round ID

47110?

### Test merges

- #9124

### Describe the bug

Playing as CMR-4, I used an agent ID to forge a new identity. After a while, I noticed my ID name was "CMR-" instead of my full name. I tried again to forge an identity, but the result was the same.

### What did you expect?

I expect agent IDs to copy your name correctly no matter what it is.

### Reproducible steps

1. Play a character whose name ends in a number.
2. Get an agent ID.
3. Forge an identity.

**Comment by Tsar-Salat** [comment]
Yup, occurs on Comms Agent ID aswell, making copying & imitating AI or IPC names rather difficult

**Comment by boombaklops** [comment]
I found some behavior that might be related to this issue. If you go into character prefs and try to give an organic character a number in their name, the number will be removed.
