### ISSUE TITLE
[Bug]: Clown Mid-Round Traitor Roll Pen Uplink Doesn't Work

### ISSUE THREAD

**Issue by DatBoiTim** [BeeStation/BeeStation-Hornet#10410]
### BYOND Version

514.1589

### Round Date

2023/28/12

### Round ID

47134

### Test merges

- #9124 
- #10404 

### Describe the bug

Have character preference set to Pen Uplink
Spawn as Clown, Non-Traitor
Roll Mid-Round Traitor
Eject Pen(is a crayon)
Use in hand, no way to rotate or access uplink

### What did you expect?

Some way to access my uplink, whether a pen or otherwise.

### Reproducible steps

1. Set Pen Uplink in Char Pref
2. Spawn as Clown, Non-Traitor
3. Become Traitor Mid Round
4. Attempt to Open Uplink

**Comment by St0rmC4st3r** [comment]
On roundstart, there is a pen spawned in your backpack in this configuration. Are you sure it didn't get added?

**Comment by DatBoiTim** [comment]
Nevermind
