### ISSUE TITLE
[Bug]: Invisible Mjolnir

### ISSUE THREAD

**Issue by NotACoderSorry** [BeeStation/BeeStation-Hornet#10435]
### BYOND Version

514.1589

### Round Date

N/A

### Round ID

N/A

### Describe the bug

When weilding Mjolnir, it is invisible

### What did you expect?

I expected to see the damn thing.

### Reproducible steps

Go into test server
Spawn wiz
Wield mjolnir
Results

**Comment by PowerfulBacon** [comment]
I bet this is to do with spelling again
