### ISSUE TITLE
[Bug]: Plasma sells for too high of a price

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#10444]
### Round Date

2024/01/08

### Round ID

47260

### Describe the bug

Plasma's worth has add at least two zeros added to its value, allowing one to get 1M credits from selling 100 sheets.

### What did you expect?

I expected to not be able to get way too much money from a basic resource

### Reproducible steps

1- Get plasma
2- Sell plasma
3- ???

**Comment by Miliviu** [comment]
#10443 It'll be fixed soon! :)

**Comment by Miliviu** [comment]
Aaand this should be closed now @PowerfulBacon
