### ISSUE TITLE
[Bug]: Guns don't spawn with a round chambered anymore

### ISSUE THREAD

**Issue by NotACoderSorry** [BeeStation/BeeStation-Hornet#10440]
### BYOND Version

514.1589

### Round Date

N/A

### Round ID

N/A

### Test merges

Nope

### Describe the bug

Guns don't spawn with a round chambered anymore. This isn't such a problem on it's own, other than being a slight annoyance, BUT it completely breaks the wizard spells Arcane Barrage and Lesser summon guns, since they rely on SPAWNING GUNS THAT CAN'T BE RELOADED.

As a side note, the weapons spawned probably should be exempt from the new draw time system, considering how the spells work, since without it the spells will be pretty fucking useless.

### What did you expect?

I expected the prior behaviour where weapons would spawn with bullets already chambered.

### Reproducible steps

Spawn wiz
Get spells 
Test

**Comment by VickiMorris** [comment]
I'll sit down and work on a fix for the wizard spells today after I run some errands. The change to guns spawning unchambered was deliberate, but this was an oversight on my part, sorry.
