### ISSUE TITLE
[Bug]: Controls got messed up after yesterday

### ISSUE THREAD

**Issue by burn1cycle** [BeeStation/BeeStation-Hornet#10467]
### Round Date

 2024-01-13 14:03:24

### Round ID

47326

### Test merges

How would I know? It worked fine yesterday.

### Describe the bug

Why are my controls messed up? Example: Ctrl+W used to swap hands now it sorta works swapping hands sometimes doesn't and often pops up the right click menu?

### What did you expect?

For my controls to work and not have to do a bunch of debugging of problems first thing in the morning.

### Reproducible steps

Press Ctrl+X I guess.

**Comment by burn1cycle** [comment]
It was Steam's fault. In a 12 hour period it decided it should take over the controller and relay random keybinds to windows. Shutting down Steam fixed it. 

Fuck Gabe Newell up the ass with cactus.

**Comment by Nakalon** [comment]
Please close this then
