### ISSUE TITLE
[Bug]: Hotkeys from controller binds now activate the chat-edit box and BREAK CONTROLS

### ISSUE THREAD

**Issue by burn1cycle** [BeeStation/BeeStation-Hornet#10468]
### Round Date

2024-01-13 

### Round ID

47327

### Test merges

- https://github.com/BeeStation/BeeStation-Hornet/pull/10465

### Describe the bug

 This morning my controls changed to activate the edit box in bottom-right when I press buttons on my controller. I blamed Steam at first but that wasn't the issue. Nothing else has changed on my PC so I blame recent change to controls from this PR

### What did you expect?

Press button on controller and it works

### Reproducible steps

Use a Xbox controller and get kicked over to edit box

**Comment by JixS4v** [comment]
Yeah, byond is notoriously buggy with gamepads. The solution is to keep your gamepad unplugged while you play ss13

**Comment by burn1cycle** [comment]
> Yeah, byond is notoriously buggy with gamepads. The solution is to keep your gamepad unplugged while you play ss13

Alternatively I would suggest not modifying code when you don't understand why it's bugging out and instead try to repair the bug.

**Comment by itsmeow** [comment]
That PR did not change controls that would in any way be relevant.
It has been like that for ages. Gamepads do not work well with BYOND.

Please do not get angry at contributors over something you don't understand. Jix didn't even make the PR in question, nor did I.

Have you tried switching to hotkeys mode (via Tab) and/or adjusting the 'Classic keybinds' game preference?

**Comment by burn1cycle** [comment]
> That PR did not change controls that would in any way be relevant. It has been like that for ages. Gamepads do not work well with BYOND.
> 
> Please do not get angry at contributors over something you don't understand. Jix didn't even make the PR in question, nor did I.
> 
> Have you tried switching to hotkeys mode (via Tab) and/or adjusting the 'Classic keybinds' game preference?

I ended up binding the keys to function keys

**Comment by burn1cycle** [comment]
I regret telling you what I did because it's broken again and I think someone changed something so Function keys are now popping up menus too. I think a coder's intentionally trying to break my controls.

**Comment by JixS4v** [comment]
out of personal curiosity, why do you use a controller?
