### ISSUE TITLE
[Bug]: Changeling beret cannot be removed from head

### ISSUE THREAD

**Issue by Marshmellow105** [BeeStation/BeeStation-Hornet#10462]
### BYOND Version

514.1589

### Round Date

2024/01/13

### Round ID

47319

### Test merges

#9124 
#10166 
#91

### Describe the bug

After picking up what appeared to be a security beret from the ground, I could not drop it, after trying to equip it to my head I could no longer remove it from my person.

### What did you expect?

I expected it to be a normal beret, but I believe it was something to do with a changeling's ability to morph clothes.

### Reproducible steps

I'm not exactly sure how the beret got to the ground, but these are the steps I took.
1. Find beret on ground (from a changeling's shapeshifting ability)
2. Pickup beret
3. Equip beret
4. Cry as you can no longer drop beret

**Comment by Marshmellow105** [comment]
I am positive it wasn't glued, as the original hat was still in possession of its owner, and the one I picked up was dropped by the changeling.

**Comment by Penwin0** [comment]
Typically changeling clothing dissapears after being removed if it didn't then something is certainly wrong
