### ISSUE TITLE
Separated Chemicals Machine Broke

### ISSUE THREAD

**Issue by Sun-Soaked** [BeeStation/BeeStation-Hornet#1047]
## Reproduction:
create a sepchem plant with any type of established chemical reaction, explosive or beneficial. Nothing happens. I confirmed this by creating a trifloride explosive plant(successful detonation) and then producing a similar reaction with florine, chlorine, and pyrosium(No effect barring slippery puddle effect on tile). This has been an issue for a while now and it makes me sad, especially since we originally took a stance on keeping separated chems.

**Comment by yorii** [comment]
This has been fixed, separated chems work as intended.
