### ISSUE TITLE
[Bug]: Can't forcefeed food to other people

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#10477]
### Round Date

2024/01/14

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 347bf8b17f](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10166: 'Ports Genpop from NSV' by Haliris at commit b301829ea8](https://www.github.com/beestation/beestation-hornet/pull/10166)
[#9126: 'Traitor Backstories' by itsmeow at commit 05e8bf5063](https://www.github.com/beestation/beestation-hornet/pull/9126)

### Describe the bug

Basically the other day we had an oozeling that needed some blood and we had some food at hand however any attempts to feed them pizza between three players failed since we would just eat the food ourselves

You can, however, feed medical pills to others so it seems it's related to food-only? think it was worth mentioning

I tried all intents and mouth targeting but nope.

Could be related to #8845 that was fixed on #9875 perhaps? 
edit: nvm #9875 was not merged i didn't see so in theory you're still also with that bug present
### What did you expect?

I expected to be able to feed food to others without eating it myself

### Reproducible steps

1. Have food
2. Attempt to feed it to the other player(i only tested it with some organs and pizza iirc)
3. You eat it yourself instead of them!

**Comment by Tsar-Salat** [comment]
Edible component methinks.

Will look later
