### ISSUE TITLE
Revenant is broken-unfair

### ISSUE THREAD

**Issue by burn1cycle** [BeeStation/BeeStation-Hornet#10480]
### BYOND Version

xxx

### Round Date

xxx

### Round ID

xxx

### Test merges

xxx

### Describe the bug

Most code bases have the revenant forced for manifest for 10 seconds. They're still hard to kill but it's fair from the half-second or less I've noticed that Revenants get to pop out of manifest on Bee Station

### What did you expect?

A fair challenge.

**Comment by ToasterBan** [comment]
this is not a bug, make a feature request instead:
https://github.com/BeeStation/BeeStation-Hornet/issues/new?assignees=&labels=Feature-Request&projects=&template=feature_request.yml&title=%5BNew+Feature%5D%3A+
