### ISSUE TITLE
[Bug]: Genpop turnstiles allow anyone through, in or out

### ISSUE THREAD

**Issue by Marshmellow105** [BeeStation/BeeStation-Hornet#10487]
### BYOND Version

514.1589

### Round Date

2024/01/16

### Round ID

47367

### Test merges

- #9124
- #9126

### Describe the bug

The two turnstiles in the general population prison appeared to be all access, letting anyone (including prisoners) in or out of the prison at will.

For context, this was on Metastation, and was happening since the start of the round.

### What did you expect?

I expected them to work normally

### Reproducible steps

1. Walk up to turnstile as any job
2. Walk through it

**Comment by Haliris** [comment]
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/97298717/ba01f131-d6b2-459f-b724-007737266d9a)
The turnstile appear correct on metastation.

Remember that they allow everyone to go through in the direction the arrow is pointing towards.

So if it's not that, then either the people you witnessed had brig access, or you forgot to mention details that could point towards a bug.

**Comment by Haliris** [comment]
Nvm

https://github.com/BeeStation/BeeStation-Hornet/pull/10494
