### ISSUE TITLE
[Bug]: Laser projectiles freezing upon interacting with blob? Clip attached.

### ISSUE THREAD

**Issue by Haliris** [BeeStation/BeeStation-Hornet#10499]
### BYOND Version

514.1589

### Round Date

2024/01/17

### Round ID

47385

### Test merges

https://github.com/BeeStation/BeeStation-Hornet/pull/9124
https://github.com/BeeStation/BeeStation-Hornet/pull/9126 

### Describe the bug

Blob fight was happening, when suddenly we noticed some laser projectiles were freezing in place, being deleted after some time instead of hitting their expected targets.

I don't know what caused that to happen, nothing particular seems to have happened. It seems it only happened over some turfs, but that could be a red herring.

https://github.com/BeeStation/BeeStation-Hornet/assets/97298717/1ab88856-7673-402f-a030-0d71b14e426f

### What did you expect?

Laser projectiles to pursue their trajectory and hit their target.

### Reproducible steps

Can't give any, don't know what happened and I didn't find any obvious relevant runtimes. I'm throwing this issue out there in case this turns out to be part of a larger problem.

**Comment by Haliris** [comment]
Round ongoing, I sent it too early, I'll post the clip later.

**Comment by DatFrostys** [comment]
I'd like to add that this isn't related to the blob. This is an issue that has been running for a while with probably all ranged weapons. I do not know how to reproduce it either.
This happens with both laser and ballistic weapons.
