### ISSUE TITLE
Beecoin shop angel wings cause moth to lose antennae.

### ISSUE THREAD

**Issue by dulcis2** [BeeStation/BeeStation-Hornet#105]
When you equip new angel wings for moth your sprite loses its antennae. 
Tried doing it on diffrent character slots with diffrent jobs selected.
The issue exist both on character settings screen and in game.

**Comment by MACIEKBAKI** [comment]
@qwertyquerty  bad moth

**Comment by hackerjsimon** [comment]
im surprised you paid attention to the antenna
