### ISSUE TITLE
[Bug]: Detective Office at Box starts depressurized

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#10514]
### Round Date

2024/01/21

### Describe the bug

![Screenshot_15](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/db23362d-1ca6-425d-a1c0-64f91062594d)
(You can see it from the ss13 webmap since it's the map that got pushed live)

### What did you expect?

I expected for detectives to not roundstart suffocate and die of lack of pressure(and anyone that goes to that maint)

### Reproducible steps

Launch Box station

Spawn as detective (or just observe) 

Suffocate and feel your skin being peeled off!

**Comment by JikkaJoestar** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/10515

made a pr to fix.
