### ISSUE TITLE
Tank Dispenser works, even if you are a ghost

### ISSUE THREAD

**Issue by TheGreyDiamond** [BeeStation/BeeStation-Hornet#1054]
Round ID: 10739
Map: MetaStation
Problem: As a ghost, I was able to interact with the Tank dispenser in the escape shuttle. That shouldn't be possible.

**Comment by St0rmC4st3r** [comment]
IMO, we should add some funny ghost interaction back.

**Comment by TheGreyDiamond** [comment]
I checked, it seems to work with every tank dispenser on MetaStation.

**Comment by Kerbin-Fiber** [comment]
Holy shit this actually works

~~Should be a feature~~

**Comment by Kerbin-Fiber** [comment]
![itworks](https://user-images.githubusercontent.com/31713423/71639434-b6cc0680-2c33-11ea-983b-011481747559.gif)

**Comment by TheGreyDiamond** [comment]
The problem seems to still exist, last time I checked it still worked. I will check it today again

**Comment by ivanmixo** [comment]
Fixed.

https://github.com/BeeStation/BeeStation-Hornet/pull/1521
