### ISSUE TITLE
[Bug]: Paraplegic Quirk not working

### ISSUE THREAD

**Issue by MarMauZag** [BeeStation/BeeStation-Hornet#10576]
### Round Date

2024/02/05

### Round ID

47589

### Describe the bug

When I did gave my character paraplegic quirk, I noticed that my character was able to walk. No need for wheelchair
![Zrzut ekranu 2024-02-05 195222](https://github.com/BeeStation/BeeStation-Hornet/assets/91204123/3141b69c-8fc4-4ef4-a26d-d2f74e16d22d)

### What did you expect?

I expected my character legs not working.

### Reproducible steps

1. Create a character with Paraplegic Quirk
2. Join round with said character.
3. Walk around, unbuckle from the wheelchair

**Comment by Tsar-Salat** [comment]
Wow, so the issue that clogged up #10083 is on live?

This makes my life easier lmao, I thought that was an issue with my pr

**Comment by Tsar-Salat** [comment]
https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/fa5a5bbb-aa96-402d-b5fc-4c14728165ce

I cant seem to reproduce on local

Am I missing a step @MarMauZag ?

**Comment by MarMauZag** [comment]
> dreamseeker_sc60OKC103.mp4 
> I cant seem to reproduce on local
> 
> Am I missing a step @MarMauZag ?


https://github.com/BeeStation/BeeStation-Hornet/assets/91204123/640e2b90-fda6-44de-bc6d-c939fff6453e

Yes, you do. You do it on local.

**Comment by MarMauZag** [comment]
Then i don't know what is going on.  I cannot play as wheelchair characters then.

**Comment by MarMauZag** [comment]
![Pic_05](https://github.com/BeeStation/BeeStation-Hornet/assets/91204123/01f2e948-f9fc-4a88-ba5b-32e37b071a78)
![Pic_04](https://github.com/BeeStation/BeeStation-Hornet/assets/91204123/5e560e3b-c6ef-4f74-bad5-50e4d3a8f5f4)
![Pic_03](https://github.com/BeeStation/BeeStation-Hornet/assets/91204123/d2136d5c-4fdf-475a-936d-748caea15e09)
![Pic_02](https://github.com/BeeStation/BeeStation-Hornet/assets/91204123/c78b5206-2307-48a5-b5ff-e9e47577fbba)
![Pic_01](https://github.com/BeeStation/BeeStation-Hornet/assets/91204123/fb6c6593-4419-4691-88e6-0284230c647c)

This is everything, not counting the item shop.
