### ISSUE TITLE
using the body bag heirloom removes the body bag status and leaves with a permanent negative debuff

### ISSUE THREAD

**Issue by TheMaggotGuy** [BeeStation/BeeStation-Hornet#10572]
Issue reported from  Round ID: 47574 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Steps to replicate:

Be paramedic with Heirloom

Unfold heirloom bodybag

(maybe optional) zip and unzip it repeatedly, both with and without yourself inside

Fold heirloom by dragging it back to yourself

Discover you are "missing your family heirloom" despite having it in your backpack, discover it no longer describes itself as heirloom

**Comment by lowwy** [comment]
Same as #9484

**Comment by Rukofamicom** [comment]
duplicate issue
