### ISSUE TITLE
Mindshield implanter looks full even when it's empty

### ISSUE THREAD

**Issue by VictorVow** [BeeStation/BeeStation-Hornet#1058]
## Reproduction:
Get a new Mindshield Crate, implanter looks full. Cue many confused security officers wondering why they can't start implanting anyone. You can still refill it with a mindshield and _then_ start implanting properly, but the implanter icon won't have changed in either state.

**Comment by Kerbin-Fiber** [comment]
I tested this locally and the mindshield implanter worked just fine
