### ISSUE TITLE
"Random Arcade" doesn't actually do anything or work correctly

### ISSUE THREAD

**Issue by TheMaggotGuy** [BeeStation/BeeStation-Hornet#10585]
Issue reported from  Round ID: 47615 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Seen on fland and other maps, will respond again here when I confirm for other maps. Lots of places have "random arcade" which does nothing and has the description " That's a random arcade.
random arcade machine
"

**Comment by Fronsis** [comment]
Yep, can confirm we had #10402 that supposedly solved it but they're still present
