### ISSUE TITLE
[Bug]: Tech-fab output doesn't z-fall

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#10593]
### Describe the bug

The output of a tech-fab doesn't check for z-fall when it is created. (Most things probably don't either to be honest). Maybe we could make it so that when something enters an open space turf it automatically gets checked one?

### What did you expect?

The output of a tech fab should z-fall when it outputs to an open-space turf.

### Reproducible steps

Get an exosuit fabricator and set the output direction to south (assuming that there is an openspace tile to the south).
Output 1 glass.
The glass will not fall.

**Comment by itsmeow** [comment]
There is a subsystem that checks the contents of openspace. It already exists, objects are added to its queue when they call Entered() on the turf.

If something isn't calling Entered() then it won't fall.

**Comment by itsmeow** [comment]
The problem being that Entered() isn't called when something initializes inside a turf. Not much to do there.
