### ISSUE TITLE
[New Feature]: Zombies can break out of cuffs much faster/bite when cuffed

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#10614]
### Describe the feature request

Xenos can instantly break cuffs, and zombies cannot. The new anti-zombie meta is to find anyone with a tumor, cuff them, buckle them, threat completely secured. 

Cryobed was removed because it allowed med to just completely halt a zombie infestation by buckling someone. This is the same but even easier since all you need is 15 cable coil and a chair, and boom, your zombie is unable to infect *anyone*.

Round 47699. Zombie infestation, five people got bitten - Med's reaction ? Cuff them all, buckle them, then remove the festering ooze at a leisurely pace. It's the cheapest possible way of dealing with zombies as it just removes all sense of urgency/danger.

Ideally, zombies should be able to burst out of cuffs/buckles within a second alike xenos, or bite while cuffed like a zombie would - although that'd not fix the issue since they could just be buckled to remove all danger as it'd take 1min for them to be able to move again.

**Comment by JixS4v** [comment]
Totally agree this is an issue, and it should be a simple addition.
