### ISSUE TITLE
[New Feature]: Forced emote should show a flag sign

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#10633]
### Describe the feature request

an emote message shows `※ laughs`
but if it's a forced emote, it should be like `▣ laughs` so that we can notice if it's a forced emote.
Maybe forced speech too?

**Comment by EveLed** [comment]
for forced speech, maybe it could be a verb. so instead of it showing as "player says", it'd be "player blurts out" or something

**Comment by oo7craigmc** [comment]
Wouldn't that defeat the purpose of it somewhat?
Like, an antag could use nanites to force the captain to order the AI to do something and then mute them so they can't belay the order right away.
If the AI can immediately tell that it was forced, they know that the captain didn't really mean it and is being manipulated.

**Comment by EvilDragonfiend** [comment]
> Wouldn't that defeat the purpose of it somewhat? Like, an antag could use nanites to force the captain to order the AI to do something and then mute them so they can't belay the order right away. If the AI can immediately tell that it was forced, they know that the captain didn't really mean it and is being manipulated.

That's not forced speech. It's forced emote.
