### ISSUE TITLE
[Bug]: Stealth implants are no longer stealth.

### ISSUE THREAD

**Issue by XeonMations** [BeeStation/BeeStation-Hornet#10667]
### BYOND Version

514.1589

### Round Date

2024/02/28

### Round ID

----

### Test merges

The test merges here do not matter, issue reproducible on localhost.

### Describe the bug

When you enter a stealth implant's box, the box goes invisible as normal, until you move, where it becomes semi-opaque and never becomes invisible again. I have a feeling this is due to an oversight in @EvilDragonfiend 's #9940 PR.

https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/32538d6d-83b7-43c0-ae7e-df75083e917f

### What did you expect?

I expected the stealth implant box to be fully invisible when not nudged

### Reproducible steps

1. Get a stealth implant
2. Implant yourself
3. Activate the box
4. Once you move, you are no longer invisible.

**Comment by EvilDragonfiend** [comment]
I will check it

**Comment by PowerfulBacon** [comment]
Does it fade to full transparency if you stand still again?

**Comment by EvilDragonfiend** [comment]
I don't get what the hell is going on this one. Every time a stealth box moves, it makes a new vis overlay obj. It really shouldn't happen but I have no idea where this happens. I think it's recently happening since it was fine before.

**Comment by EvilDragonfiend** [comment]
okay I figured. I will make a fix
