### ISSUE TITLE
[Bug]:  Food Cart does not hold food

### ISSUE THREAD

**Issue by ClownMoff** [BeeStation/BeeStation-Hornet#10677]
### BYOND Version

Latest

### Round Date

2024/03/01

### Round ID

47874

### Describe the bug

I can't put food inside the food cart

![imagen](https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/3aee6446-3350-4d13-bda5-bba91db6262d)

### What did you expect?

I expected food to go inside the food cart

### Reproducible steps

Get food
Use it on the cart

**Comment by Tsar-Salat** [comment]
Fixed this in #10332 3 months ago

shouldnt be a problem once merged
