### ISSUE TITLE
[Bug]: Putting the supermatter into a chute seems to make the area surrounding the chute darker.

### ISSUE THREAD

**Issue by Hardly3D** [BeeStation/BeeStation-Hornet#10681]
### BYOND Version

514.1589

### Round Date

Localhost

### Round ID

Localhost

### Test merges

None

### Describe the bug

Putting the SM into the disposals chute (on my case, I used a loop with conveyors) appears to be making the area darker, with the radius getting bigger the more times it goes in.
![dreamseeker_tbemsiJrcn](https://github.com/BeeStation/BeeStation-Hornet/assets/66234359/ccf24186-45f4-4fe1-897a-cccb14418609)

### What did you expect?

The chute not to suddenly start "glowing" the darkness

### Reproducible steps

1. Make a conveyor disposals loop and shove the supermatter (anchored won't work!) in.
2. Watch as the chute gets darker the more times it's shoved in.

**Comment by Tsar-Salat** [comment]
9 outta 10, probably #9438

**Comment by Hardly3D** [comment]
Still a bug by the way
