### ISSUE TITLE
Unable to record recipes using the Chem Dispenser

### ISSUE THREAD

**Issue by Crossedfall** [BeeStation/BeeStation-Hornet#1068]
The "Record" button in chem dispensers do not work. This looks to be a bug with TGUI-Next. Likely resolved by porting: https://github.com/tgstation/tgstation/pull/48095

## Reproduction:

Attempt to record any recipe using the Chem Dispenser.

**Comment by ike709** [comment]
I personally tested this and it worked. Are you sure?

**Comment by bloons3** [comment]
Has not worked for me either

**Comment by ike709** [comment]
Huh. It worked fine during the testmerge, but it does not work now.

@Cenrus Any ideas?

**Comment by VictorVow** [comment]
Does not work for me also. [The PR](https://github.com/tgstation/tgstation/pull/48095) Crossed mentioned hasn't been ported yet, so would be best to start there.

**Comment by qwertyquerty** [comment]
Closed by #1145
