### ISSUE TITLE
[New Feature]: Slowdown should be better communicated to the player.

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#10687]
### Describe the feature request

Sources of slowdown need to be better communicated to players, potentially via a status effect or some other obvious indicator. This is especially true for sources of slowdown that do not have any other obvious indicator in the game world, smoke will already tell you that you are moving slow but being sad or encumbered doesn't have any visual indicator.

**Comment by itsmeow** [comment]
Hunger, too

**Comment by PowerfulBacon** [comment]
This has been completed, hunger is now tied directly to movespeed too.
