### ISSUE TITLE
[Bug]: Mobs have mismatched shadows

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#10693]
### Describe the bug

![Screenshot_12](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/c4cbd386-e06f-43dd-bede-641b66f12862)
![Screenshot_13](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/8743f757-ba2c-4dc0-b094-580f28995440)

As you can see, mobs for some reason appear to overlap their sprites, showing both their dead and alive sprite when exposed to darknes, when you approach to them they appear normal

I've also noticed this bug sometimes when observing, when some explo ruins load a little buggy and have scuffed lights and i believe i experienced a similar one when i was a spider alongside Security/AI cameras also displaying this weird behaviour

We had some discussion with Dakae about what might be causing it https://discord.com/channels/427337870844362753/943311132007997490/1213709588566773780

### What did you expect?

I expected to see the mobs on their correct sprite (in the case of the screenshots i, as a xenomorph, i should've been able to see them dead with my thermal vision

### Reproducible steps

1- Spawn a carp alive on space
2- Spawn as a xenomorph on a dark area
3- Kill the carp outside of the view of the xeno( move the xeno to somewhere else and kill the carp)
4- The carp should appear like the screenshot

Alternative this might also work with a human and thermal vision and with Security cameras/AI eye

**Comment by HowToLoLu** [comment]
It doesn't occur at all with humans, just xenomorphs and perhaps some other player controllable mobs have this issue, and it isn't an exploration zlevel issue.

Additionally direction of the shadow is affected by the atom's direction, looking in the direction it's been pulled or moved notably

Human with thermal vision goggles:

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/d2897317-8895-4122-b39e-5c3293f415d4)

Xenomorph with low night vision set (SEE_MOBS part of their sight by default):
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/ea6f116f-3ceb-41ce-af7d-662d088f8deb)

Same carp, but Buildmode thrown upward:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/a99698bd-2f59-4e3a-92b4-296ea7bbfbb4)

**Comment by Fronsis** [comment]
Interesting.. i think Spiders could have it too

Have you tested with cameras/ai eye? I think if the area was dark it showed the xeno issue

**Comment by HowToLoLu** [comment]
It just got even wierder- it happens for AI as well. but the way I got it to work is what makes it wierd.

I started placing engine floors, which didn't cancel the star lighting, so I manually started placing an area of the type `/area/maintenance`
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/1516faf1-2f1f-402d-86d9-e6425a42ba20)

Which then resulted in this being visible to ghosts too as well as the AI

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/65a93bba-9e8b-4c4c-8f1a-69fa609513c5)


Maybe humans are the only thing with working mob shadows?

**Comment by Fronsis** [comment]
> It just got even wierder- it happens for AI as well. but the way I got it to work is what makes it wierd.
> 
> I started placing engine floors, which didn't cancel the star lighting, so I manually started placing an area of the type `/area/maintenance` ![image](https://private-user-images.githubusercontent.com/22382345/309623910-1516faf1-2f1f-402d-86d9-e6425a42ba20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjUyOTQsIm5iZiI6MTcwOTUyNDk5NCwicGF0aCI6Ii8yMjM4MjM0NS8zMDk2MjM5MTAtMTUxNmZhZjEtMmYxZi00MDJkLTg2ZDktZTY0MjVhNDJiYTIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA0MDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMmM1NmNkNzMxYzRhZjMyZjAwYmU1NmY3Y2RiOTkxYmM5NTkzNDQ4NDg1YTMxZGUxOTk0YzdmNzQxNWI5N2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rYMjyDZYXkUh0Payy5U6zBfYo7NnPHc42nas8aBSIVI)
> 
> Which then resulted in this being visible to ghosts too as well as the AI
> 
> ![image](https://private-user-images.githubusercontent.com/22382345/309624018-65a93bba-9e8b-4c4c-8f1a-69fa609513c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MjUyOTQsIm5iZiI6MTcwOTUyNDk5NCwicGF0aCI6Ii8yMjM4MjM0NS8zMDk2MjQwMTgtNjVhOTNiYmEtOWU4Yi00YzRjLThmMWEtNjlmYTYwOTUxM2M1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA0MDMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczOTUzYzZlZjQ2OWFkMzc4NTVkODA2ZmY2ZThjMWZjOGQ1ZmEzYmViMTRkMGQ2Y2RlZTI5NDExN2ZlZTVjMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sS79okp67WUMktwArd51eXG6Jm_prYcH2iLv5dmIrgI)
> 
> Maybe humans are the only thing with working mob shadows?

That might explain why i recall seeing it on explo, perhaps i was observing an explorer and i remember the map loaded strangely and buggy so the lightning was odd all over the place and spider mob that were dead were buggy like that

**Comment by PowerfulBacon** [comment]
I believe this is a byond issue with the way certain items interact with darkness tiles. You will notice if you have an item in your inventory, then when that inventory tile is above a darkness tile, it will render its original icon rather than the current icon. I have no idea why this happens.

**Comment by Fronsis** [comment]
> I believe this is a byond issue with the way certain items interact with darkness tiles. You will notice if you have an item in your inventory, then when that inventory tile is above a darkness tile, it will render its original icon rather than the current icon. I have no idea why this happens. Edit: actually if it works for ghosts too, then it can't be the byond darkness issue.

I believe i've seen it as ghost.. can't be 100% sure though since it might'vehappened under very specific circumstances

But yeah HowToLuLu explained me it could be caused by BYOND but they still tested some stuff that showed otherwise
