### ISSUE TITLE
[Bug]: Bookshelves not working

### ISSUE THREAD

**Issue by JackieOTheWisp** [BeeStation/BeeStation-Hornet#10709]
### BYOND Version

514.1589

### Round Date

2024-03-06

### Round ID

47930

### Test merges

(Didn't think I had to use this my bad)
#9124 #10652 #10648

### Describe the bug

I interacted with the bookshelf and could not pull any books out

### What did you expect?

I expected to be able to read

### Reproducible steps

1. Try to grab a book from a shelf

**Comment by Tsar-Salat** [comment]
My fault, I'll put a fix up tonight
