### ISSUE TITLE
[Bug]: Changeling Cryogenic Sting // frostoil does next to nothing

### ISSUE THREAD

**Issue by lowwy** [BeeStation/BeeStation-Hornet#10718]
### Round Date

2024-03-07

### Round ID

47942

### Test merges

#9124  #10652  #10648

### Describe the bug

Stinged a human 5 times with Cryogenic Sting.
All that happened was they shivered (frostoil cycle) but no other effects seemed to happen

Might be due to the temperature changes in #9876 

### What did you expect?

For the person to freeze, slow down & take damage.

**Comment by Tsar-Salat** [comment]
The followup PR should fix it. 

Ill look into seeing if I can recreate it on that branch

**Comment by Rukofamicom** [comment]
Frost oil is shown not to work quickly when looking at the code, expecting to take about 50 seconds before a majorly noticeable effect happens (when the shivering starts trying to fire).

**Comment by PowerfulBacon** [comment]
I just played a round and the changeling cryo-sting managed to kill at least 5 people
