### ISSUE TITLE
[Bug]: Unsliceable Pizza

### ISSUE THREAD

**Issue by JackieOTheWisp** [BeeStation/BeeStation-Hornet#10710]
### BYOND Version

514.1589

### Round Date

2024-03-06

### Round ID

47930

### Test merges

#9124 #10652 #10648

### Describe the bug

I couldn't slice the pizza using a hatchet?

### What did you expect?

I expected to cut it into slices

### Reproducible steps

1. Grab a pizza
2. Try to cut it with a hatchet

**Comment by Tsar-Salat** [comment]
IIRC It checks for TOOL_KNIFE, not the sharpness of the weapon used.

**Comment by JackieOTheWisp** [comment]
> IIRC It checks for TOOL_KNIFE, not the sharpness of the weapon used.

It used to do it with any blade, is this part of the food update?

**Comment by Tsar-Salat** [comment]
Yup.

**Comment by JackieOTheWisp** [comment]
My bad then, guess this works as intended.
