### ISSUE TITLE
[Bug]: Runtime in callback.dm,165: Cannot execute /obj/item/voodoo/proc/perform_... (/obj/item/voodoo/proc/perform_voodoo).().

### ISSUE THREAD

**Issue by ToasterBan** [BeeStation/BeeStation-Hornet#10712]
### BYOND Version

514.1598

### Round Date

2024\03\07

### Round ID

N/A

### Test merges

N/A

### Describe the bug

I used a voodoo on a local to test out various methods of force-speech, but instead I got a runtime on the doll with any interaction 

```
proc name: InvokeAsync (/datum/callback/proc/InvokeAsync)
usr: Bluezorua/(Vincent Gibson)
usr.loc: (Research Division (179, 105, 2))
src: /datum/callback (/datum/callback)
call stack:
/datum/callback (/datum/callback): InvokeAsync("chest")
/datum/task (/datum/task): continue with(/datum/callback (/datum/callback))
the wicker doll (/obj/item/voodoo): attack self(Vincent Gibson (/mob/living/carbon/human))
Vincent Gibson (/mob/living/carbon/human): Activate Held Object()
activate_inhand (/datum/keybinding/mob/activate_inhand): down(Bluezorua (/client))
Bluezorua (/client): keyDown("Z")
```

### What did you expect?

for the code to run normally

### Reproducible steps

1. Get a voodoo doll
2. Put an item someone has touched into it
3. Use it inhand to pick someone, anyone
4. Use the voodoo doll inhand, aiming for any body part, using either simplified or specific bodymode targeting

**Comment by Gilgaxx** [comment]
Fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/10922
