### ISSUE TITLE
Explosive rubber ducky is unlogged.

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#10727]
Many explosions are simply not logged at all. All explosions should have mandatory logging of their source.

**Comment by Tsar-Salat** [comment]
True. It would be useful to be able to grab sources, this particular instance didnt even log at all, we just saw that "x exploded at y (FLW)"

For duckys and plushy bombs that require stepping on to detonate, perhaps:

> x was detonated by movement of y(FLW), last touched/thrown by z(FLW)
