### ISSUE TITLE
[Bug]: MMI in a BCI circuit shell will be sent to error room if placed inside a BCI implanter

### ISSUE THREAD

**Issue by aramix273** [BeeStation/BeeStation-Hornet#10748]
### Describe the bug

placed a MMI in a BCI with an integrated circuit with MMI component
so far so good, but when inserted into the BCI implanter machine, the MMI player sees this
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/27755442/58483e61-7603-402a-8830-937d0978a3e4)
a second or so later a runtime occurs and they're sent to error room where they cannot do anything as a MMI
`ADMIN LOG: Guest-X/(Guadalupe Stroh)(?) (FLW) was found to have no .loc with an attached client, if the cause is unknown it would be wise to ask how this was accomplished.
`
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/27755442/c3c8a9e8-9663-4c32-b371-ef549ccdcc0a)

### What did you expect?

I expected the MMI to be properly kept inside the circuit during insertion in a BCI implanter

### Reproducible steps

1. get a brain in a MMI
2. insert a MMI component (needs research) into an integrated circuit
3. print a BCI shell
4. assemble with screwdriver
5. insert integrated circuit into assembled BCI shell
6. insert MMI into BCI shell
7. insert BCI shell in implanter
8. observe MMI player

**Comment by JixS4v** [comment]
My guess is BCIs are stored in nullspace so if you put a brain in it it will shit itself.

**Comment by JixS4v** [comment]
Intuition was right, TG already has a fix for this.
