### ISSUE TITLE
[Bug]: Maintenance pills can be ground in a certain way

### ISSUE THREAD

**Issue by aramix273** [BeeStation/BeeStation-Hornet#10747]
### Describe the bug

when I dropped a maintenance pill into a chemical grinder, it actually destroyed the pill and extracted the reagents inside it, allowing them to be safely and losslessly used

### What did you expect?

I expected the chemical grinders from plumbing to refuse to grind maintenance pills

### Reproducible steps

1. make a plumbing setup consisting of a chemical grinder and an output (such as output gate)
2. if unfamiliar with plumbing, make sure to anchor them
3. walk over chemical grinder (its collision is weird as well) from opposite direction of its pipe
4. drop maintenance pill for it to be ground and reagents inserted into plumbing setup
5. extract reagents obtained like this from the output

**Comment by EvilDragonfiend** [comment]
ah, yeah, fucking plumbing. It's not intended lol
