### ISSUE TITLE
Echo station is prolly not compatible with meteor event

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#10760]
Echo station is prolly not compatible with meteor event
there should be another force roundend event like earthquake or something

**Comment by PowerfulBacon** [comment]
As long as the planetary map variable is set in the config, meteors will always appear on the top layer of the map and fall down from the sky randomly. They just won't do any damage since echo made the top floor indestructable

**Comment by PowerfulBacon** [comment]
yea, you are right. They are not spawning at all.

**Comment by PowerfulBacon** [comment]
Echostation needs
```
"planetary_station": true
```
added to the config.

**Comment by BarteG44** [comment]
this should probably be closed 
![image](https://github.com/user-attachments/assets/3a9085ea-d867-478b-92e9-cbaabc3ad68b)
