### ISSUE TITLE
[Bug]: Corg Grav Gen Runs out of Power at 15 minutes

### ISSUE THREAD

**Issue by Programs-The-Station** [BeeStation/BeeStation-Hornet#10785]
### Describe the bug

The power terminals on the SMES are miswired, leading to the APC discharging rapidly, and losing gravity at the 15 minute mark. Caused by #10624 @ClownMoff 

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/d41a669a-99a6-46d5-8f69-bdf3d7c97c39)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/86da6aa0-588b-4f65-b96e-5aafd8227341)

### What did you expect?

I expected Gravity not to fail after 15 minutes.

### Reproducible steps

1. Load Corg.
2. Wait 15 minutes.
3. Float!

**Comment by ClownMoff** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/10786
