### ISSUE TITLE
Camera gets stuck when moving and attempting to use the nanite chamber during no gravity.

### ISSUE THREAD

**Issue by Lumiwrath** [BeeStation/BeeStation-Hornet#10797]
Issue reported from  Round ID: 48144 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

The camera gets stuck on public nanite chamber and body appears on the otherside of the direction you head towards the nanite chamber. You can move around the body and interact with the surrounding environment but the camera still stays stuck

Steps to reproduce bug
Step 1: make sure the station has no gravity
Step 2: float towards the nanite chamber
step 3: step into the chamber as if you are going to use it 
Step 4: result of bug

Steps to fix bug
Step 1: make sure gravity is back on
Step 2: open and step into the nanite chamber as if you are going to use it 
Step 3: open it and step out

**Comment by HowToLoLu** [comment]
Potentially related to #10220, which is related to #9383, and as such *would've* potentially been fixed in #9531, had that PR not been closed.

Overall issue seems to lie in moveloops never stopping when something enters a non-turf's contents.
