### ISSUE TITLE
MC ticker should report current atmos run level

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#10800]
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/312fba8b-82b1-4288-88d7-e5bfebcf1523)

so that we can track which part we lost

----------

maybe current fire priority level too?

**Comment by PowerfulBacon** [comment]
tbf it doesn't really matter which part we lose, since it will just go back to 1 and continue forward.

**Comment by EvilDragonfiend** [comment]
found that it's nothing wrong here.
