### ISSUE TITLE
[Bug]: You can make regular chairs with plastic sheets

### ISSUE THREAD

**Issue by ClownMoff** [BeeStation/BeeStation-Hornet#10803]
### Round Date

2024/03/28

### Describe the bug

When I used plastic sheets on hand I got the otpion to make a regular chair 

![imagen](https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/35f4dc52-bdc4-4e5e-a2b8-33a3736ec6f2)

![imagen](https://github.com/BeeStation/BeeStation-Hornet/assets/148357670/a51039e8-5054-49e4-a6c8-f6dc4bd255d3)

### What did you expect?

I expected not having regular chairs on plasstic sheets

**Comment by Miliviu** [comment]
Is this still happening? 
I'm trying to replicate it but I get a normal plastic chair

**Comment by Tsar-Salat** [comment]
> Is this still happening?
> 
>  Grabacion.2024-04-06.132107.mp4 
> I'm trying to replicate it but I get a normal plastic chair.

1st crafting option will give you the "plastic chair" located in plastic_recipes list.

2nd crafting option for chair will give you a greyscale chair made of plastic. 

This is normal basemats behavior. It's not ideal, but the system is not fully finished.
