### ISSUE TITLE
[Bug]: Corg Cargo Bay APC is Unwired at Round Start

### ISSUE THREAD

**Issue by Programs-The-Station** [BeeStation/BeeStation-Hornet#10806]
### Round Date

2024/03/28

### Round ID

48175

### Describe the bug

APC on Corg's Cargo Bay is no longer wired at round start.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/deda2f77-50f0-4b77-a967-ae317d306902)

Also, a bit of weird wiring around the maints there.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/4029ed8f-dbdd-45cc-845c-18fcbccc1e0f)
Also, QM office's grilles are not electrified due to missing wire.

Floating air alarm as well.

Probably another one for  #10624 @ClownMoff

### What did you expect?

I expected Cargonia to rise to Power, and not have a Power Failure.

### Reproducible steps

1. Wait.
2. Power Failure.
3. Womp Womp.

**Comment by ClownMoff** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/10807

**Comment by Tsar-Salat** [comment]
> #10807 thanks

link issues in pr bodies so they autoclose please
