### ISSUE TITLE
Old bug of people unable to be cloned after turning into stone even with data stored

### ISSUE THREAD

**Issue by Lumiwrath** [BeeStation/BeeStation-Hornet#10816]
Issue reported from  Round ID: 48209 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Bug information-
We had a geneticist turn into stone from too many genes. They've saved both body and whole genetic data on the cloner. The ability to clone was not available even after killing/breaking their stone statue.

Steps to reproduce bug-
step 1. save your clone data
Step 2. put too many genetic mutations and turn into stone

Additional info-
I've heard from another player that this is a old bug and I believe I have seen this happen about a year or two ago as well.

**Comment by St0rmC4st3r** [comment]
Insufficient data.
Did you put the brain/body in the cloning scanner? 
If yes, it's a bug. 
If not - functions as intended. You can't just clone people out of thin air.
