### ISSUE TITLE
All DB queries are delayed, Player panel is slow to open

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#10836]
Queries are slow because they now have to be queued into a query controller, however instead of queueing them and waiting for the MC to come around, if the number of concurrent queries has not been reached then we should instantly run it and only queue queries when we reach the limit.

Caused by #10243

Symptoms include all cases of warn_execute being unresponsible, as they have to wait for the subsystem to fire before executing which can take up to a second.

**Comment by Miliviu** [comment]
Reverting #10243 could do the trick while a real fix is done?

**Comment by Miliviu** [comment]
Because I have not noticed any performance gains, only the Player Panel issues
Rkv said it was a requirement for a future pr so it really isn't needed rn, right?
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/6f00b202-9c2b-45ac-a74e-658aaf43763c)

**Comment by PowerfulBacon** [comment]
The fix is relatively simple and just a few lines of code, the original code that came from TG was just not done very well.
