### ISSUE TITLE
[Bug]: You don't revive as a zombie if you succumb or #last wordwhisper (The revenge)

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#10847]
### Round Date

2024/05/01 

### Describe the bug

When you succumb by using #lastwords you don't revive, you stay permanently dead and stop healing

Also this is the same as #9994 but it got marked as stale, still present

### What did you expect?

I expected to revive since well, i'm a zombie that keeps regenerating and it kinda sucks that you try to same something to a fellow zombie or someone and by doing the #lastwords you cannot return to your body, as a zombie.

### Reproducible steps

1. Be zombie
2. Get put to hard crit
3. Say #Gootbye   
4. You won't revive and stay dead

**Comment by Miliviu** [comment]
I'm trying to replicate this in local to create a fix, but it doesn't really work?

https://github.com/BeeStation/BeeStation-Hornet/assets/45698448/ba9b0c91-897b-48dd-a807-db4191062523

**Comment by Fronsis** [comment]
> I'm trying to replicate this in local to create a fix, but it doesn't really work?
> 
>  8e089bf7-b1e0-4979-a3a6-b44bb175e7d4.mp4

We already discussed it in discord but just for record keeping i'll post it here: i meant that once you're already zombie if you're put in hard crit and #succumb you never really revive again you stay permanently dead!

**Comment by Fronsis** [comment]
I think it's still around
