### ISSUE TITLE
[Bug]: Combining a steak with a bun while both are in-hand literally creates a nothing burger.

### ISSUE THREAD

**Issue by TheCatbag** [BeeStation/BeeStation-Hornet#10865]
### BYOND Version

515.1634

### Round Date

2024/04/06

### Round ID

48264

### Test merges

#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a
#10811: 'Revolution 2.0: Now the gamemode works' by Miliviu at commit c224c494fc
#10828: 'Reworks the Gang gamemode and adds it to the dynamic pool' by Penwin0 at commit b4cd3f23e2
#10852: 'Client variables to new datum `/datum/client_data` + player panel now reports a disconnected person' by EvilDragonfiend at commit 9618297c92

### Describe the bug

I tried making a burger by combining a bun with a steak in hand, but the two ingredients vanished and nothing was dropped around me. I could recreate this in different areas, so I'm pretty sure something wasn't stealing the burger after it was made.

https://github.com/BeeStation/BeeStation-Hornet/assets/163605445/0c4e153c-781a-42d4-8bc1-50cd8448cf67

### What did you expect?

I expected the burger to either be in hand or on the floor.

### Reproducible steps

1. Cook a Bun and a Steak
2. Put the Bun in one hand and the Steak in another
3. Click one on the other, which would usually make a burger.
4. Observe: no burger.

**Comment by Tsar-Salat** [comment]
Magic trick. 🪄 ✨

I'll look at it. Frankly it could as very well be attack chain BS as it could be custom food bugs.

In the meantime, do it on the table and it shall work.
