### ISSUE TITLE
Custom Vendors Bluescreen

### ISSUE THREAD

**Issue by MatiAvanti** [BeeStation/BeeStation-Hornet#10860]
Issue reported from  Round ID: 48254 (BeeStation Sage - Roleplay)

Reporting client version: 515.1633

"there's a bug with custom vendors making them bluescreen, it says "TypeError: Unable to get property 'amount' of undefined or null reference" with a ton of gobbldygook.
Probably has to do with new vendor ui.
![obraz](https://github.com/BeeStation/BeeStation-Hornet/assets/58709092/42e4d747-9184-4e6a-ab78-603a12b1f5d5)
update:
Steps to replicate:
1.insert anything with a price tag on it.
2.vendor bluescreens.

**Comment by Tsar-Salat** [comment]
Gotcha. I'll look at it
