### ISSUE TITLE
Flowered vines don't show a ghost status alert

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#10881]
Flowered vines don't show an alert to ghosts saying that you can control the mob. They should.

**Comment by Tsar-Salat** [comment]
They use the legacy system instead of the spawners menu. Shitcode.

If anyone is bored, heres an relatively simple port I found a few months ago:
- https://github.com/tgstation/tgstation/pull/67418

**Comment by Tsar-Salat** [comment]
Also, technically duplicate issue of #10644
