### ISSUE TITLE
Players not joining roundstart is becoming a serious issue

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#10880]
We have rounds with 31 players and only 10 players ready up. This means that we can only ever run traitor. Players have these behaviours because they want to know what roles are filled before selecting their job, I think.

We need to figure out something to do about this

**Comment by DrDuckedGoose** [comment]
> Players have these behaviours because they want to know what roles are filled before selecting their job, I think.

Is there something wrong with this behaviour? If not, would we considering delaying antag stuff calculating until 5 mins after the round starts?

**Comment by ToasterBan** [comment]
could port something akin to:
https://github.com/DaedalusDock/daedalusdock/pull/377

**Comment by HowToLoLu** [comment]
> Couldn't we simply show the roles other people are ready'd up for in the "Select your job" screen?

I mean; maybe. 180 seconds is a short time to give people to reconfigure things, and even then some might still wait regardless so they don't have to open mess with their job settings

> I dont know if that port is what i just said above, saying there's a lack of testing evidence...

It is, though note such a system can't account for medium roles because it relies on RNG which isn't viable in calculations for precise statistics like this.

**Comment by ToasterBan** [comment]
> Couldn't we simply show the roles other people are ready'd up for in the "Select your job" screen?
> 
> > could port something akin to: [DaedalusDock/daedalusdock#377](https://github.com/DaedalusDock/daedalusdock/pull/377)
> 
> I dont know if that port is what i just said above, saying there's a lack of testing evidence...

Its shown in the status section, it checks your highest set job and has that as the estimate
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/54711687/7e564266-f2aa-4dbe-849f-f2e9088f26c3)

**Comment by HowToLoLu** [comment]
What if we started adding threat as players join, using a random multiplier determined at roundstart which adds to the budget as players pile in over time, also applying that to those who are already readied up when the round is started so there's a consistent increase in budget per player.

The multiplier itself could also possibly be tweaked throughout the round if you want a less linear amount of threat per player joined.

**Comment by PowerfulBacon** [comment]
Not as big of an issue anymore, now that I lowered the limits for the gamemodes a little.
