### ISSUE TITLE
[Bug]: random ghosting as soul shard

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#10895]
### Round Date

2024/04/16

### Round ID

48352

### Test merges

#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a
#10811: 'Revolution 2.0: Now the gamemode works' by Miliviu at commit c224c494fc

### Describe the bug

Got attacked by a blood cultist janitor who proceeds to turn me into a soul shard, instead of putting into a construct I randomly disappeared and ghosted on the cultist's hands.

### What did you expect?

Never seen this before but it should be as easy as putting the shard on the construct right?

**Comment by EvilDragonfiend** [comment]
when you say 'ghosted', do you mean ingame red cult ghost or an observer ghost?

**Comment by tontyGH** [comment]
Oh no.

**Comment by SlowHorsey** [comment]
well, I was the janitor. I just posted about this same issue from my perspective, and now I see the soulstone reported it too! I guess I should close my post then?
