### ISSUE TITLE
[New Feature]: Spawners menu should be a HUD element for observers

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#10891]
### Describe the feature request

Why is spawners hidden away in the stat panel. It should be a button on the HUD for observers, with an immediate visual tell if there are available spawns or not.

**Comment by Gilgaxx** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/11091 has been merged so this can be closed!
