### ISSUE TITLE
[Bug]: No icon for Paradox bag. 

### ISSUE THREAD

**Issue by lowwy** [BeeStation/BeeStation-Hornet#10910]
### Round Date

2024-04-24

### Describe the bug

No icon for Paradox bag. it does have the sprite.

![Screenshot 2024-04-21 002156](https://github.com/BeeStation/BeeStation-Hornet/assets/8070319/71871c44-8f70-4580-af62-3cd03838a6a7)

### What did you expect?

I expected icons

**Comment by Tsar-Salat** [comment]
Fixed by #10869

**Comment by lowwy** [comment]
fixed in #10869
