### ISSUE TITLE
[Bug]: Nuking the syndicate base nukes everyone on the station instead

### ISSUE THREAD

**Issue by Hardly3D** [BeeStation/BeeStation-Hornet#10931]
### BYOND Version

515.1636

### Round Date

2024/5/1

### Round ID

48506

### Describe the bug

A HoS tried to nuke the syndicate station, only for it to nuke the station and kill everyone on the z-level instead.

### What did you expect?

I expected the nuke to nuke Centcom z-level instead, alongside probably ending the round with the humiliating end

### Reproducible steps

1. Arm the nuke in syndicate base
2. Go to station
3. Get gibbed as soon as it detonates

**Comment by Hardly3D** [comment]
Duplicate of https://github.com/BeeStation/BeeStation-Hornet/issues/9904 but seems like that one went stale

**Comment by Fronsis** [comment]
It got marked as Stale because funny bot but the bug is still present

**Comment by Tsar-Salat** [comment]
TBH, I think this is actually from dynamic changes in the last 2 years, we just havent had this particular event happen in a long time, so it wasnt found. 

We have a lot of duplicate references as we are using dynamic fulltime, but are reliant on some old gamemode procs and vars.

I will look at it a bit, see if I can find whatever var needs to be pulled off gamemode code and made global

**Comment by Hardly3D** [comment]
Guhhhhhhhhh
