### ISSUE TITLE
[Bug]: Bandana (headgear) and Bandana Neckerchiefs have missing textures

### ISSUE THREAD

**Issue by SpagootyEggant** [BeeStation/BeeStation-Hornet#10959]
### Round Date

2024/05/24

### Round ID

48618

### Test merges

[#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10811: 'Revolution 2.0: Now the gamemode works' by Miliviu at commit c224c494fc](https://www.github.com/beestation/beestation-hornet/pull/10811)
[#10912: 'Temp Revert "Updates the hub entry"' by Crossedfall at commit 2268617730](https://www.github.com/beestation/beestation-hornet/pull/10912)

### Describe the bug

Wearing bandanas on your head or around your neck results in them losing their texture, displaying as the pink/black squares. Additionally they change shapes, appearing as textureless ushankas (?) and worn bedsheets.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82246512/163b26d1-0da9-412d-8cdc-d0666e2f33c8)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82246512/00ac61d0-17cd-44f0-ac9d-2769f6b1bbf9)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82246512/0b0611f9-9a6b-4ab8-bdfc-aa6a5973c12d)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82246512/fe11d6ea-f9a5-402e-9dbb-7b27cdc712a6)
(Sorry about the poor lighting that's my ethereal glow)

### What did you expect?

Expected for the regular bandana headwear sprite to show up. This is pretty funny, though, ngl.

### Reproducible steps

1. Obtain bandana (colour probably doesn't matter, confirmed bug with gold, black, and green)
2. Use in hand or alt-click to turn into headgear/neckerchief
3. Equip to appropriate slot
4. Enjoy your missing textures

**Comment by Tsar-Salat** [comment]
Yea, this is because of the shitcode associated with putting a mask item in the head slot.

I'll have a brute force fix up soon

**Comment by JukeJukestar** [comment]
Still a problem. Weird! They used to work a few months ago

**Comment by Tsar-Salat** [comment]
@PatienceStPim Link issues in prs to close them please
