### ISSUE TITLE
[Bug]: Revenant dust form has invisible sprite.

### ISSUE THREAD

**Issue by FriendlyIsisMember** [BeeStation/BeeStation-Hornet#10956]
### BYOND Version

514.1589

### Round Date

-

### Round ID

-

### Test merges

[9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10811: 'Revolution 2.0: Now the gamemode works' by Miliviu at commit c224c494fc](https://www.github.com/beestation/beestation-hornet/pull/10811)
[#10912: 'Temp Revert "Updates the hub entry"' by Crossedfall at commit 2268617730](https://www.github.com/beestation/beestation-hornet/pull/10912)

### Describe the bug

When a revenant is killed the glitter dust that is dropped is missing its sprite and is invisible. You can only detect it if you inspect the tile by right clicking on it to see what items are on the tile.

### What did you expect?

The item is missing a sprite and is supposed to have its original purple dust sprite I believe?

### Reproducible steps

1. Kill the revenant
2. Check if the dust is visible or not.

**Comment by Tsar-Salat** [comment]
fixed in #10869
