### ISSUE TITLE
[Bug]: Moths with Paraplegic trait can stand

### ISSUE THREAD

**Issue by Ragantis** [BeeStation/BeeStation-Hornet#10961]
### BYOND Version

515.1633

### Round Date

05/13/2024

### Round ID

48622

### Test merges

-#9124 -#10811 -#10912

### Describe the bug

When I did Unbuckle, I noticed I could stand
![Wheelchairmoth](https://github.com/BeeStation/BeeStation-Hornet/assets/147216725/0fa564a8-4564-4652-9c22-fad965e24ff2)

### What did you expect?

I expected to fall like a normal paraplegic character

### Reproducible steps

1. Click unbuckle or click wheelchair

**Comment by Tsar-Salat** [comment]
Hmmm, seems be similiar to #10576 ?

**Comment by Tsar-Salat** [comment]
Pre-mobility refactor. Unable to reproduce in live. This should be fixed now.
