### ISSUE TITLE
[Bug]: Cannot Throw/Store into bags Poppies

### ISSUE THREAD

**Issue by FriendlyIsisMember** [BeeStation/BeeStation-Hornet#10962]
### BYOND Version

514.1589

### Round Date

2024\05\13

### Round ID

48627

### Test merges

#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a
#10811: 'Revolution 2.0: Now the gamemode works' by Miliviu at commit c224c494fc
#10912: 'Temp Revert "Updates the hub entry"' by Crossedfall at commit 2268617730

### Describe the bug

Trying to put poppies into a bag does nothing except keeps them in your hand. No announcement is given nothing. Also throwing them does work not either.

I did not try this with other flowers,.

### What did you expect?

They were to be more functional, rather than plain block of nothing.

### Reproducible steps

1. Pick up a poppy
2. Try putting it in your bag
or
3. Throw them.

**Comment by Fronsis** [comment]
Aye, i reported this yesterday on the discord, there's an issue with other plants and pets too but i don't think it's exactly the same
