### ISSUE TITLE
[Bug]: Cannot put Pets in bagpack (IMPORTANT)

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#10963]
### Describe the bug

Basically you're unable to put pets/animals on a bagpack, according to @Tsar-Salat it's because they have a flag of ABSTRACT, making the issue so it's recorded

### What did you expect?

I expected to be able to secure the loyal pet into my Bagpack to protect them from threats and take them to CC 

### Reproducible steps

1. Pick Runtime/Walter/Ian/Corgi/Kalo/Ect
2. Try to put it on your bag
3. You can't!!!!

**Comment by BlueHNT** [comment]
I think it's more normal if you can't?

**Comment by Fronsis** [comment]
> I think it's more normal if you can't?

Nope, you were always able to put Cats, dogs, mouses, Kalo and others in your bagpack as long as you had space 

A lot of people are suffering from this.. they can't save Ian/Walter/Runtime/their precious pet!!!
