### ISSUE TITLE
[Bug]: Ion Gun and Ion Carabine lights don't work properly

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#10974]
### Describe the bug

Ion gun and Ion Carabine don't have a proper light effect and they look as if they were discharged
![Screenshot_79 (1)](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/058c74bf-8af0-4a60-8dc4-f47f4d557931)

I've been told this might've been caused by #10804 but @Tsar-Salat got it figured it out, just posting so it doesn't get lost, might be worth checking the other weapons work too (specially the one from research like the Beam or advanced e-gun) if it was a small oversight

### What did you expect?

I expected bright light when fully charged and usual behaviour of energy-based guns!

### Reproducible steps

1. Pick the ion gun from armory
2. Observe it...

Or

1. Print an Ion Carabine
2. Observe it..

**Comment by Tsar-Salat** [comment]
`shaded_charge = TRUE` should be removed. That fixed it during testing
