### ISSUE TITLE
[Bug]: Doctor's bag sprite shows as a baguette

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#10981]
### Describe the bug

Doctor's bag on waist shows the baguette sprite
![image (1)](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/06d505e3-5a40-48fe-9f84-c7324e4bcee9)

### What did you expect?

I expected to see the doctor's bag sprite!

### Reproducible steps

1. Spawn as CMO/Doctor
2. Your sprite on the doctor's bag is a baguette
3. Profit!

**Comment by Tsar-Salat** [comment]
> doctor's bag sprite

No such sprite exists. This is why the baguette appears.
