### ISSUE TITLE
[New Feature]: Species Specific Traitor Items

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#10984]
### Describe the feature request

I'd like it if we had more species specific traitor items. Here are some random ideas I had.

- **IPC (8TC):** Station network infiltration module, it would allow you to preform cyborg actions of opening, locking and shocking doors remotely or next to you.
- **Plasmaman  (6TC):** Auto-flamethrower, it's a flamethrower which uses your own plasma to spew out flame!
- **Plasmaman (4TC):** Plasma friend, a syringe with a plasma mutation toxin. Now you can have your own plasma friend!
- **Moth (5-10TC):** Iron wings, makes you take less damage when activated but move slower. It also makes you immune to having your wings burnt and grants you additional melee damage when you're without a weapon.
- **Moth (2TC):** Self regenerating, a piece of cloth or clothing which regenerates after you've eaten it.
- **Felinds (1TC):** Don't Bully Shirt, a shirt politely asks other crew members to not bully them. Is actually highly illegal under Space Law to have it in possession. (And it does not make other crew members bully you less.)
- **Human (1 TC):** One Human law board, it is just a normal one human law board which any human can then buy and trick cyborgs into opening up for them. 
- **Apids ():** 
- **Oozlings ():** 
- **Psyphoza (2TC):** Drug bag, it's just a 200u bag of drugs (IV-stand not included). lol

**Comment by PowerfulBacon** [comment]
Bring back #1746

**Comment by MarkusLarsson421** [comment]
> Bring back #1746

I was just talking about that PR not long ago and it is mostly why I made this list. lol
