### ISSUE TITLE
[Bug]: Failed TGUI say box loading.

### ISSUE THREAD

**Issue by XeonMations** [BeeStation/BeeStation-Hornet#10995]
### BYOND Version

514.1589

### Round Date

2023/05/23

### Round ID

48731

### Test merges

- #9124 
- #10372 
- #10990  (This issue was happening before this PR was in effect.)

### Describe the bug

When I join the server, sometimes the chat TGUI box fails to load and I have to rejoin to fix the issue. If I Alt+F4 the chatbox, i am unable to reopen it via pressing T, or O, or any other button that would normally reeopen it, until I reconnect.

### What did you expect?

I expected for the chatbox to work correctly.

### Reproducible steps

1. Join the game
2.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/b6f00443-3108-44e9-9bb2-fe50ec329c50)

**Comment by MarkusLarsson421** [comment]
This has happened to me a few times too, no idea what causes it. :/
