### ISSUE TITLE
books not working

### ISSUE THREAD

**Issue by denden117** [BeeStation/BeeStation-Hornet#11007]
Issue reported from  Round ID: 48757 (BeeStation Sage - Roleplay)

Reporting client version: 515.1637

when trying to opne some books (chemistry, bartender drinks) it pulls up a Ntos website

![Screenshot 2024-05-25 142231](https://github.com/BeeStation/BeeStation-Hornet/assets/55523789/3d99bc55-f246-415d-af36-f460daab85b8)

**Comment by Tsar-Salat** [comment]
fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/11578
