### ISSUE TITLE
Skeleton access should depend on job fufillment

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#11003]
Skeleton access should work like "If there is no QM, then the cargo techies get QM access", rather than based on simply pop alone.

**Comment by Fronsis** [comment]
I imagine this would still only be for low-pop shifts. I guess cargo tech getting QM is fine, same for an Officer/Warden getting HoS but in this way it certainly by-passes HoP/Acting Captain interactions(Usually in lowpop you have one Head) and any other job like MD having CMO access, Scientist having RD's , Engineers getting CE's, etcetera would be far too easy if they happen to roll antag and we already know lowpop is very.. bleh with a lot of either rush-objectives of stealth gameplay.

**Comment by MarkusLarsson421** [comment]
Perhaps having a Head of Staff in the related department should stop any changes from happening as they can then simply poke their boss for access. While having a dedicated HoP would prevent ANY changes as they should then ask them.

**Comment by MarkusLarsson421** [comment]
> MD having CMO access, Scientist having RD's , Engineers getting CE's, etcetera would be far too easy if they happen to roll antag 

I don't think that's what Bacon meant.
