### ISSUE TITLE
Rubbershot does the level of bleeding I'd expect from a lethal bullet.

### ISSUE THREAD

**Issue by NotACoderSorry** [BeeStation/BeeStation-Hornet#11002]
Issue reported from  Round ID: 48739 (BeeStation Sage - Roleplay)

Reporting client version: 515.1630

**Comment by EvilDragonfiend** [comment]
@PowerfulBacon

**Comment by PowerfulBacon** [comment]
Fixed in 82811c179d2dc12f7e2785226de28911962b918c
