### ISSUE TITLE
[Bug]: Durand shield blocks projectiles from all angles

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11038]
### BYOND Version

515.1614

### Round Date

02/06/2024

### Round ID

48844

### Test merges

[#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10372: 'Updates bleeding' by PowerfulBacon at commit dc744a7d64](https://www.github.com/beestation/beestation-hornet/pull/10372)
[#10990: 'Shielded suit rework' by PowerfulBacon at commit 18ac3749e9](https://www.github.com/beestation/beestation-hornet/pull/10990)

### Describe the bug

When I was being attacked by one Xenomorph Queen and four Drones, I noticed that I took next to no integrity damage on my Durand with its shield up. Additionally, I believe the shield blocked acid projectiles shot from behind it.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/00cdae62-843b-4f74-9712-308096537dd8)

### What did you expect?

I expected for it tank a lot of damage BUT NOT THAT MUCH!

**Comment by Tsar-Salat** [comment]
I think #10989 may be the cause.

**Comment by MarkusLarsson421** [comment]
Until it is patched I think Durand should be disabled as it would just be an automatic win no matter what. I've had people in-game after this ask me to make a Durand (for the purpose of going on a rampage) and it just shouldn't be done in its current state. Perhaps this is worth poking @PowerfulBacon?

**Comment by PowerfulBacon** [comment]
> I think #10989 may be the cause.
> 
> ![image](https://private-user-images.githubusercontent.com/62388554/335892752-bae7e7a0-39c3-44b1-836c-500e5c09733c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MTM0NDAsIm5iZiI6MTcxNzQxMzE0MCwicGF0aCI6Ii82MjM4ODU1NC8zMzU4OTI3NTItYmFlN2U3YTAtMzljMy00NGIxLTgzNmMtNTAwZTVjMDk3MzNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDExMTIyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMTZiYWE4NTBkZWNlYTE0YTJmNzYzOTUxOGI3M2M3MjY3NGU0MzY1MjQ2NzIwNTQ4M2Y2NTc2ZDcwMTIxODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r8eU4q8NS5rb2JuyH6leVycVHFsKDD9z96LCCpD91fI)

This change is a signature change and shouldn't have any effect on behaviour unless these variables redefine a local variable

**Comment by PowerfulBacon** [comment]
The source of projectile issues is line 71-73 of durand.dm, prehit() incorrectly assumes that projectiles will impact something before moving however this is not the case, projectiles are on the tile when they perform hits which means the projectile will always impact the durand from the durand's own tile.
