### ISSUE TITLE
[Bug]: Book Cases cannot be opened.

### ISSUE THREAD

**Issue by SirNoobsworth** [BeeStation/BeeStation-Hornet#11035]
### Round Date

2024/05/31

### Round ID

48826

### Describe the bug

When I attempt to open a book case, I noticed that no menu opens to remove books.

### What did you expect?

I expected to open the contents menu that lists the books on the shelf and allows you to remove them.

### Reproducible steps

Attempt to open a book case.

**Comment by Tsar-Salat** [comment]
fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/11311
