### ISSUE TITLE
blood demon (and tickle demon) don't spread blood

### ISSUE THREAD

**Issue by BlueHNT** [BeeStation/BeeStation-Hornet#11036]
Issue reported from  Round ID: 48841 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

With the bleeding rework both tickle and blood demon don't seem to spread blood around at all. Their punches don't bleed even though they should splatter and cause hefty amount of bleeding.

Issue caused by: #10372

**Comment by PowerfulBacon** [comment]
This might actually be an older issue
