### ISSUE TITLE
[Bug]: Piggybacking appears to be broken

### ISSUE THREAD

**Issue by Hardly3D** [BeeStation/BeeStation-Hornet#11033]
### BYOND Version

515.1636

### Describe the bug

Trying to piggyback someone immediately results in a fail message

### What did you expect?

I expected to be able to piggyback

### Reproducible steps

1. Aggro grab or be aggro grabbed
2. Have them try to climb up by dragging themselves to you in grab intent
3. The progress bar will show for a split second before it says that they failed to climb up

**Comment by tontyGH** [comment]
Caused by #10926
