### ISSUE TITLE
Remove nanite mindshield

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#11058]
It's just simply unfair, especially when paired with the automatic spreading.

**Comment by NormalAnomaly** [comment]
Isn't the only automatic spreading program locked behind alien technology, and the other trigger based spreading program that is less powerful is locked behind illegal tech?

**Comment by MarkusLarsson421** [comment]
The biggest spreading program is the Public Nanite Machines.
