### ISSUE TITLE
[New Feature]: Remove tactical crawling

### ISSUE THREAD

**Issue by Hardly3D** [BeeStation/BeeStation-Hornet#11061]
### Describe the feature request

Most of the ranged combat I see often devolves into both sides abusing rest to avoid getting hit by projectiles which is cheesy and quite stupid since they can still do it as they shoot. People should make use of their environment or dodge like Touhou players to avoid getting shot.

My suggestion is to make it so shooting at harm intent will also hit people who are also crawling, while ignoring on help; https://github.com/tgstation/tgstation/pull/61552

**Comment by MarkusLarsson421** [comment]
I'd almost say that shooting whilst laying down should have significantly worse accuracy.
