### ISSUE TITLE
[Bug]: Rust heretic's mark seems to prime flashbangs (and maybe grenades?)

### ISSUE THREAD

**Issue by Hardly3D** [BeeStation/BeeStation-Hornet#11073]
### BYOND Version

515.1636

### Round Date

2024/6/12

### Round ID

48959

### Describe the bug

One thing I experienced (not in linked round ID) and watched (linked in round ID) happen is that upon applying the mark of rust into an officer, it seems to have a chance to immediately prime the flashbangs inside their belt/bag, resulting in a stun if the heretic is not protected or have some sort of eye/ear weakness. This seems unintended as it also backfires onto the heretic itself. This might work with chem grenades too but I may be mistaken.

### What did you expect?

I expected it not to not detonate

### Reproducible steps

1. Be rust heretic
2. Have Mark of Rust learned
3. Apply Mark of Rust on a security officer or someone holding flashbangs
4. Get stunned

**Comment by MarkusLarsson421** [comment]
Do they need to hold the flashbang or just have it in their inventory?

**Comment by lowwy** [comment]
> This might work with chem grenades too but I may be mistaken.

This works on all chem grenades (and explosives too I think, but those are more devastating)

> Do they need to hold the flashbang or just have it in their inventory?

In inventory,  because Rust damages items worn & carried and basically kills the grenades making them go bang.


I thought this was as intended actually.
