### ISSUE TITLE
[New Feature]: Digitigrade Lizard Toe Stub removal

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#11082]
### Describe the feature request

Alright, this may be controversial, but : 

Digitigrade feet should *not* get random table toe stub. They're lizard feet, made of pure scales, they should *not* just get hardstunned every so often by pure RNG. Getting fucked by shards on the ground is 100% fair and fitting, but the toe stub is just annoying & makes no sense IMO. They don't even toes, just big ass claws covered in scales !

Please, can it be removed? It's definitely not a fun mechanic IMO.

**Comment by mystery3525** [comment]
They stub their toes because they aren't wearing shoes, not because they are digitigrade:
https://github.com/BeeStation/BeeStation-Hornet/blob/80c782aca0a79468384795d5e4c375d539b5acaa/code/game/objects/structures/tables_racks.dm#L55C7-L57

**Comment by Tsar-Salat** [comment]
> Please, can it be removed? It's definitely not a fun mechanic IMO.

Theres no natural tables on lavaland. The digitigrade is adapted for that environment for ashwalkers. Of course the digitigrade isnt going to be optimal for the station, lizards are a relatively recently uplifted race

**Comment by Howluinb** [comment]
Right, if the (in my opinion valid) excuse of "Their feet are completely hardened, they shouldn't be bothered by an inconvenience that only exists because human feet are soft and very pliable"

Then let me put this another way : 

It's so goddamn annoying. This mechanic is a purely RNG hardstun that serves no purpose beyond being an inconvenience that plagues any digitigrade. There is NO counter to it, there is no way to avoid this RNG check whatsoever. 
This is a feature unique to Digitigrade lizards. No other race has to deal with pure RNG annoyance. Every single one of their problems can be dealt with through proper planning and precautions, but digitigrade ? 
Not at all. This is why this mechanic is absolutely terrible on lizards, and I dare you guys to play a role like chef surrounded by tables without wanting to scream IRL at being hardstunned out of nowhere.
On the other hand, shard hardstun ? That's unique, fun & **PREVENTABLE**. If you pay attention to the floor and watch out where you stand, you will be able to avoid it entirely.
