### ISSUE TITLE
Security Record UX

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#11095]
- If you add a crime before arresting someone, it will be added again when the prison manager console adds the crime.
- If you are dragging someone, it would be helpful if there was a way to automatically fill out their name.
- Remove the comments section, they are hidden away and missed and it is ambiguous when people set crimes vs set comments.
- When you enter the name on the prisoner management interface, it should show their record somewhere and ask if the crime needs to be added
- Tabify the prisoner management vs the prisoner main interface, rather than have a big scroll menu
- It would be nice if there was a system to request arrest warrants which can have evidence or reasoning attached to it, rather than just setting them to arrest. Less people should come into brig with no crimes attached to their record, causing confusion. CM has a very nice system where you add evidence to security records, and witnesses when you mark someone to arrest.

**Comment by Tsar-Salat** [comment]
![213950290-af6cfd76-eb8b-48e9-b792-925949311d9a](https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/1e0fd1bf-fb36-4115-b56e-be81565fa671)

**Comment by Fronsis** [comment]
> ![213950290-af6cfd76-eb8b-48e9-b792-925949311d9a](https://private-user-images.githubusercontent.com/62388554/341172960-1e0fd1bf-fb36-4115-b56e-be81565fa671.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTgyMTIsIm5iZiI6MTcxOTQ1NzkxMiwicGF0aCI6Ii82MjM4ODU1NC8zNDExNzI5NjAtMWUwZmQxYmYtZmIzNi00MTE1LWI1NmUtYmU4MTU2NWZhNjcxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAzMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZjViZjIwODVhNjUyZjQxY2FlNzQ0MjFlY2Y5NDQ3NGMxOTY5MjUyMzI0ZTM0NTdlMjYyZmMxMjhiYjAxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4tMJ2ss49gUnvDF9EKDS0VLyvpgFBTdM4Bpu07UpXsY) [ ![213950290-af6cfd76-eb8b-48e9-b792-925949311d9a](https://private-user-images.githubusercontent.com/62388554/341172960-1e0fd1bf-fb36-4115-b56e-be81565fa671.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTgyMTIsIm5iZiI6MTcxOTQ1NzkxMiwicGF0aCI6Ii82MjM4ODU1NC8zNDExNzI5NjAtMWUwZmQxYmYtZmIzNi00MTE1LWI1NmUtYmU4MTU2NWZhNjcxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAzMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZjViZjIwODVhNjUyZjQxY2FlNzQ0MjFlY2Y5NDQ3NGMxOTY5MjUyMzI0ZTM0NTdlMjYyZmMxMjhiYjAxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4tMJ2ss49gUnvDF9EKDS0VLyvpgFBTdM4Bpu07UpXsY) ](https://private-user-images.githubusercontent.com/62388554/341172960-1e0fd1bf-fb36-4115-b56e-be81565fa671.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTgyMTIsIm5iZiI6MTcxOTQ1NzkxMiwicGF0aCI6Ii82MjM4ODU1NC8zNDExNzI5NjAtMWUwZmQxYmYtZmIzNi00MTE1LWI1NmUtYmU4MTU2NWZhNjcxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAzMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZjViZjIwODVhNjUyZjQxY2FlNzQ0MjFlY2Y5NDQ3NGMxOTY5MjUyMzI0ZTM0NTdlMjYyZmMxMjhiYjAxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4tMJ2ss49gUnvDF9EKDS0VLyvpgFBTdM4Bpu07UpXsY) [ ](https://private-user-images.githubusercontent.com/62388554/341172960-1e0fd1bf-fb36-4115-b56e-be81565fa671.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTgyMTIsIm5iZiI6MTcxOTQ1NzkxMiwicGF0aCI6Ii82MjM4ODU1NC8zNDExNzI5NjAtMWUwZmQxYmYtZmIzNi00MTE1LWI1NmUtYmU4MTU2NWZhNjcxLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAzMTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZjViZjIwODVhNjUyZjQxY2FlNzQ0MjFlY2Y5NDQ3NGMxOTY5MjUyMzI0ZTM0NTdlMjYyZmMxMjhiYjAxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4tMJ2ss49gUnvDF9EKDS0VLyvpgFBTdM4Bpu07UpXsY)

PLEASE (though my only nitpick is that you can't really describe them if they roundstart wear a helmet or face-covering stuff) but PLEASE AAAAAAA
