### ISSUE TITLE
Holoparasites are just completely broken

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#11096]
- They can't move with 1 range (despite a border indicating that move should be possible)
- They can't recall and are always forced to be visible

The second issue is completely debilitating and makes them unusable.

**Comment by PowerfulBacon** [comment]
Still an issue

**Comment by aramix273** [comment]
I'm not sure that range 1 holoparasites were ever able to move, current code indicates that they should always be attached to their master (``holoparasite_helpers.dm:35, is_attached_to_summoner()``)
however, the recall part indeed seems like a bug and I've been able to patch it by moving the check to Move proc and not to attachment check
should the patch also include the first point? would you prefer that they are able to move within said range or that there's no barrier displayed at all in that case?
