### ISSUE TITLE
[Bug]: Missing texture of blue bandana when used as a neck accessory 

### ISSUE THREAD

**Issue by AngryOldAZ** [BeeStation/BeeStation-Hornet#11108]
### Round Date

2024/06/21

### Round ID

49062

### Describe the bug

![image_2024-06-21_205604890](https://github.com/BeeStation/BeeStation-Hornet/assets/108103667/ca3bef7a-fd55-4e84-927e-2a04d3532833)
Blue bandana when worn on the neck looks like this

### What did you expect?

I did not expect a missing texture cape, thats for sure.

### Reproducible steps

Wear the bandana in its alt style

**Comment by Tsar-Salat** [comment]
fixed in the mentioned pr
