### ISSUE TITLE
Revenant orbiting is broken, doesn't set you out of orbit when you step away

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#11147]
When you orbit someone, your orbit status becomes you're orbiting them
and then when you move away from them, your orbit status should be null, but it's still orbiting you
and that makes you not able to orbit anyone.
It looks movement is bugged somehow

# TMs
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/f195fae1-213d-403f-922f-28491774205c)

**Comment by EvilDragonfiend** [comment]
can't reproduce the bug. not sure if it's related to the new subsystem.

**Comment by Tsar-Salat** [comment]
Cannot reproduce, it was likely the multiple TMs at the time
