### ISSUE TITLE
[Bug]: Remote Signaler PDA App

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11148]
### BYOND Version

514.1589

### Round Date

2024/07/02

### Describe the bug

When I opened the Remote Signaler PDA App, I noticed it was only showing this:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/82539179/183629e6-cb61-40d1-b0f3-4302732575a4)

Unsure if it would or wouldn't actually send a signal too.

### What did you expect?

I expected it to show the frequency being entered.

### Reproducible steps

1. Download remote signaler PDA app.
2. Open it and try to send a signal to any frequency.

**Comment by itsmeow** [comment]
Yeah you have to install the signaller. You can buy it from the PDA vendor outside sci

**Comment by MarkusLarsson421** [comment]
Oh... wow. Never mind then.
