### ISSUE TITLE
[New Feature]: Mid Rounds should Spawn Early Game

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11144]
Currently the game feels VERY late-game heavy. You have traitors who might do some crimes and general noise early and mid-game, but most of them will be planning and acting in the shadows. After one hour or so mid-rounds may start spawning and the previously mentioned traitors may start going more loudly around this time too. I think one or two mid-round antags could keep both Medbay and Security active as currently Security are chillin' and Medbay are acting as Engineers. (Some Medical staff even saying to Engineers that they'll do construction work themselves...)

So after the 1:30 hour mark, you have several round start antagonists and two to three single or groups of mid-round antagonists against the entire Secuirty team.

**Comment by PowerfulBacon** [comment]
The early game is purposely less chaotic and calmer to give people time to prepare, and to follow a nicer dramatic curve.
