### ISSUE TITLE
[Bug]: Bananium Swords cause bleed

### ISSUE THREAD

**Issue by ro5490** [BeeStation/BeeStation-Hornet#11202]
### Round Date

2024/07/16

### Round ID

49324

### Describe the bug

Bananium swords shouldnt cause bleed as they do no damage, however they inherit the regular e-swords Bleed_Force_ON value.

### What did you expect?

I expected /obj/item/melee/transforming/energy/sword/bananium to not cause bleed

### Reproducible steps

Spawn /obj/item/melee/transforming/energy/sword/bananium
Hit person
They bleed

**Comment by ClownMoff** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/11211
