### ISSUE TITLE
Wall Item Placement Bugs

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11205]
### BYOND Version

514.1589

### Round Date

2024/07/19

### Describe the bug

When I placed a light switch against a walk, I noticed [it appeared on the opposite side from where it was supposed to.

And a double issue. All cameras on lavaland science department are weirdly placed.

### What did you expect?

For the light switch to be placed on the wall I'm putting it on, not the opposite ditection in the air.

### Reproducible steps

place light switch

look at camera

**Comment by Tsar-Salat** [comment]
![image](https://github.com/user-attachments/assets/66461b60-a697-4127-bbff-1c04cf10497f)

That isnt supposed to happen
