### ISSUE TITLE
[Bug]: Echostation SM Gas Ejector Vent Shaft is Offset by 1 Tile

### ISSUE THREAD

**Issue by Programs-The-Station** [BeeStation/BeeStation-Hornet#11222]
### Round ID

49380

### Describe the bug

![image](https://github.com/user-attachments/assets/a6f6dc1d-9303-4a4e-9125-d1fdcecc5d7a)
![image](https://github.com/user-attachments/assets/27645d34-2f67-439f-b4f3-9330b4a62db3)

Landing on that ledge might be problematic.

### What did you expect?

I expected the shaft to be a straight shaft.

**Comment by BriggsIDP** [comment]
those walls on the ground floor where added by a player haha. don't worry it also fooled me for a moment
![image](https://github.com/user-attachments/assets/335ed4ed-c0b8-4dbd-8a7a-a886284a32c9)

**Comment by Programs-The-Station** [comment]
Oh, ha, duh! That... actually makes some sense. I was thinking of the toxins chamber.

Whoops.
