### ISSUE TITLE
[Bug]: Golems have holy aura when they spawn

### ISSUE THREAD

**Issue by Therealdoooc213** [BeeStation/BeeStation-Hornet#11227]
### BYOND Version

515.1641

### Round Date

23/07/2024

### Round ID

49395

### Test merges

9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a](https://www.github.com/beestation/beestation-hornet/pull/9124

### Describe the bug

When I spawned in as golem, I immediately noticed that i had the holy aura around my body, and all of the other golems.
![gole](https://github.com/user-attachments/assets/b06b2407-36d7-4ca7-ad16-b8e893c80bc4)

### What did you expect?

I expected not to have a holy aura when I spawned in with no holy items

### Reproducible steps

1. Spawn in as a Free Golem (unsure if this also happens with xenobiology golems)

**Comment by Therealdoooc213** [comment]
Apparently Adamantine and Silver golems have magic proofing, but I'd still consider adamantine golems having magic proof a bug.

**Comment by lowwy** [comment]
it is specified in the info text for their magic immunity though:
`As an <span class='danger'>Adamantine Golem**</span>, you possess special vocal cords allowing you to \"resonate\" messages to all golems. Your unique mineral makeup makes you immune to most types of magic.`

Same for silver
`As a <span class='danger'>Silver Golem</span>, your attacks have a higher chance of stunning. Being made of silver, your body is immune to most types of magic.`

**Comment by PowerfulBacon** [comment]
Adamantine and silver golems spawn with an inherent anti-magic trait. They are anti-magic and aren't protected from holy spells, when the aura is provided it doesn't differentiate between a magic aura and a holy aura which could end up causing some confusion. (Cult only care if someone has a holy aura, wizards only care if someone has a magic aura)
