### ISSUE TITLE
[Bug]:  Deepfried weapons still work

### ISSUE THREAD

**Issue by ClownMoff** [BeeStation/BeeStation-Hornet#11238]
### Round Date

2024/07/27

### Describe the bug

When I deepfried tonfa and PTSD they still worked

### What did you expect?

I expected deepfried stuff to not work

**Comment by DrDuckedGoose** [comment]
I believe this is an intended feature

**Comment by Tsar-Salat** [comment]
Why would lathering cooking oil on a stick made from reinforced steel... not make it hurt when someone hits your kneecap with it?

**Comment by ClownMoff** [comment]
what about the PTSD then

**Comment by PowerfulBacon** [comment]
I wouldn't say this is intended, but it also isn't intended for deep-friend items to lose their function. Either is perfectly valid and I wouldn't deem either to be an issue that needs changing.
