### ISSUE TITLE
failsafe uplink failing to activate

### ISSUE THREAD

**Issue by Witherael** [BeeStation/BeeStation-Hornet#11284]
Issue reported from  Round ID: 49515 (BeeStation Sage - Roleplay)

Reporting client version: 515.1631

after purchasing the failsafe uplink on a radio uplink, the failsafe code was the same as the uplink code, and saying the code only unlocked the uplink, it didn't activate the failsafe, and saying it when the uplink was active also didn't activate the failsafe
![image](https://github.com/user-attachments/assets/347bf8ba-eab7-4aff-810f-d76a872785f4)
![image](https://github.com/user-attachments/assets/5c4a9cf9-0c67-48f4-99df-a7201c061fe0)

**Comment by Tsar-Salat** [comment]
Can confirm the issue during this round, tried to handle this as admin, but I wasnt really in a position to try something like replacing his uplink with a new one, given he was being interrogated.



> the failsafe code was the same as the uplink code

Just my 2 cents, but either 2 things happened.
1. You hit the million in one chance that your uplink and failsafe code rolled the same. Highly unlikely, and feels impossible.
2. Your failsafe code was a copy of your regular code for shitcode reasons.

Im leaning towards numero dos
