### ISSUE TITLE
[Bug]: it seems organs cannot be eaten for some reason

### ISSUE THREAD

**Issue by kiekatz** [BeeStation/BeeStation-Hornet#11289]
### Round Date

2024/08/04

### Round ID

49523

### Test merges

#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a
#10474: 'WORKING Directional Lighting in 2024' by Tsar-Salat at commit ea550b2f68
#10906: 'Overhaul Xenoarchaeology ' by DrDuckedGoose at commit 2d5a9383dc
(i think)

### Describe the bug

When I [tried to eat an organ i aquired from a corpse... as one does], I noticed [i cannot eat it. as if  it was not an edible item no matter how much i tried to eat it on any intent]

### What did you expect?

at first i tought it was a feature change but later i have been informed that no. you SHOULD still be able to eat organs

### Reproducible steps

1. acquire organ (i got mine from a  disembodied corpse. but after that i tried organs from the medbay freezer and they also didnt work so i dont think there's a specific way to get the organs)
2. try to eat the organ
3. nothing happens

**Comment by Tsar-Salat** [comment]
Hi, newfood guy here. 

Nothing has touched edibility in months, so I'm thinking it's a current TM.

I will check if I can replicate on local and sage when I get homd

**Comment by Rukofamicom** [comment]
I have tested this and replicated it... by using harm intent.

On all other intents I can still eat organs just fine, but not harm intent.
