### ISSUE TITLE
[Bug]: Stickers prevent xenos from being able to attack you

### ISSUE THREAD

**Issue by Tsar-Salat** [BeeStation/BeeStation-Hornet#11293]
### Test merges

- https://github.com/beestation/beestation-hornet/pull/9124
- https://github.com/beestation/beestation-hornet/pull/10474

### Describe the bug

When I tried to attack someone covered in stickers as a Xenomorph, while on harm intent, I could not.

![image](https://github.com/user-attachments/assets/e022f30b-2f11-4060-94fc-4300f0a4ef64)

### What did you expect?

I expected to be able to attack them. I had to alt_click them and select from the statpanel to actually hit them.

**Comment by Rukofamicom** [comment]
Stickers should be destroyed by anything that doesn't have dexterity, and/or the attack simply go right through to the mob under

**Comment by Rukofamicom** [comment]
@DrDuckedGoose this is fixed now right?

**Comment by DrDuckedGoose** [comment]
That's right!

**Comment by Tsar-Salat** [comment]
Yeah looked fine last time I was ingame during TM.
