### ISSUE TITLE
[Bug]: Mushroom cap deleting a mushroom bowl

### ISSUE THREAD

**Issue by Xestia32** [BeeStation/BeeStation-Hornet#11295]
### BYOND Version

515.1641

### Round Date

2024.08.04

### Round ID

49533

### Describe the bug

When I tried putting the mushroom cap into the mushroom bowl, they both dissapeared

### What did you expect?

I expected the mushroom cap to go inside the mushroom bowl or for nothing to happen at all

### Reproducible steps

i was playing as an ashwalker. i had the mushroom cap in my right hand and the bowl in the left one. then i tried using the cap on the bowl and they both just dissapeared

### edit

Later after i died and my corpse gibbed to the nest i have found a bowl of mushroom salad where my corpse has been

**Comment by Fronsis** [comment]
I've noticed similar behaviour when putting certain items in bowls by accident(or not) on kitchen too so it might extend beyond mushrooms, same with like.. Certain steaks on buns and so on, probably a small bug from newfood, i need to try to remember the others i experienced

**Comment by Fronsis** [comment]
Newfood stuff will be solved soon shut up bot!!

**Comment by Tsar-Salat** [comment]
I fixed this in #11639
