### ISSUE TITLE
[Bug]: Changing Loadout and Killing a Mob will Crash the game

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11300]
### BYOND Version

514.1589

### Round Date

2024/08/05

### Round ID

Local

### Describe the bug

When I was cuffed by Beepsky and then changed my loadout to Debug, I noticed my cuffs had vanished and when I went back to get my revenge on him he got the last laugh and crashed me game as he was about to die.

Last moment before the crash.
![image](https://github.com/user-attachments/assets/77172216-9df6-4443-add1-63b5a1db9d25)

### What did you expect?

I expected to not crash.

### Reproducible steps

1. Hit Beepsky.
2. Get stunned and cuffed.
3. Change loadout with admin perms.
4. Go back and hit Beepsky again (with an item).

**Comment by MarkusLarsson421** [comment]
![image](https://github.com/user-attachments/assets/2588a348-53cb-4757-8007-a2e7862903e4)

**Comment by MarkusLarsson421** [comment]
Never mind, this is exclusive to VSCode hosted locals on Debug mode and not Dream Daemon.

**Comment by Dejaku51** [comment]
you can disable Runtimes errors breakpoint in debug tab on the left to stop it
