### ISSUE TITLE
Forced reconnecting

### ISSUE THREAD

**Issue by NormalAnomaly** [BeeStation/BeeStation-Hornet#1130]
Issue reported from  Round ID: 11431 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 512.1488

Description: Intermittently I am having what seems to be a forced client reset.  The UI blacks out and then pops me back into the game, displaying my "memories" as though I had relogged into the session or done a manual reconnect.  Interestingly, no matter how long I wait, if I never unbuckle from the arrivals shuttle then I also re-ride the shuttle in each time.  It took some time to identify what was happening on my end, as I could go for a longer period without a reconnect and it turned out to be any interacting with the HUD elements was a controllable way to cause these.  It should be noted that this makes Bee essentially unplayable right now.

I have tested this with both the current Byond 512.1488 and an older 512.1464 that I happened to have an install for.  I have tried a handful of other servers and have this issue on none of them.  This problem applies for both Sage and Golden.  The problem persists both before and after a cache clearing.

This has only been observed starting 1/13/20 from my first time connecting.

If it will help in any log hunting, the character's name/memory for the above listed round ID.  Had several sequential reconnects on this character.
"Lydia Hall's Memories:
Your account ID is 500377."

Steps To Reproduce:
1. Start session and join game.
2. Mouse over any hud element. The icons at the bottom or the buckle icon in the top right for instance.
2a. If the mouse is left in place during the reconnect, I can manipulate that slot as normal, for instance opening a bag.  Mousing over the slots in the bag though causes the issue to reoccur. 
3. Game freezes for a few moments (easily seen on the health hud tracker), blacks out and reset.

**Comment by qwertyquerty** [comment]
Solved by a byond update.
