### ISSUE TITLE
[New Feature]: Advanced Atmosbot

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11308]
### Describe the feature request

I'd like it if we had the old atmosbots returned in someway, such a Cargo exclusive Atmosbot which can produce regular air. Currently it is a pain to use tanks and whatnot to fix hallways, especially when atmos (performance-wise and mapping-wise) is so slow as it is.

**Comment by MarkusLarsson421** [comment]
Alternatively, Firebots (which are NEVER used) would fix the temperature and put up holofans where needed while Atmosbots would only scrub and produce air.

In the future, once the Medibot restock station is made for chemistry, it could perhaps be done the same for atmosbots to automatically go to a connector and get more air stored in them.

**Comment by PowerfulBacon** [comment]
Atmosbots don't product their own air anymore?

**Comment by MarkusLarsson421** [comment]
I thought it was you who removed it? I haven't noticed their effect in-game. Let me test it in a controlled environment.
