### ISSUE TITLE
[Bug]: Clarke Mech is Invisible During Construction

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11316]
### BYOND Version

514.1589

### Round Date

2024/08/11

### Round ID

49603

### Test merges

[#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10919: 'Adds Dionae to the game' by XeonMations at commit 93eb1af62d](https://www.github.com/beestation/beestation-hornet/pull/10919)

### Describe the bug

When I tried to construct a Clanke, I noticed as soon as I assembled all the pieces onto the chassis, that the mech turned invisible.

Additionally, the Wiki has not been updated, but it might be too early to expect that.

### What did you expect?

I expected things to not be turned invisible during construction.

**Comment by Tsar-Salat** [comment]
> Additionally, the Wiki has not been updated

Fixed an hour ago. Had to tweak some stuff around a bit.

**Comment by Tsar-Salat** [comment]
fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/11317
