### ISSUE TITLE
[Bug]: Can't enable/disable Headset's channels

### ISSUE THREAD

**Issue by May-Rai** [BeeStation/BeeStation-Hornet#11319]
### BYOND Version

515.1614

### Round Date

2024/08/11

### Round ID

49607

### Test merges

[#9124: 'Enable serverside 515.1633' by Crossedfall at commit 3e63a01a0a](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10730: '(recoup) Spatial gridmap take 3' by Tsar-Salat at commit 79ade99393](https://www.github.com/beestation/beestation-hornet/pull/10730)

### Describe the bug

When I wanted to enable channels on captain's headset (As an Acting Captain) they just reset to the default enabled channels when I closed the pop-out window.

### What did you expect?

I expected channels to be enabled.

### Reproducible steps

> Take any headset with channels (For example, captain's headset)
> Activate it in hand to open pop-out with channels
> Try to enable/disable any channels
> Close the pop-out and reopen it

**Comment by Tsar-Salat** [comment]
This is from Spatial gridmapping. Ill put up a fix
