### ISSUE TITLE
[Bug]: Simplemobs can toggle machines with ctrl + click. 

### ISSUE THREAD

**Issue by Rukofamicom** [BeeStation/BeeStation-Hornet#11362]
### Describe the bug

When I am a mouse I can sabotage the SM. 

### What did you expect?

I expect hands and/or dexterity to be required to do things that require hands and/or dexterity. 

### Reproducible steps

https://github.com/user-attachments/assets/1df0a919-1ff4-4441-944b-17e9e93ca69c

**Comment by Rukofamicom** [comment]
# What the fuck

**Comment by Tsar-Salat** [comment]
Yeah, dexterity on bee sucks ass.

Like, you'd expect a dog to be able to hit a lightswitch or hit a departmental bell, but nope! You do not have Dexterity!

But hey, you can use all the shortcuts on atmos machines, so thats swell!

**Comment by aramix273** [comment]
a monkey cannot fetch the secret documents from the cabinet in the vault but suddenly if it has telekinesis it can do so from a distance

**Comment by Tsar-Salat** [comment]
@HowToLoLu resolved?

**Comment by HowToLoLu** [comment]
> @HowToLoLu resolved?

Dunno; I'll get back to you on this one tomorrow (~12 hrs).

**Comment by Tsar-Salat** [comment]
> > @HowToLoLu resolved?
> 
> Dunno; I'll get back to you on this one tomorrow (~12 hrs).

👁️

**Comment by HowToLoLu** [comment]
Yes, it's resolved; can't ctrl+click pipes anymore at least
