### ISSUE TITLE
[Bug]: RCD's upgrades

### ISSUE THREAD

**Issue by May-Rai** [BeeStation/BeeStation-Hornet#11369]
### BYOND Version

515.1614

### Round Date

2024/08/25

### Round ID

49762

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 1b8f225789](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10983: 'Server framework v2' by Dejaku51 at commit 44df99fb5b](https://www.github.com/beestation/beestation-hornet/pull/10983)

### Describe the bug

There are four upgrades for RCD.
![image](https://github.com/user-attachments/assets/051591be-824a-4425-9e5d-31d42fc54f9e)
![image](https://github.com/user-attachments/assets/0c0e6e0e-9ca3-42e1-b4b6-cacc452dff86)
Yet they all do wrong things.
The "RCD simple circuits designs upgrade" adds furnishing upgrade;
The "RCD furnishing upgrade" adds furnishing AND ore silo connection;
The "RCD frames designs upgrade" does absolutely nothing.
The "Advanced RCD silo link upgrade" is still fine. Doing expected thing: Giving Ore Silo link.

### What did you expect?

I expected all upgrades to give their respective upgrades.

### Reproducible steps

1. Get upgrades from Engineering protolathe
2. Print RCD
3. Insert every upgrade and see for yourself

**Comment by Tsar-Salat** [comment]
uh oh

**Comment by SuperPantsHero** [comment]
RPD unwrenching upgrade also doesn't work
