### ISSUE TITLE
[Bug]: Building Lockers' mixup

### ISSUE THREAD

**Issue by May-Rai** [BeeStation/BeeStation-Hornet#11389]
### BYOND Version

515.1614

### Round Date

2024/08/27

### Round ID

49781

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 1b8f225789](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10983: 'Server framework v2' by Dejaku51 at commit 44df99fb5b](https://www.github.com/beestation/beestation-hornet/pull/10983)

### Describe the bug

When I tried building Fire Locker, it built Radiation locker. And vice-versa.

### What did you expect?

I expected to make Fire locker when making fire locker, and radiation locker when making radiation locker

### Reproducible steps

1. Take 2 iron
2. Use in hand to open building menu
3. Open "Lockers" menu
4. Build Fire/Radiation locker.

**Comment by ktlwjec0** [comment]
This can be closed #11610
