### ISSUE TITLE
cultist hood makes you topless

### ISSUE THREAD

**Issue by Niko432** [BeeStation/BeeStation-Hornet#11440]
Issue reported from  Round ID: 49899 (BeeStation Sage - Roleplay)

Reporting client version: 515.1643

I have reported an issue with the cultist robes; the hood was glitched and when you toggled it on a winter hood appeared instead of a cultist hood, after the issue was "patched" now instead of a winter hood you get a cultist hood yes, but toggling the cultist hood on makes your jumpsuit AND cultist armor disappear, making visibly you completely naked . The icon of the cultist robes also becomes invisible in the button you use to toggle the hood it on and off

**Comment by Tsar-Salat** [comment]
fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/11738
