### ISSUE TITLE
[Bug]: Inserting more than 1 plastic sheet a a time deletes the rest

### ISSUE THREAD

**Issue by Geatish** [BeeStation/BeeStation-Hornet#11493]
### BYOND Version

515.1614

### Round Date

2024-09-14

### Round ID

49976

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 1b8f225789](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#11427: 'New walls and girders (now with smoothing!) + spare fixes' by PestoVerde322 at commit bdd6c24089](https://www.github.com/beestation/beestation-hornet/pull/11427)
[#11487: 'Reverts Kapu limbs part 1' by Rukofamicom at commit 840668d538](https://www.github.com/beestation/beestation-hornet/pull/11487)

### Describe the bug

Inserting plastic stacks into a lathe deletes all but one sheet

### What did you expect?

I expected all the sheets to be loaded into the lathe. 

### Reproducible steps

1. have a stack of plastic with more than one sheet
2. insert that stack into a lathe
3. watch ~~the government take the rest~~ there only being one sheet in the lathes mat holder

**Comment by RDS88-beeman** [comment]
I started looking at this and the more I test, the more confused I get.
Inserting a stack of fifty only inserts one.
Inserting one inserts NOTHING.
Ejecting plastic one by one from the lathe makes the stack behave normally, but ejecting a stack makes the stack only count as one.
Also, false plastic and true plastic are mutually exclusive, and do not stack or interact with each other like normal.
I am so confused.
