### ISSUE TITLE
Cocktails are factually inaccurate with respect to real life standards.

### ISSUE THREAD

**Issue by 123chess456** [BeeStation/BeeStation-Hornet#1153]
## Reproduction:

The vast majority of cocktails that can be mixed in the game are incredibly inaccurate with respect to their real life counterparts. For example, the Cuba Libre has as much lime juice as actual space cola and someone thought that "silver tequila" meant actual silver was in the tequila. And the gin and tonic has more gin than tonic! Specifically after spending an hour or so reviewing the first part of the drinks_recipes.dm file I wrote down these notes/suggestions:

Goldschlager is listed in game as a combo of vodka and gold at a 10:1 ratio. In real life it's cinnamon schnapps with gold flakes. Unsure of how to fix.

"Patron" is listed in game as a cocktail made with tequila and silver at a 10:1 ratio. In real life, Patron is a brand of tequila, and "silver tequila" is a general name for clear (not really aged) tequila, opposed to "gold tequila" which has additives that colour it. Neither gold nor silver tequila contain actual precious metals. I recommend removal or name change.

"Bilk" is in the game as a 1:1 mixture of beer and milk. It's a real life branded drink that was made in Japan, however milk is actually 30% of the drink. I suggest changing to 2:1 mixture to represent a more realistic proportion. Bilk should not be confused with "Milk Stout", a type of beer made with lactose. Internet research doesn't inform me how Milk Stout is made so I'm not going to get into this other than to say "bilk" is not interchangeable terminology.

Iced tea in game is a 1:3 mixture of ice and tea. No problems here. Likewise for iced coffee.

Nuka Cola in game is a mixture of 1 part uranium and 6 parts space cola. While this is inaccurate to the original fallout games, this seems like a pretty reasonable simplification as there is no exact recipe for Nuka Cola and the drink is intended as a reference.

Moonshine is made by mixing nutriment and sugar with enzyme to catalyze it. There's no "proper" way to make moonshine and the recipe isn't grossly inaccurate so it's fine. There's a lot of other drinks made by "fermenting" plant juices by mixing them with nutriment. Examples being Wine, Beer, Vodka, and Kahlua. They're all accurate enough except for Kahlua.

Kahlua in game is portrayed as a mixture of coffee and sugar catalyzed by enzyme. This is incorrect. It is made with coffee beans, vanilla, sugar, and rum. I suggest changing the recipe to be coffee, sugar, vanilla reagant, and rum. I suggest the proportions be 1:2:1 coffee, sugar, and rum, with vanilla as a 1 unit catalyst to reflect the fact that vanilla is a solid additive.

Gin and tonic is portrayed in game as a 2:1 mixture of gin and tonic water. In real life, there are many ways to make gin and tonic. However one thing they have in common is that they are nothing like this recipe's ratio. I suggest changing to a mixture of 1 part gin and 2 parts tonic to be accurate.

Rum and coke (Cuba Libre) has the same problem. In game it's a 2:1 mixture of rum and space cola. In real life, the IBA describes it as 12 parts cola, 5 parts rum, and 1 part lime juice. However this is a "Cuba libre" and not strictly speaking a rum and coke. I suggest changing the "Rum and Coke" recipe in game to 2 parts cola with 1 part rum for accuracy. Cuba Libre should be Rum and Coke catalyzed by the addition of 1 unit of lime juice for gameplay purposes, as a 17:1 cocktail recipe is awkward but the current recipe has a very high overrepresentation of lime juice (as much lime juice as coke). 

The martini in game is a 2:1 mixture of gin and vermouth. In real life it's a 6:1 ratio. I suggest changing to a 5:1 ratio as a compromise between gameplay and accuracy. Having the end product be 6 units is desirable from a gameplay perspective due to many alcohol containers in the games being a multiple of that number.

The vodka martini should also be changed from its current 2:1 ratio of vodka to vermouth to a 5:1 ratio for the above reasons as well.

The Black Russian in game (listed here out of order from code to be next to white Russian) is listed as a 3:2 mixture of vodka and Kahlua. In real life it's a 5:2 mixture of vodka and Kahlua. I suggest changing in game recipe to be 4:2 (2:1) vodka and Kahlua. This brings it closer to accuracy while keeping the result a round number. We should also change the White Russian to a 2:1 mixture of black Russian and cream rather than a 3:2 mixture. This is closer to real life proportions, which is important for RP/accuracy reasons as the current recipe for a White Russian would entail more cream than either vodka or Kahlua. The cream should be an accent, not a main part of the drink.

Whiskey cola is listed in game as 2 parts whiskey 1 part cola. This is incorrect. Whiskey cola in real life is 1 part whiskey and 3-5 parts cola. I suggest changing it in game to 1 part whiskey and 2 parts cola. This makes the final reagant a multiple of 3 (drink containers are all such) and is in line with the changes to gin&tonic as well as the rum&coke.

The screwdriver listed in game is 2 parts vodka 1 part orange juice. The proportions are wrong again. Screwdrivers are 1 part vodka and 2 parts orange juice.

The bloody Mary listed in game is a 1:2:1 mixture of vodka, tomato juice, and lime juice. In real life it's a 3:6:1 mixture of vodka, tomato juice, and lemon juice with some other garnishes. I recommend keeping the 1:2:1 proportions for gameplay but replacing lime juice with lemon juice for accuracy.

No comment on pan galactic gargle blaster as it's a fictional drink.

The Brave Bull is 2 parts tequila and 1 part Kahlua. Since it's just a tequila version of the Black Russian I suggest keeping it the same proportion.

Tequila sunrise is basically close enough in game.

Beepsky smash/doctor delight/toxins special are fictional and I won't get into detail.

For Irish Cream, recipe IRL is a trade secret. Current in game recipe is probably fine.

Manly Dorf is a fictional drink so not analyzing. Same with green beer, which is beer with a crayon in it. Hooch also falls under this category.

"Irish Coffee" actually predates Irish Cream and is a mixture of coffee and whisky. However for gameplay reasons the recipe is fine as it is considering one would make an Irish Coffee with whiskey, cream and coffee anyways.

B52 is correct.

Atomic bomb is fictional.

In SS13 the "Margarita" is 2 parts tequila and 1 part lime juice. According to the IBA it's 7:4:3 tequila, Cointreau (triple sec), and lime juice. I suggest changing in game to 2 parts tequila, 1 part triple sec, and 1 part lime juice.

The Long Island Iced Tea in game is 1:1:1:1 vodka, gin, tequila, and Cuba Libre. In real life (according to IBA) it's 1.5:1.5:1.5:1.5:1.5:2.5:3 vodka, gin, tequila, rum, triple sec, lemon juice, bar syrup, with a dash of coke. Since Cuba Libre is used in game due to existing reaction between rum, coke, and lime juice, we can see the existing formula is really 1:1:1:2:1:1 vodka, gin, tequila, rum, coke, and lime juice. Since the Long Island Iced tea should be using lemon juice anyways, we don't need to include the Cuba Libre and should be using the rum and coke as an ingredient. I'm not going to get into mixers and want to keep this simple, so I propose a new recipe of 1:1:1:1:3:2 vodka, gin, tequila, triple sec, rum and coke (as one reagant), and lemon juice. This is simplified for gameplay purposes but is still much more accurate than the current recipe.

**Comment by zeskorion** [comment]
WYCI

**Comment by 123chess456** [comment]
Going to but I was looking for input for what is essentially changing every single bartender recipe in the game before I put in the time to code it as this sounds like it could be a very controversial change. I'm also documenting beforehands for reasons.
