### ISSUE TITLE
[Bug]: Odd Double Period after each Character Description

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11575]
### Round Date

2024/09/25

### Describe the bug

When I've been inspecting peoples clothes and such, I noticed an extra period afterwards.

![image](https://github.com/user-attachments/assets/b3b831c7-fa5b-4a70-9311-7c539c231476)

It is usually after the ID, but it is always at the end.

### What did you expect?

I expected one single period.

**Comment by ktlwjec0** [comment]
my bad #11534 , don't know how I missed that honestly
