### ISSUE TITLE
[Bug]: Performing multiple actions with do-afters at the same time no longer works

### ISSUE THREAD

**Issue by SunShine214** [BeeStation/BeeStation-Hornet#11599]
### Round Date

NAN

### Round ID

NAN

### Test merges

likely caused by the cog pr: 
https://github.com/BeeStation/BeeStation-Hornet/pull/11120

### Describe the bug

Previously when using things like the discovery scanner, you can perform multiple actions at once. This no longer works, despite a message appearing you are doing so. After some testing, only the actions the do-after is above your head are bugged.
![Screenshot (177)](https://github.com/user-attachments/assets/f57569e5-6252-4fbe-ba22-4a53b348533b)
(you should see the "already scanned" message the same number of times you scanned the mob)

### What did you expect?

I expected either a message appearing you cannot do multiple actions at once or that you can actually still do multiple actions at once

### Reproducible steps

1. use discovery scanner on multiple mobs
2. discovery scanner says you are scanning all the mobs
3. only one mob is scanned

**Comment by XeonMations** [comment]
Noted the same behavior when attempting to remove more than one item from a person's strip menu.

**Comment by Rukofamicom** [comment]
@Tsar-Salat
