### ISSUE TITLE
TGFont icons do not show, breaking Nonbinary character selection

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#11643]
Tested on the live server, round 50219, 2024-10-05 18:44:37

There appear to be some anomalies with the character creator.

- The only genders available are male and female, when other should be selectable too.
- The final character slot does not have the option to select gender and is forced to have gender disabled despite being able to select the bodytype.

![image](https://github.com/user-attachments/assets/d32e9faf-4916-417f-9b33-5165026df989)

![image](https://github.com/user-attachments/assets/4ccd195a-cb92-44cf-ad0f-29cc731ef21e)

(This character is a human, changing species has no effect)

**Comment by PowerfulBacon** [comment]
Potentially relevant runtimes:
```
[2024-10-05 18:43:12.321] runtime error: sizes does not contain mapwindow.size key. This means a winget failed to return what we wanted. --- sizes var: /list --- sizes length: 0
 - proc name: Fit Viewport (/client/verb/fit_viewport)
 -   source file: code/modules/client/verbs/ooc.dm,256
 -   usr: null
 -   src: PowerfulBacon (/client)
 -   call stack:
 - PowerfulBacon (/client): Fit Viewport()
 - world: ImmediateInvokeAsync(PowerfulBacon (/client), "fit_viewport")
 - /datum/preference/toggle/fulls... (/datum/preference/toggle/fullscreen): apply to client(PowerfulBacon (/client), 1)
 - /datum/preferences (/datum/preferences): apply all client preferences()
 - /datum/preferences (/datum/preferences): New(PowerfulBacon (/client))
 - PowerfulBacon (/client): New(null)
 - PowerfulBacon (/client): New("/")
 - 
```

```
[2024-10-05 18:45:38.979] runtime error: json_decode error: Unknown value at NO SUCH JOB (character 1)
 - proc name: process (/datum/db_query/process)
 -   source file: code/controllers/subsystem/dbcore.dm,532
 -   usr: null
 -   src: /datum/db_query (/datum/db_query)
 -   call stack:
 - /datum/db_query (/datum/db_query): process(null)
 - /datum/db_query (/datum/db_query): sync()
 - /datum/db_query (/datum/db_query): Execute(1, 1)
 - /datum/db_query (/datum/db_query): warn execute(1)
 - REDACTED (/client): db inc metabalance(4)
 - world: ImmediateInvokeAsync(REDACTED (/client), "db_inc_metabalance", 4)
 - 
```

**Comment by PowerfulBacon** [comment]
Runtimes seem irrelevant. This probably requires a DB setup with an extra slot purchased

**Comment by itsmeow** [comment]
@PowerfulBacon This issue is beacon the nonbinary icon from tgfont doesn't seem to exist in the stylesheet anymore. I saw this a few weeks ago but figured it was just some caching issue. tgfont hasn't had any major changes so I don't know what broke it.
You can tell because if you use IEExplorer to look at it, the button is there it just has no content so it doesn't display correctly.

**Comment by itsmeow** [comment]
The icon not showing on the last slot is because that slot happens to have the nonbinary gender randomly assigned. And since the icon has a size of 0 the button it's inside also has a size of 0 and just isn't visible. It's all a clientside issue.
