### ISSUE TITLE
[Bug]: oven trays not working when full

### ISSUE THREAD

**Issue by Liver-1** [BeeStation/BeeStation-Hornet#11654]
### BYOND Version

514.1589

### Round Date

2024/10/07

### Round ID

Can't remember 

### Describe the bug

When the baking tray goes into the oven with stuff on it, and it's full, the oven will accept all the items on it but not the tray, leading to the tray looking like it's been left on top of the oven, but when you pick up the baking tray, the ingredients will all come with it, leaving the oven empty.

### What did you expect?

I expected the tray to go into the oven with the ingredients, even when full.

### Reproducible steps

1- Make Oven
2- Fill the tray that comes with the oven.
3- The oven will accept all the items on it but not the tray, leading to the tray looking like it's been left on top of the oven.
4- When you pick up the baking tray, the ingredients will all come with it, leaving the oven empty.

**Comment by Tsar-Salat** [comment]
> but when you pick up the baking tray, the ingredients will all come with it, leaving the oven empty.

Does this preclude the oven from working and baking the stored items if you do not remove it?

**Comment by ColonelOrion** [comment]
No, the oven still cooks, it just looks odd
