### ISSUE TITLE
creating turfs also creates atmos for those same turfs.

### ISSUE THREAD

**Issue by SergeiKoralev** [BeeStation/BeeStation-Hornet#1168]
## Round ID:

[Round ID]: Private Test

## Testmerges:

none affecting atmos

## Reproduction:

enter room, empty room of air, crowbar up all the tiles with atmos system off, watch as Linda makes you new air.

**Comment by zeskorion** [comment]
this has been a thing for a good while now. the spacewind is especially bothersome

**Comment by VictorVow** [comment]
Especially problematic when trying to RCD over lava without magboots.

**Comment by ike709** [comment]
I'm almost certain TG fixed this, shame we can't look at their repo.

**Comment by ivanmixo** [comment]
Doesn't seem to be the case anymore.
