### ISSUE TITLE
You know it's a license volation to ban someone from "contributing to a spite server", right?

### ISSUE THREAD

**Issue by 123chess456** [BeeStation/BeeStation-Hornet#1171]
![Screenshot_20200202-013001~2](https://user-images.githubusercontent.com/8888654/73604271-e2584e80-455b-11ea-9aa9-d0106248eb1f.png)

You can't do this @ike709. Read section 10 of the LICENSE file. "You may not impose any further restrictions on the exercise of the rights granted or affirmed under this License." Since one of the many rights granted by the AGPL is the right to fork code to create new derivative codebases, retaliating against someone for contributing to a derivative codebase falls into "further restrictions" and isn't allowed. 

https://perens.com/2017/06/28/warning-grsecurity-potential-contributory-infringement-risk-for-customers/

**Comment by Crossedfall** [comment]
Either you realized how stupid this was and closed your own issue or you thought it would be a funnier meme if you did it this way. Regardless as to the why, I'll quickly point out the obvious in saying that removing someone from being a maintainer in no way violates that section of the license.

Mark is free to contribute to his own codebase (which is not a downstream of bee), he's even free to contribute to our own codebase which can be seen with his latest pr. This was idiotic. Future issues like this will result in a block.
