### ISSUE TITLE
[New Feature]: Item Teleporter

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11710]
### Describe the feature request

I'd like it if we had an item teleporter. They could be placed in some places like Toxins, Brig and so on and will teleport a single item which can be picked up no matter its size to a beacon location. It'd otherwise be a tier 4 research item and only occupy one or two tiles.

**Comment by MarkusLarsson421** [comment]
Think Joon came up with this idea on my toxins test station site removal PR.

**Comment by PowerfulBacon** [comment]
Feature issues should be used for QOL stuff rather than raw content expansions, those should go in the ideasguy section on discord unless their development is requested by a maintainer.
