### ISSUE TITLE
[Bug]: Changeling Last resort and Digital camouflage don't work

### ISSUE THREAD

**Issue by TwingoI** [BeeStation/BeeStation-Hornet#11721]
### Round ID

50339

### Describe the bug

When I had injected a morgue body with the changeling eggs, I noticed that once the eggs were ready and the body gibbed it didn't spawn me in as a monkey despite it coming up in the chat that I was now a monkey.

Digital camouflage does nothing, the AI can still see you while its active.

(And as a side note the changeling Transform ability is **STILL** broken)

### What did you expect?

I expected the abilities to work as intended

### Reproducible steps

Inject morgue body with changeling eggs
Crawl into vent and die
Wait for eggs to hatch
Eggs hatch and gib the body
No monkey

Turn on Digital camo
AI still sees you with cameras

**Comment by Geatish** [comment]
Alright i've tested a bit of both. 
The digital camo works (at least on non player controlled lings), though nobody else seems to be able to tell that they have it active. 
with the last resort, you still get unsoulbound from you old headcrab body, even though there is no new monkey spawning...
