### ISSUE TITLE
[Bounty] Port empty clones from TG

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1177]
https://github.com/tgstation/tgstation/pull/44442

**Comment by bloons3** [comment]
Bounty time

**Comment by zeskorion** [comment]
don't see why you didnt do it yourself

regardless, im gonna try to fill this. if it aint done after tommorow night, im probly not doin

**Comment by Kerbin-Fiber** [comment]
hmm, money. if I dont get it done before I pass out, then zesko will probably get it

**Comment by St0rmC4st3r** [comment]
Oh! Money! If those two won't do it, I'll do it!

**Comment by bloons3** [comment]
Shoulda added "port all of the bug fixes for empty clones" as well

**Comment by Kerbin-Fiber** [comment]
just cuz my pr is up doesn't mean it'll be accepted

**Comment by bloons3** [comment]
@Kerbin-Fiber 
Show it working on a bee codebase with a screenshot of 2 empty clones and the clone machine showing the body only scan and I'll accept the bounty

**Comment by Crossedfall** [comment]
@bloons3 I can confirm it does the above. Forgot to include the body only scan option, but it is indeed there and it does seem to work. 

![image](https://user-images.githubusercontent.com/26130695/74095108-9c4a4000-4ab1-11ea-974d-ac01d7faa887.png)

**Comment by bloons3** [comment]
Yeet
