### ISSUE TITLE
[Bug]: Hyperkinetic Dampening Projector Field isn't Deleted when Blown Up

### ISSUE THREAD

**Issue by MarkusLarsson421** [BeeStation/BeeStation-Hornet#11786]
### Round Date

2024/10/28

### Round ID

50476

### Describe the bug

When our CE detonated a Protector Cyborg, I noticed that their square projectile thingy didn't disappear.
![image](https://github.com/user-attachments/assets/b32bb469-c11f-41e6-b874-378eab14ac3a)

### What did you expect?

I expected it to disappear.

**Comment by Tsar-Salat** [comment]
Fix your title

**Comment by MarkusLarsson421** [comment]
Whoops.
