### ISSUE TITLE
[Bug]: Throwing items does not work.

### ISSUE THREAD

**Issue by XeonMations** [BeeStation/BeeStation-Hornet#11788]
### BYOND Version

514.1589

### Round Date

2024/10/28

### Round ID

50477

### Test merges

- [#9124: 'Enable serverside 515.1614' by Crossedfall at commit 1b8f225789](https://www.github.com/beestation/beestation-hornet/pull/9124)
- [#11766: 'Shadow Sect Rework' by ro5490 at commit 07046f1554](https://www.github.com/beestation/beestation-hornet/pull/11766)
- [#11694: 'Ports a total refactor of riding' by Tsar-Salat at commit bd334e6176](https://www.github.com/beestation/beestation-hornet/pull/11694)

### Describe the bug

Throwing any item does not work.

### What did you expect?

I expected to throw the item.

### Reproducible steps

1. Pick up item
2. Press R to throw
3. Press anywhere to throw
4. Fail.

**Comment by aramix273** [comment]
this has been identified as a bug with #11694 which I believe has been hence fixed
it's currently not on testmerge and it seems still open
when it comes back on TM, please check if the issue still persists or if it's stale

**Comment by Tsar-Salat** [comment]
I fixed it
