### ISSUE TITLE
[Bug]: Codex Gigas is non functioning

### ISSUE THREAD

**Issue by EveLed** [BeeStation/BeeStation-Hornet#11783]
### Round Date

2024/10/27

### Round ID

50469

### Describe the bug

When I opened the Codex Gygax, I was given the message "This book is completely blank!" and was unable to use it properly. 

### What did you expect?

I expected the demon name menu to appear

### Reproducible steps

1. Get a Codex Gigas
2. Interact with it

**Comment by Tsar-Salat** [comment]
There is no devil names because it doesn't exist anymore

https://github.com/BeeStation/BeeStation-Hornet/pull/11604

**Comment by EveLed** [comment]
well that's lame
