### ISSUE TITLE
[Bug]: Simplemobs unable to hit/destroy walls

### ISSUE THREAD

**Issue by Isaacnml** [BeeStation/BeeStation-Hornet#11808]
### BYOND Version

515.1614

### Round Date

2024/10/30

### Round ID

50499

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 1b8f225789](https://www.github.com/beestation/beestation-hornet/pull/9124)

[#11766: 'Shadow Sect Rework' by ro5490 at commit edf0c12d1e](https://www.github.com/beestation/beestation-hornet/pull/11766)

### Describe the bug

When i attacked a wall, i noticed i couldn't damage or hit in any way as a "simplemob" including xenomorphs and sentient animals

### What did you expect?

I expected to be able to break down walls as a simplemob

### Reproducible steps

1. Become Xenomorph
2. Hit a wall
3. Cry as you're unable to damage it

**Comment by PowerfulBacon** [comment]
The fix is a 1 line change to add `uses_integrity = TRUE` to turfs.

**Comment by PowerfulBacon** [comment]
This also needs investigation into whether the way turfs handle explosives have regressed and need to be corrected (they should deal damage to the turf and not just scrape them away)
