### ISSUE TITLE
[Bug]: Mysterious Bottle not working

### ISSUE THREAD

**Issue by ColderThanCold** [BeeStation/BeeStation-Hornet#11804]
### BYOND Version

515.1645 (latest)

### Round ID

50497

### Describe the bug

I could only interact with the Mysterious Bottle with the context menu and nothing else.

### What did you expect?

for it to work like every regular bottle

**Comment by Tsar-Salat** [comment]
It didn't transfer reagents, you couldn't drink from it, you couldn't hold it?

Please be clear

**Comment by ColderThanCold** [comment]
it wouldn't let me click on it at all or even take the cap off it
