### ISSUE TITLE
[Bug]: Bluespace trash bag missing sprite(Baguette 2.0)

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#11836]
### Describe the bug

Bluespace trashbag shows the classic placeholder baguette i THINK we had a sprite for the bs bag
![Screenshot_49](https://github.com/user-attachments/assets/611f9650-d4c9-49bd-acc5-2c0394fac28d)

### What did you expect?

I expected to see funny bag, now i'm hungry

### Reproducible steps

1. Spawn
2. Spawn BS Trashbag
3. Equip
4. Baguette

**Comment by Tsar-Salat** [comment]
all trashbags use baguette since 6 months ago

**Comment by Fronsis** [comment]
I'm gonna crack your skull open github-actions bot THERE'S LITERALLY A PR THAT'S ABOUT O FIX IT
