### ISSUE TITLE
Crafting is not logged

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1187]
I plan to try tackling this one myself, if and when I get the know-how to do so.

Currently, crafting isn't logged. This led to a fun situation where someone had their scooter stolen but I couldn't find in the logs where the scooter was created, and couldn't track it.

Looks like I need to hook whatever successful craft function gets called in here: https://github.com/BeeStation/BeeStation-Hornet/blob/3459e82a179d5030dd4ce76fc9b40668168d4488/code/datums/components/crafting/crafting.dm

**Comment by MarkSuckerberg** [comment]
That seems like it would be awfully spammy...

**Comment by bloons3** [comment]
Logged, not sent to admin console.

**Comment by MarkSuckerberg** [comment]
It would spam the logs, making them even more painful to look through for information regarding other things. I think there's far too much crafting done for it to need to be logged. Also, this over a scooter? *What?*

**Comment by Kerbin-Fiber** [comment]
Ctrl + F exists, I see no problem with it, especially if someone makes +12 IEDs and tries to lie.
