### ISSUE TITLE
[Bug]: Contractor Helmet slowing down

### ISSUE THREAD

**Issue by AdamUrgol** [BeeStation/BeeStation-Hornet#11886]
### Round Date

2024/11/15

### Round ID

sandbox

### Describe the bug

When character equips a Contractor Helmet they are slowed down. Just a Contractor Helmet without space suit.
Other helmets like EVA Helmet worn without an actually space suit do not slow down a character. 
The change in speed is small, just to make sure I was not imagining I measured time it takes me to move between hallway airlocks on Metastation where "Space Station 13" is written on the floor and without Contractor Helmet it's 4.5-5sec and with helmet its about 6.5sec

### What did you expect?

I expected to not be slowed down.

### Reproducible steps

1. Spawn Contractor Helmet.
2. Start walking
3. Equip Contractor Helmet
4. See your moving slower

**Comment by Tsar-Salat** [comment]
Yeah this shit makes zero sense

![image](https://github.com/user-attachments/assets/1f2e45ce-3606-403d-98c0-d558d6f7ea39)

**Comment by PowerfulBacon** [comment]
That's probably just a bug from copy and pasting the stats, no other helmets should apply slowdown
