### ISSUE TITLE
Singu eats emitter field???

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#1189]
Issue reported from  Round ID: 12414 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 512.1488

So i build a Singu with field generators and all and it worked out just fine first the emitters created a field i got the PA working and stuff then the singu was created and decided to eat right trough the field like it was just a normal wall 2 field tiles got eaten away and the singu just got out like nothing and began eating the station funny thing is between those 2  field generators was still a field line but 2 parts of it were missing while the rest was still there.
And all the other field parts where fine well until the singu was big enough to rip them from their anchoring after it got out

**Comment by ivanmixo** [comment]
Singularity starts eating walls and stuff if it gets too large, ignoring the fields.
