### ISSUE TITLE
Detective has no access to security records.

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#11891]
The detective has no access to the security records, they cannot view or update the notes of people via the secHUD and cannot change the arrest status of people.

They should be able to perform these actions as a member of security who has the job of investigating and discovering criminals.

**Comment by Marshmellow105** [comment]
likely due to the testmerged TGUI records

**Comment by XeonMations** [comment]
Tested on local, detective has access to security records via console and not sechud. Fixing.

**Comment by XeonMations** [comment]
Fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/11545/commits/96c1efdf03e955baa0653ff14681b1613f4b1173

**Comment by PowerfulBacon** [comment]
Thank you for investigating
