### ISSUE TITLE
Remove mass edit vv feature?

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#11915]
I do not see the exact purpose of this edit.
this is very dangerous option, and a mistake of an admin can break the whlle thing of that var.
just writing anyway. I need to know if it's worth to exist.

**Comment by h42-real** [comment]
I've used it before for bus, but I agree that it doesn't need to be a main option when in vv, especially with how dangerous it is.

**Comment by Dejaku51** [comment]
if you want to mass edit vv then use sdql smh
