### ISSUE TITLE
Violent screen shaking with no IC reason.

### ISSUE THREAD

**Issue by George-Apetrei** [BeeStation/BeeStation-Hornet#1193]
Round ID: 12500
Character: Phyllis Pretzel
Description:

Came back from lavaland, I went there with no meson and sometimes I took off my O2 supply so it's to be expected that I had hallucinations, however I only had one: The moment I landed with the mining shuttle back in cargo, bubblegum suddenly appeared and shook the screen and made a lot of noise, which is whatever.

The problem is that the screen shaking never stopped, it made it impossible to properly play the game as I could not reliably click on anything and it was highly nauseating.The link I will put here is to a download website where I uploaded a GIF I made of the screen shake. File is 20mb so it's above the maximum for github.

The link: https://gofile.io/?c=Avqz2d

I managed to get in a sleeper and ghost, after which all of the screen shaking stopped, I spawned as a hotel staff after and there was still no screen shake. So it must have been a character only bug because the hallucination, my guess.

**Comment by Kerbin-Fiber** [comment]
I think it has more to do with the fact that you were addicted to nicotine and the chat shows that you were in the withdrawal stage.

I play with RDS 24/7 and never have had my screen shake forever after bubblegum attempts to tackle me
