### ISSUE TITLE
[Bug]: Cannot interface with AI radio

### ISSUE THREAD

**Issue by Billcyferka** [BeeStation/BeeStation-Hornet#11931]
### BYOND Version

515.1614

### Round Date

2024/11/23

### Round ID

50745

### Test merges

- 9124

### Describe the bug

Transciever-Settings verb does not open any GUI.

### What did you expect?

I expected the radio gui to pop up

### Reproducible steps

1. Be AI
2. Go to AI Commands verb tab
3. Click "Transciever Settings"

**Comment by XeonMations** [comment]
Probably caused by https://github.com/BeeStation/BeeStation-Hornet/pull/11911 . Will check it out.
