### ISSUE TITLE
[Bug]: Downloaded remote signaler program doesnt work.

### ISSUE THREAD

**Issue by AdamUrgol** [BeeStation/BeeStation-Hornet#11952]
### Round Date

2024/11/28

### Round ID

sandbox

### Describe the bug

If you start as scientist you have remote signaler already on PDA installed and it works.
If you don't and you download it on PDA it doesn't work. It shows frequency of NaN khz and undefined code.
If you change these values, they go back to what they were at start so NaN and undefined and you cannot use it.
![image](https://github.com/user-attachments/assets/6b4fa6ca-78c4-48f2-b83e-d7469798ae96)

### What did you expect?

I expected 145.7 khz and code 30 on opening program and I expected to be able to change values

### Reproducible steps

1.Start as scientist, open PDA and see remote signaler working.
2. Start as not scientist, open PDA download remote and see it not working.

**Comment by AdamUrgol** [comment]
Wow so expensive 250 credits. Anyway, should I delete this issue?

**Comment by AdamUrgol** [comment]
Also there could be some message that remote signaler program is not working, because integrated radio card is not installed

**Comment by XeonMations** [comment]
I agree, there should be one.

**Comment by AdamUrgol** [comment]
should i make new issue or as @Dejaku51 to reopen?

**Comment by Dejaku51** [comment]
i can add that in my NTnet/modpc changes

**Comment by AdamUrgol** [comment]
hurray

**Comment by Dejaku51** [comment]
no need for the issue
