### ISSUE TITLE
[Bug]: Grinders are NOT working

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#11978]
### Round Date

2024/12/3

### Round ID

50855

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 1b8f225789](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10897: '[PORT] Follows up TG's atom_hud system' by EvilDragonfiend at commit 51f8edef4f](https://www.github.com/beestation/beestation-hornet/pull/10897)

### Describe the bug

If you try to grind/juice any fruit, this message appears:
![grinder](https://github.com/user-attachments/assets/8d506329-ba8a-4b35-b0e0-b26e6bd046ab)

The grinding sound and animation plays but once it finishes, it just ejects the fruits back as it was.

I'm unsure how this affect the medical-side of beakers-grinding but could face the same issue

### What did you expect?

I expected to grind!!

### Reproducible steps

1. Grab a fruit and beaker
2. Place it on the grinder
3. You'll hear the sound and see the animation however it doesn't work!

**Comment by Dejaku51** [comment]
likely caused by https://github.com/BeeStation/BeeStation-Hornet/pull/11770

**Comment by Dejaku51** [comment]
@XeonMations

**Comment by XeonMations** [comment]
Fuck.

**Comment by Dejaku51** [comment]
> Fuck.

you can do that stuff later, first fix the grinders
