### ISSUE TITLE
[Bug]: Grinders are NOT working 2 Electric Boogaloo(Juicing Edition)

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#11987]
### Round Date

2024/12/3

### Round ID

50855

### Test merges

[#9124: 'Enable serverside 515.1614' by Crossedfall at commit 1b8f225789](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#10897: '[PORT] Follows up TG's atom_hud system' by EvilDragonfiend at commit 51f8edef4f](https://www.github.com/beestation/beestation-hornet/pull/10897)

### Describe the bug

While i did report #11978 which was solved on #11979 unfortunately... It didn't solve the juicing option, only the grinding so um..

PLEASE MAINTAINERS DON'T KILL @XeonMations It was a small confusion but Marina helped clear it out

### What did you expect?

I expected to get juice!

### Reproducible steps

1. Grab fruit and beaker
2. Put it on machine, select juice
3. nothing!

**Comment by PowerfulBacon** [comment]
I don't even know why grinders have 2 different modes in the first place, I never knew juice ever did anything useful at all

**Comment by XeonMations** [comment]
![image](https://github.com/user-attachments/assets/2ab1236b-41f1-4750-9ba4-27cd7b1a1d1e)

fascinating.
