### ISSUE TITLE
Delta station SM Emitter reflectors on roundstart are false aligned

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#1198]
Its very simple for some reason Deltastation is the only station where the Reflectors for the SM are misaligned at roundstart no idea why but you have to seriously realigne all the Reflectors to even start the SM and that takes quite some time every round I understand making it a bit more setup and difficult but seriously at least like half the Emitters should be able to fire at the Sm without you having to Realigne every single Reflector so that it actually works. It takes a lot of time to do so and isn't really something you want to do for 20 minutes every roundstart  just to get the SM started

**Comment by MNarath1** [comment]
Also i am pretty sure that it was normal some time ago no idea why it changed

**Comment by Mat05usz** [comment]
Well for me this is a pretty good issue, those emitters really don't have to be placed like shit, as they do now.

**Comment by Kerbin-Fiber** [comment]
This is how it's been since Delta was mapped in 2016. https://github.com/tgstation/tgstation/pull/22066

**Comment by ivanmixo** [comment]
This may be intentional? Maybe?
