### ISSUE TITLE
Exercise only affects stun effect duration and not stamina damage.

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#12018]
Also exercise training only affects ground stun duration and not stamina damage taken.

**Comment by BarteG44** [comment]
how much should the stamina damage be reduced by for 100% exercised? with what i'm testing right now it takes 3-4 disabler shots to take down a naked unexercised person and 100%  increases that to about 8 shots

**Comment by PowerfulBacon** [comment]
Seems about right, max level should provide 50% resistance
