### ISSUE TITLE
[Bug]: Hot Chocolate Recipe Not Working

### ISSUE THREAD

**Issue by Mlokingbird** [BeeStation/BeeStation-Hornet#12010]
### BYOND Version

515.1647

### Round Date

2024/12/09

### Round ID

50919

### Describe the bug

During this round I was playing the bartender, and trying to make a Peppermint Patty to fulfill one of the round's bounties. I got the cocoa from botany, and ground it up as normal in the grinder to make the Hot Chocolate component of the drink. When I went to combine the cocoa powder with the water (at 10u cocoa powder to 50u water, per the recipe on the wiki) there was no reaction, and the two ingredients remained separate. I subsequently tried heating the mixture, and using the mix function on the grinder, but nothing worked.

### What did you expect?

I expected the 10u cocoa powder and 50u water to combine and create Hot Chocolate.

### Reproducible steps

1. obtain necessary ingredients (cocoa powder and water in a 1:5 ratio)
2. combine ingredients in a container

**Comment by Shiraizawa** [comment]
The wiki is out of date. 
It uses milk and cocoa instead and doesnt result in 5 instead of 6 as it says there.

```
/datum/chemical_reaction/hot_cocoa
	name = "Hot Coco"
	results = list(/datum/reagent/consumable/hot_cocoa = 6)
	required_reagents = list(/datum/reagent/consumable/milk = 5, /datum/reagent/consumable/cocoa = 1)
	required_temp = 320
```

Updated the wiki to reflect the code.

**Comment by Mlokingbird** [comment]
Thank you for letting me know! I'll see if there's anything else on the wiki that needs updating, as well. I use that guide a lot.

**Comment by Shiraizawa** [comment]
Let me know if you need anything updated if you don have an account. Ignore the missing icons on the page, already asked someone about it how I could add them.
