### ISSUE TITLE
[Bug]: Winter Echo Has A Hostile Tree Problem (And Atmos issue)

### ISSUE THREAD

**Issue by Programs-The-Station** [BeeStation/BeeStation-Hornet#12039]
### Round Date

2024/12/15

### Test merges

 #12024

### Describe the bug

Winter Echo has a hostile mob spawner that only spawns Icewing Watchers and the Hostile Pine trees.

For a low pop map, this causes lots of problems, as there are exactly 1 non-hostile mob type that is spawned (and the pine trees are annoying to deal with and hurt), so they spawn very frequently.

```
	fauna_types = list(
		/mob/living/simple_animal/crab,
		/mob/living/simple_animal/hostile/tree,
		/mob/living/simple_animal/hostile/asteroid/basilisk/watcher/icewing
	)

``` 

Additionally, the wooden barricade keeps the front door open, leading to lobby (and lower levels) freezing very rapidly (since outside is -50)

### What did you expect?

I expected less murderous trees, and Echo not getting almost irreversible damage to atmos in 20 minutes.

### Reproducible steps

1. Load Echo
2. Walk outside
3. Be murdered by the Treants.

**Comment by Therealdoooc213** [comment]
@BriggsIDP I swear bro fix this 😭

**Comment by Dejaku51** [comment]
> Be murdered by the Treants.

Echo was like that always, just replaced gorillas with trees

**Comment by Programs-The-Station** [comment]
That round must have been godlike rolls on random spawn, or security was very stupid (leaning towards the latter). Saw at least 6 encounters with trees in the first 20 minutes, once with 3 trees at once near arrivals. 

Also, don't make issues when sleep deprived....

**Comment by Therealdoooc213** [comment]
> > Be murdered by the Treants.
> 
> Echo was like that always, just replaced gorillas with trees

No, not at all. Gorillas had specific spawns
