### ISSUE TITLE
[Bug]: Syndicate Surplus Crate giving 10TC of items

### ISSUE THREAD

**Issue by lowwy** [BeeStation/BeeStation-Hornet#12048]
### Round Date

18-dec-2024

### Round ID

51009

### Test merges

#9124
#10741

### Describe the bug

I used a 20TC surplus crate, I received:
Protocol CRAB-17 Phone [8TC]
Syndicate Playing Cards [1TC]
Chameleon Combat Gloves [1TC]

Description says I should get 50TC worth of goodies at least

### What did you expect?

I expected not to be scammed by the Syndicate and get at least 50TC worth

**Comment by EvilDragonfiend** [comment]
that sounds you picked a lottery one. it has 5xN value.

**Comment by lowwy** [comment]
There's a lottery one?! I'll go double check what I picked, but if that's the case it might be that...

**Comment by lowwy** [comment]
> that sounds you picked a lottery one. it has 5xN(N=1 to 20) value.

Seems like this was the case, I picked the wrong one by mistake.

**Comment by PowerfulBacon** [comment]
I thought the lottery one glued a mask to your face if you rolled 10TC

**Comment by EvilDragonfiend** [comment]
> I thought the lottery one glued a mask to your face if you rolled 10TC

5 TC is the lowest one, and curses you.
