### ISSUE TITLE
IPC posibrains need to be put inside an mmi

### ISSUE THREAD

**Issue by constatinus** [BeeStation/BeeStation-Hornet#1206]
This may be a feature request actually, but because most people just look at my posibrain and see 'perhaps it will regain some of its luster later' they think im out/ssd and cant borg me and just leave me. The only thing that's needed is to put my ipc posibrain in an MMI. Can it somehow be made more functional so that it actually worked or the message on the ipc brain showing a hint to put it inside an mmi?

**Comment by zeskorion** [comment]
> This may be a feature request actually, but because most people just look at my posibrain and see 'perhaps it will regain some of its luster later' they think im out/ssd and cant borg me and just leave me. The only thing that's needed is to put my ipc posibrain in an MMI. Can it somehow be made more functional so that it actually worked or the message on the ipc brain showing a hint to put it inside an mmi?

when ipcs were first added, they tried to make them work like normal posibrains. However, it was far too complicated. A desc change to the brain could be added easily though

**Comment by MarkSuckerberg** [comment]
#1018
