### ISSUE TITLE
[Bug]: Linda pipes air supply and scrubbers together at round start.

### ISSUE THREAD

**Issue by JReese3** [BeeStation/BeeStation-Hornet#12107]
### Round Date

2024/12/30

### Round ID

51157

### Test merges

- #9124 
- #11813

### Describe the bug

At round start scrubbers and air supply are part of the same pipe net.  This appears to be due to how the airlocks are piped. It is a lot of mess to dismantle all of the airlocks to fix this in a round, and makes the job of atmospherics technician impossible, you can not replace air as it pulls from and replaces with from the same pipe net.

Pipe layouts all need to modified to support Linda before this a usable system.

### What did you expect?

I expected scrubbers and air supply to not be a part of the same pipenet at round start.  

### Reproducible steps

Join a match with access to atmospherics or just an analyzer, check pipe nets for scrubbers and air supply.  You will see the same pipe net for both lines.

**Comment by HowToLoLu** [comment]
This was fixed and already addressed for boxstation, will check on the other stations too

**Comment by HowToLoLu** [comment]
![image](https://github.com/user-attachments/assets/7fb3705e-eb86-4b1a-ab03-cf5714ed3ebd)
Yeaaaah, noticed it on fland as well which was that round; sorry you had to deal with that.

**Comment by HowToLoLu** [comment]
> At round start scrubbers and air supply are part of the same pipe net. This appears to be due to how the airlocks are piped.
And no this is not airlocks at all, this is the old layer adapters auto bridging distro and waste when put parallel to them, since they're still in the game and considered "omni" layer adapters now.

**Comment by JReese3** [comment]
I'll be honest pipe attachment is wonky as hell... same color same layer and pipes refuse to T to devices in some cases... I'm in favor of scrapping Linda.

**Comment by JReese3** [comment]
Confirmed Meta Station no longer merges the distro to scrubber.

**Comment by HowToLoLu** [comment]
> I'll be honest pipe attachment is wonky as hell... same color same layer and pipes refuse to T to devices in some cases... I'm in favor of scrapping Linda.

Sorry to hear that; but there is no plans to go back on linda at all, if anything gets us away from auxmos.

**Comment by HowToLoLu** [comment]
> Confirmed Meta Station no longer merges the distro to scrubber.

also it's going to be different station to station; meta station never had an issue with this because it's solely a mapping issue

**Comment by JReese3** [comment]
Can we get rid of lindas pipes?

**Comment by JReese3** [comment]
> > Confirmed Meta Station no longer merges the distro to scrubber.
> 
> also it's going to be different station to station; meta station never had an issue with this because it's solely a mapping issue

This morning Meta was the first station I noticed with merged piping

**Comment by JReese3** [comment]
I'm also noticing the piping of the airlocks has changed.

**Comment by HowToLoLu** [comment]
> Can we get rid of lindas pipes?

Currently not really planned, but there's no opposition to anyone willing to code a removal of smart pipes after linda is merged
