### ISSUE TITLE
Plumbing might be broken

### ISSUE THREAD

**Issue by rublax** [BeeStation/BeeStation-Hornet#1217]
Issue reported from  Round ID: 12724 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1511

![image](https://user-images.githubusercontent.com/39571296/74999047-867d3900-5428-11ea-8a4a-e689511e14b5.png)
The reagent in the tank isn't going into the output gate. I could just be completely stupid, but I cannot use the output gate. I've plunged the whole thing and nothing. Both are secured, I triple checked.

**Comment by rublax** [comment]
Also tried with a pill press, and doesn't work.
It seems the tank doesn't want to output anything through the blue pipe.

**Comment by rublax** [comment]
![image](https://user-images.githubusercontent.com/39571296/74999366-774abb00-5429-11ea-8636-bd804bb1b996.png)
This, however, fills the output gate.

**Comment by Kerbin-Fiber** [comment]
Just tested this, and uh, I think the pipe is backwards
![image](https://user-images.githubusercontent.com/31713423/75370629-a1193d00-5882-11ea-80a8-81084cabb12b.png)
