### ISSUE TITLE
Missing wire in MetaStation

### ISSUE THREAD

**Issue by Mat05usz** [BeeStation/BeeStation-Hornet#1229]
Issue reported from  Round ID: 12783 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 512.1488

MetaStation wiring problem.

So basically this is a small one, but there is a missing wire in medbay storage, which leads to the storage and medbay security post losing power. It's above the window between two doors leading to medbay storage.

**Comment by Kerbin-Fiber** [comment]
This is fixed in #1230 
should be closed

**Comment by Kerbin-Fiber** [comment]
closecloseclosecloseclosecloseclosecloseclosecloseclosecloseclosecloseclose
