### ISSUE TITLE
Bugged rollerbed heirloom

### ISSUE THREAD

**Issue by Mat05usz** [BeeStation/BeeStation-Hornet#1242]
Issue reported from  Round ID: 12877 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 512.1488

I don't know if EMTs or MDs get this heirloom, but I saw that bug while playing as brig phys, you get rollerbad heirloom, then you use it so it unfold on the ground and suddenly when you take it back to backpack it doesn't recognize it as previous heirloom, so it counts as if you lost it till the end of the shift.

**Comment by qwertyquerty** [comment]
This is because when you unfold it, it deletes itself. I'm just going to remove this from the heirloom list
