### ISSUE TITLE
The follow icon on mhelp messages doesn't work

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#127]
Basically, you know how theres a "F" next to nearly anything that happens that you can click on and your ghost teleports to it, mhelp messages also have that F, but if you click it nothing actually happens.

**Comment by qwertyquerty** [comment]
Pretty sure that's only for ghost mentors

**Comment by MACIEKBAKI** [comment]
Even as an admin answering a mentorhelp when observing that does not work

**Comment by yorii** [comment]
Not stale, issue in mentorhelp.dm line 99-100:
```
	if(include_follow)
		. += " (<a href='?_src_=mentor;mentor_follow=[REF(M)];[MentorHrefToken(TRUE)]'>F</a>)"
```

Should be more similar to say.dm line 36-38
```
	var/link = FOLLOW_LINK(src, to_follow)
	message = compose_message(speaker, message_language, raw_message, radio_freq, spans, message_mode)
```

**Comment by francinum** [comment]
Not even the problem.

`/datum/mentor` has no `topic()` for that code to call because it was all stolen from admin.

The link isn't even wired up to be checked, verified, or do anything.

**Comment by PowerfulBacon** [comment]
Alive mentors shouldn't be able to see other players, although maybe for ghosted mentors
