### ISSUE TITLE
Finish Xenobiology Slime Crossbreeds

### ISSUE THREAD

**Issue by Rukofamicom** [BeeStation/BeeStation-Hornet#1290]
Request made specifically so I can attach a bounty to it:
**Join this discord server**: http://discord.gg/Q32uPCS

Requesting the following dominant slime crossbreeds to be completed and implemented: Bluespace, Sepia, Red, Green, Pink, Gold, Oil, Black, Light Pink, Adamantine, Rainbow. Additional information on each family can be found in the discord server linked above, as well as discussions with those involved in the bounty and head coders with Veto power over specific ideas.

**Comment by zeskorion** [comment]
Fuck it, i'll bite. I've been planning on fuckin with xenobio for awhile anywho...

**Comment by Carbonhell** [comment]
This bounty was posted in coderbus, i assumed it was free to take? If it still is, I'll do it
RE:nvm, too many people working on this already, contact me if noone manages to do it.

**Comment by Rukofamicom** [comment]
Is there an easy way to split the bounty up per breed, so I can give partial bounty out as chunks are completed?

**Comment by zeskorion** [comment]
i'm gonna unassign this because, as it is, I'm not available enough to complete this in a quick manner

**Comment by Crossedfall** [comment]
@Carbonhell -- It's open again if you want it.

**Comment by Carbonhell** [comment]
Will do it with Reere

**Comment by Rukofamicom** [comment]
@Crossedfall Carbonhell and Reere have backed out, the bounty isn't high enough.

**Comment by Useroth** [comment]
Are there any more instructions regarding effects of the cross-breeds that you would like to see, or is it the "think everything up yourself and make sure it's balanced" kinda bounty?

**Comment by PowerfulBacon** [comment]
Not going in for sure, but I might try to make a few see what needs to be done, cause this stuff seems pretty fun to add.

Also Q with bounties, is it the first person to say they want to do it or is it anyone works on it until someone gets their PR accepted?

**Comment by Crossedfall** [comment]
> 
> 
> Also Q with bounties, is it the first person to say they want to do it or is it anyone works on it until someone gets their PR accepted?

It's free for anyone to work on until a PR gets accepted. Commenting here just makes it more obvious that you're interested in working on the issue.

**Comment by Rukofamicom** [comment]
http://discord.gg/Q32uPCS

This is a discord channel I created with the other person who has contributed to the code bounty. 
This has slimes divided by family as well as our personal ideas for what they should do.

Additionally to make the bounty both easier to complete and easier to disperse amongst multiple people involved, more funding is going to be added to the bounty in the near future - an individual reward for each family completed with the initial bounty being divided amongst all contributors based on how many families they completed.
