### ISSUE TITLE
SMES built with slime cores instead of power cells do not self-charge at all

### ISSUE THREAD

**Issue by Rukofamicom** [BeeStation/BeeStation-Hornet#1325]
Tested at variable output and input power levels, including turning the SMES to output no power
Tested replacing the power cells in existing SMES with RPED
Tested building SMES from parts instead of using RPED
Tested with both types of slime cores.

**Comment by Mat05usz** [comment]
I know what's going on, but since this is first issue I'm looking at it might take a while.
