### ISSUE TITLE
Squidpeople are bland

### ISSUE THREAD

**Issue by ToasterBan** [BeeStation/BeeStation-Hornet#1358]
---
name: Squidpeople rework
about: Squidpeople are pretty bland and are practically unfinished, some ideas I have are, having the chameleon gene on them always, being able to crawl through wents when naked and having some sort of suction cups ability which stops them from dropping items and slipping

---

**Comment by jlsnow301** [comment]
>chameleon gene 

They can change colors currently
>crawl through vents

Could not be balanced
>dropping items and slipping

In place currently, their grabs are harder to resist, they are slip resistant except on shards

Keep in mind the philosophy of the nonhumans is meant not to be better than humans at any point, thus each nonhuman race is meant to be less than average
I agree they are unfinished but I personally won't be giving them anything other than cosmetics at this point

**Comment by eeSPee** [comment]
Maybe allow them to regrow limbs, but take brute damage to chest when doing that.
