### ISSUE TITLE
Circuit tank slots cause damaging the assembly on tank insertion.

### ISSUE THREAD

**Issue by St0rmC4st3r** [BeeStation/BeeStation-Hornet#138]
So, I was debugging my machine and inserting/ejecting the tanks, and with each insertion attempt, there was a hit sound. At some point, the assembly just disappeared with all the inserted tanks. I have no idea if this issue only occurs with the tanks slots though.

**Comment by Toxici11i** [comment]
happens with gunslots etc too

**Comment by MACIEKBAKI** [comment]
I'll look into this sooner or later.

**Comment by yorii** [comment]
I don't even know where the circuit machinery is.

**Comment by Crossedfall** [comment]
> 
> 
> I don't even know where the circuit machinery is.

The specific module they're talking about is here.

https://github.com/BeeStation/BeeStation-Hornet/blob/ba40cb637d38cb9520b7a23c1cc0de53433dbf8d/code/modules/integrated_electronics/subtypes/atmospherics.dm#L693-L713

**Comment by aidan-bowman** [comment]
circuit tanks have been completely removed, can a maintainer close this?
