### ISSUE TITLE
Filter 2.0 

### ISSUE THREAD

**Issue by Crossedfall** [BeeStation/BeeStation-Hornet#1406]
Using this issue to track progress on the new filter.

The new filter (marked 2.0) should be:

- [ ] Toggleable at the client/user level
- [ ] Provide in-line censoring of select words from a list configured by the host
- [ ] Less intrusive and overbearing for the players

**Comment by qwertyquerty** [comment]
nawww laaddd

**Comment by MarkSuckerberg** [comment]
This was and still is a really good idea and I think someone should look into this. People would prefer the filter being like this SO much more than how it's implemented now, but that's just my opinion.
