### ISSUE TITLE
ghost glasses can see sentient disease

### ISSUE THREAD

**Issue by FractalBobz** [BeeStation/BeeStation-Hornet#1414]
Issue reported from  Round ID: 13898 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 512.1488

You can see in the chat for the round. Silas could see sentient disease with ghost glasses.
What the heck is this object? And also, is that intended?

**Comment by MarkSuckerberg** [comment]
🦀 I knew people would notice eventually 🦀

**Comment by St0rmC4st3r** [comment]
Zesko said that **It Is A Feature**.
Problem solved, you may close the issue.

**Comment by zeskorion** [comment]
optical ecto scanners can see whatever a ghost can see. this includes smugglers satchels, ai eye, sentient diseases, blobs, etc. this intended

**Comment by FractalBobz** [comment]
Fun feature. I'll have to find them some day.
