### ISSUE TITLE
Improve highpop by increasing the number of jobslots & equipment

### ISSUE THREAD

**Issue by ike709** [BeeStation/BeeStation-Hornet#1416]
Currently, the number of jobs are pretty limited during highpop. One of the main limiting factors is the availability of equipment. There's no reason to have 12 Engineers if there's only 3 hardsuits and a couple of equipment lockers/vendors. On the flipside, we don't want to add 20+ lockers to every department.

The most straightforward solution would be to expand Security's existing method of equipment scaling to other jobs. Currently, a different number of security lockers are spawned based on the number of people playing security officer. This relies on pre-mapped landmarks. Ideally, this would be expanded to include several other jobs. Considering that Delta is the primary highpop map, Delta is the main map that needs to be edited with these proposed locker landmarks.

This is not feasible for some jobs that require additional machinery or a workspace (such as chemists or chefs) without additional remapping, which should be addressed separately.

Here's a short, likely non-exhaustive list of jobs we believe could easily benefit from this proposed system and allow us to open up more job slots:

Botanist (Only by a little, botany is already pretty crowded)
Station Engineer (Hardsuits need to scale as well, but not all engis should be guaranteed hardsuits)
Atmos Tech
Security Officer (Make more potential lockers available)
Shaft Miner
Janitor
Medical Doctor (Scaling sleepers would be needed moreso than equipment lockers)

**Comment by ghost** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/1415

very relevant PR

**Comment by ike709** [comment]
This also entails more spawn landmarks.

**Comment by eLeCtrOssSnake** [comment]
Yes, super totally super super agreed. It makes me play assistant even when I am done greytiding.

**Comment by eLeCtrOssSnake** [comment]
Maybe would somehow contribute to this contribution, but due to how uncommon this kind of move is, that's probably not gonna happen, if @ike709 won't sort it out completely to a straight line of things to do.

**Comment by eLeCtrOssSnake** [comment]
Although some stuff is doable with increasing job slots, I wouldn't detach it from mapping, I would rather do it all at once.

**Comment by ItsTisme** [comment]
Id say 3-4 botanists is more then enough on almost all maps, especially considering hydro really doesn't need man power in any capacity unlike engineering/medical.

**Comment by ike709** [comment]
Fixed by popcap.
