### ISSUE TITLE
Game Crash after ancient helm is removed from box

### ISSUE THREAD

**Issue by nikk735** [BeeStation/BeeStation-Hornet#1418]
gonna be quick as to not waste time, spawn as chaplain get remote from vending machine, click Stone Templar remove helmet from box and put in hand, game crash. you also cant put the helmet back into the box, i suspect the item size is declared wrong and crashes.

**Comment by nikk735** [comment]
also done on pubbystaion if relevant

**Comment by Crossedfall** [comment]
Do you have the round ID?

**Comment by nikk735** [comment]
No I don’t but it was right after I posted this
