### ISSUE TITLE
[Bounty] Add an icon to brainwash victoms adminhud

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1423]
Feature requests are not handled in the repository. The best place to discuss these ideas would be on the /tg/station 13 forums here: https://tgstation13.org/phpBB/viewforum.php?f=9&sid=5153c1c704a4fb1006bf7a265e45e03f

**Comment by PowerfulBacon** [comment]
I'll have a try at this, seems pretty simple. Hardest bit will be the icon design

**Comment by Crossedfall** [comment]
Resolved by #1425

**Comment by bloons3** [comment]
unclose since it seems to have broken BountySource
