### ISSUE TITLE
Merge Bounties

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1424]
Merge these items.
If unable to merge a specific item, please explain why.
You will still likely qualify for bounty.

https://github.com/tgstation/tgstation/pull/47802 Agent ID logging
https://github.com/tgstation/tgstation/pull/47802 Atmos tank logging
https://github.com/tgstation/tgstation/pull/47525 Specific logging of door bolting
https://github.com/tgstation/tgstation/pull/46333 Better grenade logging 
https://github.com/tgstation/tgstation/pull/46330 Tomato logging (seen 2x of them used to grief)
https://github.com/tgstation/tgstation/pull/45677 Logging of door crushing

**Comment by bloons3** [comment]
https://github.com/tgstation/tgstation/pull/45697
Correct grenade logging link

**Comment by bloons3** [comment]
Derp:
https://github.com/tgstation/tgstation/pull/48627
Correct link to Agent ID logging

**Comment by Bastian0930** [comment]
i'll try my hand at this tomorrow.
