### ISSUE TITLE
Devil Law changes are not admin logged

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1426]
Devil Law changes are not admin logged
If you get AA from a devil, the AI gains an Ion law. This changed law isn't logged anywhere, which can be annoying when trying to resolve a he-said-she-said situation.

Please add some sort of logging to the Devil Law creation, either by adding Ion law changes (which Devil calls) to the Admin Investigate AI law changes, or a specific devil log addition.

**Comment by bloons3** [comment]
![image](https://user-images.githubusercontent.com/3241376/77846803-35c2d380-717e-11ea-80b7-003688acdc4f.png)
The law change should also be logged into game.log (or whichever log normal AI laws are logged in)

**Comment by St0rmC4st3r** [comment]
I'll do it.

**Comment by bloons3** [comment]
closed, accepting https://github.com/BeeStation/BeeStation-Hornet/pull/1431

**Comment by Crossedfall** [comment]
PR hasn't been merged yet.
