### ISSUE TITLE
PAIs are hilariously broken and don't log shit

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1446]
>be PAI
>get turned on
>tell owner that someone is a traitor
>owner ahelps this
>no actual pai CKEY
>no actual log in game.log of the words
lmao

**Comment by Bastian0930** [comment]
Shooould be easy to log. I'll take a look at it, since I just made a pr for a fuck ton of logs.

**Comment by Bastian0930** [comment]
On second thought, I've got something i wanna port just for my own personal project.
