### ISSUE TITLE
Box station- Incerator Airlock not working

### ISSUE THREAD

**Issue by Emiliapains** [BeeStation/BeeStation-Hornet#1463]
## Reproduction:
So the incinerator airlock wont work due to it having no vent and i would like box station to be removed from the map selection until its fixed!
![Screenshot_30](https://user-images.githubusercontent.com/63119131/78388636-4093c300-75d9-11ea-9af5-268dbe6735b4.png)

**Comment by ivanmixo** [comment]
What do you mean it won't work?

**Comment by Emiliapains** [comment]
> What do you mean it won't work?

I mean i cant open the outer airlock because there is no vent to change the pressure so i cant get into the inner airlock to add more scrubbers to speed up to trit collection process and when i try to open the outer airlock and im in the airlock i cant get out

**Comment by ivanmixo** [comment]
You could just hack the door open, this isn't really a map breaking issue.

**Comment by nikk735** [comment]
ask ai to force open or hack open or deconstruct door or break the door or beg CE to give you jaws of life

**Comment by jlsnow301** [comment]
Noted, fixed in #1712
![imgur img](https://i.imgur.com/CVXFklj.png)
