### ISSUE TITLE
PDA ghost bug

### ISSUE THREAD

**Issue by HorseShoeMan** [BeeStation/BeeStation-Hornet#1467]
Issue reported from  Round ID: 14213 (BeeStation Sage - MRP For Everyone Presented by PapaJohns™️!)

Reporting client version: 513.1517
be me antag die 
have my pda in my pocket and the traitor menu open 
now I'm a ghost 
see that it lets me buy shit still so I do it spawned stuff where my ghost was standing I spawned a 
pizza bomb and gorilla injector 
round id 14213

**Comment by ivanmixo** [comment]
Tried this out on a private server, I can't spawn anything while dead with my uplink. Odd.
