### ISSUE TITLE
Ethereal Update

### ISSUE THREAD

**Issue by Oblivire** [BeeStation/BeeStation-Hornet#1469]
I'd like to request an update to Ethereals on Bee, to bring them up to date with the Ethereals on /tg/.  I believe that would include these pull requests from /tg/, maybe a few I've missed:
https://github.com/tgstation/tgstation/pull/48309
https://github.com/tgstation/tgstation/pull/48321
https://github.com/tgstation/tgstation/pull/48550 <-- This feature is incredibly cool, allows Ethereals to drain and charge APCS.
https://github.com/tgstation/tgstation/pull/48573
https://github.com/tgstation/tgstation/pull/48718
https://github.com/tgstation/tgstation/pull/48920
https://github.com/tgstation/tgstation/pull/49253
https://github.com/tgstation/tgstation/pull/49934
https://github.com/tgstation/tgstation/pull/50084

Rather than going through all these PRs individually, it might be better to see what files were changed, and attempt to copy them over.

**Comment by jlsnow301** [comment]
These are all pretty valid

**Comment by Oblivire** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/1503 Nice, this was the main one I was interested in, sorry I missed it being added.  I'll leave this open in case tg comes back up and people want to add the others.  I think of note are ethereals having a unique tongue that adds a "zzt" similar to how lizards are, body temperature, and unique languages for each race.

**Comment by wesoda25** [comment]
fyi #48321 had a pretty significant effect on the game especially with races like lizards (they get fucked by cold shit) so its a bit misleading to only mention ethereals

**Comment by wesoda25** [comment]
wait this isnt even a pr nvm (but yeah still keep in mind thats a big change)

**Comment by yorii** [comment]
I can do all of these if required. (I've already done a few)
