### ISSUE TITLE
Abductor Change

### ISSUE THREAD

**Issue by Oblivire** [BeeStation/BeeStation-Hornet#1470]
I would like to request that abductors become a more common ghost role, by replacing the resting contraption and lower table with alien-designed (or not) sleeper pods, similar to other ghost roles in the spawner menu.  The tool on the lower table could be moved to the left.  This should probably only happen in 50% of matches, with the other half having the original layout.  It also might be smart to prevent them from spawning during malf AI rounds.  The scientist is capable of achieving their objective by themselves, and so they should always spawn before the agent.

Why:  Abductors are an interesting mid-round antagonist, that aren't seen very often.  They by their design don't cause nearly as much havoc as other antagonists, and can actually be somewhat helpful to the crew, if they choose to be.  This would allow science to get to research alien surgery more often, and in my opinion, allow for more interesting gameplay.  I suggest making them not appear all the time, as getting carded as an AI every round would get old very quickly.

**Comment by esoop1** [comment]
This would likely cause a bunch of problems on LRP with post death grudges.

**Comment by Oblivire** [comment]
I can see that, now that you've mentioned it.  Perhaps it could be avoided by nerfing the sleeper ones a bit-  Like, the agent wouldn't get the alien energy gun, and the scientist could start with 15 minutes worth of pax in their blood.  That would make them unable to be lethal at a range, and for 15 minutes at both ranged and close with only one person, since if I remember correctly they can't use the station's guns.  Usually metagrudges are only one person, so making 2 a necessity would stop most of them, and they'd opt for the hotel peacekeeper, free golems, or ashwalkers instead, as they tend to use currently.

**Comment by jlsnow301** [comment]
#1473

**Comment by Oblivire** [comment]
While I noticed and appreciate that merged pull request, I think that the increase in chance of them happening isn't enough.  This being said, I haven't had much opportunity to play since it was merged, so I could be mistaken.
