### ISSUE TITLE
Add booing and other sitcom sound effects to the Clown's sound synthesizer.

### ISSUE THREAD

**Issue by CrackChaddington** [BeeStation/BeeStation-Hornet#1475]
From the forum post: [Lets add booing to clown's sound synthesize](https://forums.beestation13.com/t/lets-add-booing-to-clowns-sound-synthesizer/3471/6)

Clown synthesizer should have more audience reaction sound effects added to compliment the applause and laughter options. 

I put together a trimmed down version of some sound effects including:

audience-boo
audience-gasp
audience-ooh
audience-awww

Sound effects are all in `.ogg` format already.

[audience-sound-effects-trimmed.zip](https://github.com/BeeStation/BeeStation-Hornet/files/4432744/audience-sound-effects-trimmed.zip)

Pretty simple update, sound effect paths and definitions would just need to be added to the file [sound_synth.dm](https://github.com/BeeStation/BeeStation-Hornet/blob/66d1e599c77a25974a89ea02a966773c5865bae0/code/game/objects/items/devices/sound_synth.dm)

**Comment by nikk735** [comment]
sure seems easy enough

**Comment by Bastian0930** [comment]
oh shit @nikk735 you doing this? in the fourm post I said I was gonna do it

**Comment by nikk735** [comment]
Didn’t see the post my bad just saw this @Bastian0930 go for it
