### ISSUE TITLE
Beheading hangmen leaves them hanging.

### ISSUE THREAD

**Issue by Goshagosha** [BeeStation/BeeStation-Hornet#1476]
## Round ID:
Any past Nooses merge

## Reproduction:
Behead hanging people and they stay hanging. Looks ugly.

**Comment by ro5490** [comment]
oof, I'll look into this
currently you cant hang headless mobs so I'll add a check for that

**Comment by ro5490** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/1489
