### ISSUE TITLE
Certain explosions are not logged well

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1491]
![image](https://user-images.githubusercontent.com/3241376/78635667-5e2c8b00-786c-11ea-905c-06fa07590942.png)

![image](https://user-images.githubusercontent.com/3241376/78635692-6a184d00-786c-11ea-9102-da4dcd7bf371.png)

![image](https://user-images.githubusercontent.com/3241376/78635710-70a6c480-786c-11ea-9ae4-35cd0ea809b9.png)

Natural explosions do not have their creation event logged in their explosion. If the cause of a natural explosion were logged to alog before/during the explosion, it would make it easier to filter out grief from random events.

Requirement: Add a logging event to game.log/admin log when natural explosions explode.

Possible Deliverable:
ADMIN LOG: A pyro anomaly has exploded in Incinerator (151, 89, 2) (JMP)
ADMIN LOG: Explosion with size (1, 4, 16, 0) in Incinerator (151, 89, 2) (JMP)

Other Possible Deliverable:

ADMIN LOG: Explosion with size (1, 4, 16, 0) in Incinerator (151, 89, 2) (JMP)
ADMIN LOG: A pyro anomaly has exploded in Incinerator (151, 89, 2) (JMP)

**Comment by bloons3** [comment]
bounty source you lil shid
https://www.bountysource.com/issues/90859996-certain-explosions-are-not-logged-well

**Comment by Bastian0930** [comment]
I'll see if I can yoink this and get it done quickly.
