### ISSUE TITLE
Botany Self-Dispenser

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#1559]
The problem: Beestation rounds are SHORT. Like, 25 minutes short at times. An effective Botanist has to speed run tech storage or chemistry to steal a dispenser (optimally) in order to get chemicals needed to mutate plants and increase yield.

Possible solution: A wall mounted self-serve dispenser that fills 30u bottles of mutagen and saltpetre.

Why: This would make Botany a little less about breaking&entering and more about... Plants. Outside of box station it has little room for building chemical synthesizers, which people are definitely building now to compensate.

Shopping list of things:
1) wall mounted machine similar to pepper spray refiller or viro wall mounted fridge
2) dispenses unstable mutagen and saltpetre
3) EDIT: dispenses 30u bottles AND/OR fills containers but is pretty obvious about what it is dispensing
4) a somewhat-unique sprite
--optional--
5) put these in the maps yourself, else I can do it
6) tgui interface

**Comment by St0rmC4st3r** [comment]
@jlsnow301 is the bottle-dispensing part necessary? Botany usually have plenty of buckets.

**Comment by jlsnow301** [comment]
> @jlsnow301 is the bottle-dispensing part necessary? Botany usually have plenty of buckets.

I suppose not, but it's just a little more obvious what you're getting dispensed. If you wanted to do some insert-your-own-container method, please have some text message to announce what has or is being dispensed

**Comment by St0rmC4st3r** [comment]
@jlsnow301 so you want a universal dispenser? Or one for each chemical like pepper sprays will do?

**Comment by St0rmC4st3r** [comment]
Separate dispensers are ugly. I am doing the better one.

**Comment by jlsnow301** [comment]
No, ideally just one that has some capacity (or interface) to switch
between the two.

**Comment by St0rmC4st3r** [comment]
@jlsnow301 Will a limited mini-chem dispenser work? Can dispense large amounts, but the assortment is.... meh.
![image](https://user-images.githubusercontent.com/34888552/79529677-f3522f80-8075-11ea-9217-bcfc13b0a4de.png)

**Comment by jlsnow301** [comment]
Ideally wall mounted, and if it’s just chem dispenser it must have unstable
mutagen / saltpetre as options (ie not clicking Cl/P/Ra each time)
