### ISSUE TITLE
IPC Brains

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#1581]
## Round ID:
All

## Testmerges:
Current

## Reproduction:
IPC brains are currently bugged, 
1) Examining them displays lifeless even if they are sitting inside
2) Reinserting the brain into the IPC's chest will teleport it to dev room
3) (as kind of a request) this should be a little more obvious that it is not a positronic brain, at best another icon, at least something that says it will fit in an MMI.

**Comment by eeSPee** [comment]
There's also a bug with IPCs and autosurgeons.
