### ISSUE TITLE
Hyperfast battery charging and draining for Borgs

### ISSUE THREAD

**Issue by Mick1299** [BeeStation/BeeStation-Hornet#1596]
## Round ID:
~~AuStation, a downstream of Bee~~ Reproduced on BeeStation Sage, thanks Caecilius

## Reproduction:
Borgs are able to charge and drain incredibly fast by rapidly connecting and disconnecting from an energy source with the power connector. You can charge an empty bluespace battery in a Borg from 0 to full (40,000 charge) in 10ish seconds, or empty it in the same amount of time

1. Replace the Borgs battery with an empty one
2. recharge enough to allow for tool selection and use
3. Select the power connector, set it to draw mode
4. spam click on a power source, such as a full battery or a Borg charger, watch the charge number fly up by thousands at a time

For draining
1. Replace the Borgs battery with a full one
2. select the power connector, set it to charge mode
3. spam click an empty battery, watch the Borgs charge drain in seconds

I tested the numbers compared to sitting in a cyborg charger. For a bluespace cell, it takes 6 minutes to fully charge in an un-upgraded charger, and 1 and a half in a fully upgraded one. It takes 13 seconds to charge from 100 to 40,000 power using the spam click method. It takes 5 seconds to drain 40,000 charge into an empty bluespace battery.

This is only a guess, but I doubt this was intentional.

**Comment by TheNeoGamer42** [comment]
damn someone found it and finally decided to report it, sad

**Comment by Mick1299** [comment]
Found the issue, its relatively simple but i'm not well enough versed in github to submit a pr. If someone else wants to, feel free to pr it.

			while(do_after(user, 15, target = M, progress = 0))
				if(!user || !user.cell || mode != "draw")
					return`

				`if((M.stat & (NOPOWER|BROKEN)) || !M.anchored)
					break

				if(!user.cell.give(150))
					break

				M.use_power(200)

			to_chat(user, "<span class='notice'>You stop charging yourself.</span>")

There is no detection in the whole loop for if a robot is already charging from a power source. So by spam clicking the same power source, you cause multiple instances of the while loop to run at once, effectively increasing the rate that you charge based on how fast you can click.

The codes found in https://github.com/BeeStation/BeeStation-Hornet/blob/master/code/game/objects/items/robot/robot_items.dm lines 183 to 196
