### ISSUE TITLE
round end report shows up way too late

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#161]
when the round ends it takes the report a good 3 to 5 seconds to show up, which makes it possible that antags get their greentext taken away due to EORG

**Comment by CthulhuOnIce** [comment]
are you sure this is possible @BeloneX? Just because the report isn't generated doesn't mean the greentexts are discounted

**Comment by ghost** [comment]
@CthulhuOnIce  yep.

**Comment by qwertyquerty** [comment]
fixed
