### ISSUE TITLE
Broken russian messages

### ISSUE THREAD

**Issue by IDEXV** [BeeStation/BeeStation-Hornet#1624]
## Round ID:
Round ID: 15056

## Testmerges:
None.

## Reproduction:
Type something in russian as a mob: the first letter will be broken + if you are stammering, all letters will be broken. There are also broken russian letters on papers, in computers.

**Comment by St0rmC4st3r** [comment]
СС13 не рассчитан на полноценное использование кириллицы. Скорее всего это связано с глобальным списком допустимых для обработки символов. Это крайне низкоприоритетный баг и он (может быть) будет исправлен когда будут закончены более важные проекты.

**Comment by IDEXV** [comment]
This was somehow fixed lately, so I'm closing this. Thanks to whoever fixed this.
