### ISSUE TITLE
Ghosts Orbit The Tile Next To Mobs

### ISSUE THREAD

**Issue by MCterra10** [BeeStation/BeeStation-Hornet#1630]
## Round ID:
Downstream. N/A.

## Testmerges:
N/A

## Reproduction:
Orbit someone
![bruh](https://user-images.githubusercontent.com/11001588/80279118-cb7e5e00-873e-11ea-9228-9fdb26036bf3.PNG)

**Comment by MCterra10** [comment]
pretty sure this might be due to runescape chat widening the overlay area for people, but I can't be sure

**Comment by CthulhuOnIce** [comment]
> pretty sure this might be due to runescape chat widening the overlay area for people, but I can't be sure

This isn't because of runescape chat, my guess is it's simply because some recent BYOND versions fuck up animations, which i will text in a minute

**Comment by CthulhuOnIce** [comment]
yeah this seems to be a BYOND animation issue

**Comment by qwertyquerty** [comment]
Appears to have been a byond animation issue fixed in a recent update
