### ISSUE TITLE
Examining paper on airlocks still broken

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#1654]
## Reproduction:

1. write on paper.

2. put the paper on an airlock.

3. examine it, you can't view the contents of the paper

**Comment by qwertyquerty** [comment]
You need to be standing right next to it to examine it. Are you sure it doesn't work?

**Comment by Cenrus** [comment]
I believe it works in localhost but examining the paper on the server itself doesn't work, even if you're right next to it.
