### ISSUE TITLE
Looking trough security cameras easily reveals malf AI's

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#1659]
**INCLUDE THE ROUND ID**
15200

## Reproduction:
If you upgrade your cameras as malf AI and anyone looks trough security cameras they will also have x-ray and all the other upgrades, easily revealing a malf AI.

**Comment by zeskorion** [comment]
You can also just shift click cameras and it'll tell you

**Comment by eeSPee** [comment]
They also shine blue and are quite easy to distinguish from regular cameras.
