### ISSUE TITLE
Bluespace Beaker crates can be turned into raw mats to be sold at massive profit

### ISSUE THREAD

**Issue by MCterra10** [BeeStation/BeeStation-Hornet#1671]
STONKS
![ahyesstonks](https://user-images.githubusercontent.com/11001588/80575789-734da180-8a47-11ea-933b-585342b5fd58.PNG)

**Comment by St0rmC4st3r** [comment]
@Isy232 can you fix this? Please?

**Comment by Cenrus** [comment]
REEEEEEE
