### ISSUE TITLE
Mining Cyborgs sometimes cannot see entities

### ISSUE THREAD

**Issue by PerishedFraud** [BeeStation/BeeStation-Hornet#1690]
ROUND ID: 15318

Mining Cyborgs seem to be suffering from a bug which causes entities to occasionally become invisible. In several prior rounds, I would experience an enemy temporarily becoming invisible. Far more often, the ore box would become invisible until walked into, and it would flicker in and out of visibility while pulled.

This round is provided because it is the first death caused by this issue. Killed by an invisible legion and skulls which were _completely_ invisible and never flickered in until ghostsight kicked in.

So far, the bug only occurred on lavaland for me.

Possibly tied to the cyborg meson item!

Edit: Whatever it was it's been okay for a while now. Closed.

**Comment by Demi-Wahoo** [comment]
Have you tried to turn on the lights? Like your headlamp? Measons let you see the area around, but not the entities. You need light to see stuff.
