### ISSUE TITLE
metastation medbay update issue

### ISSUE THREAD

**Issue by sole1777** [BeeStation/BeeStation-Hornet#1698]
## Round ID:

 all of them (since medbay update)

## Reproduction:

I don't know how this website works. all I'm saying is that on metastation, the pipes that lead from the oxygen tanks to the cryo cells, are spawning incompletely. meaning it spawns missing a pipe so the cells and tanks are not connected

**Comment by St0rmC4st3r** [comment]
![image](https://user-images.githubusercontent.com/34888552/80777946-76dc4800-8b6f-11ea-89fb-765fda477889.png)
You mean this thing, @sole1777 ? It actually works. The pipe is in fact under the floor. Yes, it is extremely ugly and I have already notified mapping, but it does work.

**Comment by sole1777** [comment]
yep i thought it didn't work! it does ur right
