### ISSUE TITLE
Bluespace Miners don't mine bluespace crystals

### ISSUE THREAD

**Issue by butagomi** [BeeStation/BeeStation-Hornet#1704]
Issue reported from  Round ID: 15364 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1517

What the fuck are you thinking you goddamned animals. You fucking morons. You stinking shit-apes? Who cares if it invalidates miners' existence, it doesn't matter when lavaland is just a shitheap top down version of dark souls now anyways.

**Comment by Pill-U** [comment]
Ever heard of making synthetic bluespace crystals out of diamonds bruh

**Comment by Cenrus** [comment]
Intentional, you need to make artificial crystals.

**Comment by Bestparty** [comment]
You are meant to craft the crystals

**Comment by St0rmC4st3r** [comment]
Just wait for the rework and then DARE to mine bluespace....

**Comment by nikk735** [comment]
miners suck make rnd spawn with a bluespace miner
