### ISSUE TITLE
Atmos Fire Extinguisher Backpacks can't be refilled

### ISSUE THREAD

**Issue by Agameofscones** [BeeStation/BeeStation-Hornet#1706]
[Round ID]: # 15370 

Testmerges: #1665 #1670 

Reproduction: Get an atmos fire extinguisher backpack, the one that comes in their lockers. Extend the nozzle and fire it til' the pack is empty. Attempt to refill by switching the nozzle to extinguisher mode and clicking a water tank or sink.

**Comment by SomeAngryMiner** [comment]
supposedly, you use resin foam tanks to refill them (i sent you one with the new atmos backpack that round where you couldnt refill them), but nobody cared to map them in.
that could be fixed by including them on atmos, or orderable by cargo.

**Comment by Cenrus** [comment]
![image](https://user-images.githubusercontent.com/31044876/80863529-f9026480-8c74-11ea-83b3-14705ff35ea8.png)

Works on master branch and the testmerged food one. I noticed that you can't refill it in extinguisher mode, but switching to resin launcher or resin foamer mode allows you to refill it just fine.
