### ISSUE TITLE
MRP (only MRP)Toxin Bomb mixes broken

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#1721]
I made a issue a while ago but that one is pretty outdated so here we go. 
I tested now on MRP and on LRP the difference is obvious on MRP a toxin bomb mix doesn't make more like a little boom hardly damaging its sourrounding tiles even at a maxcap bomb mix or a tritium bomb mix with 43K oxy tritium  and 15000K plasma and well no Reseach points at all. 
On LRP the bomb mixes work exactly like they should trough i can't figure out what exactly is the problem i guess its one of the test merges on MRP but no idea what one it is:
Those are the current Test merges according to OOC on MRP but don't ask me how this could influence it:
https://github.com/beestation/beestation-hornet/pull/1670
https://github.com/beestation/beestation-hornet/pull/1665

**Comment by zeskorion** [comment]
cenrus changes a fuckload of shit, but mine doesnt change anything to do with atmos. maxcap may hace also been lowered due to recent incedents.

**Comment by MNarath1** [comment]
> cenrus changes a fuckload of shit, but mine doesnt change anything to do with atmos
@zeskorion Well yeah i just mentioned your PR because its testmerged currently and i am out of ideas what else than those test merges could be the problem or are there other code differences than the test merges between mrp and lrp well except some of the minor ones like the AI laws and stuff

**Comment by nikk735** [comment]
ive seen people rush 50k's still in 10 min maybe you are doing it wrong

**Comment by MNarath1** [comment]
the thing is i tried that between mrp and lrp and it worked perfectly on lrp the variations where only minimal(and even if i messed up the values that i got out where still way to low to non existent i mean seriosuly i got 4K oxy tritium mix on one side and around 10000K plasma on the other that is more than enough for a pretty big boom and not only a really sad 1 tile radius) might be that something changed i will try it again if it works i am going to close this issue

**Comment by MNarath1** [comment]
Looks like it works again no idea if i fucked up or if whatever caused it is fixed now but if it works this issue is prettym uch useless.
