### ISSUE TITLE
Centcom ERT's are broken for Plasmemes.

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1725]
Issue reported from  Round ID: 15437 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1517

Centcom ERT's are broken for Plasmemes.

You will spawn as a plasma person with no envirosuit or plasma, and then die.
RIP

**Comment by zeskorion** [comment]
This is why admins need to click "enforce human authority"

**Comment by bloons3** [comment]
Burning to death shouldn't be a default option

**Comment by ike709** [comment]
Easy fix.

**Comment by ivanmixo** [comment]
Fixed with #4437
