### ISSUE TITLE
TGUI - Magic 8 ball UI doesn't work for ghosts

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#1727]
## Round ID:
I do not recall.

## Testmerges:
None

## Reproduction:
Be a ghost, have someone use the magic 8 ball. UI opens, buttons go off the screen and are un-pressable.
They stack horizontally, so do not fit at all and either don't work or don't update after you vote.

**Comment by Cenrus** [comment]
https://github.com/tgstation/tgstation/pull/46264/files
Could be a fix for you.
