### ISSUE TITLE
Imaginary Friend spawns for dead people

### ISSUE THREAD

**Issue by CasualKelly** [BeeStation/BeeStation-Hornet#1736]
## Round ID:

15464 & 15462
## Reproduction:

Unsure how to reproduce, was adminhelped by two separate players in back to back rounds. Both times the players spawned as the imaginary friend of a dead person. The first one was bugged out and unable to move from one spot. The second player was a normal ghost by the time I started looking into it.

**Comment by dekunutkid** [comment]
Also happens a lot with corpses spawned by space ruins.

**Comment by eeSPee** [comment]
And for monkey mobs.
