### ISSUE TITLE
Intermittent Freezing / Not Responding

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#1741]
Issue reported from  Round ID: 15487 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1522

I just started noticing this issue within the last 24-36 hours or so. I'll be playing the game, running "smoothly" (I average 200-250 ping) as normal, and the game window will freeze up for ~1-5 seconds, usually fading out and showing Not Responding in the title bar. It will unfreeze for a couple of frames, then freeze again for another ~1-5 seconds. This issue happens relatively often, and has occurred on client version 513.1519, 513.1520, and 513.1522. I have not tried it on version 153.1521, as there is an issue with right-click menu actions that renders the game far less playable. I don't really know what else to attach to this report, as it doesn't happen with any particular action, just at random.

CKEY: brawlerhorde
Discord: BrawlerHorde#4908 (Brawler/Anthony Rodgers)
Location: Western USA

**Comment by qwertyquerty** [comment]
You mentioned others were experiencing this aswell. Could you have people who can repro this also post in here?

**Comment by qwertyquerty** [comment]
A video would also be helpful

**Comment by ghost** [comment]
I'll record the next few rounds I play and clip any instances of this issue (if it shows on video).

**Comment by VictorVow** [comment]
I've had this happen a number of times this week as well. I'll see if I can post a video later also.

**Comment by PowerfulBacon** [comment]
Freezes happen randomly or when you do something specific like right click or alt click something?

**Comment by ghost** [comment]
No, it just occurs seemingly at random throughout the round. It didn't take place in the round I recorded last night, so I'm going to have to try and reproduce it later today.

**Comment by eLeCtrOssSnake** [comment]
I think it might be an **Internet Issue**, my average ping is 75 ms and, if I recall correctly the server is hosted in the US, but I am in Europe. I really doubt that this is server's issue.

**Comment by Crossedfall** [comment]
> I think it might be an **Internet Issue**, my average ping is 75 ms and, if I recall correctly the server is hosted in the US, but I am in Europe. I really doubt that this is server's issue.

The server is in Germany.

**Comment by PowerfulBacon** [comment]
Not enough information provided in the report to be able to investigate / fix this.
