### ISSUE TITLE
Dark Gygax on the Nanotransen Transport Gateway Mission cannot have their Coordination Systems repaired.

### ISSUE THREAD

**Issue by Jockeybane** [BeeStation/BeeStation-Hornet#1750]
## Round ID: 15510

[Round ID]: # 15510

**Comment by Cenrus** [comment]
This is fine because Dark Gygaxes are intended for nuclear operatives only.

**Comment by Jockeybane** [comment]
Obtaining usually exclusive items isn't exactly weird for the Gateway. Some examples:

- The entirety of Wizard Academy
- Wild West contains multiple BR Hardsuits, a dual Energy Sword and a wish granter
- Narsien Ruins contains a Sleeping Carp Scroll, Mjolnir, several Cult-only items, and a Honkrender

Dark Gygax being able to be taken isn't different than any of the previous. And if it is deemed too powerful despite the difficulty in obtaining it, its usage shouldn't be locked away by a bug. There should be a more professional method to keep crew members from using them that isn't 'Try for several minutes to recalibrate it for no results.'
