### ISSUE TITLE
Feature Reqest: Simplify APC repair

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#1751]
As is, there is basically no "real" way of fixing an APC other than cutting wires, destroying it, building another.

Checklist of changes requested:
- A simplified way to do this that doesn't take 5 minutes

Suggestion, maybe: Screwdriver pulls out broken (cover) glass, crowbar to remove burned apc board, replace with a fresh board, screwdriver to secure.

**Comment by Mick1299** [comment]
The process for fixing a broken apc takes 20 seconds max, it isn't that hard. Break the cover off with a blunt item, cut wires, screwdriver and crowbar out old board, use a new frame on the old to fix it, add new board and screwdriver, rewire, add battery, close cover with a crowbar and turn on.
