### ISSUE TITLE
Changling + Apid Transformation

### ISSUE THREAD

**Issue by eeSPee** [BeeStation/BeeStation-Hornet#1770]
Issue reported from  Round ID: 15582 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1511

As a ling, apid wings remain when changing appearance from apid. They cannot be removed. They do bestow you the ability, but also reveal your identity.

**Comment by jlsnow301** [comment]
IPC named humans v2

**Comment by Coolsurf6** [comment]
Just become a human, and you got no weaknesses and you got wings. Sounds pretty epic.

**Comment by FractalBobz** [comment]
The issue is that humans don't get apid wings. so you're obviously a ling because of a bug. 
Happened to me, Couldn't change ID to shake people (it felt like that anyway - but it turned out most people don't know about this bug yet)

**Comment by eeSPee** [comment]
The wing rework fixed this
