### ISSUE TITLE
"Huge Air Scrubbers" Cannot be connected to a port

### ISSUE THREAD

**Issue by Talintosh** [BeeStation/BeeStation-Hornet#1786]
Issue reported from  Round ID: 15721 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1522

The huge air scrubbers which can be found in toxins storage.

These are more powerful than normal scrubbers and can attached to a port. However, when you do so they do not output their contents into the port, and do not change their UI status from "Not connected to a port" to "Connected".

Unless I am missing how these things are supposed to work, they appear to be broken.

**Comment by jlsnow301** [comment]
Which map? Note that the huge air scrubbers usually need dual piping if they're the ones inside the incinerator

**Comment by Talintosh** [comment]
@jlsnow301 My bad! I will edit the Wiki with this information since I did look there quite a bit and couldn't find anything on how to use a huge air scrubber.

I could only find references to the normal air scrubber in the items list
