### ISSUE TITLE
Superficial Healing Resistance 10 treshold doesnt work.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#1793]
Reproduction: 
1) Make a disease with SH as the basis. 
2) Pump it up with different stuff to increase its resistance to 10.
3) Now your healing treshold should be 30 instead of 15.
4) Oh, wait, its still 15 for whatever reason.
5) Understand, that youve managed to spend some of your time on the thing, which is not even  working properly.

**Comment by Dingo-Dongler** [comment]
Replicated, I'm gonna look into a fix
