### ISSUE TITLE
Combat is CATASTROPHICALLY fucked

### ISSUE THREAD

**Issue by PerroCaca2001** [BeeStation/BeeStation-Hornet#1813]
[Round ID]: 15990 and the previous round

## Reproduction: No idea. It just happens on its own and only for some players, on round 15990 it happened to EVERYONE who joined roundstart.

Combat just does not work. Some or most people are immune to damage. Trying to use any intent other than HELP on people produces a (Player1) attempts to touch (Player2)! message. You can use weapons on people but they do not do any damage and some (like billy club and stun batons) do not even work. Projectiles do not do damage. It is possible to run into the AI sat and never get stunned or even take a single point of damage since lasers, tasers, disablers, shotguns, pistols etc etc etc. DO NOT WORK. You can only grab people with crtl-click and tableslamming/faceslamming or choking people does nothing. The only things that seem to kill people are explosions and oxygen damage.

God please help us, we re immortal now.

**Comment by ike709** [comment]
@zeskorion what did you do

**Comment by PerroCaca2001** [comment]
UPDATE: IT IS TIED TO CLOAKS. Wearing any head of staff cloak makes you immortal. Did not test with any other neck slot items but I assume it works the same.

**Comment by zeskorion** [comment]
Hm... i didnt encounter this issue when testing. Ill have a hotfix out in a few mins

**Comment by ike709** [comment]
@zeskorion Already done.
