### ISSUE TITLE
Strong lag for no apparent reason

### ISSUE THREAD

**Issue by PerroCaca2001** [BeeStation/BeeStation-Hornet#1825]
## Reproduction: Play beestation.

For the past 2 days any round I was in is lagging BADLY. The lag is not because of ping, its more of a FPS lag. The game is very choppy and jittery. I already investigated my computer for anything that might be causing this lag, but found nothing. BYOND cache was cleared but it did not solve the issue. In the preferences my FPS is set to 30.

**Comment by Coolsurf6** [comment]
Having the status bar open can cause FPS lag. It can also get worse depending on how much text is changing if you have your internals turned on. 

This is probably not the issue but try going to a different tab than the status tab and see if that fixes your problem.
