### ISSUE TITLE
Donksoft Toy Vending Machine's items are all glasses.

### ISSUE THREAD

**Issue by Kerbin-Fiber** [BeeStation/BeeStation-Hornet#183]
## Reproduction: Just make a Donksoft Toy Vendor and it's fucked.

![](https://i.imgur.com/MGfW0pV.png)

**Comment by qwertyquerty** [comment]
What lmao

**Comment by ghost** [comment]
Epic

**Comment by Kerbin-Fiber** [comment]
This has been working since moving to TGUI-Next.

*Finally, an issue I can just close*
