### ISSUE TITLE
Imaginary friend persists after death

### ISSUE THREAD

**Issue by ike709** [BeeStation/BeeStation-Hornet#1831]
See tin. Not a difficult bug but I'm tired and want to sleep.

**Comment by ike709** [comment]
This is really annoying for the person selected as imaginary friend.

**Comment by MCterra10** [comment]
unable to reproduce; imaginary friend gets ghosted just fine on death. you'll need to be more explicit in how you discovered this.

**Comment by ike709** [comment]
It was a player report.
