### ISSUE TITLE
you can spam click full-auto guns to fire them faster than intended

### ISSUE THREAD

**Issue by YakiAttaki** [BeeStation/BeeStation-Hornet#1841]
## Reproduction:
Get any full auto gun, hold in hand, spam click. Fires way faster than it would if you just held down left click.

**Comment by YakiAttaki** [comment]
after you spam click to get faster boolets, you can then hold down left click to maintain that firerate.

**Comment by Crossedfall** [comment]
Should be addressed by https://github.com/BeeStation/BeeStation-Hornet/pull/1868
