### ISSUE TITLE
You can fire guns in crit

### ISSUE THREAD

**Issue by Mick1299** [BeeStation/BeeStation-Hornet#1862]
## Reproduction:
Issue is in the title. Get a gun with full auto, start shooting, get crit while shooting, continue shooting

**Comment by Mick1299** [comment]
Scratch that. With more testing, you can fire when DEAD. 

The issue is most likely the same as the one described here https://github.com/BeeStation/BeeStation-Hornet/issues/1841

And it all most likely traces back to 
https://github.com/BeeStation/BeeStation-Hornet/pull/1799

**Comment by Flakkyboo** [comment]
Based.
Keep it

**Comment by Crossedfall** [comment]
resolved by https://github.com/BeeStation/BeeStation-Hornet/pull/1863
