### ISSUE TITLE
advanced airlock controller flooding chat as ai

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#1880]
## Reproduction: click on advanced airlock controller as ai

![3eff5c7ee30d1c59ad5b1c2361a59cba](https://user-images.githubusercontent.com/59359762/82952721-bcb9df80-9f66-11ea-9cd2-6d6d39e5ad3f.png)

**Comment by Cenrus** [comment]
https://github.com/yogstation13/Yogstation/pull/8281 Fix
