### ISSUE TITLE
cryoxadone + blood in plumbing makes more blood instead of popping out synthmeat

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#1882]

**Comment by eLeCtrOssSnake** [comment]
We already have unstable mutagen plus blood equals more blood, so this is pointless and should be closed.

**Comment by Mick1299** [comment]
It was a bug report, not a feature request Snake. I'll look into it

**Comment by hotimep** [comment]
i mean, it's supposed to pop out synthmeat, i remember it from factories i saw a couple months ago
