### ISSUE TITLE
Shuttles have no firelocks

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#1918]
our shuttles have no firelocks, YogStation shuttles do. This results in the shuttle getting depressurized all the time.

**Comment by ike709** [comment]
Honestly I think the better solution is to bolt airlocks to space while in transit.

**Comment by PowerfulBacon** [comment]
This issue has been solved by the PR that added tiny fans to the doors and firelocks to the inside of shuttles
