### ISSUE TITLE
Livestock can open their own pens in the garden

### ISSUE THREAD

**Issue by Ohagi-Chan** [BeeStation/BeeStation-Hornet#1923]
## Round ID:

Austation 4099
## Testmerges:

Monstermos
## Reproduction:

The firedoors used in the farm animal pens are the same type as the one used all over the station.  All mobs can open the firedoors just by walking against them, meaning that the livestock constantly free themselves without assistance.

**Comment by ike709** [comment]
They should really be windoors anyways tbh.

**Comment by Ohagi-Chan** [comment]
An issue that the old directional firelocks had was that closing them would crush the animal if it occupied the same square.  While that's better than finding a cow in the showers, a better solution than reverting those doors would be appreciated.
