### ISSUE TITLE
Contractor Tablet becomes unusable when turned off

### ISSUE THREAD

**Issue by Minelol76** [BeeStation/BeeStation-Hornet#1932]
Bug I found when trying to turn off the tablet to save battery, and then turn it back on two days ago. Don't do it.

PLZ FIX

**Comment by Chessus** [comment]
Tried to test this on a local server. No luck reproducing. Can turn it on and off again. 
![contractor bug1](https://user-images.githubusercontent.com/10277607/104183181-4b7b5e00-545d-11eb-8116-ce8b20d5110f.PNG)
![contractor bug2](https://user-images.githubusercontent.com/10277607/104183183-4cac8b00-545d-11eb-90dc-44b76606f94c.PNG)
![contractor bug3](https://user-images.githubusercontent.com/10277607/104183185-4d452180-545d-11eb-9695-8190f41c581a.PNG)
