### ISSUE TITLE
Nanites voice sensor doesnt activate.

### ISSUE THREAD

**Issue by satang987** [BeeStation/BeeStation-Hornet#1942]
So as R&D i recently tried to set up nanites voice sensor programm but when i tested it out, it doesnt start, though when i use the nanite control it still work like normal. I have tried to use both inclusive and exclusive order but still it's the same

**Comment by eLeCtrOssSnake** [comment]
I am pretty sure I've tried to do the same thing and it did not work. Imma try to reproduce this locally and see if it works.

**Comment by eLeCtrOssSnake** [comment]
Confirmed to not work.

**Comment by eLeCtrOssSnake** [comment]
I'm on trying to fix it. Let's see how long it takes for me.
