### ISSUE TITLE
automatic gun bugs

### ISSUE THREAD

**Issue by zeskorion** [BeeStation/BeeStation-Hornet#1944]
## Round ID:
null

## Testmerges:
null

## Reproduction:
-fire auto gun in stasis bed
it fires normally. Firing a normal gun does not. Tested using WT autorifle compared to shotguns
-spam click automatic gun
it will ignore fire rate. used same comparisons as above, with other slower automatic guns as a control as well. perhaps ad a clickdelay or some shit
-attempting to examine, or do any other non-fire click action,, including pointing, fires automatic guns
-player direction does not change while firing fullauto guns.

**Comment by Kmc2000** [comment]
The ignoring fire rate thing was actually something I made a fix PR for, and I found the hard baked delay that I put in to actually make full auto spam clicking slower than regular spam clicking. A video would be helpful here, but I'll try and recreate / fix it.

**Comment by zeskorion** [comment]
> The ignoring fire rate thing was actually something I made a fix PR for, and I found the hard baked delay that I put in to actually make full auto spam clicking slower than regular spam clicking. A video would be helpful here, but I'll try and recreate / fix it.

does the hard baked delay use the fire_rate var?

**Comment by Kmc2000** [comment]
> > The ignoring fire rate thing was actually something I made a fix PR for, and I found the hard baked delay that I put in to actually make full auto spam clicking slower than regular spam clicking. A video would be helpful here, but I'll try and recreate / fix it.
> 
> does the hard baked delay use the fire_rate var?

If I recall, it sets the next firetime to be world.time + fire_delay

**Comment by zeskorion** [comment]
> > > The ignoring fire rate thing was actually something I made a fix PR for, and I found the hard baked delay that I put in to actually make full auto spam clicking slower than regular spam clicking. A video would be helpful here, but I'll try and recreate / fix it.
> > 
> > 
> > does the hard baked delay use the fire_rate var?
> 
> If I recall, it sets the next firetime to be world.time + fire_delay

fire _delay is a deleted var in ammo casing iirc, unless you used fire delay as an in-proc var to math out fire_rate

**Comment by Kmc2000** [comment]
> > > > The ignoring fire rate thing was actually something I made a fix PR for, and I found the hard baked delay that I put in to actually make full auto spam clicking slower than regular spam clicking. A video would be helpful here, but I'll try and recreate / fix it.
> > > 
> > > 
> > > does the hard baked delay use the fire_rate var?
> > 
> > 
> > If I recall, it sets the next firetime to be world.time + fire_delay
> 
> fire _delay is a deleted var in ammo casing iirc, unless you used fire delay as an in-proc var to math out fire_rate

Ah fun, mightve mis used it! I'll take a look when I wake up tomorrow

**Comment by zeskorion** [comment]
added a few more

**Comment by zeskorion** [comment]
also, you may hve used the defined fire delay (2.5) instead of Fire_rate

**Comment by zeskorion** [comment]
OH! fire delay is the fuckin burst fire var

**Comment by Mick1299** [comment]
This feels like it should be pinned, new bugs keep popping up

**Comment by PowerfulBacon** [comment]
Full auto guns in general are pretty broken, normal interactions just don't happen.
For example: Temperature gun cannot be thrown, nor can it be placed into a recharger unless it has no ammo.

**Comment by Kmc2000** [comment]
Ugh

I'm gonna need a list of everything please. We've not experienced any of this on nsv

**Comment by PowerfulBacon** [comment]
Solved by some PR KMC made at some point
