### ISSUE TITLE
Integrated Electronics - Reference decoders do not work

### ISSUE THREAD

**Issue by MisterMecky** [BeeStation/BeeStation-Hornet#1962]
## Round ID:

(Downstream) N/A. Tested on a fresh beestation server

## Testmerges:

N/A

## Reproduction:

Reference decoders do not decode text outputted by a reference encoder

1. Using a debug integrated circuit printer, print out this assembly and insert a battery:
`{"assembly":{"type":"type-f electronic assembly"},"components":[{"type":"ranged sensor"},{"type":"reference encoder"},{"type":"reference decoder"}],"wires":[[[1,"O",1],[2,"I",1]],[[1,"A",1],[2,"A",1]],[[2,"O",1],[3,"I",1]],[[2,"A",2],[3,"A",1]]]}`

2. Use (Scan) the assembly on an object

3. Check the reference decoder inside the assembly to see if decoded the reference

**Comment by MisterMecky** [comment]
Seems to have been fixed at some point.

**Comment by Slouista** [comment]
Re open this please.

**Comment by MisterMecky** [comment]
Likely fixed by https://github.com/BeeStation/BeeStation-Hornet/pull/2543
