### ISSUE TITLE
Hyperperspiration Transmission 8 Description

### ISSUE THREAD

**Issue by imw-Oculus** [BeeStation/BeeStation-Hornet#1976]
The description of the Hyperperspiration symptom for Transmission 8 displays the description of Organic Flux Induction, Transmission 8.

[File](https://github.com/BeeStation/BeeStation-Hornet/blob/79df0725fce46fca2bc212d1a80b7925346ce52c/code/datums/diseases/advance/symptoms/heal.dm)
Line 293 reads:
`<b>transmission 8:</b> The EMP affects electronics adjacent to the subject as well."`
It should read:
`<b>transmission 8:</b> Heals toxin damage, and the host will sweat out all reagents in the same two tile radius as the previous threshold. -1 Severity`

**Comment by zeskorion** [comment]
I thought i fixed that, like, 30 times now

**Comment by jlsnow301** [comment]
This was resolved, pls close
