### ISSUE TITLE
[Code Bounty] Add logging of items destroyed by cremator

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1980]
Currently cremation is logged in attack.log

`[2020-06-15 22:25:18.313] ATTACK: bloons3/(Wesley Richardson) has cremated @Bloons3[DC]/(Ashlyn Driggers) (NEWHP: 100)  (CentCom Recovery Ship (196, 83, 1))`

However, it does not appear that item destruction is logged. So it might be possible to destroy a unique antag objective item out of spite, and have it go un-logged.

The goal of this code bounty will be to log what items are destroyed in the cremator (recursively if an inventory is destroyed) to the appropriate log file, and if possible associate the destruction of those items with a ckey.

Possible format

`[2020-06-15 22:25:18.313] ATTACK: bloons3/(Wesley Richardson) has cremated ITEM/gun/energy/laser/captain  (CentCom Recovery Ship (196, 83, 1))`

Possible alternate format:

`[2020-06-15 22:25:18.313] ATTACK: bloons3/(Wesley Richardson) has activated a crematorium  (CentCom Recovery Ship (196, 83, 1))`
`[2020-06-15 22:25:18.313] ATTACK: ITEM/gun/energy/laser/captain destroyed by crematorium  (CentCom Recovery Ship (196, 83, 1))
`

This bounty will be 15 USD payable via Cryptocurrency or BountySource, depending on which is easier for the coder who accepts.

**Comment by ike709** [comment]
sure
