### ISSUE TITLE
Cornu Cutaneum Disease Symptom Issues

### ISSUE THREAD

**Issue by imw-Oculus** [BeeStation/BeeStation-Hornet#1984]
Oh boy. A few issues with this one that I can see. No in-game testing, so I could be wrong, but - judging by the code...
[File](https://github.com/BeeStation/BeeStation-Hornet/blob/79df0725fce46fca2bc212d1a80b7925346ce52c/code/datums/diseases/advance/symptoms/spiked.dm)

To start with, the description regarding effect modification via the Resistance stat is misleading.
Line 36:
`Spikes grow faster and hurt you more often`
There is no modification of Stage Speed by the associated code. Additionally, the host is never harmed by their own spikes. This may be a reference to the attempt to have spikes have a higher possibility of triggering, and damaging an adjacent mob, but...
Line 28:
`var/Power = 1`
This variable is only modified by the Resistance stat change, which alters it to 2 on Line 49, but that variable is never actually used by the functional code beneath. That code instead calls the usual, lowercase "P" power.
Line 58:
`if(prob(20*power))`

Another issue is that the damage attempt is called regardless of stage, so when the host is experiencing:
`You feel goosebumps pop up on your skin`
There is still the same chance of dealing brute damage to people adjacent, though the damage is only 1. Lines 63-88.

**Comment by zeskorion** [comment]
i fixed this without realizing it
