### ISSUE TITLE
[Code Bounty] Adminbus Felinid Event Machine

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#1985]
![image](https://user-images.githubusercontent.com/3241376/84837505-e6ae7100-affd-11ea-8dbc-fb60a367075d.png)
![image](https://user-images.githubusercontent.com/3241376/84838098-24f86000-afff-11ea-9eea-5a549b2c8917.png)
![image](https://user-images.githubusercontent.com/3241376/84838116-2e81c800-afff-11ea-9505-d5b8095438bc.png)

Currently this will be $10 paid via bounty source, paypal, or mainstream cryptocurrency.

Rationale:
I would like to see a machine that converts crew into felinids because doing it as an admin requires tedious use of VV per player converted. The players that were on that round had a fun time revolting against the captain, and it was hilarious to watch.

Deliverable:
A machine that converts a player inserted into a felinid (species). 
There should be an additional variant that brainwashes the victim with an objective of converting additional crew into felinids.
Any style of machine would work, from a machine styled after the malf AI's borg factory, or the medical machine that inserts implants.
It would also be nice if the machine could be configured as to what species is output, because then the opportunity for racewar can go beyond just felinids (lizards, moths, etc)

**Comment by Mick1299** [comment]
Perhaps the objective could be unlocked via emag?

**Comment by bloons3** [comment]
If it is an adminbus machine, then emagging wouldn't be relevant.
The purpose of having it create antags, vs not creating antags, is that one could be used for a minor event during a round, and the other could be used for a major event during a round.

A machine that doesn't create new antags wouldn't have a major effect on a round.
A machine that does create new antags would have a major effect on a round.

**Comment by ike709** [comment]
why exactly does this need to be a machine instead of a smite option?

**Comment by bloons3** [comment]
Because I wish to podspawn this on LRP and incite a racial cleansing

**Comment by St0rmC4st3r** [comment]
Good stuff, on it

**Comment by bloons3** [comment]
Currently claimed by: St0rmC4st3r

**Comment by zeskorion** [comment]
fuck off with your adminbus bullshit

**Comment by TeomanTheGreat** [comment]
I may do this if I have time in the future

**Comment by utilbird** [comment]
@bloons3 still claimed?

**Comment by bloons3** [comment]
> @bloons3 still claimed?

Go for it

**Comment by utilbird** [comment]
I don't even remember claiming this lmao, my memory is bad. I'll work on it now
