### ISSUE TITLE
You can empty a full magazine in record time by clicking and dragging, the firerate being multiplied by how many times you've clicked and dragged.

### ISSUE THREAD

**Issue by YakiAttaki** [BeeStation/BeeStation-Hornet#1986]
## Reproduction:
Get a automatic gun (for testing I used the HoS' gun varedited to have basically inf. charge), click and drag something, and continue clicking and dragging. Speed of fire will continue to increase until you either run out of ammo or let go of left click. Note: This is not a problem of var-editing, as it occurred with a non-varedited autorifle.
Evidence of the bug can be seen [here](https://cdn.discordapp.com/attachments/563171237635948564/722612861612064877/vlc-record-2020-06-17-12h44m58s-2020-06-17_12-42-44.mp4-.mp4)

**Comment by YakiAttaki** [comment]
It doesn't seem to work for all guns, or the gun's firerate is just too high for it to be noticeable anyway (i.e. L6-SAW), and it seems to be a bit hit or miss whether it works or not, but if you know this mechanic exists you could 100% abuse it.

**Comment by ike709** [comment]
@Kmc2000

**Comment by YakiAttaki** [comment]
person i'm testing this with said

> the trick is to click drag and then clickdrag again while keeping the gap between click drags as small as possible, it can be stacked too

**Comment by Kmc2000** [comment]
what the fuck

**Comment by bloons3** [comment]
Curious, what spawn menu is demonstrated in the recording?

**Comment by YakiAttaki** [comment]
If a menu pops up its the sandbox menu, otherwise I (an admin on
AuStation), was spawning guns and ammo to test

**Comment by YakiAttaki** [comment]
this is infact still a problem that hasn't been resolved
