### ISSUE TITLE
TWEAK: Metabolism Reduction

### ISSUE THREAD

**Issue by imw-Oculus** [BeeStation/BeeStation-Hornet#1995]
I believe that the overall metabolism speed for reagents could do with getting nudged down, just a touch. Even with all the advantages that Chemistry proficiency offers, for example - I was only able to create a pill that allowed me to survive a depressurized oxygen-free environment for less than a minute. Many reagents metabolize so quickly, that their extended benefits are debatable. This tweak wouldn't have to be to an obscene degree.

**Comment by zeskorion** [comment]
> I believe that the overall metabolism speed for reagents could do with getting nudged down, just a touch. Even with all the advantages that Chemistry proficiency offers, for example - I was only able to create a pill that allowed me to survive a depressurized oxygen-free environment for less than a minute. Many reagents metabolize so quickly, that their extended benefits are debatable. This tweak wouldn't have to be to an obscene degree.

I dont think chem needs a buff. Additionally,  most chems multiply effect by metabolization multiplier, meaning lowering metab would lower benefits

**Comment by imw-Oculus** [comment]
Fair point, didn't really think this tweak out. Could probably close this issue. The other one, regarding chemical smoke behavior, could certainly do with a look though.
