### ISSUE TITLE
Metastation kitchen freezer low pressure and devoid of air

### ISSUE THREAD

**Issue by Arlojmikk** [BeeStation/BeeStation-Hornet#1997]
in the kitchen freezer there is no oxygen and when opening it theres a big woosh of air coming out of it no idea why

**Comment by ike709** [comment]
The freezer makes the air really cold. Pressure and temperature are directly proportional when volume is constant (ie in a closed room).

**Comment by ivanmixo** [comment]
Is this legit something that needs to be fixed?
