### ISSUE TITLE
[Bounty] Merge the Eldrich Cultist/Heretic antag from TG

### ISSUE THREAD

**Issue by knewtoomuch** [BeeStation/BeeStation-Hornet#2004]
There's a cool antagonist that was recently added to the TG branch called heretic, which is kinda like a less OP version of shadowlings. I've played a couple rounds of this in the past and had a lot of fun, and it'd be cool to see this gamemode here too.

https://hackmd.io/@tgstation/r1tDpqEsI https://github.com/tgstation/tgstation/pull/51199

**Comment by knewtoomuch** [comment]
https://www.bountysource.com/issues/91772972-bounty-merge-the-eldrich-cultist-heretic-antag-from-tg

**Comment by PowerfulBacon** [comment]
Whoops, wrong button, Beebot hopefully will add the right tags and stuff

**Comment by zeskorion** [comment]
> There's a cool antagonist that was recently added to the TG branch called heretic, which is kinda like a less OP version of shadowlings. I've played a couple rounds of this in the past and had a lot of fun, and it'd be cool to see this gamemode here too.
> 
> https://hackmd.io/@tgstation/r1tDpqEsI [tgstation/tgstation#51199](https://github.com/tgstation/tgstation/pull/51199)

A cursory glance of the pr seems alright,  ill try this out and mebbe correct a few spelling errors and bad descs

**Comment by TeomanTheGreat** [comment]
Yes yes yes yes

**Comment by zeskorion** [comment]
Yeah, probly definitely doing this tonight or tommorow

**Comment by zeskorion** [comment]
nevermind too much work i dont care to do this anymroe

**Comment by TeomanTheGreat** [comment]
@Cenrus do it do it

**Comment by xboxnoob** [comment]
fuck it i will i give it a try how hard it would it be

**Comment by xboxnoob** [comment]
ah fuck there is like 200 commits i need to add

**Comment by xboxnoob** [comment]
i see why zesk gave up

**Comment by xboxnoob** [comment]
i am like half done with this shit

**Comment by TeomanTheGreat** [comment]
@xboxnoob I'm pretty sure @PowerfulBacon and @Cenrus may also be working on it

**Comment by xboxnoob** [comment]
yeah fuck this sorry

**Comment by xboxnoob** [comment]
i am was talking with bacon and zesk it is pure hell

**Comment by CthulhuOnIce** [comment]
ok

**Comment by CthulhuOnIce** [comment]
nevermind this is hell

**Comment by TotallyNotChief** [comment]
cursed pr

**Comment by PowerfulBacon** [comment]
I am not working on this, I self assigned on accident

**Comment by PowerfulBacon** [comment]
was trying to get beebot to format the post properly, but he has some brain issues

**Comment by xboxnoob** [comment]
christ i am finally got it to compile

**Comment by xboxnoob** [comment]
still a draft as i have to do some bugfix pr and fix the interface

**Comment by xboxnoob** [comment]
Holy crap this was pure hell

**Comment by Djiq** [comment]
Im starting to work on this again

**Comment by PowerfulBacon** [comment]
nevermind, I think this needs to be closed for claiming

**Comment by Djiq** [comment]
@knewtoomuch accept the bounty claim on bountysource so i can cash out

**Comment by TeomanTheGreat** [comment]
Unbased bounty giver doesn't give up his shekels
