### ISSUE TITLE
WOAH! RAPID CABLE LAYER WITH NO RAPID LAYING

### ISSUE THREAD

**Issue by SirJohanot** [BeeStation/BeeStation-Hornet#2010]
Ah yes, the rapid cable layer. Is of the size of a normal item, but can carry thrice the amount of cable there is in a normal coil. Well, also, ummm.... that's it. But it shouldn't be. You see, rapid cable layers can be dual-wielded. What does it do while dual-wielded? Nothing. What is it SUPPOSED to do? Lay cables under the user while they're walking, leaving a trail of cables behind them. Adding this feature will put "rapid" back in "rapid cable layer". It'd also mean that solars can be done in mere minutes, which is good once the SM delams for the 10th round in a row because of fastmos.

**Comment by xboxnoob** [comment]
how would turning work exactly as cables are a bit buggy

**Comment by SirJohanot** [comment]
> how would turning work exactly as cables are a bit buggy

With one directional input, it would leave two cables: one on the first tile, from its center to the second tile, and one on the second tile, from its center to the first tile. there should be no problem with turning, whatsoever

**Comment by eLeCtrOssSnake** [comment]
Think of rapid cable layer as a big cable coil stack. Why do you need anything else?
