### ISSUE TITLE
TWEAK: Remove Surgical Tools from the Autolathe

### ISSUE THREAD

**Issue by imw-Oculus** [BeeStation/BeeStation-Hornet#2011]
Surgery is a wonderful, flexible module with lots of exciting potential - both standard, and ghetto. It's currently severely gimped by the presence of easy, lazy systems - Cryo and Cloning. I don't suggest the removal of those, but perhaps an adjustment would be in order.

However, that's neither here nor there. The removal of surgical tools from the autolathe, and delegating them to the Medical Techfab only would encourage the utilization of ghetto alternatives for non-Medical crew. I suggest this, because as rarely as Surgery is used, ghetto surgery is used even less. A step in the right direction, in my mind, which would lay the foundation for future tweaks.

I'll try and slam out a quick PR for this later, but for now - post thoughts.

**Comment by xboxnoob** [comment]
i kind of agree with this as it is incredibly easy for someone to make a chainsaw using the autolathe, but what about robotics

**Comment by imw-Oculus** [comment]
I stand by what I said. Surgical tools for surgery. Denying Surgical tools to the Science Techfab means that Robotics will actually have to interact with Medical to get what they want, beyond basic, round-start tools.

**Comment by Isy232** [comment]
> I stand by what I said. Surgical tools for surgery. Denying Surgical tools to the Science Techfab means that Robotics will actually have to interact with Medical to get what they want, beyond basic, round-start tools.

No, just no on so many levels. NT would never make a department that often finds use for these tools unable to acquire them themselves. It wastes the time of players who wish to being doing productive or interesting jobs. Robotics without surgery is just cyborgs and mechs.

That being said, I do heavily agree with removing surgical tools from the public autolathe. Circular saws should not be widely available and it is especially an issue to see bartenders shortening their shotgun at the lathe every round.

**Comment by Dingo-Dongler** [comment]
Science can already print surgical tools.

**Comment by Dingo-Dongler** [comment]
Issue resolved.

**Comment by imw-Oculus** [comment]
Can confirm issue is resolved.
