### ISSUE TITLE
Advanced airlock controller broke for AI

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#2017]
Issue reported from  Round ID: 17453 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1524

Probably old issue, AI get "too many clicks" message when trying to interact with it.
Also the one in AI sat (meta) is badly configured.

**Comment by ivanmixo** [comment]
Tried on private server, couldn't reproduce
