### ISSUE TITLE
[Bounty] Port custom vendors from TG.

### ISSUE THREAD

**Issue by St0rmC4st3r** [BeeStation/BeeStation-Hornet#2056]
One commissary is not enough for one station. This should help cargo in selling items they order for a ton of money to the crew and SOMEHOW be SOMEWHAT profitable. 

Main PR you need to port: https://github.com/tgstation/tgstation/pull/46240
Fix that allows to actually load stuff: https://github.com/tgstation/tgstation/pull/46351
I guess it is a fix for selling stacks of items: https://github.com/tgstation/tgstation/pull/46538

PR these, make them merged and I will accept your claim.

**Comment by St0rmC4st3r** [comment]
Upped to 10$ since I really want it.

**Comment by Kerbin-Fiber** [comment]
time to redownload beecode and hope I don't have to mess with TGUI stuff. Then I will and will give up

**Comment by imw-Oculus** [comment]
Will I legit get ten buckaroos for porting this ez-peezy shit?
EDIT: Oh, PR already open. So much for my custom vendor Integrated Circuit, and dreams of wealth. Why hasn't it been merged yet?
