### ISSUE TITLE
Turbine gas filter outputs are flipped on Kilo

### ISSUE THREAD

**Issue by sunshinehunter** [BeeStation/BeeStation-Hornet#2057]
Issue reported from  Round ID: 17740 (BeeStation Sage - MRP For Everyone!)
With #2053 testmerge

Reporting client version: 513.1526

On roundstart Kilo, the gas filter at the turbine is spacing the filtered gas and putting the waste gas into the tank, even though it should be reversed.

How it's (roughly) supposed to be:
![image](https://user-images.githubusercontent.com/11196338/85902787-1da63300-b805-11ea-8791-7a7fca9a37af.png)
There were waste loop pipes in this set up, I think they need to be moved in order to fit this configuration there.

How it's (very roughly) set up round-start:
![grafik](https://user-images.githubusercontent.com/11196338/85903412-9063de00-b806-11ea-978e-6b61d39006c3.png)

**Comment by zeskorion** [comment]
fixing right now, thnks for making the issue
