### ISSUE TITLE
where do i find the beestation main menu photos?

### ISSUE THREAD

**Issue by slingring** [BeeStation/BeeStation-Hornet#2081]
wrong area but i dont know where to throw this otherwise. can someone tell me where i can find the beestation main menu art? 
im just looking for it

**Comment by gidgeesheep** [comment]
1. Download latest copy of beestation

2. Open  Dream maker in the BYOND engine

3. Locate config\Sage\title_screens\images
    
    OR config\title_screens\images

4.??????

5.Profit

**Comment by gidgeesheep** [comment]
The #questions, #spriting, and #coding parts of the Beestation Discord will also do a pretty good job if you have more questions.

**Comment by slingring** [comment]
@gidgeesheep global banned from both servers and discord. thanks for asking.
