### ISSUE TITLE
[Metastation] Cooling loop in kitchen is very bad with fastmos

### ISSUE THREAD

**Issue by Arrfur** [BeeStation/BeeStation-Hornet#2085]
![image](https://user-images.githubusercontent.com/49613258/86119796-08fac100-bacb-11ea-837e-5f065965ff89.png)

Please remove the cooling loop from the metastation kitchen, at roundstart it lowers the pressure by so much that going into the backroom will throw you in the room and the pressure is low enough that you are oxygen starved. 

I've never understood this and its got no function other than "le epic half baked flavour" so maybe remove the lethal aspect of the chefs backroom ?

**Comment by bloons3** [comment]
Could probably be fixed by adding  atmos fans like the shuttles have to the doorways.

**Comment by Arrfur** [comment]
I'd say just remove it tbh, no other map has it and is literally lethal to be in (oxyloss and burn damage).

**Comment by ivanmixo** [comment]
This has been happening even since before fastmos and nobody knows why it's actually a thing

**Comment by TheGreyDiamond** [comment]
Got fixed with PR#2177, so someone should close it

**Comment by Crossedfall** [comment]
Fixed with https://github.com/BeeStation/BeeStation-Hornet/pull/2177
