### ISSUE TITLE
Dried tea leaves contain no reagents

### ISSUE THREAD

**Issue by ModDownloading** [BeeStation/BeeStation-Hornet#209]
When you grow tea aspera plants of any potency, the resulting leaves contain no reagents when ground in the all-in-one grinder after being dried. I grew the leaves in the botany maintenance on deltastation and once I noticed that the beaker was still empty after I ground up the leaves I had an admin check the reagents in one of the leaves. The variables showed that there were no reagents in the leaf and this seems like a bug since it seems to prevent tea powder from being produced.

I think the code is responsible, since I found the lines:

/obj/item/reagent_containers/food/snacks/grown/tea
	seed = /obj/item/seeds/tea
	name = "Tea Aspera tips"
	desc = "These aromatic tips of the tea plant can be dried to make tea."
	icon_state = "tea_aspera_leaves"
	filling_color = "#008000"
	**grind_results = list(/datum/reagent/toxin/teapowder = 0)**
	dry_grind = TRUE
	can_distill = FALSE

and

/obj/item/reagent_containers/food/snacks/grown/tea/astra
	seed = /obj/item/seeds/tea/astra
	name = "Tea Astra tips"
	icon_state = "tea_astra_leaves"
	filling_color = "#4582B4"
	**grind_results = list(/datum/reagent/toxin/teapowder = 0, /datum/reagent/medicine/salglu_solution = 0)**

that seem to be the issue.

EDIT: I dried the leaves before grinding them, so dry_grind should have worked

**Comment by Toxici11i** [comment]
fixing this rn, qwerty broke alotta shit
