### ISSUE TITLE
[Code Bounty] Fluid Void for Mediborgs

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#2091]
Medical Cyborgs do not have an easy way to void fluids like humans do (via throwing a beaker on the ground).

The purpose of this bounty is to create a means for borgs equipped with beakers to remove fluids from their onboard beakers (which they start with 1 of currently, for medical borgs).

Deliverable:
Some manner in which a borg equipped with a beaker upgrade can remove fluid from that beaker. This could be another attachment that is a beaker that voids all fluids transferred into it. It could also be a special keybind that removes all fluids from the current beaker equipped.

Bounty:
5 USD via Code Bounty, or Paypal, or Cryptocurrency

**Comment by ike709** [comment]
This is already a thing, click on yourself on a non-help intent with the beaker, IIRC.

**Comment by bloons3** [comment]
🤦
