### ISSUE TITLE
Geneticist Console not opening bug

### ISSUE THREAD

**Issue by SirJohanot** [BeeStation/BeeStation-Hornet#2096]
Issue reported from  Round ID: 18016 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1526

When you make an advanced injector with 3 or more powers/disabilities, the console will eventually stop working and will require disassembling. Testing seems to show that it becomes this way right after you close the console window, if you don't, it will be working as normal. Clicking on it afterwards doesn't make any window show up

**Comment by imw-Oculus** [comment]
Are you absolutely sure this issue isn't client-side?

**Comment by SirJohanot** [comment]
> Are you absolutely sure this issue isn't client-side?

I will try to get some other geneticist to recreate it, will report back
