### ISSUE TITLE
Multiple goliaths cause permastun

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#2106]
Issue reported from  Round ID: 18148 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1526

Testmerges: apparently none

Issue: goliaths can dig tentacles under you even if you are already grappled by another goliath, resetting the trap time. That way, as little as 2 of them can permastun a miner, who has no way to escape. I couldn't reproduce this bug obviously since I was dead, but it seemed like the exact same happened to another one. Doesn't seem like this is intended, as that would make goliath tendrils literal unavoidable deathtraps, especially to players with a bit higher ping.

**Comment by zeskorion** [comment]
Goliath tentacles are easy to avoid. This has existed for a long time,  and no one plans to fix it

**Comment by St0rmC4st3r** [comment]
Pick your fights, think about positioning and movement. Lure one goliath away from others. The situation in which several miners die to multiple goliaths is a bit less common but still possible. 

I think it works as intended.

**Comment by imw-Oculus** [comment]
>Works as intended

Agreed. It's almost like Lavaland is a treacherous place. Sidenote: 90% of SS13 processing happens server-side. I'm running on an almost literal toaster, and have never experience unusual ping, unless the server is getting DDOS'd.
