### ISSUE TITLE
Having no liver results in alcohol immunity

### ISSUE THREAD

**Issue by TheOneJohiah** [BeeStation/BeeStation-Hornet#2107]
So I'm probably not doing this right but I've never submitted a bug report before. Basically, as of the 02 July version that my private server runs on, having your liver be utterly destroyed by bacchus blessing, or presumably any alcohol, actually results in alcohol immunity as the various drinks will no longer metabolize. Upon installing a cybernetic liver I almost immediately went into toxin shock due to the 300 units of bacchus floating around my bloodstream.
It's either an issue of the liver not causing toxin damage when destroyed or something else, I'm not too familiar with how the internal code works.

**Comment by TeomanTheGreat** [comment]
Something like that happened to me too but it was with blood. I had like 0% but when it went **_Up_** to a certain point I just died quickly.

**Comment by TheOneJohiah** [comment]
How does one end up with no blood?

**Comment by imw-Oculus** [comment]
If you have no liver, you'll almost certainly die before the logic of not being able to process alcohol applies. In fact, you CANT process any toxins in your body with no liver, and will quickly build a terminal level of toxins. Yes, it's a bug. No, I don't see it having a drastic gameplay impact.

**Comment by TheOneJohiah** [comment]
It has happened multiple times to me since taking the alcohol resistance quirk, whatever that's called. I spent an entire round starving, and stuffing my face with pizza did nothing as it didn't actually process that I had eaten food for purposes of nutrition.

**Comment by ghost** [comment]
Having no liver makes you take 10 toxin damage per second.
