### ISSUE TITLE
You cannot buy assistant's formal uniform in OOC shop.

### ISSUE THREAD

**Issue by Firefox13** [BeeStation/BeeStation-Hornet#2108]
## Round ID:

Irrevelant

## Testmerges:

Irrevelant!!!

## Reproduction:

Have enough coins to buy assistant's formal uniform.
Press the button PURCHASE.
Notice nothing.

**Comment by Mick1299** [comment]
Can you specify which vendor you were trying to buy it from, and what map it was on?

**Comment by Firefox13** [comment]
> 
> 
> Can you specify which vendor you were trying to buy it from, and what map it was on?

Whoops, I meant the OOC shop! The beecoins.

**Comment by Crossedfall** [comment]
This happens for anything that has an apostrophe in it. By the time it gets to the below code, the gear's name is truncated to just before the apostrophe leading to `TG` equaling `null`.

https://github.com/BeeStation/BeeStation-Hornet/blob/ba40cb637d38cb9520b7a23c1cc0de53433dbf8d/code/modules/client/preferences.dm#L1207-L1211

**Comment by PowerfulBacon** [comment]
Confirmed working, at the cost of 2500 of my precious beecoins
![image](https://user-images.githubusercontent.com/26465327/172244530-743f36c1-9fa7-4432-9d0f-cc5f8e7135b1.png)
