### ISSUE TITLE
Firelocks keep pressure even when broken

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#2109]
Issue reported from  Round ID: 18196 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1526

Pretty much title. Pressure didn't change and air wasn't sucked out of rooms when I broke the airlock.
In fact the second airlock didn't even react to me breaking the first one.

**Comment by Crossedfall** [comment]
Easy to reproduce.

1. Create a breach
2. Destroy or delete a firelock

**Expected**: After the firelock(s) are removed, the air should rush out into the breach
**Actual**: Nothing happens and an invisible barrier separates the space where the firelock used to be and the breach. Mobs can pass over, but atmos will not.

If you fix the breach, the barrier will remain. 

![image](https://user-images.githubusercontent.com/26130695/90072872-c9281b80-dcbd-11ea-8d97-36ccf47345ea.png)

**Comment by francinum** [comment]
This is likely due to firelocks not forcing tile reconciliation on break.
