### ISSUE TITLE
TWEAK: Remove Mass Mind Swap on Sage

### ISSUE THREAD

**Issue by imw-Oculus** [BeeStation/BeeStation-Hornet#2110]
Mass Mind Swap - IE, changing a large number of people from one character to another, is not conducive to RP. It eliminates all character and in-game progress from the round, encourage people to either act poorly, or to not act at all. I would recommend that this feature be removed from Sage - which is ostensibly the more RP-oriented of the two BeeStation servers. The goal of roleplaying is to establish a character. While this is possible while taking the body of an entirely different character, it is less than optimal. I'm mostly making this issue to field thoughts in the comments. Spitting at the wall, and seeing what sticks.

**Comment by zeskorion** [comment]
> Mass Mind Swap - IE, changing a large number of people from one character to another, is not conducive to RP. It eliminates all character and in-game progress from the round, encourage people to either act poorly, or to not act at all. I would recommend that this feature be removed from Sage - which is ostensibly the more RP-oriented of the two BeeStation servers. The goal of roleplaying is to establish a character. While this is possible while taking the body of an entirely different character, it is less than optimal. I'm mostly making this issue to field thoughts in the comments. Spitting at the wall, and seeing what sticks.

didnt i already remove this event from rotation

**Comment by imw-Oculus** [comment]
> > Mass Mind Swap - IE, changing a large number of people from one character to another, is not conducive to RP. It eliminates all character and in-game progress from the round, encourage people to either act poorly, or to not act at all. I would recommend that this feature be removed from Sage - which is ostensibly the more RP-oriented of the two BeeStation servers. The goal of roleplaying is to establish a character. While this is possible while taking the body of an entirely different character, it is less than optimal. I'm mostly making this issue to field thoughts in the comments. Spitting at the wall, and seeing what sticks.
> 
> didnt i already remove this event from rotation

Apparently not, since it happened last round. Probably happened under the Wizard.

EDIT: I defiantly believe it was removed as a regular event, I argue it should be remove entirely from Sage.

**Comment by Crossedfall** [comment]
I'll be real, I think this actually can add to RP. I don't really see it as an automatic loss to roleplay.

**Comment by badideaguy** [comment]
Wizard is THE lrp antag, this isn't surprising
