### ISSUE TITLE
Morgue does not light up when impersonated by ling

### ISSUE THREAD

**Issue by Alainx277** [BeeStation/BeeStation-Hornet#2115]
## Reproduction:

I was absorbed by a ling, which proceeded to impersonate me.
When I got put in the morgue (for some reason), it stayed red no matter how many times I exited and re-entered my body.

I assume morgues should still work when someone steals your identity.

**Comment by TheTrigg** [comment]
That's because it renders you husked and unclonable. Think about it, they steal your DNA. You can't be cloned if your DNA is all fucky.

**Comment by Alainx277** [comment]
> That's because it renders you husked and unclonable. Think about it, they steal your DNA. You can't be cloned if your DNA is all fucky.

I always thought husked bodies could be brain revived?

**Comment by TheTrigg** [comment]
They can. Mindless bodies too. And the trays don't beep. Pretty sure they indicate whether the body can be _cloned_; most corpses can be revived given enough surgical effort. So yes, I'm pretty sure you could be revived via surgery if a very attentive medical doctor noticed that there was still a soul in your body (via the lack of the "and their soul has departed..." part of the message). But c'mon, we know that's never gonna happen.

**Comment by Alainx277** [comment]
Honestly if you get put into the morgue and it doesn't light up you will NEVER be revived.
I'd advocate to change it so it tells you if someone's ghost is still present, even when you are husked (which happens quite often).

**Comment by eLeCtrOssSnake** [comment]
Do not think that this is an issue, bug or intended behaviour, the changeling lore explains it pretty clearly.

**Comment by PowerfulBacon** [comment]
TRAIT_BADDNA prevents the morgue light from activating.
