### ISSUE TITLE
Slimes attack trough directional glass doors

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#2145]
Issue reported from  Round ID: 18575 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1527

Slimes are able to attack trough glass doors for some reason i do not know which PR caused this but it is quite annoying if you are doing xenobio as hungry slimes often attack you or kill that one monkey another slime is eating causing him to get less food and wasting monkeys.
How to reproduce: just put a slime behind a glass door let it get hungry and then put a monkey behind said door if the monkey stays there the slime will stun the monkey but because of the door the slime can't feed on it and will instead keep attacking the monkey until it dies or attack you if are happening to stand to near.

**Comment by eLeCtrOssSnake** [comment]
Never encountered such even though had situations where slimes where hungry and I was behind directional glass door. Doubt.

**Comment by MNarath1** [comment]
> Never encountered such even though had situations where slimes where hungry and I was behind directional glass door. Doubt.

@eLeCtrOssSnake The problem seems to have been fixed trough  https://github.com/BeeStation/BeeStation-Hornet/pull/2152 i forgot to close this Issue trough i will do so now as it is not a problem anymore.
