### ISSUE TITLE
Sleeping Carp does not block projectiles

### ISSUE THREAD

**Issue by FancyPak** [BeeStation/BeeStation-Hornet#2146]
Issue reported from  Round ID: 18575 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1526

It appears that the sleeping carp ability does not block bullets or lasers, which the discription suggests it should

**Comment by ivanmixo** [comment]
Works fine on private server. Deflects every single projectile fired from a gun, balistic or otherwise.

**Comment by eLeCtrOssSnake** [comment]
Well, it does not block them, you dodge them. Everything works as intended.

**Comment by PowerfulBacon** [comment]
Works fine, Sleeping carp does not block shotgun blast back which is a massive oversight due to the shoddy shotgun code and it doesn't block spear gun projectiles which is intentional (hunting carps.)
