### ISSUE TITLE
was able to see parts of deadchat for some reason

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#2151]
## Reproduction: just happened randomly during a game
![9a3cbc9fac47c685dccbae2b638ed8b1](https://user-images.githubusercontent.com/59359762/87759410-83198e00-c7cb-11ea-8745-046a2e63aa99.png)

**Comment by Bastian0930** [comment]
Did you by any chance hallucinate you died? This happens on purpose iirc.

**Comment by hotimep** [comment]
nah, was walking around, SM didn't explode either, straight up was just able to see deaths and people talking in deadchat, small bursts of it, i mean
