### ISSUE TITLE
Health Sensor "Sense Death" mode doesn't trigger a chemical grenade on death

### ISSUE THREAD

**Issue by LivingBatteryBox** [BeeStation/BeeStation-Hornet#2154]
## Round ID:
Round 18674

## Reproduction:
Step 1: Get a health sensor and a chemical grenade setup, using a multitool to change the health sensor to "detect death" mode.
Step 2: Attach the health sensor to the chemical grenade's one and only crimson wire.
Step 3: Secure grenade casing with screwdriver.
Step 4: Die
Step 5: Realize that you can't blow up while saying "Truth be told, the game was rigged from the start." in crit
cause the health sensor is borked.

**Comment by Mick1299** [comment]
Pretty sure health sensors only work in your hand or pocket. Was the grenade in your bag?

**Comment by Angustmeta** [comment]
Did you turn it on? 

![200718 1136 53](https://user-images.githubusercontent.com/46400996/87849725-14335680-c8eb-11ea-84f1-6ea3bc4273b8.png)

**Comment by LivingBatteryBox** [comment]
Oh, dangit... Nevermind.
