### ISSUE TITLE
hacked shady cigs deluxe shows wrong price for e-cigs

### ISSUE THREAD

**Issue by ToasterBan** [BeeStation/BeeStation-Hornet#2157]
Issue reported from  Round ID: 18707 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1526

when trying to buy an e-cig, the vendor says it costs 10 credits, but with 30 credits it says insufficient funds

Reproduction:
step one be an assistant (or just have 30? credits or less)
step two hack a smoking vendor so it displays contraband
step three try to buy e-cig

**Comment by BettonnCZ** [comment]
its hacked im about to purchase
![obrazek](https://user-images.githubusercontent.com/63119702/88686589-87ad4300-d0f7-11ea-8d3f-7b6a1be90a79.png)
![obrazek](https://user-images.githubusercontent.com/63119702/88686663-98f64f80-d0f7-11ea-8b43-b370b7932d51.png)
my dude is right

**Comment by BettonnCZ** [comment]
the vape should be 50cr as the others, since price of contraband is 50 by default

**Comment by BettonnCZ** [comment]
dunno how to fiks )) probably DM is just confused and shows it as a default price for normal items

**Comment by BettonnCZ** [comment]
![obrazek](https://user-images.githubusercontent.com/63119702/88689215-816c9600-d0fa-11ea-854a-cf6985f07b07.png)
nevermind, i moved the vape to the premium list so it shows the proper price.
