### ISSUE TITLE
tgui paper has broken paper

### ISSUE THREAD

**Issue by YakiAttaki** [BeeStation/BeeStation-Hornet#2171]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
paper can now no longer be read off doors or by examining it with shift click, and stamping is now a fucking minigame instead of literally just stamping the paper with a click.
Literally just try to examine a piece of paper; you cannot, you have to physically pick it up and use it to examine it

**Comment by imw-Oculus** [comment]
I can confirm this issue, and additionally note that - even before the Paper update - one has to click twice on a folder to insert a piece of paper if the folder is not in-hand. Maybe even if it is in-hand. I'll make a separate issue, I suppose.

**Comment by eLeCtrOssSnake** [comment]
Still doesn't work.

**Comment by KubeRoot** [comment]
I believe this issue was fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/2860
