### ISSUE TITLE
Conflicting and nonsensical language shortcut keys

### ISSUE THREAD

**Issue by yorii** [BeeStation/BeeStation-Hornet#2176]
Not a regular issue, it has just been brought to my attention that the language keys need to be altered, in particular due to this conflict:
![image](https://user-images.githubusercontent.com/7960287/88243515-eb1b1900-cc90-11ea-90b0-389bf38fb205.png)

Here is a list of all current languages and their shortcuts:

```
Aphasia		,i
Apidite		,*
Beachbum	,u
Buzzwords	,z
Calcic		,b
Codespeak	,t
Common		,0
Draconic	,o
Drone		,d
Machine		,6
Moffic		,m
Monkey		,1
Mushroom	,y
Narsian		,n
Piratespeak	,p
Ratvarian	,r
Rlyehian	,x
Shadowtongue	,x
Slime		,k
Swarmer		,s
Sylvan		,h
Terrum		,g
Uncommon	,!
Volcaic		,v
Xenocommon	,4
```

Some of these are nonsensical, and two of them conflict.

**Comment by yorii** [comment]
I made the issue since I feel it's not up to me to decide what to alter these to.

**Comment by St0rmC4st3r** [comment]
Remove everything from .x since it is also a Voice of God pefix.
