### ISSUE TITLE
Bee coin shop items not spawning in

### ISSUE THREAD

**Issue by Iocanthos** [BeeStation/BeeStation-Hornet#2194]
## Reproduction:

Bee coin shop items (exec jacket, tie, glassess, lace up shoes) I have purchased and equip often fail to apply when I late join. If I join right after round start im usually fine, past 5 minutes I seem to have a nearly 100% chance of not spawning in with any of the items.

Really all I can say at this point :<

**Comment by imw-Oculus** [comment]
I've noted this before, but I could've sworn there was already an issue. Guess not. Yes, items that were purchased in the BeeCoin shop have an almost random chance to spawn into your inventory. I'll take a look at the code, and see if I can layout the issue from a coding perspective.

**Comment by super12pl** [comment]
> I've noted this before, but I could've sworn there was already an issue. Guess not. Yes, items that were purchased in the BeeCoin shop have an almost random chance to spawn into your inventory. I'll take a look at the code, and see if I can layout the issue from a coding perspective.

So did you find anything?

**Comment by Iocanthos** [comment]
If it is of any help, usually the items that occupy slots that are occupied at round start do not spawn in. Example:

Glasses and ties: spawn 95% of the time. Shoes or other inner layer clothing? Those barely ever do spawn. They sometimes do in backpack/satchel or in hand, but more often than not, they do not at all.

**Comment by Crossedfall** [comment]
Likely related to https://github.com/BeeStation/BeeStation-Hornet/issues/2283. Closing in favor of the other issue
