### ISSUE TITLE
Ethereals cannot recharge despite being low on charge

### ISSUE THREAD

**Issue by tomohawks-FLINT** [BeeStation/BeeStation-Hornet#2204]
Issue reported from  Round ID: 19010 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1526

Ethereals can no longer absorb power from APCs, saying that you're always at full charge (batteries, too). You can absorb power from lightbulbs, but you never loose the lower power status and constantly take damage from low power.
![etherealnopower](https://user-images.githubusercontent.com/61092939/88462839-5d9c1c80-ce7c-11ea-8fd0-d308f567aef0.png)

**Comment by Mick1299** [comment]
#2178

**Comment by yorii** [comment]
I'm sure it will be merged anytime now...
![image](https://user-images.githubusercontent.com/7960287/88486786-7db50400-cf80-11ea-9f99-3370adbeabec.png)
