### ISSUE TITLE
you can become a gang leader even if the jobs are antag protected

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#2218]
## Reproduction:
the glitch has existed for a while now from what i've seen, if you have a protected antag job set to high, (i.e security, ai, captain) and you also roll for gang leader, the game kicks you back to the main menu. Then when you try and join back into the game, the job you pick will have 100% chance of becoming gang leader.

yorpan says this: Admin PM from-Yorpan: the bug is either that mindshielded people can roll gang boss, or that gang boss doesn't override mindshield, and all the logic happens during a single tick at roundstart so it gets a bit fucky

**Comment by hotimep** [comment]
by the way, if this happens, you spawn with no gang stuff, no hud, no gang tool

**Comment by PowerfulBacon** [comment]
Ghosts and new_player can also become gang leaders for some reason
