### ISSUE TITLE
Circuits "Inserter" doesn't work

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#2219]
Issue reported from  Round ID: 19112 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1528

Test Merges: Syndie Incursion (Team based traitors) #2168

Issue: I was working with circuits, and tried to use an inserter (yes, I made sure it was properly wired) to put a plasma sheet inside a Satchel, located by an adjacent locator and referenced to the inserter. However, it just didn't do that, and didn't remove the plasma from a grabber's inventory. When I tried just a simple machine to put a scanned item inside the satchel, it didn't work either, and just dropped the item on the floor.

Code for the simple machine: {"assembly":{"type":"type-a electronic mechanism"},"components":[{"type":"button"},{"type":"ranged sensor"},{"type":"scanner","inputs":[[1,0,1]]},{"type":"inserter","inputs":[[3,0,0]]},{"type":"half-sec delay circuit"},{"type":"adjacent locator"}],"wires":[[[1,"A",1],[4,"A",1]],[[3,"O",1],[4,"I",1]],[[3,"A",1],[6,"A",1]],[[4,"I",2],[6,"O",1]],[[4,"A",1],[5,"A",2]],[[5,"A",1],[6,"A",2]]]}

Needs to be "calibrated" by pointing it to the satchel to get the reference for it so the locator can find the satchel in the game world. Was supposed to work by clicking the mechanism with an item, and, after a short delay, put it in the satchel. 

Just in case it helps, the original machine was an attempt at something to inject plasma into a dark purple extract, and store surplus sheets inside a satchel, before taking a second sheet and grinding it down. Doesn't work as intended, but here is the code for it:

{"assembly":{"type":"type-a electronic machine"},"components":[{"type":"tiny photovoltaic cell"},{"type":"adjacent locator","name":"Plasma Grinder Locator"},{"type":"starter"},{"type":"inserter"},{"type":"grabber","name":"Plasma Grinder Grabber","inputs":[[2,0,1]]},{"type":"half-sec delay circuit"},{"type":"grabber","name":"Ref Grabber","inputs":[[2,0,1]]},{"type":"tenth-sec delay circuit"},{"type":"scanner","inputs":[[1,0,1]]},{"type":"ranged sensor"},{"type":"inserter","inputs":[[3,0,1]]},{"type":"reagent grinder"},{"type":"adjacent locator","name":"Industry Locator"},{"type":"adjacent locator","name":"Container Locator"},{"type":"reagent pump","inputs":[[3,0,20]]},{"type":"integrated hypo-injector","inputs":[[2,0,20]]},{"type":"grabber","name":"Plasma Surplus Grabber","inputs":[[2,0,1]]},{"type":"adjacent locator","name":"Plasma Surplus Locator"},{"type":"button","name":"Boot Up"},{"type":"five-sec delay circuit"},{"type":"one-sec delay circuit"},{"type":"tenth-sec delay circuit"},{"type":"tenth-sec delay circuit"},{"type":"tenth-sec delay circuit"},{"type":"tenth-sec delay circuit"},{"type":"five-sec delay circuit"},{"type":"tenth-sec delay circuit"}],"wires":[[[2,"I",1],[7,"O",1]],[[2,"O",1],[5,"I",1]],[[2,"A",1],[19,"A",1]],[[2,"A",1],[26,"A",2]],[[2,"A",2],[8,"A",1]],[[3,"A",1],[16,"A",4]],[[3,"A",1],[12,"A",4]],[[5,"O",1],[12,"I",1]],[[5,"A",1],[8,"A",2]],[[5,"A",2],[22,"A",1]],[[7,"I",1],[9,"O",1]],[[7,"O",1],[18,"I",1]],[[7,"A",1],[9,"A",1]],[[11,"I",1],[17,"O",1]],[[11,"I",2],[14,"O",1]],[[11,"A",1],[25,"A",2]],[[11,"A",2],[26,"A",1]],[[12,"O",2],[15,"I",1]],[[12,"A",1],[22,"A",2]],[[12,"A",2],[23,"A",1]],[[13,"O",1],[16,"I",1]],[[13,"A",1],[19,"A",1]],[[14,"A",1],[19,"A",1]],[[15,"I",2],[16,"O",2]],[[15,"A",1],[23,"A",2]],[[15,"A",2],[27,"A",1]],[[16,"A",1],[27,"A",2]],[[16,"A",2],[20,"A",1]],[[17,"I",1],[18,"O",1]],[[17,"A",1],[24,"A",2]],[[17,"A",2],[25,"A",1]],[[18,"A",1],[21,"A",2]],[[18,"A",2],[24,"A",1]],[[20,"A",2],[21,"A",1]]]}

Also needs to be "calibrated" with a debugger to place the respective references inside the locators. Does pretty much the same thing: takes the plasma from the floor, but instead of transfering it to the satchel, just leaves the sheet in the storage.

**Comment by imw-Oculus** [comment]
If you see the actual code of the Inserter, you will hilariously note that there is comment code simply stating "doesn't work" - and it was merged at some time, by some person, anyway.
I'll examine this along the lines of what you found out, from a coding perspective, and post up again here with the precise layout of what a fix would be.
