### ISSUE TITLE
Adamantite shield does no damage and does not block anything

### ISSUE THREAD

**Issue by LivingBatteryBox** [BeeStation/BeeStation-Hornet#2221]
Issue reported from  Round ID: 19134 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1527

Make a shield using xenobiology and it won't deal damage, despite the fact that it is a shield, will not block anything. According to the wiki it is supposed to do 15 brute.

**Comment by That0nePerson** [comment]
I can't reproduce this on a private server. The shield does 15 brute and blocks damage for me.
