### ISSUE TITLE
Lizards spawning without draconic

### ISSUE THREAD

**Issue by super12pl** [BeeStation/BeeStation-Hornet#2231]
Round ID: Every round

Issue: When joining the round lizards can spawn without being able to speak/understand draconic.

Reproduction : 1. Choose lizard character 2. Try to join round

Image:
![Zrzut ekranu (115)](https://user-images.githubusercontent.com/67762796/88907376-d4f4f600-d258-11ea-8e48-532f023ffe99.png)

**Comment by yorii** [comment]
I have tried looking for the issue but I really for the life of me can't figure this one out... The code for draconic is identical to any other racial language, I see no reason at all why it wouldn't work...
