### ISSUE TITLE
Sepia slime extracts delete whatever you inject them with

### ISSUE THREAD

**Issue by LivingBatteryBox** [BeeStation/BeeStation-Hornet#2234]
Issue reported from  Round ID: 19226 (BeeStation Sage - MRP For Everyone!)
When you inject a sepia slime extract with plasma, it seems to cause whatever you used to inject the extract to disappear.
Reporting client version: 513.1527

**Comment by aguyiguess** [comment]
Is anyone able to replicate this? This doesn't happen for me.

**Comment by LivingBatteryBox** [comment]
I think you have to be hit by the timestop yourself in order for the bug to occur.

**Comment by Crossedfall** [comment]
I can't reproduce this. If you can determine more exact steps that'd be helpful.
