### ISSUE TITLE
Repository description is invalid

### ISSUE THREAD

**Issue by AffectedArc07** [BeeStation/BeeStation-Hornet#2237]
Not really a game issue so it doesnt follow standard format.

The repository description reads the following:
![image](https://user-images.githubusercontent.com/25063394/88969571-f54ca100-d2a8-11ea-82f5-6ee4d86aa261.png)

However after calling in the best detectives on the planet and spending a fortune on research teams, we have come to the conclusion this statement is invalid. 
![image](https://user-images.githubusercontent.com/25063394/88969611-05fd1700-d2a9-11ea-9b49-7039e1a5a5c2.png)

As seen here, the codebase contains hostile bees, bee sprites, a beesease disease and a beekeeper suit. This breaks the description and is not good.

**Comment by qwertyquerty** [comment]
Did your investigation team successfully calculate exactly what % of bees we are?

**Comment by AffectedArc07** [comment]
@qwertyquerty Sadly not, I did not have the funds to hire the whole of the FBI for this investigation, and I couldnt find any other force competent enough to get the exact percentage. I humbly apologise.

**Comment by qwertyquerty** [comment]
Well then how do you expect us to fix this?? God arc, always doing the bare minimum

**Comment by LemonInTheDark** [comment]
good fucking god what are you doing beating around the bush. this is top priority, how dare you demean the man for coming forward

**Comment by AffectedArc07** [comment]
I got hold of a quantum computer, ran the maths, and I have come to the conclusion that the codebase is approximately `0.0310192418`% bees

![image](https://user-images.githubusercontent.com/25063394/88972297-3c3c9580-d2ad-11ea-9879-3c47ff57a19f.png)
Its also 562,168 lines of code but thats beside the point

**Comment by ike709** [comment]
![image](https://user-images.githubusercontent.com/5714543/88972476-3af27500-d27b-11ea-88fc-cf87e08024fb.png)

Resolved.
