### ISSUE TITLE
Atmos doesnt try and do pressure or temp damage to windows/walls on the tile beside it.

### ISSUE THREAD

**Issue by Jalleo** [BeeStation/BeeStation-Hornet#2255]
This was tested on the latest version of Yog and is confirmed on NSV.  Bee (NSV was recently updated so bee counts too)

## Reproduction:
Make a TEG. Use plasma windows that face to the tiles you want to burn to keep it contained without any issues.
E.G.
![image](https://user-images.githubusercontent.com/4549053/89332879-0a9c4380-d68c-11ea-96e2-a26188142467.png)
Of which a setup like this when it gets released by a admin or by accident causes
![image](https://user-images.githubusercontent.com/4549053/89332950-230c5e00-d68c-11ea-87e5-d70e90ef517f.png)
There is no temp or pressure sharing to tiles outside of the fire so its technically perfectly contained and gets to temperatures hotter than anything that is actually possible in a lab even theoretically (A lot more than the sun)

This allows for TEGs on the NSV13 codebase after a 25% nerf to power generation get to 250 MW if setup correctly or even higher to the point where the gasses may overflow on the integers. That last part is currently unproven.

**Comment by Jalleo** [comment]
This is a joint bug report with https://github.com/yogstation13/Yogstation/issues/9386

**Comment by Jalleo** [comment]
This is highly related to the current PR at https://github.com/tgstation/tgstation/pull/52493

**Comment by LemonInTheDark** [comment]
something something :), something something fuck the teg
