### ISSUE TITLE
drinking a lavaland potion as any race gives you mechanical wings instead of the ones you're supposed to get

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#2256]

**Comment by hotimep** [comment]
don't know if the problem is on the othe races

**Comment by zeskorion** [comment]
I have no fucking idea how or why this happens. gonna look up every single instance of MOB_ROBOTIC and see if you can get it applied somehow

**Comment by hotimep** [comment]
in action
![epic](https://user-images.githubusercontent.com/59359762/89482095-66cb9a00-d756-11ea-8627-a83df9b547c6.gif)
clideo.com

**Comment by Mick1299** [comment]
I noticed this the other day. Got robotic wings when I drunk it as a human

**Comment by super12pl** [comment]
Every type of flight potion gives mechanical wings to every species @zeskorion please fix

**Comment by super12pl** [comment]
#2299 fixed this

**Comment by RedFoxIV** [comment]
but robot wings are cool

**Comment by PowerfulBacon** [comment]
Resolved
