### ISSUE TITLE
Regex error? String exploder circuit does not output properly with null delimiter

### ISSUE THREAD

**Issue by PKPenguin321** [BeeStation/BeeStation-Hornet#2265]
https://github.com/BeeStation/BeeStation-Hornet/blob/ed661d41b3f2964bc0be39418e49d964d4c8d37f/code/modules/integrated_electronics/subtypes/text.dm#L237-L238

Intended behavior of the above:
If the delimiter of the string exploder is set to null, it should turn the given string into a list of each individual character, IE a string `"joey"` would become a list like `{"j", "o", "e", "y"}`

The bug:
Instead, the string exploder circuit outputs a list of empty strings that is one longer than intended if the delimiter is null. The same `"joey"` string from before becomes a list like `{"", "", "", "", ""}`
This is possibly because the regex here is bad:
https://github.com/BeeStation/BeeStation-Hornet/blob/ba40cb637d38cb9520b7a23c1cc0de53433dbf8d/code/__HELPERS/text.dm#L550

**Comment by Crossedfall** [comment]
The regex isn't needed and can be removed entirely. 

https://github.com/BeeStation/BeeStation-Hornet/blob/ed661d41b3f2964bc0be39418e49d964d4c8d37f/code/modules/integrated_electronics/subtypes/text.dm#L237-L238

Can be updated to use `splittext(strin, "")` instead.
