### ISSUE TITLE
Slimes stop feeding after a while

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#2269]
Issue reported from  Round ID: 19580 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1528

Test Merges: none

Reproduction: work on xenobio for about half an hour, and try to feed the slimes with monkeys. At some point, they all stop feeding for no apparent reason, and will not attempt to even if ordered to attack, just ignoring the monkeys.

**Comment by ike709** [comment]
I can't debug this unless an admin VVs several slimes when it's happening and notes if `special_process` is `TRUE` or `FALSE` on them. The number of slimes that exist when it occurs would also be useful.

Also is it *some/most* slimes or *all* slimes? Important distinction.

**Comment by gabrielckc** [comment]
> Also is it _some/most_ slimes or _all_ slimes? Important distinction.

All slimes.

**Comment by eLeCtrOssSnake** [comment]
Did not see once.

**Comment by PowerfulBacon** [comment]
I believe this was fixed at some point
