### ISSUE TITLE
You cant recharge bluespace compression kit with bluespace polycrystal.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#2271]
You just cant. It seems like an oversight.

**Comment by St0rmC4st3r** [comment]
Well, just make separate crystals, what's the problem?

**Comment by IllotAFV** [comment]
You need plasma and diamonds for them, right? Sometimes diamonds are not available.

**Comment by Mick1299** [comment]
1. Hold the polycrystal in one hand
2. Click on it with your other hand
3. ???
4. Profit

**Comment by PowerfulBacon** [comment]
You cant use polycrystals for almost anything and you cannot separate down polycrystals into single Crystal's, I believe this is to prevent people using all the bs Crystal's on stupid shit like smashing them

**Comment by IllotAFV** [comment]
Ok, using another hand on the polycrystal actually breaks it down to the stable crystal, but its not intuitive at all, and there is only so much information about this way of getting crystals. It says, that it needs to be broken off, but I was using it in one hand, like nearly everything else in this game, getting very vague "You cannot crush the polycrystal in-hand".
