### ISSUE TITLE
Code Bounty: Station Role: Antifa Member [$15]

### ISSUE THREAD

**Issue by dbford** [BeeStation/BeeStation-Hornet#2275]
New Station Role: Antifa Member
Role Responsibilities: Report bad behavior to admins through report system
Role Win Conditions: Admin action, started from antifa reports, taken against 2+ players 
Role Lose Conditions: Annoy admin enough to themselves get banned
Role Graphics: Trumpet guy in this pic: [link]( https://twt-thumbs.washtimes.com/media/image/2020/07/27/racial_injustice_portland_32764_s878x585.jpg?9739c089d09019457eff90957353d2bf131e7da7)
Role Items: Trumpet, Black cloths, maybe umbrella

Please let me know if any additional information is required.

https://www.bountysource.com/issues/92268717-code-bounty-station-role-antifa-member

**Comment by zeskorion** [comment]
sorry bud, you're about 24 hours too late to get in as a gimmick role

**Comment by francinum** [comment]
This is a fucking terrible idea.
