### ISSUE TITLE
Code Bounty: New Station Role - 007 Spy

### ISSUE THREAD

**Issue by dbford** [BeeStation/BeeStation-Hornet#2276]
New Station Role: 00-Spy
Role Reponsibilities: Various antag tasks (steal an item, assasinate a role, pm @Crossedfall a dirty pic)
Role Items: license to kill (does what is says, can be stolen), silenced pistol, costume of some other role
Role Win Conditions: Fullfill all tasks
Role Lose Conditions: Fail to fullfill all tasks before game end

License to kill item - this item would be a holdeable item giving permission to kill any person if doing so advances the antag goals. Space police must release the holder if they are arrested for murder while holding it. This item can be stolen.

**Comment by PowerfulBacon** [comment]
I mean this could work as a minor antag role, but the licence to kill doesn't really work that well since people just gunna kill anyway even if they lose it.

**Comment by eLeCtrOssSnake** [comment]
Antag - yes, most likely with traitors blood bros and etc. Event antag - yes. Station job - no.

**Comment by badideaguy** [comment]
This is just a traitor, under cover agents from a rival organization to complete an objective with special tools to do said objective
