### ISSUE TITLE
Renaming borgs not logged

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#2308]
Yes, this is an issue now for some reason.
Borgs can have a non-random name set via user setting preference, or by having their random name changed by admin/player.

As far as I am aware, there are 3 ways to rename borgs. 

1. Via rename upgrade
https://github.com/BeeStation/BeeStation-Hornet/blob/aa29c77e3b1ab60112395f2c4ad3a165fbe2abad/code/game/objects/items/robot/robot_upgrades.dm#L42

2. Via PDA applied to borg shell before a MMI/Posibrain has been added to the shell
https://github.com/BeeStation/BeeStation-Hornet/blob/aa29c77e3b1ab60112395f2c4ad3a165fbe2abad/code/game/objects/items/robot/robot_parts.dm#L396

3. Via admin-tools Borg Panel (already logged)
[2020-08-19 18:31:03.383] ADMIN: Bloons3/(Myriam Powell) renamed *no key*/(VVrename) to BPrename.
[2020-08-19 18:31:03.383] GAME: *no key*/(VVrename) VVrename name changed from VVrename to BPrename (Research Division (173, 116, 2))

4. Via VV (already logged, but not well)
[2020-08-19 18:30:47.478] GAME: *no key*/(Borgi Cyborg-227) Borgi Cyborg-227 name changed from Borgi Cyborg-227 to VVrename (Research Division (173, 116, 2))

Methods 1 and 2 are the only methods that a normal player could use to rename a borg.

It was noticed in a recent round that a borg had an _inappropriate_ name, but the origin of that name couldn't be proved to originate to a specific user directly, only indirectly.

$5 bounty (Crypto, PayPal, BountySource) to add logging for methods 1 and 2 that will log in game.log (or a more appropriate log) what a player has renamed a borg to.

The log line should include the user's CKEY, in game name, and location, as well as the borg's original name and new name.

**Comment by St0rmC4st3r** [comment]
I'll do it.

**Comment by bloons3** [comment]
Resolved by #2310
