### ISSUE TITLE
Reebe fucking deletes slimepeople & other clockcult bullshit

### ISSUE THREAD

**Issue by yyzsong** [BeeStation/BeeStation-Hornet#2311]
Reproduction:

If you are a clockcult slimeperson, teleporting to reebe will deal assloads of toxin damage and melt you as soon as you get on it.

Also, for the slimeperson subspecies that creates more of itself, its other bodies will stay on the station even when they all get mass recalled back to reebe, which could potentially allow for Servants to cross the barrier that keeps them out and maxcap the invader from their backlines or something (Havent gotten to see if this works yet)

**Comment by Flakkyboo** [comment]
fukin snowflake races

**Comment by ike709** [comment]
@PowerfulBacon Is this still an issue?
