### ISSUE TITLE
BIG ASS ISSUE: Gloves of the north stars give you literal fucking aimbot

### ISSUE THREAD

**Issue by ivanmixo** [BeeStation/BeeStation-Hornet#2314]
## Testmerges:

There is one on LRP, but it doesn't matter because even in older versions before the test merge this was a thing.

## Reproduction:

So holy fucking shit.  Basically have the mob/person you want to punch next to you with the gloves on, go harm intent and just start clicking ANYWHERE. You will start punching the person next to you. Doesn't matter if you're moving or standing still, or just passing through a crowded hallway you will just start fucking going ham on their ass. You can just kite them until they die, basically giving them no chance of clicking you.

If you combine this with carp and or noslips/magboots you are literally pretty much fucking invincible. 

I have no idea how this happened or when it happened but this is absolutely ridiculous.

**Comment by That0nePerson** [comment]
#1709 added this, it was made by zesko and approved by ike

**Comment by ghost** [comment]
this is a feature.

**Comment by zeskorion** [comment]
Feature not bug

**Comment by ivanmixo** [comment]
oh shit this is intentional? kinda epic
