### ISSUE TITLE
Pituitary Disruption combined with necrotic metabolism bug

### ISSUE THREAD

**Issue by Demi-Wahoo** [BeeStation/BeeStation-Hornet#2321]
## Reproduction:
1. Create Virus containing "Pituitary Disruption" and "Necrotic Metabolism", reaching stage speed 12 treshhold.
2. Infect player with it (Someone or yourself).
3. After disease reaches max stage speed, kill the infected person and clone them.
4. After finishing cloning, decapitate the corpse and wait for head to regrow.
Results: Player who got cloned, is taken back to his old body (corpse), possibly due to "regrowing" brain (head).

**Comment by zeskorion** [comment]
This is intentional behaviour, but i put isliving checks in there to avoid this happening to living people iirc. Ill fix it in the future

**Comment by Demi-Wahoo** [comment]
i was really surprised when i found this bug. I brought my corpse to chef and moments later i suddenly got ghosted. I pressed re-enter body and i was taken to my old body and it just ended badly for me. I was dead, couldn't do anything and chef harvested my head for infinite brains and other organs.
