### ISSUE TITLE
Hotdogs are not pastries

### ISSUE THREAD

**Issue by Ansome101** [BeeStation/BeeStation-Hornet#2322]
## Round ID:
NSV13 Round 845

## Reproduction:
I tried making a hotdog in the crafting menu - it's listed under pastries. Why? Why is it listed under pastries? What kind of pastries are you people making?

**Comment by Mick1299** [comment]
What, you mean hotdogs don't look like this?

![image](https://user-images.githubusercontent.com/54165560/91514260-a6d30680-e929-11ea-829d-9b4e9db1be94.png)

**Comment by eLeCtrOssSnake** [comment]
Why does this PR have a "good first issue" label on it, it's kinda cringe.

**Comment by ItsTisme** [comment]
Speed PR right now
