### ISSUE TITLE
Displaced window on syndicate lavaland spawner

### ISSUE THREAD

**Issue by Nosnek199** [BeeStation/BeeStation-Hornet#2332]
Issue reported from  Round ID: 20371 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1526

As you can see here, a window is displaced the on syndicate lavaland spawner.
![displaced window](https://user-images.githubusercontent.com/70182306/91111651-135eb480-e64f-11ea-8727-8aaf3fcf1648.JPG)

**Comment by super12pl** [comment]
Theres no displaced window on the map the one on an image was moved during the round @Nosnek199

**Comment by PowerfulBacon** [comment]
That happens when a large mob, like an ash drake or something walks into the window. Not an issue with the map
