### ISSUE TITLE
Lizard light snout option is above some helmets and masks' layers.

### ISSUE THREAD

**Issue by r1ks-iwnl** [BeeStation/BeeStation-Hornet#2334]
Sharp + Light and Round + Light lizard snout options are above the layer of some masks and helmets, so far i only noticed this on the air mask and skinsuit helmet you find in your internals box. I tried fixing it myself but had no clue where to start.
It only seems to do this when your character is facing south.

![Screenshot_1](https://user-images.githubusercontent.com/69760936/91169298-c119a400-e6df-11ea-920a-d6bfcc908b2a.png)
![Screenshot_3](https://user-images.githubusercontent.com/69760936/91169302-c37bfe00-e6df-11ea-8cb2-844e368cc79b.png)

**Comment by super12pl** [comment]
#2341 @r1ks-iwnl

**Comment by r1ks-iwnl** [comment]
Ah, nice. When i tried to fix it i was messing around with the snout options, didnt realize the masks were the problem.

**Comment by r1ks-iwnl** [comment]
Reopened since #2341 closed without a good fix.
