### ISSUE TITLE
Client Graphics stops working

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#2350]
Issue reported from  Round ID: 20519 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1529

I did check on other servers, so far it only happens on beestation. The graphics part of the client just stops after a few minutes of gameplay. The rest works fine.

If I try to adjust the client display to change the size of the graphics part, when it is frozen, the client crashes sooner. If I do not do that it crashes after a while.

**Comment by yorii** [comment]
Download the new BYOND version 513.1530 that was released today: http://www.byond.com/download/
