### ISSUE TITLE
Signalers do not log persistently

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#2357]
$ grep -i "lastsignalers" -r
code/game/objects/items/devices/PDA/radio.dm:   GLOB.lastsignalers.Add("[time] <B>:</B> [usr.key] used [src] @ location [AREACOORD(T)] <B>:</B> [format_frequency(frequency)]/[code]")
code/modules/admin/secrets.dm:                  list("Show last [length(GLOB.lastsignalers)] signalers", "list_signalers"),
code/modules/admin/secrets.dm:                  var/dat = "<B>Showing last [length(GLOB.lastsignalers)] signalers.</B><HR>"
code/modules/admin/secrets.dm:                  for(var/sig in GLOB.lastsignalers)
code/modules/admin/secrets.dm:                  usr << browse(dat, "window=lastsignalers;size=800x500")
code/modules/assembly/signaler.dm:              GLOB.lastsignalers.Add("[time] <B>:</B> [usr.key] used [src] @ location ([T.x],[T.y],[T.z]) <B>:</B> [format_frequency(frequency)]/[code]")
code/_globalvars/logging.dm:GLOBAL_LIST_EMPTY(lastsignalers)    //! keeps last 100 signals here in format: "[src] used [REF(src)] @ location [src.loc]: [freq]/[code]"
code/_globalvars/logging.dm:GLOBAL_PROTECT(lastsignalers)

Signalers don't log to disk, which makes investigating hard.

**Comment by PowerfulBacon** [comment]
Seems to still be an issue as of 06/06/2022

**Comment by ivanmixo** [comment]
I did this in my better maxcap logging PR

**Comment by Penwin0** [comment]
Ivan did infact do this
