### ISSUE TITLE
Firelocks can't be built

### ISSUE THREAD

**Issue by 4rchibald** [BeeStation/BeeStation-Hornet#2363]
It appears we can't currently build any firelocks.
When using metal sheet we can choose to start building old firelock, we can put wires and board inside but when it comes to finishing it up with wrench it doesn't work properly. Once loading bar is full you get a message ' You finish the firelock.' but its not finished, its not even bolted down to floor.
As far as I can tell there's no way to even start building new, slim firelocks.

No idea how it got overlooked, I remember reporting it while new atmos was still being tested. Because of how air works now its important that we have ability to build new firelocks to replace destroyed ones and add them wherever they are needed.

**Comment by eLeCtrOssSnake** [comment]
I have built new fastmossy shitty airlocks and they worked... I'll try to reproduce in a second.

**Comment by eLeCtrOssSnake** [comment]
Yeah, it seems that you can rebuild broken fastmos airlocks if their object wasn't destroyed, although you still can't create them from scratch, which is still ok because nobody builds them anyway.

**Comment by 4rchibald** [comment]
@eLeCtrOssSnake 
I wouldn't say its ok. Those airlocks are the only thing that allows us to play with fastmos. They already have some annoying issues even if they 'work' but not being able to build them is a big issue. They still get destroyed-either in explosions or, when in unanchored state, by less competent engineers who see them as obstruction or don't know how to fix them. 
Once firelock is gone its gone for good and we won't be able to properly secure area against problems with air.
Not to mention any new area build by players during the round, including custom shuttles, we are simply not able to provide them with any solution against fires, breaches etc

**Comment by eLeCtrOssSnake** [comment]
@4rchibald You got me totally right, I don't want to play with fastmos.
