### ISSUE TITLE
you can use antiviruses on any carbon lifeform

### ISSUE THREAD

**Issue by Ratvarr** [BeeStation/BeeStation-Hornet#2367]
Issue reported from  Round ID: 20662 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1527

you can install an antivirus on *any* carbon based lifeform
how to do: make antivirus
click on your pal spess man 
""Installing McValozk. Please do not turn your Human unit off or otherwise disturb it during the installation process.""

**Comment by PowerfulBacon** [comment]
bruh

**Comment by eLeCtrOssSnake** [comment]
It's a feature, not a bug, do not fix.

**Comment by zeskorion** [comment]
Hm.
