### ISSUE TITLE
Turret control doesnt actually target borgs

### ISSUE THREAD

**Issue by thelaughingbomb** [BeeStation/BeeStation-Hornet#2370]
## Round ID:

N/A: was a local version running beestation

## Testmerges:

No test merges were being run
## Reproduction:

Set turret to target borgs, turret dont shoot the borg.

Also camera hotkeys dont work.

![no target borgs](https://user-images.githubusercontent.com/59128923/91798541-744a4600-ec68-11ea-975b-0e1919811593.PNG)

I tried while the borg was synced and unsynced and got same results.

**Comment by jlsnow301** [comment]
Similar issue here, #2254
