### ISSUE TITLE
Something is wrong with TTVs reactions

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#2390]
I am not completely sure about this, but ive noticed it several times already, so... I guess?
Toxins behaves in a weird fashion. I put trit and oxygen mix with the ratio of 33:67 at 2550 pressure of 43 K in the oxy tank. And filled  plasma tank with 2550 pressure of 27000k. It was working before, with some variations in numbers of moles and temperature, but it was still working. But now it didnt do anything, the explosion was 0/1/5, however screen shaked like from the proper big explosion. After that I filled plasma tank with the same plasma, oxy tank with the same mix ratio, but only 900 pressure of trit and oxy mix. And after that it worked, explosion was of the 212/424/848 size. Yes, with that many moles of oxy and trit mix it couldnt give any more numbers in that explosion size. But why didnt the first bomb work? And it happened like twice already. 
EDIT: cant catch it anymore, but i am telling you, it was real.

**Comment by St0rmC4st3r** [comment]
Not sure. Probably some fastmos fuckery.
