### ISSUE TITLE
Reinforced flooring & Monstermos makes infinite iron.

### ISSUE THREAD

**Issue by Kerbin-Fiber** [BeeStation/BeeStation-Hornet#2420]
## Reproduction: break wall in atmos holder thingymcjigger
![gif](https://user-images.githubusercontent.com/31713423/92724575-18e31c80-f328-11ea-92e5-cb01725660d3.gif)

**Comment by Kerbin-Fiber** [comment]
Tested in CentCom too, it's a problem with the root reinforced obj type, `/turf/open/floor/engine`
![gif](https://user-images.githubusercontent.com/31713423/92725318-3795e300-f329-11ea-8760-26f38cdafe10.gif)

**Comment by Jalleo** [comment]
I recently got a patch put in https://github.com/BeeStation/BeeStation-Hornet/pull/3502 which should of fixed it but there might be a way to still cause this. I am investigating to confirm if its true or not.
