### ISSUE TITLE
Possible Bounty 1: Atmos Bot

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#2424]
Just a little roaming bot that attempts (somewhat foolishly) to replace the atmos with regular air in a region. If there's a hull breach... well, it's just going to stay there and blast air. 

Feature shopping list
1. A custom icon that sort of resembles a maxcap on wheels
2. On emag: Sprays miasma
3. Has options similar to other bots like stationary / roaming
3b. Option to heat / cool only instead of replacing air
4. Simple recipe: robot arm, air tank, prox sensor, analyzer

**Comment by PowerfulBacon** [comment]
Seems interesting

Edit: 
Been making a prototype real quick, would it be ok to have it go and place holobarriers near detected breaches, or should I have a MkII that costs a holobarrier on top of the simple materials that goes and also places holofans near breaches?

**Comment by jlsnow301** [comment]
I think the design should be "simple but suboptimal", the holobarrier capability is fine on the bot, so long as it's limited to ~1 holobarrier at a time

edit for clarity:
there needn't be a second version to do this

**Comment by PowerfulBacon** [comment]
Will finish tomorrow if no one else gets to it overnight

**Comment by jlsnow301** [comment]
Just ping me here (or discord but I'm never on) and I'll accept the claim asap

**Comment by TeomanTheGreat** [comment]
50 bucks holy shit
