### ISSUE TITLE
Possible Bounty 2: Better Secondary Objectives

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#2425]
Secondary objectives are largely trivial, barely work (but you don't notice because they're trivial), or are sometimes impossible.

Feature Shopping List: New secondary objectives that must be both ATTAINABLE and HELPFUL. There's a good bit of artistic freedom available here, I do not work all departments, I'm not versed enough to know what is/isn't a cool "secondary" objective. Each role needn't a guaranteed secondary each shift, and not all jobs need changes.

Some thoughts, with placeholder values (just keep it attainable):
- **station engineer:** have >300kW of power generating at shift end. i don't think the station integrity objective is working
- **roboticist:** the cyborg secondary objective is great but it needs to be tuned down, there's no way you're getting 7 active cyborgs, etc. keyword ATTAINABLE. ~3.
- **chemist:** make at least ~200 units of [BENEFICIAL CHEM] by shift end. i don't like the current breaking bad "have 15u of krokodil in your blood when you arrive at centcom"
- **chef:** the current secondary to bring [craftedfood] needs tuned down to be a bit more attainable, perhaps by simplifying the list a bit. or something better altogether? 
- **botany:** pod ~1 non-botanist in the shift. put [10 tomatoes/wheat/apples] in the kitchen smartfridge.
- **geneticist:** clone ~1 crew member during the shift (it's literally their department, who knew!)
- **scientist:** upgrade the [ORM/cloner/sec fab/cargo fab/cryosleeper/recycler]
- **miner:** have collected at least [NUMBER] of [RANDOM ORE] by shift end. note that this should be less for rarer materials
- **cargo:** I don't normally play cargo so this is up to you. Fulfill at least one cargo supply request by another department??
- **barber:** give ~3 haircuts to crew

**Comment by jlsnow301** [comment]
bountybot wya

**Comment by St0rmC4st3r** [comment]
@jlsnow301, uh, just for the future, don't rush with putting a bounty on bountysource. Quite a few people have various problems with it.

**Comment by jlsnow301** [comment]
Agreed and not doing this on cloning zombies lol
For what I would consider relatively non controversial aspects though - it's either risk it or hit page 10? #2254

**Comment by St0rmC4st3r** [comment]
Well, throwing money at bugs is a sure way to fix them, but it seems that I wasn't really clear in my previous comment. What I really meant was "Don't hurry to put your bounties on *bountysource*. Multiple people had problems dealing with *bountysource* as a service, such as long wait times for payouts and for some people (mostly me) complete inaccessibility to normal cashing out."

**Comment by jlsnow301** [comment]
Oooo I see. Yes, interpreted "problems with it" as in disagreed with the pr. I remember having issues months ago with bountysource when converting to the new interfaces 😐

**Comment by Archanial** [comment]
clown - be in jailcell at least 3 times.
I'll see what I can do

**Comment by jlsnow301** [comment]
> clown - be in jailcell at least 3 times.
> 
> I'll see what I can do

Even if you're joking here this is gold
Attainable and much more stylish than PDA slips

**Comment by badideaguy** [comment]
cargo: complete # bounties
Scientist: bring over # research nodes in data disk on shuttle(yes I know this is an antag objective, fun)

**Comment by utilbird** [comment]
Bountysource :pensive:
