### ISSUE TITLE
Possible Bounty 3: Cloning Rework

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#2426]
Cloning has been the focus of umpteen changes (and PRs still) because it's such a huge part of the game. I disagree with the overall notion that it should be made any bit more "difficult" by requiring more setup in any fashion. I prefer chaos.

Feature shopping list:
1. Synthflesh requirement for cloning reduced
2. All lower tiers have much higher chance to spawn in with random "errors": 
2b. Organs malfunctioning, limbs missing, increased % chance of negative DNA traits. Things that require actual medical staff to fix.
2c. A small chance that the resulting clone is a simple mob zombie. Zombie chances are significantly raised upon cloning SSD ("soul departed") players. Yes, the infectious type. What did you think would happen?

**Comment by yyzsong** [comment]
hmm yes let me put the 25 tc traitor item into something that can be gotten via cloning SSD people very funny

**Comment by jlsnow301** [comment]
setting up a whole synth factory in medbay just to roll for that ~5% chance. epic pranks

**Comment by zeskorion** [comment]
ix-nay on the zombies. especially not simplemobs.

**Comment by Chessus** [comment]
I like the idea of cloning only working on a body that has been dead for x amount of time. That way players will have to focus on other revival means.
