### ISSUE TITLE
Necropolis Seed Stealth 8 Threshold is broken

### ISSUE THREAD

**Issue by Jockeybane** [BeeStation/BeeStation-Hornet#2427]
## Round ID:
21126

## Reproduction:

Produce a Virus containing the symptom Necroseed that has a Stealth of 8+, meeting the threshold. Apply it to another player and kill them. According to the threshold description, the victim will be gibbed and an artifact should be created(This was normally a Tendril Chest). However, the player is gibbed, but no chest or other item is produced.

**Comment by zeskorion** [comment]
depends. I have several checks in necroseed stealth 8 currently to prevent cheesing. it wont work on slimes, golems, i think podpeople as well, and also doesnt work on monky- and other viable carbons.
