### ISSUE TITLE
Lack of copper on Charlie 

### ISSUE THREAD

**Issue by HeartwawyHorror** [BeeStation/BeeStation-Hornet#243]
## Round ID:
Every round.

## Reproduction:
Playing.

This issue is more of a balance issue than a bug. With the introduction of copper as a necessary component of boards, Charlie Station is crippled in its technology since there is no copper in the nearby asteroids.

**Comment by Toxici11i** [comment]
ill map this in

**Comment by MarkSuckerberg** [comment]
It should be solved with the PR I just submitted
