### ISSUE TITLE
Incursions does not treat the clown like other antags

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/BeeStation-Hornet#2436]
## Round ID:
977 - Downstream on NSV13 
_Hope you've not forgotten about us_

## Testmerges:
Incursions team antag game mode
#2168 

## Reproduction:
Clowns when they become traitor, cultist, revolutionary gets a loosened version of the clumsy gene. So they can fire guns, cuff, use stun batons. 
Incursions seems to not have done followed this standard, so an incursion clown can't clown on the crew like any other antag.

Just give yourself incursion antag status as round start clown to see this in effect. Compare it to other antagonist roles.

**Comment by francinum** [comment]
Clowns don't have rights.

**Comment by GoatMonarch** [comment]
Clowns do have rights.
