### ISSUE TITLE
Flying over lava makes your items in hand catch on fire

### ISSUE THREAD

**Issue by Moccha-Bee** [BeeStation/BeeStation-Hornet#2460]
## Round ID:
Any

## Testmerges:
Heretics

## Reproduction:
Get a wing from the elixir fly over lava with an item in hand and watch it burn

**Comment by Bestparty** [comment]
ok then keep your hands in the air next time, dont let them drop down and let the items dip in the lava

**Comment by Moccha-Bee** [comment]
> ok then keep your hands in the air next time, dont let them drop down and let the items dip in the lava

skinny dipping my hiero be like
