### ISSUE TITLE
Bounty: Emote Keybinds (20$)

### ISSUE THREAD

**Issue by Johnathon-Baxter** [BeeStation/BeeStation-Hornet#2469]
https://github.com/tgstation/tgstation/pull/51683 has a comment by user Timberpoes that showcases a new genetics UI. I want this to be ported to Beestation so you can just click once to change a half of a gene couple.

I also want the emote hotkeys from https://github.com/tgstation/tgstation/pull/47750.

If either of these tasks is too daunting from a technical side for the price, let me know in the comments. I may need to atomize these bounties so that it is 20$ each if the genetics one turns out to be too much.

**Comment by Djiq** [comment]
you should atomize these

**Comment by Johnathon-Baxter** [comment]
Ignore the stuff on the genetics console for now, I have no idea how to edit the actual original bounty posts' contents, only the title.

**Comment by TeomanTheGreat** [comment]
Epic

**Comment by zukonake** [comment]
Is this bounty "valid", or should it be paid into bountysource first? Asking whoever knows how this stuff works/whoever manages it.

**Comment by zukonake** [comment]
@Crossedfall ?

**Comment by Johnathon-Baxter** [comment]
I have zero clue how to make the bounty valid. I suppose just message me at Leo Errith #6783 if you want to do the bounty, we can work out details later.

**Comment by zukonake** [comment]
@Johnathon-Baxter I think you post the bounty here https://www.bountysource.com/issues/93014105-bounty-emote-keybinds-20?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github

**Comment by ike709** [comment]
Letting this go stale since it doesn't seem to be a proper bounty.

**Comment by utilbird** [comment]
Eh, not everyone (myself included) likes bountysource. Unless @zukonake wants it, I'd be happy to take a steam game for this xd

**Comment by TeomanTheGreat** [comment]
I was working on this at one point but changed my mind. Also wouldn't people spam flip during combat to help them dodge attacks because their sprite is moving (I think people do this on TG)?

**Comment by zukonake** [comment]
@TheFakeElon 

Feel free to take it, I'm out.

**Comment by utilbird** [comment]
Just want to make sure @Johnathon-Baxter is still here, it's been a while since this bounty was made

**Comment by MNarath1** [comment]
@Johnathon-Baxter is this bounty still up?
