### ISSUE TITLE
AI doomsday bug.

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#249]
Round ID: 5674

## Reproduction:

During that round, the AI was malf, and it triggered doomsday, at the exact moment when doomsday was triggered the AI was killed, which made the doomsday still countdown even when the AI was dead, basically making doomsday inevitable.

**Comment by Toxici11i** [comment]
I dont think this is possible to reproduce - as it requires server lag with a combination of heavy RNG to reproduce. ill add a check later to check if the AI is alive each time it procs the "Doomsday countdown".
