### ISSUE TITLE
The library ship ruin cannot be turned into a shuttle

### ISSUE THREAD

**Issue by Bastian0930** [BeeStation/BeeStation-Hornet#2525]

**Comment by Moccha-Bee** [comment]
is there any other space ruins like this one that can be turned into one?

**Comment by Bastian0930** [comment]
i'm unsure. you'd really wanna check them. honestly, all space ruins should not be considered part of the station

**Comment by TotallyNotChief** [comment]
its not that they're a "part of the station", it just says that for every already designated area; you cant simply turn one into a shuttle

**Comment by Bastian0930** [comment]
@PowerfulBacon I believe this is still not addressed, however I could be incorrect. Said to ping a maintainer, so I picked you. Also, problem is misspelled by the bot.

**Comment by TotallyNotChief** [comment]
@Bastian0930 bro multiple people have told you that you cant turn an existing area into a shuttle and its intended

**Comment by Bastian0930** [comment]
Alright, I see. I'll just close it.
