### ISSUE TITLE
Lexorin and dexalin recipe conflict

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#2529]
Issue reported from  Round ID: 21702 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1532

Recipe for lexorin is equal parts plasma, hydrogen, sulfonal and oxygen. Dexalin, on the other hand, is oxygen with plasma as catalyst. So, trying to make lexorin and adding oxygen last results in dexalin instead. It can be worked around by adding the plasma last, but I'm pretty sure the recipes shouldn't overlap like that regardless.

**Comment by eLeCtrOssSnake** [comment]
Whatever, I don't really care.
