### ISSUE TITLE
Few heretic bugs

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#2533]
If you make someone heretic (via traitor panel) they don't get their heart or book.
The realities don't spawn if you make someone heretic.
If you spawn realities yourself there is random chance that the heretic won't see them.

**Comment by TeomanTheGreat** [comment]
@EdgeLordExe

**Comment by Djiq** [comment]
dont spawn realities yourself, there is an automated system for doing that. to generate realities go to MC - > globals - > reality_smash_tracker - Generate( number )  otherwise they WILL be invisible

**Comment by Djiq** [comment]
there is an equip button after you heretic someone

**Comment by Djiq** [comment]
ive checked it and no, realities do spawn after you make someone a heretic

**Comment by Djiq** [comment]
close this issue, nothing seems to be bugged

**Comment by Archanial** [comment]
> there is an equip button after you heretic someone

Well they didn't. 
I couldn't find equip button but they should be equipped the moment I hereticize them.

**Comment by Chessus** [comment]
Did the never ending space tile get fixed?
