### ISSUE TITLE
Eating catus past a certain point won't stop the legion transformation

### ISSUE THREAD

**Issue by Moccha-Bee** [BeeStation/BeeStation-Hornet#2538]
## Round ID:
21787 mrp

## Testmerges:
Clock-cult

**Comment by zeskorion** [comment]
Curing takes time- it counts as a disease. If you fail to eat the cactus before it reaches stage 5, od the cactus doesnt metabolize fast enough, you fuckdd

**Comment by Moccha-Bee** [comment]
aight
