### ISSUE TITLE
Screen is freezing and only restarting the game will fix it.

### ISSUE THREAD

**Issue by Moccha-Bee** [BeeStation/BeeStation-Hornet#2549]
## Round ID:
21841

## Testmerges:
Clock cult and True Auto fire by KMC

## Reproduction:
just play the game, the screen has been freezing for me for a long time ,and today it froze in the middle of my battle with the hiero and i died.

**Comment by ike709** [comment]
Is this after playing multiple consecutive rounds? BYOND likes to crap out after a while without being restarted.

**Comment by Moccha-Bee** [comment]
> Is this after playing multiple consecutive rounds? BYOND likes to crap out after a while without being restarted.

i generally restart after round end due to the lag. So no.

**Comment by PowerfulBacon** [comment]
Not enough info, unable to reproduce
