### ISSUE TITLE
Heretic End Round Result Bug

### ISSUE THREAD

**Issue by ocan4214** [BeeStation/BeeStation-Hornet#2605]
## Reproduction:(Sadly i couldnt take screenshoots to prove it cuz i went to eat dinner)
1- Be Heretic
2-In my case my objective to eliminate someone changed 2 times (it might affect or not no idea and at the end of round in my notes section i only had 2 objectives. One was protect someone other was sacrifice 3 people )
3- also dump your codex and heart(i had no codex and heart, i just had heretic blade)
4- Die as Heretic
5- Get revived via cloning 
6- At the end round result your name will not be in antag list.

**Comment by TeomanTheGreat** [comment]
@EdgeLordExe
