### ISSUE TITLE
Autogrammar not reacting to all forms of punctuation

### ISSUE THREAD

**Issue by madruckus** [BeeStation/BeeStation-Hornet#2606]
## Round ID:
22102

## Testmerges:
#2336

## Reproduction:
Ending any message with "." ":" "?" or "!" cause the message to properly end like intended, ending a message with no punctuation ends in it automatically getting a ".". This is fine and dandy, and I quite prefer this to any other way of having autogrammar. But ending a message in a "," cause your message to get the auto-dot added to the end, such as "test," becoming "test,."

**Comment by PowerfulBacon** [comment]
I don't see the issue here, could you give an example as to what situations you would need to end a sentence in a comma?

**Comment by madruckus** [comment]
When I write messages, I often do it in chunks, such as “No,” then followed with the reason. That is an example of where getting “No,.” Is annoying.

**Comment by madruckus** [comment]
Apologies if my last message looked weird, had no idea replying to the email directly would do that. Edited it to fix it.
