### ISSUE TITLE
No sprite for lemonade pitcher

### ISSUE THREAD

**Issue by MarkSuckerberg** [BeeStation/BeeStation-Hornet#262]
## Reproduction: Make a pitcher of lemonade (10u lemon juice, 10u water, 5u ice, 5u sugar) at bar. No sprite when held in hand or placed on table/dropped. Note that the round is not the first round I noticed it, just one where I reproduced it to see if it still happened, which it did.

*Sorry if the issue quality is bad, just felt like pointing it out, I guess. Likely not important but I wanna help and this is all I've found so far. Included a sprite from /TG/ just because that must mean there is a sprite somewhere in the files*

![Lemonade](https://user-images.githubusercontent.com/29362068/61813770-2bd91b80-ae0c-11e9-9512-190d6ee7ddd9.png)

**Comment by ghost** [comment]
ill see if its just not set up right when i get home cause I have the files for drink dmis open already
