### ISSUE TITLE
Round Start Issue 

### ISSUE THREAD

**Issue by ocan4214** [BeeStation/BeeStation-Hornet#2652]
## Reproduction:

This was something confusing for me and i don't know how to reproduce this. I was internal affairs agent and my job was Debtor gimmick role. When i started to round after like 5-10 sec at maximum game said my target was dead and after 1 sec later at max it said "Your sensors tell you that Objective, one of the targets you were meant to have killed, pulled one over on you, and is still alive - do the job properly this time!"  and after this message my pinpointer show my location sometimes and othertimes it kept showing objective's location. Same thing happened again my target died and same message of that i have failed. So it was really confusing for me. I am going to post you screenshot of it.

![Ekran Alıntısı](https://user-images.githubusercontent.com/26821604/95264872-c6b6ed80-0838-11eb-92f5-82c198dd5af7.PNG)

**Comment by zeskorion** [comment]
The issue with the pinpointer is not an issue- IAA pinpointers arent very accurate, and only show the general area of the target. 


No isea what was going on with yolanda

**Comment by yyzsong** [comment]
>your target is suspected of vandalism
>fucking kill them for us please

now that's the real issue with IAA

**Comment by PowerfulBacon** [comment]
Target shows as being a black dot when you are within 15 tiles of them

**Comment by ocan4214** [comment]
Thing was it was either red or black there was no transition through blue. i wish i should have get the video record of it. But still it was confusing.

**Comment by PowerfulBacon** [comment]
The minimum range is so low on it that there is no blue zone

**Comment by zeskorion** [comment]
The pinpointer is also very slow to update
