### ISSUE TITLE
Custom shuttle engines bug

### ISSUE THREAD

**Issue by Dennok** [BeeStation/BeeStation-Hornet#2670]
BYOND Version: 513.1533
Server revision compiled on: 2020-10-10
Master commit: d6fe72804a08cee7e457602e695831e54f6e03b0

## Reproduction:

Build shuttle, add engines, fly, VV docking_port and see this
![image](https://user-images.githubusercontent.com/7734424/95650107-03f5d680-0aea-11eb-8d32-ceff1ae00615.png)

And engines don't removes self from this list on destroy
![image](https://user-images.githubusercontent.com/7734424/95650157-66e76d80-0aea-11eb-94f4-91f26ef706e2.png)

**Comment by ike709** [comment]
@PowerfulBacon

**Comment by Dennok** [comment]
#2689 fix this
