### ISSUE TITLE
Going down disposals has a chance to delete you, possible cause is the pipe breaking

### ISSUE THREAD

**Issue by Bungo555** [BeeStation/BeeStation-Hornet#2672]
Issue reported from  Round ID: 22426 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1533

So this has happened multiple times, when going down disposals, you can end up getting deleted from the game almost instantly for no real reason. you dont even make it to the conveyer, it just makes you go poof

**Comment by thelaughingbomb** [comment]
Related: https://github.com/BeeStation/BeeStation-Hornet/issues/2518

**Comment by FortSumter** [comment]
I've had this happen to me once. Someone a while back made a disposals pipe in a main hall and broke the end as I was in the pipe and got deleted.
