### ISSUE TITLE
SM layer issue

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#2694]
SM sliver appears under the actual SM.

**Comment by SomeAngryMiner** [comment]
this is because SM is on layer 4 now, wich is above object and mobs, to prevent stuff from being above the SM sprite, while should be behind it.

**Comment by Archanial** [comment]
I know, why not make sm shard on a layer above then, don't see why anything else would sit on top of SM.

**Comment by bloons3** [comment]
SM Sliver item appears under the SM crystal object?

**Comment by Archanial** [comment]
https://cdn.discordapp.com/attachments/463784644781932565/765279340283428894/unknown.png
https://cdn.discordapp.com/attachments/463784644781932565/765279370403119124/unknown.png

yes

**Comment by Archanial** [comment]
Super confusing to new people
