### ISSUE TITLE
You cant heal yourself with ointment and bruise packs through security protective apparel anymore.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#2736]
1) Get an armour vest from the locker. That one, which barkeeper, HoP and any security personnel start with. 
2) Try to use healing items from the white medical kit.
3) There will be a warning, that there is no exposed flesh to heal.
4) Try a limb now, vests dont cover limbs.
5) Get the same message about exposed flesh.
I am totally sure, that you could heal through that in the past.

**Comment by zeskorion** [comment]
Hm, i was under the impression thick_material cared about limb covering. Remind me ehen i  get home from work to fix thar shitcode

**Comment by Jake-Wheal** [comment]
@zeskorion are you back from work yet?
