### ISSUE TITLE
Build Your own Shuttle decided that half of it din't want to go to centocomm funny vid inside.

### ISSUE THREAD

**Issue by Moccha-Bee** [BeeStation/BeeStation-Hornet#2745]
## Round ID:
27780 i think

## Testmerges:
None

## Reproduction:
https://www.youtube.com/watch?v=iya1pmi0lP4&ab_channel=Nizteroth
I don't know how to reproduce the bug, it happened during shuttle take off from the station half of it decided to stay, there was a plasma fire before not sure if it was related.

**Comment by PowerfulBacon** [comment]
Seems like only part of the shuttle took off from the station
