### ISSUE TITLE
Borg transformation via maintpills doesn't give you silicon abilities

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#2750]
Can't interact with thing from a distance, some stuff doesn't work etc etc

**Comment by KubeRoot** [comment]
Tried to reproduce this on a test server by drinking some `/reagent/nanomachines`, assuming this is the culprit. However, after transformation I was able to use machines at a distance, select my module and use my tools.

Can't tell what might've fixed this, is there maybe another reagent that can turn you into a cyborg?

**Comment by Ivniinvi** [comment]
Nope, just nanomachines
