### ISSUE TITLE
Thanking the driver mutes you

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#2753]
If you thank the driver enough times (in clown car) you get automuted.

**Comment by Moccha-Bee** [comment]
Stop being so grateful

**Comment by ghost** [comment]
Intended, this is to prevent spamming i also was IC muted once because of nanites force saying stuff.

**Comment by Archanial** [comment]
How is this intended?
there literally exists a button with cooldown for situation like this

**Comment by Moccha-Bee** [comment]
> How is this intended?
> there literally exists a button with cooldown for situation like this

the mute must exist indepedently from the coodownl, it prolly checks not for intervals but by the volume of said phrase.

**Comment by utilbird** [comment]
The clown car's best prank
