### ISSUE TITLE
Apids can't jump no more

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/BeeStation-Hornet#2772]
## Round ID:
22876 
Also an active issue downstream. Tested on 2020 october 21.

## Testmerges:
May be related to the latest wing PR.

## Reproduction:
Join as an apid, any job. You won't spawn with the neck item, that gives apids the ability to do a jump.
It also makes them look really silly without wings.
Balancing the apids to **bee** equal to any other race with no upsides, but only negatives.

**Comment by ToasterBan** [comment]
yeah, its a nerf apids dont jump no more

**Comment by ghost** [comment]
Not a bug, this was removed.

**Comment by GoatMonarch** [comment]
> Not a bug, this was removed.

Got cha. The wiki page for apids isn't updated on the matter.
What makes apids unique besides needing half atmosphere pressure to breathe then?
