### ISSUE TITLE
Appearance transformation items remove wings after use

### ISSUE THREAD

**Issue by super12pl** [BeeStation/BeeStation-Hornet#2793]
Appearance transformation items (mulligan, stabilized green, envy's knife, dna injector etc.) remove wings from the user.

## Reproduction:
1. Use one of the items mentioned above while having wings
2. Get wings removed

**Comment by Chessus** [comment]
I'm trying to recreate this in a local server. What wings are you referring to? The cybernetic wings implants do not remove when using the mulligan, but with slime transformation does.
