### ISSUE TITLE
Zulu Station

### ISSUE THREAD

**Issue by LastCrusader105** [BeeStation/BeeStation-Hornet#2851]
I need feedback for the station, personally I think I will redo sec cause its just shit
but all the mappers and coders are busy so cant provide feedback so I must pass it over to you guys
please tear into me like we did to kilo station

a few things to note
**its a station for LRP least it was meant to be, same time I hope MRP get some use out of it
im not trying to reinvent the station and at same time not trying to make box extended
### it uses manual APCS
donuts SM heavily inspired Zulu SM but it adheres to beestations building standards (fireshutters and firedoors)**

![Zulustation](https://user-images.githubusercontent.com/56616002/97649003-1eb6cd80-1a4e-11eb-9351-69eaba2095b0.png)

**Comment by LastCrusader105** [comment]
should point out that atm its only bare bones till i get the layout sorted then i will go back and make it feel "alive" if you will

**Comment by yyzsong** [comment]
From the perspective of a non-mapper: this actually looks pretty good. Spawning engineers right next to the supermatter crystal is icky though, given that staring at the soup matter without mesons tends to cause hallucinations

**Comment by LastCrusader105** [comment]
@yyzsong cheers spawn points, apcs and vents are just anywhere atm till i get the general layout done, my main concern is i dont like sec, im done for the day but i did a quick idea, please ignore fact it doesnt actually connect etc but it should give the visual feel of my plan

![Zulu](https://user-images.githubusercontent.com/56616002/97650458-9f2afd80-1a51-11eb-9391-87bb77c0e7d9.png)

plus side is it both opens up space for atmos/engie to be free and looks nicer

**Comment by LastCrusader105** [comment]
I have reworked sec and personally I quite like it, hopefully will feel like its not box and its not meta 

![Zulustation](https://user-images.githubusercontent.com/56616002/97698149-fe176380-1a9f-11eb-889a-75af5a8916c8.png)

**Comment by LastCrusader105** [comment]
added Chapel and The God Pod
![Zulustation](https://user-images.githubusercontent.com/56616002/97768103-a23cf100-1b18-11eb-857b-64157fe1359f.png)

**Comment by LastCrusader105** [comment]
added science and extended centcoom recovery ship to take up to 6 pods and gave sec a little area to rodney king their inmates without the public getting involved

![ZuluStation](https://user-images.githubusercontent.com/56616002/97792508-fdcdb400-1bd6-11eb-96e4-d30e75655ffc.png)


![Recovery Ship](https://user-images.githubusercontent.com/56616002/97792510-0625ef00-1bd7-11eb-9099-e036a202f317.png)

**Comment by Sinestia** [comment]
I really like the look of it, keep it up

**Comment by francinum** [comment]
Why is the top of the central loop 4 tiles wide?
Security is really wide and is like 40% detached hallway, what's wrong with routing it through the briefing room?
Why is the RD nanite lab so big.

**Comment by LastCrusader105** [comment]
@francinum all good questions
Simple answer a wizard did it
No the sec hallway-will be made 3 wide with fire doors
I assume you mean to perma? And tbh your right no reason for it I suppose, Originally I did it cause I imagined a break out and didn’t want them to get into the secure parts but I see I added a side door so it’s pointless anyway, suppose I could remove the corridor and have it leading to the brieffing room
Thank you for the feedback

**Comment by LastCrusader105** [comment]
Oh sorry you meant the central loop, it’s 4 wide same as bottom so I can make it “alive” (lockers vending machines chairs etc) which will come last
Nanites are big because I was playing around with idea of making it have access to the public, plan to add a glass door so you can deal with them then get your nanites
Today’s update: had real life to deal with so not much, piping on rest of science done but given me errors which I will sort
Back to work tonight so progress will slow, no more departments in a day
Tomorrow I will be sleeping most day, I plan to sort the pipe error at least, Then progress will continue

**Comment by LastCrusader105** [comment]
todays update
yesterday went as planned the errors was from toxins mixing chamber
I have now moved onto evac cause I had this idea, sometimes evac gets crazy, so what if engie had a small area with air tanks filters and some metal to fix the worse of it

**get bored of waiting and want to read the adventures of the HOS Ella Aese: in Monkey Madness, or perhaps you'd prefer the epic 3 part drama: Karen Holmes and the Corona Virus? well the lounge is the place for you**


**Ever had a patient dying and evacs on its way? well now you can stabilise them and get them to evacs mini med outpost 
and we still got the sec checkpoint**

![ZuluStation](https://user-images.githubusercontent.com/56616002/98023230-87ab9600-1dfe-11eb-8d67-eaa734f1f6c5.png)

still needs more items to be truly "alive" but gives general idea

_**still to do**_
medical department
ai sat
ai upload
library
disposals
and then go room to room checking pipes cables etc and filling the rooms up to appear like a station
once the general layout is sorted I can "finish" maint

**Comment by LastCrusader105** [comment]
a second update aint you guys lucky
@francinum i took you advice and I quite like it (the old corridoe will probably be maint when I do my maint "update")
![ZuluStation](https://user-images.githubusercontent.com/56616002/98039749-188e6b80-1e17-11eb-9cf1-078616439e63.png)

I have started medical, but I dont think I like it so may start again, I wanted the entrance to be for LRP when no doctors are on, but I wanted the rest of it to be a journey depending on how messed up you are with CMO office in middle overseeing everything, it maybe time to seperate genetics from cloning (I never see them actually clone anyone)

![ZuluStationmed](https://user-images.githubusercontent.com/56616002/98040065-994d6780-1e17-11eb-99c1-c7e8d24ef68d.png)
feel free to comment we are nearing the home stretch

**Comment by aguyiguess** [comment]
very based whats the intended population

**Comment by francinum** [comment]
Your south hallway is uh, way too long, honestly.
Robotics is a little oversized and the wall between it and the south hall is quite empty and flat.
On the topic of security:

![](https://file.house/4Fdp.png)

**Comment by LastCrusader105** [comment]
@aguyiguess it was originally meant to be box size but I fear my ambition has carried me away so I don’t know

@francinum I like your sec ideas, south hallway will have medical and evac so should be right size
As for robotics, it is a chunky boi but should allow maybe 3 robotics

Thank you for the feedback

**Comment by LastCrusader105** [comment]
Hello all todays update
@francinum see further down for the south hallway
![Zulumsec](https://user-images.githubusercontent.com/56616002/98166479-61115c00-1edf-11eb-8b72-fe7487207ef6.png)

medbay is nearly finished, just medbay storage and viro to be added, (placed deltas so you can get "feel" of it)
![Zulumed](https://user-images.githubusercontent.com/56616002/98165690-3bd01e00-1ede-11eb-9ed0-f8a86470abbf.png)

as you can see with have a few exciting things and a few we have seen before:
![Zulumorgue](https://user-images.githubusercontent.com/56616002/98165727-47bbe000-1ede-11eb-8d40-423b80526e4e.png)
sort of seen on box but should you wish to you can harvest organs, and for our **Plasmemes** we finally have a surgery for us (one of the autopsy rooms has a shower not pictured)

hopwfully the chem feels like its own thing, tried not to copy and paste  
![ZulumedChem](https://user-images.githubusercontent.com/56616002/98165993-b26d1b80-1ede-11eb-8f53-6b3aecc272f9.png)

yes you do see a shuttle dock
![Zulumedshuttle](https://user-images.githubusercontent.com/56616002/98166134-dd576f80-1ede-11eb-9813-91ba299461ce.png)
in the future hopefully we will have need of it

![ZuluStation](https://user-images.githubusercontent.com/56616002/98165331-9b79f980-1edd-11eb-9e01-1eaea76e75b9.png)

ignore the floating departments, they are so i can refrence things i liked about X stations X and one is my first attempt of a chem

_to do:_
finish medbay (pipes cables vents pumps, add viro, add storage
add AI sat+upload
library
disposals
and then quality check and make station feel alive
im excited to be nearing the end as i have a based new idea for a map, its really a special idea i cant wait to get started on it

**Comment by LastCrusader105** [comment]
@TeomanTheGreat looky looky gib feedback cheers

**Comment by TeomanTheGreat** [comment]
Am busy

**Comment by TeomanTheGreat** [comment]
I feel like it needs a second solar panel area and maybe some more maint

**Comment by LastCrusader105** [comment]
@TeomanTheGreat
I plan to add one normal one and one double one, the plan for the double one, is when the Sm explodes on LRP as per usual it can be used to power the station without to much hassle

**Comment by LastCrusader105** [comment]
Todays update, medbay is barebones finished (powered and piped), I kept delta viro cause it was my favorite viro and the one I first learned on
![Zulumed](https://user-images.githubusercontent.com/56616002/98295251-2c69d700-1fa9-11eb-9da1-60cc53ebbe1b.png)
i also added a little plasmeme break room (in space to stop plasma floods and we are pretty much space proof)
![Zuluplasmeme](https://user-images.githubusercontent.com/56616002/98295428-7bb00780-1fa9-11eb-81e3-abc3068c3262.png)
we can now smoke safely in our break room

heres map so far
![Zulu](https://user-images.githubusercontent.com/56616002/98295492-92565e80-1fa9-11eb-85e3-38e0d3945e21.png)

**Comment by TeomanTheGreat** [comment]
Move the solar panel that's near the sm away so it doesn't get destroyed by the inevitable sm delam.

**Comment by LastCrusader105** [comment]
You think it will reach do you?
To the left will be AI sat

**Comment by LastCrusader105** [comment]
good news today is my last day at work so we will actually have bigger updates than one room

today was AI day, i hate being AI so I have no idea what to do with it so I consulted some AI mains and apparently kilo is the best AI so i took that and made the layers 1 and 3 removed rust and made a uploader too

![ZuluAI](https://user-images.githubusercontent.com/56616002/98411730-81235580-206e-11eb-933d-748d4b700ceb.png)

my idea was with fastmos they can now use space as a weapon, stun them open the window and keep em stunned
![ZuluAI](https://user-images.githubusercontent.com/56616002/98411869-bfb91000-206e-11eb-982e-7f5c0b814d81.png)


the ai will sit roughly hereish
![Zulu](https://user-images.githubusercontent.com/56616002/98411794-9f895100-206e-11eb-90d7-79178bbe9911.png)

**still to do:**
tcomms
disposals
library
make station "feel alive"
once thats done or nearly done finalise AI position

**bugs to fix:**
I plan to redo all configs etc
figure out how to fix air alarm in plasmeme smoko

why does the smoko room matter so much?
because plasmemes never get anything so fuck you, we are having our own place, and our own pet

**Comment by LastCrusader105** [comment]
### **todays update**

not much visible but
swapped ai upload for tcoms, upload is now on ai sat
![Zulumed](https://user-images.githubusercontent.com/56616002/98454586-fde12d00-215d-11eb-9776-4bb141c29c9d.png)

**today was more about swishing bugs-
sat apc is sorted
plasmeme smoko is sorted now acts like it should
z level issue is sorted**

here is the ai sat, (please ignore the LONG corridor connecting it, was just while I test stuff)
![ZuluAI](https://user-images.githubusercontent.com/56616002/98454615-6e884980-215e-11eb-890c-2229c5983728.png)

only Library left now
then its onto making station alive and seeing what room i got for maints checking every room for errors and finally locking ai place in
heres the station now
![Zulu](https://user-images.githubusercontent.com/56616002/98454622-8d86db80-215e-11eb-9a6d-9bef17ccaca2.png)

**Comment by francinum** [comment]
You seem to have misunderstood the real issue with the bottom hallway.

You have a lot of really long sections of flat wall with nothing on them.

**Comment by LastCrusader105** [comment]
@francinum when you say south hallway
Do you mean what leads to evac/medical
Or you on about sec hallway?
I do be confused now

**Comment by francinum** [comment]
South Primary

**Comment by LastCrusader105** [comment]
![image](https://user-images.githubusercontent.com/56616002/98483846-50c0f000-2203-11eb-8589-94d709a09e0f.png)

this is south primary now
compared to deltas south primary
![image](https://user-images.githubusercontent.com/56616002/98483879-806ff800-2203-11eb-9579-b1ebe773d931.png)

**Comment by LastCrusader105** [comment]
todays update is.....mainly maint
I have added a library
![Zululibraray](https://user-images.githubusercontent.com/56616002/98490285-f6d32100-2228-11eb-96cf-85e87597faf5.png)

I moved tech storage and replaced with both teleporter and eva access
![Zulueva](https://user-images.githubusercontent.com/56616002/98490391-46b1e800-2229-11eb-86de-bab5d0be675d.png)

finally I added gateway, by arrivals cause I had no room and lore wise I feel it would fit centcoom sends a team to station, they want to be away on their mission asap
![Zulueva](https://user-images.githubusercontent.com/56616002/98490459-7b25a400-2229-11eb-836f-6bec0e9f3a7e.png)

damn bro that's thicc, that's some more THICC ass maint, perhaps too thicc, im trying to sneak up on sec but the clap of maints ass cheeks keeps alerting them
![image](https://user-images.githubusercontent.com/56616002/98490505-998b9f80-2229-11eb-81ea-ba650fd4c8db.png)

and i got started on making station "feel alive"
![image](https://user-images.githubusercontent.com/56616002/98490553-b922c800-2229-11eb-996b-81d4a871fd43.png)


finally here is zulu as is atm
![Zulu](https://user-images.githubusercontent.com/56616002/98490580-ccce2e80-2229-11eb-972b-a58e5deb4f14.png)

**Comment by LastCrusader105** [comment]
todays update, disposals, you can now send bombs, letters calling them gay or whatever to 30 different locations (my personal favorite is sending irradiated post)
![6CF555B2-132A-4BCE-AF00-4A575695C677](https://user-images.githubusercontent.com/56616002/98608639-8fc67280-22e3-11eb-826a-d62db30ac02a.jpeg)


here is zulu as it currently stands as you can see the bar gained a new rage cage, HOP office and bridge was refurbished (bridge still to finish)
engineering got a new currently unused shuttle bay (i will put the wooden barricades in way so it looks under construction)
im sure theres more
![Zulu](https://user-images.githubusercontent.com/56616002/98608107-6e18bb80-22e2-11eb-810f-5e9fe2020059.png)

### **still to do**
patrol navigators for bots
mule bot delivery things
make station feel alive
thats it

**Comment by francinum** [comment]
Add windows to the break room in cargo, add a window to the west side of robotics, they're both uninterrupted stretches of blank hallway when seen from the hallway.

**Comment by LastCrusader105** [comment]
@francinum you was right did look a bit bland, but your in luck as part of my "alive" update it should feel more alive
![Zulu](https://user-images.githubusercontent.com/56616002/98746412-59edc080-23ad-11eb-8e49-892fc2ba436e.png)
ive finished both bot patrols and mule bots along with a few hidden extras 
![image](https://user-images.githubusercontent.com/56616002/98746998-881fd000-23ae-11eb-99fa-e5504924eb40.png)


### **still to do**
bug hunting
and finishing making it feel alive

**Comment by francinum** [comment]
![](https://file.house/hQZ7.png)

![](https://file.house/_Z9H.png)

**Comment by LastCrusader105** [comment]
@francinum thank you, you got the vision
I will implement all of those ideas

**Comment by LastCrusader105** [comment]
a quick update francinums ideas have been added
### **solar update**
I moved all the existing solars and added some more
for LRP when the sm gone boom and noone can be bothered to do solars, all it takes is one experienced player to do them, dont even need a hardsuit so its a chunky solar (please note the doors will be available to everyone I forgot to do it in this image)
![Zulusolar](https://user-images.githubusercontent.com/56616002/98850045-14340500-244c-11eb-879a-6dc8a54bd7dd.png)

next up is a build your own solar with lil side enginerring station should sm blow up, and your the only surviving engie left? you can continue your legacy
![Zulusolar](https://user-images.githubusercontent.com/56616002/98850298-7856c900-244c-11eb-887c-67cdfdbf7a57.png)

the other 3 are standard solars not interesting, one by science and north by arrivals, engie one has moved further right

fixed some issues pointed out by yyzsong
I have moved the test site, it was too close and I am trying to give science maint a feel of it was once a glorious department first one to always get funding cut is science, hopefully I can pull it off
![Zulu](https://user-images.githubusercontent.com/56616002/98850838-45f99b80-244d-11eb-9373-f254acb66a29.png)

**Comment by LastCrusader105** [comment]
fixed the floating bit by LRP solar

**Comment by LastCrusader105** [comment]
Just to point out before I get comments saying X is empty
I’d say half station is done (the arrival half to the bridge vertically)
Medbay and sec, science etc side till to do
Spawn points will be last

**Comment by LastCrusader105** [comment]
### **todays update**
 still making station "feel alive"
all lights are added
need to add more vents etc etc
just door access left then I think its done
noone checks here so no doubt when I do a pull request more people will see it
so thank you to all those who have commented
redid sec gave him a bedroom
![zulusec](https://user-images.githubusercontent.com/56616002/99016479-1e8af780-254f-11eb-914d-42421cfb44c3.png)
added a hide out in space
![zuluhideout](https://user-images.githubusercontent.com/56616002/99016514-2d71aa00-254f-11eb-8a46-28130f94e175.png)
oh and added a service shuttle
![zuluhideout](https://user-images.githubusercontent.com/56616002/99016996-8c372380-254f-11eb-9c7f-0929cdb56ee5.png)
its not a actual shuttle but its there to "future proof" it, if a feature like science away missions never gets added its just flavour for station
heres zulustation as it stands
![zulu](https://user-images.githubusercontent.com/56616002/99017393-b7217780-254f-11eb-9d2c-aae234b2f743.png)

**please do comment and issues/concerns you have**
