### ISSUE TITLE
Golem antag status 

### ISSUE THREAD

**Issue by blackwolf602** [BeeStation/BeeStation-Hornet#2852]
Issue reported from  Round ID: 23217 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1536

I was a cloth golem traitor and I transferred my soul into a runic golem I created and lost my notes and antag status

**Comment by PowerfulBacon** [comment]
Transferred soul how?

**Comment by blackwolf602** [comment]
> Transferred soul how?

I was once a antag as a cloth golem and went through the process of becoming a runic golem only to show my antag status was gone as well with my in game character. i transferred my soul through the creating a shell and clicking on the button to transfer my soul to it

**Comment by MNarath1** [comment]
> > Transferred soul how?
> 
> 
> 
> I was once a antag as a cloth golem and went through the process of becoming a runic golem only to show my antag status was gone as well with my in game character. i transferred my soul through the creating a shell and clicking on the button to transfer my soul to it 

Didn't even knew you could do that interresting well most likely this is a feature that never got updated and with time broke.
