### ISSUE TITLE
Maint room spawner bug.

### ISSUE THREAD

**Issue by Blueturbo47** [BeeStation/BeeStation-Hornet#2908]
https://www.twitch.tv/durrhurrdurr/clip/RespectfulOriginalToothAliens?filter=clips&range=30d&sort=tim

## Reproduction:

No idea

**Comment by LastCrusader105** [comment]
that would be when a wall for example is in way and it cant spawn properly so it leaves the object

**Comment by francinum** [comment]
This issue is caused by a strange null in the `possibletemplates` list.

The relevant runtime from the round:
```
[2020-11-11 00:20:23.085] runtime error: Cannot read null.stock
 - proc name: LateInitialize (/obj/effect/spawner/room/LateInitialize)
 -   source file: roomspawner.dm,32
 -   usr: null
 -   src: 3x5 room spawner (/obj/effect/spawner/room/threexfive)
 -   src.loc: the plating (204,69,2) (/turf/open/floor/plating)
 -   call stack:
 - 3x5 room spawner (/obj/effect/spawner/room/threexfive): LateInitialize()
 - Atoms (/datum/controller/subsystem/atoms): InitializeAtoms(null)
 - Atoms (/datum/controller/subsystem/atoms): Initialize(11913)
 - Master (/datum/controller/master): Initialize(10, 0, 1)
 - 
```

https://github.com/BeeStation/BeeStation-Hornet/blob/d2b2d26bfd68c57850ddad15cfcbe7bb494742b6/code/game/objects/effects/spawners/roomspawner.dm#L20-L40
