### ISSUE TITLE
Emag returning "Access Denied" when using on locker

### ISSUE THREAD

**Issue by sosowskiFS** [BeeStation/BeeStation-Hornet#294]
## Round ID:
5881

## Reproduction:
Use any emag on a locker you don't have access to. It doesn't break the lock but instead just returns "access denied" like you're trying to open it normally. Tested on CMO, Security, and personal lockers with all the same result.

**Comment by SomeAngryMiner** [comment]
Bruh, use harm intent to hack, the cryptographic sequencer somehow counts as an ID, thats why you get that message.

**Comment by sosowskiFS** [comment]
Got me there, but help intent with it on airlocks you don't have access to works fine, so I don't see why lockers shouldn't work the same way.

**Comment by SomeAngryMiner** [comment]
thats because ID lockers ask for ID swipe access, wich you do so by using an id on them for unlock, while on airlocks it just sees if the item/mob has the required access, so you kinda just slap the airlock with id, causing emag, like using it on lockers on harm intent.

**Comment by Toxici11i** [comment]
instructions unclear, dick stuck in blender situation. close this
