### ISSUE TITLE
You can pick up intercoms with a trash bag

### ISSUE THREAD

**Issue by Bokkiewokkie** [BeeStation/BeeStation-Hornet#2947]
When you click on an intercom while holding a (bluespace) trash bag you can pick up intercoms. This is most likely due to intercoms being objs instead of machines like other wall mounts.

## Reproduction:

1. Grab trash bag.
2. click on intercom with trash bag in hand.
3. you've picked up the intercom and can now put it in disposals or place it down anywhere using the bag.

Image for context:
![image](https://user-images.githubusercontent.com/43698041/99245203-7f425a80-2803-11eb-89d4-6d95eaf110be.png)
Moth picks up five intercoms and puts them in the AI chamber.

**Comment by St0rmC4st3r** [comment]
I know what I will be doing today.

**Comment by St0rmC4st3r** [comment]
![image](https://user-images.githubusercontent.com/34888552/99250893-1d8aec00-2815-11eb-9d36-c62a4f7d840c.png)
Bug confirmed
