### ISSUE TITLE
Limbs Regrown with Wand of Healing are not Affected by Paraplegic Trait

### ISSUE THREAD

**Issue by Chickenfarmer48** [BeeStation/BeeStation-Hornet#2968]
## Round ID:
1426 (NSV13)
(Told to report this here by an admin rather than on NSV13)

## Testmerges:
Missions 2

## Reproduction:
My character, a paraplegic, got shot by a HE RPG rocket that blew off one of my legs. When regrown with a wand of healing, it wasn't disabled, but the one not blown off still was. This eventually fixed itself a few minutes later when I healed myself with the wand, causing the non-disabled leg to become disabled.

How to reproduce: Pick paraplegic, lose leg(s), be healed once by a wand of healing, missing leg(s) that are regrown now work until healed again.

**Comment by Unidentified-Biohazard** [comment]
it would be better if wand of healing just fixed paraplegic rather than just regrowing the broke legs.

**Comment by eeSPee** [comment]
I think I know what happens.

Should have a update_mobility check after limbs are regrown?
