### ISSUE TITLE
Nerf the electric touch geneticist gene.

### ISSUE THREAD

**Issue by DemonOfHatred** [BeeStation/BeeStation-Hornet#2996]
This electric touch is absolute nuts, it literally destroyed the entirety of our cult because theres no counter to it for cultists whats so ever. it goes through walls, it causes permanent stun lock for like 15 seconds and has no counter play.

**Comment by Blueturbo47** [comment]
The counter is insulated gloves or to stun the genetics with an easy stun spell, or just convert the genetics and not allow their spells to be used against the cult.
