### ISSUE TITLE
Blank chat problem

### ISSUE THREAD

**Issue by defilter** [BeeStation/BeeStation-Hornet#300]
Issue reported from  Round ID: 5931 (BeeStation - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 512.1475

blank chat it's been like this for over a week probably and switching versions and reinstalling didn't help, this happened after i quit because the server crashed and the next day it was like that
didnt find anything like this on the internet so i'll ask here because
also its only on bee, bad deathclaw paradise and the other servers' chats are normal

![image](https://user-images.githubusercontent.com/53544906/62257470-db624f00-b405-11e9-8de2-f8cd430aca7a.png)

**Comment by ike709** [comment]
Trying clearing your cache.

1. Open BYOND.
2. Click the gear in the top right.
3. Click Preferences.
4. Click Games.
5. Click Clear Cache.

**Comment by defilter** [comment]
Doesn't work

**Comment by defilter** [comment]
> Trying clearing your cache.
> 
> 1. Open BYOND.
> 2. Click the gear in the top right.
> 3. Click Preferences.
> 4. Click Games.
> 5. Click Clear Cache.

yeah, i was told that, didn't work after multiple tries
