### ISSUE TITLE
Alt-Click no longer opens the inventory of a labcoat

### ISSUE THREAD

**Issue by MisterMecky** [BeeStation/BeeStation-Hornet#3016]
## Round ID:

N/A (Downstream)
## Testmerges:

N/A

## Reproduction:

- Alt-click on labcoat

Alt-Click can be used on items to open up their inventory. This is no longer possible with lab-coats and  click dragging onto yourself is honestly a pain

Probably related to https://github.com/BeeStation/BeeStation-Hornet/pull/2976

**Comment by Crossedfall** [comment]
Probably this: https://github.com/BeeStation/BeeStation-Hornet/commit/f4cb9279f80446fb76cda9988dac763e8f3d6106#diff-e10ed3fbd73364d0e6d3f063b2a73ca0f738d113c078bc18ed64084e3ff4ad5eL97

**Comment by PowerfulBacon** [comment]
Also certain things can no longer be rotated
