### ISSUE TITLE
Cook has aggressive grabs anywhere on the station

### ISSUE THREAD

**Issue by VictorVow** [BeeStation/BeeStation-Hornet#302]
## Reproduction:
In the engineering hallway on Box Station I was a cultist fighting the chef when they banana pie'd me in the face, which stunned me. But they soon after they grabbed me and it started off as violent grab and I was instantly chucked against the wall for another stun. To my knowledge they should have no melee enhancements outside of their kitchen.

**Comment by Toxici11i** [comment]
This is a known bug. I will look for the code that does the CQC grab and attempt to hotfix it.
