### ISSUE TITLE
HOS can be a traitor on dynamic

### ISSUE THREAD

**Issue by Snowy1237** [BeeStation/BeeStation-Hornet#3025]
## Round ID:
24442

## Testmerges:
None

## Reproduction:
1. Join a server with the game mode "dynamic".
2. spawn as HOS.
3. Roll traitor.
**What was expected to happen**:
 You will not be able to roll traitor because the role comes with a mindshield and can not be a traitor.
**What happened**:
You rolled traitor even when you are the HOS.

This is my first issue and I did not find any issues about this topic. if I did something bad please tell me.

**Comment by TeomanTheGreat** [comment]
Can confirm it did happen. @PowerfulBacon this is a very important bug. Can you fix it?

**Comment by ItsTisme** [comment]
I checked the code but HoS is protected, did it happend round start, midround or as a late join?

**Comment by park66665** [comment]
I wrote #3128 but I still am not 100% sure if the bug is fixed or not. We
need to see if this still happens or not.

**Comment by Sinestia** [comment]
> 
> I wrote #3128 but I still am not 100% sure if the bug is fixed or not. We need to see if this still happens or not.

Got it on the 23rd, after that PR, captain with die a glorious death and a traitor detective.

**Comment by park66665** [comment]
I am currently doing some serious code-diving, and would appreciate more
data on how it happened, like, was it roundstart, latejoin or midround?

**Comment by park66665** [comment]
Meh, I am too tired and you didn't respond in time, so maybe tomorrow or Bacon? Who knows?

**Comment by Sinestia** [comment]
It happened roundstart, there was only one midround (an infiltrator, no issue there.)

**Comment by park66665** [comment]
~~Relating to #3268, was the roundstart ruleset forced?~~

Nevermind, found the issue. The fix is on the way.

**Comment by badideaguy** [comment]
hos gets done with our nonsense and joins the syndicate for the LAW
Fun

**Comment by Vexylius** [comment]
Isn't this fixed by https://github.com/BeeStation/BeeStation-Hornet/pull/3797 @Crossedfall?

**Comment by Crossedfall** [comment]
This should be resolved yes.
