### ISSUE TITLE
Ghosts get clickable website names with people named after a valid link

### ISSUE THREAD

**Issue by ondrej008** [BeeStation/BeeStation-Hornet#303]
## Round ID:

Round ID: 5943
BYOND Version: 512.1472
Server revision compiled on: 
Master commit: c0b29e5d54f73eadc4c40c62dc34915d22620781
Server tools version: /tg/station 13 Server v3.2.6.2

## Testmerges:

none lmao

## Reproduction:

![Snímek obrazovky (1028)](https://user-images.githubusercontent.com/8739855/62292724-53149600-b467-11e9-9a20-53398f219b63.png)

Clicking the link does indeed lead me to the hell that is ifunny.co

**Comment by ondrej008** [comment]
@qwertyquerty why you close this?

**Comment by qwertyquerty** [comment]
not an issue
