### ISSUE TITLE
Growth Serum - Making you small

### ISSUE THREAD

**Issue by Demi-Wahoo** [BeeStation/BeeStation-Hornet#3059]
## Reproduction:
1. Drink at least 50u of Growth Serum.
2. Wait till you become giant.
3. Put on clown shoes and walk in any direction.
4. Take off clown shoes.
5. Wait till you become small.

## Results:
You are now small. It is cute, but it is a bad thing since you are harder to notice and this can be abused by certain people.

**Comment by Demi-Wahoo** [comment]
I wish that it won't get removed because it is cute as heck.

**Comment by nikk735** [comment]
delete this if you don't want it removed lol if no one knows about it wont be abused

**Comment by Demi-Wahoo** [comment]
> delete this if you don't want it removed lol if no one knows about it wont be abused

i am conflicted about this bug. On one side it is a cool thing, on other side it is a thing that can break the game. Bugs like this should be reported, because they might be abused. I will play with it as long as it is in game. Maybe they could make a limiter, so it doesn't turn into something bad. Like size cannot be under certain amount. A amount that could bad (invisibility).

**Comment by francinum** [comment]
This is an innate issue with matrix math related to transform, we can't limit it within sane bounds, only control what affects it.
