### ISSUE TITLE
Rev can toggle passability for emitter blasts for some objects. Can be used to delam SM.

### ISSUE THREAD

**Issue by Ravellon** [BeeStation/BeeStation-Hornet#3069]
## Reproduction:

1. Become revenant.
2. Sit on the SM crystal's tile that is being hit by emitter blasts or over glass/grille that is being passed by emitter blasts.
3. Behold as the blasts start passing the SM or start hitting the glass/grille.

The issue with that is potential to delam the SM as a revenant by breaking the glass.

**Comment by francinum** [comment]
Likely needs a similar solution to #2915

**Comment by Ravellon** [comment]
Additionally, it seems to have the same effect on laser shots. Haven't tested bullets or other projectiles though.

**Comment by francinum** [comment]
This behavior likely has to do with the fact that we don't actually have any way for a projectile to completely ignore an atom.
