### ISSUE TITLE
Teratomas die in distro

### ISSUE THREAD

**Issue by Unidentified-Biohazard** [BeeStation/BeeStation-Hornet#3072]
## Reproduction:

be Teratoma, enter a vent distro vent, start taking pressure damage.

**Comment by zeskorion** [comment]
This means they upped the pipe pressure. Not a bug.

**Comment by ghost** [comment]
Not a bug, someone in Atmos was smart and increased the pipe pressure.

**Comment by PowerfulBacon** [comment]
Intentional
