### ISSUE TITLE
Breath mask still gets burnt off when in a (fireproof) Elite Hardsuit

### ISSUE THREAD

**Issue by ArcaneSage1** [BeeStation/BeeStation-Hornet#308]
## Reproduction:
>be elite hardsuit nuke op
>mask burns in off when chilling in a plasmafire

I think the related fix should have been [here](https://github.com/tgstation/tgstation/issues/41618), not sure why it isn't working on Bee though.

Edit: Looking at the issue more closely it says this is normal when in Combat mode. I can't recall if I was in EVA or Combat mode at the time.

**Comment by Toxici11i** [comment]
turn to eva mode or it doesnt offer full protection from fire
