### ISSUE TITLE
ghost glitch

### ISSUE THREAD

**Issue by cursedkiller** [BeeStation/BeeStation-Hornet#3092]
Issue reported from  Round ID: 24752 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

i died and the ghost buttons dont show up this happend for alot of rounds i asked other people and they said its fine for them i tried restarting but still nothin

Reporting client version: 513.1536

**Comment by IllotAFV** [comment]
Preferences->toggle GhostHUD
