### ISSUE TITLE
Hud dissapearing

### ISSUE THREAD

**Issue by Tamumus** [BeeStation/BeeStation-Hornet#310]
## Reproduction:

I was playing sec officer, warden grabbed me to bring to labor shuttle, on the way all my hud dissapeared except for left and rigth hand at the base of screen, center.
I was able to buckle on a chair but the option to unbuckle top rigth corner did not appear.

admin cloned me to resolve the issue, but at the end of the round i got cloned randomly again without him intervening.

**Comment by ike709** [comment]
I have no idea what caused this bug, but for future reference you can unbuckle by clicking on the chair.

**Comment by qwertyquerty** [comment]
You probably accidentally tapped F12 which toggles minimal HUD mode

**Comment by LordZanos** [comment]
you get cloned again seemed to be a bug with the admin command

i jumped into your body to see what was up and later humanized my own ghost, and it targeted you for some reason
