### ISSUE TITLE
Contractor Tablet Not allowing re-entry

### ISSUE THREAD

**Issue by YuriVitch5** [BeeStation/BeeStation-Hornet#3147]
## Reproduction:
The issue that occured was that after a target went into cryo, 2 similar contracts popped up, It would not let me accept any of the contracts so I shut down and re-opened the Contractor table, but it did not allow me to "Register user" even though I already did this.

**Comment by Archanial** [comment]
![obraz](https://user-images.githubusercontent.com/37456678/102030386-e88d9d00-3db2-11eb-8e85-7d0680996dc8.png)
proc name: ui data (/datum/computer_file/program/contract_uplink/ui_data)
src: /datum/computer_file/program/c... (/datum/computer_file/program/contract_uplink)
call stack:
/datum/computer_file/program/c... (/datum/computer_file/program/contract_uplink): ui data(John Michael (/mob/living/carbon/human))
/datum/tgui (/datum/tgui): get payload(null, 1, null)
/datum/tgui (/datum/tgui): send update(null, null)
tgui (/datum/controller/subsystem/tgui): try update ui(John Michael (/mob/living/carbon/human), /datum/computer_file/program/c... (/datum/computer_file/program/contract_uplink), /datum/tgui (/datum/tgui))
/datum/computer_file/program/c... (/datum/computer_file/program/contract_uplink): ui interact(John Michael (/mob/living/carbon/human), /datum/tgui (/datum/tgui))
/datum/tgui (/datum/tgui): process(0)
tgui (/datum/controller/subsystem/tgui): fire(1)
tgui (/datum/controller/subsystem/tgui): ignite(1)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)

**Comment by Archanial** [comment]
Happened again
```
proc name: ui data (/datum/computer_file/program/contract_uplink/ui_data)
src: /datum/computer_file/program/c... (/datum/computer_file/program/contract_uplink)
call stack:
/datum/computer_file/program/c... (/datum/computer_file/program/contract_uplink): ui data(Beta (/mob/living/carbon/human))
/datum/tgui (/datum/tgui): get payload(null, 1, null)
/datum/tgui (/datum/tgui): send update(null, null)
tgui (/datum/controller/subsystem/tgui): try update ui(Beta (/mob/living/carbon/human), /datum/computer_file/program/c... (/datum/computer_file/program/contract_uplink), /datum/tgui (/datum/tgui))
/datum/computer_file/program/c... (/datum/computer_file/program/contract_uplink): ui interact(Beta (/mob/living/carbon/human), /datum/tgui (/datum/tgui))
/datum/tgui (/datum/tgui): process(0)
tgui (/datum/controller/subsystem/tgui): fire(0)
tgui (/datum/controller/subsystem/tgui): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

**Comment by Cenrus** [comment]
Confirmed to happen when a contract target enters cryo because handle_objectives doesn't know how to handle contract objective datums
