### ISSUE TITLE
Transformation sting on abductor scientist breaks his ablity to use observation console

### ISSUE THREAD

**Issue by ItsTisme** [BeeStation/BeeStation-Hornet#3161]
## Reproduction:

1: be scientist
2: get transformation stung
3: become golem or what ever
4: teleport back and you cant use the console

As funny as it was that I got transormed into a banana golem seems a little bit too hard of a counter to near instnatly wreck a abductor like that.

**Comment by Sarchutar** [comment]
I can't think of a better solution than to give them the `NOTRANSSTING` trait or to outright make them able to interact with the console regardless of their species (which would make solo abductors a bit OP). If someone has a better idea for this or if one of those ideas is fine i can make a pr for it.
