### ISSUE TITLE
Error room

### ISSUE THREAD

**Issue by GregTheEgg42069** [BeeStation/BeeStation-Hornet#3182]
## Round ID:25131

If you discovered this issue from playing beestation hosted servers:--> MRP

**Comment by ivanmixo** [comment]
This is very, very easy to reproduce. All you need is to not have a loc. This can also be accomplished by being in a locker.

**Comment by ike709** [comment]
I'm annoyed that nullspacing yourself is trivial. It used to be an accomplishment.

**Comment by PowerfulBacon** [comment]
Couldn't reproduce
