### ISSUE TITLE
Pretty sure air born viruses spread even if on internals specifically FT

### ISSUE THREAD

**Issue by DemonOfHatred** [BeeStation/BeeStation-Hornet#3186]
Issue reported from  Round ID: 25171 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1536

Probably need to test this but i was on internals the entire round and got the virus anyway.

**Comment by leestriter** [comment]
Airborne viruses also spread by touch and fluids, so that could've been it.
