### ISSUE TITLE
add +1 virologist slot

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#3192]
there was a PR a while ago that remapped viro to have two workstations, but there's still only one job slot for some reason

**Comment by Blueturbo47** [comment]
Viro spawners do not add a job slot, to add another job slot you need to go into config and add one.

**Comment by leestriter** [comment]
Sometimes there are two, I don't know if its map specific or something but I've played when there are two viros.

**Comment by zeskorion** [comment]
I made a pr for it awhile ago. The pr was merged, but viro job slots were lowered a few weeks later, probably due to a pr conflict

**Comment by hotimep** [comment]
> I made a pr for it awhile ago. The pr was merged, but viro job slots were lowered a few weeks later, probably due to a pr conflict

sad!
