### ISSUE TITLE
Someone randomly killing everyone

### ISSUE THREAD

**Issue by Am37000** [BeeStation/BeeStation-Hornet#3198]
Issue reported from  Round ID: 25245 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1536

I was in a game, I was BB at first, and I understand why this guy killed me, but when I came back as ashwalker, I was going to help everyone out, but he killed me with an explosive, I somehow got revived and when shuttle arrived, he threw me out airlock, he also killed around 3 innocents, he was NOT antag, I dont know his username but his ingame name was Tyrone Dante Davis Anthonia Randall Austin, Others said they would report him, so you should be able to find out his username.

**Comment by ike709** [comment]
https://forums.beestation13.com/c/player-input/player-reports/19
