### ISSUE TITLE
Check-Contents does not check PDA ID slots

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#3221]
## Round ID: 0

![image](https://user-images.githubusercontent.com/3241376/102958513-aa733600-44a2-11eb-819e-fa859d26695a.png)

## Reproduction:
Take an ID and put it in your PDA's ID slot.
This ID will not show up when the admin command "Check Contents" from the right-click menu is used.

This makes it harder to tell when someone has stolen an ID, since only the PDA is shown and not the ID in the PDA.

For example, an Assistant steals the ID of an engineer and puts it in their PDA, and their PDA in their ID slot. The Assistant's HUD icon will read engineer, and they will have the access of the engineer ID, but you cannot see what ID is in the PDA other than VV'ing the PDA to read the contents.

**Comment by Blueturbo47** [comment]
I don't think you can put an ID of a different name in a PDA, but that means job changes will not show up unless the PDA has been updated

**Comment by bloons3** [comment]
You can put another ID into a PDA. It will give you the same access as that ID, but will show the ID's icon to Sec-HUDs.

I find it useful when stealing access, since normal players that examine you will not see the ID but your PDA instead.

**Comment by Vexylius** [comment]
you can swap your id for the caps spare ID and admins won't notice a thing! 👀

**Comment by bloons3** [comment]
https://github.com/BeeStation/BeeStation-Hornet/blob/dd295c119c20f6bf2a0d2f1a4b684f6998810a4b/code/modules/admin/verbs/randomverbs.dm#L712
admin proc called here

calls here: https://github.com/BeeStation/BeeStation-Hornet/blob/5e08a213c1920f181b80d054e8df05531c3deb6e/code/modules/mob/living/living.dm#L495

Does the PDA lack a response to the signal sent to it?

**Comment by bloons3** [comment]
`SEND_SIGNAL(A, COMSIG_TRY_STORAGE_RETURN_INVENTORY, ret)`

**Comment by bloons3** [comment]
https://github.com/BeeStation/BeeStation-Hornet/blob/87cd7d8345cf0e9b7b06bc55102b2cb8ff8ed650/code/datums/components/storage/storage.dm#L481

So every storage datum object registers to that signal, and recursively returns those contents when sent a signal.
So, should there be a specific check for PDA contents, or should the PDA register a signal handler to return the contents (a single ID card).

**Comment by bloons3** [comment]
fuck oof bot
