### ISSUE TITLE
Any amount of tranquility will cause gondola infection

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#3228]
https://github.com/BeeStation/BeeStation-Hornet/blob/2467386bb666982dd41cb5e6acb4b1ebc4e392f3/code/modules/reagents/chemistry/reagents/other_reagents.dm#L1977

To bring this in line with https://github.com/BeeStation/BeeStation-Hornet/pull/2222 , a minimum amount of tranquility should be required to be ingested in order to cause the infection.

No more microdosing.

**Comment by zeskorion** [comment]
This is actually a piece of viro content i planned to do before I left:

Currently, *anything* that uses diseases is microdosable. I planned to give it a required amount scaling with transmission. Or another amount for simple diseases
