### ISSUE TITLE
RPD doesn't show pipe icons before crashing.

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#3229]
## Reproduction: 
Everytime I open up the RPD, it looks like this : https://imgur.com/a/vR0YfcK.
For every single tab, No icons on the pipes. I can still select them and find out what they are by placing, but there is nothing showing up. 

After about 5 seconds of opening it and selecting some random pipe, it instantly closes and gets replaced by this : https://imgur.com/a/10wuAIV

I can then close the window shown above, reopen the rpd, and it repeats, ad infinitum. I have no idea what causes this, or if it's a known bug. I apologize if it is something easily fixed and I just didn't know.

**Comment by MNarath1** [comment]
Did you try clearing your byond cache yet? And what byond version are you on?

**Comment by MNarath1** [comment]
Cause that second window is tg-ui breaking

**Comment by MNarath1** [comment]
Yes try to clear your cache that might just fix it
