### ISSUE TITLE
Unlogged chemical transfer method

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#3239]
https://github.com/BeeStation/BeeStation-Hornet/blob/b3d1ef930be506289c2c0f345557167c834bf7b2/code/game/objects/effects/effect_system/effects_smoke.dm#L242

Location is candidate to add smoke logging of chemical transfer into MOB.

**Comment by bloons3** [comment]
Reason for: Player affected had nothing mentioned in their logs of consuming that reagent.
![image](https://user-images.githubusercontent.com/3241376/103165867-9e5ce080-47e2-11eb-9757-ff71d3905b9f.png)

**Comment by yyzsong** [comment]
current round 😳
