### ISSUE TITLE
$50 Bounty - IC Chat Filtering

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#3250]
Marking this as $50 Bounty in title because some people are averse to bountysource. If you want a different form, I can paypal it. 

Anywho. Not asking for some sort of chat filter for gamer words, but something that makes IC a bit easier and more immersive. You currently (on MRP) cannot say things like "lol" and so forth. So, I'd rather these words be typeable but turn to an emote, or filtered in a sentence. Also - certain non-words, like [, /, so forth, automatically cut. You cannot physically pronounce "[", and they're more often than not a typo. You must say "bracket" if you need to explain it for some ungodly reason. These shouldn't apply to ghosts, who I don't think CAN emote.

Ex:
Typing "lol" your character laughs.
Typing "honk lol" your character says "Honk haha" and laughs.

**Shopping list:**
1. Single keywords emote. Keywords in sentences still say them, but emote after.
2. Some abbreviations typeable, but filter to actual words, wtf -> what, etc
2. Singular i is always capitalized
3. Special characters - cut from string

**Keywords:**
Not the complete list, but add or remove if you wish
- lol or haha - *laugh
- aaa -  *scream
- omg -  filtered to "oh my god" + *gasp
- hehe -  *giggle
- ahem - *cough
- whatever -  add *shrug
- wtf -  filtered to "what?" + *eyebrow
- sigh - add *sigh
- ugh or eugh - *grimace

**Comment by St0rmC4st3r** [comment]
I will start working on it aftertomorrow. If someone is willing to hop in before that - feel free to do so.

**Comment by PowerfulBacon** [comment]
I like the abreviations like lol being shortened but the stuff like haha would be annoying to be removed, since it gives less character / expression to your messages. The one for sigh would mean you can't say the word sigh.
Maybe one some of them rather than replace it with an emote, change the say adverb. <s>Also replacing teh with the would be cool since I do it on accident all the time.</s>
Removing stuff like 'ugh fine' makes it much harder to put expression into the messages themselves and having it as just fine followed by a tiny message in chat saying [x] grimaces conveys a completely different message.

**Comment by jlsnow301** [comment]
> I like the abreviations like lol being shortened but the stuff like haha would be annoying to be removed, since it gives less character / expression to your messages. The one for sigh would mean you can't say the word sigh.

You're right, and it shouldn't feel restrictive, only additive. I batted around this idea as I was typing it. I wouldn't be against just adding an emote after, but it would also come out as 
Bacon says "sigh."
Bacon sighs. 

That's where I was thinking that only one word sentences would automatically emote, but any larger sentences would just add on afterwards. This request is almost two PRs in one: a filter for abbreviations and an automatic emote keyword

**Comment by jlsnow301** [comment]
Additional: single letter i to always capitalized I

**Comment by ike709** [comment]
I'm not really a fan of adding *another* set of regex parsing to every chat message.
