### ISSUE TITLE
$50 Bounty - Newbie friendly hazards button

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#3251]
This is marked $50 bounty because, if you're averse to bountysource, I'm open to other methods like paypal.

Beestation! The server for new players! ... Sort of. Well, one of the hardest things in the beginning, and arguably one of the most non-fun, is the interaction of atmospherics and your character. So, picture, you, the absolute new player, having freshly understood how to unbuckle your seatbelt, walks outside of the arrivals shuttle only to die of pressure loss or no oxygen. No fun. SS13 sucks, go leave a negative review on... Steam?

This bounty would seek to make it a little simpler, yet not game breaking, by adding a _slow_ mechanic to equip your hazard gear automatically: The "hazard" button. Clicking this, while in possession of any type of hazard gear, such as your emergency skinsuit or firesuit, will cast a 10 second spell that will cause your character to equip it and turn on your internals. With a bit of a timer on casting, it's not effective for anyone that's done it once or twice.

Not having a piece will mean your character does not equip that piece. Probably needs an empty hand. Recasting it will attempt to shove it back into your emergency cardboard box, if possible. No more "turn on internals guys!" and the new player is like, "What?" Shortly before dying.

**Shopping List:**
A new ability button that causes character to start fumbling around, putting on internals and space suit. 
Reclickable to put away hazard gear in box (if skinsuit).

**Comment by ItsTisme** [comment]
Looks fun
