### ISSUE TITLE
Reinforced directional glass not always properly gets anchored

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#3257]
## Reproduction:

Take a reinforced glass or plasma reinforced glass to make directional windows screw it to the floor and then crowbar and screw again sometimes the window will still be draggable and not be anchored to the floor also atmos will be able to pass trough it now i was not able to reproduce this issue locally but it happened multiple times to  me on MRP server where i after realizing what happened to fix it had to first unscrew it from the frame then lever it out of the frame again and then i could screw it to the floor and do the rest of the steps normally.
Now i had this problem with directional reinforced plasma windows i do not know if it happens with normal windows too and i cannot reproduce it locally for some reason but i know it happened between multiple rounds to me already so yeah that was not so funny when i realized what happened after we had a atmos leak from the fusion chamber i build that burned down atmos cause of this bug.

**Comment by Chessus** [comment]
@MNarath1  Hmm I tried as well to reproduce this locally and had no luck. I had no issuse with atmos passing through a 1x1 chamber.
What size was your chamber?

If it happens again try to get a round number. Also use "Examine" and see what it says on the anchired, move-able glass!

**Comment by MNarath1** [comment]
> @MNarath1  Hmm I tried as well to reproduce this locally and had no luck. I had no issuse with atmos passing through a 1x1 chamber.
> 
> What size was your chamber?
> 
> 
> 
> If it happens again try to get a round number. Also use "Examine" and see what it says on the anchired, move-able glass!

Ye thats the thing i am also unable to reproduce locally but i had it in multiple rounds where i encountered it with one time getting a leak that burned down whole atmos the size of my chamber is usually 3x1

**Comment by MNarath1** [comment]
After that i first had to unscrew and rescrew it to the floor to actually get it to anchor

**Comment by Chessus** [comment]
I've had it happen to me a few times while testing with bith reinforced glass/plasma glass.. I think I may have hit the same glass twice while screwing it in. For example:
![glass anchor 1](https://user-images.githubusercontent.com/10277607/104186109-a44cf580-5461-11eb-95e3-43abc8c5fec2.PNG)
I think I have been hitting those, because when I do it slowly and accurately I don't get this issue. 
If it happens again you should check the chat box for somthing like this
```
You begin to screw the frame to the floor...
x6
You fasten the frame to the floor.
x6
You begin to screw the frame to the floor...
x2
You fasten the frame to the floor.
x2
You put the alien screwdriver into the agent belt.
You begin to lever the window into the frame...
x5
You pry the window into the frame.
x6
You begin to lever the window out of the frame...
x2
You pry the window out of the frame.
x2
You begin to lever the window into the frame...
You put the alien crowbar into the agent belt.
You begin to screw the window to the frame...
x4
You fasten the window to the frame.
x4
You begin to unscrew the frame from the floor...
x3
You unfasten the frame from the floor.
x3
```
