### ISSUE TITLE
Ninja Gets Blank Objective

### ISSUE THREAD

**Issue by DatBoiTim** [BeeStation/BeeStation-Hornet#3264]
## Testmerges:
N/A

##  Reproduction:
Ninja Spawn, become ninja, blank objective.
Beyond this I cannot provide any other explanation for reproduction.

## Related Photo
![NinjaObjIssue](https://user-images.githubusercontent.com/68963748/103260871-3f77a280-496d-11eb-92c5-82657b5a4862.png)

**Comment by Hibabo** [comment]
i was the ninja. while we're at it, having the brain of your target in your backpack fails the objective, im not sure why it happened but yeah it happened, could have something to do with the target supposedly being podded? heard after the round that he got revived via podding though i can't confirm.

**Comment by MCterra10** [comment]
Intended feature lol
"Free Objectives" are a thing, as weird as they are
