### ISSUE TITLE
mutation toxin recipes swapped

### ISSUE THREAD

**Issue by blakeeeee** [BeeStation/BeeStation-Hornet#3269]
## Round ID:

Irrelevant, but 25533 was the round that I discovered it.

## Reproduction:

The recipes for IPC mutation toxin and Squid mutation toxin are swapped. That's it. That's the bug.

**Comment by blakeeeee** [comment]
yeah it was on lrp

**Comment by St0rmC4st3r** [comment]
Zesko did it. #2222.
