### ISSUE TITLE
Bug? Feature? IC Overhead chat

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#3278]
## Round ID:
Current

## Testmerges:
Current

## Reproduction:
Any character resizing effect also resizes overhead text. While it is funny, it should also have its limits for readability: a min and a max size

**Comment by francinum** [comment]
Resizing itself should have better controls and never get out of scale, the problem is that overhead text utilizes maptext which obeys transform. This would be more effort than it's worth.

**Comment by jlsnow301** [comment]
> Resizing itself should have better controls and never get out of scale

two birds one stone then
