### ISSUE TITLE
Teratomas are counted as antag and end the round when they die

### ISSUE THREAD

**Issue by yyzsong** [BeeStation/BeeStation-Hornet#3279]
Round ID: 25582 

Reproduction: On a normal extended round, someone tried to transplant the brain of a Maint Teratoma into a human. This killed the teratoma, and, according to the admins, ended the round

additional: bruh bruh bruh

**Comment by badideaguy** [comment]
based

**Comment by Archanial** [comment]
Oh no

**Comment by Archanial** [comment]
Couldn't replicate it on localhost.

**Comment by bloons3** [comment]
If this is true, extended shouldn't have End on Antagonist Death set...
