### ISSUE TITLE
I always end up as someone I don't wanna be

### ISSUE THREAD

**Issue by JackieOTheWisp** [BeeStation/BeeStation-Hornet#3281]
Issue reported from  Round ID: 25582 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1536

When I choose my 4th player slot, it doesn't save that I keep it selected. My 4th character is named Marvin and my 1st is Patton, so I choose a second character, Alfred, no problem. I choose the 3rd character Tino, no problem. I choose Marvin and between rounds it sets me back to Patton.

**Comment by Sinestia** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/3254

that mean that this didn't work ?
