### ISSUE TITLE
Fancy chat string highlighting skips every second string

### ISSUE THREAD

**Issue by mudzbe** [BeeStation/BeeStation-Hornet#3295]
The string highlighting for the fancy chat whatever only highlights every even string, whilst every odd string is highlighted normally. This issue is regardless of capitalization or whether the strings have spaces.

## Reproduction:
In the highlight box type a series of strings separated by commas. For example: "Jamal,Mcterra,SS13" Jamal and SS13 will be highlighted, whilst Mcterra isn't. 

From Austation

**Comment by ike709** [comment]
This is probably TG's fault and you should probably try to reproduce it there and file an issue there if you can reproduce it.

**Comment by mudzbe** [comment]
Alright, I have now
