### ISSUE TITLE
ghosts can mess with scanner gates

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#3312]
## Reproduction:

![image](https://user-images.githubusercontent.com/3241376/103580120-3ae84800-4e9f-11eb-86b1-85439430226a.png)
scanner gates can be controlled by ghosts. Was not using admin-ai interact

**Comment by bloons3** [comment]
bump

**Comment by francinum** [comment]
I can't replicate this behavior live on sage.
