### ISSUE TITLE
Atmos alarms not clearing on their own?

### ISSUE THREAD

**Issue by Zerathrax** [BeeStation/BeeStation-Hornet#3334]
Issue reported from  Round ID: 25857 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1539

I've been noticing lately that it seems atmos alarms are not clearing on their own unless you manually set the alarm and then turn it back off on whatever air alarm is being triggered. Everything will be in the green but it wont deactivate on AI or Borg alarms until you turn it on and off again then its fine. Is this a bug or is there something I am missing that would still be triggering it?

**Comment by Chessus** [comment]
Can confirm this on MRP also, you need to do an action from the interface for the alarm to wipe such as vent on/off ect. Has been an issue for sometime.

Havn't tested whether adding/removing gasses does anything

**Comment by Chessus** [comment]
Recreation:
Opened plasma cannister in central primary hallway.
Used Stalise Atmos to clear it away.
Blue atmos lights but the alarm icon (only one) is still flashing with no dangerous elements in the air 
Seems only to happen when there's 2 or more atmos alarms in an area e.g Central Primary Hallway.
![airalarm1](https://user-images.githubusercontent.com/10277607/104188484-05c29380-5465-11eb-8377-d57a66291da6.png)

**Comment by Zerathrax** [comment]
Come to think of it, that may actually be the case. If I remember correctly its one vent in a room containing multiple. Also I think one vent will hold the alarms for others on Alarm list for say AI or Borgs because I THINK I have cleared one and it cleared any that may have been connected, but my memory is fuzzy so I may be wrong.

**Comment by Chessus** [comment]
[Refactor](https://github.com/tgstation/tgstation/pull/54406) from tg possible solution
