### ISSUE TITLE
[TGUISTAT] Design

### ISSUE THREAD

**Issue by francinum** [BeeStation/BeeStation-Hornet#3362]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Have eyes. View the stat panel.

Here's what TG's looks like.

![](https://file.house/OKXC.png)

**Comment by Chessus** [comment]
For those who can't see the current one:

![tguistat1](https://user-images.githubusercontent.com/10277607/104259119-7ea90600-54cc-11eb-9981-81583fcdcebc.png)
![tguistat2](https://user-images.githubusercontent.com/10277607/104259123-8072c980-54cc-11eb-8c40-455f9b9174f1.png)

**Comment by Crossedfall** [comment]
Multiple lines is a bit yucky (better than the scroll option, I guess)
![image](https://user-images.githubusercontent.com/26130695/104288678-bd639f80-547d-11eb-8365-848a08898ec0.png)

I also think it'd likely look a bit better to have matching background colors, or at least to have more care put into the separation of objects. Right now it's a bit jarring and doesn't look overly attractive.

---

The column widths could use some adjusting.
![image](https://user-images.githubusercontent.com/26130695/104288862-fbf95a00-547d-11eb-907b-eb05c6b66df2.png)

--

Lastly, the colors could stand to be a bit darker. As it is now, they're a bit too bright. Looking at it for a while can cause my eyes to defocus and it makes searching for things harder than it should be.

**Comment by Crossedfall** [comment]
Dark mode is a *little* better. I haven't decided if I like the choice to add a discord style embed color-bar on the left of the boxes. This does highlight another problem, which is that the dark theme seems to have had a bit more care put into it when compared to the light theme.

![image](https://user-images.githubusercontent.com/26130695/104289291-8fcb2600-547e-11eb-9f69-25ec801d3b79.png)

**Comment by PowerfulBacon** [comment]
fuuuck why is multiline mode the default

**Comment by Crossedfall** [comment]
> 
> 
> fuuuck why is multiline mode the default

Honestly though? I think it probably should be default. Bit easier to navigate

**Comment by PowerfulBacon** [comment]
> Honestly though? I think it probably should be default. Bit easier to navigate

It seems to be marked as the default.
Anyway, I just toggled to lightmode and its absolute garbage, ill fix it up

**Comment by francinum** [comment]
I'm sorry, no. It still looks dreadful.

**Comment by ike709** [comment]
It does, I hadn't noticed this had been autoclosed.

**Comment by PowerfulBacon** [comment]
could probably make something nice with an idea of what it would look like, the TG one provided as an example looks awful

**Comment by PowerfulBacon** [comment]
This issue is too opinionated, I need actual things I can implement and can't make any changes based on 'make it better'. What may look bad to you looks fine to me.
Feel free to reopen once screenshots with what needs to change being pointed out with a description of why it needs to change are provided.
