### ISSUE TITLE
Problems with uncraftable Tribal tab recipes 

### ISSUE THREAD

**Issue by FortSumter** [BeeStation/BeeStation-Hornet#3364]
Issue reported from  Round ID: 25993 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1539

Not related to the round, but from something I realized. There is no way to craft tribal arrows due to them requiring silk.

There is no info on the wiki on how to get silk, nor is there an entry on the wiki for the arrows. Some items also require leather, and there is no information on how to get leather as an ashwalker.

this may just require the ashwalkers page to be updated, but if silk truly doesn't exist as an item the recipes will need to be updated to use items actually available.

**Comment by Flakkyboo** [comment]
silk requires wool and a loom
leather is gotten from skinning goliath plate, wetting it then burning.

i provided all the tools necessary to make them in the nest

**Comment by FortSumter** [comment]
thank you. I had a talk about this with fellow mentors and while I find the tribal recipes to be lacking, there is not an error.

**Comment by Flakkyboo** [comment]
> 
> 
> thank you. I had a talk about this with fellow mentors and while I find the tribal recipes to be lacking, there is not an error.

the wiki is a little unclear yeah
