### ISSUE TITLE
invisible morph disguises

### ISSUE THREAD

**Issue by utilbird** [BeeStation/BeeStation-Hornet#3376]
## Reproduction:

Morphing/disguising as any open airlock turns you into a completely invisible, unclickable object. Most likely caused by sprite overlays being on a temporarily invisible object

**Comment by MNarath1** [comment]
not exactly the reason for this is that the actual icon_state is null since the smooth airlocks and the airlock parts are in the vis content list of the airlock.

**Comment by MNarath1** [comment]
I will probably make a fix for this bug soon'ish
