### ISSUE TITLE
Fastmos going hairwire

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#3383]
## Reproduction:
Reason is totally unknown but here some video material i know that is not really helpfull but yeah https://streamable.com/3bnpmt

**Comment by Chessus** [comment]
What round was this from?

Was there a breach on the shuttle prior to this as it looks like the ship is being re-pressurised. And fire alarm doors were tripped. Maybe its the vents in the exits that had something to do with it. I'm just speculating

**Comment by MNarath1** [comment]
> What round was this from?
> 
> 
> 
> Was there a breach on the shuttle prior to this as it looks like the ship is being re-pressurised. And fire alarm doors were tripped. Maybe its the vents in the exits that had something to do with it. I'm just speculating

 round id is in the description the vents where not the reason for this madness from what i can tell also the atmos system completly broke between multiple different rooms like the sec area window was destroyed by stuff smashing into it. The space wind was also fully bugged and way beyond what vents can do

**Comment by Sapfearon** [comment]
There was breach, yes. After breach was fixed we got this.

**Comment by MNarath1** [comment]
> There was breach, yes. After breach was fixed we got this.

Only thing i can say for sure about this is that the shuttle suddenly became a fucking centrifuge smashing everyone all around until only a few people in the command section survived the ghost gas scanner did not even show a vacuum in the effected area just nothing

**Comment by Sinestia** [comment]
Someone in discord told me casting ignite within a mech (or I guess being set on fire for that matter) caused this
havent tried tho 

edit: seems like a dead end F
