### ISSUE TITLE
Missing Polyvitiligo symptom

### ISSUE THREAD

**Issue by JAremko** [BeeStation/BeeStation-Hornet#339]
https://github.com/BeeStation/BeeStation-Hornet/blob/master/code/modules/antagonists/disease/disease_abilities.dm

Missing very important (for clown) Polyvitiligo symptom from Wiki https://tgstation13.org/wiki/Infections#Symptoms_Table

**Comment by Kerbin-Fiber** [comment]
I believe the symptom was removed and the wiki wasn't updated, which we should start updating the wiki with new PRs...

**Comment by yorii** [comment]
Polyvitiligo was readded on feb 18 by zeskorion in https://github.com/BeeStation/BeeStation-Hornet/pull/1203

Issue can be closed
