### ISSUE TITLE
drill screwdriver/bolt driver difference is imperceptible 

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#3393]
## Reproduction:
![image](https://user-images.githubusercontent.com/3241376/104686415-c85b4180-56c2-11eb-991b-af92203d6f1d.png)

![image](https://user-images.githubusercontent.com/3241376/104686427-cd1ff580-56c2-11eb-8d1a-73754e4f944e.png)

Old one was better since you could actually tell what the difference between the tool modes was.

**Comment by ItsTisme** [comment]
I had this aswel, maby another ircon to tell but I had a super hard time at first figuring it out.

If anything the bolt driver is a bigger sprite thats how I usualy do it

**Comment by Chessus** [comment]
@SomeAngryMiner @Agameofscones @thatguythere03
