### ISSUE TITLE
Xenos are too overwhelming in melee combat even if you're in a mech

### ISSUE THREAD

**Issue by githubuser4141** [BeeStation/BeeStation-Hornet#3426]
## Description: 

Xenos in their current form cannot be defeated in melee even if you're in a durand unless they're incompetent or you have a ranged weapon. A few rounds ago I was fighting a xenomorph drone one versus one in a durand in a 1x1 maint corridor and I couldn't get a single hit in, I tried spam clicking the tile he passed to claw at my mech, that didn't work, so I tried 'sniping' him by clicking ONLY when my cursor was over his sprite, that didn't work, I tried to corner him somewhere where he'd be stuck, obviously didn't work. Eventually I hit him a few times to which he simply backed off to let his health regenerate without any serious effects since patch #2785 removed stuns on mech punches.

# Suggestion:

Xenos IMHO shouldn't be able to beat a durand one on one in a close-quarters battle. If there's five of them then maybe, but the flavour text of durands suggests they were designed to mostly fight hostile fauna (aka xenos) in close quarters. Here's a few things that come to mind: 

1. Xenos should be stunnable if hit by a heavy mech's punch (Durand, Antag mechs, maybe Phazons), even if it's for a second or so. They can out-play this simply by avoiding close quarters mech combat, or bringing a buddy with good reflexes to drag you away when you're stunned.

2. Xenos should have a larger hitbox, or mechs should be able to 'slam' the entire tile instead of pixel hunting for a single purple pixel. This'll make it so you can simple click the tile a xeno's on if you're in a combat mech instead of trying to click their sprite exactly. Xenos can still counterplay this by grouping up on a mech (as they should be) or by running away when hit.

3. Add a new mech module primarily for CQC defense similar to a few other server's 'electric grid/fence' modules, that shock things that hit a mech in melee. This'll mean xenos won't get any free hits in, and will have to be smarter about how they approach fighting a mech in melee.

**Comment by ivanmixo** [comment]
Mechs aren't supposed to be good at melee, but xenos are supposed to be gods at melee with their high ass move speed that is used for kiting opponents (which that xeno was doing to you). Durand especially is designed to have ranged weapons.

**Comment by TeomanTheGreat** [comment]
Isn't point number 1already a thing?

**Comment by githubuser4141** [comment]
> Isn't point number 1already a thing?

I don't think so, mech punches knock humans down, but I don't think it applies to xenos.

> Mechs aren't supposed to be good at melee, but xenos are supposed to be gods at melee with their high ass move speed that is used for kiting opponents (which that xeno was doing to you). Durand especially is designed to have ranged weapons.

The damage values for mech's punches says otherwise, the gygax has a 25 damage punch, Phazon 15, and Durand a whopping 40 damage plus knockdown. And according to the wiki, the lore is that xenos especially hate Durands for their punches in close quarters. I don't think mechs should be unstoppable monsters in melee but surely a lone drone shouldn't be enough to take out a Durand in a 1x1 maintenance corridor? A horde of drones, sure. 2-3 drones in a more open environment, no problem.. but not a single drone who wasn't even laying on weeds.

**Comment by MNarath1** [comment]
Well yeah durant is made for ranged weapons problem is ranged weapons cannot be made with exofab anymore and good luck getting sec to actually give you access to their protolath highly unlikely that will happen unless hallways are overflowing with xenos and if that is the case getting to sec to get the weapons alone will be a adventure of itself not that by that time the ore silo is probably already broken

**Comment by githubuser4141** [comment]
> Well yeah durant is made for ranged weapons problem is ranged weapons cannot be made with exofab anymore and good luck getting sec to actually give you access to their protolath highly unlikely that will happen unless hallways are overflowing with xenos and if that is the case getting to sec to get the weapons alone will be a adventure of itself not that by that time the ore silo is probably already broken

Look, I'm not saying a durand should be able to one-man a whole infestation or anything with melee. But when compared to other antags, like for example a traitor with a blood-red + esword + ebow, the aforementioned traitor will easily die to a unarmed durand while doing minimal damage to it. Most xeno-bio mobs (mi-go, tree, faithless) will lose against a durand even if they outnumber it. Hell, even a bulldog or double e-sword operative can lose to a durand in a melee battle. Sure, xenos are supposed to be superior in melee and yes, they have no other serious weapons except melee, but surely a single drone shouldn't be able to kill a durand on it's own in a tight maintenance corridor? In the Aliens lore, a xenomorph queen was sent flying across the room by the equivalent of our own MK.1 Ripley mechs, so if a durand manages to score a hit on anything it should have some consequence.

**Comment by ghost** [comment]
The flavor text of the Durand does say it was made to combat hostile alien lifeforms.

**Comment by Sinestia** [comment]
> 
> 
> Well yeah durant is made for ranged weapons problem is ranged weapons cannot be made with exofab anymore and good luck getting sec to actually give you access to their protolath highly unlikely that will happen unless hallways are overflowing with xenos and if that is the case getting to sec to get the weapons alone will be a adventure of itself not that by that time the ore silo is probably already broken

you could always just give the mech to them lol

**Comment by PowerfulBacon** [comment]
Intentional
