### ISSUE TITLE
Heretics can sacrifice humanized monkeys. 

### ISSUE THREAD

**Issue by Rukofamicom** [BeeStation/BeeStation-Hornet#3434]
Step 1: Get LOTS of monkey cubes
Step 2: Place monkey cubes on rune for sacrifice
Step 3: Expose monkey cubes to Water + Mutadone via smoke/foam
Step 4: Use heart to pick a sacrifice target - it will select from among the humanized monkeys
Step 5: Probably have a valid sacrifice ready to go, if not you just created dozens of spare hearts
Step 6: Repeat until ascension, bypassing most of the heretic gameplay for monkey memes

Bonus: Convince crew you're friendly and bypass acting like an antag entirely.

**Comment by MNarath1** [comment]
Well first how do you even make spare hearts never got that also monkey cubes have a cap on how many you can spawn with those is this enough for this?

**Comment by eeSPee** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/3437

This PR fixes this, because heart will search targets with a mind.
