### ISSUE TITLE
pAI can only hear radios while holochassis is active.

### ISSUE THREAD

**Issue by QuarterEighth** [BeeStation/BeeStation-Hornet#3467]
Issue reported from  Round ID: 26368 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 513.1539

Me and a few other players have noted that, as a pAI, you can use the radio in both card and holochassis form. However, you can only hear the radio while your holochassis is active. I haven't tested if that's the case near an intercom or a station-bounced radio, but I've been around people with headsets speaking into them (yes, onto the common channel,) and I've only heard their speech, not the echo on the radio. Video / pictures can be recorded and posted if necessary.

**Comment by ike709** [comment]
Essentially the same issue as https://github.com/BeeStation/BeeStation-Hornet/pull/3464
