### ISSUE TITLE
Ctrl+Key hotkeys don't work anymore.

### ISSUE THREAD

**Issue by MiniMeatwad** [BeeStation/BeeStation-Hornet#347]
## Round ID: 
6446

## Reproduction:
Can't use Ctrl+Q to drop items for example.
(Hotkey mode off)

**Comment by MiniMeatwad** [comment]
fix

**Comment by qwertyquerty** [comment]
Imagine not using hotkey mode in 2019

**Comment by yorii** [comment]
Confirmed as not stale, but only occurs outside hotkey mode, is it really anything to care about?
Workaround exists by inputting any character into the command line and then doing Ctrl-Q.

**Comment by Crossedfall** [comment]
I don't see us fixing this anytime soon.
