### ISSUE TITLE
AI can hear the dead

### ISSUE THREAD

**Issue by FractalBobz** [BeeStation/BeeStation-Hornet#350]
## Reproduction:

MALF AI fucked up, hacked one apc and deployed into it, then accidentally shut it down.

In this space between life and death, still having working cores but with their main process in a deactivated APC they can still speak on all channels but can also hear ghosts.
If that's intended it's kind of funny.  it probably isn't.

Possibly relevant - i got an AI clone or something mid round?

**Comment by Toxici11i** [comment]
Uhh, this seems like a bug with how malf AI is designed, due to the latency required to do this (be able to shunt into the APC, and use hotkeys to shut it down would take a ping >90) and other factors (most people wont do this), ill investigate it but it may be unreproducable in live/test server play

**Comment by FractalBobz** [comment]
I'm betting i could reproduce it, but it really is a strange bug. I guess i only stumbled into it because I was playing MALF very badly. I didn't know what shunting into an APC would do and i didn't know how to get out.
For my own references - Where in the codebase should I go if I want to see the MALF specific code?

**Comment by ondrej008** [comment]
@FractalBobz Look in code/modules/antagonists/traitor/datum_traitor.dm it's both for IAA, AI and normal traitors. It sets the AI's hack_software var, which is also what the malf upgrade disk does.

**Comment by yorii** [comment]
Could not reproduce.

**Comment by FractalBobz** [comment]
It was a really fun bug for the round where it happened but it's so unlikely to come back I'm gonna close it.
