### ISSUE TITLE
Headpats don't force felinids and lizard to wag their tail.

### ISSUE THREAD

**Issue by Wilchenx** [BeeStation/BeeStation-Hornet#3564]
## Reproduction:

headpat the cat
it does not wag

**Comment by bloons3** [comment]
Sev 1 bug

**Comment by ToasterBan** [comment]
IC issue contact admins if this happens

**Comment by TeomanTheGreat** [comment]
Is this even an intended feature in the code?

**Comment by Wilchenx** [comment]
> Is this even an intended feature in the code?

It was on tg which I assume is what the code was based on

If it's not a bug then it's a feature request

**Comment by Sinestia** [comment]
this is fucking critical who gonna get on it

**Comment by ItsTisme** [comment]
OH FUCK SHIT GOTTA FIX IT SPEED MERGE
