### ISSUE TITLE
Cogscarabs start without a cultist status.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#3578]
They dont get a cult chat ability, they dont get a cog HUD either.

**Comment by PowerfulBacon** [comment]
Round ID? Anything in particular happened? Admin or cultist spawned?

**Comment by IllotAFV** [comment]
Can’t remember the number ID, but cult won that time, maybe it can be tracked this way.  
I picked a roundstart shell, that was lying on the table. I could use all the tools including the fabricator, but there wasn’t a HUD cog nearby scarab’s head. I could invoke scriptures at the slab, but there wasn’t a HUD shortcut for the cult speech. I probably couldn’t see an eminence either, but I am not sure about this one.
Seems like an overlay HUD problem of the scarab itself, because all the spells of the slab were visible with the shortcuts.
