### ISSUE TITLE
Ghetto powersink is too strong

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#3586]
You can construct a ghetto powersink by using a monkey on a conveyor belt that leads directly into an electrified grille. This causes power drain in excess of several MW (probably much higher as I did not actually reach a limit) and will easily prevent all networked APCs from receiving power.

I'm not sure what would be the best course of nerfing this aside from removing power drain from shocks.

**Comment by yyzsong** [comment]
Remove the ability to shock husks, maybe?

**Comment by MNarath1** [comment]
Sorry but a powersinks true horror is that it will suck even apc's dry (then at one point explode) the powerdrain from this should not effect the apc's beyond maybe recharging most likely engineering will respond way before there is any problem

**Comment by MNarath1** [comment]
Most likely engineering will either balance it out or find the cause

**Comment by MNarath1** [comment]
I guess to see if this actually would become a problem we would need this to be used in an actual round to see how it will be handled by crew
