### ISSUE TITLE
Firelocks being destroyed/broken do not allow atmos to pass through the tile

### ISSUE THREAD

**Issue by Chessus** [BeeStation/BeeStation-Hornet#3594]
## Round ID:
26580, all rounds

## Reproduction:
As a swarmer I consumed fire doors that were deployed because a breach.

Once one or both are destroyed, they do not let the atmos pass through. When they are completely consumed/destroyed to metal, the tile does not update and atmos can not pass through it. 

By destroying the walls around it, the atmos was able to pass through. No items that were caught in the atmos wooshed passed over the tile the doors were on, the simply went around that tile even though it was blank.

I tested again on a private server and it does not matter how it's destroyed. A broken then destroyed firelock will not let atmos pass unless the tile is updated, e.g. Open/close the air lock.

**Comment by MNarath1** [comment]
This problem seems to extend more then we trought its not only firelocks this also applies to directional window doors

**Comment by MNarath1** [comment]
its more or less cause CanAtmoPass() is not called on destroy

**Comment by MNarath1** [comment]
correction reason for this to happen is that the turf is not properly reset to Atmos_pass =TRUE if all directional windows /airlocks are destroyed.
