### ISSUE TITLE
Expanded Hypospray upgrade for Mediborgs isn't working

### ISSUE THREAD

**Issue by 1210Avi** [BeeStation/BeeStation-Hornet#3621]
Issue reported from  Round ID: 26994 (BeeStation Golden)

Reporting client version: 513.1536

I noticed every chemical associated with the Expanded Hypospray upgrade is always empty. Even if I never used them on that round. Waiting, charging, unequipping and equipping the module doesn't solve the problem. I got a module reset and re-equipped all upgrades and I was able to use expanded chemicals (mutadone) once. I thought that was the end of it but 5 minutes later when I require advanced chemicals they're all empty again, except for the basic, default, chemicals

**Comment by Sarchutar** [comment]
Seems to be working for me. (Tested on a local server)

<details>
  <summary>Before injecting
</summary>

![Screenshot_1](https://user-images.githubusercontent.com/53494785/107813537-d5765980-6d70-11eb-95d0-9d6b3474a20a.png)
</details>

<details>
  <summary>After injecting (Rezadone)
</summary>

![Screenshot_2](https://user-images.githubusercontent.com/53494785/107813596-ec1cb080-6d70-11eb-91ce-9468bfd2cde1.png)
![Screenshot_3](https://user-images.githubusercontent.com/53494785/107813600-ede67400-6d70-11eb-8218-b59e119d3d8e.png)
![Screenshot_4](https://user-images.githubusercontent.com/53494785/107813607-efb03780-6d70-11eb-8981-deacc26fc3e3.png)
</details>
