### ISSUE TITLE
Genetics fireball power destroys implants and pins out of guns on whatever it hits.

### ISSUE THREAD

**Issue by Isy232** [BeeStation/BeeStation-Hornet#3626]
## Round ID:

27005
## Testmerges:

None

## Reproduction:

Have a gun with a firing pin in your backpack and a mindshield in you.

Get fireballed by firebreath.

Everything is destroyed, even implants in you and firing pins in guns.

**Comment by ZombiesVsPlants** [comment]
The fireball from wizard also destroyed all borg modules and deleted the entire battery when I got hit with it a month back.
