### ISSUE TITLE
Alien's neurotoxin rebalance made it useless.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#3665]
Everyone has thick clothing of any sort. Moreover, that armour rebalance made even more stuff thick. It cant even reach the person now.

**Comment by Cenrus** [comment]
Was a bit of a kneejerk nerf if you ask me

**Comment by leestriter** [comment]
Completely agree. I wasn't there for the event round they used as the basis for the nerf but I've personally just gotten decimated every time I've been a xeno since the nerf.

**Comment by bloons3** [comment]
Also keep in mind that everyone has a facehugger blocking mask roundstart in their backpack...
