### ISSUE TITLE
Clockcult: Issues with nonhuman cultists

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#3666]
Eminence has no way to tell who is cult or non cult, they don't have the antag HUD like human servants do.

The Eminence can nuzzle mobs and swim in the pool despite being incorporeal.

Same with scarabs and marauders they don't have access to the heirophant network and can't see the HUD.

**Comment by park66665** [comment]
By "nonhuman", you are talking about cultists that aren't `mob/living/carbon/human`, or human that isn't humanbasic (for example, mothpeople, catpeople etc?) in code?

**Comment by IllotAFV** [comment]
It's like in #3578. Looks like it is the same problem.

**Comment by ike709** [comment]
@PowerfulBacon

**Comment by Cenrus** [comment]
Scarabs do have the clock cult antag datum, but not the HUD or the hiero network for some reason, I mean human as in humanbasic.

**Comment by PowerfulBacon** [comment]
This was already fixed

**Comment by PowerfulBacon** [comment]
wait it wasnt merged

**Comment by PowerfulBacon** [comment]
resolved by https://github.com/BeeStation/BeeStation-Hornet/pull/3658
