### ISSUE TITLE
[Bounty] $5 Camera implant

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#3689]
Yet another thing for security to craft and admins to 'bus.

Deliverable: A camera implant, that when implanted works like the cyborg camera, where a camera console will be able to see that person.

Cameras should be joined to the SS13 network, and start with "IMPLANT #" with some random numbers after it.
(Talked with Cenrus, this is probably better off as an admin bus only item)

**Comment by Sarchutar** [comment]
I might actually work on this.

@bloons3 is this wanted as an implant like the chemical/tracking implant or like a cybernetic implant?

**Comment by bloons3** [comment]
> I might actually work on this.
> 
> @bloons3 is this wanted as an implant like the chemical/tracking implant or like a cybernetic implant?

It could be either, but it should be insertable with admin tools. For balance, it should be adminbus only.
