### ISSUE TITLE
[Bounty] $20 Port TG sects

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#3707]
Port all pull requests dealing with chaplain sects from TG station

https://github.com/tgstation/tgstation/pull/49434 is the first one.

It's a good way to give the chaplain something to do, and more utility than simply valid hunting the entire round.

**Comment by Archanial** [comment]
I'll do it

**Comment by bloons3** [comment]
Paid

**Comment by Archanial** [comment]
Can confirm
