### ISSUE TITLE
Necropolis Seed doesn't give any loot.

### ISSUE THREAD

**Issue by Demi-Wahoo** [BeeStation/BeeStation-Hornet#3728]
## Reproduction:
1. Make Necropolis Seed virus with stealth 8 and Viral Aggressive Metabolism
2. Infect a player. (Yourself or Somebody else)
3. Kill that player.
 
 ## Results:
Virus doesn't yield any lavaland necropolis tendril items, it only permanently removes the infected player from the round.

**Comment by RDS88-beeman** [comment]
i am fairly sure this was because of a botched patch zesko implemented to prevent slimepeople and golems from using the virus, as i know it worked before this, but afterwards i have no evidence of it continuing to work. The simplest solution would probably be to revert the patch, as the case it exists for is, while powerful, very niche, and requires the optimal performance and co-operation of two very luck based departments for a luck based reward, and both can probably do better alone

**Comment by RDS88-beeman** [comment]
Code after patch
/datum/symptom/necroseed/OnDeath(datum/disease/advance/A)
	if(!..())
		return
	var/mob/living/M = A.affected_mob
	if(chest && A.stage == 5 && M.mind)
		to_chat(M, "<span class='danger'>Your soul is ripped from your body!</span>")
		M.visible_message("<span class='danger'>An unearthly roar shakes the ground as [M] explodes into a shower of gore, leaving behind an ominous, fleshy chest.</span>")
		playsound(M.loc,'sound/effects/tendril_destroyed.ogg', 200, 0, 50, 1, 1)
		M.hellbound = TRUE
		M.gib()
		if(ishuman(M)) //We don't NEED them to be human. However, I want to avoid people making teratoma-farms for necrochests
			var/mob/living/carbon/human/H = M
			var/S = H.dna.species
			if(istype(S, /datum/species/golem) || istype(S, /datum/species/jelly)) //nope. sorry, xenobio.
				return
		else
			return (having looked at it, i think this return is the problem, as it returns after the gib but before the creation of the chest)
		new /obj/structure/closet/crate/necropolis/tendril(M.loc)
		
Code before patch

/datum/symptom/necroseed/OnDeath(datum/disease/advance/A)
	if(!..())
		return
	var/mob/living/M = A.affected_mob
	if(chest && A.stage == 5 && M.mind)
		to_chat(M, "<span class='danger'>Your soul is ripped from your body!</span>")
		M.visible_message("<span class='danger'>An unearthly roar shakes the ground as [M] explodes into a shower of gore, leaving behind an ominous, fleshy chest.</span>")
		new /obj/structure/closet/crate/necropolis/tendril(M.loc)
		playsound(M.loc,'sound/effects/tendril_destroyed.ogg', 200, 0, 50, 1, 1)
		M.hellbound = TRUE
		M.gib()
