### ISSUE TITLE
Express Supply Console destroying contents of crates

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#3732]
The express supply console drop pods destroy the contents of their crates when they land, effectively making it useless. I'm almost certain this is because of zeskos explosion changes, as the pod generates a small explosion when it arrives at a beacon.

**Comment by PowerfulBacon** [comment]
I've had supply pods work after zesko's changes. The only time I've had this not work was recently on Reebe, although location was probably not important.

**Comment by FlamePrince** [comment]
I thought this was intentional.
