### ISSUE TITLE
Audit this fucking list for shit that shouldn't give illegal tech

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#3755]
1. The roundstart grenade launcher
2. Anything cargo can order without an emag
3. The fucking MOSIN NAGANT
4. deck/syndicate, the toy version that cargo can buy

https://github.com/BeeStation/BeeStation-Hornet/blob/6f578c485ca9ba8ee11eb5a770f351bea7f761a6/code/modules/research/techweb/all_nodes.dm#L1140

uplink_items

(E) (C) (-) 1 = /datum/uplink_item/discounts(E) (C) (-) 2 = /datum/uplink_item/bundles_TC/chemical(E) (C) (-) 3 = /datum/uplink_item/bundles_TC/bulldog(E) (C) (-) 4 = /datum/uplink_item/bundles_TC/c20r(E) (C) (-) 5 = /datum/uplink_item/bundles_TC/cyber_implants(E) (C) (-) 6 = /datum/uplink_item/bundles_TC/medical(E) (C) (-) 7 = /datum/uplink_item/bundles_TC/sniper(E) (C) (-) 8 = /datum/uplink_item/bundles_TC/firestarter(E) (C) (-) 9 = /datum/uplink_item/bundles_TC/contract_kit(E) (C) (-) 10 = /datum/uplink_item/bundles_TC/bundle_A(E) (C) (-) 11 = /datum/uplink_item/bundles_TC/bundle_B(E) (C) (-) 12 = /datum/uplink_item/bundles_TC/surplus/super(E) (C) (-) 13 = /datum/uplink_item/bundles_TC/surplus/random(E) (C) (-) 14 = /datum/uplink_item/bundles_TC/surplus(E) (C) (-) 15 = /datum/uplink_item/bundles_TC/random(E) (C) (-) 16 = /datum/uplink_item/bundles_TC/telecrystal/five(E) (C) (-) 17 = /datum/uplink_item/bundles_TC/telecrystal/twenty(E) (C) (-) 18 = /datum/uplink_item/bundles_TC/telecrystal(E) (C) (-) 19 = /datum/uplink_item/bundles_TC/crate/medical(E) (C) (-) 20 = /datum/uplink_item/bundles_TC/crate/shuttle(E) (C) (-) 21 = /datum/uplink_item/bundles_TC/crate(E) (C) (-) 22 = /datum/uplink_item/bundles_TC(E) (C) (-) 23 = /datum/uplink_item/dangerous/poisonknife(E) (C) (-) 24 = /datum/uplink_item/dangerous/rawketlawnchair(E) (C) (-) 25 = /datum/uplink_item/dangerous/grenadelauncher(E) (C) (-) 26 = /datum/uplink_item/dangerous/pie_cannon(E) (C) (-) 27 = /datum/uplink_item/dangerous/bananashield(E) (C) (-) 28 = /datum/uplink_item/dangerous/clownsword(E) (C) (-) 29 = /datum/uplink_item/dangerous/bioterror(E) (C) (-) 30 = /datum/uplink_item/dangerous/throwingweapons(E) (C) (-) 31 = /datum/uplink_item/dangerous/shotgun(E) (C) (-) 32 = /datum/uplink_item/dangerous/smg(E) (C) (-) 33 = /datum/uplink_item/dangerous/superechainsaw(E) (C) (-) 34 = /datum/uplink_item/dangerous/doublesword(E) (C) (-) 35 = /datum/uplink_item/dangerous/sword(E) (C) (-) 36 = /datum/uplink_item/dangerous/shield(E) (C) (-) 37 = /datum/uplink_item/dangerous/flamethrower(E) (C) (-) 38 = /datum/uplink_item/dangerous/rapid(E) (C) (-) 39 = /datum/uplink_item/dangerous/guardian(E) (C) (-) 40 = /datum/uplink_item/dangerous/machinegun(E) (C) (-) 41 = /datum/uplink_item/dangerous/carbine(E) (C) (-) 42 = /datum/uplink_item/dangerous/powerfist(E) (C) (-) 43 = /datum/uplink_item/dangerous/sniper(E) (C) (-) 44 = /datum/uplink_item/dangerous/pistol(E) (C) (-) 45 = /datum/uplink_item/dangerous/bolt_action(E) (C) (-) 46 = /datum/uplink_item/dangerous/revolver(E) (C) (-) 47 = /datum/uplink_item/dangerous/foamsmg(E) (C) (-) 48 = /datum/uplink_item/dangerous/foammachinegun(E) (C) (-) 49 = /datum/uplink_item/dangerous/foampistol(E) (C) (-) 50 = /datum/uplink_item/dangerous/semiautoturret(E) (C) (-) 51 = /datum/uplink_item/dangerous/heavylaserturret(E) (C) (-) 52 = /datum/uplink_item/dangerous(E) (C) (-) 53 = /datum/uplink_item/stealthy_weapons/combatglovesplus(E) (C) (-) 54 = /datum/uplink_item/stealthy_weapons/cqc(E) (C) (-) 55 = /datum/uplink_item/stealthy_weapons/dart_pistol(E) (C) (-) 56 = /datum/uplink_item/stealthy_weapons/dehy_carp(E) (C) (-) 57 = /datum/uplink_item/stealthy_weapons/edagger(E) (C) (-) 58 = /datum/uplink_item/stealthy_weapons/martialartskarate(E) (C) (-) 59 = /datum/uplink_item/stealthy_weapons/martialarts(E) (C) (-) 60 = /datum/uplink_item/stealthy_weapons/radbow(E) (C) (-) 61 = /datum/uplink_item/stealthy_weapons/crossbow(E) (C) (-) 62 = /datum/uplink_item/stealthy_weapons/origami_kit(E) (C) (-) 63 = /datum/uplink_item/stealthy_weapons/traitor_chem_bottle(E) (C) (-) 64 = /datum/uplink_item/stealthy_weapons/romerol_kit(E) (C) (-) 65 = /datum/uplink_item/stealthy_weapons/sleepy_pen(E) (C) (-) 66 = /datum/uplink_item/stealthy_weapons/suppressor(E) (C) (-) 67 = /datum/uplink_item/stealthy_weapons(E) (C) (-) 68 = /datum/uplink_item/ammo/pistol(E) (C) (-) 69 = /datum/uplink_item/ammo/pistolap(E) (C) (-) 70 = /datum/uplink_item/ammo/pistolhp(E) (C) (-) 71 = /datum/uplink_item/ammo/pistolfire(E) (C) (-) 72 = /datum/uplink_item/ammo/shotgun/bag(E) (C) (-) 73 = /datum/uplink_item/ammo/shotgun/buck(E) (C) (-) 74 = /datum/uplink_item/ammo/shotgun/dragon(E) (C) (-) 75 = /datum/uplink_item/ammo/shotgun/meteor(E) (C) (-) 76 = /datum/uplink_item/ammo/shotgun/slug(E) (C) (-) 77 = /datum/uplink_item/ammo/shotgun/breacher(E) (C) (-) 78 = /datum/uplink_item/ammo/shotgun(E) (C) (-) 79 = /datum/uplink_item/ammo/revolver(E) (C) (-) 80 = /datum/uplink_item/ammo/a40mm(E) (C) (-) 81 = /datum/uplink_item/ammo/smg/bag(E) (C) (-) 82 = /datum/uplink_item/ammo/smg(E) (C) (-) 83 = /datum/uplink_item/ammo/sniper/basic(E) (C) (-) 84 = /datum/uplink_item/ammo/sniper/penetrator(E) (C) (-) 85 = /datum/uplink_item/ammo/sniper/soporific(E) (C) (-) 86 = /datum/uplink_item/ammo/sniper(E) (C) (-) 87 = /datum/uplink_item/ammo/carbine(E) (C) (-) 88 = /datum/uplink_item/ammo/machinegun/basic(E) (C) (-) 89 = /datum/uplink_item/ammo/machinegun/ap(E) (C) (-) 90 = /datum/uplink_item/ammo/machinegun/hollow(E) (C) (-) 91 = /datum/uplink_item/ammo/machinegun/incen(E) (C) (-) 92 = /datum/uplink_item/ammo/machinegun(E) (C) (-) 93 = /datum/uplink_item/ammo/rocket/basic(E) (C) (-) 94 = /datum/uplink_item/ammo/rocket/hedp(E) (C) (-) 95 = /datum/uplink_item/ammo/rocket(E) (C) (-) 96 = /datum/uplink_item/ammo/pistolaps(E) (C) (-) 97 = /datum/uplink_item/ammo/toydarts(E) (C) (-) 98 = /datum/uplink_item/ammo/bioterror(E) (C) (-) 99 = /datum/uplink_item/ammo/bolt_action(E) (C) (-) 100 = /datum/uplink_item/ammo(E) (C) (-) 101 = /datum/uplink_item/explosives/bioterrorfoam(E) (C) (-) 102 = /datum/uplink_item/explosives/bombanana(E) (C) (-) 103 = /datum/uplink_item/explosives/buzzkill(E) (C) (-) 104 = /datum/uplink_item/explosives/c4(E) (C) (-) 105 = /datum/uplink_item/explosives/c4bag(E) (C) (-) 106 = /datum/uplink_item/explosives/x4bag(E) (C) (-) 107 = /datum/uplink_item/explosives/clown_bomb_clownops(E) (C) (-) 108 = /datum/uplink_item/explosives/detomatix(E) (C) (-) 109 = /datum/uplink_item/explosives/emp(E) (C) (-) 110 = /datum/uplink_item/explosives/ducky(E) (C) (-) 111 = /datum/uplink_item/explosives/doorCharge(E) (C) (-) 112 = /datum/uplink_item/explosives/virus_grenade(E) (C) (-) 113 = /datum/uplink_item/explosives/grenadier(E) (C) (-) 114 = /datum/uplink_item/explosives/bigducky(E) (C) (-) 115 = /datum/uplink_item/explosives/pizza_bomb(E) (C) (-) 116 = /datum/uplink_item/explosives/soap_clusterbang(E) (C) (-) 117 = /datum/uplink_item/explosives/syndicate_bomb(E) (C) (-) 118 = /datum/uplink_item/explosives/syndicate_detonator(E) (C) (-) 119 = /datum/uplink_item/explosives/syndicate_minibomb(E) (C) (-) 120 = /datum/uplink_item/explosives/tearstache(E) (C) (-) 121 = /datum/uplink_item/explosives/viscerators(E) (C) (-) 122 = /datum/uplink_item/explosives/explosive_flashbulbs(E) (C) (-) 123 = /datum/uplink_item/explosives(E) (C) (-) 124 = /datum/uplink_item/support/clown_reinforcement(E) (C) (-) 125 = /datum/uplink_item/support/reinforcement/assault_borg(E) (C) (-) 126 = /datum/uplink_item/support/reinforcement/medical_borg(E) (C) (-) 127 = /datum/uplink_item/support/reinforcement/saboteur_borg(E) (C) (-) 128 = /datum/uplink_item/support/reinforcement(E) (C) (-) 129 = /datum/uplink_item/support/gygax(E) (C) (-) 130 = /datum/uplink_item/support/honker(E) (C) (-) 131 = /datum/uplink_item/support/mauler(E) (C) (-) 132 = /datum/uplink_item/support(E) (C) (-) 133 = /datum/uplink_item/stealthy_tools/agent_card(E) (C) (-) 134 = /datum/uplink_item/stealthy_tools/ai_detector(E) (C) (-) 135 = /datum/uplink_item/stealthy_tools/chameleon(E) (C) (-) 136 = /datum/uplink_item/stealthy_tools/chameleon_proj(E) (C) (-) 137 = /datum/uplink_item/stealthy_tools/codespeak_manual(E) (C) (-) 138 = /datum/uplink_item/stealthy_tools/combatbananashoes(E) (C) (-) 139 = /datum/uplink_item/stealthy_tools/taeclowndo_shoes(E) (C) (-) 140 = /datum/uplink_item/stealthy_tools/emplight(E) (C) (-) 141 = /datum/uplink_item/stealthy_tools/mulligan(E) (C) (-) 142 = /datum/uplink_item/stealthy_tools/syndigaloshes/nuke(E) (C) (-) 143 = /datum/uplink_item/stealthy_tools/syndigaloshes(E) (C) (-) 144 = /datum/uplink_item/stealthy_tools/chambowman(E) (C) (-) 145 = /datum/uplink_item/stealthy_tools/chamweldinggoggles(E) (C) (-) 146 = /datum/uplink_item/stealthy_tools/chaminsuls(E) (C) (-) 147 = /datum/uplink_item/stealthy_tools/jammer(E) (C) (-) 148 = /datum/uplink_item/stealthy_tools/smugglersatchel(E) (C) (-) 149 = /datum/uplink_item/stealthy_tools(E) (C) (-) 150 = /datum/uplink_item/suits/space_suit(E) (C) (-) 151 = /datum/uplink_item/suits/hardsuit/elite(E) (C) (-) 152 = /datum/uplink_item/suits/hardsuit/shielded(E) (C) (-) 153 = /datum/uplink_item/suits/hardsuit(E) (C) (-) 154 = /datum/uplink_item/suits(E) (C) (-) 155 = /datum/uplink_item/device_tools/cutouts(E) (C) (-) 156 = /datum/uplink_item/device_tools/assault_pod(E) (C) (-) 157 = /datum/uplink_item/device_tools/binary(E) (C) (-) 158 = /datum/uplink_item/device_tools/compressionkit(E) (C) (-) 159 = /datum/uplink_item/device_tools/magboots(E) (C) (-) 160 = /datum/uplink_item/device_tools/brainwash_disk(E) (C) (-) 161 = /datum/uplink_item/device_tools/briefcase_launchpad(E) (C) (-) 162 = /datum/uplink_item/device_tools/camera_bug(E) (C) (-) 163 = /datum/uplink_item/device_tools/military_belt(E) (C) (-) 164 = /datum/uplink_item/device_tools/emag(E) (C) (-) 165 = /datum/uplink_item/device_tools/fakenucleardisk(E) (C) (-) 166 = /datum/uplink_item/device_tools/syndicate_teleporter(E) (C) (-) 167 = /datum/uplink_item/device_tools/frame(E) (C) (-) 168 = /datum/uplink_item/device_tools/failsafe(E) (C) (-) 169 = /datum/uplink_item/device_tools/toolbox(E) (C) (-) 170 = /datum/uplink_item/device_tools/syndie_glue(E) (C) (-) 171 = /datum/uplink_item/device_tools/hacked_module(E) (C) (-) 172 = /datum/uplink_item/device_tools/hypnotic_flash(E) (C) (-) 173 = /datum/uplink_item/device_tools/medgun(E) (C) (-) 174 = /datum/uplink_item/device_tools/singularity_beacon(E) (C) (-) 175 = /datum/uplink_item/device_tools/powersink(E) (C) (-) 176 = /datum/uplink_item/device_tools/stimpack(E) (C) (-) 177 = /datum/uplink_item/device_tools/medkit(E) (C) (-) 178 = /datum/uplink_item/device_tools/soap(E) (C) (-) 179 = /datum/uplink_item/device_tools/surgerybag(E) (C) (-) 180 = /datum/uplink_item/device_tools/encryptionkey(E) (C) (-) 181 = /datum/uplink_item/device_tools/syndietome(E) (C) (-) 182 = /datum/uplink_item/device_tools/potion(E) (C) (-) 183 = /datum/uplink_item/device_tools/suspiciousphone(E) (C) (-) 184 = /datum/uplink_item/device_tools/thermal(E) (C) (-) 185 = /datum/uplink_item/device_tools(E) (C) (-) 186 = /datum/uplink_item/implants/adrenal(E) (C) (-) 187 = /datum/uplink_item/implants/antistun(E) (C) (-) 188 = /datum/uplink_item/implants/freedom(E) (C) (-) 189 = /datum/uplink_item/implants/microbomb(E) (C) (-) 190 = /datum/uplink_item/implants/macrobomb(E) (C) (-) 191 = /datum/uplink_item/implants/radio(E) (C) (-) 192 = /datum/uplink_item/implants/reviver(E) (C) (-) 193 = /datum/uplink_item/implants/stealthimplant(E) (C) (-) 194 = /datum/uplink_item/implants/storage(E) (C) (-) 195 = /datum/uplink_item/implants/thermals(E) (C) (-) 196 = /datum/uplink_item/implants/uplink(E) (C) (-) 197 = /datum/uplink_item/implants/xray(E) (C) (-) 198 = /datum/uplink_item/implants(E) (C) (-) 199 = /datum/uplink_item/race_restricted/syndilamp(E) (C) (-) 200 = /datum/uplink_item/race_restricted/ethereal_grenade(E) (C) (-) 201 = /datum/uplink_item/race_restricted/plasmachameleon(E) (C) (-) 202 = /datum/uplink_item/race_restricted/tribal_claw(E) (C) (-) 203 = /datum/uplink_item/race_restricted(E) (C) (-) 204 = /datum/uplink_item/role_restricted/ancient_jumpsuit(E) (C) (-) 205 = /datum/uplink_item/role_restricted/oldtoolboxclean(E) (C) (-) 206 = /datum/uplink_item/role_restricted/pie_cannon(E) (C) (-) 207 = /datum/uplink_item/role_restricted/blastcannon(E) (C) (-) 208 = /datum/uplink_item/role_restricted/crushmagboots(E) (C) (-) 209 = /datum/uplink_item/role_restricted/gorillacubes(E) (C) (-) 210 = /datum/uplink_item/role_restricted/rad_laser(E) (C) (-) 211 = /datum/uplink_item/role_restricted/syndicate_mmi(E) (C) (-) 212 = /datum/uplink_item/role_restricted/upgrade_wand(E) (C) (-) 213 = /datum/uplink_item/role_restricted/clown_bomb(E) (C) (-) 214 = /datum/uplink_item/role_restricted/clown_grenade(E) (C) (-) 215 = /datum/uplink_item/role_restricted/clown_grenade_broken(E) (C) (-) 216 = /datum/uplink_item/role_restricted/spider_injector(E) (C) (-) 217 = /datum/uplink_item/role_restricted/clowncar(E) (C) (-) 218 = /datum/uplink_item/role_restricted/taeclowndo_shoes(E) (C) (-) 219 = /datum/uplink_item/role_restricted/superior_honkrender(E) (C) (-) 220 = /datum/uplink_item/role_restricted/concealed_weapon_bay(E) (C) (-) 221 = /datum/uplink_item/role_restricted/haunted_magic_eightball(E) (C) (-) 222 = /datum/uplink_item/role_restricted/his_grace(E) (C) (-) 223 = /datum/uplink_item/role_restricted/cultconstructkit(E) (C) (-) 224 = /datum/uplink_item/role_restricted/spanish_flu(E) (C) (-) 225 = /datum/uplink_item/role_restricted/retrovirus(E) (C) (-) 226 = /datum/uplink_item/role_restricted/random_disease(E) (C) (-) 227 = /datum/uplink_item/role_restricted/anxiety(E) (C) (-) 228 = /datum/uplink_item/role_restricted/explosive_hot_potato(E) (C) (-) 229 = /datum/uplink_item/role_restricted/echainsaw(E) (C) (-) 230 = /datum/uplink_item/role_restricted/holocarp(E) (C) (-) 231 = /datum/uplink_item/role_restricted/ez_clean_bundle(E) (C) (-) 232 = /datum/uplink_item/role_restricted/mimery(E) (C) (-) 233 = /datum/uplink_item/role_restricted/pressure_mod(E) (C) (-) 234 = /datum/uplink_item/role_restricted/esaw_arm(E) (C) (-) 235 = /datum/uplink_item/role_restricted/magillitis_serum(E) (C) (-) 236 = /datum/uplink_item/role_restricted/modified_syringe_gun(E) (C) (-) 237 = /datum/uplink_item/role_restricted/chemical_gun(E) (C) (-) 238 = /datum/uplink_item/role_restricted/reverse_bear_trap(E) (C) (-) 239 = /datum/uplink_item/role_restricted/reverse_revolver(E) (C) (-) 240 = /datum/uplink_item/role_restricted/laser_arm(E) (C) (-) 241 = /datum/uplink_item/role_restricted(E) (C) (-) 242 = /datum/uplink_item/badass/costumes/obvious_chameleon(E) (C) (-) 243 = /datum/uplink_item/badass/costumes/centcom_official(E) (C) (-) 244 = /datum/uplink_item/badass/costumes/clown(E) (C) (-) 245 = /datum/uplink_item/badass/costumes(E) (C) (-) 246 = /datum/uplink_item/badass/balloon(E) (C) (-) 247 = /datum/uplink_item/badass/syndiebeer(E) (C) (-) 248 = /datum/uplink_item/badass/syndiecash(E) (C) (-) 249 = /datum/uplink_item/badass/syndiecards(E) (C) (-) 250 = /datum/uplink_item/badass/syndiecigs(E) (C) (-) 251 = /datum/uplink_item/badass

**Comment by park66665** [comment]
Another note; the item checking only works for the exact match of the type: subtypes of the said items don't automatically work unless they are also on the list. For example, `/obj/item/suppressor`, which is on the list, works, but `/obj/item/suppressor/specialoffer`, which is a subtype of `/obj/item/suppressor` but is not on the list, doesn't work.

The exact list of illegal technology-revealing items follows:
```
1 = /obj/item/storage/backpack/duffelbag/syndie/med/bioterrorbundle
2 = /obj/item/storage/backpack/duffelbag/syndie/bulldogbundle
3 = /obj/item/storage/backpack/duffelbag/syndie/c20rbundle
4 = /obj/item/storage/box/cyber_implants
5 = /obj/item/storage/backpack/duffelbag/syndie/med/medicalbundle
6 = /obj/item/storage/briefcase/sniperbundle
7 = /obj/item/storage/backpack/duffelbag/syndie/firestarter
8 = /obj/item/storage/box/syndicate/contract_kit
9 = /obj/item/storage/box/syndicate/bundle_A
10 = /obj/item/storage/box/syndicate/bundle_B
11 = /obj/structure/closet/crate
12 = /obj/effect/gibspawner/generic
13 = /obj/item/stack/telecrystal/five
14 = /obj/item/stack/telecrystal/twenty
15 = /obj/item/stack/telecrystal
16 = /obj/item/kitchen/knife/poison
17 = /obj/item/gun/ballistic/rocketlauncher
18 = /obj/item/gun/grenadelauncher
19 = /obj/item/pneumatic_cannon/pie/selfcharge
20 = /obj/item/shield/energy/bananium
21 = /obj/item/melee/transforming/energy/sword/bananium
22 = /obj/item/reagent_containers/spray/chemsprayer/bioterror
23 = /obj/item/storage/box/syndie_kit/throwing_weapons
24 = /obj/item/gun/ballistic/shotgun/bulldog
25 = /obj/item/gun/ballistic/automatic/c20r
26 = /obj/item/twohanded/required/chainsaw/energy/doom
27 = /obj/item/twohanded/dualsaber
28 = /obj/item/melee/transforming/energy/sword/saber
29 = /obj/item/shield/energy
30 = /obj/item/flamethrower/full/tank
31 = /obj/item/clothing/gloves/rapid
32 = /obj/item/guardiancreator/tech
33 = /obj/item/gun/ballistic/automatic/l6_saw
34 = /obj/item/gun/ballistic/automatic/m90
35 = /obj/item/melee/powerfist
36 = /obj/item/gun/ballistic/automatic/sniper_rifle/syndicate
37 = /obj/item/gun/ballistic/automatic/pistol
38 = /obj/item/gun/ballistic/rifle/boltaction
39 = /obj/item/gun/ballistic/revolver
40 = /obj/item/gun/ballistic/automatic/c20r/toy
41 = /obj/item/gun/ballistic/automatic/l6_saw/toy
42 = /obj/item/gun/ballistic/automatic/toy/pistol/riot
43 = /obj/item/sbeacondrop/semiautoturret
44 = /obj/item/sbeacondrop/heavylaserturret
45 = /obj/item/clothing/gloves/krav_maga/combatglovesplus
46 = /obj/item/book/granter/martial/cqc
47 = /obj/item/gun/syringe/syndicate
48 = /obj/item/toy/plush/carpplushie/dehy_carp
49 = /obj/item/pen/edagger
50 = /obj/item/book/granter/martial/karate
51 = /obj/item/book/granter/martial/carp
52 = /obj/item/gun/energy/kinetic_accelerator/crossbow/radbow
53 = /obj/item/gun/energy/kinetic_accelerator/crossbow
54 = /obj/item/storage/box/syndie_kit/origami_bundle
55 = /obj/item/storage/box/syndie_kit/chemical
56 = /obj/item/storage/box/syndie_kit/romerol
57 = /obj/item/pen/sleepy
58 = /obj/item/suppressor
59 = /obj/item/ammo_box/magazine/m10mm
60 = /obj/item/ammo_box/magazine/m10mm/ap
61 = /obj/item/ammo_box/magazine/m10mm/hp
62 = /obj/item/ammo_box/magazine/m10mm/fire
63 = /obj/item/storage/backpack/duffelbag/syndie/ammo/shotgun
64 = /obj/item/ammo_box/magazine/m12g
65 = /obj/item/ammo_box/magazine/m12g/dragon
66 = /obj/item/ammo_box/magazine/m12g/meteor
67 = /obj/item/ammo_box/magazine/m12g/slug
68 = /obj/item/ammo_box/magazine/m12g/breacher
69 = /obj/item/ammo_casing/a40mm
70 = /obj/item/storage/backpack/duffelbag/syndie/ammo/smg
71 = /obj/item/ammo_box/magazine/smgm45
72 = /obj/item/ammo_box/magazine/sniper_rounds
73 = /obj/item/ammo_box/magazine/sniper_rounds/penetrator
74 = /obj/item/ammo_box/magazine/sniper_rounds/soporific
75 = /obj/item/ammo_box/magazine/m556
76 = /obj/item/ammo_box/magazine/mm712x82
77 = /obj/item/ammo_box/magazine/mm712x82/ap
78 = /obj/item/ammo_box/magazine/mm712x82/hollow
79 = /obj/item/ammo_box/magazine/mm712x82/incen
80 = /obj/item/ammo_casing/caseless/rocket
81 = /obj/item/ammo_casing/caseless/rocket/hedp
82 = /obj/item/ammo_box/magazine/pistolm9mm
83 = /obj/item/storage/box/syndie_kit/bioterror
84 = /obj/item/ammo_box/a762
85 = /obj/item/grenade/chem_grenade/bioterrorfoam
86 = /obj/item/reagent_containers/food/snacks/grown/banana/bombanana
87 = /obj/item/storage/box/syndie_kit/bee_grenades
88 = /obj/item/grenade/plastic/c4
89 = /obj/item/storage/backpack/duffelbag/syndie/c4
90 = /obj/item/storage/backpack/duffelbag/syndie/x4
91 = /obj/item/sbeacondrop/clownbomb
92 = /obj/item/cartridge/virus/syndicate
93 = /obj/item/storage/box/syndie_kit/emp
94 = /obj/item/deployablemine/traitor
95 = /obj/item/doorCharge
96 = /obj/item/storage/box/syndie_kit/tuberculosisgrenade
97 = /obj/item/storage/belt/grenade/full
98 = /obj/item/deployablemine/traitor/bigboom
99 = /obj/item/pizzabox/bomb
100 = /obj/item/grenade/clusterbuster/soap
101 = /obj/item/sbeacondrop/bomb
102 = /obj/item/syndicatedetonator
103 = /obj/item/grenade/syndieminibomb
104 = /obj/item/grenade/chem_grenade/teargas/moustache
105 = /obj/item/grenade/spawnergrenade/manhacks
106 = /obj/item/flashbulb/bomb
107 = /obj/item/antag_spawner/nuke_ops/clown
108 = /obj/item/antag_spawner/nuke_ops/borg_tele/assault
109 = /obj/item/antag_spawner/nuke_ops/borg_tele/medical
110 = /obj/item/antag_spawner/nuke_ops/borg_tele/saboteur
111 = /obj/item/antag_spawner/nuke_ops
112 = /obj/mecha/combat/gygax/dark/loaded
113 = /obj/mecha/combat/honker/dark/loaded
114 = /obj/mecha/combat/marauder/mauler/loaded
115 = /obj/item/card/id/syndicate
116 = /obj/item/multitool/ai_detect
117 = /obj/item/storage/box/syndie_kit/chameleon
118 = /obj/item/chameleon
119 = /obj/item/codespeak_manual/unlimited
120 = /obj/item/clothing/shoes/clown_shoes/banana_shoes/combat
121 = /obj/item/clothing/shoes/clown_shoes/taeclowndo
122 = /obj/item/flashlight/emp
123 = /obj/item/reagent_containers/syringe/mulligan
124 = /obj/item/clothing/shoes/chameleon/noslip
125 = /obj/item/radio/headset/chameleon/bowman
126 = /obj/item/clothing/glasses/chameleon/flashproof
127 = /obj/item/clothing/gloves/chameleon/combat
128 = /obj/item/jammer
129 = /obj/item/storage/backpack/satchel/flat/with_tools
130 = /obj/item/storage/box/syndie_kit/space
131 = /obj/item/clothing/suit/space/hardsuit/syndi/elite
132 = /obj/item/clothing/suit/space/hardsuit/shielded/syndi
133 = /obj/item/clothing/suit/space/hardsuit/syndi
134 = /obj/item/storage/box/syndie_kit/cutouts
135 = /obj/item/assault_pod
136 = /obj/item/encryptionkey/binary
137 = /obj/item/compressionkit
138 = /obj/item/clothing/shoes/magboots/syndie
139 = /obj/item/disk/surgery/brainwashing
140 = /obj/item/storage/briefcase/launchpad
141 = /obj/item/camera_bug
142 = /obj/item/storage/belt/military
143 = /obj/item/card/emag
144 = /obj/item/disk/nuclear/fake
145 = /obj/item/storage/box/syndie_kit/teleporter
146 = /obj/item/cartridge/virus/frame
147 = /obj/item/storage/toolbox/syndicate
148 = /obj/item/syndie_glue
149 = /obj/item/aiModule/syndicate
150 = /obj/item/assembly/flash/hypnotic
151 = /obj/item/gun/medbeam
152 = /obj/item/sbeacondrop
153 = /obj/item/powersink
154 = /obj/item/reagent_containers/hypospray/medipen/pumpup
155 = /obj/item/storage/firstaid/tactical
156 = /obj/item/soap/syndie
157 = /obj/item/storage/backpack/duffelbag/syndie/surgery
158 = /obj/item/encryptionkey/syndicate
159 = /obj/item/storage/book/bible/syndicate
160 = /obj/item/slimepotion/slime/sentience/nuclear
161 = /obj/item/suspiciousphone
162 = /obj/item/clothing/glasses/thermal/syndi
163 = /obj/item/storage/box/syndie_kit/imp_adrenal
164 = /obj/item/autosurgeon/syndicate/anti_stun
165 = /obj/item/storage/box/syndie_kit/imp_freedom
166 = /obj/item/storage/box/syndie_kit/imp_microbomb
167 = /obj/item/storage/box/syndie_kit/imp_macrobomb
168 = /obj/item/storage/box/syndie_kit/imp_radio
169 = /obj/item/autosurgeon/syndicate/reviver
170 = /obj/item/storage/box/syndie_kit/imp_stealth
171 = /obj/item/storage/box/syndie_kit/imp_storage
172 = /obj/item/autosurgeon/syndicate/thermal_eyes
173 = /obj/item/storage/box/syndie_kit/imp_uplink
174 = /obj/item/autosurgeon/syndicate/xray_eyes
175 = /obj/item/flashlight/lantern/syndicate
176 = /obj/item/grenade/discogrenade
177 = /obj/item/storage/box/syndie_kit/plasmachameleon
178 = /obj/item/book/granter/martial/tribal_claw
179 = /obj/item/clothing/under/color/grey/glorf
180 = /obj/item/storage/toolbox/mechanical/old/clean
181 = /obj/item/gun/blastcannon
182 = /obj/item/clothing/shoes/magboots/crushing
183 = /obj/item/storage/box/gorillacubes
184 = /obj/item/healthanalyzer/rad_laser
185 = /obj/item/mmi/syndie
186 = /obj/item/upgradewand
187 = /obj/item/grenade/spawnergrenade/clown
188 = /obj/item/grenade/spawnergrenade/clown_broken
189 = /obj/item/reagent_containers/syringe/spider_extract
190 = /obj/vehicle/sealed/car/clowncar
191 = /obj/item/veilrender/honkrender/honkhulkrender
192 = /obj/item/mecha_parts/concealed_weapon_bay
193 = /obj/item/toy/eightball/haunted
194 = /obj/item/his_grace
195 = /obj/item/storage/box/syndie_kit/cultconstructkit
196 = /obj/item/reagent_containers/glass/bottle/fluspanish
197 = /obj/item/reagent_containers/glass/bottle/retrovirus
198 = /obj/item/reagent_containers/glass/bottle/random_virus
199 = /obj/item/reagent_containers/glass/bottle/anxiety
200 = /obj/item/hot_potato/syndicate
201 = /obj/item/twohanded/required/chainsaw/energy
202 = /obj/item/guardiancreator/carp
203 = /obj/item/storage/box/syndie_kit/ez_clean
204 = /obj/item/storage/box/syndie_kit/mimery
205 = /obj/item/borg/upgrade/modkit/indoors
206 = /obj/item/autosurgeon/syndicate/esaw_arm
207 = /obj/item/reagent_containers/hypospray/medipen/magillitis
208 = /obj/item/gun/syringe/dna
209 = /obj/item/gun/chem
210 = /obj/item/reverse_bear_trap
211 = /obj/item/storage/box/hug/reverse_revolver
212 = /obj/item/autosurgeon/syndicate/laser_arm
213 = /obj/item/storage/box/syndie_kit/chameleon/broken
214 = /obj/item/storage/box/syndie_kit/centcom_costume
215 = /obj/item/storage/backpack/duffelbag/clown/syndie
216 = /obj/item/storage/secure/briefcase/syndie
217 = /obj/item/toy/cards/deck/syndicate 
```

**Comment by Rukofamicom** [comment]
@bloons3 Going to ask a probably obvious question, but I would like a serious answer:

Why do we care if illegal tech has tricks that let you research it? What specific items require illegal tech that it should be more than just an end-of-techweb node?

Should it be restricted to exclusively antagonist weaponry, or should certain non-antagonist tricks still work?
