### ISSUE TITLE
Movement Problem

### ISSUE THREAD

**Issue by Pill-U** [BeeStation/BeeStation-Hornet#376]
Issue reported from  Round ID: 6586 (BeeStation - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 512.1478

I seemingly randomly start moving in a direction and can sometimes counteract this by moving in the opposite direction and sometimes I just straight up can't do anything against it. Changing Servers, reinstalling Byond, closing background programs and unplugging my keyboard does nothing, but the problem seems to disappear after an hour or two. I also noticed that I do not move while having the text menu open, I alt tab to another program or while the game is closed.

**Comment by qwertyquerty** [comment]
Sounds like an issue with your PC and not our code
