### ISSUE TITLE
firelock timings

### ISSUE THREAD

**Issue by Emiliapains** [BeeStation/BeeStation-Hornet#3761]
to increase the timings for firelocks cause you legit cant pass when your critted

**Comment by MNarath1** [comment]
has nothing to do with the timing that was already an issue before cause firelocks never properly disengage when you open them that way

**Comment by MNarath1** [comment]
another reason why the new firelocks are shit yes old blocked you entirely but at least you knew that you are in a deathtrap and don't spend 5 minutes trying

**Comment by francinum** [comment]
Fastmos was a mistake.
