### ISSUE TITLE
IPC screen

### ISSUE THREAD

**Issue by Ambulo-gif** [BeeStation/BeeStation-Hornet#3768]
Problem Description: Winter coat and ipc screen bug

When wearing winter coat hood while having "drone eyes" ipc screen makes your screen return to previous chosen ipc screen you've played. Once your winter coat hood is removed ipc screen goes back to "drones eyes" screen.

**Comment by eris-webserv** [comment]
probelm
P A I N

**Comment by KubeRoot** [comment]
"drone eyes" is not a screen, it's an antenna, and antennas are covered by hoods and helmets (`HIDEHAIR|HIDEEARS`) since most of them go upwards. Seems like it counts as hair, specifically.

One way or another, not a bug, probably an oversight though.
