### ISSUE TITLE
Abductors can no longer teleport 

### ISSUE THREAD

**Issue by Crossedfall** [BeeStation/BeeStation-Hornet#3813]
## Reproduction:

1. Be an ayy
2. Try to send yourself or others to a location

https://github.com/BeeStation/BeeStation-Hornet/pull/3662 is most likely the cause

**Comment by park66665** [comment]
In a nutshell, `/area/abductor_ship`'s `noteleport` is true, which blocks teleports both to and fro; `do_teleport` checks both of current and destination area's `noteleport`.

**Comment by PowerfulBacon** [comment]
fixed by some PR I made
