### ISSUE TITLE
Bounty: Give Acting Captain Access to Captain Quarters (35$)

### ISSUE THREAD

**Issue by leestriter** [BeeStation/BeeStation-Hornet#3832]
If the new rule set is going to require the Acting Captain get the spare ID and nuke disc before the riders, the code should reflect those rules and give the acting captain access to do so. Right now acting captain needs to be excellent at breaking and entering, that has little to do with managing the station and running their chosen department. Let's make the code base reflect the rules.

**Comment by leestriter** [comment]
https://www.bountysource.com/issues/96975350-acting-captain-needs-access-to-captain-s-quarters

**Comment by MNarath1** [comment]
Might as well call dibs on it i cannot say when i get time to do so but probably around the weekend/end of the week.

**Comment by PowerfulBacon** [comment]
Order of COC?
What happens if there are no heads?
What about when the new captain arrives?

**Comment by bloons3** [comment]
Might be worth basing this off of TG's acting captain:

https://github.com/tgstation/tgstation/pull/56910

https://github.com/tgstation/tgstation/pull/57460

_Captain’s Spare ID - Now kept on the bridge in a safe. The Captain spawns with a piece of paper containing the code to this safe. If there’s no captain, it falls to the chain of command from HoP at the top through to QM at the bottom. This roughly follows Chain of Command - /tg/station 13 Wiki with creative freedom for where the CE and CMO are placed.

The safe for the Captain’s spare is impervious to ordinary weaponry. It cannot be hacked. It’s immune to melee, bullets, lasers and energy weapons. It is weak to explosions and can be corroded with acid. Its description hints at these two weaknesses. Players may find other creative ways to open it outside of these intended weaknesses._

**Comment by MNarath1** [comment]
> Order of COC?
> 
A priority list that will choose an appropriate head if one is there on roundstart if not will go down the list:Possible Order:
HOP,HOS,RD,CE,CMO
> What happens if there are no heads?
> 
Choose the next head that arrives on the station.
> What about when the new captain arrives?

Either remove the access after a certain time code wise(so you don't suddenly get stuck behind an airlock) or handle it trough normal COC conduct.
I think the second option is here better after all cause editing the access just cause a certain job arrived is a bit overboard and could mess other things up.

**Comment by MNarath1** [comment]
Well thats a crude draft of the plan

**Comment by bloons3** [comment]
> Well thats a crude draft of the plan

Is the Acting Head's ID automagically modified to have captain perms, or do they just get given access to the spare?

**Comment by MNarath1** [comment]
> > Well thats a crude draft of the plan
> 
> 
> 
> Is the Acting Head's ID automagically modified to have captain perms, or do they just get given access to the spare?

Well as acting captain he will get that access anyways trough the id but if he would get cap level access i would need to think of a better way for when the actual captain arrives maybe something involving the keycard auth hmm.

**Comment by bloons3** [comment]
Basically you want someone to be able to _choose_ to be the captain (priority to heads of staff), but also give them an advantage to become the Captain ahead of a tider with insulated gloves or thermite.

**Comment by leestriter** [comment]
> Basically you want someone to be able to _choose_ to be the captain (priority to heads of staff), but also give them an advantage to become the Captain ahead of a tider with insulated gloves or thermite.

My thinking was, only heads of staff. This is because the rules say the acting captain (who I believe is currently selected from head of staff if available) must secure the disc and spare ID. This PR is intended to make it easier for them then a tider.. If there are no heads, the round goes on as normal (unless there are ways to declare an acting captain I am unfamiliar with).

Currently heads do not choose to be acting captain. I did not intend to change that, only to give the acting captain access to the spare and nuke disc roundstart without using thermite and shit like that.

**Comment by leestriter** [comment]
> > Well thats a crude draft of the plan
> 
> Is the Acting Head's ID automagically modified to have captain perms, or do they just get given access to the spare?

I think they just need access to the captain's quarters to get the nuke disc and spare. They can then use the spare until a real captain arrives in order to function as captain.

**Comment by bloons3** [comment]
> > > Well thats a crude draft of the plan
> > 
> > 
> > Is the Acting Head's ID automagically modified to have captain perms, or do they just get given access to the spare?
> 
> I think they just need access to the captain's quarters to get the nuke disc and spare. They can then use the spare until a real captain arrives in order to function as captain.

If the goal is to give heads of staff easy access to the captain's spare, then it would probably be better to move the spare to the bridge where the heads of staff already have access to and gate it behind a code that heads of staff are given to their mind so long as they are not job banned from Captain.

The spare ID could still be stolen with enough effort, but the heads of staff have easy and immediate access to it at the start of the round, but they are not forced to become Captain if they do not wish to.

**Comment by leestriter** [comment]
> > > > Well thats a crude draft of the plan
> > > 
> > > 
> > > Is the Acting Head's ID automagically modified to have captain perms, or do they just get given access to the spare?
> > 
> > 
> > I think they just need access to the captain's quarters to get the nuke disc and spare. They can then use the spare until a real captain arrives in order to function as captain.
> 
> If the goal is to give heads of staff easy access to the captain's spare, then it would probably be better to move the spare to the bridge where the heads of staff already have access to and gate it behind a code that heads of staff are given to their mind so long as they are not job banned from Captain.
> 
> The spare ID could still be stolen with enough effort, but the heads of staff have easy and immediate access to it at the start of the round, but they are not forced to become Captain if they do not wish to.

That would work fine for me, I just thought the access would be easier to code. I only really care about the end effect here for people who didn't expect to play captain when they sign up as a different head role, to let them fulfill their responsibilities without unnecessary BS and racing a bunch of assistants.

As for the last part, aren't heads already forced into acting captain even if they don't wish to be? If you are the only head or the highest in CoC? As far as I know the only person who picks to play captain is, well, whoever actually picks captain. But any head can end up acting captain if they have the most current authority, whether they want it or not. For instance the round that inspired this I was CMO acting captain.

**Comment by bloons3** [comment]
https://github.com/BeeStation/BeeStation-Hornet/blob/d898aa7889214360c6f162f14f59266f4b287258/code/controllers/subsystem/ticker.dm#L390

**Comment by leestriter** [comment]
I've seen it say captainship not forced on anyone, assumed it meant when there were no heads at all (but never thought much of it).

**Comment by bloons3** [comment]
I would have an issue with a system that forced captainship onto someone, even if temporarily.
I would support a system that makes it easier for a Head of Staff to become Acting Captain if they wish to be.

**Comment by leestriter** [comment]
> I would have an issue with a system that forced captainship onto someone, even if temporarily.
> I would support a system that makes it easier for a Head of Staff to become Acting Captain if they wish to be.

I was under the impression captainship was forced. When I was the only head I was told I was acting captain and had to get the disk and I'd, I dont recall a prompt or any sort of choice for me so I'm confused.

**Comment by leestriter** [comment]
Is the highest ranking head forced to be acting captain or nah? I swear ruko said as the only head online I had to be acting captain, which suggests someone has to do it. But that's not a conversation for githhub.

**Comment by leestriter** [comment]
Reading the rules I figured out the confusion. It seems acting captain isnt forced on you, but heads have to secure the disk/spare id. That is still overly difficult for an acting cap or normal head of staff when there is no cap. Which still, I want to make that easier for the heads to do. Bloons method sounds solid.

**Comment by Archanial** [comment]
I can do this, should be pretty straight forward

**Comment by MNarath1** [comment]
> I can do this, should be pretty straight forward 

You doing this now or not i literally would not have time to work on this before weekend so you are free to take it.

**Comment by Archanial** [comment]
I am doing it now

**Comment by leestriter** [comment]
How do I give archanial the bounty?

**Comment by bloons3** [comment]
If you did the bounty through bounty source, there is a process.

otherwise you should be able to send the money directly to them through PayPal or some other method.

**Comment by leestriter** [comment]
I did it through bountysource. Let me know the preferred way to do future bounties.

**Comment by leestriter** [comment]
Sorry about closing the issue for a bit I did not understand bountysource at that time.

**Comment by MNarath1** [comment]
Bounty source takes 10% of the bounty i think

**Comment by leestriter** [comment]
> Bounty source takes 10% of the bounty i think

Yeah, and that's why I won't use bountysource in the future, but I used it for this so everyone knows the money will be paid.

**Comment by leestriter** [comment]
Sorry for closing and reopening so much, trying to learn bounty source. I think the solution has to be merged before bountysource pays out, which is stupid.
