### ISSUE TITLE
Invisible toma?

### ISSUE THREAD

**Issue by JackieOTheWisp** [BeeStation/BeeStation-Hornet#3858]
Issue reported from  Round ID: 27799 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542

So first I chucked a toma into a plasma chamber with an igniter. It had gotten husked by the time I grabbed it. Then I put the burning body under a freezing shower and the corpse became invisible. So I decided to see if this would work with living ones. Luckily, it does not seem to.

![image](https://user-images.githubusercontent.com/68827851/110727850-fb651180-81e9-11eb-873d-1a5926cbbb87.png)

**Comment by JackieOTheWisp** [comment]
This does not happen to monkeys. Strange considering tomas are a monkey subtype honestly
![image](https://user-images.githubusercontent.com/68827851/110728848-b641df00-81eb-11eb-8cdc-e5fbacdb5ca6.png)

**Comment by JackieOTheWisp** [comment]
This does however, also work with a fire extinguisher rather than a shower.

**Comment by JackieOTheWisp** [comment]
Research suggests it has something to do with husking

**Comment by St0rmC4st3r** [comment]
Probably with teratomas not having a husked icon?

**Comment by FlamePrince** [comment]
> 
> 
> Probably with teratomas not having a husked icon?

https://gyazo.com/e44022c15182f1649f9d8d5b25d8a4c0

right on the money. code's all there for a teratoma_husk_chest etc but no icon to go with it. all that needs to happen is for someone to sprite and add teratoma_husk limbs to animalparts.dmi. placeholder would be to copy monkey_husk limbs and rename them to teratoma_husk limbs

[animal_parts.zip](https://github.com/BeeStation/BeeStation-Hornet/files/6225438/animal_parts.zip)

**Comment by FlamePrince** [comment]
@zeskorion
