### ISSUE TITLE
Feature Req.: SSD at round start

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#386]
a) AFK detected sooner in all cases
b) players that go afk before 5 minutes teleport to arrival shuttle 
c) their jobs revert to assistant so new players can sign up as xjob

I'm making this because mining is retarded and I get 2/3 SSD miners at round start, fucking robo, fucking sci

**Comment by ike709** [comment]
This is a long-winded way of saying "port oracle's cryopods". Which I am in favor of.

**Comment by jlsnow301** [comment]
I've never seen them, but yeah, shit sux

**Comment by qwertyquerty** [comment]
I might make this a bounty, good ideas very good ideas

**Comment by jlsnow301** [comment]
I am looking at code now. Would you want it to just be an exact port? I wouldn't mind a (simpler) system where it waits a few minutes then:
- ports them to arrivals
- jobchanges them to assistant
- message: You've been demoted!
- opens job back up to select
- wait another 5 minutes
- ghost them as they "returned to hq"

Another option:
- Set arrivals area to have this 5 minute individual timer to despawn players ("return to HQ") so it will despawn anyone that entered the game but never left arrivals, AND the players that are ported there after being afk elsewhere. Two birds one stone

**Comment by ike709** [comment]
Or you could just... port cryopods... which handles this in an elegant way that also doesn't ruin immersion.

**Comment by jlsnow301** [comment]
Porting
