### ISSUE TITLE
Dynamic: Revs holding the round hostage

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#3863]
Dynamic revs does not end then the heads of staff are exiled or killed off.

## Reproduction:

1. Spawn revs on dynamic
2. Kill heads
3. Round doesn't end and the shuttle is locked, preventing it from leaving and ending the round

**Comment by bloons3** [comment]
Might be useful: https://github.com/tgstation/tgstation/pull/55956
