### ISSUE TITLE
IPCs should not be rad immune

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#3873]
This is not merely a suggestion to nerf IPCs because I think they are unbalanced. I play IPC.
Circuitry is literally affected by radiation and IPCs are walking TVs. It's implausible that they are not affected by rads.

**Comment by leestriter** [comment]
Do you think rads should affect borgs?

**Comment by jlsnow301** [comment]
> Do you think rads should affect borgs?

Good question. I suppose so?

**Comment by TeomanTheGreat** [comment]
Make it so rads deal brain damage to IPCs because their circuitry and shit are being messed up from the rads.

**Comment by leestriter** [comment]
I mean you can build machines with like, lead lining and shit to protect the internal stuff. I will say, if we get rid of immunity for ipcs we should do the same for borgs.

**Comment by bloons3** [comment]
> I mean you can build machines with like, lead lining and shit to protect the internal stuff. I will say, if we get rid of immunity for ipcs we should do the same for borgs.

Playing as a borg is enough of a punishment

**Comment by ZombiesVsPlants** [comment]
borgs aren't immune to rad burn i.e they'll cook alive if they're around rads.

**Comment by jlsnow301** [comment]
> I mean you can build machines with like, lead lining and shit to protect the internal stuff. I will say, if we get rid of immunity for ipcs we should do the same for borgs.

Lead would offer some protection but they would still get shredded standing near the sm or similar

**Comment by FlamePrince** [comment]
Given that no circuitry is affected by radiation ingame afaik, it would be suffice to say that they've come up with radiation-proof circuits. On the topic of IPC being op, though, there's definitely some balancing issues.

**Comment by jlsnow301** [comment]
> Given that no circuitry is affected by radiation ingame afaik, it would be suffice to say that they've come up with radiation-proof circuits. 

Seems so. I don't think that it would really hurt to change it so circuitry would be affected in a radius with increasing rads. This effect is already sort of mimicked by the singulo, which emp's everything in a distance.

> On the topic of IPC being op, though, there's definitely some balancing issues.

I'm trying to dodge that topic hah. Their trade offs are often the agonizing process of being dragged to medbay. I think trying to clone IPCs should blow the scanner with the force of a meth lab. Balance and justice

**Comment by PowerfulBacon** [comment]
Feel free to work on this, NSV has a pretty good solution.
