### ISSUE TITLE
Fly People Move Speed Is Too Slow

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#3875]
## Round ID:
Any

## Testmerges:
Any

## Reproduction:
Fly people were intended to move faster than your average person but take more damage. They now walk slower and take more damage, making playing a fly pretty lame.

**Comment by Pontenerd** [comment]
Isn't the whole point of flypeople being genetic fuckups

**Comment by jlsnow301** [comment]
> Isn't the whole point of flypeople being genetic fuckups

Not sure about their lore but I feel it's a bit thematic for a fly to be fast

**Comment by OceanFish1** [comment]
> Isn't the whole point of flypeople being genetic fuckups

I mean if you fuck up with teleport calibration you're meant to become a genetic fuckup

**Comment by Rukofamicom** [comment]
Flypeople are a meme race borne from teleportation failures. They don't need any mechanical advantages.

**Comment by jlsnow301** [comment]
> Flypeople are a meme race borne from teleportation failures. They don't need any mechanical advantages.

~~let's double it then~~
wait wait no let's give them default paraplegic trait
