### ISSUE TITLE
Wizard Item Renaming Spell Bugs

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#3882]
## Round ID:
Any

## Testmerges:
Any

## Reproduction:
Wizard's spell that renames items around the station also renames components, one by one, thus they are no longer stackable. This results in RPEDs with a gargantuan list of individual components.
While funny, it's probably also not great for the server to rename stacking items like this, and a big surprise for anyone that alt-clicks an rped to view contents

**Comment by Lautarourtiaga** [comment]
Started working on this issue xD

**Comment by Lautarourtiaga** [comment]
Check the pr out when you can!
