### ISSUE TITLE
Clockcult: Wardens can't be unwrenched and repositioned

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#3901]
Title, you used to be able to reposition these with a wrench. If you misplace a warden the only way to correct your mistake is to destroy it.

**Comment by PowerfulBacon** [comment]
Intentional due to wardens not being able to be placed too close to each other.

**Comment by PowerfulBacon** [comment]
Also they aren't the same as other gear based structures
