### ISSUE TITLE
Heretic Rifts not showing up for all heretics.

### ISSUE THREAD

**Issue by heepox** [BeeStation/BeeStation-Hornet#3911]
## Reproduction: 
Have a bunch of heretics looking for rifts. some will see them some wont see them where other see them.
sometimes a heretic will never see an unclaimed rift anywhere for some reason.

**Comment by Archanial** [comment]
Was this heretic admin spawned?

**Comment by Cenrus** [comment]
I should mention that this is an issue on /tg/ too

**Comment by heepox** [comment]
> Was this heretic admin spawned?

no it was me normal round start heretic and I checked every nook and cranny on the station, including AI sat, solars, permabrig, armory, toxins test site, SM, all the storages, AI upload and all of maint. Had to sacrifice 6 people without a single rift, but no other heretics even managed 1 sac so its actyally pretty bad if it happens to someone less robust than me.
