### ISSUE TITLE
Medical Cryopod Rework ($40 Bounty)

### ISSUE THREAD

**Issue by Rukofamicom** [BeeStation/BeeStation-Hornet#3921]
Forum discussion here: https://forums.beestation13.com/t/medical-cryopod-rework-bounty/11897

### Bounty payout details:
* $40, payable via Steam or PayPal preferably. (Price and platform Negotiable)
* Will pay for finished code even if not merged on Bee

### Machine specs and info:
* **Machine functions like a fusion between current cryopod/sleepers, as a resource efficient chemical treatment machine, but no longer *infinite* chem treatment machine**
  * Machines require reagents to be manually added, but may accept any reagents instead of being restricted to only select medicines. Roundstart machines should have a crate near them with assorted bottles of basic medical reagents (detailed further down)
  * Sleeping patients (either drugged or cryo) inside of the pod will receive boosted chemical efficiency based on the machine's part upgrades. *This gives an actual, functional use for morphine, even if somewhat marginal compared to cryo-mode*
  * "Cryo-mode" is a feature that can be toggled anytime the machine is stocked with Cryoxadone. While this is active, patients are put to sleep, then chilled and constantly micro-dosed (add 1u any tick that less than 3u is present in patient) with Cryoxadone until the machine ejects the patient. Cryo-mode automatically disables when the machine runs out of Cryoxadone, which will also allow the patient to wake up.
  * "Auto Eject" will dump patients (unceremoniously on the floor if unconscious) out of the machine when their health is full, just like current cryopods. 
  * Patients may exit the machine at any time if they are conscious - there is no locking function on the machine so intentional entrapment will be at least somewhat difficult. Naturally patients may only be injected with chems after being closed in the machine as well. 
  * Does not require the arbitrary atmos setup that current cryopods do to function - just needs to be loaded with chemicals and be in a powered room. 
  * When emagged, Cryo-mode will operate without injecting or requiring any cryoxadone, slowly killing the patient via freezing and ejecting their corpse after they have died. Additionally, trying to inject any chems into a patient will result in a 50/50 chance of attempting to add 30u or destroying 30u of a randomly selected chem. 

* **Three part UI**
  * Control buttons for: Initiate Cryo-mode, Auto-eject (On/Off), Open/Close, 
  * Display patient's vitals and current reagents (like sleepers currently do)
  * Display currently stored reagents in a way similar to ChemMaster3000 - Buttons for dosing at 1, 5, 10u (and an X which will destroy 10u of that reagent)

* **Stock Parts:**
  * Four beakers - maximum reagent storage (200u roundstart, 1200u max upgrades)
  * One Manipulator - Controls reagent efficiency while patients are asleep. 25% Boost at T1 and 70% at T4 with a linear upgrade path (25, 40, 55, 70)
  * One Scanning Module - Controls how quickly cryo-mode puts patients to sleep, should not be instantaneous at T4 to prevent easily weaponizing the machine. 
  * One Micro Laser - Controls how quickly cryo-mode chills patients, being near instantaneous at T4. 
  * The difference between T1 and T4 Scanning Modules/Micro Lasers should be noticeable but not huge. The total initiation process should not feel especially sluggish with T1 parts. 

### Other changes to include in the PR:
* Cargo: Add a somewhat pricey "Cryo-chem crate" to the medical tab. It should contain:
  * 2 Bottles of Cryoxadone
  * 1 Bottle of Morphine
  * 1 Bottle of Bicaridine
  * 1 Bottle of Kelotane
  * 1 Bottle of Epinephrine
  * 1 Bottle of Charcoal
* Mapping: Replace all sleepers with stasis beds in all station medbays
* Mapping: Remove unnecessary atmos leftovers from old cryopods (O2 canister, atmos piping and freezer) from all medbays
* Mapping: Replace the glass table with four, partially filled beakers of cryoxadone with a Cryo-Chem Crate that has double the stock of the ones you order from Cargo (since there are two pods to fill)
* Other: Make sleeper  circuit boards unobtainable via conventional means

**Comment by Archanial** [comment]
Doesn't sound bad, I'll do it.

**Comment by KubeRoot** [comment]
Should this issue still be open with the PR implementing this being rejected?
