### ISSUE TITLE
Feature Req: New Tech, Space Mining

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#393]
New tech branch, only one or the other: Mining Tech OR Space Mining
ie: Well if there's no fucking miners, let's make the station mine nearby asteroids instead.
Researching this reds out mining tech level 1 and all mining tech afterwards but provides a steady, slow income of all materials with modifier:

Iron: 1
Glass: 1
Copper: 0.7
Silver: 0.7
Gold: 0.7
Plasma: 0.5
Titanium: 0.3
Uranium: 0.3
Diamond: 0.1
Bluespace: 0.1

Tickrate: Trickling in at what one brand new miner would provide
Point of this research: Mining is dead every game and I play robo :(

**Comment by prophed** [comment]
This is a great idea, as an engi it triggers me when someone else AKA SCIENCE takes all the metal and most (or not all) miners are dead. But I feel like removing the mining tech to balanced is a little too much, for people that switch jobs to miners are fucked. 
Maybe make more leaves of the brand space mining, starts super fucking slow but you can keep upgrading it to a reasonable amount.

**Comment by Toxici11i** [comment]
you literally want us to port /vg/ mining i guess

**Comment by jlsnow301** [comment]
I've never played vg, but I like their tetris research, tbh

This is a way to fuck mining if they're shit, rather than just 2+ departments getting fucked by mining.  If you researched it WITH miners, it stunts both of you in the process. 
If you fully research mining and they die, you bet on the wrong horse as you can't get space mining.
Literally 2 or just 1 competent miner would bring in more than space mining, so it would require a little communication before making the decision.

It's a niche but can come in handy when they're all dead (USUALLY ARE)
