### ISSUE TITLE
Teleport pilon

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#3932]
Issue reported from  Round ID: 28076 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542
I made a bounch of teleport pilons inside rainbow pilons, at first they worked well but at the end of the round they started teleporting me to random locations.

**Comment by Rukofamicom** [comment]
Bag of holding?

**Comment by Mails-z** [comment]
No, teleport pilons are a xenobiology thing, you can make rainbow pilons and add to them other pilons to get several efects.

**Comment by Mat05usz** [comment]
> No, teleport pilons are a xenobiology thing, you can make rainbow pilons and add to them other pilons to get several efects.

What Ruko meant is that maybe you had Bag of Holding on your back, it messes up with all kinds of teleporters (basically teleporting you to a random spot) and probably with the pylon too.

**Comment by PowerfulBacon** [comment]
Pretty sure if the location of the pylon changes, the teleport point goes to the old location causing it to break on shuttles.
