### ISSUE TITLE
Oh god oh fuck you can filter evade with renaming potions

### ISSUE THREAD

**Issue by RDS88-beeman** [BeeStation/BeeStation-Hornet#3938]
## Round ID:
28107

## Testmerges:
Server revision compiled on: 2021-03-21T13:40:12+00:00
Master commit: c77d28839106339a25b33f308c09340baf5e5d8f
The following pull requests are currently test merged:
#3906: 'fixes ex_act being called multiple times on the same items, thus destroying it in any explosion strengths' by jupyterkat at commit 6a0f52cbf4
#3879: 'Stat panel updates' by PowerfulBacon at commit edbe04da3b
#2929: 'Stamina Healing Improvements' by PowerfulBacon at commit c3df718cf0

## Reproduction:
Step one: Say Sussus Amogus
Step two: Take note that Amogus is filtered
Step three: Use a renaming potion on yourself, and name yourself Amogus
Step four (optional): Panic

**Comment by ike709** [comment]
Fixed

**Comment by OceanFish1** [comment]
Sussus Amogus
