### ISSUE TITLE
Feature Req.: IPC Changes

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#395]
Changes I'd like to see:
a) IPC's not visible by medbots. No, inspector johnson, I will not show for mandatory penis inspection.
b) IPC's have blood, and it reads as 5W30. You can withdraw/inject Oil with syringe, and they bleed black blood decals at a VERY reduced rate, but this (in my opinion) shouldn't be able to be slipped on or else medbay would be retarded. more retarded, anyway.
c) Blood deficiency perk affects IPCs (low oil)
d) Low blood applies speedmod

**Comment by jlsnow301** [comment]
a is complete

**Comment by SomeAngryMiner** [comment]
should mark this as resolved.

**Comment by jlsnow301** [comment]
Dpme
