### ISSUE TITLE
Vision obscuring overlay occasionally fails to load

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#3952]
<h1>Meta Info:</h1>
Issue reported from  Round ID: 28143 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542
<h1>Issue:</h1>
In rare cases, the vision obscuring overlay from being blind, wearing a blindfold, a welding mask and so on fails to activate, giving the player perfect vision as seen below.<br><br>

In this particular instance , the blind trait itself DID work, and I was unable to examine things around my character but resetting the trait, restarting the client and even removing the eyes organ entirely didn't bring the overlay back.

![image](https://user-images.githubusercontent.com/29107291/112141957-ae683e80-8bde-11eb-8169-3e181c402bee.png)
<h1>Reproduction:</h1>
Uncertain, it was suggested long continuous playtime might be a potential cause.

**Comment by MNarath1** [comment]
I would ask you first to clear your byond cache as it is basically 90% of the times the cause for problems like this.

**Comment by Pirill** [comment]
> I would ask you first to clear your byond catch as it is basically 90% of the times the cause for problems like this.

I can certainly try that and report results but seeing as this only happens rarely, it might take a while to see if it comes up again.

**Comment by heepox** [comment]
this happens regularly when I play for a long time. I will no longer have vision obstructions...
usually after 6 or 8 rounds.
