### ISSUE TITLE
Prostonic Mech

### ISSUE THREAD

**Issue by nameacow** [BeeStation/BeeStation-Hornet#3976]
Issue reported from  Round ID: 28259 (BeeStation Sage - Roleplay)

Reporting client version: 513.1541

Not alot of issue but more want. When you but a Prostonic Brain inside of a mech, the brain cannot interfact with doors, or anything for that matter but walk around and exist.

**Comment by bloons3** [comment]
Are they able to walk into doors to activate them?

**Comment by nameacow** [comment]
It activates them, but you have no acsess.

**Comment by nameacow** [comment]
Also by interact, I meant by how borgs can interact by clicking on them from a distance.

**Comment by bloons3** [comment]
That is intentional

**Comment by aidan-bowman** [comment]
they're not borgs, they're mechs, they obviously wouldn't have the same abilities

**Comment by nameacow** [comment]
I know, I'm just saying it would be nice to open doors. Afterall, when you put a brain into a mech it's pretty much the same has the borg. I can see your reason, on how they are different, but they are both still AI's. So there is still logical reason to why both mech brains and borgs would have access to said interfaces and doors.

**Comment by St0rmC4st3r** [comment]
If you want door access on mechs - you gotta upload it first. I don't remember how exactly is it done, but it is the intended way.

**Comment by Megaddd** [comment]
you slap the mech with an ID (or PDA+ID) and access ID panel to set the door access rights it can bump through
