### ISSUE TITLE
Feature Req: Clockwork Cult MASSIVE Rework

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#398]
Clock Cult Premise:

Clock cult is not announced to the station
The entire building area for tower defense is REMOVED
Culties determine where to individually teleport in
Culties can purchase some spells using power, nothing lethal though
Culties are tasked with infiltrating ship and stealing power. This includes:
- stealing charged battery cells
- hacking mech/cyborg recharge stations
- abducting IPC's, cyborgs, entire mechs, or the AI core
- building structures that leech the power grid of the station
- Hacking SM controls to reroute power (pro gamer move)

Purchasing equipment reduces total power stolen so it's a tradeoff. However, the cult leader is able to start summoning Ratvar any time after 15 minutes, this ritual takes 10 minutes to complete. After 30 minutes, this ritual starts automatically.

**The fun part:**
Ratvar's size is dependent on the amount of power stolen. There is NO tower defense part to this. At certain power thresholds, he is able to summon clockwork minions, otherwise he can be just as big as a chlown (if the team literally did nothing). He is entirely stoppable at MOST sizes. But, with a robust team, he shows early, huge, and fucks the station.
 
Why this is good for the game:
Clockwork Cult, as is, is a poorly implemented and complicated game mode that is entirely anticlimactic

**Comment by Toxici11i** [comment]
So your saying you want a blood cult esque clockcult, where the only real difference would be the need for power instead of health?

**Comment by jlsnow301** [comment]
Basically, yes. Tower defense removed. Ratvar a guaranteed summon unless literally all culties die before 30min. The size difference mechanic makes it a bit more unique.

**Comment by zeskorion** [comment]
You're saying the crew must fight a ratvar simplemob then

**Comment by jlsnow301** [comment]
Depending on how much (or how little) power they stole, could be. Ratvar would be full sized at a certain threshold.
I literally think anything is better than the tower defense setup it has now.

**Comment by qwertyquerty** [comment]
Tower defense is the entire point of clock cult. Sounds to me like you want to make a team boss fight game mode.

**Comment by jlsnow301** [comment]
Correct. Pretty obvious I don't like it at this point. I think it's only a great idea on paper

**Comment by qwertyquerty** [comment]
What you wanna do here is make a new gamemode instead of reworking an old one because you specifically don't like it.
