### ISSUE TITLE
apids no use hulk :(

### ISSUE THREAD

**Issue by spockye** [BeeStation/BeeStation-Hornet#3985]
Issue reported from  Round ID: 28289 (BeeStation Sage - Roleplay)

Reporting client version: 513.1536

apids cant use hulk 
if you inject yourself with a mutator, nothing happens

**Comment by Lagomorphica** [comment]
Non-humans in general can't use hulk if I recall. I believe it is intentional.

**Comment by PowerfulBacon** [comment]
Intentional

**Comment by spockye** [comment]
sad
