### ISSUE TITLE
[$25] Engiborg pseudocircuit to be also usable as airlock controller board

### ISSUE THREAD

**Issue by Megaddd** [BeeStation/BeeStation-Hornet#4003]
**Borgs cannot build windoors**, this triggers the OCD when fixing the desk in Medbay after Meth Explosion number 3867 takes place.

• Using the Engineer Borg Pseudocircuit 'in hand' now brings up the airlock controller board configuration interface for setting access and free entry side(s) (the existing functionality from printed airlock controller boards)
• **Pseudocircuit can now be used on Windoors** (and unfinished airlocks I guess, for consistency) to insert an airlock controller board with the configured access settings.
• Same cost/cooldown as existing analogs (air alarm, apc board, etc.)

**Comment by zeskorion** [comment]
if francinum giving a thumb here doesnt mean he'll do it, i will
