### ISSUE TITLE
Silicone bans dont properly ban from PAI

### ISSUE THREAD

**Issue by WaifuThread** [BeeStation/BeeStation-Hornet#4005]
## Reproduction: Be banned from silicone, have PAI turned on before ban, submit yourself as a PaI personality. be downloaded, and boom, you have subverted the ban

**Comment by FlamePrince** [comment]
PAI jobbans are their own thing afaik, you can be banned from AI/cyborg without being banned from pAI

**Comment by aidan-bowman** [comment]
pai's are hardly abusable lol, plus i'm pretty sure pai settings are used for some other minor things
