### ISSUE TITLE
Corgstation Cargo issues

### ISSUE THREAD

**Issue by yorii** [BeeStation/BeeStation-Hornet#4051]
## Reproduction: Cargo shuttle seems to spawn in with no atmos or somehow loses its atmos immediately. And this disposals is filling the wall with items:
![image](https://user-images.githubusercontent.com/7960287/113747962-37679580-9708-11eb-977a-3d66ef4cdf00.png)

**Comment by ike709** [comment]
@PowerfulBacon

**Comment by yorii** [comment]
Actually I think I know what causes the airleak, if you press the cargo shutter buttons on station while the shuttle isn't there, the shuttle in another z-level will open its doors and leak out all atmos. Maybe?

**Comment by PowerfulBacon** [comment]
2 of the shutters dont have buttons, fixed
