### ISSUE TITLE
Ashwalkers can speak common

### ISSUE THREAD

**Issue by Absolutely-Steph** [BeeStation/BeeStation-Hornet#4066]
## Round ID:
all rounds, but i noticed it in 28667

## Testmerges:
#3993: '[PORT] Emissivity Blockers' by francinum at commit b868d8270d
#3085: 'Corgstation 4' by PowerfulBacon at commit 8e58d20856

## Reproduction:
>be ashwalker
>have a leisurely chat with the miners, instead of a frantic session of trying to find out if you're gonna die or not.

Frankly, this is stupid.

**Comment by super12pl** [comment]
Intended, it encourages miners and ashwalkers to try diplomacy sometimes instead of "i dont understand you, kill".
It doesn't make sense but thats not important

**Comment by Absolutely-Steph** [comment]
If ashwalkers can speak common, then diplomacy is just gonna be them meeting the ashwalkers, and instead of a tense standoff where both sides try to figure out if the other is interested in cooperation, they just get a "yo we good? yeah okay." and thats it. what interesting diplomacy. make them bring a universal recorder, or a lizard, as a mediator.

**Comment by super12pl** [comment]
> If ashwalkers can speak common, then diplomacy is just gonna be them meeting the ashwalkers, and instead of a tense standoff where both sides try to figure out if the other is interested in cooperation, they just get a "yo we good? yeah okay." and thats it. what interesting diplomacy. make them bring a universal recorder, or a lizard, as a mediator.

there will be no tense standoff because miners can crit ashwalkers in one double pka hit lmao

**Comment by williamcll** [comment]
Besides, there's at least one lizard shaftminer per round anyways. I do try to stay in character and use only draconic however.

**Comment by PowerfulBacon** [comment]
> 
> 
> Intended, it encourages miners and ashwalkers to try diplomacy sometimes instead of "i dont understand you, kill".
> It doesn't make sense but thats not important

Aren't ashwalkers told specifically not to do diplomacy and that they must be aggressive outside of extreme circumstances?

**Comment by Absolutely-Steph** [comment]
I often see cooperative ashwalkers tho, maybe that should be stated in the spawners tab or something, or it could be forced by taking away their understanding of common.

**Comment by Absolutely-Steph** [comment]
wew, it happened #4146.
