### ISSUE TITLE
Item stacking is broken

### ISSUE THREAD

**Issue by yyzsong** [BeeStation/BeeStation-Hornet#4067]
## Round ID:
28667

## Testmerges:
https://github.com/beestation/beestation-hornet/pull/3993
https://www.github.com/beestation/beestation-hornet/pull/3085

## Reproduction:
Get multiple bottles of whatever chemicals. Put them in a chemistry bag. Despair as they all merge into a single stack.
![image](https://user-images.githubusercontent.com/65325586/114250505-8826fa80-9963-11eb-8d63-1b5d5f3f0324.png)
*Pictured: five bottles of salicyclic acid, six bottles of oxandrolone, five bottles of atropine, and four bottles of carthatoline. Supposedly.*

**Comment by DatBoiTim** [comment]
This might be a side effect of the RPGLoot bugfix

**Comment by FlamePrince** [comment]
I saw this with the bluespace RPED, I believe if you cycle through the stack you can find the specific chemical you're looking for. They don't "merge" and become all one item, afaik. It's still a bit buggy and inconvenient for pulling out specific parts/chemicals from stacked bags (for me it was bluespace power cells, some charged some not) but at least no one should be losing items this way.

**Comment by francinum** [comment]
The stacking system derives stacking behavior from basic data and reagent content is not one of them, I'm not sure there's a good fix for this.

**Comment by ivanmixo** [comment]
Close your issues after you fix them aaaaa

**Comment by DatBoiTim** [comment]
@francinum Close Issue :)
