### ISSUE TITLE
Contractor tablet just stops working for some reason sometimes.

### ISSUE THREAD

**Issue by heepox** [BeeStation/BeeStation-Hornet#4076]
## Reproduction:
Contractor tablet Breaks, becomes unresponsive, freezes and other things when you have had it for some time.
Step 1: Get the kit
Step 2: Accept a contract
Step 3: wait a few minutes
Step 4: try to sell your target
Step 5: Back to step 2 if it did not break.

Other times it breaks
Step 1: Get kit
Step 2: register with ID or without ID or a disguised ID
Step 3: Change ID and disguise
Step 4: Try to do contracts while changing IDs

What I think breaks:
The Login/register Breaks.
When you open the tablet again it just shows REGISTER and clicking it does nothing.
Sometimes it does this while still open in the contract menu. (freezes)
Someone else gets the kit aswell (rare but might cause it sometimes too?)

**Comment by Sinestia** [comment]
duplicate of https://github.com/BeeStation/BeeStation-Hornet/issues/3147
