### ISSUE TITLE
New sprites for tools broke AI detector.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#4083]
New sprite of the AI detector doesnt update itself to its other states. It just doesn't work.

**Comment by ivanmixo** [comment]
The AI detector works by painting the tiles the AI can see in red, like so. It definitely has some broken parts, I'll look into it later.

![image](https://user-images.githubusercontent.com/22431091/125347092-c9f88000-e35a-11eb-825f-071bca9d26c2.png)
