### ISSUE TITLE
Broken Contractor upload

### ISSUE THREAD

**Issue by Sadowstrike** [BeeStation/BeeStation-Hornet#4086]
Issue reported from  Round ID: 28807 (BeeStation Golden)

Reporting client version: 513.1539

When you activate your Contractor upload and store it in your pockets. It stops working and sends you back to the registration screen where nothing happens. Where you also cannot log in again.

![Unbenannt](https://user-images.githubusercontent.com/82540131/114767083-82685500-9d67-11eb-8d4c-bcf92494087c.PNG)

**Comment by aidan-bowman** [comment]
#4076 issue already exists lol

**Comment by heepox** [comment]
it works fine in the pocket... it just does that sometimes for some reason.
