### ISSUE TITLE
Problem with blindness and sensory restoration

### ISSUE THREAD

**Issue by DemonOfHatred** [BeeStation/BeeStation-Hornet#4088]
Issue reported from  Round ID: 28813 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542
Virus should have restored blindness caused by damage but was bugged out and would keep resetting to being blind again.
I'm clown, Lizard and i had nothing else in my system besides this as it was the very start of the round.
resistance:1, stealth:0, stage speed:-2, transmitability:2, severity:-1. Symptoms: sensory restoration. agent - advance microbes

**Comment by Vexylius** [comment]
![image](https://user-images.githubusercontent.com/22380218/114800243-a2187100-9d99-11eb-8e4e-d0766f636dd2.png)

![image](https://user-images.githubusercontent.com/22380218/114800392-eb68c080-9d99-11eb-8b40-6be6df735a67.png)
![image](https://user-images.githubusercontent.com/22380218/114800412-f6235580-9d99-11eb-9a98-f388802d6b55.png)


¯\_(ツ)_/¯
