### ISSUE TITLE
Latejoin chaplain broken

### ISSUE THREAD

**Issue by Bluedazzled** [BeeStation/BeeStation-Hornet#4102]
Issue reported from  Round ID: 28886 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542

Steps to reproduce:
1: Have roundstart chaplain cryo
2: Latejoin as chaplain
3: Bible is invisible, not the religion you chose, and unable to choose sect as you are "Not the high priest"
4: ???
5: Profit

**Comment by KubeRoot** [comment]
Issue seems to still be present, just happened to me on round ID `34017`, bible was invisible. Didn't try anything else since the round ended immediately after though.
