### ISSUE TITLE
Slimes will say hello even if you dont say "hello slimes" and dont include the word "slimes"

### ISSUE THREAD

**Issue by Zero123-star** [BeeStation/BeeStation-Hornet#411]
Title/ Its annoying happened today 07/09/2019

**Comment by epicss13gamer** [comment]
>Not a bug, and I dont understand how this is annoying.

**Comment by yorii** [comment]
Can't reproduce:
![image](https://user-images.githubusercontent.com/7960287/87312516-f3e94d80-c520-11ea-80a8-4e8871a5cf12.png)
