### ISSUE TITLE
Being turned into a dog (momentarily) counts as exile.

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#4117]
As a headrev, round 28954, I was the last headrev alive - a botanist arrived and pricked me. Instantly, round ended - Somehow, having been turned into a dog for 10 seconds (without dying) was enough to make the game consider that I was dead. Revolution was over. End screen listed me as "exiled".

**Comment by ItsTisme** [comment]
corgium do be funky

**Comment by Howluinb** [comment]
> 
> 
> corgium do be funky

It apparently removes all implants too, as I lost the cybersun hud implant upon coming back to me.

**Comment by francinum** [comment]
corgium fucking sucks.

This is mostly due to the way the abandonment checks during rev.
