### ISSUE TITLE
AI Camera Multi-view turns to static if you jump to core in a miniwindow and click out of the active port

### ISSUE THREAD

**Issue by tomohawks-FLINT** [BeeStation/BeeStation-Hornet#4125]
Issue reported from  Round ID: 29021 (BeeStation Sage - Roleplay)

Reporting client version: 513.1526

Trying to switch to another mini window in mutli-cam mode after jumping to core causes it to be permanent static in multicam mode, but not default view.

![ohno](https://user-images.githubusercontent.com/61092939/115637288-c74b3900-a2dd-11eb-9e69-f468e4c6e5de.png)

**Comment by MNarath1** [comment]
so i took a look at this and it looks like this happens cause the area you see when you switch to multicam is an actual space on the centcom z level and it has no cameras pretty sure it should have something like a flag that prevents static there but looks like that somehow broke
