### ISSUE TITLE
#3944 nerfed the medical vendor of the mining supply pod, making it useless. Was it really intended?

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#4143]
The only way of healing now in the mining pod is eating donk pockets.

**Comment by bloons3** [comment]
Yes

**Comment by IllotAFV** [comment]
But I have to admit, that it's kind of lame.

**Comment by USB3pt0** [comment]
Miners aren't the only ones using the survival pods, yanno.

*cries in curator*
