### ISSUE TITLE
Cyborgs can't be upgraded with new tGUI on ExoFab

### ISSUE THREAD

**Issue by quantumtechkat** [BeeStation/BeeStation-Hornet#4157]
## Round ID:
29166

## Reproduction:

Try to add upgrade modules to cyborg..
90% of upgrades rejected, even if they are compatible
100% issue is caused by new tGUI on exosuit fabricator

Example:
Tried all three skins of mining cyborg, tried to add lavaproof and satchel of holding. All upgrades rejected on all three models.

**Comment by jupyterkat** [comment]
silicon mains btfo 😎
