### ISSUE TITLE
Clicking (F) next to a person's name as ghost or the person's name to track them as AI opens the BYOND command in the browser.

### ISSUE THREAD

**Issue by MilkmansWife8291** [BeeStation/BeeStation-Hornet#4171]
Client version: 513.1542

Whenever I click follow next to a name or click the name in chat to track it in cameras, it opens my default browser with the BYOND command in the URL, which is something like: http://IP/tmpXXXX/browseroutput.html?src=[mob_339];follow=[mob_895]

This issue happens in no other servers.

**Comment by FluffTheMoth01** [comment]
I'm not able to replicate this

**Comment by Bluedazzled** [comment]
this only happens if you hold shift when clicking it. usually when clicking a hyperlink in a browser shift click opens a new tab
