### ISSUE TITLE
Corg station holodeck burn test is not contained inside of the holodeck.

### ISSUE THREAD

**Issue by Ravellon** [BeeStation/BeeStation-Hornet#4172]
## Round ID: 
29198

Golden

## Reproduction:
A player tried out dangerous holodeck programms. The player did not have to open a door to start a plasma fire, the plasma spread outside of the holodeck the moment it was loaded.

**Comment by ike709** [comment]
@PowerfulBacon

**Comment by jupyterkat** [comment]
Should be fixed and closed after #4472
