### ISSUE TITLE
[Refactor] Rename Transmittable In Assoc List for Advanced Diseases to Transmission

### ISSUE THREAD

**Issue by DatBoiTim** [BeeStation/BeeStation-Hornet#4192]
Feature requests are handled in the repository, but you could also discuss your ideas on beestation discord or forums here: https://forums.beestation13.com/

This would save many people sanity. This is mostly a tedious thing I do not want to do since I have other things to work on.

Literally change the name and any references to it. Please double check that all symptom thresholds match this(cause some use a different name for the transmission stat).

If nobody does this I'll eventually do it myself. I just do not want to prioritize a tedious rename.

**Comment by zeskorion** [comment]
Also with stage speed being stage rate. Fucks up everyone
