### ISSUE TITLE
Full vision with AI

### ISSUE THREAD

**Issue by LordChusmimax** [BeeStation/BeeStation-Hornet#4194]
Issue reported from  Round ID: 29270 (BeeStation Sage - Roleplay)

Reporting client version: 513.1528

As the Main AI, I currently have full vision of the station, no matter where cameras are situated. The only things that I can't see are the ones obscured by mere lack of light

**Comment by LordChusmimax** [comment]
after some minutes, it suddently solved

**Comment by Crossedfall** [comment]
Likely related to some of the performance issues we were having. If you experience it again, feel free to open a new issue.

**Comment by TerryTehCoder** [comment]
This is a concurrent issue that i've seen over not just a specific codebase and a long time span, so it honestly might just have something to do with byond and subsystems freaking out. 

I do know that even when it does occur, the proper restrictions to prevent the A.I from clicking on and accessing things in blindspots still work.
