### ISSUE TITLE
New GameMode: Clown/Mime Cult

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#421]
Essentially the same as blood cult, except:

a) Clown offers to Honkmother and subtle clown items start being added to culties
b) Mime culties eventually lose speech then are able to build invisible structures

objective is to dominate the station etc
just a gag gamemode

**Comment by xboxnoob** [comment]
the runed metal/brass from blood/clock culties can be replaced with bananium for clown culties

**Comment by zeskorion** [comment]
Gay

**Comment by despong** [comment]
security is the new chaplain

**Comment by Crossedfall** [comment]
A new issue with a bounty has been made regarding this. Discussions should be moved to #629
