### ISSUE TITLE
Cyborg modules don't install correctly

### ISSUE THREAD

**Issue by Crossedfall** [BeeStation/BeeStation-Hornet#4212]
(Creating on the behalf of a player)

## Reproduction:

1.  Have a cyborg with a mining chassis
2. Spawn/print standard mining upgrades (e.g. lavaproof tracks or the drill)
3. Attempt to insert the module into the cyborg

**Expected:** The module gets installed and the cyborgs is upgraded
**Actual:** The module gets rejected and the player is unable to upgrade the cyborg

**Comment by williamcll** [comment]
Other borgs have similar issues, for example:
Engineering - RPED
Medical - Crew pointer
Service - Gambling

**Comment by bloons3** [comment]
Borg diamond drill

![image](https://user-images.githubusercontent.com/3241376/116913687-655cce80-ac0f-11eb-9bc0-6ed9dab79372.png)

Robot module is:
![image](https://user-images.githubusercontent.com/3241376/116913922-b371d200-ac0f-11eb-8c40-5abe6bd21427.png)


Diamond drill works
![image](https://user-images.githubusercontent.com/3241376/116914117-f764d700-ac0f-11eb-8f04-cf3f7f795865.png)

---

Cannot reproduce for RPED
![image](https://user-images.githubusercontent.com/3241376/116914418-53c7f680-ac10-11eb-8523-48aee9904a7a.png)
 ---

Cannot reproduce for crew pinpointer

![image](https://user-images.githubusercontent.com/3241376/116914615-8f62c080-ac10-11eb-878f-e1b0981e52d0.png)

**Comment by bloons3** [comment]
Checked on a live server

@ike709 regressed borgs in the revert
![image](https://user-images.githubusercontent.com/3241376/116915025-1e6fd880-ac11-11eb-9bd6-43b1ef1a2858.png)

![image](https://user-images.githubusercontent.com/3241376/116915041-229bf600-ac11-11eb-8a02-a313edf58512.png)

https://github.com/BeeStation/BeeStation-Hornet/pull/4208

**Comment by 1210Avi** [comment]
Borgs essentially cannot have upgrades still.
Class-wide upgrades are working. Ion, self repair. The plasma gun works for mining borgs.
All other upgrades are rejected under the error of no mounting point
This bug started since the merging of the fabricator UI in robotics. Removing the UI didn't fix the bug.
