### ISSUE TITLE
Telecomms issues with broadcasting and receiving

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#4217]
radio works on reebe even though the hiero relay is set to `broadcasting = FALSE`. Might be to do with new runechat or tcomms tgui 

This also happens with the mining station comms relay, disabling broadcasting won't prevent messages being transmitted but disabling the receiving setting does.

**Comment by Sarchutar** [comment]
I went all the way back before both of the PRs (Runechat and Tcomms tgui) were merged and it was also a problem at that point so there is something else going on there.
