### ISSUE TITLE
Two robotics issue : break room and bot pathing on corg

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#4274]
Round ID: 29554 Corgstation dynamic round with wizards, nukeops, traitors and blob and some.

 Sage

## Reproduction:

Problem one: As roboticst, you cannot enter the break room in science department. The room also has no light

Problem two: bots on patrol gets stuck on northeast arrivals between north hallway and cargo hallway, moving anti-clockwise around the character below.
![image](https://user-images.githubusercontent.com/43061493/117673014-f66a1180-b1dc-11eb-992e-401e4e35b273.png)

**Comment by ike709** [comment]
@PowerfulBacon

**Comment by ivanmixo** [comment]
Closed this back in #4342 which I forgot to link to this PR. Sorry!
