### ISSUE TITLE
Admins can't trigger instantaneous meteors

### ISSUE THREAD

**Issue by ike709** [BeeStation/BeeStation-Hornet#4277]
Caused by @PowerfulBacon putting a 10 minute delay on them.

Create an admin subtype of the event, and maybe give admins a popup asking if they want instantaneous or delayed.

**Comment by ike709** [comment]
Also if it's the delayed one there should really be another announcement when the meteors are about to actually start.

**Comment by ike709** [comment]
@PowerfulBacon

**Comment by yyzsong** [comment]
Should probably close this because of https://github.com/BeeStation/BeeStation-Hornet/pull/4845
