### ISSUE TITLE
Being a part of incursion team does not remove clown's clumsiness. 

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#4294]
It probably should, being a usual traitor or a ling takes away the clown's clumsiness.

**Comment by ItsTisme** [comment]
Traitor clowns also still are clumsy, no point in treating incursion diffrent

**Comment by IllotAFV** [comment]
There was a check, that removes clumsiness from the antag clown shift start, I am totally sure about this

**Comment by KubeRoot** [comment]
> There was a check, that removes clumsiness from the antag clown shift start, I am totally sure about this

I think I found it: https://github.com/BeeStation/BeeStation-Hornet/blob/a851032fa745e67372bd5c16adf7ae98e087f535/code/modules/antagonists/_common/antag_datum.dm#L322

**Comment by IllotAFV** [comment]
Yes, that is the stuff. It just never gets called.

**Comment by KubeRoot** [comment]
> Yes, that is the stuff. It just never gets called.

Seems like it's used for heretics specifically https://github.com/BeeStation/BeeStation-Hornet/blob/2d069180866d23d2a65925b1daee865023eff285/code/modules/antagonists/eldritch_cult/eldritch_antag.dm#L138

**Comment by Jeff-3** [comment]
Seems like a feature considering there's a clown specific uplink item that has the reverse clumsiness effect of other guns.
