### ISSUE TITLE
No printer in HOP office in PubbyStation

### ISSUE THREAD

**Issue by Troontjelolo** [BeeStation/BeeStation-Hornet#4302]
## Round ID:
29639

## Testmerges:
#4219 

## Reproduction:
No printer in pubby HOP office, anti-paperwork HOP discrimination.

**Comment by Sinestia** [comment]
What

none of them have printers

**Comment by Archanial** [comment]
> 
> 
> What
> 
> none of them have printers

He meant copiers.

**Comment by Sinestia** [comment]
![image](https://user-images.githubusercontent.com/40812746/118300021-1b91a500-b4a7-11eb-8543-0451b5aec732.png)
i dont get it whats missing

**Comment by Archanial** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/40812746/118300021-1b91a500-b4a7-11eb-8543-0451b5aec732.png)
> i dont get it whats missing

copier

**Comment by Sinestia** [comment]
> > ![image](https://user-images.githubusercontent.com/40812746/118300021-1b91a500-b4a7-11eb-8543-0451b5aec732.png)
> > i dont get it whats missing
> 
> copier

OH

it literally blends in on the other maps

**Comment by Troontjelolo** [comment]
> > > ![image](https://user-images.githubusercontent.com/40812746/118300021-1b91a500-b4a7-11eb-8543-0451b5aec732.png)
> > > i dont get it whats missing
> > 
> > 
> > copier
> 
> OH
> 
> it literally blends in on the other maps

I know right? I thought I was going insane so I searched the HOP office for like 5 minutes.
