### ISSUE TITLE
Make Swarmers Able to Consume Things that Make Sense

### ISSUE THREAD

**Issue by DatBoiTim** [BeeStation/BeeStation-Hornet#4309]
Feature requests are handled in the repository, but you could also discuss your ideas on beestation discord or forums here: https://forums.beestation13.com/

Like why can't you eat metal coins? Or cable pieces? Or literally anything from the ore silo? Right now it seems very arbitrary and lacks logic.

**Comment by zeskorion** [comment]
you can eat things with a metal material datum of a certain amount iirc. problem is, most things don't have that

**Comment by DatBoiTim** [comment]
> you can eat things with a metal material datum of a certain amount iirc. problem is, most things don't have that

Yeah so expanding it a bit, or hell even having a swarmer_consumable var may be in order.

**Comment by zeskorion** [comment]
> > you can eat things with a metal material datum of a certain amount iirc. problem is, most things don't have that
> 
> Yeah so expanding it a bit, or hell even having a swarmer_consumable var may be in order.

probbbably a flag instead?

**Comment by DatBoiTim** [comment]
> > > you can eat things with a metal material datum of a certain amount iirc. problem is, most things don't have that
> 
> > 
> 
> > Yeah so expanding it a bit, or hell even having a swarmer_consumable var may be in order.
> 
> 
> 
> probbbably a flag instead?
> 
> 

Yeah something to allow expansion of consumable
