### ISSUE TITLE
no blacklist for random rooms

### ISSUE THREAD

**Issue by bloons3** [BeeStation/BeeStation-Hornet#4323]
https://github.com/BeeStation/BeeStation-Hornet/blob/09902e8d98a0b5eb24679de26fe054e179c153a0/code/controllers/subsystem/mapping.dm#L364

**Comment by zeskorion** [comment]
i actually had a few ideas i could do with random room bitflags and station traits recently
for now? just comment them out or set their weight to 0

**Comment by bloons3** [comment]
I'm talking about a config blacklist, like exists for Lavaland ruins
