### ISSUE TITLE
The Road to Multi-Z 

### ISSUE THREAD

**Issue by qwertyquerty** [BeeStation/BeeStation-Hornet#434]
Genuine problems:
- [ ] When you walk off of a wall, it doesn't do the same amount of damage as walking off of a floor at the same height.
- [x] You can walk off and crash into space
- [x] When you break a tile on an upper floor, it makes a space tile instead of a hole to the lower floor
~~- [ ] Explosions are not multi-z~~ Too laggy. Even oranges refuses to do multi-z explosions.
- [ ] You cannot pick up items on a wall that is the same level as a floor
- [ ] You cannot shoot projectiles down pits
- [x] We need elevators
- [x] You need a grav gen on every level
- [x] Ladders must be constructable
- [x] If there is no gravity, I shouldn't fall! ...right?
- [x] You don't take more damage if you fall more levels
- [ ] Things like vehicles or other items that can take damage should take damage when they fall.
- [ ] Backlog of multi-z fixes/features from TG. See: https://github.com/BeeStation/BeeStation-Hornet/projects/2

Qwerty's silly wishlist:
- [ ] YOU SHOULD BE ABLE TO DROP HEAVY ITEMS ON PEOPLES HEADS TO DO DAMAGE

Visual bugs (see aurora subsection below):
- [ ] Holes aren't extremely obvious. A slight blur to lower levels could work
- [ ] You don't get the same hole effect when looking down multiple holes, only the first hole works
- [ ] You can't really see mob movement on lower levels. They just kind of jump to their new spot
- [ ] Transparent tiles should show down to lower levels. Catwalks, lattices, glass floors
- [ ] You cannot see lighting on lower levels
- [ ] The shadow effect shows on a wall that is the same level as a floor

Cool-looking aurora z-level stuff:
EDIT - It would probably be better to use visual contents once we're on 513 instead of z-mimic.
- [ ] De-planeify TG
- [ ] Port https://github.com/Baystation12/Baystation12/pull/26862
- [ ] See how many visual bugs it fixes

**Comment by MarkSuckerberg** [comment]
All of these are valid issues, but I have tested the multi floor falling, and it does give more damage(unless falling from more than two floors is different) and, not entirely sure what you mean by "you don't get the same hole effect..." as Im also pretty sure you see the same thing in a hole that goes down two floors as you see in a hole that goes down one. The things I think will be most difficult would likely be multiz explosions and making falling slower.

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/435

**Comment by ike709** [comment]
TODO: Investigate multi-z visuals on Aurora(?)

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/448

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/465

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/467

**Comment by ike709** [comment]
Aurora's cool z-level visuals: https://github.com/Baystation12/Baystation12/pull/26862/files

Requires all atoms to be on one plane. (See https://github.com/Baystation12/Baystation12/pull/26829 for reference).

**Comment by despong** [comment]
hey... what about trams, cranes and little platforms that can ride on the walls (for construction and janny stuff)

**Comment by MarkSuckerberg** [comment]
#571

**Comment by MarkSuckerberg** [comment]
#584

**Comment by MarkSuckerberg** [comment]
Todo; Fix Move Upwards/Downwards for mobs besides observers

**Comment by ike709** [comment]
This issue is worth revisiting since TG has put a lot of work into fixing multi-z bugs since the issue was opened.

**Comment by ike709** [comment]
This issue is pretty out of date so I'm closing and unpinning it.
