### ISSUE TITLE
Space hotel Solar panel issues

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#4347]
## Round ID:29825

 Reproduction: Ghost spawn in a space hotel staff, heading to engineering you would notice a few issues with the solar panel setup.
 
 1) The bottom row of the SouthWest solar is not connected to the grid and requires a little bit of wiring, not sure if this was intentional.
 
2) On the same grid, but on the opposite side of the station is the NorthEast solars, which despite connected does not show up on the solar panel tracking computer.

I asked the admins about it but so far the only solution seems to be putting a solar tracking computer near the NorthEast solars, such as hotel room 6.

**Comment by KubeRoot** [comment]
As for point 2, turns out solars need to be within 40 turfs of the control console, that's why the ones on the opposite direction cannot connect. I think cramming another console near them might be a good idea, could even be hard to access or need to be setup to give hotel staff something to do.
