### ISSUE TITLE
Odysseus reagent synthesis not functioning

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#436]
## Reproduction:

1.  Construct an Odyessus exosuit and attach both a mounted sleeper and syringe gun to it.

3. Fill the syringe gun with syringes by clicking on a syringe box with the gun selected.

2. Click on view stats and set the syringe gun to analyse mode. With the syringe gun set to analyse mode, click on a chemical in a beaker to scan it. I used cryoxadone.

3. After scanning a chemical, go to the list of reagents. you should see epinephrine, charcoal, and whichever chemical you scanned with the syringe gun.

4. Checkmark the chemical and click apply settings. Nothing seems to happen when I try this on Beestation, however when I followed these exact steps in a /tg/ server, the Odysseus would synthesise the chemicals I had selected.

**Comment by Toxici11i** [comment]
I have encountered this issue, and speculate its to do with the chemical changes (we made everything a subtype of its respective category, therefor changing the path). either that or it got broken by something misc
