### ISSUE TITLE
Infinity chemical generation  bug 

### ISSUE THREAD

**Issue by NickEmbased** [BeeStation/BeeStation-Hornet#4371]
1. Be service cyborg
2. Make any drink in a cup
3. Place it 
4. Remove all chemicals from that cup
5. Place it again
6. Wait
7. Watch it refill itself to full after some time

**Comment by St0rmC4st3r** [comment]
Works as intended, move along citizens,

**Comment by pickleinjar** [comment]
perfectly balanced

**Comment by BrumalLake** [comment]
@NickEmbased gonna close this?
