### ISSUE TITLE
Mime finger guns stick around too long

### ISSUE THREAD

**Issue by Raven-Industries** [BeeStation/BeeStation-Hornet#4382]
## Issue: 
When using the mime traitor's finger guns, after shooting at something (with nothing else in your hands), you are unable to click the HUD button to disable your fingers, and trying to pick up objects/interact with storage items/ will just give you the message "Finger Guns is still recharging". You are therefore stuck unable to use any other items, punch someone, or even shift-click to examine stuff for the 30 second cooldown between each shot. 

Round ID: N/A
Test Merges: N/A

## Reproduction: 
Be a traitor mime, purchase advanced mimery and get finger guns. Shoot at something, and then attempt to turn off finger guns or interact with anything else.

**Comment by aidan-bowman** [comment]
can't you just drop them to get rid of them? with regular finger guns you stop using them by dropping them

**Comment by DatBoiTim** [comment]
> can't you just drop them to get rid of them? with regular finger guns you stop using them by dropping them

You can also get rid of those by attempting to shoot once empty.

However, these are quite dumb and entirely different.
