### ISSUE TITLE
RCD sometimes can't deconstruct volcanic floor tiles on lavaland

### ISSUE THREAD

**Issue by Ikalpo** [BeeStation/BeeStation-Hornet#4392]
## Round ID:
30008

## Testmerges:
#4272

## Reproduction:
get an RCD and try building a robust shuttle on lavaland using plating

**Comment by KubeRoot** [comment]
This might have been fixed since world generation was majorly changed since, and the reproduction steps aren't helpful, because this most likely occurred in specific circumstances (exposed ground? ground under mined out rock? ground that's part of a ruin? ground under deconstructed ruin tile?)
