### ISSUE TITLE
`ShowChoices()` needs a rewrite

### ISSUE THREAD

**Issue by ike709** [BeeStation/BeeStation-Hornet#4431]
![image](https://user-images.githubusercontent.com/5714543/120247471-2b481200-c239-11eb-8f44-a80ca3f5c085.png)

**Comment by FluffTheMoth01** [comment]
HOLY MOTHER OF GOD ITS JUUST A BIG IF ELSE TREE
it is 650 LINES LONG. IT IS ABSOLUTELY BRAINDEAD

**Comment by PowerfulBacon** [comment]
The preview is probably what makes it slow

**Comment by Kapu1178** [comment]
our entire preference backend needs a rewrite.

**Comment by Tsar-Salat** [comment]
Does this till apply after #8776 ? I know showchoices() literally no longer exists as a proc, but was it inherited or did it receive a refactor?

**Comment by itsmeow** [comment]
ShowChoices is the prefs HTML renderer. It no longer exists.
