### ISSUE TITLE
Brain problems quirk can fail to equip

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#4453]
Issue reported from  Round ID: 30237 (BeeStation Sage - Roleplay)

Reporting client version: 514.1554

[00:03:51] Runtime in inventory.dm, line 19: list index out of bounds
proc name: equip in one of slots (/mob/living/carbon/proc/equip_in_one_of_slots)
src: (/mob/living/carbon/human)
src.loc: the floor (113,91,2) (/turf/open/floor/circuit)
call stack:
(/mob/living/carbon/human): equip in one of slots(the bottle of mannitol pills (/obj/item/storage/pill_bottle/mannitol/braintumor), /list (/list), 0)
Brain Tumor (/datum/quirk/brainproblems): on spawn()
Brain Tumor (/datum/quirk/brainproblems): New( (/mob/living/carbon/human), 1)
(/mob/living/carbon/human): add quirk(/datum/quirk/brainproblems (/datum/quirk/brainproblems), 1)
Quirks (/datum/controller/subsystem/processing/quirks): AssignQuirks( (/mob/living/carbon/human), (/client), 1)
Ticker (/datum/controller/subsystem/ticker): equip characters()
Ticker (/datum/controller/subsystem/ticker): setup()
Ticker (/datum/controller/subsystem/ticker): fire(0)
Ticker (/datum/controller/subsystem/ticker): ignite(0)

**Comment by EvilDragonfiend** [comment]
related issue
- #5919

I think we need to change things to spawn in their backpack. For the heirloom, It's handled in my PR already, but the brain tumor will need to have its own.

**Comment by Archanial** [comment]
Just see how I did it with Cult/heretics.

The issue is you can have backpack full of beecoin stuff.
