### ISSUE TITLE
Infinte Materials with satchel of holding.

### ISSUE THREAD

**Issue by Boxlta** [BeeStation/BeeStation-Hornet#4459]
## Round ID: 30255

If you discovered this issue from playing beestation hosted servers:--> LRP

## Reproduction: 
You can get infinite materals via smelting ores in a Mining Satchel of holding, with a welder or a plasma cutter
1. Obtain ore to infintely reproduce
2. Obtain satchel of holding and welder/plasma cutter
3. Put ore in satchel of holding, smelt ore with cutter/welder.
4. Ore is not consumed, sheets are produced, resulting in infinite materials.

**Comment by MNarath1** [comment]
Question can this be applied to all types of ore?

**Comment by MNarath1** [comment]
I tested and i cannot reproduce it the ore is consumed trough the stack count does not update properly for some reason however the ore number itself gets depleded like its supposed to and once it reaches 0 the stack number gets updated too aka it vanishes.
trough the stack number does update if you close and reopen the ore satchel

**Comment by MNarath1** [comment]
in short this is not a material dublication bug but just a ui update bug instead cause the ui does not update properly when smelting or probably cause of how old that code actually is.

**Comment by Boxlta** [comment]
Ah, yeah. That makes sense, i only tried smelting 1 or 2 times and I had a lot of ore so.
