### ISSUE TITLE
Internals get consumed about 5x faster than before

### ISSUE THREAD

**Issue by BrumalLake** [BeeStation/BeeStation-Hornet#4483]
## Round ID:
30335, 30336, 30337 sage

## Reproduction:
breathe internals
they get consumed 5x faster
most noticeable on plasmamen which only have 30 minutes to live with their starting tank and spare which is normally 2 hours
fleeting emergency tanks last a minute
believed to be caused by "delta time"?

**Comment by ike709** [comment]
@jupyterkat

**Comment by utilbird** [comment]
I see this as an absolute win

**Comment by Absolutely-Steph** [comment]
This might actually be a good thing tho, emergency tanks holding for what feels like 30mins is overkill anyway, you are supposed to use them to get into a pressurized area as fast as possible.
And the plasmaman tanks mean they have to either ask atmos or science for a quick refill, or buy new tanks with cargo. More reasons to talk to people are always good i think. Now pluox actually has a reason to be used.

**Comment by BrumalLake** [comment]
> 
> 
> This might actually be a good thing tho, emergency tanks holding for what feels like 30mins is overkill anyway, you are supposed to use them to get into a pressurized area as fast as possible.
> And the plasmaman tanks mean they have to either ask atmos or science for a quick refill, or buy new tanks with cargo. More reasons to talk to people are always good i think. Now pluox actually has a reason to be used.

you ever tried living on a stasis unit?
