### ISSUE TITLE
Radio communication doesn't reach docked shuttles

### ISSUE THREAD

**Issue by KubeRoot** [BeeStation/BeeStation-Hornet#4492]
## Reproduction:

Ensure the comms are operational by saying something over the headset.
Walk onto an escape pod, cargo shuttle, arrivals shuttle, emergency shuttle, or corgstation transport shuttle.
Try to talk over the headset.

### Expected results

Being able to hear yourself and others speaking over the radio.

### Actual results

Even though comms are operational, you are unable to speak over or hear the radio while on a docked shuttle.

## Additional notes:

Presumably caused by https://github.com/BeeStation/BeeStation-Hornet/pull/4202
Should be fixed by https://github.com/BeeStation/BeeStation-Hornet/pull/4489

**Comment by ike709** [comment]
Presumably fixed
