### ISSUE TITLE
R&D Can't Print Jani Equipment

### ISSUE THREAD

**Issue by Alex-Selvey** [BeeStation/BeeStation-Hornet#4497]
Even if R&D has the janitor equipment researched you can't print any of it from the protolathe. It just doesn't show up in the list to be printable. The big thing being the floor buffer upgrade for the jani cart. This issue seemed to persist through multiple games.

**Comment by Sarchutar** [comment]
They are in the Service techfab under "Equipment" and not the Science one, also make sure you press the "Synchronize Research" button

**Comment by Alex-Selvey** [comment]
Just want to make sure, but are you talking about the public autolathe outside of science?

**Comment by Sarchutar** [comment]
Nono, the protolathe/techfab which every department has their own of.

Like those things: 
(Also location of it on meta)
<details>
<summary>Picture</summary>

![picture](https://user-images.githubusercontent.com/53494785/121367409-96c96800-c93a-11eb-8ca4-502da5434a68.png)

</details>

**Comment by Alex-Selvey** [comment]
I didn't even know that existed. Thank you so much! I just thought It was something typical that science could print out. Closing as this is user error.
