### ISSUE TITLE
Petition to revert balloon alerts

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [BeeStation/BeeStation-Hornet#4517]
While playing BeeStation, with its unique gameplay experience on its all, balancing both modern and old SS13 experience, I still question the necessity of porting some stuff from /tg/ - from a "modern" SS13.

It is not the first time that /tg/ port fails to work or integrate properly into BeeStation. For example, let's take the "Smart Asset Caching System". It is still slower(even though it's supposed to be faster?) and a lot of times produces incorrect results, such as showing some random incorrect sprite for the object. But again, that's just an example, not the point.

So do we really need to port everything from /tg/? I think we need to think more in-depth, to a point on do we even need that? Not just blindly copy stuff because somebody made it. We're a separate thing now, not just a slightly off branch.

Everything that was said applies to the new balloon alerts port, that just does not fit our server's style. So maybe it's time to stop and correct some mistakes that we've already made.

Also worth mentioning though, not only does it not fit our server, those ports have issues on their own, I've said that "Smart  Asset Caching System" does not work properly, more on the balloon alerts are much slower and harder to read and understand than the traditional text alerts.

I am very bothered to put this issue up because it removes that authentic experience BeeStation has. And it is being destroyed and dusted into nothing by these kinds of changes, making the server feel like nothing.

**Comment by ToasterBan** [comment]
it's a preference option....

**Comment by eLeCtrOssSnake** [comment]
> it's a preference option....

They are poorly made/ported as well as other ports from/tg/ ports, maybe the title should be about /tg/ ports in general but still.
It also changes chat messages text fnr.

**Comment by Sinestia** [comment]
Balloon alerts being slow isn't something I know about

But it itself is a good idea, fits in changes to make you have to look at chat box less, especially since it's optional.

**Comment by eLeCtrOssSnake** [comment]
They are more inconvenient and slower, while also changing text that is printed on chat, making it look worse.

**Comment by Sinestia** [comment]
> They are more inconvenient and slower, while also changing text that is printed on chat, making it look worse.

It is possible to change what they do to chat


 And maybe on them being slower, but I'd attribute that to the animation they use. I'd personally have probably designed them to just start on top of your head and fade, but w.e

**Comment by eLeCtrOssSnake** [comment]
Confirms that they need improvements to work properly.

**Comment by eLeCtrOssSnake** [comment]
When items do not fit into storage because they're too big it balloon alerts even if you disable it in preferences. Checkmate

**Comment by eLeCtrOssSnake** [comment]
The "gun clicks" phrase is also edited out in white colour fnr.

**Comment by eLeCtrOssSnake** [comment]
It is strange that some text alerts are coloured in white while others remain cool old-ish style. I don’t really understand what was the point of changing colour of the text in chat.

**Comment by Archanial** [comment]
Who are you to say what fits and what doesn't fit our server? Who are you to dictate "theme" of bee?
What did balloon alerts destroy? I've made it even a config option. YOU CAN DISABLE IT IF YOU DON'T LIKE IT.

It's not slow. It's as fast as runechat because it uses the same SS and is literally just subtype of chatmessage.

And if you'd look into my pr and compared it to tgs you'd find they're pretty different.

**Comment by Mothblocks** [comment]
lmao

**Comment by BrumalLake** [comment]
> So do we really need to port everything from /tg/? I think we need to think more in-depth, to a point on do we even need that? Not just blindly copy stuff because somebody made it. We're a separate thing now, not just a slightly off branch.

nooo tg branch is using tg features!1
We're pretty much an older version of tg, name a major gameplay feature that we have unique from tg

**Comment by eLeCtrOssSnake** [comment]
We don't need to have anything better/worse over /tg/. Our gameplay style is different, it's not about whose game looks cooler/techy or whatever else some other server will introduce.

**Comment by eLeCtrOssSnake** [comment]
> Who are you to say what fits and what doesn't fit our server? Who are you to dictate "theme" of bee?
> What did balloon alerts destroy? I've made it even a config option. YOU CAN DISABLE IT IF YOU DON'T LIKE IT.
>
> It's not slow. It's as fast as runechat because it uses the same SS and is literally just subtype of chatmessage.
>
> And if you'd look into my pr and compared it to tgs you'd find they're pretty different.

@Archanial I did not promote myself in any way, that is my opinion on how it looks like and seeking support from others to see if their opinion matches mine. I don't really know what are you on about.
