### ISSUE TITLE
Bugs: Antagonists getting free objectives

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#453]
## Round ID:
Any

## Testmerges:
Primary server

## Reproduction:
1. Space Ninjas: Able to get a free "Succeed - Success!" objective
2. Changelings: Changeling team objectives can choose to impersonate a changeling, meaning greentext just for leaving
3. Wizards/Apprentices: Same as ninjas - free objective with no goal.

**Comment by ike709** [comment]
1. Ninjas are horrifically broken and shouldn't ever exist. Looking at you @Toxici11i 
2. @qwertyquerty Looks like @jlsnow301 was correct.
3. Actual bug.

**Comment by jlsnow301** [comment]
Zesko can comment on #2

**Comment by Toxici11i** [comment]
Ninja/wizards are either the easiest antags to beat or the most robust. Ninjas shouldnt have a free objective so idk
