### ISSUE TITLE
[$25 BOUNTY] Port GAGS

### ISSUE THREAD

**Issue by ike709** [BeeStation/BeeStation-Hornet#4533]
TG has a new system called Greyscale AutoGenerated Sprites, which enables advanced greyscale usage and generally reduces icon bloat.

There is a *large* number of PRs to port and icon files to edit, hence this bounty. A mostly (but not entirely) complete list of PRs to port can be found as part of https://github.com/BeeStation/BeeStation-Hornet/projects/2#column-7174998

Upon completion and successful testing a single payment of $25 will be sent directly via Paypal, due to the numerous problems with Bountysource. No alternative compensation options will be provided. Whomever completes it should provide their Discord info in the PR description so we can contact you.

**Comment by BrumalLake** [comment]
going after this
