### ISSUE TITLE
No more empty clone button thanks to #4364

### ISSUE THREAD

**Issue by BrumalLake** [BeeStation/BeeStation-Hornet#4579]
## Reproduction:
Look at cloning console
Empty clone button is gone! 😭
Thanks #4364 👍
https://discord.com/channels/427337870844362753/605179594617782302/855821209450971176

**Comment by DatBoiTim** [comment]
Shame Brickets for not opening the issue himself.

S H A M E

**Comment by Archanial** [comment]
@jupyterkat

**Comment by jupyterkat** [comment]
![image](https://user-images.githubusercontent.com/56778689/122661055-bc236500-d1c9-11eb-874a-3f20f8bf3581.png)
It's still there, dummy

**Comment by jupyterkat** [comment]
You press body only, it outputs a record of the body only scan and then you press clone?
