### ISSUE TITLE
Deconversion not removing blood cult hud

### ISSUE THREAD

**Issue by theonlymacmac** [BeeStation/BeeStation-Hornet#4585]
## Round ID:30678

I was a cultist, and was captured by sec. I am an ipc, so they injected me with what I assumed to be holy water. The process took longer than usual (that I could tell) and when the text saying the geomancer's light faded from my mind appeared, I still had all the HUD icons for blood cult.

**Comment by MNarath1** [comment]
can't reproduce this

**Comment by MNarath1** [comment]
for me at least deconversion on ipc's  works just fine if you can provite more info that would be apreachiated like more detailed repro steps might be that there is something missing here
