### ISSUE TITLE
Bundles can trigger weird behavior

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#4591]
Bundle of syndie hardsuit + radio:
![obraz](https://user-images.githubusercontent.com/37456678/122700845-57f5b500-d24c-11eb-8e79-286e73dc1291.png)

**Comment by BrumalLake** [comment]
whats a hardsuit doing in a box?
hardsuit helmets just have weird behavior in general, checking the runtime you get on the dummy when you open the ert spawn menu
