### ISSUE TITLE
Light boxes and light swapping is brokene

### ISSUE THREAD

**Issue by yyzsong** [BeeStation/BeeStation-Hornet#4596]
## Round ID:
30697

## Testmerges:
#4415 
#4380
#4454 
#4357 

## Reproduction:
Find a broken lightbulb in a light fixture
use a normal lightbulb on it to try and fix it
your normal lightbulb will shatter, despite producing a 'You replace the lightbulb' message
if you try putting your now-broken lightbulb back into the lightbulb box, the REST of the lightbulbs in the box will shatter!

**Comment by yorii** [comment]
wait what the fuck?

**Comment by ivanmixo** [comment]
Can't reproduce
