### ISSUE TITLE
Seclights disappear when you attach them to guns

### ISSUE THREAD

**Issue by yyzsong** [BeeStation/BeeStation-Hornet#4597]
## Round ID:
30697

## Testmerges:
#4415
#4380
#4454
#4357

## Reproduction:
Try and attach a seclight to your gun. It will disappear and not produce light. Toggling it on/off will do nothing. Cry.

**Comment by yorii** [comment]
@yyzsong does it register a toggling action? If so I probably know what's up.

**Comment by ivanmixo** [comment]
Caused by #4380 which is now dead. Edit: Nevermind it is caused by #4765
