### ISSUE TITLE
corg needs to be rewired

### ISSUE THREAD

**Issue by KittyNoodle** [BeeStation/BeeStation-Hornet#4602]
Issue reported from  Round ID: 30704 (BeeStation Sage - Roleplay)

Reporting client version: 514.1556

Wires have zero redundancy.  The civilian sector starts not connected to main power.

**Comment by ike709** [comment]
@PowerfulBacon

**Comment by PowerfulBacon** [comment]
All departments should connect back up to the source with a single wire roundstart, however this can be broken by mice. Wires in maints have nodes near each other which can be connected up by engineers to add redundancy.

**Comment by ike709** [comment]
There should be a single level of redundancy IMO, as there's a literal laundry list of things that could take out the single wire and it's almost always just random inconvenience rather than intentional sabotage.

**Comment by KittyNoodle** [comment]
started a private testing server with no mice and civ sector still depowered with fully charged all SMESs fully charged.
