### ISSUE TITLE
Crematorium igniter req_access field allows anyone to press the button (intentions seem to conflict)

### ISSUE THREAD

**Issue by Ohagi-Chan** [BeeStation/BeeStation-Hornet#4621]
## Round ID:
NA

## Reproduction:
Somebody told me that there was meant to be code in place that prevented normal crewmembers from pressing the crematorium button, but in practice this doesn't actually happen.

I looked into the issue in both the code and map editor and found that the intention seems to be conflicted.
On the map editor, req_**access_txt** is overwritten to list("27"), while in machinery/buttons.dm line 275, the req_**access** is set to list().
Because of this conflict, I can't tell what the intended function is supposed to be; are normal people supposed to be able to press the button or not?

However I have confirmed through testing that if you simply change line 275 to
`req_access = list(ACCESS_CREMATORIUM)`
then the button stops working for any carbon that is not holding an ID with crematorium access.

Submitting this as an issue rather than a PR because I don't know whether you'd consider this change to be a fix or not.

**Comment by francinum** [comment]
Mapper's responsibility IMO.

The code however is an issue. `req_access` should probably be set to `null` so `*_txt` parsing is triggered.

**Comment by francinum** [comment]
...Wait has this seriously been broken since 2015?!
e17b3c8392613905ed38be604011796621289279
