### ISSUE TITLE
Funny Fireman broken

### ISSUE THREAD

**Issue by yyzsong** [BeeStation/BeeStation-Hornet#4624]
## Round ID:
30749

## Testmerges:
#4415: 'Let's see if this helps anything at all.' by francinum at commit 41b343ce2c
#4380: 'Security Rework Part 1 of ?: Energy pistols' by ike709 at commit c10d3a13cb
#4357: 'Ports new overlay lighting component and opacity refactor from tg' by yorii at commit 0f934881d1

## Reproduction:
Try and fireman carry someone. Get the succeed message but fail to carry them anyway. Try again, succeed.

**Comment by williamcll** [comment]
yeah, you need to fireman carry twice to pick up someone. very annoying. doesn't happen on NSV however.

**Comment by ivanmixo** [comment]
Also a problem with piggybacking so I'm suspecting this is an issue with mob buckling

**Comment by Archanial** [comment]
It's issue with riding component not initializing on first try. It also affects stuff like riding on borgs.
