### ISSUE TITLE
Corgstation cargo and service have protolathes instead of techfabs

### ISSUE THREAD

**Issue by BrumalLake** [BeeStation/BeeStation-Hornet#4628]
## Reproduction:
Can't print an express console board with it or any other cargo circuits cause its not a hybrid techfab

**Comment by KubeRoot** [comment]
From checking the map files, looks like service also only has a protolathe. Medbay and security have techfabs, engineering and science have protolathe+circuit imprinter combos. Not sure if mistake/oversight or intentional.
