### ISSUE TITLE
Toy Dswords are actual Dswords

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#4636]
## Round ID: 30769 as well as some rounds before this

Servers: Sage
## Reproduction:

Built a donk vendor in primary hallway. Clown buy **toy** dsword and swings it at another person. Person takes 30+ damage like a regular dsword. Captain dismantles vendor after showing the scientist who built it the damage caused (4 casualties).

![image](https://user-images.githubusercontent.com/43061493/123251548-e94f7a80-d51d-11eb-8c30-9d2e1caed277.png)

**Comment by Effemu** [comment]
based, leave it as it is

**Comment by pickleinjar** [comment]
extremely based i agree

**Comment by KittyNoodle** [comment]
based

**Comment by KittyNoodle** [comment]
not a bug.

**Comment by imsynthex** [comment]
This was fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/4637 btw

**Comment by Sinestia** [comment]
@ImSynthex Thank you for pointing that out.
