### ISSUE TITLE
Shields dont block while in your offhand

### ISSUE THREAD

**Issue by BrumalLake** [BeeStation/BeeStation-Hornet#4644]
## Testmerges:
#4415 
#4380 
#4357

## Reproduction:
try blocking

**Comment by r1ks-iwnl** [comment]
Worked fine on my local when i blocked with a wrench a crowbar and a riot shield so its either bcs of testmerges which you didn't list or you did it wrong

**Comment by BrumalLake** [comment]
its testmerges then, i extended my riot shield, was in walk mode, and the shield was still in roleplay mode and was purely cosmetic

**Comment by r1ks-iwnl** [comment]
Were you on harm intent ? You can't block on harm.

**Comment by r1ks-iwnl** [comment]
Nevermind something is actually broken, you CAN block but only if your active hand is on the shield, if you switch hands you won't block anymore which is how normal items should behave but not shields.
