### ISSUE TITLE
Ash Mutation Toxin doesn't exist

### ISSUE THREAD

**Issue by RDS88-beeman** [BeeStation/BeeStation-Hornet#4652]
## Round ID:
30803

## Testmerges:
#4415: 'Let's see if this helps anything at all.' by francinum at commit 41b343ce2c
#4380: 'Security Rework Part 1 of ?: Energy pistols' by ike709 at commit c10d3a13cb
#4357: 'Ports new overlay lighting component and opacity refactor from tg' by yorii at commit 0f934881d1

## Reproduction:
Mix the required ingreedients for Ash Mutation Toxin as per https://wiki.beestation13.com/view/Guide_to_chemistry#Mutation_Toxins
It doesn't do anything

**Comment by Ivniinvi** [comment]
The wiki recipe is incorrect, it requires 10 parts ash in addition to the listed reagents.

**Comment by RDS88-beeman** [comment]
ah well consider this a wiki report then

**Comment by Ivniinvi** [comment]
I have corrected the wiki just now.

**Comment by RDS88-beeman** [comment]
Thank you kindly
