### ISSUE TITLE
Creating new books as a heretics comes with a free point

### ISSUE THREAD

**Issue by Goblinu** [BeeStation/BeeStation-Hornet#4667]
## Reproduction: Create a new book as a heretic

When you create a new book as a heretic through the circle the new books comes with a free point, this can be repeated infinitly to create a points if you just repeat this proccess over and over.

**Comment by RDS88-beeman** [comment]
Can confirm, was trying to test (and also avoid killing) on discovered round. Actually discovered some rounds earlier but wasn't sure enough to make an issue report for it.

**Comment by eeSPee** [comment]
Like I said in my PR, not sure if it's an oversight, or it's a reward for getting through the hassle of getting human skin.
