### ISSUE TITLE
TGUI fails to load a stylesheet and breaks

### ISSUE THREAD

**Issue by KittyNoodle** [BeeStation/BeeStation-Hornet#4669]
Issue reported from  Round ID: 30871 (BeeStation Sage - Roleplay)

Reporting client version: 514.1556

Error: Error: Failed to load the stylesheet 'font-awesome.css' after 5 attempts.
It was either not found, or you're trying to load an empty stylesheet that has no CSS rules in it.
   at node.onload (http://127.0.0.1:59107/tmp48992/browseroutput.html:258:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)
State: {"ckey":"noodlecat","window":{"fancy":0,"locked":0}}

**Comment by ivanmixo** [comment]
this is on your end

**Comment by KittyNoodle** [comment]
yes

**Comment by KittyNoodle** [comment]
what do you mean.

**Comment by KittyNoodle** [comment]
how do i fix it.

**Comment by KittyNoodle** [comment]
>have a gamebreaking bug
>coder tells me it is on my side
>does not tell me how to fix it

**Comment by ike709** [comment]
Have you tried clearing cache?

**Comment by ike709** [comment]
Also this is likely a 514-only issue so you could try switching to 513

**Comment by ike709** [comment]
There's actually a bug related to this that might be fixed in 1557 so you should try updating your 514 build first.

**Comment by ike709** [comment]
Also let me know if 1557 fixed it for you.

**Comment by ike709** [comment]
I'm confident that this is a BYOND version issue.
