### ISSUE TITLE
IPC spawned as changeling

### ISSUE THREAD

**Issue by VictorVow** [BeeStation/BeeStation-Hornet#468]
Round 7508, A.N.O.M.A.L.Y. was an IPC that started as a changeling. Later varedited to a human name Andrew Jones.

**Comment by St0rmC4st3r** [comment]
Same issue here. IPC spawned as a human changeling with a custom IPC name (Chmod -xrw) also in objectives there was an assassination of BOB-, who was too an IPC changeling.

**Comment by ike709** [comment]
Were they actual IPCs or just humans with IPC names? The latter is a known issue.

**Comment by St0rmC4st3r** [comment]
Humans with IPC names. Also, apparently, such human IPCs are a valid assassination target for changelings.

**Comment by VictorVow** [comment]
Hmm yeah actually it was the latter.

**Comment by SomeAngryMiner** [comment]
should have been fixed a long time ago with the port.

**Comment by Kerbin-Fiber** [comment]
So this should be closed
