### ISSUE TITLE
bio bag interaction with reproductives is broken

### ISSUE THREAD

**Issue by RDS88-beeman** [BeeStation/BeeStation-Hornet#4701]
## Round ID:
30977

## Reproduction:
Using a bio bag with monkey cubes in it on a reproductive extract causes it to attempt to pick up everything on the tile instead of autofeeding the reproductive.

**Comment by yrokhlin** [comment]
I was going to post the same issue, this is extremely frustrating.

**Comment by Sapfearon** [comment]
20 days later we still have broken bio bags.
