### ISSUE TITLE
Can't get contraband from vendors

### ISSUE THREAD

**Issue by VictorVow** [BeeStation/BeeStation-Hornet#472]
I've been trying on and off for weeks now and I can't seem to turn on the contraband light like I used to. At first I thought ah it's just because they don't have contraband this shift, but the amount of times I've tried it makes me think it's actually just bugged right now.

**Comment by St0rmC4st3r** [comment]
How exactly are you trying to turn the contraband on?

**Comment by Arrfur** [comment]
And what machine*. Autolathe? Vending machine?

**Comment by despong** [comment]
screwdriver vending machine and use multitool until green light is on, wires are random every round, close
for more stuff you can use an emag or a coin

**Comment by VictorVow** [comment]
I was using wirecutters instead of a multitool, you can close this.
