### ISSUE TITLE
Game Breaking Pseudo TK Glitch

### ISSUE THREAD

**Issue by FortSumter** [BeeStation/BeeStation-Hornet#4737]
Issue reported from  Round ID: 31061 (BeeStation Golden)

Reporting client version: 513.1542

A BB roboticist was able to both grab and throw objects at range while inside of a mech suit. This was near round start at the roboticist as an IPC. He didn't have TK and yet he was capable of abilities like TK. The HOs (myself) was shive stunned at range by him while his BB killed me.

**Comment by KittyNoodle** [comment]
grav catapult go brrrr

**Comment by FortSumter** [comment]
Turns out the mech user rushed the grav catapult, which is somehow a more effective version of TK, and it only costs 5 iron. Not exactly a bug, but its still broken.

**Comment by KubeRoot** [comment]
> Turns out the mech user rushed the grav catapult, which is somehow a more effective version of TK, and it only costs 5 iron. Not exactly a bug, but its still broken.

I think grav catapult requires energy, like most mech things. Considering this requires you to build a mech, get a grav catapult on it, supply it with power, and deal with the bulkiness of a mech, I don't think it's broken, rather a powerful strategy.

Could've probably been countered by Ion rifle/EMP, or defeated simply by attacking it with more people and overpowering it. Seeing as BBs do not get any advantages beyond stealth communications, they need viable ways to fight.

**Comment by BrumalLake** [comment]
are you gonna close this or what
ideas arent exactly issues, but i will say that grav catapult having no indication that someone is using it is stupid and annoying
shitter robos keep messing with me and it takes me a while to notice that bastard ripley with 5 fathers sitting in the corner quietly "watching" me
