### ISSUE TITLE
No TGUI on connect

### ISSUE THREAD

**Issue by rockcabbage** [BeeStation/BeeStation-Hornet#4740]
Nanotrasen incident handler at https://github.com/tgstation/tgstation. Thank you for your cooperation. 
 UnhandledRejection: Failed to open IDB: UnknownError
   at null:null
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {}

UnhandledRejection: UnhandledRejection: Failed to open IDB: UnknownError
   at null:null
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {}

UnhandledRejection: UnhandledRejection: UnhandledRejection: Failed to open IDB: UnknownError
   at null:null
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: Failed to open IDB: UnknownError
   at null:null
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)
State: {}

UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: UnhandledRejection: Failed to open IDB: UnknownError
   at null:null

**Comment by ivanmixo** [comment]
This is on your end. What byond version are you on?

**Comment by Archanial** [comment]
Update to 514.1557

**Comment by stylemistake** [comment]
This error happens inside `tgui/packages/common/storage.ts`, coming from IndexedDB, but this kind of error should disable the IndexedDB backend. Someone, make sure that part is up to date with tg and if not, then maybe you can come up with a fix.

**Comment by Sinestia** [comment]
> 
> 
> This error happens inside `tgui/packages/common/storage.ts`, coming from IndexedDB, but this kind of error should disable the IndexedDB backend. Someone, make sure that part is up to date with tg and if not, then maybe you can come up with a fix.

Looks like we're missing https://github.com/tgstation/tgstation/pull/53294

I'll submit a PR, tyvm for bringing this up.
