### ISSUE TITLE
Prototype Cloner

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#4747]
Issue reported from  Round ID: 31094 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542

The prototype cloning definitely doesn’t work anymore.
I blame the rework of the main cloning machin.

**Comment by jupyterkat** [comment]
gimme more detail wanker

**Comment by MNarath1** [comment]
Thats not enough info if you want us to test this give us exact steps to reproduce this even if its just open the ui and try this or something.

**Comment by Mails-z** [comment]
It just doesn't work. You try to clone someone, it makes a sound and then
don’t clone him. It doesn't eve give a problem notification.

**Comment by jupyterkat** [comment]
tried adding like some frickin synthflesh to the cloner itself?

**Comment by Mails-z** [comment]
The lack of synthfleshwas definetly was not the problem

**Comment by pro100Player** [comment]
+
It doesnt work at all. Before the update it would clone the body in the scanner no matter what, if it doesnt have synthflesh, it spits the totally screwed body out of pod instantly or almost instantly. If it does have synthflesh, it starts cloning properly and, most importantly, sends an offer to all ghosts to occupy take control of the body.
And, I repeat, it doesnt even start the process at all, even if the pod is full of synthflesh, local APC has charge, and with ghosts nearby.
We tried with dead body, soulless body, monkey, humanized monkey, dead monkey, empty clone from regular cloner. It just doesnt work.
upd1. before this update (https://github.com/BeeStation/BeeStation-Hornet/pull/4364) it was working as intended.

**Comment by EvilDragonfiend** [comment]
I tried to fix this shit at my PR. Please reopen the issue if my PR didn't catch your issue properly. (It's not merged yet.)
