### ISSUE TITLE
Forced chat should not count towards the IC filter

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#476]
Yesterday when i played clock cult i got muted because of spaming Cult Spells in a too short timeframe (i teleported in and out to cog apc‘s) i suggest to whitelist things like cult spells for clock and blood also even when muted you can still speak in cult chat normally that would be heared by nearby crewmembers as wispher but if you are muted its not the case making it possible to abuse this like standing directly beside a normal crewmember and ready a spell without them noticing or chatting with your fellow cult members while standing beside a security guard.

**Comment by yorii** [comment]
Confirmed as not stale

**Comment by DatBoiTim** [comment]
Is this issue still live?
