### ISSUE TITLE
I have this error, what do I do?

### ISSUE THREAD

**Issue by SodaCanInSpace** [BeeStation/BeeStation-Hornet#4776]
Issue reported from  Round ID: 31215 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542

![image](https://user-images.githubusercontent.com/87235069/125165760-a3491680-e1ad-11eb-878f-7b674bb2adb1.png)

**Comment by ike709** [comment]
Clear your BYOND cache

**Comment by SodaCanInSpace** [comment]
> Clear your BYOND cache

thank you, its fixed.
