### ISSUE TITLE
Entertainment Monitors can be activated from a distance

### ISSUE THREAD

**Issue by yyzsong** [BeeStation/BeeStation-Hornet#4783]

**Comment by RDS88-beeman** [comment]
I think this is at least SOMEWHAT intentional, because you can watch TV without standing directly next to the TV

**Comment by ivanmixo** [comment]
Clicking on it by accident and having it freeze your client for a while is pretty annoying though. Although this is definitely intentional judging by the code comment.

**Comment by BrumalLake** [comment]
all nt crew come with a remote for the entertainment monitor
it is hidden for convenience's sake
