### ISSUE TITLE
Stargazer and luminescent powers don't work

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#4788]
Issue reported from  Round ID: 31255 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542

Stargazers can't slimelink. If you try, you will get the message that you are attempting to link and the progress bar, but nothing will happen at the end. No confirmation message, and no link. Luminescents also can't use their activation powers: once you incorporate an extract, the activation buttons light up but stay empty, as if there were no core inside of you, and pressing the buttons does nothing (both major and minor).

**Comment by Sapfearon** [comment]
yep, it's true.
