### ISSUE TITLE
Bronze floor has no burned sprite.

### ISSUE THREAD

**Issue by r1ks-iwnl** [BeeStation/BeeStation-Hornet#4795]
## Reproduction:
Release burning plasma over bronze tiles.
Tiles will turn completely black and examine icon shows you Pepe the bronze floor.
![Screenshot_2](https://user-images.githubusercontent.com/69760936/125338196-93ba0100-e358-11eb-8e8c-8d366e468736.png)

**Comment by BrumalLake** [comment]
![image](https://user-images.githubusercontent.com/85033680/125362158-0b296980-e334-11eb-9d8b-c28bf60b97e9.png)
i remember seeing a lot of pepe cult stuff something to do with clockies when i used object sorting in dream maker before
