### ISSUE TITLE
You can't hear your own instrument while in a locker, but others can.

### ISSUE THREAD

**Issue by ivanmixo** [BeeStation/BeeStation-Hornet#4797]
## Round ID:

Local.

## Testmerges:

Local.

## Reproduction:

1. Start playing a song on an instrument
2. Get in a locker, or if you're a pAI get scooped up
3. Others can hear the instrument, but you can't.

**Comment by MNarath1** [comment]
reason for this is cause ``hearers`` will not check for contents of objects mobs etc this was introduced by a code change that replaced ```get_hearers_in_view``` with ```hearers``` but unlike the former hearers will not check for in the vars of a mob / content list of a locker.
