### ISSUE TITLE
Tracking beacons should only be placeable when the mech has maint protocols on.

### ISSUE THREAD

**Issue by KittyNoodle** [BeeStation/BeeStation-Hornet#4803]
100% spite. Tired of mechs being killed in effectively one shot by attaching a beacon and spamming emp.

**Comment by Mick1299** [comment]
alternate proposal, mechs should have a detonate option just like borgs. So you can destroy a rogue mech in one click, instead of having to spam emp them

**Comment by jupyterkat** [comment]
just add a delay to attatching all mech weapons/modules lol
