### ISSUE TITLE
Corg AI upload turret control does not work.

### ISSUE THREAD

**Issue by Cirrial** [BeeStation/BeeStation-Hornet#4805]
Issue reported from  Round ID: 31302 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542

Trying to turn the turrets on does not work.

**Comment by Sarchutar** [comment]
Do you mean that when you turn the turrets off and back on again that they won't do anything? If yes then it is probably related to what i wrote on #4782.

Or do they just start turned off and need to be manually turned on?

**Comment by Cirrial** [comment]
They start on and don't seem to do anything.

**Comment by Sarchutar** [comment]
Okay i just tested them on a local server and they seem to work like they should roundstart.

Did someone maybe turn them off or did the room lose power for a bit at one point?
