### ISSUE TITLE
Clockcult: Eminence issues

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#4818]
issues found with eminence

1. Jumping to servant simply doesnt work, only message is "You can't jump to them"
2. Manifesting and demanifesting with the abstraction crystal causes it to be destroyed because the ghost is dusted.
3. no way to tell how many cogs you have
4. Bend reality doesn't seem to have any effect no matter what you choose

**Comment by Archanial** [comment]
@PowerfulBacon
