### ISSUE TITLE
The Characters in the Character preview get set on fire after Rat'var appears.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#4820]
Issue reported from  Round ID: 31329 (BeeStation Sage - Roleplay)

Reporting client version: 514.1557

![image](https://user-images.githubusercontent.com/82319489/125690950-22369d25-0651-40bb-8d13-c823a7798988.png)

**Comment by Mick1299** [comment]
Amazing, call it a feature
