### ISSUE TITLE
IPCS have Encoded Audio Language (EAL) but can't speak it, despite being robotic

### ISSUE THREAD

**Issue by despong** [BeeStation/BeeStation-Hornet#483]
i can't speak robot despite being robot, for some reason but i can understand it
![cringe sa fuck](https://user-images.githubusercontent.com/56105176/66102552-75ea2600-e54e-11e9-83a7-4c5b4610ec81.PNG)
edit : this probably has to do with something with ipc using human language tongue, as in, they can only speak galactic common or something, i can't really explain it at this time, if i can guess

**Comment by SomeAngryMiner** [comment]
Works as intended.
