### ISSUE TITLE
Unknown bug causing AI static to disappear

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#4839]
Round 31379, AIs static overlay disappeared allowing it to see anywhere on the z level. Couldn't reproduce.

**Comment by Archanial** [comment]
It's actually known for about 2 years.

**Comment by AnCopper** [comment]
This has been known for a long time but nobody really knows what triggers it.

**Comment by TheGreyDiamond** [comment]
So my story of today about this:
It was night shift lighting, I had Camera Lights on. I was able to see all maint shafts but was not able to interact. After (probably) the change to normal daylighting the noise returned.

Round was 32551

**Comment by AnCopper** [comment]
/tg/station has a fix for this.
https://github.com/tgstation/tgstation/pull/63666 
@ike709 Please add this to 'things to port'
