### ISSUE TITLE
Piercing Hypospray upgrade for the medical borg breaks it

### ISSUE THREAD

**Issue by ZombiesVsPlants** [BeeStation/BeeStation-Hornet#4850]
## Reproduction:
1. Be a medical borg
2. get expanded hypospray
3. get piercing hypsopray
4. try to inject someone with penetic 
5. End up injecting them with mannitol
6. chems never recharge no matter how long you wait (keep clicking on person with mannitol/penetic acid it will eventually say that the hypospray is out, it will never refill no matter how long you wait or if you go to a borg charger)
7. If you inspect the hypospray the list is double the proper size with duplicate chemicals yet no way to access them
8. It should be noted that this was a medical shell for the ai, but it is most likely still a problem for medical borgs.

**Comment by Mick1299** [comment]
Its still an issue for normal borgs. I think it occurs if you have the hypospray equipped as one of your three tools when the upgrade is inserted. 

Had this happen to me around a week ago, resetting the borg to default and having them reselect medical doesn't fix the issue. You need to fully deconstruct to fix it.

edit: All of my testing was on sage, its not a downstream issue

**Comment by ZombiesVsPlants** [comment]
Mick is right

![image](https://user-images.githubusercontent.com/60122079/126930887-731024d0-7f63-468f-a872-cf775c1f3cad.png)

**Comment by KubeRoot** [comment]
Tried reproducing on a local server, seems to work fine. Could you try testing if the issue is still present, and if yes, try to provide more detailed reproduction steps?
