### ISSUE TITLE
Space Law Books are broken.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#4855]
![image](https://user-images.githubusercontent.com/82319489/126081490-b784fb72-afa6-49e7-a4aa-5c4bc6e1812b.png)

**Comment by ike709** [comment]
...Can you give the error message in english?

**Comment by AnCopper** [comment]
> ...Can you give the error message in english?

This content cannot be displayed in a frame.

To protect the information you provide on this website, the publisher of this content has prohibited the content from being displayed in a frame.

**Comment by yurara** [comment]
same problem here, but I prefer to see them in Chrome browser though.

**Comment by ivanmixo** [comment]
This extends to all the books.
