### ISSUE TITLE
Infinite use cyborg endoskeleton bug

### ISSUE THREAD

**Issue by DallasRatcliff** [BeeStation/BeeStation-Hornet#4893]
## Round ID:

31521

## Testmerges:

#4882: 'Testing Revert of Hearer Changes *one more time* [DNM]' by francinum at commit 5dabaf5b94

## Reproduction:

Have a complete cyborg endoskeleton and a BORIS module, spam click on the cyborg endoskeleton with it and it will make the AI shell and a cyborg endoskeleton that can be used infinitely.

**Comment by MNarath1** [comment]
Said test merge is a revert of another PR so in this case it should be unrelated
