### ISSUE TITLE
"Lawyerspeak" emotes are gone

### ISSUE THREAD

**Issue by Fresh839** [BeeStation/BeeStation-Hornet#4895]
## Round ID:
Every round

## Testmerges:

Could've been caused by the "recent" runechat/overhead chat update to include emotes. Not 100% sure though.

## Reproduction:

Normally when you play as a lawyer and attach your attorney's badge to your jumpsuit there should be some nice emotes appearing next to your head when you speak. For example a big red exclamation mark, or question mark for questions. It gives that ace attorney vibe. Well all of this is just gone. It doesn't work anymore. It's been like this for a long while too. I am not a 100% sure but i think it stopped working when the overhead chat got updated.

**Comment by ivanmixo** [comment]
It works, but only with runechat off.

**Comment by Fresh341** [comment]
Thank you for the reopen, yeah it's still an issue.
