### ISSUE TITLE
Invisible slimes

### ISSUE THREAD

**Issue by Rebelord01** [BeeStation/BeeStation-Hornet#4896]
## Reproduction:

1. aquire warping grey extract
2. place 8 extracts of dark blue(any may work but i know dark blue works for sure) on the rune
3. activate
4. notice the lack of slime, however the rune and extracts are gone
5. right click where you think the slime may be and you'll see that its there just invisible

note: if you manage to make a hybrid of it, the produced extract will not appears to not exsist

**Comment by KubeRoot** [comment]
Assuming this is a duplicate of https://github.com/BeeStation/BeeStation-Hornet/issues/3811, fixed by https://github.com/BeeStation/BeeStation-Hornet/pull/5425
