### ISSUE TITLE
Plasma seems to be extremely difficult to light with sparks

### ISSUE THREAD

**Issue by ivanmixo** [BeeStation/BeeStation-Hornet#4923]
## Round ID:

n/a

## Testmerges:

n/a

## Reproduction:

For example, try lighting the turbine or the toxins burn chamber, or hell try breaking a light in a main hall when it's absolutely filled with plasma. The tiles the sparks are on light, but extinguish themselves immediately as soon as the sparks disappear. Only way to circumvent this is throw in a welding tool or a lighter.

**Comment by williamcll** [comment]
Best way is to use the sparks of a rapid pipe dispenser.
