### ISSUE TITLE
Need a way to reset chat settings

### ISSUE THREAD

**Issue by ike709** [BeeStation/BeeStation-Hornet#4936]
Someone managed to make their font so big that their chat became useless and also they couldn't fix it.

**Comment by ike709** [comment]
Alternatively just reduce the cap to 24 here: https://github.com/BeeStation/BeeStation-Hornet/blob/master/tgui/packages/tgui-panel/settings/SettingsPanel.js#L126

**Comment by ToasterBan** [comment]
happened to me before, clearing IE cache fixes it

**Comment by PowerfulBacon** [comment]
Its not really a fix but you can revert it by just making the stat window bigger.
![image](https://user-images.githubusercontent.com/26465327/127016894-6fed8d91-b1ca-4fbc-9147-65fcef9e58f2.png)
