### ISSUE TITLE
AI can strip people

### ISSUE THREAD

**Issue by Ivniinvi** [BeeStation/BeeStation-Hornet#4950]
## Round ID:
31642

## Testmerges:
#4939: 'Hearing revert round whatever [DNM]' by francinum at commit db6b8402c0
#4836: 'Stat panel verb caching' by PowerfulBacon at commit ba7de817fa

## Reproduction:
Be cuffed/clothed
Stand next to AI
AI can uncuff/strip people like humans

**Comment by BrumalLake** [comment]
again

**Comment by ghost** [comment]
It's a feature. the AI could hypnotize people to strip and ERP

**Comment by ZombiesVsPlants** [comment]
This is funny

**Comment by Mat05usz** [comment]
Isn't it intended so AI may max people's sensors? :flushed:

**Comment by FriendlyContractor** [comment]
While this is rather not an intended feature its so absurd i want it to stay 😆

**Comment by kit-katz** [comment]
how else im i going to turn up THEIR sensors 
keep it
