### ISSUE TITLE
pAIs can't see or use custom emotes and looc when carded, held, or worn

### ISSUE THREAD

**Issue by Skies-Of-Blue** [BeeStation/BeeStation-Hornet#4968]
## Round ID:
N/A

## Testmerges:
#4939: 'Hearing revert round whatever [DNM]' by francinum at commit db6b8402c0

## Reproduction:
As a pAI, custom emotes AND looc are not visible/usable while you're carded. If the pAI is in holochassis, being carried or worn also removes the ability to see/use custom emotes and looc.

**Comment by ivanmixo** [comment]
Linked to my issue (#4797). I think the pAI's loc just set to null when they get turned into an item.
