### ISSUE TITLE
Virology: Necropolis Seed Stealth Threshold generates a battery.

### ISSUE THREAD

**Issue by Dethstorm** [BeeStation/BeeStation-Hornet#4972]
### Round ID:
31665

Necropolis Seed's Stealth 8 Threshold (Host gets dusted upon death, and generates an unholy artifact) generates a standard computer battery instead of any sort of lavaland loot/unholy artifact. I've been told it was caused by a change to the lavaland loot system, but I'm unsure. Reproduction is simple, get Necropolis Seed, add symptoms to reach Stealth 8, infect yourself, get a weapon of your liking and kill yourself with it. Your body will dissapear and a standard computer battery will appear.

**Comment by BrumalLake** [comment]
that battery is from the janitor's tablet which they come with
pretty sure someone ported some qdel stuff which fixed it but it's apparently been back for a while now
i dunno about the symptom dropping some artifact though

not sure about that someone port this https://github.com/tgstation/tgstation/pull/45342
