### ISSUE TITLE
Light bulbs do not update 

### ISSUE THREAD

**Issue by Sinestia** [BeeStation/BeeStation-Hornet#4973]
## Round ID:

N/A

## Reproduction:
![unknown 1](https://user-images.githubusercontent.com/40812746/127429876-d40ef60a-4aef-4519-8606-726b2831257c.png)

just look at a wall, the tube is on but looks as if it were off. Applies to both tubes and bulbs. 

Not sure how old this is or what may have broken it. 

edit: it's been broke for awhile, I checked out a commit in may and it was wrong too.

**Comment by ivanmixo** [comment]
Oh wow, we actually don't have seperate sprites for "light on" and "light off".

**Comment by ike709** [comment]
It's an overlay iirc

**Comment by Sinestia** [comment]
cyka blyat
