### ISSUE TITLE
Power Loss Breaks the Holodeck It Seems

### ISSUE THREAD

**Issue by Sinestia** [BeeStation/BeeStation-Hornet#4974]
## Round ID:

31670

## Reproduction:

Holodeck broke with a 
`line 225: Cannot execute null.load().`

after a grid check occurred while it was being utilized. It could no longer be used once power was back, and required respawning (deconstructing would have probably worked too.)

Unfortunately that's the best info I have, haven't attempted to play it locally.

**Comment by KubeRoot** [comment]
This might've been fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/5153, I wasn't aware of this issue but I fixed some runtimes that broke it I encountered at the time, might need further testing.
