### ISSUE TITLE
Change message on Sage when server is full

### ISSUE THREAD

**Issue by TheGreyDiamond** [BeeStation/BeeStation-Hornet#4994]
When the server is full, this message shows up:

![Screenshot](https://cdn.thegreydiamond.de/img/2021/07/31/2021-07-31_18-35-53-18233e66-1d42-41a7-8035-00cbc01fb95c.png)

Golden is dead. Maybe change it.

RIP Golden.

**Comment by Crossedfall** [comment]
Already handled, but I'll leave this issue open so it can be linked to the repo restructure later.

**Comment by TheGreyDiamond** [comment]
So we can close this now?
