### ISSUE TITLE
You can still hear a pAI in a Mule-bot after being deafened by an explosion.

### ISSUE THREAD

**Issue by FlamesWillLive** [BeeStation/BeeStation-Hornet#5011]
Issue reported from  Round ID: 31749 (BeeStation Acacia)

Reporting client version: 513.1536

Might be related to #4939, since that changes hearing. As it said in the title, Topaz Sampson lost his hearing form a Kudzu explosion, yet was still able to hear rounds the pAI while they were in a Mule-bot. I couldn't hear myself, and I don't know if I was able to hear others, but I definitely heard rounds.

**Comment by Ivniinvi** [comment]
Symptom of #5044
