### ISSUE TITLE
Blind players only able to perceive very limited emotes.

### ISSUE THREAD

**Issue by KieraKatsura** [BeeStation/BeeStation-Hornet#5024]
## Round ID:
N/A

## Testmerges:
Unsure - Issue present since roughly June 28-30th, believe around same time there were issues with [Balloon Alerts for #4414](https://github.com/BeeStation/BeeStation-Hornet/pull/4414). When only Runechat was present, did not have any issues as best I can recall. Sorry I don't have more I can reference to help!

## Range of Issues:
- Hearable emotes no longer available for crewmembers to utilize around blind crewmembers. (Formerly accessible via T -> Enter -> (write out the custom emote) ->  select Hearable -> Enter) This functionality disappeared around the dates above during teething issues with Balloon Alerts. [This cumbersome process was also the only way for players to interact with blind crewmembers outside of the (T *help) emote list.]

- Only some emotes that are part of the (T *help) list, even audio emotes, are perceivable in the text box to blind players. For example, T *inhale/T *exhale cannot be perceived. 
- Blind players cannot see their own ( M / T *help / T *Me) emotes in the chatbox. 
    -- The only ones blind players can see in the chatbox that they used, are the ones perceivable to blind players, such as (T *shiver) or (T *sigh). Emotes such as (T *Inhale) are not noted in the chatbox. All (M and T *me) emotes cannot be seen. Thus, blind players have to rely on their memory for what actions they have done in the past few minutes, and cannot tell if some emotes even work from the (T *help) list.
- Custom emotes via (M or T *Me) are completely un-perceivable, this is probably the biggest one. 
     --Now I miss out on actions such as say someone placing a hand on my shoulder, or someone awkwardly coughing, versus what is only available to me to hear such as (T *cough). Nuance in RP is no longer available as blind players can only rely on conversation and the limited, somewhat broken list of (T *help) emotes.

## Reproduction:

Play as a blind character for a few rounds and try to RP. 

Have someone go through the (T *help) emote list and use them by you.

## Ideal World Solution:

Just being able to see (M or T *Me) custom emotes in the chatbox would allow for so much more RP for blind players. I cannot even see my own custom emotes in the chatbox as noted above. Having reached out to other players with blind characters, this was the solution we saw best. As it allows us to have more nuance in RP interacting with others, while also being able to track our own custom emotes in a situation.

- **Potential issue(s)** with this solution: blind players being able to perceive the body language of someone across the room (Ex: M Subtly lowers his hand to his revolver)
     -- With the move toward heavier RP on Bee, I think blind player mains are responsible enough to know what their character should, and should not be able to perceive. Very few people stick to this trait in the first place. Players with characters that can see are also generally blind for a few minutes at most.
     -- I also think this is a non-issue in that it allows "oblivious" blind players to OOC follow along with RP happening in the same room. (Any bit of RP we can get IC or follow OOC makes up for playing as a blind character)

**Comment by Pirill** [comment]
I cannot second this enough, being able to see all emotes when blind would make it bearable to play a blind character again and frankly should be the expected functionality, with the players using common sense for what they should or shouldn't know.

I have actually cryo'd for more rounds than I could bring myself to see through (pun intended) to the end lately because not only is it hard enough to chase anyone willing to RP with a blind character but when you can't even see YOUR OWN emotes, let alone anyone else's, a big part of that enjoyment is gone. It was bad enough as it was with most players not knowing audible emotes were a thing, but now it's just frustrating to have to deal with, both for myself and for the people I interact with.

**Comment by Archanial** [comment]
@PowerfulBacon

**Comment by KieraKatsura** [comment]
If it um, comes to it, I would be okay with a code bounty if told how to set one up. This really impacts my game and I know blind characters are a very small minority :(

**Comment by ike709** [comment]
Custom emotes were fixed in #5365

**Comment by KieraKatsura** [comment]
> Custom emotes were fixed in #5365

Thank you Ike
