### ISSUE TITLE
Nurse Outfit is replaced with a different item when buying from store

### ISSUE THREAD

**Issue by Quink-Fix** [BeeStation/BeeStation-Hornet#5025]
Problem Description: When using Austation's store (presumably shared with Beestation) to buy a medical nurse uniform for pre-round loadout in outfits, the player spawns with a regular medical jumpsuit held in their hand on top of whatever they chose to wear (jumpsuit/jumpskirt in customisation).

What did you expect to happen: The nurse outfit spawning in the player's hand.

What happened instead: A standard MD jumpsuit spawned instead.

Why is this bad/What are the consequences: Seeing as the player spends earned currency on this, they are wasting their time played buying something that doesn't work. This is bad.

Steps to reproduce the problem: Use the pre-round store to buy the nurse outfit. Equip it. Spawn in with a medical profession (MD, paramedic, CMO)

Server: Austation

Revision: Server revision compiled on: 2021-08-03T02:36:46+00:00
Master commit: bcdd7babe0ce70c64fb8ebd0076be3b207f4a301
TGS version: 4.12.1
![unknown](https://user-images.githubusercontent.com/88389357/128033987-7772b4cc-de3f-4090-96f7-5f0e09d4a88d.png)

DMAPI version: 5.3.0

Possibly related stuff: Happened in secret gamemode twice in a row, but I'm assuming that has no bearing on the issue considering its nature.

Terra identified that the issue is that the code is referring to the wrong object path, so this should be a relatively easy fix in code. I'd do it myself if I knew anything about contributing.

**Comment by Quink-Fix** [comment]
Not sure why the image rendered in the middle. Oh well.

**Comment by BrumalLake** [comment]
we have a nurse outfit?

**Comment by Quink-Fix** [comment]
Apparently.
