### ISSUE TITLE
Luminescant slime minor and major activations broken

### ISSUE THREAD

**Issue by psychnurse** [BeeStation/BeeStation-Hornet#5053]
## Round ID: 7613 

Discovered on austation

Issue seems to be that luminescant slimes are unable to use slime cores. Tried to use the grey, yellow, blue and bluespace slimes to no effect. Minor and major activations seem to be broken

**Comment by imsynthex** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/5051 should fix this
