### ISSUE TITLE
can't touch or smother with rags anymore

### ISSUE THREAD

**Issue by BrumalLake** [BeeStation/BeeStation-Hornet#5058]
## Round ID:
31890

## Reproduction:
use disarm intent, use harm intent, it just makes you start wiping the person down and if you do it to yourself while you're masked it tells you to remove your mask first but wipes you down anyways mask or not

**Comment by ivanmixo** [comment]
It needs to have reagents in it. Seems to work fine.

**Comment by BrumalLake** [comment]
swear i put some honey in it dunno
