### ISSUE TITLE
can't unbuckle restrained people from tables while grabbing them

### ISSUE THREAD

**Issue by BrumalLake** [BeeStation/BeeStation-Hornet#5059]
## Round ID:
31890 long-term bug

## Reproduction:
try clicking the optable, it just tells you that they're buckled to the optable
it attempts the place on table action

**Comment by KubeRoot** [comment]
From a quick look at the code, it seems like this should happen specifically if you're pulling the person, since clicking the table attempts to place them on it while they're already buckled to it. Have you tried reproducing it after letting go of them?

**Comment by BrumalLake** [comment]
now that's stupid, cause i grab them before unbuckling so they don't bolt

**Comment by KubeRoot** [comment]
Maybe it's stupid, but makes sense, it's an oversight due to clicking having two different actions on tables. I guess clicking on the same table the person you're holding is buckled to should unbuckle them, unless there's a better suggestion.
