### ISSUE TITLE
You can no longer put a speed potion on clown shoes

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/BeeStation-Hornet#506]
## Reproduction:
Spawn in a speed potion and clown shoes, if you try to use said speed potion on the shoes it does nothing but go into the shoes. If the shoes are already full you'll just get a message that they are too full.
Speed potion on clown shoes usualy made you run much faster, so this is a sad aspect.

**Comment by SomeAngryMiner** [comment]
try harm intent?

**Comment by GoatMonarch** [comment]
> try harm intent?

Very certain that I tried that as well, though I may remember it incorrectly

**Comment by GoatMonarch** [comment]
Some month later I got the opportunity to test. Harm intent does not work. You need a mutated red slime core which reduces weight of all items on you, to get a speed potion effect. Sad.

**Comment by yorii** [comment]
Has been fixed at some point, clown shoes can now be made speedy.
Issue can be closed.
