### ISSUE TITLE
Codebase no longer compiles.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#5064]
Running BUILD.bat, it just does not work.
I get an error message saying that the file will not run on my computer, running as an administrator also doesn't fix this.

Here are my specs: 
OS: Windows 10 (64-bit)
CPU: AMD Ryzen 3600
RAM: 16GB
GPU: NVIDIA GeForce GTX 1660

![image](https://user-images.githubusercontent.com/82319489/128630181-e4041670-bccf-42dc-8827-dc648523ae1b.png)

"This app cannot be run on the PC

Contact the software publisher to find a suitable version for your PC"

![image](https://user-images.githubusercontent.com/82319489/128630241-d8f4795c-9a5c-4461-a856-f8e4d2796e05.png)

"Using vendored node Access denied
Access denied"

And yes, I am using vscode.

**Comment by Sinestia** [comment]
What's your path 

if it's in documents I think windows can get real dumb with permissions

**Comment by AnCopper** [comment]
> What's your path
> 
> if it's in documents I think windows can get real dumb with permissions

I put SS13 codebases onto my D drive so it doesn't clog up my SSD
D:\BeeStation-Hornet

**Comment by AnCopper** [comment]
I also think this exact same issue that I'm having is what makes the server die upon restarting.

**Comment by Sinestia** [comment]
> 
> 
> I also think this exact same issue that I'm having is what makes the server die upon restarting.

Nah, it seems to be a different issue. 

Try to pull a clean repo and tell me what happens, or run git clean -fdx.

**Comment by AnCopper** [comment]
> git clean -fdx.

Yeah it works now.

**Comment by Sinestia** [comment]
> 
> 
> > git clean -fdx.
> 
> Yeah it works now.

Bless
