### ISSUE TITLE
Kinetic Accelerator Seclite Attachment Has No Light

### ISSUE THREAD

**Issue by dualdooter** [BeeStation/BeeStation-Hornet#5072]
## Round ID:
31911

Sage
## Reproduction:

Adding a seclite to a Kinetic Accelerator doesn't seem to be toggling its light properly now. An admin thinks it's due to the lighting update.

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/5060

**Comment by Sinestia** [comment]
Should be fixed now
