### ISSUE TITLE
Moth race lost welding protection while wearing proper welding gear

### ISSUE THREAD

**Issue by Syrox25** [BeeStation/BeeStation-Hornet#5074]
## Round ID: 
31911  (Still happened in that round but noticed it yesterday)

## Testmerges: 
N/A?

## Reproduction: 
Be Moth, equip Welding helmet, Engineering hardsuit or Welding Hardhat.
Still go blind from welding.

**Comment by Archanial** [comment]
Good

**Comment by Syrox25** [comment]
Witty response # 5

I mean.. If you want to change racial traits then fine... Go make a PR where that's the central issue instead of having it hit by something indirectly.

**Comment by St0rmC4st3r** [comment]
Works as intended. Moths need double layer of protection to weld.

**Comment by Syrox25** [comment]
Delightful... as if it wasn't bad enough...
Thank you for the stealth patch.
Guess its time to PR welding goggle accessibility

**Comment by AnCopper** [comment]
> Delightful... as if it wasn't bad enough...
> Thank you for the stealth patch.
> Guess its time to PR welding goggle accessibility

This has been like that for years.

**Comment by Syrox25** [comment]
Well apparently not within the last half year?

**Comment by St0rmC4st3r** [comment]
> Well apparently not within the last half year?

I can swear I saw a giant discussion about this about half a year ago and a PR being merged, but I can't find it now. Anyway, the lighting PR two days ago actually fixed a bug that was making the experimental welder no better in terms of flashing than the standard one.
And bugfixes do not require maintainer approval on the race balance topic. 

As for welding goggles accessibility, being able to order them via cargo would be a very good solution without outcompeting the welding helmets.

**Comment by Syrox25** [comment]
Is there any reason you shouldn't be allowed to print them same as welding helmets? They have the same vision reduction and require eye slot to be taken up.
Only 5-6 are available and generally locked away or unknown about.

Is welding goggles really going to be called out as power gaming?
Same as being allowed to choose second language on an RP SERVER

**Comment by St0rmC4st3r** [comment]
> Is there any reason you shouldn't be allowed to print them same as welding helmets? They have the same vision reduction and require eye slot to be taken up.

I just gave my opinion, you are free to PR whatever you see good for the codebase.

**Comment by PowerfulBacon** [comment]
Intentional
