### ISSUE TITLE
PDA lights and Flashlights stop functioning late round.

### ISSUE THREAD

**Issue by SergeiKoralev** [BeeStation/BeeStation-Hornet#5078]
## Reproduction:

Initially noticed at approximate round time 1:20:00, Acacia, noticed it before on both servers, but haven't made a bug report until now.

**Comment by ike709** [comment]
@Sinestia

**Comment by ivanmixo** [comment]
Okay so this is just a hunch, but maybe lights stop working after you get shot with a laser gun for some reason. Ive had a round where that happened.
