### ISSUE TITLE
Flashlight busted

### ISSUE THREAD

**Issue by FerretBox** [BeeStation/BeeStation-Hornet#5079]
Issue reported from  Round ID: 31944 (BeeStation Sage - Roleplay)

Reporting client version: 514.1557

Whenever I have a flashlight on and in my pocket, doesn't matter which one, the light is nowhere near my character. It is always in the top left of my screen, and makes maints super dark and scary :( I dont know how to fix it,

**Comment by ike709** [comment]
@Sinestia

**Comment by Sinestia** [comment]
This is bizarre, I couldn't get it to happen myself. 

Although I might test something ivan mentioned
