### ISSUE TITLE
Random Pacifism

### ISSUE THREAD

**Issue by apple5382** [BeeStation/BeeStation-Hornet#5083]
## Round ID: 31949
31949

**Comment by imsynthex** [comment]
Note: Pacifism can also come things that aren't brain traumas (xenobio and i think chems)

**Comment by apple5382** [comment]
@ImSynthex do you happen to know which xenobio items?

**Comment by imsynthex** [comment]
Stabilized light pink, as of https://github.com/BeeStation/BeeStation-Hornet/pull/4724

**Comment by AnCopper** [comment]
Peacekeeper Cyborgs have a chemical injector which has a chemical called "Pax" which pacifies People.

**Comment by mcmeiler** [comment]
Synthpax only pacifies people while it's in their bloodstream.
Stabilized light pink also only pacifies people while they have it on them.
