### ISSUE TITLE
cyborgs cannot screwdrive unactivated swarmers

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#5098]
## Reproduction:
![image](https://user-images.githubusercontent.com/43061493/129212678-bc5cd542-4ff5-4a5b-9b11-8c9f408200e3.png)
A cyborg cannot screwdrive a swarmer shell once it has been created, and must wait for it to activate then be destroyed.

**Comment by Sarchutar** [comment]
Works for me on a local server, i noticed that you need to be on help intent and not harm intent though. Maybe that was your problem?

**Comment by williamcll** [comment]
> Works for me on a local server, i noticed that you need to be on help intent and not harm intent though. Maybe that was your problem?

Might be the issue, I'll try it out later
