### ISSUE TITLE
Mark as complete doesn't work

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#5116]
I marked AI stay alive until the end as complete and it wasn't completed

**Comment by AnCopper** [comment]
AI's and Cyborgs count as dead for traitor objectives.

**Comment by Ivniinvi** [comment]
Survive's check for completion deliberately excludes things such as Silicons and Zombies. /datum/objective/survive/exist should be used in the event that a silicon needs to survive until the end.
