### ISSUE TITLE
Seeing through mulligan as AI via Holopads

### ISSUE THREAD

**Issue by rmarkus231** [BeeStation/BeeStation-Hornet#5140]
Seeing the original job of someone who mulligan'd without them wearing an id as an AI through relayed speech.
![image](https://user-images.githubusercontent.com/75732726/129646391-a7976d16-5310-4162-826c-0d3340c29e37.png)
The target in the picture is wearing no identification nor has the same identity as before (previously named Makes-The-Revolution)

**Comment by francinum** [comment]
virtualspeakers are awful.
