### ISSUE TITLE
instantly completing self surgery on bed with ghetto tools

### ISSUE THREAD

**Issue by BrumalLake** [BeeStation/BeeStation-Hornet#5141]
## Reproduction:
title
didn't experience it myself
just heard Contained Tesla Ball#2736 say it https://discord.com/channels/427337870844362753/801432004058939422/877015502248099882

**Comment by zeskorion** [comment]
ive noticed this a few times myself, when doing self surgery as an ipc to install new eyes

**Comment by BrumalLake** [comment]
got it pinned, turns out leaving the self penalty for self surgery and turf modifier in the same proc was a bad idea, the surgery speed can go negative and i presume before it just made the failure chance 100%
basically if you are on a bed or shittier which has a .5+ bonus and don't have a mirror which is a .6- you can get a negative multiplier

i don't think tg has a self operating penalty

**Comment by lordScrubling** [comment]
basically if you are on a bed or shittier which has a .5+ bonus and don't have a mirror which is a .6- you can get a negative multiplier
