### ISSUE TITLE
an error from adv. injector thing in mutation printer

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#5156]
## Reproduction:
![image](https://user-images.githubusercontent.com/87972842/130122917-0475dae5-37ca-4702-99d9-325a9245c016.png)

The Korean part means _ReferenceError: 'buuttonContent' is not defined_ if you are curious.
If you hit a button to go into an advanced injector category, It pops up and the printer becomes broken. The printer was not roundstart one and is made within the brig.

**Comment by ivanmixo** [comment]
Yeah, can confirm it just bricks the console if you pick adv. injector. Same thing happens if you click the chat client in the civillian computer.
