### ISSUE TITLE
Layer adaptors break if connected directly to a gas mixer.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#5162]
## Round ID:

32177

## Testmerges:

#5161: ''Archival Tape' Announcer' by francinum at commit 873a1440bc

## Reproduction:
![image](https://user-images.githubusercontent.com/82319489/130283458-40a8805d-7e80-410b-88b9-51e8da793bbc.png)

**Comment by ike709** [comment]
Layer adapters generally don't like other atmos machinery, it's not just mixers.
