### ISSUE TITLE
Fancy chat error

### ISSUE THREAD

**Issue by Alpkant** [BeeStation/BeeStation-Hornet#5171]
Issue reported from  Round ID: 32217 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542

Fancy chat gives the following error when try to reload.

Error: Error: Failed to load the script 'tgui-common.bundle.js' after 5 attempts.
   at node.onerror (http://127.0.0.1:52909/tmp10684/browseroutput.html:305:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)

Error: Error: Failed to load the script 'tgui-panel.bundle.js' after 5 attempts.
   at node.onerror (http://127.0.0.1:52909/tmp10684/browseroutput.html:305:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)

Error: Error: Failed to load the stylesheet 'tgui-panel.bundle.css' after 5 attempts.
It was either not found, or you're trying to load an empty stylesheet that has no CSS rules in it.
   at node.onload (http://127.0.0.1:52909/tmp10684/browseroutput.html:266:9)
User Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; Zoom 3.6.0)

Nanotrasen (c) 2525-2559

**Comment by ike709** [comment]
Things you should try, in this order:
* Clear your BYOND cache (There are instructions pinned in the discord somewhere)
* Run the `fix-chat` verb a couple minutes after joining (so assets are done downloading)
* Update to 514.1561
