### ISSUE TITLE
some part of Ruin is removed by rng chasm

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#5185]
## Reproduction:
![image](https://user-images.githubusercontent.com/87972842/130595377-185e7a0f-c5a5-45c5-af48-8a016bffbde7.png)

I think the image is enough.

**Comment by AnCopper** [comment]
@KubeRoot

**Comment by KubeRoot** [comment]
This should be fixed by https://github.com/BeeStation/BeeStation-Hornet/pull/5182

From what I can tell, a tendril spawned on the lava surrounding the ruin (would be deleted with the PR linked), got destroyed, either by a miner or perhaps by the lava, and spawned a chasm when destroyed.
