### ISSUE TITLE
IPCS can take cellular damage

### ISSUE THREAD

**Issue by despong** [BeeStation/BeeStation-Hornet#519]
## Round ID: 
7697 beestation lrp

## Reproduction:
Get a slime latched onto you. they do some cellular damage
(me, the ipc mime)
![me!](https://user-images.githubusercontent.com/56105176/66292058-11e19d80-e87f-11e9-83a3-707785887757.PNG)

![bruh!](https://user-images.githubusercontent.com/56105176/66292070-173ee800-e87f-11e9-8859-c75032fa6b77.PNG)

**Comment by ghost** [comment]
this is actually an easy fix, you just have to set their clone damage mod to 0, although im not sure if slimes will still try to drain you properly or not

**Comment by St0rmC4st3r** [comment]
IPC should also have a slime-friendly flag or however it works, like slimepeople do.

**Comment by despong** [comment]
ipcs taking cellular damage : the precursor to ipcs taking oxygen damage

**Comment by ghost** [comment]
ipc dont really need a reason to be in the slime faction, just set their genetics mod to 0 so they get bludgeoned to death instead by a slime

**Comment by SomeAngryMiner** [comment]
they do have clonemod 0, but slimes are hardcoded to do cellular damage, so i simply set it so they cant latch into IPC at all, for now.
this should be fixed when the ipc fix is merged.
