### ISSUE TITLE
Instruments don't play sound

### ISSUE THREAD

**Issue by QAI-07** [BeeStation/BeeStation-Hornet#5193]
## Round ID: 32266
Beestation Sage

## Testmerges:
#4543 Supercruise Part 2

## Reproduction:
Now a Detail to note is I was playing as a PAI at the time, so I'm not sure if this is just limited to them but either way,
1. Attempt to play music
2. Nothing happens, regardless of song or instrument.

**Comment by QAI-07** [comment]
Update: 

Apparently this was caused by the fact I had not entered my pAI holoform at all until that point. While in Holoform it is fully possible to play music, however returning to card form will immediately cease any music from being played.

**Comment by ivanmixo** [comment]
Linked to #4797, should hopefully be closed by #5136

**Comment by MNarath1** [comment]
> Update: 
> 
> 
> 
> Apparently this was caused by the fact I had not entered my pAI holoform at all until that point. While in Holoform it is fully possible to play music, however returning to card form will immediately cease any music from being played.
> 
> 

This might very well be because of you not beeing in your holoform because fun fact in card form your body is an object the actual mob/living is inside a var of the pai obj if i remember right so yes it is the exact same reason as to why you won't hear music inside lockers etc.
