### ISSUE TITLE
Revnants can delam the sm bug (?)

### ISSUE THREAD

**Issue by Arrfur** [BeeStation/BeeStation-Hornet#521]
A player has reported that standing inside the plasma glass that the emitters fire through will cause the emitters to collide with the glass instead of passing through it, being able to break the SM chamber and fuck with the SM

https://gyazo.com/2a2d6ef12f2acd238c2f199c52814cf4

**Comment by Toxici11i** [comment]
i wouldnt say this is a bug and more a feature because of how long the revenant needs to stand there.
also revenant also has an ability that can just fuck glass over anyway soooo

**Comment by yorii** [comment]
Confirmed as not stale, easily reproducible. But as mentioned, revenant can still delam the SM in other ways.

**Comment by Crossedfall** [comment]
Intended
