### ISSUE TITLE
Unable to Produce Polyvitiligo with viro chems

### ISSUE THREAD

**Issue by Rebelord01** [BeeStation/BeeStation-Hornet#5229]
## Reproduction:

1. Attempt to create Polyvitiligo by using Unstable Mutagen or Sucrose Agar
2. notice that the symptom never seems to form itself regardless of how many times you try

I am unsure if this symptom can be found in samples found in maints, given that some symptoms rarely spawn in maints such as itching, and this may be one of the more rare ones

**Comment by KubeRoot** [comment]
From what I can tell in the code, Polyvitiligo is level 0, which requires anomolous virus food [sic], made from virus food and laughter.

The wiki appears to be only partially updated, stating it as level 0 accurately, but listing the wrong required chemical. You can see other level 0 symptoms have anomalous virus food listed.

**Comment by zeskorion** [comment]
Polyvitiligo needs anomalous virus food yes

**Comment by BrumalLake** [comment]
someone update the wiki thanks

**Comment by Ivniinvi** [comment]
Updated, issue resolved.

**Comment by DatBoiTim** [comment]
@francinum Issue was with wiki. Please close this.

**Comment by DatBoiTim** [comment]
@KubeRoot see above comment. This issue was with wiki documentation, since resolved.

**Comment by KubeRoot** [comment]
Confirmed as resolved
