### ISSUE TITLE
Spawned in wrong locations.

### ISSUE THREAD

**Issue by RRAM-1** [BeeStation/BeeStation-Hornet#524]
[Round ID]: # 7792

I am not sure how to reproduce the issue, but I keep getting spawned in locations I am not supposed to be and because it is bee, killed instantly by other people.

In round 7792 I got spawned as a janitor in the captain office, right next to the nuke disk.

account ID is 863188, incase that helps.

**Comment by ghost** [comment]
the only time i remember something like this happeneing was when ee increased the round start role spawns, might be an issue on that but last i heard it was fixed

**Comment by despong** [comment]
ive been spawned in places where im not supposed to be as a janitor. one time i spawned in the CE's office and another is in cargo, i think

**Comment by RRAM-1** [comment]
Yeah , I have tried it some more. It seems to only happen to me when I play janitor.

EDIT: it seems to happen when too many people plays janitor

**Comment by SomeAngryMiner** [comment]
my guess is that this happens with the increased job slots if they are still in, that combined with the lack of start_locations on maps, it ends on crew starting on random places, such as what is seen here, should be pretty easy to fix, if its just spawn locations getting added.

**Comment by Bastian0930** [comment]
As a malf ai, a janitor spawned in my sat... very unfortunate for him

**Comment by yorii** [comment]
Mapping/config issue with amount of spawn locations contra amount of job slots.

**Comment by Crossedfall** [comment]
This specific one should be resolved, but there may be others that happen while maps are changed. I'm going to close this specific issue, but please open a new one if it happens with any other roles.
