### ISSUE TITLE
AI's on multi-Z corg cannot remotely control bots

### ISSUE THREAD

**Issue by kit-katz** [BeeStation/BeeStation-Hornet#5256]
## Testmerges:

corgstation multi-z

## Reproduction:

join corgstation multi-z as an AI 
![image](https://user-images.githubusercontent.com/77494494/131715802-584062bd-d862-4585-994a-a30342dd815c.png)
querry does jack

exist as an AI on the second floor
i presume its because you are thecnically on a diffrent floor/level

**Comment by ZombiesVsPlants** [comment]
also doesn't work with lavaland which is sad

**Comment by williamcll** [comment]
was this ever fixed on NSV?
