### ISSUE TITLE
Mediborg cannot abort surgery

### ISSUE THREAD

**Issue by constatinus** [BeeStation/BeeStation-Hornet#527]
## Reproduction:

Just take surgical drapes and a cautery and use the drapes, the mediborg wont abort the current surgery. You should be able to abort surgeries with drapes in one hand and cautery in the other, and then using the drapes.

**Comment by 123chess456** [comment]
Related issue is that medborgs are literally unable to complete revival surgery past the spark of life step.

**Comment by yorii** [comment]
Confirmed as not stale, easily reproducible, tried fixing it myself but I can't figure it out at all.

The issue is definitely in the code/modules/surgery/helpers.dm file, somewhere around lines 79 or later would be my guess.

**Comment by Chessus** [comment]
Think I found the solution

**Comment by Chessus** [comment]
But only works on harm intent

**Comment by Chessus** [comment]
@Crossedfall @yorii 

Turns out tg moved a lot of the stuff in surgery.helpers to a new file in datums called [surgery_initiator.dm](https://github.com/tgstation/tgstation/pull/52295). There was a number of changes which led to a [bad bug](https://github.com/tgstation/tgstation/issues/54173) and a refactor of [update_mobility()](https://github.com/tgstation/tgstation/pull/54183).

 So I think those steps would be needed to make it work

**Comment by Sarchutar** [comment]
surgery_initiator.dm has nothing to with it. The problem that it only works on harm intent is the `next_step` proc.
 ```
/datum/surgery/proc/next_step(mob/user, intent)
	if(step_in_progress)
		return TRUE

	var/try_to_fail = FALSE
	if(intent == INTENT_DISARM)
		try_to_fail = TRUE

	var/datum/surgery_step/S = get_surgery_step()
	if(S)
		if(S.try_op(user, target, user.zone_selected, user.get_active_held_item(), src, try_to_fail))
			return TRUE
		if(iscyborg(user) && user.a_intent != INTENT_HARM) //to save asimov borgs a LOT of heartache
			return TRUE
	return FALSE
```

`if(iscyborg(user) && user.a_intent != INTENT_HARM)` This part to be precise. TG doesn't have this anymore since they changed this to every surgery tool, not only cyborgs.

**Comment by ivanmixo** [comment]
This does not seem to be an issue anymore. Borgs can cancel surgeries by having drapes and cautery equipped, then clicking the person who is being operated on with harm intent with the drapes.

**Comment by KubeRoot** [comment]
Can confirm this is not an issue, works as ivanmixo reported. Perhaps could have better feedback, but it's working fine.
