### ISSUE TITLE
[Metastation] Wrong access settings on maint airlock next to exploration

### ISSUE THREAD

**Issue by Goshagosha** [BeeStation/BeeStation-Hornet#5287]
## Reproduction:
Problem is at the crossed out airlock.
I am not sure about details (whether it is _require all_ or _require one_ but not _maintenance_), but with maint access it did not let me through, like the bottom maint door did:
  
![Capture](https://user-images.githubusercontent.com/33848913/131937870-505a0934-d00b-468c-be07-693e9d0ded63.PNG)

**Comment by spockye** [comment]
the door is exploration crew only.

**Comment by Goshagosha** [comment]
Isn't the same maint area accessible from the North?
