### ISSUE TITLE
AI cant interact with intercoms properly

### ISSUE THREAD

**Issue by Absolutely-Steph** [BeeStation/BeeStation-Hornet#5310]
## Round ID:
32499

## Testmerges:
emergency hotpatch [DNM] #5252

## Reproduction:
Be ai
clicky on intercom
it shows up as if you are too far away to interact, slightly grayed out and with yellow eye icon.
aghh i cant spy on the meatbags crawling around inside my hulls like ants
I believe #5111 is to blame

**Comment by 1210Avi** [comment]
Borgs can't interact with them either.
