### ISSUE TITLE
Dead humanized monkies continue to move even if dead.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#5327]
https://streamable.com/5rdeo0

Round ID: 32528

Supposedly this is also a bug on /tg/station.

**Comment by AnCopper** [comment]
It later also continued to move after the crew cut of all of its limbs and head.

**Comment by williamcll** [comment]
Confirmed. Will move even after husked.

**Comment by Alpkant** [comment]
This one is really annoying. Every humanized monkey continues to move away from people who killed them.

**Comment by williamcll** [comment]
This is still an issue.
