### ISSUE TITLE
AI's static noise will disappear at random

### ISSUE THREAD

**Issue by TheGreyDiamond** [BeeStation/BeeStation-Hornet#5340]
## Testmerges:
#4984 and #5252 

## Reproduction: Unknown

Under unknown conditions, the AI's static noise disappears briefly. I can try to include everything I know but welp
It was night shift lighting, I had Camera Lights on. I was able to see all maint shafts, but was not able to interact. After (probably) the change to normal daylighting the noise returned.

**Comment by ivanmixo** [comment]
Duplicate of #4839

**Comment by TheGreyDiamond** [comment]
Closed then.
