### ISSUE TITLE
Bluespace anomaly in mining shuttle

### ISSUE THREAD

**Issue by PerishedFraud** [BeeStation/BeeStation-Hornet#5359]
## Reproduction: Try to go to lavaland using the mining shuttle.

 The mining shuttle refuses to land on lavaland, instead being launched at high velocity to another part of the map. This happens several times in a row until it decides to work once. Each time it happens, a kind of bluespace anomaly is reported in the mining shuttle (a unique alert, from what I've seen.) I've consistently encountered this bug, however it MIGHT be tied to map. I don't know.

**Comment by ike709** [comment]
@PowerfulBacon

**Comment by PowerfulBacon** [comment]
> a kind of bluespace anomaly is reported in the mining shuttle (a unique alert, from what I've seen.

This is caused by a shuttle moving out of bounds / travelling too far.

This happens before pressing initiate docking, or after?
This happens with autopilot, no autopilot or both?
Are there any errors that the console says or just the bluespace anomaly?

**Comment by PerishedFraud** [comment]
> > a kind of bluespace anomaly is reported in the mining shuttle (a unique alert, from what I've seen.
> 
> This is caused by a shuttle moving out of bounds / travelling too far.
> 
> This happens before pressing initiate docking, or after?
> This happens with autopilot, no autopilot or both?
> Are there any errors that the console says or just the bluespace anomaly?

The docking can't even occur as it teleports before it is available. In effect it hovers over lavaland and immediately jumps away before docking is up. 

Happened on autopilot from memory, but i rage i tried to pilot it manually at least once and it still happened. Requires more testing.

No errors anywhere. It just gets launched away and the anomaly gets reported.

**Comment by PowerfulBacon** [comment]
Hm I don't suppose you know what directions it happens from? It might only happen in a specific corner due to lavaland being positioned at 0,0.

What I think is happening is lavaland being at 0,0 means that some corners are being out of the collision bounds making it so you don't collide with lavaland. When you are colliding with an object the gravity of that object doesn't affect you, but if the object stops colliding then the immense gravity of lavaland flings you away.

**Comment by PowerfulBacon** [comment]
Assuming that https://github.com/BeeStation/BeeStation-Hornet/pull/5313/files is the culprit

**Comment by PerishedFraud** [comment]
Nice.
