### ISSUE TITLE
Explorers' Recover Dead Crew system is bugged for Borgs

### ISSUE THREAD

**Issue by 1210Avi** [BeeStation/BeeStation-Hornet#5364]
## Reproduction: Die as a borg on an explorer mission, wait for the crew recovery notification, get rescued, and have someone generate a new ruin
As a medical cyborg I got killed on a derelict station during an explorer mission. The crew received a notification that I was missing and I was recovered on another spawned derelict. I was fixed and brought back to life as a cyborg (not MMI) on that derelict. However, for the rest of the shift I kept teleporting over and over again to newly created derelicts, even when I was back on the main station. I believe the system kept considering me dead and respawned me to be found every time someone entered a new explorer ruin.

**Comment by PowerfulBacon** [comment]
Assumed issue:
SSzclear.nullspaced_mobs has null entires as aresult of qdeleted mobs which causes a runtime resulting in nullspaced_mobs not being cleared on completion. This means that any mob added before the deleted mob gets teleported to the location, however the list is not cleared at the end resulting in a loop of teleporting to ruins foerever.

Proper Fix Required:
When a mob is put in the nullspaced_mobs list it needs to register a signal to handle deletion of the mob and remove it from the list. This will also prevent potential hard dels.
