### ISSUE TITLE
Explorers can be headrevs

### ISSUE THREAD

**Issue by dog132-ss13** [BeeStation/BeeStation-Hornet#5368]
Issue reported from Round ID: 32613 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542

Reproduction:

>Be explorer
>Be headrev
>Go to spess
>Almost beat the beestation rev speedrun record

**Comment by williamcll** [comment]
Isn't it the same problem with miners?

**Comment by dog132-ss13** [comment]
That problem was solved a long time ago, but yeah

**Comment by PowerfulBacon** [comment]
The explorers have the same problem as miners in that they the other people on it can send the shuttle but they can't.

**Comment by PowerfulBacon** [comment]
This is more of an overall issue to all off-station jobs, not just exploration teams. Really there should be a time limit at the start of the round where they can leave the station

**Comment by ike709** [comment]
Just blacklist explorer from headrev like we did miner

**Comment by PowerfulBacon** [comment]
> 
> 
> Just blacklist explorer from headrev like we did miner

Miner is blacklisted from headrev?

**Comment by williamcll** [comment]
Maybe instead check if headrev/command is in custody area instead?

**Comment by PowerfulBacon** [comment]
Not a bug
