### ISSUE TITLE
Cannot throw items over tables

### ISSUE THREAD

**Issue by dog132-ss13** [BeeStation/BeeStation-Hornet#5370]
Issue reported from  Round ID: 32613 (BeeStation Sage - Roleplay)

Reporting client version: 513.1542

Testmerges:
5252: 'emergency hotpatch [DNM]' by francinum at commit 2dd36a7b69
https://github.com/beestation/beestation-hornet/pull/5252

(I'm not sure how detailed this issue should be, so I'll give all the info I can)
Recreation:

>Try to throw item over table
>Item lands on/hits the table (hit sound is played)

It only blocks some items from passing over tables, despite having the same throw range.

Same effect with other players throwing items.

Tested items:

Normal behaviour:
* soap
* RD's stamp
* tools

Broken:
* toolbox
* (red) oxygen tank
* fish food
* all clothes
* corpses

**Comment by MrEloda** [comment]
Damn nobody looked into that bug yet ?
It's really annoying and prevent a lot of stuff like throwing a grenade at someone if he is behind a table, throwing your money into kitchen to prevent people from stealing the chef's money.
LOOK INTO IT CODERBROS PLEASE !

**Comment by KubeRoot** [comment]
> LOOK INTO IT CODERBROS PLEASE !

Okay, okay, chill, I looked into it and found the cause, there was some missing code in a refactor for thrownthings, but the missing code uses a feature we don't have yet, so I commented on the PR porting the missing feature. It will probably take a bit of time to get this fixed, but at least we know what needs to be done to fix it.
