### ISSUE TITLE
The power fist just does not work.

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#5375]
Round ID 32630

The power fist is completely broken, not working anymore no matter the setting used - only doing a very light slap when used on someone.

![image](https://user-images.githubusercontent.com/24866230/132948206-90bb791a-5f6f-42ea-aeea-e5dc011cb103.png)

This was the tank installed in it. It started at 2533 kpa of 2.7k o2 and n2o. Note that it *did* consume gas, but it just refused to even do a level 1 setting punch.

Apparently, the fault of slowmos. Yet it works on TG. please fix, powerfist is a really cool weapon and it's annoying to see it fucked over like that

**Comment by evermore9932** [comment]
I might try to fix this
