### ISSUE TITLE
Station names are borked

### ISSUE THREAD

**Issue by Kapu1178** [BeeStation/BeeStation-Hornet#5389]
## Round ID:

32676
## Testmerges:
N/A

## Reproduction:
Station names are kinda fucked. Also happens with the randomly generated Supercruise location names.

I've seen "span>" attached to station names, and straight up "STATION EVENT NOT FOUND" or something, as both station names and location names

**Comment by Ivniinvi** [comment]
It's programmer day, those are event prefixes, this is intentional.

**Comment by ike709** [comment]
Happy programmer day, you didn't get the joke
