### ISSUE TITLE
Blind player's screens stuck with blurry effect after being pied and cleaning it off

### ISSUE THREAD

**Issue by KieraKatsura** [BeeStation/BeeStation-Hornet#5400]
If you play with the blind quirk, and a clown pies you, your screen will stay blurry for the rest of the round even if you wash your face or shower.

I _think_ you run into the same issue if you get too drunk or drink certain drinks ingame as well.

## Reproduction:
 Get pied while using the blind quirk, see blurry screen for the rest of the round

**Comment by PowerfulBacon** [comment]
Bruh code detected
![image](https://user-images.githubusercontent.com/26465327/133335014-6318645a-746b-4581-b911-14f54ef9e181.png)
![image](https://user-images.githubusercontent.com/26465327/133335157-2eb17707-92e1-42c3-812a-f66071d95cf0.png)

**Comment by PowerfulBacon** [comment]
this is a super easy fix, itll take like 2 minutes so ill do it

**Comment by KieraKatsura** [comment]
Speed fix 😳

**Comment by KieraKatsura** [comment]
Thanks again~!
