### ISSUE TITLE
PAI can only hear played music in hologram form

### ISSUE THREAD

**Issue by Nosnek199** [BeeStation/BeeStation-Hornet#5402]
Issue reported from  Round ID: 32704 (BeeStation Sage - Roleplay)

Reporting client version: 514.1554

This may be a client issue, but somebody should test it out incase it isn't just my client.
Reproduction:
1: Become PAI
2: Download loudness booster
3: Play any sort of music.
4: See if you can hear music,
5:
(If unable to hear music, go in hologram form)
(If able to hear music, ignore this issue.)

**Comment by ivanmixo** [comment]
Duplicate of #4968
