### ISSUE TITLE
Abductor mutation toxin made me invisible.

### ISSUE THREAD

**Issue by Poloniolopus194** [BeeStation/BeeStation-Hornet#5405]
## Round ID:
32709

## Testmerges:
#5367 
#5403 

## Reproduction:
I swallowed a maintenance pill full of Abductor mutation toxin. Upon transformation I had taken on all traits of abductors, save for appearance, because my body was entirely invisible. The only way players could see me was because my clothes remained visible.

**Comment by Mick1299** [comment]
Are you sure it was abductor mutation toxin? Also, what race were you before consuming the mutation toxin?

Just tested, and I can't repeat it
