### ISSUE TITLE
The pubbystation shuttle is too long for the game.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#5409]
It always crashes deep into the station if used on Delta Station, and can also result in situations like these:
![image](https://user-images.githubusercontent.com/82319489/133453365-a8d1df2e-c8a3-4631-85fb-ea811cc5d182.png)

**Comment by williamcll** [comment]
Pretty sure this is intended for BBs to shuttle gib people since they can't emag the asteroid engine.

**Comment by AnCopper** [comment]
> Pretty sure this is intended for BBs to shuttle gib people since they can't emag the asteroid engine.

I don't know what the pubby shuttle has to do with blood brothers and the asteroid shuttle but okay.
