### ISSUE TITLE
Biometallic replication breaks revolutionaries icons

### ISSUE THREAD

**Issue by KubeRoot** [BeeStation/BeeStation-Hornet#5412]
## Testmerges:

- #5367 at commit 91fedcc99f
- #5403 at commit ce437d5136

## Reproduction:

Did not attempt isolated reproduction, happened in-round.

There was a virus that turns people into robots - I believe the symptom is called Biometallic replication, it turns your limbs and organs into clockwork parts. At the moment my brain was turned (you can tell because it displays you your notes like you just were revived) I lost the headrev icon - Neither I nor my fellow revs could see that I was a headrev. This is quite problematic as it prevented revolutionaries from recognizing each other and seemingly lead to them attacking me, the headrev.

**Comment by zeskorion** [comment]
This is likely due to the fact that it replaces your brain- rev icons are likely tied to your brain organ, for some reason
