### ISSUE TITLE
Getting traitor without playing

### ISSUE THREAD

**Issue by chizzyyyy** [BeeStation/BeeStation-Hornet#5424]
## Round ID:
32759 

## Testmerges:
#5367 #5417 

## Reproduction:
I clicked "Ready" when there was around 40 sec on timer before the game started, then I clicked "Not ready" because I wanted the round to start first. Without clicking anything else, I got the tot.
[tot moment](https://user-images.githubusercontent.com/90527540/133817434-517fbeb5-053a-4a1d-a604-456cf91cb3b3.png)

<!-- **For Admins:** Oddities induced by var-edits and other admin tools are not necessarily bugs. Verify that your issues occur under regular circumstances before reporting them. --
!>

**Comment by qwertyquerty** [comment]
When did you click not ready, right before it was up?

**Comment by chizzy376** [comment]
> When did you click not ready, right before it was up?

I clicked it around the 10 sec mark.
