### ISSUE TITLE
Chameleon Projector makes you invisible.

### ISSUE THREAD

**Issue by YoussriLMAO** [BeeStation/BeeStation-Hornet#5426]
Issue reported from  Round ID: 32759 (BeeStation Sage - Roleplay)

Reporting client version: 514.1566

The Bug didnt happen on this round, but on a round on the same day.
So it appears if you scan an atmos holofan with the chameleon projector and use it you will become invisible.
thats all i can say to that. I was a miner at this round. 
In-Game Name : Youssri Pitt.
Maybe you can filter it on that name to get the round id or somehow.

**Comment by williamcll** [comment]
Do you appear invisible to others too?

**Comment by YoussriLMAO** [comment]
I think yes. If I remember correctly I asked somebody if they see me, they
said no and people where wondering where I did come from when I used it.
Then it claryfied it for me that I was invisible.

williamcll ***@***.***> schrieb am So., 26. Sept. 2021, 18:27:
