### ISSUE TITLE
Vending Machine Input Lock Glitch

### ISSUE THREAD

**Issue by thatguythere03** [BeeStation/BeeStation-Hornet#5448]
Issue reported from  Round ID: 32922 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

There appears to be some error relating to opening windows by interacting with vending machines. On the latest BYOND build, this seemingly locks up your character and starts flooding your client with garbage inputs. I managed to replicate this twice this round.

**Comment by Guestratem** [comment]
What did you do to recreate it
