### ISSUE TITLE
You can clone Xenomorphs and they'll pop out as humans.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#5460]
![image](https://user-images.githubusercontent.com/82319489/134941047-c6a32c70-0a37-4a69-aa88-b8b7be25c662.png)

They then got out as a human.

**Comment by Kapu1178** [comment]
This is an incredibly funny bug. No further comment.

**Comment by williamcll** [comment]
confirmed to have seen this on Golden. We later inserted all the xeno organs back into the human

**Comment by PerishedFraud** [comment]
Does it work with mob xenos

**Comment by AnCopper** [comment]
> Does it work with mob xenos

Obviously not, they're not carbons.

**Comment by TerryTehCoder** [comment]
I get the feeling if Nanotrasen had the tech to clone xenomorphs easily, they wouldn't be requesting spare organs on Cargo Bounties.
