### ISSUE TITLE
Server wont let me connect

### ISSUE THREAD

**Issue by actiongirth** [BeeStation/BeeStation-Hornet#5465]
I simply try to join from the byond client and it constantly gives me the message "connection died".
I played 2-3 days ago and I didn't receive a ban.
I've done multiple ping tests for packet loss, and its not a problem.
I can join other servers

My current version of byond is Beta 514.1557
I really don't know what to do at this point, could this be a server issue
![2021-09-27 20_24_45-Greenshot](https://user-images.githubusercontent.com/58463237/135183130-8a0b6054-a2da-4ef9-82d6-66444b694de2.png)
?

**Comment by BrumalLake** [comment]
update byond dammit

**Comment by ike709** [comment]
Update BYOND

**Comment by actiongirth** [comment]
thanks
