### ISSUE TITLE
Impossible to Hijack Centcom Raven Cruiser

### ISSUE THREAD

**Issue by Ivniinvi** [BeeStation/BeeStation-Hornet#5468]
## Round ID:
33027

## Testmerges:
#5367: 'Derelict Shuttle Ruins - Custom shuttle persistance' by PowerfulBacon at commit 7db500019b
#5417: 'Remove delay from say verb caused by typing indicators' by KubeRoot at commit 2ac6c749a4

## Reproduction:
Buy CC Raven Cruiser
Observe "shuttle console" and not "emergency shuttle console"
Cannot hijack

**Comment by GregTheEgg42069** [comment]
Bruh

**Comment by PowerfulBacon** [comment]
This has been resolved at some point
