### ISSUE TITLE
The Eminence can't see the blessed tiles.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#5488]
It can be stopped by them, but can't see them.

**Comment by francinum** [comment]
I believe this is true for any mob affected by blessed turfs.
Usability issue, not strictly a bug.

**Comment by r1ks-iwnl** [comment]
> 
> 
> I believe this is true for any mob affected by blessed turfs. Usability issue, not strictly a bug.

Revenant can see blessed tiles.
