### ISSUE TITLE
How do I get your project to stop spamming my email?

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#5490]
For the past several months I've been getting these emails several times a day.
![image](https://user-images.githubusercontent.com/82319489/135726302-70bec648-aa9d-4c3c-a544-fb68751a3923.png)

**Comment by ToasterBan** [comment]
holy fuck I get these too, I think the pr that requires build.bat to compile caused these?

**Comment by KubeRoot** [comment]
Check if you're watching the repo from the main page? 
![image](https://user-images.githubusercontent.com/6917698/135726373-3d075e14-6730-4885-8531-64363f8b17db.png)

**Comment by KubeRoot** [comment]
Wait a second, this is about your fork, isn't it? You've enabled actions on your fork of beestation but haven't filled in the secrets, so the actions are trying to run but failing...

**Comment by AnCopper** [comment]
> Wait a second, this is about your fork, isn't it? You've enabled actions on your fork of beestation but haven't filled in the secrets, so the actions are trying to run but failing...

How do I disable whatever is causing this?

**Comment by KubeRoot** [comment]
You can go to your fork's settings and disable actions completely:
![image](https://user-images.githubusercontent.com/6917698/135726541-1133f106-72ff-49fe-85ba-904a973b0189.png)

This will also prevent any checks from running on your repository, so linters will only run on PRs you open, never directly on your repo's commits. If you care about that, you could also look into disabling individual actions on your fork, but I don't know how that works.

**Comment by AnCopper** [comment]
> You can go to your fork's settings and disable actions completely: ![image](https://user-images.githubusercontent.com/6917698/135726541-1133f106-72ff-49fe-85ba-904a973b0189.png)
> 
> This will also prevent any checks from running on your repository, so linters will only run on PRs you open, never directly on your repo's commits. If you care about that, you could also look into disabling individual actions on your fork, but I don't know how that works.

Okay, thank fuck that's over.
