### ISSUE TITLE
Chemical scans not showing chemicals the subject is overdosing on

### ISSUE THREAD

**Issue by mcmeiler** [BeeStation/BeeStation-Hornet#5499]
## Testmerges:

#5367: 'Derelict Shuttle Ruins - Custom shuttle persistance' by PowerfulBacon at commit 7db500019b
#5363: 'Sprite_Sheets, a new system to allow for better species' by Kapu1178 at commit 7bf1cfca11

## Reproduction: Overdose someone on chemicals, chemically scan them with a medical scanner.

I've seen a person with 60u Tricordrazine in their body, with the chem scan reporting no reagents in the body. The only way to see the "hidden" chems is to put them in a sleeper.
![grafik](https://user-images.githubusercontent.com/83819203/135761547-ad8f45b1-6fe2-4d59-b547-dbe2eb9d2eb0.png)

**Comment by KubeRoot** [comment]
I think this happens if you use a new tab in the chat as opposed to the default one, because the message doesn't register as any other specific kind of message:
![image](https://user-images.githubusercontent.com/6917698/135764376-93b908b5-16b8-41d4-9f2d-d3590e385e43.png)

**Comment by mcmeiler** [comment]
That might be the issue since at some point I believe I accidentally deleted the original Main tab while making some others.
