### ISSUE TITLE
Bugged masks

### ISSUE THREAD

**Issue by Mat05usz** [BeeStation/BeeStation-Hornet#550]
Issue reported from  Round ID: 7971 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 512.1470

I think there is something bugged with masks, you can eat while mask still covers your mouth, there is a message 'you have to remove your mask first' but that's it, still eating food. I'm talking about breath masks, but as far as I recall it works for gas ones too, but not 100% sure about that.

**Comment by Mordecaimusinahama** [comment]
will take a look would be interested to help

**Comment by Mat05usz** [comment]
It's been happening for a few days now, at least for me, if that helps in anything.

**Comment by ike709** [comment]
Was the mask adjusted or not adjusted? (The action button to move the mask out of the way so you can eat).

**Comment by Mat05usz** [comment]
The mask was adjusted, checked it few times. Tried taking it off and on again, different set ups and still I could eat with mask on and that message that I should first take it off.

**Comment by ike709** [comment]
If the mask was adjusted then being able to eat is normal behavior and the message is just erroneously displaying for some reason.

**Comment by Mat05usz** [comment]
so if eating with a mask on is a normal and intented behaviour then the message is a bug, it probably needs fixing to not make anyone confused

**Comment by MarkSuckerberg** [comment]
nah I've seen it and you can eat/drink with masks on in either position, even with internals on. It's a bug

**Comment by Mat05usz** [comment]
Okay, I just wanted to issue this because i found it weird and buggy, if it's not worth repairing that's fine, just wanted to raise this so you know
