### ISSUE TITLE
Nanite Defib is broken

### ISSUE THREAD

**Issue by Rebelord01** [BeeStation/BeeStation-Hornet#5502]
## Reproduction:
1. kill a monkey or player (i tested this on a monkey for this report but previous rounds where players werent revived made me do the test)
2. heal it so it has less then 100 brute and nothing else (suffocation and toxins will disable nanite defib)
3. make a nanite program thats just defib with trigger set to 1
4. take a nanite remote set it to targeted with the signal set to 1
5. use the remote on the monkey
6. notice it wont revive

**Comment by WhereAmO** [comment]
Actually monkies don't have hearts, so they can't be defibbed.

**Comment by Rebelord01** [comment]
nope after the nanite defib failed i took them to med bay and used a regular defib and it worked

**Comment by Rebelord01** [comment]
also in the previous round someone died and i tried to use my nanites to revive em but it also didnt work, they said they where in their body and using my health analyzer i could tell they where in the thresholds

**Comment by Dejaku51** [comment]
checking it now

**Comment by Kapu1178** [comment]
https://user-images.githubusercontent.com/75460809/135911948-f2c2dd47-b408-47a5-9d74-8e4354366f8d.mp4

They're not broken.

**Comment by Dejaku51** [comment]
@Rebelord01 nanites aren't broken, just time in which they can revive is 3 minutes after death
