### ISSUE TITLE
SSOrbits (technically Z-Clear) Bugs out on the creation of a dynamic free level.

### ISSUE THREAD

**Issue by Ivniinvi** [BeeStation/BeeStation-Hornet#5531]
## Round ID:
33182

## Testmerges:
#5367 

## Reproduction:
At some points in the round, this message will be spammed in admin logs:
![image](https://user-images.githubusercontent.com/22421329/136304206-fc5fe910-eafa-4489-8442-26b44d45f8a6.png)
It will always say 0 now created.
If I go into VV and look at free_levels:
![image](https://user-images.githubusercontent.com/22421329/136304242-c8b9bef3-d835-409c-961d-6271937a17aa.png)
There will be a boatload of them, all named Dynamic Free Level 0
The issue is most likely in zclear.dm, in the proc get_free_z_level(), at line 122. This bug is believed to have crashed the server on one or more occasions.

**Comment by MNarath1** [comment]
Just for the record this is probably the same bug that got fixed by https://github.com/BeeStation/BeeStation-Hornet/pull/6303 so this is redundant anyways.
