### ISSUE TITLE
Morphs don't heal on consuming bodies

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#5537]
Issue reported from  Round ID: 33191 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

Just as title says. Morphs are supposed to be healed when they eat bodies, but that doesn't happen.

**Comment by ToasterBan** [comment]
did you digest the bodies or just eat?

**Comment by zeskorion** [comment]
You have to use your morph ability to digest the body

**Comment by JukeJukestar** [comment]
doesnt happen anymore. played multiple rounds and was able to heal from digesting just fine. recommend closing
