### ISSUE TITLE
Shuttle escaping into the void, probably impossible to interdict.

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#5541]
## Reproduction: Take a shuttle (probably with infinite fuel like pirate shuttle). Zoom out massively. like, 50 times. Hit a corner. See a blue line appear showing shuttle is moving at that speed. Keep doing it for a bit till the blue line disappears. Zoom back in. Congrats, you entered null space. (black screen)

Leave the computer, then reopen it to see this

![image](https://user-images.githubusercontent.com/24866230/136479265-d9a757ba-517c-4be8-a9b0-cfe06a1dab90.png)

I sincerely doubt anyone could board our shuttle ever after this bug was produced. Hence the bug report, due to maybe abuse.

**Comment by ike709** [comment]
@PowerfulBacon was this ever solved
