### ISSUE TITLE
Printed toolboxes missing right handed inhand sprites

### ISSUE THREAD

**Issue by mcmeiler** [BeeStation/BeeStation-Hornet#5553]
## Reproduction:
1. Put materials (i.e. copper, glass, iron, etc.) into an autolathe
2. Print a toolbox using a material
3. Equip it in your right hand
4. Observe no sprite as opposed to your left hand

Seriously why am I like the only one who notices this stuff

**Comment by Pirill** [comment]
👀

> Seriously why am I like the only one who notices this stuff

We should make a list of these things somewhere so it's easier to know what's borked at a glance if anyone wants to pick up on it.
