### ISSUE TITLE
My grood foot notes

### ISSUE THREAD

**Issue by ItsTisme** [BeeStation/BeeStation-Hornet#5554]
## My notes

Few notes
1. having gloves, going 4 stance then back to 2 causes the gloves to drop
2. science goggles cant be worn, I imagine for chemists that would be a major issue.
3. lack of suit storage means grod cant carry guns with them as easily, mainly issue for sec(e-guns dont fit in backpacks anymore)

**Comment by BrumalLake** [comment]
2 chem whiz pda chip
3 belt for most

**Comment by Kapu1178** [comment]
1. Bug, need to investigate.
2. Waiting on sprite.
3. This is essentially a balance decision.

**Comment by ItsTisme** [comment]
>2 chem whiz pda chip

I didnt test other goggles but I assume mesons, sec huds or welding goggles also are incompatible

**Comment by Kapu1178** [comment]
> 
> 
> > 2 chem whiz pda chip
> 
> I didnt test other goggles but I assume mesons, sec huds or welding goggles also are incompatible

As of writing Mesons, SecHuds, MedHuds, and Sunglasses are the only completed glasses sprites.
