### ISSUE TITLE
Squids have been removed?

### ISSUE THREAD

**Issue by Denosaurus813** [BeeStation/BeeStation-Hornet#5555]
## Reproduction:

When I went into the character setup tab, I discovered one of my characters I know to be a squidperson was suddenly a human. The squid species also disappeared from the list of options to pick for my character, so I am inclined to believe some accident occurred that made them unselectable. Please allow my character to be whole again.

**Comment by Crossedfall** [comment]
Fixed. Had a typo in the config.
