### ISSUE TITLE
Off-station Exosuit Fabricators are linked with the station ore silo

### ISSUE THREAD

**Issue by mcmeiler** [BeeStation/BeeStation-Hornet#5556]
## Reproduction:
1. Do exploration
2. Find robotics off-station
3. Notice the Exosuit Fabricators are linked to the ore silo

**Comment by Crossedfall** [comment]
I can think of a pretty effective way to solve this problem. 😏

**Comment by mcmeiler** [comment]
Note, this isn't just limited to exploration

Exofabs built by free golems on LL are also linked to the station silo lmao

**Comment by francinum** [comment]
Probably some shitcode in their init. I'll have a look at it.
