### ISSUE TITLE
Sodium Chloride can't be added to the Reaction Chamber's list

### ISSUE THREAD

**Issue by giacomoh** [BeeStation/BeeStation-Hornet#5558]
Issue reported from  Round ID: 33338 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

hello! first time reporting a bug, so i'm not sure if i'm doing this correctly. sorry in advance.

i can't seem to be able to add Sodium Chloride to the reaction chamber. tested it on the beestation Sage server and my own private server running with the latest public beestation code.

maybe some other chemicals can't be added? i'll try to test the other whenever i'll have some spare time

**Comment by BrumalLake** [comment]
i'm pretty sure it's called salt in code

**Comment by KubeRoot** [comment]
I believe the name you need to use is "Table Salt", AFAIK that's the actual reagent name

**Comment by mcmeiler** [comment]
Actual reagent name is "Table Salt", not "Sodium Chloride".

**Comment by giacomoh** [comment]
ah shoot. thanks everyone, i just used the names on the wiki.

**Comment by mcmeiler** [comment]
(Never trust the wiki)
