### ISSUE TITLE
bunch of xenobio bugs

### ISSUE THREAD

**Issue by Sapfearon** [BeeStation/BeeStation-Hornet#5562]
round id 33360 for mindtransfer into headspider.

Alright, first - if you mind transfer into headspider - your soul is bound to spider. And if you plant egg - monke you got will be souless while you gonna be dead. Given how hard is it to actually get xenoling(rainbow, lazarus,dead headspider, permissions from heads) it is a very unfunny bug. I swear i remember actual xenolings from gold cores, and they worked with mind transfer. Not sure what's broken now.

Xenobio bags - still broken, still can't use bag to mass feed cubes to extracts.

another mind transfer bug - if you mind transfer into monster and someone uses intelligence potion on same monster...oh boy, you clien will crash completly, you will be in main menu with option to join(!!!) round. pretty interesting bug. Should be easy to replicate - but int potion probably needs ghost, not sure if bug works without willing ghost.

**Comment by zeskorion** [comment]
Xenolings were intentionally made to be impossible iirc

**Comment by KubeRoot** [comment]
> Xenobio bags - still broken, still can't use bag to mass feed cubes to extracts.

Known issue, see https://github.com/BeeStation/BeeStation-Hornet/pull/5090
This is the fourth issue talking about this. In fact, *you even commented on an earlier issue about this.*
