### ISSUE TITLE
Missing Crate items and stamina damage that doesn't go away

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#5569]
## Reproduction:
![image](https://user-images.githubusercontent.com/43061493/137511988-b1e17364-7a97-4176-bffd-01de0af0822d.png)
So I ordered one crate of plastic sheets from cargo, but upon arrival the crate had nothing but the manifest.

Additionally, I had 0.6 stamina damage on me that doesn't go away for some reason, I had punch myself for it to go away.

**Comment by St0rmC4st3r** [comment]
>So I ordered one crate of plastic sheets from cargo, but upon arrival the crate had nothing but the manifest.

Iirc, it's intended. Spamp the manifest with the denied stamp and ship it back.

**Comment by BrumalLake** [comment]
stop putting two unrelated issues in one report

**Comment by zeskorion** [comment]
I think stamina regen code doesnt check for fractions

**Comment by williamcll** [comment]
> > So I ordered one crate of plastic sheets from cargo, but upon arrival the crate had nothing but the manifest.
> 
> Iirc, it's intended. Spamp the manifest with the denied stamp and ship it back.

Do I get a full refund?

**Comment by Sarchutar** [comment]
> Do I get a full refund?

If it was an actual error, there are three types of possible errors, and you stamp the manifest with the DENIED thing then you should get a refund for how much the order cost, yes.
