### ISSUE TITLE
Slime healing pylon damages oozelings

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#5571]
Issue reported from  Round ID: 33384 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

No clue why this happens, but the healing effect from purple slimic pylons slowly damages oozelings and all jellypeople as well, instead of healing them. This probably shouldn't be the case, as it's slime healing magic and it shouldn't damage slimepeople.

**Comment by zeskorion** [comment]
this can easily be fixed by setting its toxheal to forced=true

**Comment by mcmeiler** [comment]
*and this is why i don't let xenobiologists set one up in medbay, ever.*
