### ISSUE TITLE
Using Bamboo Cuttings makes Wall Griders dissapear

### ISSUE THREAD

**Issue by MarMauZag** [BeeStation/BeeStation-Hornet#5577]
## Reproduction:
1. Get some bamboo cuttings (At least two sheets)
2. Make a wall grider.
3. Click on the wall grider with bamboo cuttings.

## Results:
The wall grider dissapears and now you wasted two iron.

**Comment by Archanial** [comment]
This is because of how code works.
It dynamically creates wall type of used material's name and bamboo wall doesn't exist

**Comment by rkvothe14** [comment]
> This is because of how code works. It dynamically creates wall type of used material's name and bamboo wall doesn't exist

@Archanial  Fixing this issue would be adding bamboo walls + sprite, or preventing wall girders/walls made of bamboo?
