### ISSUE TITLE
Chameleon Gas Mask does not prevent from being facehugged.

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#5582]
All in the title. Wear a firefighter helmet & gas mask => facehugger immune. Wear a firefighter helmet & chamo gas mask =>you get facehugged.

**Comment by Kapu1178** [comment]
im pretty sure this is intentional. Chameleon gas masks arent actual gas masks.

**Comment by Howluinb** [comment]
But it makes no sense ? It literally changes your voice, and allows to breathe oxygen, why the hell can it not have the functionality of being an actual gas mask? This'd be like the chameleon PDA being non functional because "it's a chamo pda" ... except it works. It's only shit like insuls/flashbang proof/glasses that don't work for obvious reasons

**Comment by Kapu1178** [comment]
the chameleon pda is an actual pda. the chameleon gasmask is only the **mask** typepath.

**Comment by BrumalLake** [comment]
pretty sure this gas mask not being torn off thing isn't true cause swat masks security masks etc subtypes get torn off
