### ISSUE TITLE
Objectives in notes or in round report do not show up if you get obsessed 

### ISSUE THREAD

**Issue by Alpkant** [BeeStation/BeeStation-Hornet#5587]
I couldn't find my round id so I can't give the id but reproduction is simple.

## Reproduction:
- Start to round as a crewmember (medical doctor in my case).
- Be obsessed during the round (I became obsessed with another doctor) and get your objectives from the chat
- Objectives don't appear in the notes section but can be seen in the chat
- Complete your objectives
- At the end of the round you don't show up as antag even though you had to murder a crew for objective
- Victim yells at you for murderboning

**Comment by Archanial** [comment]
Obsessed is broken entirely
