### ISSUE TITLE
MODULE FREEZE: CARBONS

### ISSUE THREAD

**Issue by francinum** [BeeStation/BeeStation-Hornet#5605]
Carbon Bodyparts and Organs will be going under a significant refactor (KapuCarbons) soon, as such, all changes that involve bodyparts or organs in a significant way are frozen. In addition, you should not be changing the way carbon/human icons are constructed for the time being (not like anyone is that insane). If you are unsure what qualifies as "a significant way", ping or DM `@Kapu#1178`

**Comment by Kapu1178** [comment]
Sink in the code or code in the sink.

**Comment by utilbird** [comment]
Why not announce the refactor details now instead of holding it up in the air 4no rasen. Something something codebase direction gets brought up a lot.

**Comment by Kapu1178** [comment]
#5611 Phase 1.

**Comment by Kapu1178** [comment]
> 
> 
> Why not announce the refactor details now instead of holding it up in the air 4no rasen. Something something codebase direction gets brought up a lot.

I am a very, very chaotic coder. In general
Limbs: Move most species data into limb subtypes, and make limbs retain information across owners, clean up digitigrade code
Organs: Kill mutant_bodyparts, making fucking everything an organ.
