### ISSUE TITLE
Light Eater doesnt disable borg lamps

### ISSUE THREAD

**Issue by Boxlta** [BeeStation/BeeStation-Hornet#5609]
Issue reported from  Round ID: 33549 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568
smackin a borg with a light eater doesnt disable their lights, as it previously did. Now borgs are a hard counter because they have a like 10 tile wide light

**Comment by rkvothe14** [comment]
I'll give this a look later today, as I was the one that probably did this.

**Comment by rkvothe14** [comment]
https://user-images.githubusercontent.com/90270186/138704466-993b41b8-5a52-4c46-b81f-4a50f46fbbf9.mp4

@Boxlta this looks like it's working on master. Do you have any more details about your issue? Which type of borg was it?

**Comment by Boxlta** [comment]
It was a mediborg. you should also do it in a darker area so its easier to see

**Comment by rkvothe14** [comment]
https://user-images.githubusercontent.com/90270186/138869589-96a3b98f-2990-4914-a595-8d9fc849d32d.mp4

Excuse the watermark, I had to compress the video, hah.

As seen above, I see no issue with the borgs headlamps 🤔

**Comment by Boxlta** [comment]
Hmm. Mighta been a one off thing. Suppose ill close this and make a new issue if i see it again
