### ISSUE TITLE
Research unable to be unlocked even with prerequisites unlocked.

### ISSUE THREAD

**Issue by ThatFiveGuys** [BeeStation/BeeStation-Hornet#5613]
## Reproduction:

1. Research all of the technology already in R and D (Im including this as I suspect this may be the start of the bug).
2. Go on an exploration and receive PHAZON tech disk.
3. Upload tech disk to research computer.
4. Attempt to research PHAZON
5.  
![image](https://user-images.githubusercontent.com/73148980/138618020-ab98dd3c-95a2-4633-9a7b-12116b01fbbf.png)
![image](https://user-images.githubusercontent.com/73148980/138618023-deb671d8-1985-4415-853c-ab5fe3f1e7f7.png)

This isnt just for PHAZON either, got a bunch of other tech and unable to research, Ive experienced this bug across multiple rounds.
![image](https://user-images.githubusercontent.com/73148980/138618064-2aa68c61-9a11-475a-a268-dad1e4ef0431.png)

**Comment by BrumalLake** [comment]
pretty sure you can only find them on ruins

**Comment by KubeRoot** [comment]
Somebody told me in-game how to work around this: You have to load technology from disk, then load it onto the disk and back from the disk again.

I'm not entirely sure this is a bug, but the current behavior is certainly annoying and unnecessary.

**Comment by MNarath1** [comment]
> 
> 
> pretty sure you can only find them on ruins

this seems to also happen if you have found the disk or more like without the disk uploading the reseach the tech node is not even visible its a bug that sometimes doesn't unlock the node after the satisfaction of the prerequisits.

**Comment by MNarath1** [comment]
Seems to mainly happen to tech disk reseach trough that got introduced with ruins. Had that problem yesterday with boh had the disk properly uploaded it with the methode described by kuberoot and it still did not unlock the tech node trough it became visible despite all prereqisits beeing satisfied and enough reseach point beeing aviable

**Comment by MNarath1** [comment]
You can even see above that the phanzo is hidden on default so without uploading the disk the tech node isn't visible so it got uploaded but didn't unlock afterwards.

**Comment by KubeRoot** [comment]
> Seems to mainly happen to tech disk reseach trough that got introduced with ruins. Had that problem yesterday with boh had the disk properly uploaded it with the methode described by kuberoot and it still did not unlock the tech node trough it became visible despite all prereqisits beeing satisfied and enough reseach point beeing aviable

I can tell you that I had the same problem being described here, and I've been using the steps I described since with consistent success.
To be sure: you need to be doing 3 operations - upload, download, upload.
The first operation reveals the technology in the console, the second puts all research technologies on the disk, the third properly uploads the technology making it available to be researched.
