### ISSUE TITLE
Blood Brothers Implant showing up in Mind reading

### ISSUE THREAD

**Issue by Yatosamasensei1** [BeeStation/BeeStation-Hornet#5619]
## Round ID: 253921

![Mindread bug](https://user-images.githubusercontent.com/93158899/138760641-3b5b8142-36c5-4135-92f5-0efee774321a.PNG)
## Reproduction:

Was mind reading and it showed  (Blood brother implant) before one of the messages

**Comment by TeomanTheGreat** [comment]
I think this is intentional. You are reading their mind after all.

**Comment by ivanmixo** [comment]
This also works for ling hivemind, blood and clock cult comms, telepathy, and anything else you can think of that uses the say box to communicate.

**Comment by Yatosamasensei1** [comment]
I was told by admin it was 100% not intended and to make a bug report

**Comment by Archanial** [comment]
It's not intentional

**Comment by kit-katz** [comment]
i feel violated
