### ISSUE TITLE
Changeling Headspider in crematorium bug

### ISSUE THREAD

**Issue by Slauenza12** [BeeStation/BeeStation-Hornet#5625]
## Reproduction:

As a changeling in the crematorium use the headspider ability and the head spider will spawn on top of the crematorium not inside.

**Comment by Boxlta** [comment]
Fairly certain this is intended behavior

**Comment by Slauenza12** [comment]
Ah the admin who asked me to help test it said it was not. I think. i could very easily be wrong.
