### ISSUE TITLE
SM engine

### ISSUE THREAD

**Issue by Mat05usz** [BeeStation/BeeStation-Hornet#565]
Issue reported from  Round ID: 8017 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 512.1470

Godmins weren't able to answer that but, is it possible to fix that bug that you can have like 20 MW of power just by throwing shit into SM chamber and having rad increased to magical levels?

**Comment by Mat05usz** [comment]
I don't know, like having a cap for items so it's not possible for them to have 'infinite' rads stored.

**Comment by Mat05usz** [comment]
It's often abused to irradiate matter bins to silently give tons of rads to crew that doesn't know what's going on or to boost SM engine to levels that are way to good for basic set up.

**Comment by ike709** [comment]
Radiation is horrifically broken and unbalanced because it breaks the laws of thermodynamics. This is a very large issue to deal with.

**Comment by yorii** [comment]
Intended feature 😄

**Comment by park66665** [comment]
tgstation/tgstation#42572
