### ISSUE TITLE
wielding potted plants stop rendering the plant sprite after a while

### ISSUE THREAD

**Issue by kit-katz** [BeeStation/BeeStation-Hornet#5658]
## Round ID:
N/A (consistent)

## Testmerges:
N/A

## Reproduction:
pick up potted plant
 wait 0-5 minutes (it can happen almost instalty it can take minutes)
become exposed once more even tho you are still wielding it

**Comment by Coding-Grape** [comment]
Ah yes, stale, because nobody would fix it
