### ISSUE TITLE
Pubbystation SM cannot be set without atmos access

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#5659]
This has been an long-standing issue but seeing as it hasn't been fixed yet I might as well make a report and see if it goes anywhere:
![image](https://user-images.githubusercontent.com/29107291/139558457-c9e77369-3b5b-4be6-867d-e3a04f046733.png)

Notably, while the burn chamber scrubber is on the SM air alarm which Engineers can access, the burn chamber vent (7) is on the room's air alarm which requires Atmospherics access to configure.
## Reproduction:
Try to set up the Pubby SM as an Engineer without extended access. Cry.

**Comment by Crossedfall** [comment]
Thaaaat was the thing I forgot to fix in my last minor map fixes PR. I knew it was something in that area. This is a super simple fix.

**Comment by Pirill** [comment]
Amazing! Thanks!
