### ISSUE TITLE
Piercing syringes do not petetrate armour

### ISSUE THREAD

**Issue by mcmeiler** [BeeStation/BeeStation-Hornet#5665]
## Reproduction:
1. Load a piercing syringe into a syringe gun
2. Shoot at an armoured target, like a person in a hardsuit
3. Notice the syringe gets "deflected"

From what I can tell this is *directly* caused by Bacon's embedding rework. This seems unintended in my opinion.

**Comment by zeskorion** [comment]
Were they a skeleton? Piercing syringes pierce thick clothing, but they cant inject species that have inherent piercing immunity.

**Comment by mcmeiler** [comment]
Not like I can tell if they're in a hardsuit, is it?

**Comment by ivanmixo** [comment]
The limp and lifeless still appears no matter what they have on.

**Comment by BrumalLake** [comment]
so it's not reproducible and the target was likely an immune species?

**Comment by PowerfulBacon** [comment]
![image](https://user-images.githubusercontent.com/26465327/172253026-88f841f7-5976-4dd6-8502-c9fd878226f4.png)
