### ISSUE TITLE
Xeno Eggs not hatching properly

### ISSUE THREAD

**Issue by Penwin0** [BeeStation/BeeStation-Hornet#5666]
# Round ID:33724

# Testmerges: #5442

# Reproduction:
Laid some eggs as Queen in virology, openned them manually and nothing came out, I cannot think of anything that could have caused it

**Comment by Howluinb** [comment]
Ah, right, i think I know the problem -

if you happen an egg and start spam clicking *before* the facehugger is above the hatched egg sprite, you will delete the egg before the hugger physically spawned
