### ISSUE TITLE
Bacon's gun changes broke the robust dress shop a bit

### ISSUE THREAD

**Issue by Kapu1178** [BeeStation/BeeStation-Hornet#5689]
## Reproduction:
Because of guns now containing an "offhand" item that doesnt even need to exist, it will delete/prevent creation of the other hand's item if an outfit datum has a gun in one hand and anything else in the other.

**Comment by PowerfulBacon** [comment]
This will break for all two-handed force-wielded items and needs a general solution that isn't specific to guns. While outfits shouldn't be giving 2 different items into the hands of mobs and should instead prefer to put things in pockets or backpacks, it should still work.
Getting around this sounds kind of annoying to be honest and all the solutions I can really think of sound a bit bodge. Maybe if an item is initialized inside a player having it not auto-wield would be the best thing? I feel like changes to the two-handed component are a lot less shitcode than making the outfit system changed to check everything for a case that shouldn't really happen

**Comment by BrumalLake** [comment]
rip plasmamen
the equip_outfit proc outfits use makes sure that the slot they're on is not being overridden so it should be a pre init issue
one cheap solution would be to just swap the hands of outfits and that would take a bit of tinkering with plasma belt tanks well that's assuming they're always using their left hand, use some code to put the gun in inactive hands always instead, or you could simply put them in belts suit storages or bags
