### ISSUE TITLE
RnD console freezes when uploading tech disk.

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#5698]
## Reproduction:

With the new RnD console UI, if I were to upload a disk to the techweb, download all the nodes back to disk, then upload it to techweb again to make it researchable, it makes the byond client freezes for up to 10 seconds for every disk I do this on.

**Comment by KubeRoot** [comment]
This should be fixed with https://github.com/BeeStation/BeeStation-Hornet/pull/5735
