### ISSUE TITLE
Adding bamboo shavings to a wall girder deletes the wall

### ISSUE THREAD

**Issue by PerishedFraud** [BeeStation/BeeStation-Hornet#5710]
Tested on round 33848.

Cause unknown. See title, no further description needed. Deletes walls like it's nothing.

**Comment by KubeRoot** [comment]
Duplicate of https://github.com/BeeStation/BeeStation-Hornet/issues/5577
Resolved by https://github.com/BeeStation/BeeStation-Hornet/pull/5703

**Comment by DatBoiTim** [comment]
@KubeRoot Noted as resolved in comments
