### ISSUE TITLE
Orbiting someone in a transit tube de-orbits you.

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#5729]
Round ID : 33886

## Reproduction:

No idea if it's all transit tubes, or only the pubby tube from chapel to station - if you orbit someone who takes the transit tube, you'll suddenly stop orbiting them in the middle of it and you have to manually orbit them again.

**Comment by francinum** [comment]
Transit tube code is ancient and terrible, but I'm not entirely sure why it would dereference mobs, considering it works with lockers. I'll try to look into this later.

**Comment by PowerfulBacon** [comment]
Doesn't seem to happen anymore
