### ISSUE TITLE
Mulligan Toxin can't be crafted.

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#5731]
## Reproduction:
1 part Stable Mutation Toxin
1 part Unstable Mutagen
Put it in a beaker.
Doesn't create mulligan tox. Kinda bad since cargo bounty requires it sometimes.

**Comment by BrumalLake** [comment]
wiki is too hard to edit only source editing button works

**Comment by QueenReduviidae** [comment]
Mulligan Toxin CAN be crafted it's just the wiki has the wrong recipe.
The recipe for mulligan toxin is:
1 part Mutation Toxin (The one that turns you into a slime person)
1 part Unstable Mutagen
(This is what the code says at least.)

**Comment by PowerfulBacon** [comment]
I've updated the wiki
