### ISSUE TITLE
Centcom ferry mapping error.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#5749]
![image](https://user-images.githubusercontent.com/82319489/140825924-4ba153c6-961d-408d-af6c-1ecf0dee2acd.png)

May have something to do with the Flandstation TM.

**Comment by AnCopper** [comment]
Nevermind, just realized that this isn't an escape pod inside the ferry.

**Comment by PestoVerde322** [comment]
> 
> 
> Nevermind, just realized that this isn't an escape pod inside the ferry.

yep, it's intentional, however the front of the shuttle being a brick not.
