### ISSUE TITLE
Hangover spawners do not automatically clean themeslves up

### ISSUE THREAD

**Issue by francinum** [BeeStation/BeeStation-Hornet#5750]
## Testmerges:
#5442 at 17693f6c5c
#5617 at 8862e1c9d6
## Reproduction:
Have the Hangover station trait trigger, right click any tile that has a hangover spawner.
See the entry in the right click menu.

**Comment by KubeRoot** [comment]
Weren't hangover landmarks removed in favor of fixing finding a random safe station turf?

**Comment by francinum** [comment]
> 
> 
> Weren't hangover landmarks removed in favor of fixing finding a random safe station turf?

They're still used internally as the targets, and need to be cleaned up after use.
