### ISSUE TITLE
Hand tele portals now acting extremely weirdly.

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#5763]
## Testmerges: 
#5442 [DNM][NEW SPECIES] Grod. Also, a ton of species improvements.
Commit: 8691e98
#5725 Ports removal of crossed() and uncrossed(), also checkexit()
Commit: 3b4c8fc

## Reproduction:

Use hand tele. Create a portal. Try to enter - It now says locked in. You now have to manually click the portal to enter its tile, then click the portal again to pass through. 
Portals also block all projectiles, too, along with movement - you can't pass through a portal whatsoever now.

**Comment by Archanial** [comment]
thank you for the issue
