### ISSUE TITLE
Dissection surgery

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#5776]
The dissection surgery only gives research points, but now they are pretty worthless. Pleases make it so it gives discovery points.

**Comment by Alpkant** [comment]
We really need more ways to get discovery points, especially with the new calculation method. Lack of discovery points becomes a much bigger issue in the low-pop games.

**Comment by Mails-z** [comment]
YAY, THIS WAS IMPLEMENTED
