### ISSUE TITLE
IPCs broke badly.

### ISSUE THREAD

**Issue by St0rmC4st3r** [BeeStation/BeeStation-Hornet#5781]
Issue reported from  Round ID: 34022 (BeeStation Sage - Roleplay)
Testmerges: #5611: '[DNM] BetterLimbs' by Kapu1178 at commit cb08e02b9d
Reporting client version: 514.1568

Got killed, beheaded, and dragged as IPC. Lost some blood (oil). Eventually got revived. For some reason kept getting damaged with brute. Suspected that it is because of bloodless. So because of bloodloss I got brute damage and I kept bleeding because of brute damage. At least I think so. 
IVs do not replace oil blood.
When tried to deal with the constant limb damage, got libs replaced by borg limbs. I was dying much quicker for whatever reason, like at 80hp or so, but later this problem disappeared for the little time the round had.

**Comment by Kapu1178** [comment]
I caused this but not with the limb refactor. Probably.

**Comment by Kapu1178** [comment]
If this bug happens again, do not hesitate to ping me on discord.
