### ISSUE TITLE
Syndicate Elite Hardsuit on Non EVA mode do not protect against Facehugging

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#5783]
## Reproduction:

get syndicate elite hardsuit and syndicate mask
get facehugged
cry because it makes no sense that they're able to facehug you through ultra high tech syndie gear and you're now dead

**Comment by Howluinb** [comment]
https://github.com/BeeStation/BeeStation-Hornet/issues/5582

twice that syndicate gear does not prevent facehugging, this makes no sense - I understand the purpose is to prevent crew from just grabbing gas mask & killing benos, but syndicate should actually have facehug proof gear ?

**Comment by BrumalLake** [comment]
maybe it's cause the hardsuit only covers your face in eva mode
so many troll prs about how face gear should protect facehugging

**Comment by BrumalLake** [comment]
please no "doesn't make sense" argument btw thanks
nevermind you already did it ☠
TWICE even

**Comment by Howluinb** [comment]
The only difference between EVA and non EVA is a tiny light and a visor closed. Are you telling me a facehugger can crawl through a minuscule visor and replace a syndicate mask through there?

Also, if you don't want "doesnt make sense" arguments, the CMO hardsuit has less body protection and cover than an actual nukie hardsuit and yet still is enough not to be hugged. a bomb suit which literally, has a visor will still protect you from being hugged. 

balance wise is fucked too, considering how op xenos already are  - if even nukies can't face them (because they wont win on walk speed ie eva mode), then it's super bullshit.

**Comment by Howluinb** [comment]
Ifuckindedplzfixxx

**Comment by Ivniinvi** [comment]
died to mechanic

neuron activation

> CMO hardsuit has less body protection and cover

it has a full helmet what

**Comment by BrumalLake** [comment]
look there's two types of helmets in this world helmets that have their face completely covered and helmets that don't and the medical hardsuit is the former
there is no such thing as a helmet that "doesn't have enough body protection armor weak material bull"
swat helmets which are space proof are prey to face huggers

**Comment by Howluinb** [comment]
i am coping and malding so fucking hard at this because of the lack of indication of this shit

if you wanna make it so non eva mode doesnt protect against facehug; fine, same for firefighter helmet or whatever, but give an indication on shift click or anything whatsoever so you dont just get fucked over for a reason you had no way of knowing/fighting against

this applies for the chamo gas mask, too, how are you supposed to know it's not an actual gas mask and thus wont do like, actual gas mask work?

**Comment by BrumalLake** [comment]
face huggers tear off all uncovered masks there is no reason why gas masks and chameleons should be an exception

**Comment by Kapu1178** [comment]
> 
> 
> i am coping and malding so fucking hard at this because of the lack of indication of this shit
> 
> if you wanna make it so non eva mode doesnt protect against facehug; fine, same for firefighter helmet or whatever, but give an indication on shift click or anything whatsoever so you dont just get fucked over for a reason you had no way of knowing/fighting against
> 
> this applies for the chamo gas mask, too, how are you supposed to know it's not an actual gas mask and thus wont do like, actual gas mask work?

this game has hundreds of clothing items, datums, and game mechanics.

There is literally no way to reasonably assume we could even be aware of such a thing being a problem. Stop acting like SS13 is created by professionals who understand the entirety of their own game, please. Its honestly getting incredibly annoying. If you think its a bug, simply report it as a bug. We do not need a 2 paragraph tirade about how "fucking stupid it is" or "lack of indication".

**Comment by Howluinb** [comment]
> 
> 
> > i am coping and malding so fucking hard at this because of the lack of indication of this shit
> > if you wanna make it so non eva mode doesnt protect against facehug; fine, same for firefighter helmet or whatever, but give an indication on shift click or anything whatsoever so you dont just get fucked over for a reason you had no way of knowing/fighting against
> > this applies for the chamo gas mask, too, how are you supposed to know it's not an actual gas mask and thus wont do like, actual gas mask work?
> 
> this game has hundreds of clothing items, datums, and game mechanics.
> 
> There is literally no way to reasonably assume we could even be aware of such a thing being a problem. Stop acting like SS13 is created by professionals who understand the entirety of their own game, please. Its honestly getting incredibly annoying. If you think its a bug, simply report it as a bug. We do not need a 2 paragraph tirade about how "fucking stupid it is" or "lack of indication".

the only reason i went into paragraphs is because I got called out after making a concise post in the beginning, lmao
we didn't need the paragraph, but i'm not going to get shat on and not reply
