### ISSUE TITLE
Body husked while wearing full atmossuit.

### ISSUE THREAD

**Issue by DemonOfHatred** [BeeStation/BeeStation-Hornet#5785]
Issue reported from  Round ID: 34038 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

The area my body was in was being depressurized via a breached wall into space, there was enough plasma to start a fire, i died from oxygen loss but the body when it was recovered by a doctor was husked. the only thing that I can think of is that the lack of internals caused fire damage but that shouldn't be the case right?

Name:  Spills the blood
Death: Oxygen loss
Problem: husked body
Apparal at TOD: chaplains starting gear, full atmospheric technician gear including helmet.

**Comment by BrumalLake** [comment]
~lots of missing details, did a fire actually start
haven't played anything but plasmaman for a long time so i don't remember if not having internals in space is cold or not~
it's a firesuit not a hardsuit issue closed
or if you weren't on a space tile you probably just burned did you check the temperature

**Comment by DemonOfHatred** [comment]
ah so the lack of atmosphere spaced me instead of the fire
