### ISSUE TITLE
Mobs keep honking post-mortem due to clown virus

### ISSUE THREAD

**Issue by Penwin0** [BeeStation/BeeStation-Hornet#5789]
## Testmerges: 
#5611: '[DNM] BetterLimbs' by Kapu1178 at commit f0f14cc852

## Reproduction:
Have Honk virus and die, keep honking in the afterlife

**Comment by zeskorion** [comment]
This is likely due to the virus having necrotic metabolism, which causes it to function on corpses. Not a bug.

**Comment by St0rmC4st3r** [comment]
iirc it caused ghosts to honk

**Comment by spockye** [comment]
> This is likely due to the virus having necrotic metabolism, which causes it to function on corpses. Not a bug.

every time something gets infected and dies, a new ghost appears and starts honking in D-chat, filling it up with spam

**Comment by zeskorion** [comment]
> > This is likely due to the virus having necrotic metabolism, which causes it to function on corpses. Not a bug.
> 
> every time something gets infected and dies, a new ghost appears and starts honking in D-chat, filling it up with spam

How the fuck
