### ISSUE TITLE
Lizard clown defaults back to default size even with genetic mutation or admin size select.

### ISSUE THREAD

**Issue by DemonOfHatred** [BeeStation/BeeStation-Hornet#5794]
Issue reported from  Round ID: 34046 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

Clown, lizard, dwarfism, or gigantism it doesn't matter which as soon as i move it resets my character model back to default.

**Comment by zeskorion** [comment]
Waddling with clown shoes resets size mods

**Comment by BrumalLake** [comment]
the clown shoes thing was hacky
