### ISSUE TITLE
felinids no longer keep wagging their tail after being tabled

### ISSUE THREAD

**Issue by Wilchenx** [BeeStation/BeeStation-Hornet#5797]
## Reproduction:

get tabled
start wagging your tail because memecode
start getting up
stop wagging your tail

its 100% not related to betterlimbs as this was a issue before that

**Comment by Hardly3D** [comment]
https://github.com/BeeStation/BeeStation-Hornet/blob/48ece11504ae30f366c85d39bf7e37ba19643db8/code/datums/mood_events/generic_negative_events.dm#L88
Pretty sure that's intended
