### ISSUE TITLE
Medbots stop working when patients move

### ISSUE THREAD

**Issue by Wilchenx** [BeeStation/BeeStation-Hornet#5806]
## Reproduction:

1. medbot heals you
2. you move or get moved away
3. it gets stuck and no longer tries to heal you

turning it off and on fixes it but its annoying

**Comment by Zaess** [comment]
Yeah I experienced it too. It's much more dangerous then just "turn it off and on again" if your ID card doesn't have the rights to do it and you are almost in crit well bad for you I guess
