### ISSUE TITLE
Ducatopod Issue

### ISSUE THREAD

**Issue by nednaZ** [BeeStation/BeeStation-Hornet#5807]
## Reproduction:
Inside lubefeet.dm, "var/clownshoes" starts as TRUE which causes clown shoes at all times. 
This makes the threshold entirely pointless.

I've already fixed this for a downstream server, but my fork is too far off from Bee mainline to actually PR this bugfix for you.

**Comment by KubeRoot** [comment]
Addressed by https://github.com/BeeStation/BeeStation-Hornet/pull/5574

**Comment by zeskorion** [comment]
this issue is fixed in #5574

**Comment by DatBoiTim** [comment]
@KubeRoot Close plz.

**Comment by KubeRoot** [comment]
True, I can close this now!

Issue has been resolved by https://github.com/BeeStation/BeeStation-Hornet/pull/5574
