### ISSUE TITLE
Half of the emergency shuttle leaves the other half behind when departing/landing

### ISSUE THREAD

**Issue by 1210Avi** [BeeStation/BeeStation-Hornet#5809]
## Round ID:

34102

## Reproduction:

Seemingly at random, when it is time for the shuttle to either leave the station, or land at centcom, the emergency shuttle will only take half shuttle into account (as far as I've seen it will always be the eastern or northern side), thus either leaving the other half stranded on the station when it departs, or in deep space when it lands at centcom. I've seen this happen on multiple occasions, roughly once every 10-15 shifts.  I do not know how to reproduce this bug. 

![111](https://user-images.githubusercontent.com/22588168/142202097-9b21f91f-0bb4-447d-be27-6d3201a69495.jpeg)
![222](https://user-images.githubusercontent.com/22588168/142202119-c00207b4-02b3-4969-8327-01027ad9975a.jpeg)

**Comment by PowerfulBacon** [comment]
Needs more information in order to fix this. Haven't seen this happen in months now, so closing this on the basis that we cannot confirm this to be true or false without more rigorous testing details.
