### ISSUE TITLE
TGUI error when opening ghost orbit menu

### ISSUE THREAD

**Issue by benbot16** [BeeStation/BeeStation-Hornet#5817]
## Round ID:
34116

## Testmerges:
#5726 

## Reproduction:
When I attempted to open the orbit menu as a ghost, I was given a TGUI error. It resolved itself after a while, though I'm not sure why.

Said error:

![image](https://user-images.githubusercontent.com/9423435/142344072-8aabdf18-e282-446e-ad8f-ce8c7cd6e72b.png)

**Comment by KubeRoot** [comment]
Managed to figure out where the stacktrace points to:

```js
for (const antagonist of antagonists) {
```

in `Orbit.js:93`.

I can't see a way for this to be null unless the UI simply failed to receive data, or the code somehow runtimed on the DM side.
