### ISSUE TITLE
False Insufficient Materials on lathe

### ISSUE THREAD

**Issue by UltraNumeron** [BeeStation/BeeStation-Hornet#5824]

**Comment by KubeRoot** [comment]
From a quick code check, I believe the .45 ammo box requires 15 sheets of iron. Are you sure there was enough iron? I'm asking because that's a rather large amount of iron, especially compared to most items.

**Comment by UltraNumeron** [comment]
It was though  i believe i didnt have enough att he first time of making it, however when i did add enough mats it did the described bug have been having the same bug with other items too, after not having enough mats then adding them it wont let me print the item no matter what and still say that there are insufficient mats.
