### ISSUE TITLE
Can't pda people in different zlevel but Pda bomb can? Kinda dumb.

### ISSUE THREAD

**Issue by warface1234455** [BeeStation/BeeStation-Hornet#5825]
## Reproduction:

 
One traitor - buy bombing cart fridge?(Forgot what it called) - Another person will go to lavaland for example - the traitor does pda bomb - ????

**Comment by St0rmC4st3r** [comment]
iirc, you only can't send messages from z-levels with no comms, but still can receive them. Also you can use the PDA on lavaland.
