### ISSUE TITLE
Xenomorphs gasp for air

### ISSUE THREAD

**Issue by 1210Avi** [BeeStation/BeeStation-Hornet#5826]
## Round ID:
34137

## Reproduction:

Quite an old bug that I'm reporting. Xenomorphs will randomly gasp at any stage of life from chest burster to queen. This can be either just immersion breaking, or life-threatening as it can expose your existence in the pipes, or when hiding under a table.

**Comment by BrumalLake** [comment]
noo my immersion

**Comment by Howluinb** [comment]
> noo my immersion

It's terrible for gamebalance. There's been tons of xenos ousted because they were in vents and *gasp.
It makes no sense, too, indeed.

**Comment by 1210Avi** [comment]
round id: 35154. Xeno drone managed to sneak and hide inside the explorer ship pipes. Gets ousted by gasping for air and the explorers dismantle the pipe system in deep space until they find and shoot it down. Would have easily led to an unannounced infestation without the bug.
