### ISSUE TITLE
IPCs Get Suffocation damage when revived

### ISSUE THREAD

**Issue by GolfinhoVoador** [BeeStation/BeeStation-Hornet#583]
You get suffocation damage when getting revived as an IPC, Which makes you sleep forever.
The only way to wake up is with an admin healing you.

**Comment by SomeAngryMiner** [comment]
currently working on a fix, along with the cloneloss/brain surgery problems, actually.

**Comment by despong** [comment]
hi video

**Comment by St0rmC4st3r** [comment]
Confirming oxyloss buildup when in crit as IPC.
Whenever you get 60 oxyloss you are as good as dead.

**Comment by SomeAngryMiner** [comment]
should be fixed with the new IPC fix pr, wich makes them properly clear oxyloss and breathloss.
