### ISSUE TITLE
Atmospheric Technicians can't open firelocks with their ID

### ISSUE THREAD

**Issue by 4rchibald** [BeeStation/BeeStation-Hornet#5835]
## Reproduction:

PR #5638 came with ability to open firelocks by authorized personnel with their ID. For some reason atmospheric technicians (guys who are usually the one fixing air issues) are not authorized while regular station engineers are

Also if anyone would be working on it, it would be nice for PDA with proper ID in it to work on firelocks instead of having to eject it

@francinum

**Comment by BrumalLake** [comment]
i did exactly what this pr is claiming you can't do just 2 days ago

**Comment by 4rchibald** [comment]
@lordScrubling 
I'm pretty sure you must have been on skeleton crew or received extra access from CE/HoP then

I have faced firelock refusing to open for me while having vanilla atmos access and I actually made this report while observing a round with atmosian complaining he is not authorized to unlock firelocks

**Comment by francinum** [comment]
One line fix. Firelocks use access lists identical to firelocks
