### ISSUE TITLE
Making hyperspace/prides mirror not an inescapable prison.

### ISSUE THREAD

**Issue by UltraNumeron** [BeeStation/BeeStation-Hornet#5843]
Currently  if you eat hyperspace or use prides mirror you often get put in an empty space z level where you are unable to even throw  or target other tiles at all, and without outside help that will pretty much never come and  if they do come if you dont got  a gps will never find you. Or if you have one use a fulton.

So if those arent your options you are fucked with not being able to escape for even if you somehow reach the borders of the z level you cannot leave. I would pr this myself if i knew how, but i dont so im making a feature request. To make hyperspace less of an inescapable prison, to perhaps make it send you to station z level space or lavaland or  someplace else, because right now its just pain.

**Comment by DemonOfHatred** [comment]
... cant believe this hasnt been fixed since november
