### ISSUE TITLE
holopara's healing deals tox damage to oozelings

### ISSUE THREAD

**Issue by kit-katz** [BeeStation/BeeStation-Hornet#5847]
## Round ID:

N/A

## Testmerges:
N/A

## Reproduction:
get a holopara as an oozeling give it healing abilities. watch as it heals you it also kills you with "toxins"
we all know what's going on here

**Comment by zeskorion** [comment]
This is a really easy change to make

**Comment by kit-katz** [comment]
i know but my private server is in the wash

i cant do shit
