### ISSUE TITLE
shake_camera proc doesn't work anymore (for bombs etc)

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#5868]
## Reproduction:
1) Spawn a bomb any bomb.
2) Blow it up and stand near or a bit further away
3) no screen shake from explosion unlike what you would expect

Interrestingly other screen transforms like the one rotatium is doing still work kinda (trough it took a while i suspect that processing was messy)
However screenshake that should result from the proc call of /proc/shake_camera don't seem to do anything at all anymore.
I am unsure how long this issue actually has been present i tried to go back quite far back in the commit history of the repo without any changes to the problem at hand. However i am pretty sure screenshake did work for quite some of the timeframe i checked so i wonder if something is up with the byond version possible trough thats just speculation at this point in time other screen transforms worked after all trough those used a bit different syntax for the animate proc.
EDIT: This is a issue with the currently used byond version of 1568 (Serverside) the next version 1569 would fix this but only if the compile version of the server is changed.

**Comment by BrumalLake** [comment]
hurray

**Comment by MNarath1** [comment]
seems to be a server side issue of the currently used compile version of byond aka 1568 the next version 1569 would fix this but yeah we would need to up the currently used compile version sadly just downloading it clientside won't do

**Comment by Crossedfall** [comment]
Resolved by #5891
