### ISSUE TITLE
Force strings are part of item descriptions

### ISSUE THREAD

**Issue by mcmeiler** [BeeStation/BeeStation-Hornet#5869]
## Reproduction: 

Examine any item with a force string ("Force: medium", "Force: robust")

**Comment by zeskorion** [comment]
?

**Comment by mcmeiler** [comment]
![grafik](https://user-images.githubusercontent.com/83819203/143815358-342b3d90-f969-4443-89f7-d0226be46149.png)
Why add the force string to the bottom of descriptions when you can hover over

**Comment by ivanmixo** [comment]
Intentional

**Comment by zeskorion** [comment]
> ![grafik](https://user-images.githubusercontent.com/83819203/143815358-342b3d90-f969-4443-89f7-d0226be46149.png) Why add the force string to the bottom of descriptions when you can hover over

intentional

**Comment by PestoVerde322** [comment]
That's more relevant to the Holodeck's E-Sword however, I think that's very much intentional on whoever did them sooo...

**Comment by mcmeiler** [comment]
That's extremely dumb if that really is intentional. Why the actual fuck would you append the force string to descriptions when you can hover over the item to see it?
