### ISSUE TITLE
random items "Force:" at the end of the examine

### ISSUE THREAD

**Issue by ToasterBan** [BeeStation/BeeStation-Hornet#5902]
## Reproduction:examine an item and it, completely inconsistently may have "force:" at the end of its examine

https://media.discordapp.net/attachments/670954058206543892/917100257245020300/unknown.png

**Comment by ivanmixo** [comment]
Speaking of which, this could use some stylisation like making it a notice or italics for instance.

**Comment by KubeRoot** [comment]
Embedded image for convenience:
![image](https://media.discordapp.net/attachments/670954058206543892/917100257245020300/unknown.png)

**Comment by DatBoiTim** [comment]
Any other items this occurs on?

**Comment by ToasterBan** [comment]
> Any other items this occurs on?
> 

it appears to happen on any item that has a force greater than 0? not 100% certain on that tough

**Comment by ToasterBan** [comment]
don't have a screenshot but blocking items seem to have the blocking text at the end aswell

**Comment by DatBoiTim** [comment]
> don't have a screenshot but blocking items seem to have the blocking text at the end aswell

Oh yeah, sounds like it may be an issue with examine code
