### ISSUE TITLE
critter crate kills mob/living/carbon

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#5903]
## Reproduction:

Get a critter crate and step onto it and close it so that you are inside.
You will see that suddenly your character will get damage as if in an high pressure enviroment together with beeing unable to breath etc.
Simplemobs seem to be fine.
This seems to happen because 
`/obj/structure/closet/crate/critter/return_air()
	if(tank)
		return tank.air_contents
	else
		return loc.return_air()`
basically the emergency oxygen tank has a pressure of over 1000 kpa and this will return those value as the crate content including the pressure etc.
So if you close the crate you have the pressure of almost 10 atmospheres crushing down on you at once thats actually not that bad but game logic etc(also not bad in terms of not kill you immidiatly there are other issue with sudden pressure changes i am not going to go into here).
I presume this has to do with current auxmos behavior for stuff like this because tg that uses the exact same code as shown above does not have this issue at all.

**Comment by Kapu1178** [comment]
I always thought this was intentional

**Comment by MNarath1** [comment]
The way this seems to work does make it look to me as if this isn't intentional i personally think this happened because of the from LINDA and thus slightly different behavior trough i am not that versed in atmos code so this is just a guess however i know this doesn't happen on TG.
