### ISSUE TITLE
light system isn't working properly

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#5914]
## Reproduction:
https://youtu.be/0NFdc4xsVnw

the light sources are blue bioluminescence from plants

**Comment by Kapu1178** [comment]
This is less of a bug and more a limitation of Overlay Lighting as a whole. Its one of the small sacrifices that needs to be made for performant lights.

Edit: If you can't view a source of light, its overlay isn't drawn. Thats why this happens.
