### ISSUE TITLE
Blob lost it's ability to rally spores.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#5933]
Rally spore power of the blob doesn't work anymore.

**Comment by Sinmero** [comment]
I think this has to do with spore pathfinding. They cant rally when they are surrounded by blob fibers yet they rally just fine when they are not.
I think the pathfinding sees blob fibers as solid and tries to go around them.

Edit: #define CAN_STEP(cur_turf, next) (next && **!next.density** //_this appears to be the source of the problem_// && cur_turf.Adjacent(next) && !(simulated_only && SSpathfinder.space_type_cache[next.type]) && !cur_turf.LinkBlockedWithAccess(next,caller, id) && (next != avoid))

**Comment by MNarath1** [comment]
> I think this has to do with spore pathfinding. They cant rally when they are surrounded by blob fibers yet they rally just fine when they are not. I think the pathfinding sees blob fibers as solid and tries to go around them.
> 
> Edit: #define CAN_STEP(cur_turf, next) (next && **!next.density** //_this appears to be the source of the problem_// && cur_turf.Adjacent(next) && !(simulated_only && SSpathfinder.space_type_cache[next.type]) && !cur_turf.LinkBlockedWithAccess(next,caller, id) && (next != avoid))

wait you are right they seem to not ignore the blob tiles

**Comment by MNarath1** [comment]
This seems to happen because the density for blob structures was set to true and the proc handeling the Pathfinding uses the byond native density var to identify obstacles.

**Comment by MNarath1** [comment]
this is pain the only proper fix here would be to write a completly new pathfinding that instead of density takes passflags into account

**Comment by MNarath1** [comment]
> I think this has to do with spore pathfinding. They cant rally when they are surrounded by blob fibers yet they rally just fine when they are not. I think the pathfinding sees blob fibers as solid and tries to go around them.
> 
> Edit: #define CAN_STEP(cur_turf, next) (next && **!next.density** //_this appears to be the source of the problem_// && cur_turf.Adjacent(next) && !(simulated_only && SSpathfinder.space_type_cache[next.type]) && !cur_turf.LinkBlockedWithAccess(next,caller, id) && (next != avoid))

wrong the JPS pathfinding wasn't used for blob spores well its gonna be from now on trough(if the fix i made gets merged) and this checks for density in next and next is a turf (blobs are structures not turfs)
