### ISSUE TITLE
You are dead! message still appears under the status tab even if you were brought back to being alive

### ISSUE THREAD

**Issue by TeomanTheGreat** [BeeStation/BeeStation-Hornet#5935]
## Testmerges:
![image](https://user-images.githubusercontent.com/55861563/145689082-9bfb4a1b-00ab-4711-b439-60e1cec5efef.png)

## Reproduction:
Step 1. Die. Step 2. Come back to life. Step 3. Check status tab  (I have noticed this for a long while but neglected reporting it since I was lazy)
![image](https://user-images.githubusercontent.com/55861563/145688789-bf70e762-0859-4690-ab55-d20fec974fe1.png)

**Comment by Kapu1178** [comment]
This isnt a bug. All of those types of messages stay there until you click the X.

**Comment by TeomanTheGreat** [comment]
> This isnt a bug. All of those types of messages stay there until you click the X.

i had no idea. but they should disappear on their own tbh

**Comment by KubeRoot** [comment]
I think this should be turned into a feature request and kept open (unless we have one already)

**Comment by TeomanTheGreat** [comment]
> I think this should be turned into a feature request and kept open (unless we have one already)

ill make a separate issue as a feature request

**Comment by TeomanTheGreat** [comment]
#5936 Here
