### ISSUE TITLE
missing ghost lights

### ISSUE THREAD

**Issue by BrumalLake** [BeeStation/BeeStation-Hornet#5942]
## Reproduction:
ghosts no longer have their lights because of overlay lighting

![image](https://user-images.githubusercontent.com/85033680/145698819-60bd678f-e300-45bd-9138-a35fe590a1cc.png)

**Comment by ike709** [comment]
@Dejaku51

**Comment by Dejaku51** [comment]
Issue closed so i'll i'll take it as Explained

**Comment by BrumalLake** [comment]
when i closed this i heard they were apparently end round so i closed this after seeing they did have overlay lighting in the code
i actually played a full round today and saw they didn't have any lights even at end round if that's the case
