### ISSUE TITLE
Changeling Lizard stuck with Digitigrade Feet

### ISSUE THREAD

**Issue by DatBoiTim** [BeeStation/BeeStation-Hornet#5951]
## Reproduction:

1. Be a lizard changeling, no digitigrade legs
2. Transform into a lizard with digitigrade legs
3. Transform back into lizard with no digitigrade legs
4. You can no longer wear shoes.

**Comment by Kapu1178** [comment]
Fixed by the limb refactor

![image](https://user-images.githubusercontent.com/75460809/145920287-433dcdd6-2048-4cce-b627-86026dab8025.png)

**Comment by DatBoiTim** [comment]
> Fixed by the limb refactor
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/75460809/145920287-433dcdd6-2048-4cce-b627-86026dab8025.png)
> 
> 

Include the following in limb factor PR desc:

closes #5951

For autoclose's sake

**Comment by PowerfulBacon** [comment]
Changelings are bugged like this with mutations and traits. If you transform into someone with shit mutations or traits, you get screwed. Change back and you are still screwed.
