### ISSUE TITLE
The new light system broke the nightmare's evasion of the laser shots.

### ISSUE THREAD

**Issue by IllotAFV** [BeeStation/BeeStation-Hornet#5964]
Nightmare could dodge them in the past, it can't do that anymore.

**Comment by ivanmixo** [comment]
I mean this makes sense, no? Lasers emit light.

**Comment by IllotAFV** [comment]
Nightmare could evade them in the past, seems like an oversight problem to me.

**Comment by ivanmixo** [comment]
It could only dodge them due to lighting being so laggy the laser lights basically never rendered.
