### ISSUE TITLE
Ketamine split personality + monkify makes the body perma-catatonic

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#5968]
## Testmerges:
#5897: 'Molests Say code alot. Big roleplay update. Many ports.' by Kapu1178 at commit 23f3f90e9d
#5611: '[DNM] BetterLimbs' by Kapu1178 at commit ffb3f2630b

## Reproduction:
It's not correctly confirmed.
I monkified a person (to deconstruct their reinforced mutation) then fed mutadone into human. They were responsive at the moment before I was giving the mutation ('do it quickly!'), but once they became a human, they got catatonic too. (I didn't know they had a split personality issue.)
Below is a log that I and the admin talked about the situation.

> Admin PM from-Daridine: Any chance you could clarify that a little more
Click on the administrator's name to reply.
PM to-Admins: I tried to monkify Forgets-Their-Name and fed mutadone, suddenly they got catatonic
...
Admin PM from-Daridine: I have no idea what exactly was causing it, but I think their split personality, plus the monkification broke something
...
PM to-Admins: I have a question. was the real 'Forgets-Their-Name' still connected at the moment?
Admin PM from-Daridine: They were, but either you or them had taken a ghost role
Admin PM from-Daridine: I was trying to drag whoever was a ghost still back into the body and it wasn't taking
Admin PM from-Daridine: Something to do with monkifying then mutadone too
PM to-Admins: that's how you got a clue about split + monkey ones. got it. thank you!

**Comment by BNGP0** [comment]
By the way, monkefying and demonkefying someone with genetics console turns them into a human, despite of their starting race. Is it supposed to be like this or is it a bug?
