### ISSUE TITLE
Putting clown backpack into locker while still having the interface open allows retrieval of all items while in locker

### ISSUE THREAD

**Issue by DemonOfHatred** [BeeStation/BeeStation-Hornet#5972]
Issue reported from  Round ID: 34744 (BeeStation Sage - Roleplay)

Reporting client version: 514.1571

Even though my stuff was put in a security locker I had the backpack open still which allowed me to pull all of my stuff out still.

**Comment by St0rmC4st3r** [comment]
This is known

**Comment by zeskorion** [comment]
This is the general case for storage yes
