### ISSUE TITLE
Cloning only shows ''Body-Only''

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#5997]
Don't know when exactly this issue started to happen but at the current moment, when you select someone to clone them the only option that shows is ''Body only'', from what i've seen on **multiple** rounds this had lead to the following scenarios:

- Most doctors mains and new were equally confused about why only that option was showing up
- Brains sometimes didn't transfer the soul correctly to the new body, since well.. it does create a ''body only''.
- A lot of unespecified reasons for the body not being suited to be clonned (since empty clone works differently than regular iirc)

**Comment by EvilDragonfiend** [comment]
@jupyterkat I think you're involved in this.

**Comment by EvilDragonfiend** [comment]
![image](https://user-images.githubusercontent.com/87972842/147309389-c1e5eb08-14e9-4a7c-9fb6-8a79e2814bfb.png)
I don't know which is which, but two are full and empty.

**Comment by EvilDragonfiend** [comment]
plus, the TGUI isn't updated actively when we clone it.
I mean, when we copy our clone, we need to touch the clone console manually to refresh the TG clone interface.

**Comment by EvilDragonfiend** [comment]
@Fronsis just telling you. You can't clone whom you presaved, and it has been always so.
I tried to correct some the cloning failure issue, but I am not sure if it would work properly. We'll find it out.

**Comment by Mails-z** [comment]
Cloning worked perfectly before it was rework, I miss it working well
