### ISSUE TITLE
Advanced sunglasses/sechuds/relatives don't have weld protection

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#5998]
From what i've gathered from other players this was a very old bug/unintended feature  that has re-emerged somehow, at the time being all the advanced sunglasses and sechuds haven't had their tag and description changed to reflect that you do, in fact, get blind and don't have weld protection

I'm reporting it as a bug since that's what everyone think it is and there's nothing on github or the **changelog** that reflects this big change being implemented.

**Comment by zeskorion** [comment]
advanced sunglasses only provide 1 flash protection, weld protection is 2

**Comment by Fronsis** [comment]
And.. Why did it got reduced to 1? Why wasn't this on the changelog (if it got sneak changed on the tag pr) From what i've seen most people dislike it and it's been something quite iconic for a bit, but yeah everyone is saying it's a bug.

**Comment by zeskorion** [comment]
> And.. Why did it got reduced to 1? Why wasn't this on the changelog (if it got sneak changed on the tag pr) From what i've seen most people dislike it and it's been something quite iconic for a bit, but yeah everyone is saying it's a bug.

eh, they shouldnt have had that behavior in the first place.

**Comment by ivanmixo** [comment]
They should not have flash protection.

**Comment by BrumalLake** [comment]
the pr to make sunglasses not protect from welding got closed https://github.com/BeeStation/BeeStation-Hornet/pull/5035 but somehow it got snuck in anyways and no one cared i guess

**Comment by BrumalLake** [comment]
turns out it was caused by overlay lighting
![image](https://user-images.githubusercontent.com/85033680/146677115-886e0e8c-1d7f-4c30-be38-9026e0d97942.png)
![image](https://user-images.githubusercontent.com/85033680/146677133-d97e37fc-ee00-4666-852a-2851269c5bad.png)

**Comment by ivanmixo** [comment]
Good. Sunglasses being basically meta isn't good. Welding equipment should exist for a reason.

**Comment by Fronsis** [comment]
I figured it was thanks to the new overlay lighting, in any case if someone can add it into the changelog i would appreciate it so everybody stop thinking it's bugged and it's something 100% intended

**Comment by BrumalLake** [comment]
it's not intended and i guess you could call it a bug but it is here to stay

**Comment by PowerfulBacon** [comment]
This is now a feature, I assume the original was a stealth nerf ported from tg
