### ISSUE TITLE
Wraiths can still teleport straight into the AI Satellite.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#6026]
They shouldn't be able to do this for the same reason that Clock Cultists can't.

**Comment by zeskorion** [comment]
I'd nerf them, but cult is so Op im just gonna remake it from the ground up

**Comment by cometevil** [comment]
Clockcult can liitterly teleport outside hack in disable turrets with the lockerstrat and take the ai it won't matter cult just needs a rework

**Comment by AnCopper** [comment]
> Clockcult can liitterly teleport outside hack in disable turrets with the lockerstrat and take the ai it won't matter cult just needs a rework

Is this supposed to be a comparison?

**Comment by PowerfulBacon** [comment]
This is not a bug, wraith teleportation can be cancelled by the chaplain blessing tiles
