### ISSUE TITLE
Xenos able to hold (and use) almost any item if it embeds/sticks

### ISSUE THREAD

**Issue by ToasterBan** [BeeStation/BeeStation-Hornet#6031]
## Reproduction:

1.get an item, any item if you duct tape it

2.throw it at the beno

3.have the beno click on itself with an empty hand in help intent

4. have it remove the embedded item

5. it now holds the item and can throw it or even use it

**Comment by Mails-z** [comment]
I have give a benos a bike honk now

**Comment by Mails-z** [comment]
Aww
