### ISSUE TITLE
FUKING NEW MONKEYS TAKE LIGHTBULBS

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#6035]
Issue reported from  Round ID: 34929 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568
The dam new monkeys grab lightbulbs making xenobioly and genetist very dark, your average monkey-brain assistant can't do this because he burns his hand.

**Comment by KubeRoot** [comment]
What's the issue? Seems like everything's working as intended.

**Comment by ike709** [comment]
> What's the issue? Seems like everything's working as intended.

The lightbulbs are on. Players can't do this.
