### ISSUE TITLE
wt550 security autorifle doing no damage sometimes?

### ISSUE THREAD

**Issue by heepox** [BeeStation/BeeStation-Hornet#6040]

**Comment by zeskorion** [comment]
sounds like nanites or viro. healing coupled with damage resistance.

viro's a bit more obvious, you'd see spikes or he'd be slow

**Comment by heepox** [comment]
no nanites, no virus, no armour
he even wondered why he was taking no damage and we both paused in the middle of combat.

**Comment by PowerfulBacon** [comment]
Investigating

**Comment by PowerfulBacon** [comment]
Only ammo type that I used that didn't do visible damage on the health hud was the rubber rounds, which caused stamina damage and stun-crit. Could not reproduce
