### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by cometevil** [BeeStation/BeeStation-Hornet#6041]
Issue reported from  Round ID: 34954 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

The ORM failed to spawn in none of cargo knew where it was at and we always had a person at the front desk meaning no one could've taken it without our knowledge. someone please look into this we had to make one and thats very annoying if you are forced to make one every round.

**Comment by Dejaku51** [comment]
Map?

**Comment by EvilDragonfiend** [comment]
please change the title to identical.

**Comment by cometevil** [comment]
I'm not aware of the map name the most I can tell you is cargos at the bottom medbays at the right and explorer shuttle is below cargo

**Comment by Dejaku51** [comment]
Map is Flandstation and author is aware of it. If it won't be fixed soon just bully PigeonVerde#8826 on discord

**Comment by PowerfulBacon** [comment]
Looking at the map file, it seems an ORM has been added
