### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by cometevil** [BeeStation/BeeStation-Hornet#6042]
Issue reported from  Round ID: 34956 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

Hypno flash breaks and doesn't actually drop in the memory forced to ask admins to put the memory in for it to do anything and if it does drop a memory it drops random words or another persons sentence instead of the one you throw in

**Comment by St0rmC4st3r** [comment]
Did you take off the victim's headset?

**Comment by cometevil** [comment]
Yes I did

**Comment by PowerfulBacon** [comment]
Hypnoflash requires a target to be sleeping / drugged / drunk / vulnerable in some way.

**Comment by PowerfulBacon** [comment]
Seen the hypnoflash working in game, so can confirm that it definitely works. You need to flash the target twice to hypnotise them, so it may be an issue of poor communication between the device and the player.
