### ISSUE TITLE
Explorer gun increased damage to simplemobs is bugged.

### ISSUE THREAD

**Issue by Isy232** [BeeStation/BeeStation-Hornet#6048]
## Testmerges:

Local, none applied.

## Reproduction:

Use explorer gun on "anti-creature" mode.

It takes 9 shots to kill a 125 hp xeno, for 15 damage per shot instead of the 30 it should be doing.

Something is probably wrong with this code as the gun does 15 to everything instead of 30 on simplemobs.

```
/obj/item/projectile/beam/laser/anti_creature
    damage = 15
    tracer_type = /obj/effect/projectile/tracer/laser
    muzzle_type = /obj/effect/projectile/muzzle/laser
    impact_type = /obj/effect/projectile/impact/laser

/obj/item/projectile/beam/laser/anti_creature/on_hit(atom/target, blocked)
    damage = initial(damage)
    if(!iscarbon(target) && !issilicon(target))
        damage = 30
    . = ..()
```

**Comment by KubeRoot** [comment]
From a quick codedive, I think a projectile's `on_hit` is ran after `apply_damage`:

```dm
/mob/living/simple_animal/bullet_act(obj/item/projectile/Proj, def_zone, piercing_hit = FALSE)
	apply_damage(Proj.damage, Proj.damage_type)
	Proj.on_hit(src, 0, piercing_hit)
	return BULLET_ACT_HIT
```

Which means the damage is only doubled *after* the damage has already been inflicted.
Not sure what the best way to resolve this is though.

EDIT: Looking at some other code, `prehit_pierce` might be the proc we want. It's used in ctf code to adjust the damage of the projectile based on the target.

**Comment by PowerfulBacon** [comment]
oof

**Comment by DatBoiTim** [comment]
Testing fix right now.
