### ISSUE TITLE
You can blind yourself with your own pepperspray.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#6059]
The cloud isn't fast enough.

**Comment by KubeRoot** [comment]
Are you talking about spraying in a direction while standing still? Or spraying in the direction you're running?

**Comment by AnCopper** [comment]
> Are you talking about spraying in a direction while standing still? Or spraying in the direction you're running?

Running.

**Comment by KubeRoot** [comment]
I don't see an issue then, happens in real life too. You're just running in the same direction you're spraying, of course you might run into your own pepper spray cloud.

**Comment by BrumalLake** [comment]
> The cloud isn't fast enough.

i logged in yesterday and i saw someone who was probably you do this
wear a gas mask next time
