### ISSUE TITLE
Kapulimbs Broke Romerol Zombies

### ISSUE THREAD

**Issue by heepox** [BeeStation/BeeStation-Hornet#6074]
## Testmerges: 
Kapulimbs
https://github.com/beestation/beestation-hornet/pull/5611

## Reproduction: 
Infect someone with zombie claw (romerol zomvbie) and kill them... they wont rise up just get limbs replaced and drop old limbs every defib. (leads to a stack of like 10 of the same guys limbs including heads)

Kapulimbs may have broken romerol zombies...
they dont rise after infection and death
and they drop all their limbs and gain zombie limbs
and the limbs they gain become invisible
they drop multiple copies of the same limbs including head every defib
They also no longer make the occasional zombie moan sound that alerts everyone to the presence of the undead

**Comment by Demi-Wahoo** [comment]
Also about the issue.
The issue also unfortunatley works on the virology symptom "Autophagocytosis Necrosis".
This virus makes zombies, but also special zombies. This issue also affects those zombies.

**Comment by Kapu1178** [comment]
Investigating zombie shitcode.

**Comment by Kapu1178** [comment]
Fix committed. It won't be live on Sage for a bit because our maintainers are away or drunk. If other issues crop up, please comment on this issue.
