### ISSUE TITLE
Can't Juice Pineapples???

### ISSUE THREAD

**Issue by civilCornball** [BeeStation/BeeStation-Hornet#6080]
Issue reported from  Round ID: 35103 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1568

Exactly what it says on the tin. I put the pineapples into the juicer, which has a beaker currently inside. I click on it, select "juice." It whirrs, I click on it again, and eject it. Note that the selection GUI has not changed one bit.

The pineapples are unchanged. Still whole fruits.

I even went to botany and used some of the vanilla seeds from the dispenser. Tried those, no dice.
Tried cutting the pineapples, 'cause maybe they were too large. Nope.

**Comment by BrumalLake** [comment]
wypi

**Comment by KubeRoot** [comment]
This might be unintuitive, but as far as I can tell not a bug - it's just that there's no pineapple juice for you to get out of juicing pineapples. Judging by lordScrubling's comment, this might be a feature in another codebase, in which case it should be easy to port if somebody's willing to do it.

**Comment by civilCornball** [comment]
Yeah, I needed it for some drink recipes in https://wiki.beestation13.com/view/Guide_to_food_and_drinks

**Comment by KubeRoot** [comment]
That's odd, but looking in the code, looks like neither the Painkiller nor Pina Colada actually exist. I just wonder if that's something that was removed without updating wiki, or if somebody added it while not adding the actual drinks...

**Comment by BrumalLake** [comment]
#5551
