### ISSUE TITLE
Blob spores remain docile and passive

### ISSUE THREAD

**Issue by 1210Avi** [BeeStation/BeeStation-Hornet#6098]
## Round ID:
35152

## Reproduction:
On the mentioned round ID a zombifying blob spawned. Its multiple spores were passive and never moved on their own to attack the crew.

**Comment by MNarath1** [comment]
Kinda my fault that comes from when you decide to add a nice feature to a PR and forget to go trough the whole chain of tests you did beforehand cause it sounded minor enough i made blob spore pathfinding avoid mobs..... including mobs they target thats why they won't move the PR i mention here will fix this however and has some other nice stuff in it.
