### ISSUE TITLE
Station Engineers don't start round wearing their Beecoin items

### ISSUE THREAD

**Issue by 4rchibald** [BeeStation/BeeStation-Hornet#6103]
## Reproduction:

If you are a station engineer and you equip jumpsuit or hard hat from Beecoin shop you will start round holding those items in your hands.
I have no idea how things like shop items or clothes themselves are handled but I believe its station engineer issue since when you start the game as atmos technician you will be wearing those very same items.

![coinshophands](https://user-images.githubusercontent.com/54917446/147994903-24dbbd54-9a21-4f28-97b0-d2fad9e65d47.png)

**Comment by TzuInferno** [comment]
This is for every job. More specifically, if a job has an item you already start with in that slot, it just puts it in your hands or inventory, or drops it on the floor.
