### ISSUE TITLE
Gibbonite doesn't store correctly in a suit storage unit

### ISSUE THREAD

**Issue by SpinnerMaster** [BeeStation/BeeStation-Hornet#6109]
Issue reported from  Round ID: 35187 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

I tried storing some gibbonite ore in a suit storage unit on lavaland mining base. I was just curious if I could put it in there, it fits into the storage slot just fine, but when you hit the close button it appears on the ground at your feet, but when you open the suit storage unit it appears to be in the storage slot. When you click the gibbonite in the suit storage unit the gibbonite on the ground teleports on top of the suit storage unit. I don't think teleporting gibbonite is an intended mechanic.

To reproduce:

1. Put gibbonite into a suit storage unit
2. Close suit storage unit, gibbonite ore appears at your feet
3. Open suit storage unit, gibbonite ore appears to be in the storage slot
4. Click gibbonite in the suit storage unit slot
5. Gibbonite moves to the suit storage unit

**Comment by MNarath1** [comment]
Sounds like something force moves the gibtonite but doesn't clear the reference to it from the suit storage unit.
