### ISSUE TITLE
Formatting doesn't work on the new communications console TGUI.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#6110]
![image](https://user-images.githubusercontent.com/82319489/148237289-a7a6cbc3-b7f2-4dfb-90af-fa80f2aba98a.png)

**Comment by Dejaku51** [comment]
@KubeRoot

**Comment by KubeRoot** [comment]
Thanks for the ping, looks like I missed https://github.com/tgstation/tgstation/pull/54765 when porting.
