### ISSUE TITLE
Removing a xenomorph's alien tongue allows them to speak Common in runechat

### ISSUE THREAD

**Issue by VictorVow** [BeeStation/BeeStation-Hornet#6111]
## Testmerges:

KapuLimbs I think is being testmerged still, I can't see how I can check since my chat window has already scrolled past the beginning logs.

## Reproduction:

A human scientist was turned into a xenomorph I believe (Xul-Ru), and I observed a crew member operating on them to remove their alien tongue. After removal, when they tried to speak it showed in the chat log it showed as "Xul-Ru makes a strange sound." but it showed as Galactic Common in runechat above their head. They weren't able to understand Common themselves, but other crew members could understand them.

**Comment by rkvothe14** [comment]
> I can't see how I can check since my chat window has already scrolled past the beginning logs.

In OOC tab, press Show Server Revision

**Comment by VictorVow** [comment]
Still a bug.
