### ISSUE TITLE
Science shuttle on Fland can't dock anywhere but the station

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#6115]
Issue reported from  Round ID: 35201 (BeeStation Sage - Roleplay) (Actually the previous round which was on Flandstation)

Reporting client version: 514.1571

I got science shuttle (not exploration) working and flying normally though space. It would launch, supercruise, track targets, all fine. But any time I tried to dock in a space ruin, I would be docked right back at the exploration dock in the station, where the shuttle launched from, and nowhere close to where the science shuttle actually was.

This happened on 3 different signals in space, 2 being apparently empty z-levels, and the other being a normal space ruin, which I actually managed to see the z-level before choosing a place to stop the shuttle in, but docked back in the station.

**Comment by PowerfulBacon** [comment]
Should be fixed by this PR, deconstructing a shuttle console currently causes the previously placed custom dock location to never be reverted meaning any time you dock at a custom location you get sent back to the old one.

If the issue takes you somewhere but a custom dock, or happens when not docking at a custom dock then it may be anotehr problem.

**Comment by PestoVerde322** [comment]
i think this is a bit of my fault, accidentally killed the dock there, but the SP2 should fix it soon-ish

**Comment by PowerfulBacon** [comment]
Just confirmed that it's not docking with custom docks at all, so is a different issue

**Comment by PestoVerde322** [comment]
![immagine](https://user-images.githubusercontent.com/75247747/148290482-4b23446d-c4b4-453d-b1c6-42da462ac949.png)
now the dock works, some updating touches and it should be good. 
Stay tuned for the update.

**Comment by ike709** [comment]
Fixed
