### ISSUE TITLE
Parallax movement  effect is broken

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#6118]
The parallax movement effect very rarely works on shuttles:

Reproduction:
 - Launch any shuttle
 - A majority of time the parallax effect will simply not work unless you leave and re-enter the area.

Additionally, entering a camera and then exiting it while on a shuttle cancels the parallax movement effect.

**Comment by St0rmC4st3r** [comment]
I remember it breaking after one of the byond updates

**Comment by Mat05usz** [comment]
Fixed by: https://github.com/BeeStation/BeeStation-Hornet/pull/6891
