### ISSUE TITLE
Exploration VIP death bugs and prevents picking further missions

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#6131]
I've experienced this issue at least three times:

If the person who was VIP dies and soul departs while on the Z level of the mission it prevents the mission from being completed AND prevents you from picking a new one, since the body can't be defibbed and even if you clone it back at the station it won't suddenly count as completed

I had to ask an admin to delete the mission since we weren't able to pick a new one

For some reason i thought that you could brought the VIP death for a lower pay out

**Comment by Fronsis** [comment]
I believe @PowerfulBacon is the one to report the intercruise/exploration stuff right?

**Comment by ike709** [comment]
Fixed
