### ISSUE TITLE
Changeling Sting not noticeable

### ISSUE THREAD

**Issue by TheLarker** [BeeStation/BeeStation-Hornet#6139]
Issue reported from  Round ID: 35238 (BeeStation Sage - Roleplay)

Reporting client version: 514.1571

I was running around, trying to fix an unsalvageable situation, when a ling stung me. Except, I could not tell at all that I had been stung, since I did not get the "You feel a tiny prick." message in red.

And then the changeling came to finish me off once I was down because of it.

Please fix this.

![image](https://user-images.githubusercontent.com/97289046/148537071-aabbf0b7-21b4-48ce-9639-c13bb9559f90.png)

**Comment by BrumalLake** [comment]
it's designed that way

**Comment by St0rmC4st3r** [comment]
As a non-changeling you can feel all stings except DNA extractor, Hallucination sting, and Cryo sting.
Changelings can feel all stings.

**Comment by PowerfulBacon** [comment]
What sting was it?

**Comment by DatBoiTim** [comment]
From OP:

> And then the changeling came to finish me off once I was down because of it.
------------------------------
> What sting was it?

Given that I'm gonna wager cryo sting, as that would be the only sting that can cause damage and not be felt

**Comment by Kryyto** [comment]
Someone should probably close this
