### ISSUE TITLE
Clothing doesn't cover the other worn clothing that it's supposed to

### ISSUE THREAD

**Issue by VictorVow** [BeeStation/BeeStation-Hornet#6158]
## Reproduction:

Spawn or pickup `/obj/item/clothing/mask/gas` or `/obj/item/clothing/mask/gas/old`. Notice that `flags_inv = HIDEEARS|HIDEEYES|HIDEFACE|HIDEFACIALHAIR` doesn't seem to work as you can still:
- Examine yourself and still see what's being worn on eyes, ears etc
- It still shows on sprite (use bowman's or earmuffs for more obvious sprite change) 

The same happens for hardsuits and spacesuits - it shows the uniform underneath on examine, when this should be hidden. 
e.g.
```
This is Ricky Manley!
He is wearing   an engineer's jumpsuit.
He is wearing   a wig on his head.
He is wearing   an engineering hardsuit.
He is carrying   an extended-capacity emergency oxygen tank on his engineering hardsuit.
He has   a backpack on his back.
He has   some insulated gloves on his hands.
He has   a toolbelt about his waist.
He is wearing   some work boots on his feet.
He is wearing   PDA-Ricky Manley (Station Engineer).
```

Another report on Discord suggested that your uniform still burns when wearing a fireproof hardsuit, but I haven't tested this personally.

**Comment by DatBoiTim** [comment]
I've tested the Advanced Hardsuit. Issue persists regardless of whether you use EVA or Combat mode.

Issue also seems to effect the firesuits.

**Comment by BrumalLake** [comment]
ah this is why you can see masks and stuff peeking out under clothing most remarkably through envirohelms
nevermind must've always been a thing cause i can track it earlier

**Comment by DatBoiTim** [comment]
#6184 Also documents issue for other items
