### ISSUE TITLE
Having the blackbox in hand when the shuttle docks with centcomm will cause the objective to fail if not buckled in to a chair..

### ISSUE THREAD

**Issue by Crus0** [BeeStation/BeeStation-Hornet#6159]
See title, even if you have the box in hand when the shuttle docks with centcomm (while not buckled to a chair), you will fail the objective due to you dropping the box with no chance of picking it up. This seems like an oversight, as you do in fact reach centcomm with the box in hand, but you end of failing nonetheless. 

Reproduction:
1. Have blackbox in hand 
2. Do not be buckled to a chair
3. Wait until the shuttle docks with centcomm, the box will fall out of your hand and you fail despite the box being on the tile you are standing on.

**Comment by AnCopper** [comment]
Intended behaivor.

**Comment by Archanial** [comment]
Not a bug
