### ISSUE TITLE
Weirdness with Mining Shuttle Console

### ISSUE THREAD

**Issue by civilCornball** [BeeStation/BeeStation-Hornet#6167]
Pressing the "zoom in" or "zoom out" button on a Mining Shuttle Console, then attempting to scroll down, will cause the window to scroll down to an area without any element. It's just the default background.

Issue reported from  Round ID: 35316 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1572

**Comment by ike709** [comment]
Is this still an issue?

**Comment by civilCornball** [comment]
It is indeed.

**Comment by PowerfulBacon** [comment]
I believe KubeRoot fixed this
