### ISSUE TITLE
GUI Weirdness: Ghost Orbit Menu

### ISSUE THREAD

**Issue by civilCornball** [BeeStation/BeeStation-Hornet#6176]
## Round ID: 35379 (BeeStation Sage - Roleplay)
![image](https://user-images.githubusercontent.com/48499004/149422010-3447c168-de5c-4874-965c-19c2be269b63.png)

## Reproduction:
Find a name that ends up stretching waaaay past the border of the window.
Click and drag your mouse over it, as if you're highlighting it.
Yep. That's a thing.

Resets if you close and reopen the Orbit menu. So that's nice.

Maybe we could add a bottom scroll bar instead of just fixing this?

**Comment by ro5490** [comment]
@Archanial 
Was this meant to be reopened?
