### ISSUE TITLE
Fleshy mass is invisible

### ISSUE THREAD

**Issue by covertcorvid** [BeeStation/BeeStation-Hornet#6177]
## Round ID:
35380

## Reproduction:
1. Have an alien abductee
2. Do surgery to replace the fleshy mass with a heart
3. Go to pick up the fleshy mass
4. Find that it is invisible
5. Pick it up with right click
6. Find that it is still invisible

**Comment by zeskorion** [comment]
This bug is commonplace. I believe it's because these are hearts, and dont have a beating icon state
