### ISSUE TITLE
exploration assassination targets spawned without oxygen in atmos

### ISSUE THREAD

**Issue by DerpiestBruh** [BeeStation/BeeStation-Hornet#6178]
## Reproduction:

- be ghost
- observe around for a while
exp crew gets assassination announcement
- minutes later, target spawns
- spam click and join
- HOLY SHIT THERES NO OXYGEN

**Comment by DatBoiTim** [comment]
Can you provide details about the room?

If it was one of the rooms that's partly spaced, you're SOL. Otherwise sounds like a generation issue.

**Comment by DerpiestBruh** [comment]
My brain is really short minded so I might have forgotten few things

I believe I spawned in a corner of the outpost? No hull breach in sight, there were no windows, only one airlock north, the south (and probably right) walls lead to space, misc stuff in the floor (trash and "radioactive" puddle mainly) and the only lights in the room was a red glowstick in the floor

There was a extra toolbelt and a big oxygen tank under where I spawned, I couldn't use it for a good part of my characters life because I had no breathmask

I didn't get any pressure warnings or damage, only there wasn't enough oxygen for me to inhale

**Comment by ike709** [comment]
@PowerfulBacon
