### ISSUE TITLE
Lazarus Injector does not function

### ISSUE THREAD

**Issue by VickiMorris** [BeeStation/BeeStation-Hornet#6180]
Issue reported from  Round ID: 35384 (BeeStation Sage - Roleplay)

Reporting client version: 514.1571

## Reproduction:
Purchase Lazarus Injector from mining equipment vendor
Attempt to inject French Ian (Yann)
No prompt in textbox for attempt, Laz Injector remains unused and Yann remains dead.

**Comment by BNGP0** [comment]
Did you try to use it on a player?

**Comment by VickiMorris** [comment]
No, I was attempting to use it on a non-sentient/player controlled Ian as an IPC.On Jan 15, 2022 11:56 AM, BNGP0 ***@***.***> wrote:
Did you try to use it on a player?
