### ISSUE TITLE
Atmospheric Hard-suit not properly protecting clothing from heat.

### ISSUE THREAD

**Issue by Overdrive659** [BeeStation/BeeStation-Hornet#6184]
Issue reported from  Round ID: 35403 (BeeStation Sage - Roleplay)

Reporting client version: 514.1569

---Background & Issue---

Was playing traitor round, for once in a lifetime, as atmospherics technician and was retrieving my contraband from security by breaking in from space, dragging a pump of plasma behind me for areal denial. I lit the plasma as I made my escape but to my horror and surprise all of my clothes and items burn up in the heat, leaving me without internals or gear in only an atmos suit. Safe to say I died of suffocation as I tried to escape to space without internals because they burned up. The suit was fully sealed and worked in space.

**Comment by Overdrive659** [comment]
had the exact same thing happen to me in departures with another plasma fire.

Round ID: 35419 (BeeStation Sage - Roleplay)

Reporting client version: 514.1569

**Comment by DatBoiTim** [comment]
Issue is documented in #6158 for other items. Add this to the pile of things broken I guess.
