### ISSUE TITLE
Bahama Mama Wiki Recipe incorrect / Bugged

### ISSUE THREAD

**Issue by DesecratedSage** [BeeStation/BeeStation-Hornet#6185]
Issue reported from  Round ID: 35404 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1575

What it says on the tin. Bahama Mama Cocktail on Wiki is 2 parts Rum, 2 parts Orange juice, 1 part Lime, 1 part Ice. It doesn't mix.

**Comment by BrumalLake** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/5551 recipe was changed
