### ISSUE TITLE
Technological Shells can't be printed 

### ISSUE THREAD

**Issue by Zar000** [BeeStation/BeeStation-Hornet#6194]
Issue reported from  Round ID: 35427 (BeeStation Sage - Roleplay)

Reporting client version: 514.1575

During Nukies war, I researched weapon development research which highlights the Unloaded Technological Shell, I proceed to sec to try and print some of them and they wouldn't show up. Admin told me to report it so here I am.

**Comment by Dejaku51** [comment]
are you sure they were researched and you refreshed protolathe? the research is "Exotic Ammunition"

**Comment by Dejaku51** [comment]
oh i see the issue now i think

**Comment by Zar000** [comment]
An admin told me it was bugged and that I should report it. Maybe I failed to try something but I did the following :
- Dont remember research node but it has an image of the shell, I researched it.
- Went to sec and synced with latest
- Searched " shell " , " unloaded " , " technological "
- Went into ammo category
- Went into weapons category
Nowhere to be seen

**Comment by DatBoiTim** [comment]
Exotic ammo gives the tech shells. It requires exploration to have recovered a disk, which is unlikely with war ops.

What admin told you this? I need more details.

**Comment by Zar000** [comment]
I did not remember their name at all, but the roundID is in my original post so perhaps checking logs would reveal who they are?

**Comment by DatBoiTim** [comment]
> I did not remember their name at all, but the roundID is in my original post so perhaps checking logs would reveal who they are?

I'm not a maintainer, no log access.

Was asking for name so they could provide me with the any research related logs.

**Comment by PowerfulBacon** [comment]
Weird that it shows under another research, it should be under exotic ammunition which requires a tech disk
