### ISSUE TITLE
Charlie Station (Proper /tg/ Charlie) Is Borked

### ISSUE THREAD

**Issue by unit0016** [BeeStation/BeeStation-Hornet#6198]
Randomrooms thought it'd be funny to spawn regular charlie station, and none of the /turf/s actually spawned, period. All the objects inside did, but not the turfs themselves.

I was still able to spawn and even yoink a spacesuit before the thing got deloaded by explorers, but uh..
Wooohooo boy.
Issue reported from  Round ID: 35446 (BeeStation Sage - Roleplay)

Reporting client version: 514.1568

**Comment by St0rmC4st3r** [comment]
Known bug. Sometimes the maps don't get property unloaded.

**Comment by unit0016** [comment]
> Known bug. Sometimes the maps don't get property unloaded.

Possibly not the same? *Maybe?* The objects unloaded a bit after I spawned, with the "You've been left behind" message displaying.
...And I was left alive.
