### ISSUE TITLE
[Metastation] Chemistry window restricted access

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#6200]
![bug](https://user-images.githubusercontent.com/72167130/149676394-bbc94b96-ee11-40be-bd00-70faa352f711.png)
In this picture I try to deliver some green slimes, but the window have access restricted, you can see the red light on it.
Maybe this is intended to be this way, but I doubt it.

**Comment by ta3370** [comment]
There's two public desks to the north, that's the internal-medbay-use desk.
