### ISSUE TITLE
Ling headcrabbing qdels backpack and its contents (Heads, brains, AI cards, you name it)

### ISSUE THREAD

**Issue by Megaddd** [BeeStation/BeeStation-Hornet#6215]
## Reproduction:
An easy (but debatably costly) way to qdel anything as a ling is to put it in your bag and headcrab. All the bag's contents disappear.

**Comment by zeskorion** [comment]
Any source of gibbing does this.

**Comment by Tsar-Salat** [comment]
This is intended behavior AFAIK

**Comment by Tsar-Salat** [comment]
If we want ling's to have an alternative "Last Resort" ability, that should be done in a balance pr.

Otherwise, it is as Zams said, its just how gib() works.
