### ISSUE TITLE
Random Space shuttles won't spawn

### ISSUE THREAD

**Issue by spockye** [BeeStation/BeeStation-Hornet#6225]
## Reproduction: shuttles at the caravan space ruin won't spawn. probably because of some exploration fuckery

take any kind of shuttle, go to space, find the caravan ruin, the pirate ship and syndicate dropship are gone

**Comment by ike709** [comment]
@PowerfulBacon

**Comment by Archanial** [comment]
Round ID would be really useful on this one since it's most likely tied to a runtime
