### ISSUE TITLE
Transformative light pink extracts arent working

### ISSUE THREAD

**Issue by snek-with-tophat** [BeeStation/BeeStation-Hornet#6228]
Transformative light pink were supposed to make slime and it descendants ghost controllable, it does not do that, they dont show up in spawner menu, and they cannot be controlled by clicking the slime directly
Reproduction:
Feed adult black slime 10 lightpink cores then use resulting extract on a baby slime

**Comment by St0rmC4st3r** [comment]
The dominant extract is the one that you **feed** to the colour you want. If you want a transformative light pink, you need to feed 10 black extracts to an adult light pink slime.
