### ISSUE TITLE
Sticky Grenade Bug

### ISSUE THREAD

**Issue by Isy232** [BeeStation/BeeStation-Hornet#6232]
## Round ID: 35,591

Reproducable in local, affects current server.

## Testmerges:

BYOND Version: 514.1568
Server revision compiled on: 2022-01-21
Master commit: 26eee18159bbed86e92daa9260c2b1f57279a59b
Local commit: 66823dedae8628beb4018d59c45c5b362ebd1a21

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Protect Command Roles From Traitor: 1
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 15 of 28 roundtypes
Allow Midround Antagonists: 7 of 28 roundtypes

## Reproduction:

Use sticky tape on a chemical grenade to make a sticky chemical grenade.
Ignite the grenade and throw it at the head of a xenomorph queen's sprite.
Grenade gets stuck to your hand, is undroppable and isn't thrown.
You blow up.

It works just fine if you click on the middle of the xenomorph queen's sprite (as in the part still on the tile the queen is on). And will stick to the queen and blow it up.

**Comment by zeskorion** [comment]
sticky tape has an rng chance to stick to your hand on throwing stuff iirc

**Comment by Isy232** [comment]
This is a s

> sticky tape has an rng chance to stick to your hand on throwing stuff iirc

yep,. damnit, it does.

annoying how there is no way to know this unless you dived into the code or died to it while looking very closely at the chat for the small message of "oh shit you dead"
