### ISSUE TITLE
Breath and gas maks burn through fireproof hardsuits.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#6233]
Which will cause you to die.

**Comment by DatBoiTim** [comment]
This is already documented under another issue. Please at least specify what hardsuit is affected by this so it can be added to the pile.

**Comment by AnCopper** [comment]
> This is already documented under another issue. Please at least specify what hardsuit is affected by this so it can be added to the pile.

Seemingly all of them, I've seen it happen on deathsquad and atmos hardsuits.
