### ISSUE TITLE
Add two more dialog questions for an admin who starts battleroyal

### ISSUE THREAD

**Issue by pro100Player** [BeeStation/BeeStation-Hornet#6240]
1) Sometimes admins may press it out of curiosity, make it so they have a choice to not begin it, because it once happened in the middle of the normal round.

2) Make poddrops togglable, so battleroyal may go somewhat less chaotic because all of the loot which falls onto the heads, so people might use common weapons or break into places for better stuff.

**Comment by PowerfulBacon** [comment]
theres a popup in full capital letters saying "ARE YOU SURE YOU ARE SURE YOU WANT TO START BATTLE ROYALE?" when you press the button.
