### ISSUE TITLE
Infinite un-interactable bluespace bodybags.

### ISSUE THREAD

**Issue by Daridine** [BeeStation/BeeStation-Hornet#6243]
## Reproduction: 
Spawn a bluespace bodybag
Have someone zip you in it
Now you can click on the bag and pick it up, while in the bag.
use bag in hand to infinately spawn bluespace body bags
Spawned bags can't be interacted with or deleted, except by clicking them with the "Picked up" bag?

**Comment by DatBoiTim** [comment]
Fun fact, the body bags are not entirely uninteractable.

You can pull them. And then they behave as normal(sorta).

From there they enter this weird quantum bullshit I'm not getting into(because I don't understand and it scares me)
