### ISSUE TITLE
The light grey text of the medical radio channel is extraordinarily harder to read against the white background. Is it possible to recolor it?

### ISSUE THREAD

**Issue by shivvyshubby** [BeeStation/BeeStation-Hornet#625]
Title says it all. Light grey text on a white background is hard to read quickly. Recoloring it would be make it much more helpful.

**Comment by St0rmC4st3r** [comment]
Also maybe something with the service channel, which is rarely used because of colour confusion with common.

**Comment by TheGreyDiamond** [comment]
Just added a pull request: #1520 Should fix it
