### ISSUE TITLE
"Failed to load the script 'tgui-common.bundle.js' after 5 attempts.    at node.onerror"

### ISSUE THREAD

**Issue by civilCornball** [BeeStation/BeeStation-Hornet#6264]
Issue reported from  Round ID: 35719 (BeeStation Sage - Roleplay)

Reporting client version: 514.1572

I just joined the server, and this happens?
![image](https://user-images.githubusercontent.com/48499004/151615313-0f32ab68-0df5-4354-8a8a-1ba55c33ea22.png)
I can't see chat.

**Comment by civilCornball** [comment]
updated to recommended byond version (514.1571).
worked until i tried to say something to deadchat.
![image](https://user-images.githubusercontent.com/48499004/151615895-8b7c29ae-fecd-43e5-86ae-3249e504f646.png)

**Comment by Crossedfall** [comment]
Try clearing your BYOND cache and reconnecting.

1. Click on the cog at the top right of BYOND
2. Select Preferences
3.  Go to Games
4. Click Clear Cache
5. Click OK

**Comment by civilCornball** [comment]
already did that
![image](https://user-images.githubusercontent.com/48499004/151616222-1713773c-11f9-4e72-aa9b-f3fb16292a9a.png)
![image](https://user-images.githubusercontent.com/48499004/151616295-ed585c30-238a-4301-8a11-5d90a60a518e.png)

**Comment by Crossedfall** [comment]
Clear your IE cache/cookies.

1. Close all of BYOND (check your task manager to ensure that BYOND and all Dream* processes are totally closed out)
1. Open `Internet Options` from the start menu
2. Under "Browsing history" click `Delete...`
3. Check everything and confirm

**Comment by civilCornball** [comment]
going to uninstall & reinstall byond
it keeps thinking there's another open copy of itself when I try to clear cache
and i have to go to task manager to clear it

also that afterwards

**Comment by civilCornball** [comment]
did the earlier instructions.
still crashing.
![image](https://user-images.githubusercontent.com/48499004/151617563-713bc9b4-03a0-48b3-a107-efb3f0ab22bf.png)

**Comment by civilCornball** [comment]
it seems to be opening multiple copies of Dream Seeker

is that normal?

**Comment by ike709** [comment]
Is it just the stat panel or every TGUI?

**Comment by civilCornball** [comment]
it's the right side of the screen. i'll check with the ghost menu


i was able to choose to Observe the game

**Comment by ike709** [comment]
Go open like a vending machine UI or APC UI or air alarm UI and see if any of those work or if they're broken.

**Comment by civilCornball** [comment]
it takes a few seconds to crash, and it's functional during that time. I can use the Orbit menu to orbit someone, for instance.

note that the fatal exception occurs at the SAME EXACT PLACE every time. 002B:C562F1B7 in TGUI.

Jump to Mob doesn't seem to fail
Orbit crashes.
I'm Observing, so I don't have a corpse to reenter.
Teleport doesn't seem to fail either. (why is it named BOOYEA?)
pAI Candidate... nope, not failing.

Language Menu... Crashed.

Vending machine... Goodbye.

**Comment by civilCornball** [comment]
checking shuttle console... yep, goodbye

note that I can still cause https://github.com/BeeStation/BeeStation-Hornet/issues/6167

**Comment by civilCornball** [comment]
the "cult victory" animation played out in its entirety

and the RoundEnd Report does not crash.

**Comment by civilCornball** [comment]
checking... currently have only 1 dream seeker

**Comment by civilCornball** [comment]
send issue to tgstation devs?

**Comment by civilCornball** [comment]
fixed as of server restart
