### ISSUE TITLE
Chat glitch

### ISSUE THREAD

**Issue by Jacobthegamer070** [BeeStation/BeeStation-Hornet#6265]
When i join the Acacia server, my chat after like 10 seconds crashes, I dont know if its my Byond client or something else
![Screenshot 2022-01-28 152549](https://user-images.githubusercontent.com/97812099/151623637-0f3cb9bf-115a-4dac-bbd8-c3bfa45b59ac.png)
.

**Comment by Dejaku51** [comment]
i think we got oh god oh fuck moment with TGUI, try using "fix-chat" verb

**Comment by ike709** [comment]
Should be fixed, make a new issue if it's still broken.
