### ISSUE TITLE
Code Bounty: Beecoin Shop

### ISSUE THREAD

**Issue by AsciiSquid** [BeeStation/BeeStation-Hornet#627]
## Wanted: A place to spend my Beecoin collection.
Implement a functioning Beecoin shop which can be used to spend Beecoins on additional character slots and cosmetic items/features to be used from the character creator. Not expecting any specific cosmetics added, just the framework to put items in for future development and a few examples for testing. As such the easier it is to code new stuff into the shop the better.
### Required Feature Checklist
All these features **must** be included to accept the bounty.
- [x] A beecoin shop menu accessible from the OOC tab or character preferences menu
- [x] Option to access and equip cosmetic items from the character creator
- [x] Features/support for job-restricted cosmetics
- [x] Additional character slots, that are locked until purchased individually from the beecoin shop.
### Optional Feature Checklist
These features are not required, but I'll tip extra if they're done well.
- [x] Support for equipping cosmetics based on body region (Hat slot, jumpsuit slot, ect)
- [ ] Preview cosmetic options from the character creator before purchasing
- [x] Make the shop menu look nice / easy to navigate for players
- [x] Make the shop code easy to maintain / further develop
- [ ] Adding items you think are cool
Items currently fulfilled by #645 , bounty will be closed once the PR is accepted.

**Comment by Crossedfall** [comment]
The above bounty is being paid for by Ascii. Those that want to try and claim the bounty should submit a PR referencing this issue. It should meet the conditions above. Questions can be asked here.

**Comment by AsciiSquid** [comment]
By the way, I'm willing to go as far as to double the reward for those extra features.

**Comment by Kerbin-Fiber** [comment]
Time to not donate to BYOND for 8 character slots

**Comment by ike709** [comment]
Dibs.

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/645
