### ISSUE TITLE
Game instantly crashing on load

### ISSUE THREAD

**Issue by pirate1337** [BeeStation/BeeStation-Hornet#6283]
My game has been crashing on boot for the past couple days. First it'll load up like normal, then about 3 seconds later on the main menu it will close then reopen to a blank window seen in the image below.
![image](https://user-images.githubusercontent.com/52904784/151923035-49d4f763-f80b-4064-a4b3-846304996509.png)

I've tried clearing IE cache, BYOND cache, installing older versions of BYOND, trying it out on my laptop yet the issue still persists.

**Comment by Mantlecrawler** [comment]
This is because of the panic bunker. Ask a admeme in the discord
