### ISSUE TITLE
Several station mounted radios can be tuned into every single frequency.

### ISSUE THREAD

**Issue by AnCopper** [BeeStation/BeeStation-Hornet#6286]
Wall mounted radio in the box-station tcomms control room
"Custom" wall-mounted radio in the Pubby AI core.

There are undoubtedly more.

**Comment by Fresh839** [comment]
I can confirm this we just had an AI turn into the CTF blue team radio channel. Round ID 35827.

**Comment by imsynthex** [comment]
I think all intercoms with the tag "(command)" can through every frequency

Nevermind, these are all intercoms with the "freerange" variable set to true
![image](https://user-images.githubusercontent.com/81387903/152191946-570e72f4-a450-44ee-b2a0-f9cf0a2c91e8.png)
