### ISSUE TITLE
Code Bounty: Clown Cult

### ISSUE THREAD

**Issue by honkhonkclown** [BeeStation/BeeStation-Hornet#629]
A Clown themed Blood Cult variant in the same style as clown ops vs. nuke ops. 
Reward of $60 USD for the gamemode with optional additions and $40 for just the reskinned and tweaked Blood Cult

Normal cult weapons will be replaced with Clown variants made of bananium (Optionally, they can be given different stats and balance for the $60 bounty or they can simply be reskins of the cult items. e.g Cult Sword becomes Bananium Sword which slips on hit but does less damage similar to the Clown Ops bananium esword.)
Normal cult stun becomes an equally long slip that filters speech to honks instead of muting the victim
Conversion works largely the same, with cult dagger being replaced by the chaplain's honk dagger skin but functioning identically. 
Rather than holy water to deconvert, the Mime's bottle of nothing is used and the Chap can be converted by the Clown Cultists
Endgame victory condition summons a Nar'Sie reskin which will respawn anyone who clicks on it as a clown rather than a harvester and converts to bananium rather than cult floors and walls. (Possibly reuse code from clown bomb/nuke ops bananium fission nuke?)
Runes all function largely the same except for the constructs and sacrifice runes which instead return Cult variant H.O.N.K mech parts or weapons after enough sacrifices (Not 1 sac = 1 mech as that would be broken as fuck but rather make them acquire a single honk mech through several sacrifices.) 
Cult H.O.N.Ks would be slightly more durable and their version of the Oingo Boingo Punch Face would do brute damage in addition to the standard knockback and stun/airlock removal

**Comment by honkhonkclown** [comment]
These requirements aren't absolute and I am willing to talk on discord about flexible requirements and bounty amount if something I mentioned isn't a practical idea or presents balance issues

**Comment by Crossedfall** [comment]
@honkhonkclown Can you please add an itemized list of your requirements (A task/checklist would be preferable)? That'll help developers better understand what you're after and can use it as a checklist before submitting their PR.

**Comment by honkhonkclown** [comment]
Reskin all basic cult gear / weapons (Robes, weapons, items etc)

Rework Nar'Sie to be Honkmother/Honk'Sie (Spawns clowns/turns people into clowns like the clown ops bananium nuke)

Make Mime's Bottle Of Nothing/the reagent Nothing replace Holy Water, works the same way

Rework sacrifice system from soulshards to either bananium golems or H.O.N.K mech parts 

Cult H.O.N.K mech variant - Greater damage resist and buffed H.O.N.K weapons (Mousetrap mortar into cult conversion trap similar to clockies with a much larger cooldown than the normal mortar? Honkerblast would work similar to flashbangs with both glasses and a bowmans headset/muffs needed to protect, oingo boingo punch would now do actual brute damage)

Replace cult spells with honked versions in cases where it doesn't work (Twisted Construction no longer does runed metal, now does bananium. Summon Equipment now summons the clown versions of the equipment such as the ritual dagger becoming the Chaplain's clown dagger with the added cult rune function.)

Spells such as stun and teleport can remain the same 

Blood rites/blood absorb spell would be changed to work through slipping people similar to how the clown PDA can recharge its virus ability through slips.  The magic abilities would be replaced with existing clown ones, such as the animal mask spell, the lava ruin honkmother's staff effect, and maybe a lube AOE?

Cult lines said when doing cult actions are changed from Nar'Sie speak to clown speak (honk,henk,hjonk,we live in a society, e.g common clown sayings/memes)

**Comment by honkhonkclown** [comment]
These are the basic checklist for making this a functional rework that actually makes sense. I will use these when checking a PR to see if it meets the requirements of the bounty. Anything not specified is to remain the same as in the regular Blood Cult mode. If you are unsure about anything, contact me on Discord at Clown#7307

**Comment by honkhonkclown** [comment]
hit the wrong button by mistake bruh moment

**Comment by Kerbin-Fiber** [comment]
I'll start working on this so I can learn more about how BYOND works and how new gamemodes/config setting are made, but I *cannot* guarantee that I can or will finish it.

**Comment by CthulhuOnIce** [comment]
@honkhonkclown is this still up for grabs?

**Comment by Crossedfall** [comment]
~~@Kerbin-Fiber @CthulhuOnIce are either of you actively working on this? I'd like to get it assigned to make it clearer that someone is working on it.~~

**Comment by Crossedfall** [comment]
Update from discord: 

Kerbin has stopped working on this request. Another user is currently working on the bounty, waiting for them to update this issue so that I can assign it accordingly.

**Comment by nauticalfellow** [comment]
Hello! I'm currently working on this. I'm done most of the spritework, just ironing out the relevant code bits now.

**Comment by johanlives** [comment]
> Hello! I'm currently working on this. I'm done most of the spritework, just ironing out the relevant code bits now.

Hi @nauticalfellow 
I am from Bountysource support.   

**Bounty withdrawal request**
We have received a request to withdraw the bounty posted on this issue.   However, it is our policy not to withdraw funding from issues in active development without the consent of the developer.   

**Intention to claim/consent to refund** 
Would you kindly advise me if it is your intention to make a claim for this bounty?   If it is not your intention and your PR is independent of the bounty incentive, would you please consent to me refunding the bounty.

_Note: In the event of an eventual claim dispute, Bountysource reserves the right to arbitrate the dispute and force award the bounty to either party based on fair judgement & consideration._

I apologise for the inconvenience.

Thanks & regards

Johan

**Comment by nauticalfellow** [comment]
Hi @johanlives, I'm still working on this issue and planning to submit a claim

**Comment by nauticalfellow** [comment]
Hi just as a quick update I'm still on this! Corona has slightly messed up things but I'm not too far from being done.

**Comment by TeomanTheGreat** [comment]
Remember when this was a thing?

**Comment by eeSPee** [comment]
Bounty still available?

**Comment by BrumalLake** [comment]
Soon.

**Comment by TeomanTheGreat** [comment]
😳

**Comment by AnCopper** [comment]
Do you still accept this bounty?

**Comment by TeomanTheGreat** [comment]
> 
> 
> Do you still accept this bounty?

its been ages I think the answer would be no. also honkhonkclown was banned a long while ago I think

**Comment by PowerfulBacon** [comment]
Closing since author was banned.
