### ISSUE TITLE
Floor bot Delta Station

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#6307]
![damit](https://user-images.githubusercontent.com/72167130/152617005-50b8ac87-c317-4bfd-964d-4f262458d773.png)
Floor bots in patrol stay rolling up and down in engineering halfway in Delta Station. This doesn't happen with other bots, Is very confusing

**Comment by Chessus** [comment]
Odd, Is this recreatable on a private server? I'd guess it was the nav beacon under the tiles but if it's only the floorbots then it the issue must be them.
