### ISSUE TITLE
Set of Hotkey Problems

### ISSUE THREAD

**Issue by NormalAnomaly** [BeeStation/BeeStation-Hornet#6308]
Issue reported from  Round ID: 35882 (BeeStation Sage - Roleplay)

Reporting client version: 514.1572

Bug Name: Hotkey Alt to Toggle Walk Not Working Correctly/Not Working with Mechs Correctly/Ctrl to block movement not unbinding correctly. 

Descriptions: These have been observed for about a week or two.  Took me a while to remember/ask about the correct bug reporting channels.

Regarding ALT to Toggle walk: It does so, however it also blocks movement and turning from happening via the WASD movement keys or even clicking to change facing.  Given the need to walk to block correctly and the need of dynamic movement, it greatly cuts down on a players combat ability in addition to general utility.  If one is moving using WASD before pressing the ALT key first it does function to temporarily toggle run>walk or walk>run but they will be at a dead stop if they continue holding ALT and stop moving.  This problem persists even if the bind is changed off of ALT.

The behavior is instead correct if using alt to toggle movement and using the arrow keys.

Steps to reproduce:
1. Hold ALT
2. Press W, A, S, or D

Expected Outcome: Free movement as normal, just at the altered movement pace.

Regarding ALT not working with mechs correctly: Holding alt on a mech should temporarily toggle facing changing or strafing mode.  Like the prior issue, using the arrow keys instead of WASD produces the expected result.  Also like the prior issue, moving first seems to partially overcome the problem.  For instance, turning it to strafing mode, getting moving and then pressing alt will permit a facing change in the direction moved but also stops WASD movement and facing changes should you be stationary or come to a stop.

Steps to reproduce:
1. Get in a powered mech
2. Hold ALT
2. Press W, A, S, or D

Expected Outcome: Assuming strafing is on, holding ALT and pressing W, A, S, or D should result in facing changes.   In any case, ALT should not prevent movement.

Regarding CTRL to block movement not unbinding correctly: CTRL is used to stop movement to allow a player to stand in place and change facing using WASD.  Even unbound CTRL retains this function.  Rebinding it to another key makes the new key block movement too, but does not permit turning with WASD or arrow keys.  Finally, even unbound CTRL does not permit turning with the 
arrow keys.

If you need any further details I'm on the discord, and I'll try to check back here

**Comment by PowerfulBacon** [comment]
Multiple issues here, one of which being ctrl, shift and alt are allowed to be bound to toggle walk but will completely screw with your game if bound to them keys due to hardcoded click stuff

**Comment by NormalAnomaly** [comment]
I took a break for like a month or more so the change/issues here were pretty jarring.  I'm comparing to the time I took the break in which none of these issues were present.  I can't speak for the CTRL though because till this came up it never hit me to rebind the CTRL stop movement function to anything else.
