### ISSUE TITLE
Code Bounty: Banana Mutation

### ISSUE THREAD

**Issue by dbford** [BeeStation/BeeStation-Hornet#631]
Scrambling DNA at the monkey mutation machine should have a chance of turning of the subject into a banana. Humans share 50% of their DNA with bananas, so this should be possible.

https://www.bountysource.com/issues/82593668-code-bounty-banana-mutation

**Comment by despong** [comment]
everyone gangster until banana players start erping and take their skin off (FUCK)

**Comment by ike709** [comment]
What do you mean by turning them into a banana? Kill the player and spawn in a banana item? Make a talking banana like the cursed sword? Make a species of banana-human hybrids?

**Comment by Kerbin-Fiber** [comment]
Time to just make a subtype of stickmen but make it 
![image](https://user-images.githubusercontent.com/31713423/67841510-e0df3c00-fabd-11e9-88c4-efe8bdf2961e.png)

and force the person into it

**Comment by dbford** [comment]
> What do you mean by turning them into a banana? Kill the player and spawn in a banana item? Make a talking banana like the cursed sword? Make a species of banana-human hybrids?

Any or all of the above

**Comment by ike709** [comment]
Alright.

**Comment by ike709** [comment]
@danielbradford Please go on bountysource and approve the claim so I don't have to wait two weeks to receive the money.
