### ISSUE TITLE
Suit burn to ashes while wearing CE suit

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#6310]
Issue reported from  Round ID: 35892 (BeeStation Sage - Roleplay)

Reporting client version: 514.1575

I was wearing the CE suit when the AI plasmafire me, I was wearing it closes with the helmet and my suit burn to ashes. I was not taking burning damage, but my suit burn to ashes.

**Comment by Pirill** [comment]
Same issue seems to happen with all exosuits. A miner's jumpsuit will eagerly burn through the explorer suit if fighting a drake for instance.
Seems related to #6158 and a number of other reported issues.

**Comment by BrumalLake** [comment]
i'm pretty sure those miner suits don't protect anything under anyways
