### ISSUE TITLE
Metal disappears.

### ISSUE THREAD

**Issue by pro100Player** [BeeStation/BeeStation-Hornet#6318]
ok

## Round ID:

Irrelevant.

## Testmerges:

I am pretty sure they are not a problem.

## Reproduction:

1) Place a microwave on a table frame either by finishing construction or pulling (and securing) it with a wrench.
2) Click a table frame with an iron sheet.
3) You get chat log "The microwave oven is in the way." and one of the metal sheets is gone if it is a stack or if you clicked with a single metal sheet it just disappears.

Place a microwave oven on a table frame. Try to assemble a table by adding a metal sheet to frame. Boom, metal sheet is gone, "the microwave oven is in the way."

**Comment by DatBoiTim** [comment]
Can you please redo this report with proper format and a bit more info on replication?
