### ISSUE TITLE
Chair's gone

### ISSUE THREAD

**Issue by pro100Player** [BeeStation/BeeStation-Hornet#6319]
fine

## Round ID: 
Irrelevant

## Testmerges:

I am 99.99% sure that it was not caused by any testmerges.

## Reproduction:

1) Grab any chair which is made of 1 iron sheet;
2) Robust somebody/something with it. Even floor works. (Yes, if you click floor on harm intent it may get smashed);
3) 5% that the chair will be completely gone.

When you smash a chair it gets smashed into nothing instead of two metal rods like on tg. Port it maybe?

**Comment by DatBoiTim** [comment]
Can you please redo this report with proper format and a bit more info on replication?
