### ISSUE TITLE
Code Bounty: Will Smith Mutation

### ISSUE THREAD

**Issue by dbford** [BeeStation/BeeStation-Hornet#632]
Scrambling DNA at the monkey mutation machine should have a chance of turning of the subject into a Will Smith. Humans share 50% of their DNA with Will Smith, so this should be possible.

Super powers include: increased twitter followers
https://www.bountysource.com/issues/82593794-code-bounty-will-smith-mutation

**Comment by dbford** [comment]
See this picture for reference: https://www.indiewire.com/wp-content/uploads/2019/02/Screen-Shot-2019-02-11-at-8.52.02-AM.png?w=780

**Comment by Kerbin-Fiber** [comment]
Might as well do it for the meme

Although to get it accepted, it might need a pretty low chance to happen, or to have it only happen when the occupant's rad levels are pretty high

**Comment by qwertyquerty** [comment]
dumb.
