### ISSUE TITLE
Jellypeople/oozeling limb conversion

### ISSUE THREAD

**Issue by Tsar-Salat** [BeeStation/BeeStation-Hornet#6328]
Round ID: Nonspecific

For some reason, jellypeople will convert limbs into their race specific ones, even after implementation of kapulimbs.
Reproduction: 
Take a slimeperson/oozeling patient.

Reduce their blood plasma to around 270 where they are in noncritical condition but their limbs have all receded.

Surgically attach a unrelated species limb to one if the stumps. The unrelated limb will instantly be converted into  a slime limb and then receded into the body. 

While converting organic matter into a slime form makes sense, it will also convert non-organic limbs, which doesn't make any sense.

I will test with augments when I get a chance

**Comment by zeskorion** [comment]
> Round ID: Nonspecific
> 
> For some reason, jellypeople will convert limbs into their race specific ones, even after implementation of kapulimbs. Reproduction: Take a slimeperson/oozeling patient.
> 
> Reduce their blood plasma to around 270 where they are in noncritical condition but their limbs have all receded.
> 
> Surgically attach a unrelated species limb to one if the stumps. The unrelated limb will instantly be converted into a slime limb and then receded into the body.
> 
> While converting organic matter into a slime form makes sense, it will also convert non-organic limbs, which doesn't make any sense.
> 
> I will test with augments when I get a chance

were the limbs damaged? did they have enough blood to have limbs?

**Comment by Tsar-Salat** [comment]
> did they have enough blood to have limbs?


> Reduce their blood plasma to around 270 where they are in noncritical condition but their limbs have all receded.

**Comment by Tsar-Salat** [comment]
completed? not really but aight
