### ISSUE TITLE
Cross-server communication no longer works

### ISSUE THREAD

**Issue by Crossedfall** [BeeStation/BeeStation-Hornet#6334]
## Reproduction:

1. Configure cross-comms and the relating API tokens in the comms.txt file
2. Attempt to send a message to allied stations
3. 😔

**Comment by williamcll** [comment]
Confirmed, it also used to allow players from NSV to make calls to Bee as well.

**Comment by Crossedfall** [comment]
> Confirmed, it also used to allow players from NSV to make calls to Bee as well.

NSV is unrelated. That stopped because they weren't using the new topic API. They recently got back up to date but we haven't swapped updated keys.
