### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by LinusMatysiak** [BeeStation/BeeStation-Hornet#6336]
tittle

**Comment by pro100Player** [comment]
Bruv, space cleaner uses... SPACE CLEANER chem, you need to ask a chemist for refill.

**Comment by mcmeiler** [comment]
> i mean if i can replenish space cleaner with water tank then why cant i do it with my janitor cart?

Alright. First off, space cleaner uses Space Cleaner reagent to clean, not Water reagent, so there's no real reason to fill a spray bottle with water.

Secondly, the janicart is an input-only container, the only way to use up the reagents inside is to use a mop on it. It wasn't intended as a space cleaner storage for your spray.

If you REALLY need that much space cleaner, you start with a backpack cleaner tank anyway.
