### ISSUE TITLE
Can't wear clothes casually

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#6339]
## Testmerges:
#5755: 'Updates Kilo Station and re-adds it to rotation' by dog132-ss13 at commit f127ef2efe
#5774: 'Cryopods use signals to handle objectives and other objective improvements' by TheChaser212 at commit 51926d39d8
#6254: 'Ports MC deletion recovery' by ike709 at commit 4d72f64365

## Reproduction:
Just can't change to wear clothes casually.

**Comment by Archanial** [comment]
What do you mean "cant't"? 
Which clothes and what happens?

**Comment by JukeJukestar** [comment]
The chat message to wear suit casually still appears, but there is no visual change. As far as I can tell this is the case with all suits
(tested with grey jumpsuit, lawyer suit, chap jumpsuit and cargotech suit)

**Comment by Archanial** [comment]
In the future please try writting more detailed issue reports, would save me some time.

**Comment by yurara** [comment]
Oh, sorry. I thought that was simple enough, not lack of detail.
