### ISSUE TITLE
Losing quirks if cloning with only head/brain

### ISSUE THREAD

**Issue by pro100Player** [BeeStation/BeeStation-Hornet#6342]
## Round ID:
Irrelevant

## Testmerges:
I ain't sure they are the problem

## Reproduction:

1) Get someone's head separated from a body;
2) Put it into a cloning machine;
3) Clone;
4) All quirks are gone.

Same happens if you get monkified (and demonkified)

**Comment by EvilDragonfiend** [comment]
This is actually because of the structure of the quirks code, not because of the clone code. Yeah, your quirks are stored in your body, not your brain, that's it. This is a likely unfixable issue until we rework the quirks code.
