### ISSUE TITLE
AtmosBot UI errors.

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#6347]
## Reproduction: 
As AI I interfaced with an atmosbot and the UI looked like this.
![unknown 1](https://user-images.githubusercontent.com/43061493/153379777-e6bb1ba5-448c-4941-9522-3b28acf28e71.png)
Note that the temperature indicator is also wrong since it's showing degrees rather than kelvins.

**Comment by Tsar-Salat** [comment]
Probable issue from #6282 
@KubeRoot  

Can confirm this appeared on all atmosbot displays for me too in the past week.

**Comment by KubeRoot** [comment]
> Probable issue from #6282

My PR only touched the `explode` proc, should be unrelated. That said, I also don't know when this might've broken, might look into it later.

**Comment by Crossedfall** [comment]
Solved by #6511
