### ISSUE TITLE
Bugged reinforced floors

### ISSUE THREAD

**Issue by Mat05usz** [BeeStation/BeeStation-Hornet#635]
Issue reported from  Round ID: 8382 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 512.1488

So I noticed a bug with reinforced floors, that if you only remove one and use the sheet of iron you get, it doesn't disappear after the floor is made, giving a possibility to spawn iron sheets infinite times. The other thing i noticed is I deconstructed 6 reinforced floors, took all the 6 sheets, and when i was placing them in a 'queue' so there were 6 being placed at one moment, only 3 actually did end up on the floor while 6 sheets disappearing.

**Comment by MarkSuckerberg** [comment]
Already fixing them
