### ISSUE TITLE
Experimonitor too far away from R&D console on Boxstation 

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#6354]
## Reproduction:
Currently, the experimonitor cannot synchronize because the nearest R&D console is too far away, so you can put strange items in it.
[[https://cdn.discordapp.com/attachments/605179594617782302/941515546397130802/unknown.png]]

**Comment by Alpkant** [comment]
I have also seen this in Kilostation too. I don't know if it is fixed on Kilo.

**Comment by williamcll** [comment]
Think this was fixed.
