### ISSUE TITLE
Plasma canisters look like N2 canisters

### ISSUE THREAD

**Issue by The-Moon-Itself** [BeeStation/BeeStation-Hornet#6355]
## Round ID:
36024

## Testmerges:
MC recovery and Kilo changes

## Reproduction:
Label a canister as a plasma canister, note that it is the same color as nitrogen canisters:
![plasma and nitrogen cans](https://user-images.githubusercontent.com/51838176/153534862-d1e4fc6e-a6b0-4b9b-a5dd-8dcd99c991b3.PNG)
(Nitrogen canisters on top, plasma canister between the trit can and pump)

**Comment by BrumalLake** [comment]
one is red and one is orange with hazard stripes
the slight color shifts from gags look fine to me

**Comment by The-Moon-Itself** [comment]
Huh, I didn't notice the hazard signs, but its definitely the same color, or, atleast very close to the same color. I could have swarn plasma cans used to be a lot more orange.

**Comment by KubeRoot** [comment]
I believe plasma cans were always very similar to nitrogen, but I think they had a P marking that was knowingly removed in GAGS.

**Comment by Archanial** [comment]
They're not the same color and if anything changing the color is just changing gags color in canister.dm

**Comment by ike709** [comment]
Them not being the same color doesn't mean they don't look basically identical.

**Comment by KubeRoot** [comment]
> doesn't mean they don't look basically identical.

While I'm inclined to agree, I do want to remind you there are also warning stripes. I think the current difference might be very much enough, just something people need to get used to.

**Comment by MNarath1** [comment]
How about adding the warning strip as an overlayer that stays with a consistant color? So you actually can see it right now its almost invisible ontop of the canister looking pretty much identical to n2

**Comment by Archanial** [comment]
It's not invisible, making the canister brighter might solve the issue.
