### ISSUE TITLE
Status panel doesn't update while in lobby

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#6363]
bruh moment

**Comment by ike709** [comment]
Before or after the pregame lobby? Or both?

**Comment by ike709** [comment]
I would assume this is a side effect of an optimization to reduce unnecessary TGUI updates during pregame, but it should still be fixed to update at the slow rate for people still in lobby post-roundstart.

**Comment by Archanial** [comment]
Tested in pre game lobby but I suspect it's the same after round starts

**Comment by PowerfulBacon** [comment]
Status panel cannot automatically update until TGUI subsystem it loaded.
