### ISSUE TITLE
Disposal pipe sprites are not appearing

### ISSUE THREAD

**Issue by EAFChunk** [BeeStation/BeeStation-Hornet#6368]
Issue reported from  Round ID: 36071 (BeeStation Sage - Roleplay)

Reporting client version: 514.1572

Some disposal pipes got busted from an explosion. While trying to repair them, the RPD would make the noise indicating it placed a new one down, but nothing appeared. Follow on attempts to place another disposal pipe gave the message "there's not enough room to build that here."
I tried creating a new path for disposals to follow, but the same issue came up.
![SS13 Bug](https://user-images.githubusercontent.com/99569856/153736009-939fe708-2a3d-4799-838b-410402200937.PNG)

**Comment by Archanial** [comment]
Most likely broken by ike
