### ISSUE TITLE
Traitor goal of Dying, and escaping at the same time

### ISSUE THREAD

**Issue by XeonMations** [BeeStation/BeeStation-Hornet#6377]
Issue reported from  Round ID: 36100 (BeeStation Sage - Roleplay)

Reporting client version: 514.1575

As a traitor, if you become a heartbreaker (i believe), you can get an additional goal. This has the chance to add the goal "Die a glorious death", when you already have "Escape on the shuttle or an escape pod alive and without being in custody"

**Comment by AnCopper** [comment]
Schrödingers traitor.
