### ISSUE TITLE
Kilo: Atmos tanks are not configured with proper vents.

### ISSUE THREAD

**Issue by SergeiKoralev** [BeeStation/BeeStation-Hornet#6382]
Issue reported from  Round ID: 36139 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1575

the atmos tank controllers are useless without the appropriately linked vents, and those are not used.

**Comment by dog132-ss13** [comment]
I took a look at this and the injectors, vents and sensors look appropriately linked. Could you please explain this more in-depth for me? I am bad at atmospherics.

**Comment by SergeiKoralev** [comment]
I just checked and had the same finding in the map. I'll re-verify the bug. The primary symptom is this...

If you shut off the output vent and then turn the pump below the mixer to max, mixer node 2 to 100% and turn it all on it should drain the pipe, but in this instance it did not.

**Comment by SergeiKoralev** [comment]
Huh, unable to duplicate on local. Must be a one time.
