### ISSUE TITLE
Abductor Telepathy not working

### ISSUE THREAD

**Issue by Tyranicranger4** [BeeStation/BeeStation-Hornet#6390]
## Round ID:
36175 (Sage)

## Testmerges:
#6316 
#6380

## Reproduction:
Spawn in as an abductor and then type in chat until the telepathy breaks and you start speaking normally. Seems to happen to natural spawns and admin spawns. The issue wasn't present at the same time on Acacia so I'd assume it's probably from one of the TMs, but what do I know I'm not a coder.

**Comment by Crossedfall** [comment]
Unlikely to be a tgui related issue, so bets are on the speech subsystem changes.

**Comment by Tyranicranger4** [comment]
No longer an issue from what I can see.
