### ISSUE TITLE
Mechs can not turn in strafe mode with alt anymore

### ISSUE THREAD

**Issue by Megaddd** [BeeStation/BeeStation-Hornet#6397]
## Round ID:
N/A

## Testmerges:
N/A

## Reproduction:
Attempt to turn in a mech with holding alt + direction key whilst in strafe mode

**Comment by Megaddd** [comment]
This is likely as a result of the new hotkeys registering as Alt + W = new hotkey

**Comment by ivanmixo** [comment]
try ctrl

**Comment by NormalAnomaly** [comment]
Throwing it out there, this has been going for some time.  I offer the issue I opened for what workarounds I saw.  You can't rebind the mech strafe thing, thats a set function of mechs not related to the remappable hotkeys.

[https://github.com/BeeStation/BeeStation-Hornet/issues/6308](https://github.com/BeeStation/BeeStation-Hornet/issues/6308)

Hotkeys in general have some jank right now.
