### ISSUE TITLE
Split Personality Slimepeople should each gain their own body upon first splitting

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#6398]
When a slimeperson duplicates, it would be cool if it checked for a split personality disorder, in which case the trauma would be removed and the secondary personality got the new body. (They would not share a bodypool)

**Comment by kit-katz** [comment]
im sure giving xenobio even more ways to make slaves is a great idea

**Comment by Tsar-Salat** [comment]
This is interesting.

Brain traumas such as split are specific to *that* brain. If the host transfers their brain to another body, the split should thereotically stay in the og.

Hmmm, needs testing

**Comment by JukeJukestar** [comment]
Dont think anyone is gonna pick up on it, and I guess that guy is right - slimepeople are already very powerful
