### ISSUE TITLE
Emote runechat is broken

### ISSUE THREAD

**Issue by Tyranicranger4** [BeeStation/BeeStation-Hornet#6406]
## Round ID:

Discovered on round 36265 (Sage), although I doubt this matters for this one.
## Testmerges:

N/A
## Reproduction:
Use an emote, watch as the runechat displays "makes a strange sound" no matter what you emoted.
Only effects the overhead chat, normal chat displays it as usual.
![image](https://user-images.githubusercontent.com/80382633/155120737-1c008b05-92d5-4117-ab23-07a9318a10b7.png)
![image](https://user-images.githubusercontent.com/80382633/155120803-df84ee6e-4b52-427e-9065-d417da7d15f1.png)

**Comment by ryanmunz** [comment]
+1 This happens with both custom *me says and regular emotes like *laughs. 

This started in the round immediately after the "remove debtor" PR was merged (I was mime so it was very obvious).

**Comment by PowerfulBacon** [comment]
blame me

**Comment by ike709** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/6413
