### ISSUE TITLE
nanites wearing off? [edit]

### ISSUE THREAD

**Issue by bepisman-now-only-fizz** [BeeStation/BeeStation-Hornet#641]
Issue reported from  Round ID: 8430 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1492

it looks like after a specific amount of time or after laying down (i need to look into it a bit more) nanites just disappear from your bloodstream. is this a bug or a balance feature? it already takes quite a while to get the more advanced nanites, the time it takes PLUS the resource management means that they are not very useful or fun. [ EDIT] it looks like when the shuttle leaves the station, it completely removes the nanites from your bloodstream. the nanites may be getting deleted when they change z axis? if not on the shuttle nanites remain.[EDIT 2 ELECTRIC BOOGALOO] so it's definitely not changing z-axis as going to lavaland does nothing to nanites, i don't know what is going on in the shuttle but its destroying nanites. it might be a side effect of disabling comms, although going on an escape pod does NOT disable nanites.

**Comment by yorii** [comment]
This might have been fixed? I can't seem to reproduce it at all right now.
