### ISSUE TITLE
Microwave never stops microwaving

### ISSUE THREAD

**Issue by Tiger-Brows** [BeeStation/BeeStation-Hornet#6412]
## Round ID:

36276, Sage 

## Reproduction:

Came to the kitchen for food and the Cook was complaining about one of his microwaves. He'd put something in it and turned it on, but it never stopped microwaving. I couldn't interact with it at all (can't screwdriver open, can't wrench loose, can't crowbar it to pieces), and it kept going even when the AI turned the power off and on again. I have no idea how to reproduce this bug, because I don't know what the chef put in the microwave, but my character was Ashley Amaranth if looking through the logs helps you find the cause. Looking for "microwave" will probably help as well because we were shouting on radio about a magic microwave.

**Comment by DingleFlop** [comment]
Think I've seen this before. If the APC loses power temporarily while the microwave is running, it wont stop. It also wont finish, and because non-interactable. I don't think it ever finishes cooking once power is restored, either.

**Comment by Chessus** [comment]
Recreated in private server with latest updates.  OBS didn't capture it but the power/equipment was turned off and on again. 
Microwave can't be interacted with, you only can destroy it.
https://user-images.githubusercontent.com/10277607/155511332-8ee4aa5a-fd3a-448b-af37-45e0c7991630.mp4
