### ISSUE TITLE
Changeling Augmented Eyesight flash protection broke

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#6416]
## Reproduction:
Augment Eyesight randomly broke:
I cannot reproduce it locally however i checked the chat logs:
`<div class="ChatMessage"><span class="userdanger">[BORG NAME] blinds you with the flash!</span></div>
<div class="ChatMessage"><span class="game say"><span class="name centcom">[BORG NAME]</span> <span class="message">states, "<span class="robot ">Changeling.</span>"</span></span></div>
<div class="ChatMessage"><span class="userdanger">[Random Guy NAME] handcuffs you.</span></div>
<div class="ChatMessage">We adjust our eyes to sense prey through walls.</div>`
The borg definitly flashed me while i had augmented eyesight off as you can see here i try to toggle it directly afterwards out of confusion of what is going on.

**Comment by St0rmC4st3r** [comment]
Not a bug. The flash protection works when the xray is deactivated. So you either have flash protection or xray.

**Comment by MNarath1** [comment]
> 

If you look at the small chat entry i put up there you can see that i had my eyes on flash protect when they flashed me then i swapped to xray cause i am confused so it should have worked
