### ISSUE TITLE
Exploration map bugs

### ISSUE THREAD

**Issue by lucincus** [BeeStation/BeeStation-Hornet#6418]
So we went on a blackbox mission only to see doors disappear and not let us even shoot them and object spawners allover the place we cant interact with many objects

**Comment by PowerfulBacon** [comment]
I can't do much without the round ID unfortunately, I need the runtimes to see what is causing the map init to break since this is related to another issue.

**Comment by lucincus** [comment]
> So we went on a blackbox mission only to see doors disappear and not let us even shoot them and object spawners allover the place we cant interact with many objects

Me and a friend went onto the exploration shuttle and chose a mission, then we launched and went to the target destination and arrived at the station breaking a window to get in, then we explored the entire area except the vault (which was the bugged area) then we went to the vault and walked in. we had to break a couple walls because a couple doors disappeared.( when the problem started)

**Comment by williamcll** [comment]
Confirmed similar issue, while I don't have the round ID, the round was on March 10th 2022, 6:56AM GMT on Acacia
![dreamseeker_ZPlOnf463X](https://user-images.githubusercontent.com/43061493/157826642-75a1045b-323d-47c0-b07d-4352b5b495b2.png)
![dreamseeker_Czl9yk5u1U](https://user-images.githubusercontent.com/43061493/157826650-d9d09157-7b8c-4b83-82fb-e8e58c58300a.png)
![dreamseeker_lurpSqa8Mb](https://user-images.githubusercontent.com/43061493/157827382-8f198e36-9173-4c41-9d2a-12a80a7b8e8f.png)
