### ISSUE TITLE
Reproductive core spotty production

### ISSUE THREAD

**Issue by PsionTarrasque** [BeeStation/BeeStation-Hornet#6423]
Working on xenobiology and having issues with reproductive slime core occasionally failing to produce anything when fed.
And sometimes, it instead produces one Live slime of the appropriate color instead of cores.
Issue reported from  Round ID: 36308 (BeeStation Acacia - Roleplay 2)

Reporting client version: 514.1572

**Comment by BrumalLake** [comment]
#5989 but i don't know about what this implied consuming cube when on cooldown thing is

**Comment by DatBoiTim** [comment]
Producing a slime is intended.

It also has a 30 second cooldown, hence why it so rarely does the above.

**Comment by Archanial** [comment]
Intended now
