### ISSUE TITLE
Non-Advanced sunglasses can be crafted into Advanced sunglasses

### ISSUE THREAD

**Issue by Oscari-pog** [BeeStation/BeeStation-Hornet#6439]
## Testmerges:
The following pull requests are currently test merged:
[#6032: 'Cloning machine major fixes and changes' by EvilDragonfiend at commit 2b478a61f1](https://www.github.com/beestation/beestation-hornet/pull/6032)

## Reproduction:
1. Take non-advanced sunglasses, a sec/medhud, and the necessary tools.
2. Craft them into degraded sec/medhudglasses.
3. Craft the medhud out of the sunglasses.
4. You get advanced sunglasses.
5. Win.

**Comment by FriendlyContractor** [comment]
I could swear this was already fixed a while ago

**Comment by Jeff-3** [comment]
Seems like this is no longer the case. If you can reproduce it create a new issue with updated instructions, but otherwise this issue is already resolved
