### ISSUE TITLE
Flandstation Wiring Issues

### ISSUE THREAD

**Issue by Programs-The-Station** [BeeStation/BeeStation-Hornet#6442]
Issue reported from  Round ID: 36438 (BeeStation Sage - Roleplay)

Reporting client version: 514.1571

- [ ] Fland Tech Storage wire is curved and not a knot

![image](https://user-images.githubusercontent.com/100493881/156294247-8f71e056-eed7-4110-925e-0fd2a55ac06a.png)

- [ ] Security Cargo Office is Not wired at all

![image](https://user-images.githubusercontent.com/100493881/156296299-e077f433-93ba-4c38-9284-e57d2fe6d061.png)

- [ ] Central Maintenance APC is mislabeled I think. I would call it Central Bow maints. (And yes, this might be because I spent half the shift looking for this blasted APC to get it off my power alarms screen.)

![image](https://user-images.githubusercontent.com/100493881/156300153-06dd8668-91d5-4c6f-a1f7-a2ce379d2295.png)

**Comment by mystery3525** [comment]
If the web-map is up to date, which I believe it is, I also have some more wire discrepancies.
- [ ] There are extraneous wires under the doors and the two windows are not electrified in EVA
![image](https://user-images.githubusercontent.com/30960302/156364966-8bc75886-5d4a-47c9-b028-12ed38d2c201.png)
- [ ] The gravity generator windows *appear* not to be electrified
![image](https://user-images.githubusercontent.com/30960302/156364645-e669b4ff-60fd-4fda-8308-c320926d5e92.png)
- [ ] This window at the Medbay Security Outpost is not electrified
![image](https://user-images.githubusercontent.com/30960302/156364315-7393883c-152a-4e12-a33f-f4efbb6523ae.png)
- [ ] This split which looks like it should go to electrify the exploration crew dock
![image](https://user-images.githubusercontent.com/30960302/156362809-211333bd-77a4-4890-aacd-fae7927da4c7.png)
- [ ] There are wire pieces under these shield projectors
![image](https://user-images.githubusercontent.com/30960302/156364063-8bca7d9f-abd8-4328-bf53-34a4143eb657.png)
- [ ] Random wire under the mining office door
![image](https://user-images.githubusercontent.com/30960302/156363707-dd76e2e6-67ea-429c-bb30-4a8188cedc83.png)
- [ ] These Cargo Maintenance wires go to nowhere.
![image](https://user-images.githubusercontent.com/30960302/156363842-1093abdd-8a2a-485d-a851-53ab0747ced1.png)
- [ ] The humble missing wire above Engineering in Maintenance, which was gone for a while
![image](https://user-images.githubusercontent.com/30960302/156362377-9159c337-5540-49a4-ba6f-6c3c7c295b40.png)

This is what I found by looking around.
