### ISSUE TITLE
[Suggestion] Slot-Specific Antag-Prefs

### ISSUE THREAD

**Issue by ta3370** [BeeStation/BeeStation-Hornet#6450]
[Suggestion]
Either Slot-Specific Antag Prefs, or the ability to tell it that you don't want to roll a random role inorder to get antag
Global-Antag-Prefs effecting all character slots is really annoying when trying to set characters up for specific types of RP.

Playing a By-The-Book charslot who cares about their fellow crew and suddenly getting yoinked into engineer (with really outdated engineering knowledge from another codebase) to steal the HoS Gun and fully Round Remove an Explorer with it because you have other charslots with different characters who would fit antagging more so you have the settings on, is kind of a bummer. Especially when you try to keep your charslots to specific departments.

At bare minimum if it's having to yoink you to another role outside your prefs, atleast have it RandomName you, still sucks but atleast you aren't obliterating your character development for it.
Having "Getting antag roll is the end-all-be-all with global-antag-prefs instead of slot based" is definitely more incentivizing of Arcade Play than RP

**Comment by itsmeow** [comment]
Added in #9229 and #8776
