### ISSUE TITLE
felinid mutation toxin make you bald

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#6453]
Issue reported from  Round ID: 36534 (BeeStation Sage - Roleplay)

Reporting client version: 514.1575

Now felinid mutation toxin make you bald and if you regrow your hair now is black. This is not how it used to work

**Comment by Mails-z** [comment]
Well this was fixed immediately, thanks coders wizards.

**Comment by ivanmixo** [comment]
not merged yet
