### ISSUE TITLE
You lose your quirks if your brain is transferred into a body only clone

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#6456]
* #6032 

This is already a known issue. This report is made to prevent people to report this issue again.

Quirks are from a body, not from a brain. That's why you lose your quirks when your brain is transferred. If your brain is transferred into someone else's body, you will get their quirks because quirks are in their body.

To fix this issue, Bee code needs a rework quirk system, not the clone.

**Comment by ivanmixo** [comment]
quirks are stored in the balls

**Comment by Mails-z** [comment]
I once transfer a brain of a paraplegic and the new body immediately became paraplegic. I'm happy it got fixed

**Comment by EvilDragonfiend** [comment]
> I once transfer a brain of a paraplegic and the new body immediately became paraplegic. I'm happy it got fixed

It isn't fixed, and it will take forever to fix it.
