### ISSUE TITLE
heretics can keep their spells when borged

### ISSUE THREAD

**Issue by kit-katz** [BeeStation/BeeStation-Hornet#6462]
## Testmerges:
N/A

## Reproduction:
get a heretic...  give them ashen shift(the one spell oberved).
borg... 
the borg will retain the ability to use ashen shift

**Comment by Ivniinvi** [comment]
Intended behavior

**Comment by mcmeiler** [comment]
Intentional, spells are tied to mind

**Comment by Archanial** [comment]
Oversight

**Comment by kit-katz** [comment]
i see its a feature:tm:
