### ISSUE TITLE
Immovable rods miss too much

### ISSUE THREAD

**Issue by Oscari-pog** [BeeStation/BeeStation-Hornet#6467]
## Testmerges:
Huh. None.

## Reproduction:
1. Trigger rod event
2. Miss. Miss. Miss. Brush the AI sat slightly. Miss.
Might be just be a series of bad hits that I have seen but this has went on for long enough to be sus. It seems to, when it fires diagonally, eventually correct itself to fly straight up, which results in missing the station entirely.

**Comment by BrumalLake** [comment]
it should spawn aligned with the person highest in the coc as an afk prevention measure

**Comment by ike709** [comment]
Best fix would be a generator with a normal distribution to encourage it to pick a coordinate towards the middle of the x or y axis.
