### ISSUE TITLE
mutations doesn't reveal even if you get perfect matches

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#6469]
## Reproduction:
![image](https://user-images.githubusercontent.com/87972842/157929970-4cdce9d3-4c17-416d-b616-1cae30ed88a7.png)
![image](https://user-images.githubusercontent.com/87972842/157930004-a467011f-7aa8-431c-abf6-000c5dad172a.png)

Once you make perfect pairs, It becomes... nothing. literally.
I asked autisme to check this with his admin variable check, he answered the image one.

**Comment by Ivniinvi** [comment]
I believe (but am not certain) that this is the new species specific mutations popping up in bodies not of that species. I've been meaning to check it but have been bogged down with other things this week.

**Comment by EvilDragonfiend** [comment]
fixed now
