### ISSUE TITLE
light eater does NOT destroy inventory light sources

### ISSUE THREAD

**Issue by kit-katz** [BeeStation/BeeStation-Hornet#6473]
## Testmerges:
N/A

## Reproduction:
the light eater doesnt seem to destroy flashlights attached to items (ive noticed it on helmets and im pretty sure pda's to)
hitting an item that emmits light via an attached flashlight does not destroy it.
i only got to experience the missfortune of this bug twice so for all i know the list of inventory lights that dont get destroyed might as well be every single one

considering that a nightmare being unable to remove said lights form a officer is a death sentence. until fixed nightmares might as well be unplayable nightmare difficulty

**Comment by PowerfulBacon** [comment]
Fixed
