### ISSUE TITLE
tgui menus using internet explorer breaking

### ISSUE THREAD

**Issue by Jeff-3** [BeeStation/BeeStation-Hornet#6490]
## Reproduction:
Open a tgui machine that uses IE such as the prolathe, attempt to navigate the menu, get invisible, white, or unresponsive window. I'm currently experiencing this issue, but I've heard from others about the same issue that seemingly resolves itself over time. I would include screen shots, but the issue itself just looks like a regular menu, it just doesn't work. This issue is difficult to document because of how inconsistent it is, and it may even be system/OS specific, so I'm leaving this here for anyone in the future experiencing this to be able to document it so that we can hopefully build a better picture of what's happening.

Experienced on both byond version 514.1575 and 514.1582 using windows 10, persists through cache clears and reinstalls.

**Comment by Archanial** [comment]
Upstream issue

This is ancient and noone has any idea how to fix that

**Comment by Jeff-3** [comment]
> Upstream issue
> 
> This is ancient and noone has any idea how to fix that

Then all we can do is wait
