### ISSUE TITLE
stacking virus severity doesn't go above +5

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#6494]
## Testmerges:
#5624: '2021 viro expansion pack' by zeskorion at commit 4c0bd0d9df

## Reproduction:
stacking lethal virus severity doesn't let you go above +5. this is difficult to describe.
+5 (ARDS) +2 (deaness) -2 (coma) -1 (sensory) -1 (organ) = +3 in total
but for lethal ones, as it only counts +5, it becomes +1 in total. +2 (deafness) isn't counted.

I think it is because lethal ones count the highest one. I am not sure if it's intentional.

**Comment by EvilDragonfiend** [comment]
@zeskorion

**Comment by zeskorion** [comment]
> ## Round ID: 36758
> ## Testmerges:
> #5624: '2021 viro expansion pack' by zeskorion at commit [4c0bd0d](https://github.com/BeeStation/BeeStation-Hornet/commit/4c0bd0d9dfd2d21f3a915ee36d622daa0a98efda)
> 
> ## Reproduction:
> stacking lethal virus severity doesn't let you go above +5. this is difficult to describe. +5 (ARDS) +2 (deaness) -2 (coma) -1 (sensory) -1 (organ) = +3 in total but for lethal ones, as it only counts +5, it becomes +1 in total. +2 (deafness) isn't counted.
> 
> I think it is because lethal ones count the highest one. I am not sure if it's intentional.

this is intentional. You cannot go above 5 without using other symptoms that also go over 5. there was a period of a few months where archanial reduced severity calculations where doing so was possible, but i reverted that change a few months ago

basically, non-issue
