### ISSUE TITLE
Can we get better xeno protection classification already?

### ISSUE THREAD

**Issue by PerishedFraud** [BeeStation/BeeStation-Hornet#6496]
So you're telling me a riot helmet works, but a swat helmet doesn't, but an emergency space suit helmet does? And even the welding mask and swat mask just break instantly?

This is shitcode. And also another noob trap. You'll never know the specifics of this interaction without testing or code diving. The logic is lost. 

Fix it. The fact that no one likes a ranged, one-hit kill is only more incentive.

**Comment by Jeff-3** [comment]
wyci

**Comment by PerishedFraud** [comment]
no thanks they'll just ignore it. it needs to be coded by someone more trustworthy.

**Comment by Jeff-3** [comment]
> no thanks they'll just ignore it. it needs to be coded by someone more trustworthy.

I'm not sure if you realize, but what you're asking for is literally one line of code per item

**Comment by PerishedFraud** [comment]
>I'm not sure if you realize, but what you're asking for is literally one line of code per item

this argument goes both ways. I'd rather if someone the big boys like do it than me.

**Comment by zeskorion** [comment]
> So you're telling me a riot helmet works, but a swat helmet doesn't, but an emergency space suit helmet does? And even the welding mask and swat mask just break instantly?
> 
> This is shitcode. And also another noob trap. You'll never know the specifics of this interaction without testing or code diving. The logic is lost.
> 
> Fix it. The fact that no one likes a ranged, one-hit kill is only more incentive.

you need a helmet with face protection. swat helmets do not cover the face, riot helmets do. when in doubt, wear a mask and see if it shows through the helmet.

and yes, this is very much an easy thing to code. do it yourself if you care that much lmao

**Comment by WrillWasTaken** [comment]
This closed as stale during a xeno round, how ironic.
