### ISSUE TITLE
Some plant species don't inherit their parent plant stats on harvest

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#6510]
Issue reported from  Round ID: 36808 (BeeStation Sage - Roleplay)

Reporting client version: 514.1582

Some species of plant have their fruits not inherit the traits from the plant they came from.

On this round, I harvested plants from many species, BUT specifically Towercaps and Durathread always had harvests with 50 potency and no traits, regardless of the traits and stats of the plant in the tray. I even replanted the durathread, put in Perennial Growth and 100 pot again, but the harvests were still with the altered stats. I THINK they still inherited the yield, but no clue about the other stats.

Didn't plant all species of plant of course, there might be some more that don't work idk

**Comment by MarMauZag** [comment]
I can see this is kinda ignored topic and it seems it is quite flustrating. I can say for sure that it is Tower Caps, Steel Caps, Bamboo, Nova Flowers after doing some testing. There is probably more.

**Comment by EvilDragonfiend** [comment]
the issue is located and it will be fixed in my botany rework.

**Comment by MarMauZag** [comment]
> 

But this got fixed already. Seems this report got ignored and left to be there. I made similar report and it got closed and fixed already.

Edit: here is link to the issue. https://github.com/BeeStation/BeeStation-Hornet/issues/6552

**Comment by EvilDragonfiend** [comment]
ah, it's fixed already. coo. thanks for letting me know!
