### ISSUE TITLE
Hyperactivity Paralyse bug

### ISSUE THREAD

**Issue by Tsarkhastic** [BeeStation/BeeStation-Hornet#6535]
## Round ID:
36862

## Testmerges:
Viro Expansion 2020

## Reproduction:

It appears that the stage speed threshold of the new hyperactivity symptoms effect is bugged, the description states that it further increases stam regen and stun resistance however in its current state it causes the user to become permanently stunned without the ability to move, stand or use their hands. The stamina appears to be maxed, however when attempting to do an action e.g emote it informs that you are stunned.

I've tested it with all thresholds, just resistance and just stage speed threshold and the conclusion is the stage speed threshold is the cause. 

The symptom does appear to work properly with just resistance or no thresholds.

Also to add, after curing the virus the person is no longer paralysed

**Comment by zeskorion** [comment]
Should be Fixed
