### ISSUE TITLE
Borg module and battery disabling

### ISSUE THREAD

**Issue by airlines7** [BeeStation/BeeStation-Hornet#6538]
Issue reported from  Round ID: 36868 (BeeStation Sage - Roleplay)

Reporting client version: 514.1582

This is the situation that happened to me, If a unmoduled borg is flashed and have their battery taken out when flashed, They will be able to move around and talk without a battery, downside is you can no longer interact with the module button or various intractables (though you can interact with some). Give it a try its funny to do

**Comment by Sinestia** [comment]
this is intentional im p. sure


otherwise you'd have no option but suicide or going afk.

**Comment by Dejaku51** [comment]
Intentional
