### ISSUE TITLE
Camera static in maints as an organic

### ISSUE THREAD

**Issue by Shiraizawa** [BeeStation/BeeStation-Hornet#6546]
Issue reported from  Round ID: 36906 (BeeStation Sage - Roleplay)

Reporting client version: 514.1572

Im just a moth running around Box Medical Maints and this happened:
![image](https://user-images.githubusercontent.com/48320612/160008997-736c9042-c16a-4b93-8c8e-79450b8ef6ee.png)

Opening either the north of the south door made the static partially go away, as cameras could now partially see into that hallway. With both doors closed, the whole section was just static.
Reconnecting fixed it.

**Comment by PowerfulBacon** [comment]
Issue cannot be confirmed due to lack if reproduction steps
