### ISSUE TITLE
Rapid construction device doesn't offer anything new with one of it's upgraded

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#6554]
Issue reported from  Round ID: 36943 (BeeStation Sage - Roleplay)

Reporting client version: 514.1575
![fail145](https://user-images.githubusercontent.com/72167130/160242175-0cd57d4f-2ce9-4a6b-80f5-7f6919424765.png)
The rapid construction device doesn't seem to change when upgraded, with the circuit upgraded. In tg it lets you made APCs and air alarms instantly with that upgrade

**Comment by ToasterBan** [comment]
the upgrade works you just need to use it on hand made APC frames and such
