### ISSUE TITLE
"Gimmick" available as a latejoin role option.

### ISSUE THREAD

**Issue by Tyranicranger4** [BeeStation/BeeStation-Hornet#6559]
## Round ID: 
36957 (Sage)

## Testmerges:

#6556 
Although I don't see any reason why this would be related.
## Reproduction:
That moment when I have no clue how to recreate the issue because it's just something that happened randomly.

As for actual details of what happened.
Someone was able to latejoin as the 'Gimmick' role, no not a Gimmick role, just 'Gimmick'.
They were an Assistant with an ID reading 'Gimmick'. I'm fairly certain that's not how latejoin Gimmick roles are supposed to work.
No bureaucratic overflow event had occurred this round if that's relevant.
![image](https://user-images.githubusercontent.com/80382633/160265899-46e7238b-00ee-4bae-b27b-e7f6f52e39ac.png)
![image](https://user-images.githubusercontent.com/80382633/160265918-44cbf885-2bf8-4e7f-a84c-f2fddf55f26d.png)

**Comment by yurara** [comment]
The true hidden role

**Comment by PowerfulBacon** [comment]
HOP is able to open additional job slots for them
