### ISSUE TITLE
Tech disks can be used to jump to tier 5 on the research tree.

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#6565]
By inserting a tech disk into the R&D console, tier 5 can be accessed making all discovery research costs 0.

**Comment by Tsar-Salat** [comment]
> tier 5 can be accessed making all discovery research costs 0.

Was this produced from an empty techdisk or a filled exploration one?

**Comment by PowerfulBacon** [comment]
Confirmed this happened, I managed to reproduce it by just inserting a research disk into the thing and uploading it. Instantly jumped to level 5.

**Comment by Penwin0** [comment]
Unable to reproduce

**Comment by Tsar-Salat** [comment]
I am also unable to reproduce. This sounds like an edgecase.
