### ISSUE TITLE
Research stuck at tier 4

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#6569]
## Reproduction:
![image](https://user-images.githubusercontent.com/43061493/160603737-2b5f5a25-c1ff-46a7-b4e8-57ef4f310ec3.png)
honestly why not just do "go up a level for every 5 previous levels researched" whatever method is being used to calculate tech tiers are bugged to hell. 5x5x1000=25000 discovery points still requires effort and would stop people rushing all tech in 20 minutes like before supercruise. In fact I'm see other beebase lowering or even downright cancelling discovery.

**Comment by Archanial** [comment]
This isn't a bug. Those programs need to be researched from special items deconstructed.

**Comment by williamcll** [comment]
> This isn't a bug. Those programs need to be researched from special items deconstructed.

Not the issue that I'm talking about, normally you only need around 23000 discovery points to get to tier 5 by simply going up 1000 point researches without need disks from exploration. However this particular round I was still stuck at Tier 4 despite researching everything regular.
