### ISSUE TITLE
Blind bug?

### ISSUE THREAD

**Issue by CatimirPutin** [BeeStation/BeeStation-Hornet#6584]
Issue reported from  Round ID: 37034 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

Taking the teleporter on metastation in the ai chamber without it being calibrated resulted in me turning into a flyperson and blinded, as in my eyes were completely removed. Not 100% if this is a bug but i was told to report this.

**Comment by Dejaku51** [comment]
Should be already fixed
