### ISSUE TITLE
Lia the HoS' Carp is now an Error

### ISSUE THREAD

**Issue by KieraKatsura** [BeeStation/BeeStation-Hornet#6585]
## Round ID: 37034 - Sage

As reported to me by Kay Rique#7661 | 494257568324255745

This is the HoS' carp, Lia

![Lia Error](https://user-images.githubusercontent.com/88355569/160950539-ce82d2ca-e872-48ce-9a72-d76e342fc913.png)

**Comment by Archanial** [comment]
Can't replicate
