### ISSUE TITLE
Killer Tomatoes Attack Eachother + Podpeople

### ISSUE THREAD

**Issue by Jockeybane** [BeeStation/BeeStation-Hornet#6600]
## Reproduction: Produce a Killer Tomato. Despite having previously been allied to Podpeople, they no longer are and will attack them. Additionally, they will aggro onto and attack eachother, making them utterly useless.

In the specific instance they were used in this round, a podperson Botanist wanted to use Tomatoes to fight megafauna near the end of the shift; they chose to fight them and themselves over Hiero and the Swarmer Beacon

**Comment by PowerfulBacon** [comment]
This was added as a feature to counter botany mob spam
