### ISSUE TITLE
Getting cloned may change your gender, but the game still recognises you as your original gender

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#6601]
Issue reported from  Round ID: 37106 (BeeStation Sage - Roleplay)

Reporting client version: 514.1575
![hey](https://user-images.githubusercontent.com/72167130/161375429-4c945beb-ea01-4844-b5ef-dbc254a5e91d.png)

You can see that I examinated myself and is referred to me as she

**Comment by mcmeiler** [comment]
?

You were handed player-filed paperwork.

**Comment by Mails-z** [comment]
Yes, pretty rare thing to happen

**Comment by Archanial** [comment]
Not a bug
