### ISSUE TITLE
Warped Crossbreeds don't seem to draw runes

### ISSUE THREAD

**Issue by RDS88-beeman** [BeeStation/BeeStation-Hornet#6607]
## Reproduction:
1 - Feed ten bluespace extracts to a grey slime, creating a warped grey crossbreed
2 - Wait for it to charge, then attempt to draw a rune with it
3 - Complete the rune drawing and be met by nothing
4 - cry

**Comment by Zembaflemba** [comment]
For further clarification, making an extract by hand causes it to create the extract, but the effect and examine text are both null. An admin spawning one works as normal, so I suspect it's something with the actual process of creating the crossbreed.

(Although I tested it on a local server and it worked fine so ?????)

**Comment by Zembaflemba** [comment]
@PowerfulBacon Github is yelling at me so I'm yelling at you AAAAAAAA

**Comment by Zembaflemba** [comment]
@Rukofamicom I dunno maybe you'd like to take a crack at this.

**Comment by Rukofamicom** [comment]
I've definitely seen runes used in rounds since this report was made so I believe this to be user error in some form. 

That or it only applies to specific crossbreeds. Was it specifically the grey rune you were having trouble with @Zembaflemba ? Either way I recommend contacting me on Discord if you want to discuss debugging it with me, I don't check here very frequently.

**Comment by Zembaflemba** [comment]
It's specifically greys. Admin spawned ones work correctly, but if you make one by hand, the extract created has an effect of "null" instead of the correct description.

**Comment by Rukofamicom** [comment]
I'll look into this when I get a chance - expect it to be a few days and feel free to poke if a week has gone by without another response from me.

**Comment by Zembaflemba** [comment]
@Rukofamicom gaming

**Comment by Rukofamicom** [comment]
I'll be on it tomorrow

**Comment by Rukofamicom** [comment]
fixed, PR going up soon
