### ISSUE TITLE
Wiremod USB cables are not functional

### ISSUE THREAD

**Issue by thebigpgm153** [BeeStation/BeeStation-Hornet#6609]
## Round ID:
Not applicable : tested on private server

## Testmerges:
Not applicable : see above

## Reproduction:

* Build and launch a private beestation server
* create a bot shell, an integrated circuit loaded with a charged cell, and a USB cable
* screwdrive the bot shell next to an USB compatible console (example : sec records)
*  try to apply USB cable to the bot, just slap with it (even on help intent)
* try to apply cable to console, same result
* attempt the same on server running code from TG fork, see the USB cable working as intended

**Comment by Archanial** [comment]
The functionality wasn't ported.
