### ISSUE TITLE
Wiremod is not up to date

### ISSUE THREAD

**Issue by Archanial** [BeeStation/BeeStation-Hornet#6611]
We're missing many components, bugfixes, improvements and the whole USB thingy.

Bringing it up to date would be appreciated/

**Comment by Archanial** [comment]
#6609

**Comment by Dejaku51** [comment]
if you mean circuits im planning on doing it after pAI is merged
~~so go merge it~~

**Comment by Tsar-Salat** [comment]
> We're missing many components, bugfixes, improvements and the whole USB thingy.

Wasn't this intended?

The point being to make an unusable rump state of a feature?
I thought that was the whole reason we transitioned to the tg stuff

**Comment by Dejaku51** [comment]
> bumping this as current circuits are so much limited and pain to work with after the purge. porting the current tg wiremod or atleast components like view sensor, pathfinder, ntnet alone would widen the amount of fun stuff you can make. porting it as it is shouldn't be a big of a problem.

it is, i keep trying to update them but one PR requires another PR which requires another PR and so on
