### ISSUE TITLE
Welded firelocks can be opened with atmos ID

### ISSUE THREAD

**Issue by 4rchibald** [BeeStation/BeeStation-Hornet#6615]
## Reproduction:

Closed welded firelocks can be opened by sliding engi/atmos ID on them, they will just lift as if they weren't welded, once that happens they stay opened until they get unwelded. 

Also if anyone would be working on it, it would be much appreciated if firelocks could start accepting PDA with proper ID (just like air alarms and APCs do) instead of having to eject ID and only then slide it.

**Comment by Mat05usz** [comment]
Well this is debatable since regular airlocks will not open if you slide a PDA on them, so why would firelocks do?

**Comment by 4rchibald** [comment]
@Mat05usz  That seems like another omission than a deliberate design
If you slide ID into PDA and put it in your ID slot you can walk at airlock and it will open, if you throw PDA with ID in it airlock will open, it only refuses to open when when you have it in hand and try to open airlock by using PDA on it

Most people are putting their ID in PDA and it seems like unnecessary obstruction (that doesn't work in consistent manner with rest of unlockable and openable objects), it really only affects atmosians and engineers trying to deal with emergency and it's actually quite a challenge when you are racing to at least stop heat from spreading out and you have to slide your ID from PDA while having resin launcher, backpack in your hand and pulling water tank behind you
