### ISSUE TITLE
The ORM eats ID and you have to force it to give 'em back.

### ISSUE THREAD

**Issue by tsaoToast** [BeeStation/BeeStation-Hornet#663]
Round ID: Every round with miners
How to cause it: Put your ID in the ORM

Anyone unlucky enough to use the ORM has to then deconstruct it entirely, as there's no option to eject your ID.

**Comment by Kerbin-Fiber** [comment]
mm

must be tgui

@ike709

**Comment by Crossedfall** [comment]
No, it's a known bug. It's been around for a while now. Changes to the ORM tend to break it pretty easily.

**Comment by Kerbin-Fiber** [comment]
ORM? More like SPAGHETTI

**Comment by Crossedfall** [comment]
This should provide a more permanent fix: https://github.com/tgstation/tgstation/pull/45693
