### ISSUE TITLE
Cannot Fill Hypospray v2

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#6632]
First version went stale, linked [https://github.com/BeeStation/BeeStation-Hornet/issues/6369](here)

You cannot re-fill the hypospray at all once you depleted the original reagent and added a new one
## Reproduction:

-Empty Hypospray
- Load new reagent (In this case a vaccine bottle)
- Vaccine runs out, hypospray empty
- Try to refill it with another vaccine bottle
- Nothing happens.

**Comment by Rukofamicom** [comment]
Did some extensive testing on this one hoping to fix it, and even dug through changes to hypospray.dm from around the time of the original posting (there have only been three cases that aren't multiple years old) and couldn't find anything. 

In my testing I found:
* The base hypospray item (unobtainable) starts empty and may be filled with anything
* The CMO hypospray starts full and may be emptied or filled freely so long as you do not inject a mob
* The first time the hypospray is used to inject a mob, it becomes impossible to refill
* Using a syringe gives error messages both for drawing and filling: "You can't remove its reagents" and "You cannot fill the hypospray"
* Trying to use the admin command to add reagents gives a successful admin log message, but _**also fails to fill the hypospray**_. 

I'm not sure where to go from here with it.

**Comment by Rukofamicom** [comment]
Nevermind I have found it. 

`reagents.maximum_volume = 0 //Makes them useless afterwards`
`reagents.flags = NONE`

**Comment by Rukofamicom** [comment]
This was caused by #6245 which applied the above code to ALL HYPOSPRAYS instead of just medipens. 
Thank you @Hardly3D

**Comment by Fronsis** [comment]
Interesting, thank you for the extensive testing Ruko, looking forward for this to be resolved! let the mass vaccines start again!

**Comment by Rukofamicom** [comment]
issue was fixed ages ago lmao

**Comment by Rukofamicom** [comment]
@PowerfulBacon close this yo
