### ISSUE TITLE
Whiteship / Pirate ship / Syndicate fighters missing

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#6633]
I don't know if this was intentional by Bacon or overlooked when doing shuttlecruise but most of the old pilotable ships are gone, Whiteship is completely missing from all of the ruins/signals and the Pirate Ship and Syndicate little fighter that are on the Syndicate caravan attack signal are gone, only the non-pilotable ships that were destroyed are there, missing all the other loot

That explains why we haven't seen Whiteship in forever and why no one really docked randomly with a pirate ship/ Syndicate fighter outside arrivals, idk some people loved to explore and pilot them back to station, specially Whiteship

**Comment by PowerfulBacon** [comment]
That's odd, I'll look into this. Wasn't aware that the shuttles just didn't spawn.

**Comment by PowerfulBacon** [comment]
This is a pretty important bug since they are spawned via docking ports on map load. Something is pretty broken here but I'm not sure what.
