### ISSUE TITLE
chicken nugget box sprite

### ISSUE THREAD

**Issue by LodedDiper69** [BeeStation/BeeStation-Hornet#6646]
## Reproduction:
Step 1: Acquire chicken nugget box
Step 2: See it is misplaced

Proof:
![image](https://user-images.githubusercontent.com/101019561/162791514-f3271695-3cda-43f1-aadc-b4def09d167a.png)

**Comment by Tsar-Salat** [comment]
> See it is misplaced

The problem being it is off-center?
