### ISSUE TITLE
Crew monitor not showing anyone.

### ISSUE THREAD

**Issue by lowwy** [BeeStation/BeeStation-Hornet#6650]
## Reproduction: Open handheld crew monitor or use the crew monitor computer
![cm](https://user-images.githubusercontent.com/8070319/162815236-f744381b-1a86-43be-97a3-7f2a59fd195a.PNG)

**Comment by Dejaku51** [comment]
known issue https://github.com/BeeStation/BeeStation-Hornet/pull/6645

**Comment by ivanmixo** [comment]
Fixed by #6645

**Comment by kit-katz** [comment]
no it aint

**Comment by lowwy** [comment]
It mostly work now (tested it while playing yesterday (20-04)), though it did breaks randomly in-round and fixed itself 20 min later.

I guess the fix for that is #6717
