### ISSUE TITLE
PAI separating from holofrom

### ISSUE THREAD

**Issue by pricklytomato** [BeeStation/BeeStation-Hornet#6662]
## Round ID:
37358

## Reproduction:

Become a PAI, set holoform to something like a raven, get picked up by a person, and then dissolve holo form. The person is still holding the holoform in their hand and can drop it. I also found out that if the PAI is then put into a bot and then ejected, you have total control over the holoform and rune text is above the holoform. This is only fixed if the PAI then goes into holoform again, which then removes the original holoform

**Comment by Archanial** [comment]
Ancient bug from tg.
I think it's fixed with pai pr we have opened but I'm not sure.
