### ISSUE TITLE
Unsolvable abandoned crate

### ISSUE THREAD

**Issue by Vanshark** [BeeStation/BeeStation-Hornet#6665]
## Round ID:

37344
## Reproduction:
Not sure how reproducible this is gonna be given the random nature of these, but what happened was I went on Sage and tried to open an abandoned crate. I entered "1234" and got 0 bulls, 0 cows. I entered "5678" and got 0 bulls, 1 cow. That's already unsolvable to my understanding but I did "7890" for fun and got 1 bull, 2 cows. I looked at the .dm for abandoned crates and there doesn't seem to be an "eleventh digit" or anything so I feel confident that this is a bug and not a skill issue.

**Comment by PowerfulBacon** [comment]
This is possible if you can have the same digit twice, but I'm pretty sure it shouldn't allow that

**Comment by Vanshark** [comment]
> This is possible if you can have the same digit twice, but I'm pretty sure it shouldn't allow that

It shouldn't, yeah. The lock system tells you there are no duplicates and even prevents you from attempting to enter them.

Extra info, maybe useful if the codes are logged: This was the crate that always spawns in mining base next to the pacman.
