### ISSUE TITLE
Cogscarab ghostrole can be used to spoil clock cult in OOC before round start

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#6675]
As the cogscarab ghost role is avaiable as soon as you can select "observe", there is a timeframe of about half a minute between being able to ghost and the round actually starting where OOC is still enabled.
Because of this I have seen several people ghost, see there are cogscarabs and then yell in OOC that its clock cult.

My idea to solve this would be to make the scarabs avaiable only once everyone else spawns, similarly to Ashwalker eggs.

**Comment by ta3370** [comment]
Alternatively: Leave it available, screencap and report people who do it, and get asshats who don't intend to play fairly or by the rules banned.
