### ISSUE TITLE
Search bar in chem dispenser UI

### ISSUE THREAD

**Issue by CriticalVRAM** [BeeStation/BeeStation-Hornet#6676]
Simple suggestion that will have big QoL impact when working with the chem dispenser. I don’t know how it works, but you already have search functionality in certain UI elements.

**Comment by Ivniinvi** [comment]
There's like, twenty chemicals? And they're in alphabetical order?

**Comment by CriticalVRAM** [comment]
Well it would still be nice I think.

**Comment by Rukofamicom** [comment]
Okay I just got done with tiny hand labeler, but I have to take a pass on this one. This seems totally unnecessary to me and might have strange interactions with hallucinations (which will randomly change chemical names)
