### ISSUE TITLE
Players who suicide or cryo should not be able to roll for antagonist positions for 5 minutes (Same as ghost role spawns)

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#6701]
Players who suicide or ghost should not be able to roll for the antag popup messages for a certain amount of time.
Players should not be able to suicide as soon as nuke ops is declared to attempt to role antags.

**Comment by nednaZ** [comment]
I 100% agree.

If possible, this could have a config setting for how long of a delay there should be.

**Comment by Archanial** [comment]
100% disagree.
There should be no message and it should only deduct some of your antag rep.

**Comment by Rukofamicom** [comment]
There should be an antag rep reduction and it should _also_ prevent immediately joining as any given ghost role, antagonist or not.

**Comment by PowerfulBacon** [comment]
This should not reduce antag reputation for cases of legitimate use. (We don't want to subtract antag rep from every single player that dies)

**Comment by mcmeiler** [comment]
I don't quite get what you mean?

If it's a nuke op round, there won't be any antag popups barring reinforcements, which are 90% of the time already bought and used before they appear on station.

**Comment by Dallen999** [comment]
Aren't suicide/cyro already punished by not receiving round end antag rep?

Add negative rep for Cyro and people will just afk/non-verb suicide and potentially ruin antag objectives.

**Comment by pricklytomato** [comment]
Wouldn’t one possible work around doing something like hanging yourself or throwing yourself into space? I know a admin will probably see it, but would still allow someone to antag roll and then die in a way that doesn’t punish them so they can use a ghost role.

**Comment by d0sboots** [comment]
I'd consider working on this... but it would require having a definition of what "suicide" means. Obviously we have an idea in our heads, but that doesn't help the code tell the difference between suicides and legit deaths. How much self-harm counts? If you jump out the airlock, is that a suicide, or just you forgetting to grab a mask?

**Comment by PowerfulBacon** [comment]
I guess it would have to count all player deaths
