### ISSUE TITLE
Cyborgs shouldnt be able to cryo like crew

### ISSUE THREAD

**Issue by Tsar-Salat** [BeeStation/BeeStation-Hornet#6704]
Inspired by: https://forums.beestation13.com/t/c-b-t-cyborg-report/17702/

Cyborgs shouldn't be able to cryo like regular crew can at the cryosleep chambers. 

Borgs are both a resource to the station and a ghostrole, a combination that does not mix very well. For a station with lowpop and/or low resources, borgs are a lifesaver.

This request is for borgs to no longer be able to use the cryo machines, but cryo in a similiar fashion as the AI within the OOC tab.

**Comment by TheMaggotGuy** [comment]
Frankly it's ridiculous they were even allowed to to begin with

**Comment by Lagomorphica** [comment]
You could also just have it that when they enter the cryosleep chamber it automatically refunds the materials used for their upgrades and their shell, but thats a WYCI. 

Something similar to this can already be accomplished by simply having them ghost out of their body, though.

**Comment by ToasterBan** [comment]
I am pretty sure if a borg cryos it becomes possible for someone to latejoin as one

**Comment by williamcll** [comment]
Maybe have cryopods recycle all the borg materials so the robotcist can rebuild one without consuming resouces?

**Comment by Tsar-Salat** [comment]
> Maybe have cryopods recycle all the borg materials so the robotcist can rebuild one without consuming resouces?

Borgs can be dismantled by cutting their wires and wrenching them, which returns them to their base parts. Any robo can easily do this. 

The mechanic of a borg returning the parts used to build them is well in place. It is simply the oversight that allows borgs to cryo and waste their chassis that is the issue here

**Comment by PowerfulBacon** [comment]
They are allowed to cryo, which opens up the job role for someone else.
