### ISSUE TITLE
Add the ability to place attach wall girder to the RCD

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#6725]
The RCD can place iron walls, but if you want any other type of wall, you have to build by hand a wall girder, attach it to the floor and ad then the other material.
My suggestion if to be able to toggle the RCD to place attach wall girder instead of iron walls

Why is this good for the game?
It would allow the engineers to build custom shuttles of other materials rather than iron, cutting 2/3 of the time it would normally take

**Comment by JukeJukestar** [comment]
I think you mean "frame" instead of "flame"?
Also, its called a wall girder - might wanna update it so its easier to find!
