### ISSUE TITLE
Replace the shower floor tile in science box entrance with and anti slip tile pleases

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#6740]
Issue reported from  Round ID: 37611 (BeeStation Sage - Roleplay)

Reporting client version: 514.1575
![BRUHHHHHH](https://user-images.githubusercontent.com/72167130/164891513-2a964904-edc9-4f9b-ac6c-ce5503bedb4d.png)

**Comment by Mails-z** [comment]
A dragon kill me because I slipped there, in Meta station there are anti slip floor tile in sciences entrance

**Comment by Tyranicranger4** [comment]
Massive skill issue.
Probably should be noslip though.
