### ISSUE TITLE
Midround server update creates cursed pipe layers

### ISSUE THREAD

**Issue by OverwatchVoice** [BeeStation/BeeStation-Hornet#6750]
## Testmerges: 
#6553: '[PORT] New sounds when interacting with stuff' by Hardly3D at commit 255aaff30a

## Reproduction:
Place down pipes on various layers. Some pipe items are misaligned, some are straight up invisible

As stated above. Pictures attached.

[oh god oh fuck](https://cdn.discordapp.com/attachments/932069087075532810/968264986717716501/unknown.png)

**Comment by Tsar-Salat** [comment]
#6039 in all likelihood
