### ISSUE TITLE
Some Cyborg items aren't deleted during cremation

### ISSUE THREAD

**Issue by benbot16** [BeeStation/BeeStation-Hornet#6765]
## Round ID:
37750

## Testmerges:
#6558 

## Reproduction:
1. Upgrade a borgo with items (In this specific case it was a borgo crew pinpointer and borgo defibrillator)
2. Cremate said cyborg
3. Some items won't be deleted with the borg, and can't be dropped if picked up by humans.

**Comment by EvilDragonfiend** [comment]
It appears the dropped items were what borg was holding at the moment.

**Comment by Dejaku51** [comment]
why the fuck would you cremate a borg

**Comment by EvilDragonfiend** [comment]
> why the fuck would you cremate a borg

the captain who cremated the borg was insane at the moment...
