### ISSUE TITLE
Crew monitoring died mid-round

### ISSUE THREAD

**Issue by lowwy** [BeeStation/BeeStation-Hornet#6766]
## Reproduction: no clue

At some point this round, around 45~ mins in, crew monitoring died

![nosensors](https://user-images.githubusercontent.com/8070319/166068699-2acfdc8c-dade-4102-8c2b-8cdf653f28c3.PNG)

Sidenote:: In some rounds, I don't pop up on sensors as Roundstart CMO while my sensors are maxxed. I changed jumpsuit but that did not fix it. i'll get a round ID for that when it happens again.

**Comment by Mat05usz** [comment]
I know why the monitor died, no idea about the jumpsuit thing though

**Comment by Mat05usz** [comment]
Please make another issue with jumpsuit not working if it happens again when the fix is merged

**Comment by Mat05usz** [comment]
Actually I also found out the bug with jumpsuits, it's unrelated to crew monitor though

**Comment by lowwy** [comment]
As it's unrelated to crew monitor I made another issue for the CMO not showing up.
Can you add your knowledge about it @Mat05usz ?

#6780

**Comment by Mat05usz** [comment]
Posted in the jumpsuit related issue
