### ISSUE TITLE
Contractor kidnapping lethal to Oozelings : 

### ISSUE THREAD

**Issue by Rasselbok** [BeeStation/BeeStation-Hornet#6770]
## Round ID:
37790

## Reproduction:

Got kidnapped by a contractor as an oozeling - was fully fed and not hungry/injured/poisoned - after getting ransomed back, within seconds i started dying of massive toxin damage and the associated blood loss for oozelings. Passed out, was unable to be revived even by a full team of people trying surgery and defib, so whatever it was it REALLY fucked me up. 

Something about the contractor kidnap/ransom process seems like it's possibly trying to 'heal' toxin damage and as such killing the oozeling - the same thing happens if I ever take nanites for any reason as an oozeling - it tries to heal toxin damage, by giving me more toxin damage, until I die.

**Comment by Liidero** [comment]
Think it might be this line of code in the syndicate_contract.dm? seems that it gives you 20(?) units of omnizine when you get returned. Maybe there should be a check for oozelings and appropriate healing for them

![image](https://user-images.githubusercontent.com/34969294/166153053-5bedd3b8-4e92-4f7d-984f-cd439966ccb3.png)

**Comment by Zembaflemba** [comment]
Simple fix would be to replace /datum/reagent/medicine/omnizine with /datum/reagent/medicine/regen_ooze, since that doesn't kill slimedudes.

**Comment by MNarath1** [comment]
> Simple fix would be to replace /datum/reagent/medicine/omnizine with /datum/reagent/medicine/regen_ooze, since that doesn't kill slimedudes.

Or just don't use chemicals here and adjust their health directly trough the appropriate procs.
