### ISSUE TITLE
Picking up jumpsuit removes you from crew monitoring

### ISSUE THREAD

**Issue by lowwy** [BeeStation/BeeStation-Hornet#6780]
## Reproduction: Be roundstart CMO, open locker, pick up spare jumpsuit

As roundstart CMO I go through my locker picking up everything. After that I don't show up on sensors anymore. 
Apperently this is due to picking up jumpsuits. 

**Edited description as its jumpsuit related not role related.** 

## Split from other issue #6766

Please make another issue with jumpsuit not working if it happens again when the fix is merged

_Originally posted by @Mat05usz in https://github.com/BeeStation/BeeStation-Hornet/issues/6766#issuecomment-1113969929_

Actually I also found out the bug with jumpsuits, it's unrelated to crew monitor though

_Originally posted by @Mat05usz in https://github.com/BeeStation/BeeStation-Hornet/issues/6766#issuecomment-1114063740_

**Comment by Mat05usz** [comment]
Until the fix is merged, do not pick up anything jumpsuit-related that you can put on the jumpsuit slot. It will remove you from sensors, requiring to remove your worn jumpsuit and equipping it again.
