### ISSUE TITLE
Nanite Program Cap maximum of 20 programms in Nanite Cloud

### ISSUE THREAD

**Issue by MNarath1** [BeeStation/BeeStation-Hornet#680]
Issue reported from  Round ID: 8581 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 512.1488
I don't know if thats just the intended ammount or if during the making of nanites someone decided  thats enough because there is no entry on any wiki that 20 is the maximum. But 20 programms is not enough for complex automatic nanite programms please increase the cap to make sure that you can't reach it that easy.

**Comment by Kevak** [comment]
I agree that more programs would permit more interesting, higher complexity setups. I'll see about making a PR to boost the cap later today.

Can't guarantee it'll get merged but hey, I'll try.

**Comment by MNarath1** [comment]
Ok thank you.
