### ISSUE TITLE
Tgstation hrf

### ISSUE THREAD

**Issue by codingnoobster** [BeeStation/BeeStation-Hornet#6820]
Please add tg stations nuclear reactor/hrf to bee it would be a good opportunity for both antags and atmos.

**Comment by mystery3525** [comment]
I do not believe you understand the intricacies of what you are asking. TG uses the "updated" version of fusion [Fusion V6: Chaos Hyper-Torus Edition](https://github.com/tgstation/tgstation/pull/42748), which is **wildly** different from our fusion setup, mostly open turf.

**Comment by williamcll** [comment]
No, awful. Open turf fusion is more fun than the glorified storm drive.

**Comment by codingnoobster** [comment]
> I do not believe you understand the intricacies of what you are asking. TG uses the "updated" version of fusion [Fusion V6: Chaos Hyper-Torus Edition](https://github.com/tgstation/tgstation/pull/42748), which is **wildly** different from our fusion setup, mostly open turf.

The one bee uses isnt near as good as the hrf mainly due to good roleplay opportunities and safer ways to make gasses

**Comment by Tsar-Salat** [comment]
> The one bee uses isnt near as good as the hrf mainly due to good roleplay opportunities and safer ways to make gasses

IMO no part of Engineering should ever be truly "safe". Industrial accidents and getting disintegrated by the space crystal are already the norm.

Atmosia should be no different.

**Comment by williamcll** [comment]
> The one bee uses isnt near as good as the hrf mainly due to good roleplay opportunities and safer ways to make gasses

Irridating all of atmos is fun and gets the rest of the station to interact
