### ISSUE TITLE
Ethereal emag interaction doesn't work as intended

### ISSUE THREAD

**Issue by imsynthex** [BeeStation/BeeStation-Hornet#6829]
## Round ID:
37935

## Testmerges:
None

## Reproduction:
Be an ethereal
Spawn in an emag
Use it on yourself
Only your glow changes color, not your actual character sprite, like seen below:

![image](https://user-images.githubusercontent.com/81387903/167247042-6d16ee91-9540-40db-9ede-fef17a4dfc48.png)

Note: this seems to be a problem with all things that include ethereals changing colors (i.e dying should make an ethereal pale white, it does not)

**Comment by Penwin0** [comment]
This is probably kapulimbs, god damnit
