### ISSUE TITLE
Unable to string wire together on top of Catwalks(I.E. Solars)

### ISSUE THREAD

**Issue by stromlin** [BeeStation/BeeStation-Hornet#6837]
## Reproduction: 
This is on space exposed catwalks such as is found at solars
Using either Cables or the Rapid Cable Layer place one wire as normal on a catwalk then attempt to place a second wire to connect further.

Doing the above steps results in the cable connecting downward in regards to z-level no matter which direction the second cable is placed.
On two occasions while testing the connection instead was made in a upwards manner, in the cases of this the wire is unable to be cut directly and the catwalk had to be removed to fix.
On one unreproducible occasion making a downwards connection then placing a cable ontop of that tile then another at a different angle on the same tile caused all cable to visually disappear, it was still there on rightclick and on removal of the catwalk was detached

**Comment by SetchDreskar** [comment]
Posting evidence for this particular issue so you can get a visual look at how weird this thing is
![Stitched Wires](https://user-images.githubusercontent.com/9970998/167279468-112f6338-2a23-433d-8482-bb9d2641e5b4.png)
.
