### ISSUE TITLE
Goliath AI is fucked sideways. 

### ISSUE THREAD

**Issue by Rukofamicom** [BeeStation/BeeStation-Hornet#6844]
## Round ID:
~~37974~~
Irrelevant, the behavior is easily replicated to some degree. 

## Testmerges:
None

## Reproduction:

Exist anywhere near a goliath. One of three things will happen:
`case 1` Goliath aggros, moves one tile away from you, then never moves again until dropping aggro. It will use tentacles to attack from a range and melee if you are adjacent during an attack cycle. 
`case 2` Goliath aggros, chases and never uses tentacles at all. Will appropriately melee an adjacent target as expected. 
`case 3` Goliath acts as shown. Which is to say it doesn't act at all outside of getting red eyes.

**Comment by zeskorion** [comment]
simplemob ai code in general is extremely basic and needs... work

**Comment by Rukofamicom** [comment]
Going to try to work on this myself, but went ahead and made an issue since it's late. This was broken recently because I do not encounter this bug on my local code with slightly out of date copies of the codebase. 

Player who prompted me to test it claims it started about two days ago.

**Comment by MNarath1** [comment]
Did any other simplemob hostile behave like that or only goliath?

**Comment by Rukofamicom** [comment]
Unsure, as of yet. I'm sifting through my various branches to see exactly when the bug stops and starts, since none of the goliath pages were updated recently. 

I'm checking to see if #6786 is the point at which it started happening right now.

**Comment by Rukofamicom** [comment]
Appears to be just the goliaths.

**Comment by Rukofamicom** [comment]
It's #6697

**Comment by Rukofamicom** [comment]
Okay they are **way** more broken than just not moving after aggro. I'm getting different responses every time I spawn a new one to try and replicate the bug. 

https://user-images.githubusercontent.com/9547572/167355736-2f6ff9df-dfe2-493c-a8e4-de4623c869ba.mp4

They're fucked sideways lmao

**Comment by MNarath1** [comment]
> Okay they are **way** more broken than just not moving after aggro. I'm getting different responses every time I spawn a new one to try and replicate the bug. 
> 
> 
> 
> https://user-images.githubusercontent.com/9547572/167355736-2f6ff9df-dfe2-493c-a8e4-de4623c869ba.mp4
> 
> 
> 
> They're fucked sideways lmao
> 
> 
> 
> 

Makes no sense trough that its just the goliath cause the proc that is used to handle movement goto that was modified by that PR is used for all hostile mobs so if this was broken it should be broken elsewhere to unless something else is the issue

**Comment by MNarath1** [comment]
Will look at it trough

**Comment by MNarath1** [comment]
Goliath's move delay is 4 seconds it keeps overwriting the loop before it can actually fire the move proc

**Comment by MNarath1** [comment]
Unless somehow it was able to actually move because of either lag or because it could not overwrite it this time
