### ISSUE TITLE
Clowns can't use Bee-shop items

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/BeeStation-Hornet#686]
## Round ID: 
Any round where a clown joins late or at round start. (Probably the same for mimes)

## Testmerges: 
Not really a test merge. Probably an issue originated from #645 

## Reproduction: 
Equip an item in your loadout, join as a clown (mimes probably have the same issue), and the item won't be found on your head or within your backpack.

**Comment by ike709** [comment]
Probably another case of `after_spawn()` not calling parent for clowns. Same thing happened with mimes, I'll fix it tomorrow.

**Comment by GoatMonarch** [comment]
I would not be supriced if it's some spawning prock yeah, glad to see you hard at work. HONK

**Comment by ike709** [comment]
![image](https://user-images.githubusercontent.com/5714543/68052764-662e4080-fcb8-11e9-9bb7-fd768c0da69b.png)

Works fine locally.

**Comment by GoatMonarch** [comment]
Hell yeah, speed merge dat *Clap clap*

**Comment by ike709** [comment]
No. It works fine locally as in I can't reproduce this bug.

**Comment by GoatMonarch** [comment]
Test out starting with the yellow hard hat then. Might just be an issue to that item.

**Comment by GoatMonarch** [comment]
Otherwise I am unsure as to what the issue may be. I purchased the hard hat, ensured the button next to it is green to signal it's equiped. 
Saved it all too of course. 🤔

Other note I won't be aviable till later tomorow. Feel free to bring additional questions, and I will try to respond to it as fast as possible.

**Comment by MarkSuckerberg** [comment]
Fixed, supposedly.
