### ISSUE TITLE
Disposal pipe layering does not affect atmospherics pipe despite stated in code

### ISSUE THREAD

**Issue by williamcll** [BeeStation/BeeStation-Hornet#6864]
## Reproduction:
In code, the disposal pipe is set so that it's always below the atmospherics pipes, which allows accessibility for all pipes.
![image](https://user-images.githubusercontent.com/43061493/168237331-69790614-8d6e-4d0e-b4be-a366572919ac.png)
However, when tested, this is not the case, as shown here in EVA maintenance on boxstation. This makes atmospherics pipes on that tile inaccessible without alt clicking or removeing the disposal pipe.
![image](https://user-images.githubusercontent.com/43061493/168244849-44f16771-cb61-416a-bf7a-a74f33fbe781.png)

**Comment by Mat05usz** [comment]
Iirc it's mappers fault, ~~the air supply pipe is probably a subtype that's 'hidden'~~, 1 minute mapping fix

I think it's due to disposal pipe being 'on top' in the map editor, just right click it and 'move to bottom' until it's below pipes.

**Comment by williamcll** [comment]
> Iirc it's mappers fault, ~the air supply pipe is probably a subtype that's 'hidden'~, 1 minute mapping fix
> 
> I think it's due to disposal pipe being 'on top' in the map editor, just right click it and 'move to bottom' until it's below pipes.

Problem is some maps have a lot of this incorrectly layered pipes, so going through each and every tile can take forever.
