### ISSUE TITLE
Felinid taking zombie mutation bug

### ISSUE THREAD

**Issue by Mat05usz** [BeeStation/BeeStation-Hornet#6873]
Issue reported from  Round ID: 38063 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

- be cat
- get zombie mutation toxin
- get turned into a bald human while moaning like a zombie

**Comment by RDS88-beeman** [comment]
this is a kapulimbs moment i think
zombie just doesn't have unique limb types anymore so it just defaults to giving you human ones
seems like it at least.

**Comment by Mat05usz** [comment]
I was kinda worried it is kapu limbs. I heard they are no longer coding here so it's gonna be fun to fix
