### ISSUE TITLE
Sentient vending machines can throw stuff at the Eminence during clock cult

### ISSUE THREAD

**Issue by Hardly3D** [BeeStation/BeeStation-Hornet#6874]
## Reproduction:
While playing as Eminence during Clock Cult, if you activate an event that makes vending machines go sentient and go towards one, it'll throw stuff at you which can potentially expose you to the crew.

![image](https://user-images.githubusercontent.com/66234359/168345513-3d521caf-7c98-4165-9cbd-bbd0976d9ec5.png)

**Comment by Mat05usz** [comment]
Yeah it's because eminence is a subtype of a simple animal, I'll put a fix up soon
