### ISSUE TITLE
Roundstart borgs don't appear on robo console/ AI link

### ISSUE THREAD

**Issue by Mat05usz** [BeeStation/BeeStation-Hornet#6877]
Issue reported from  Round ID: 38065 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

- Become roundstar borgo
- have no master
- late round AI comes
- it isn't your master, nor is anyone else.
- you do not show up on either AI's status tab or robo console

**Comment by Coding-Grape** [comment]
Wait you're saying that round start borgs aren't by default initialized to Asimov before checking for a master AI the fuck?

**Comment by Dejaku51** [comment]
> you are basically free to do anything cause no laws apply to you

you still have your round start laws

**Comment by Mat05usz** [comment]
> Wait you're saying that round start borgs aren't by default initialized to Asimov before checking for a master AI the fuck?

yeah you have your laws, but you are basically invisible. No mention of you either in AI's status tab or robo console.

I meant that no authority applies to you, not no laws, my bad.

**Comment by Dejaku51** [comment]
crew (RD, captain etc) can still see you on robo console and lock you/make you explode

**Comment by Mat05usz** [comment]
> crew (RD, captain etc) can still see you on robo console and lock you/make you explode

AI can't though

**Comment by Mat05usz** [comment]
I updated the description

**Comment by Dejaku51** [comment]
> AI can't though

works as intended

if you want to control it, tell roboticist about the borg and they will sync it

**Comment by PowerfulBacon** [comment]
After looking at #6955, this seems intentional. AI shouldn't be able to control borgs that it doesn't have authority over.
