### ISSUE TITLE
Botany Seed Extractor machine does not vend directly to hand

### ISSUE THREAD

**Issue by RussianGenCoke** [BeeStation/BeeStation-Hornet#6883]
step 1: have a seed in the machine
step 2: have the machine vend the seed

it still vends directly on top of the machine, instead of it being directly in hand like other vending machines

unsure if this is intentional or if the seed extractor isn't labeled as a vending machine in the code

**Comment by mcmeiler** [comment]
No (vending) machine in this codebase vends to the hand.

**Comment by RussianGenCoke** [comment]
> No (vending) machine in this codebase vends to the hand.

was there not a pr that makes vending machines vend to hands?

https://github.com/BeeStation/BeeStation-Hornet/pull/6854
