### ISSUE TITLE
Monkey AI bug

### ISSUE THREAD

**Issue by Mat05usz** [BeeStation/BeeStation-Hornet#6903]
Issue reported from  Round ID: 38155 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

- Have a monkey
- Remove all of it's limbs
- Buckle it to a rollerbed
- Piss it off, it will move the rollerbed as if it was a wheelchair and continue to chase you fueled only by hatred towards you

**Comment by williamcll** [comment]
It will still chase you when dead, I think, or maybe that's another bug.

**Comment by Mat05usz** [comment]
Might fix these during weekend, if noone does before me

~~it totally wasn't me who ported it over from TG with all these bugs~~

**Comment by Mat05usz** [comment]
Aye I'm fixing it, or porting TGs upgrades over? Who knows!
