### ISSUE TITLE
Plumbing does not work at all

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#6923]
## Reproduction:

- Place plumbing trying to create any chemical (synthesizer + reaction chamber)
- Wrench it all down
- Set the regents
- Nothing happens, no output from reaction chamber.

Have reproduced in multiple rounds.

**Comment by ToasterBan** [comment]
did you fill the synthesisers with matter capsules?

**Comment by Rukofamicom** [comment]
This is not a bug, this is the result of a plumbing nerf outlined here: #6281

**Comment by itsmeow** [comment]
Understood. Would be nice if someone could update Guide to Plumbing on the wiki with this information
