### ISSUE TITLE
Limbs rework caused new mobs to always be bald.

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#6943]
The reworking of limbs by Kapu has lead to newly spawned mobs to be bald. This affects nukies, clockcult, most ghost spawns, zombies and some other things.

**Comment by ivanmixo** [comment]
Also affects species changing last time I checked. They're bald with black hair.

**Comment by ivanmixo** [comment]
The first commit in #6454 used to fix this, but kapu said he'd make a fix that isn't a bandaid, then never did.

**Comment by Kapu1178** [comment]
why are you lying. the proper fix WAS made. You are aware about it since you tried to port it and gave up.

**Comment by ivanmixo** [comment]
Well you didn't make it here ;3
