### ISSUE TITLE
Blob zombie issue

### ISSUE THREAD

**Issue by snek-with-tophat** [BeeStation/BeeStation-Hornet#6945]
Round ID :38284

When trying to take over a blob zombie created from humanised monkey, the zombie would seemingly retain the original AI of the human NPC and prove impossible to control.

Reproduction:
1. Make a blob zombie virus
2. Infect a humanised monkey
3. Try to ghost control the resulting blob zombie

**Comment by MNarath1** [comment]
Best guess the moveloop does not get properly canceled does it jump between targets like going after a new target or just keep on trying to get back to its original location?

**Comment by MNarath1** [comment]
Wait you said monkey ai thats strange

**Comment by snek-with-tophat** [comment]
I may be wrong about the monkey AI, the bug doesn't seem to affect zombies made from players tho

**Comment by MNarath1** [comment]
thanks that helps a lot i will take a look at it

**Comment by MNarath1** [comment]
the reason why i say its strange by the way is because blob zombies are technically still blob spores and should not get a new ai or anything else so the only thing that can realistically break is the system preventing their ai from fireing.

**Comment by MNarath1** [comment]
strange thing is when what i think is the reason is indeed why this is happening why is it only happening to this kind of blob zombies it should be all of them

**Comment by Tsar-Salat** [comment]
this shit still happens, real fuckin annoying
