### ISSUE TITLE
/mob/living/carbon/monkey hard del

### ISSUE THREAD

**Issue by mystery3525** [BeeStation/BeeStation-Hornet#6950]
## Testmerges:

Nothing of note.

## Reproduction:

Spawn 20-30 or more monkeys with the xenobio console, then have them somehow die (to slimes) and recycle all of them as fast as possible. Once the Garbage subsystem tries to delete all of the monkeys, there is a noticeable spike in performance, noticed by all players.

Supplementary:
![image](https://user-images.githubusercontent.com/30960302/170495517-17e3dbb4-e6ec-4871-bf67-5eae38fcb6dd.png)
![image](https://user-images.githubusercontent.com/30960302/170495548-8d29b81e-7640-467b-875f-0cc90a344d5e.png)

**Comment by MNarath1** [comment]
Looks easy enough to reproduce and run trough the reference tracker if no one else wants to give it a go i could take a look at it

**Comment by MNarath1** [comment]
important question did you keep that vv window open while you scooped up the monkeys? Of a monkey i mean

**Comment by MNarath1** [comment]
i can't find any evidence of harddeletes here

**Comment by mystery3525** [comment]
I believe we scooped up the monkey while they had a slime still buckled to them, someone on coding thought that it possibly left a weakref to the slime it was still attached to.
