### ISSUE TITLE
Cybernetic Heart becomes a Ordinary Heart when inserted and removed from a patient with a cursed heart.

### ISSUE THREAD

**Issue by TerryTehCoder** [BeeStation/BeeStation-Hornet#6951]
## Reproduction:

Unsure:

1. Remove Cursed heart from patient.
2. Insert Cybernetic Heart.
3. Remove Cybernetic Heart.
4. Cybernetic heart now has changed Sprite and Functionality, but keeps its description.

-Patient with a cursed heart. Cursed heart removed during revival.
-Cybernetic heart inserted and taken out.
-Cybernetic heart now has the sprite for a Ordinary Heart, the description of a cybernetic heart, and can be Squeezed to beat again like a Heart. 

<img width="590" alt="HeartBug" src="https://user-images.githubusercontent.com/78599370/170585897-77fa0553-a77d-4921-b60e-2dba1cfe42cb.png">
<img width="188" alt="Heartbug2" src="https://user-images.githubusercontent.com/78599370/170585916-fbf10acf-05e1-4a6d-bb90-a3b3a00e3d0e.png">

**Comment by TerryTehCoder** [comment]
As a side note, I'm unsure if the cursed heart is related to this issue at all. 
I've not tried to reproduce it asides this round in which I saw it.

**Comment by blackwolf602** [comment]
Had a similar situation where a virus was going around causing the cursed heart, when printing and replacing the hearts they were as you described
