### ISSUE TITLE
Incorrectly conjugated "has"

### ISSUE THREAD

**Issue by dragomagol** [BeeStation/BeeStation-Hornet#6959]
Issue reported from  Round ID: 38355 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

![image](https://user-images.githubusercontent.com/66640614/170815035-3c481b4f-8909-4acb-894d-2c0ffc4db518.png)

**Comment by DatBoiTim** [comment]
Can you specify where the error is in the screenshot?

**Comment by dragomagol** [comment]
"They has a robotic right arm"

**Comment by DatBoiTim** [comment]
Alright. Issue addressed. Please wait for a merge.
