### ISSUE TITLE
Clown soundsynth is inconsistent

### ISSUE THREAD

**Issue by GoatMonarch** [BeeStation/BeeStation-Hornet#697]
## Round ID: 
Depends. It mostly originates from you having a new byond platform and using the non-base game sound files. Like the cheer, clap and kawaii option.

## Testmerges:
Really old one, likely from #9 having issues sharing the sound files.

## Reproduction:
Having a newly installed byond client, will make you unable to hear; laughing, clap, kawaii and yeet.
I've experienced this on two seperate computers, two months betwen eachother. One on the byond version back two months, one on the latest version.

To test this out you probably need to empty your byond cache, or reinstal byond.
Making it clear, explosion, bwoink or honk has always functioned no issue.
Playing for longer makes the issue dissapear by itself after a handfull of rounds.

My guess is the sound files either are not being downloaded correctly, or are not located correctly.

**Comment by yorii** [comment]
Can't reproduce this issue, it has likely been fixed? Can you confirm you're still having issues?

**Comment by GoatMonarch** [comment]
I've yet to experience it, but I suspect it could different for newer players. The newest sounds from the latest synth update have not caused any issues though. Keep it closed, but some people might report simmilar issues in the future.
