### ISSUE TITLE
Lavaland should use a shared, immutable atmosphere like space.

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#6988]
Lavaland should use a shared immutable atmosphere like with how space works.

**Comment by Rukofamicom** [comment]
This seems like it would be simple enough to tackle

**Comment by Rukofamicom** [comment]
After starting work on it, I want to ask why this is necessary now. The planetary atmos system seems to handle the issues lavaland atmos used to cause exceptionally well on its own. 

I wasn't aware this had been implemented, but see for yourself, by video end the atmos had reset entirely.

https://user-images.githubusercontent.com/9547572/171322009-9865cfbf-8a57-4c7c-a2c4-43d4f240fae0.mp4

**Comment by PowerfulBacon** [comment]
Less need to waste time processing atmos updates on a planet that shouldn't be changing its atmos
