### ISSUE TITLE
Unable to speak or hear after taking a floor pill. (Not deafness or ear damage)

### ISSUE THREAD

**Issue by Chirynnn** [BeeStation/BeeStation-Hornet#6992]
## Reproduction:
 I ate a floor pill which contained 13u of Quantum Medicine. I could not hear or speak from then on, no comms, emotes only with the me command. I could see the chat bubble on anyone, but that's it. It kept happening after the medicine ran out too, I had no reagents, no damage, no mutations because I took 50u of Mutadone, I ahelped this and it got marked as an IC issue for whatever reason. I'm pretty sure it's a bug.

**Comment by nednaZ** [comment]
This appears to have been broken by #6558, I had actually fixed this myself in #6424

**Comment by Pirill** [comment]
> This appears to have been broken by #6558, I had actually fixed this myself in #6424

I'm not _entirely_ sure this is related. I've had it happen to me randomly once before with nothing able to fix it and I don't usually take floor pills. I've also seen someone else mention the same bug recently so /shrug.

**Comment by EvilDragonfiend** [comment]
It's somehow merge conflicted with your PR. sorry, I will fix it.
