### ISSUE TITLE
Oozelings take damage from water while in full hardsuit

### ISSUE THREAD

**Issue by VickiMorris** [BeeStation/BeeStation-Hornet#6997]
Issue reported from  Round ID: 38443 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

Suffered from bloodloss and de-limbing from being sprayed with a fire extingisher while in a full hardsuit with internals on, unsure if this is intentional or not for oozelings.

**Comment by etherware-novice** [comment]
i think this was fixed already
