### ISSUE TITLE
Borgo relink wire not working

### ISSUE THREAD

**Issue by Mat05usz** [BeeStation/BeeStation-Hornet#7019]
Issue reported from  Round ID: 38497 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

I've seen it happen several times:

- Late join as AI
- Have a borgo that was there earlier
- Tell robo to link it to me
- Apparently it's impossible?

**Comment by St0rmC4st3r** [comment]
You sure robo was pulsing it, not cutting and mending?

**Comment by Liidero** [comment]
I was the RD that round I'm pretty sure (except if we just happened to have the same bug occur on the same day) and was watching the interaction. I told the robo to pulse the wire. The borg said that the robo has been pulsing it a lot and got it working (it actually wasn't working still). We had to dismantle the whole borg and rebuild it to fix it.

**Comment by blackwolf602** [comment]
Had a similar round where robo was trying to link a borg but couldn't so I attempted and could get it done either

**Comment by Mat05usz** [comment]
> You sure robo was pulsing it, not cutting and mending?

I am not, however I've seen it happen few times with different people? Maybe they were all doing it wrong
