### ISSUE TITLE
Exploration NPC Encounters

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#7022]
Currently exploration is lacking in things happening on the flights map and could use with some more interesting encounters to spice up flight.

 - NPC ship controllers that have different behaviours
   - Trader ships: Attempt to avoid combat and will flee nearby ships, will just fly between 2 random supercruise beacons. Will attempt to flee interdiction sites.
   - Pirates: Will hunt down nearby ships and interdict them. Upon interdiction, some NPCs on that ship will move towards the player ship and attack it. Won't flee interdiction sites while another ship is there.
   - Military Convoy: Will move between 2 random beacons, will not interdict or attempt to flee. Will attempt to leave interdiction sites to continue their mission. Strongly armed but good equipment if successful.
 - NPC ship controllers applied to some non-flyable ships that spawn randomly on the map
 - NPC ship controllers only run if there are living mobs on the ship (Someone to actually fly it, once you kill everyone it will stop doing stuff).

**Comment by snek-with-tophat** [comment]
Maybe add a ghost spawner or 2 to those ship while they are on the same zlevel as players, similar to how they do it on NSV.
NPC combat isn't particularity challenging if you know what you are doing.
