### ISSUE TITLE
Medical Injury System

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#7023]
## Ideas

Make medical more interesting and healing slightly more complicated, but at the same time making all forms of damage extremely difficult to heal.
Make taking repeated damage and getting into combat often more and more punishing.

## General Spec

 - Injury datum that defines damage and damage type
 - Injury datums can be applied to a mob (For humans this would have to apply to limbs?)
 - Damage is dont through injuries instead, when damage is applied an injury is added to the list of injuries and the cached damage is updated.
 - Injuries can be unique (Toolbox hit damage should be a seperate injury for each hit)
 - If not unique, the extra damage will be added onto an existing injury (Slowly building up damage, for example from heat or pressure damage)
 - Injuries have 3 types: Minor, Major and Critical.
 - Minor injuries can be healed with simply medicine (Kelotane etc.) and bruise packs / ointment.
 - Major injuries require surgery to heal (Tend wounds) or some more advanced medicine that is more difficult to create, harder to distribute or has more negative downsides.
 - Critical Injuries require some more advanced surgery to heal.
 - When an injury is healed, a 0 damage injury will exist for some time (scars?). Taking more damage while these are active could result in the damage being worse.
 - Initially, if a mob has no injuries it will recieve mostly minor injuries (Some stuff like guns or energy swords could go straight to major due to being high damage).
 - If a mob takes minor injuries while other minor injuries are applied, it may become a major version of that injury. This includes if 0 damage injuries/scars are applied.
 - If a mob continues to take damage with some number of major injuries on that limb/mob then the injury may become a critical injury.
 - If a limb is destroyed with critical injuries, it cannot be healed and requires a full replacement.
 - Armour will lower the injury level of incoming things. For example, a gunshot may apply a major injury to someone without armour, however when shot at a nukie with 60 bullet protection, the bullet protection will lower the injury down to a minor injury.
 - This should probably only apply to burn/brute damage due to the nature of it.
 - Calculating damage should never have to iterate over all injuries, some number on the body should be added and subtracted as and when they are added, meaning it is always in sync.
 - The med analyser / examine might need to be changed to accomodate the injuries. Display something like:
**Head (34 damage)**
Burn (10)
Burn (4)
Cut (6)            //The minor version of sharp damage
Laceration (8)  //The major version of sharp damage
Bash (6)
**Chest (No damage)**
Burn scar (0)
Bash scar (0)

**Comment by PowerfulBacon** [comment]
For now I will take this, although I'll probably give up halfway through the 700 proc conversions required to refactor damage to something sane

**Comment by PowerfulBacon** [comment]
God, damage application is so terrible and inconsistent almost half the stuff in the game just completely ignores armour entirely

**Comment by FriendlyContractor** [comment]
Im not exactly fammiliar with differences between our codebase and tg, but would it not be much better to port their wounds system(which i think is quite good with all the injury types and cool effects they have) instead of coding a new one from scratch ?

**Comment by PowerfulBacon** [comment]
Eh, I don't like TG's wounds as much, they have some good points but some bits I don't like and one of the most important points is the damage severity building up.

**Comment by Pirill** [comment]
Kinda like the idea overall. Main thing for me is to make sure there's some more variety in terms of injury treatment, which is the main thing I liked about TG wounds. (That, and breaking people's limbs)

**Comment by EvilDragonfiend** [comment]
Put weapon types more like D&D system does.
> Punch, stool, wrench...: Blunt type
> Laser Scalpel, Esword, cooking knife...: Slash type
> Most bullets, Standard Scalpel, Spear...: Pierce type

It should give different injuries based on which flag they had.
