### ISSUE TITLE
Artifacts have a chance of thanos snapping you out of existance.

### ISSUE THREAD

**Issue by DemonOfHatred** [BeeStation/BeeStation-Hornet#7024]
Issue reported from  Round ID: 38518 (BeeStation Sage - Roleplay)

Reporting client version: 514.1584

Was just doing artifacts, when we picked up a sentient artifact, and it activated snapping us out of existance. it was as fast as admin deletion and effective too.

Spills-The-Blood

**Comment by ivanmixo** [comment]
>Doesn't list the testmerge that caused this

**Comment by DemonOfHatred** [comment]
im just a player my guy

**Comment by Mat05usz** [comment]
> Doesn't list the testmerge that caused this

I mean, it's pretty obvious innit

**Comment by PowerfulBacon** [comment]
> I mean, it's pretty obvious innit

Not really considering the testmerge completely replaces artifacts with artifacts.

**Comment by DrDuckedGoose** [comment]
Addressed: https://github.com/DrDuckedGoose/BeeStation-Hornet/commit/78cdc6e4e8365143e928515c3023f8d257ac0b0c
