### ISSUE TITLE
ERT spawn should use backup human

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#7044]
The ERT spawn should use the backup human name.

**Comment by mcmeiler** [comment]
You get an option to enforce human authority. Make it use backup human with that setting enabled, but keep peoples' names for the rest - people want to play their characters.

**Comment by PowerfulBacon** [comment]
Yea, but people's characters existed in the round already.

**Comment by ItsTisme** [comment]
I do want to play as my own character, maby pref option to enable it if you want it?

**Comment by AnCopper** [comment]
> I do want to play as my own character, maby pref option to enable it if you want it?

The obvious issue is spawning in as a character that's already a crew member of the station.

**Comment by PowerfulBacon** [comment]
Your character should be your character on the station, not a member of CC at the same time

**Comment by mcmeiler** [comment]
And what if people observed? Their character wouldn't be a part of the station

**Comment by Oscari-pog** [comment]
Why are we even discussing this
Onstation characters should never be used for a CC role, it doesnt matter if they observed. This even makes sense from a RP perspective.

**Comment by PowerfulBacon** [comment]
> And what if people observed? Their character wouldn't be a part of the station

Well, they aren't spawning in as their character, they are spawning in as an elite response unit that comes directly from CC. If anything the characters should be fully randomised rather than their default characters

**Comment by EvilDragonfiend** [comment]
I would want to put `backup species name` along with `backup human name`, so that you can use different name at your species.
