### ISSUE TITLE
moving conveyor belt bug?

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7047]
## Reproduction:

it's really difficult to tell...
there was a conveyor belt item that moves itself to west. It's not even placed.
when I picked up it, it got out of my hands, and moves to west again.
I reported it to mod(megaddd), he had no idea what's going on, and soon it was disappeared.

**Comment by MNarath1** [comment]
First was there a conveyor belt active in the area? Second was the item on a coveyor belt at least once? (An active one)

**Comment by EvilDragonfiend** [comment]
1. I am not sure, but I remember there were placed belts.
2. There were no items, I think, the room was conveyor belts with throwing stars room, but there was no item moving(I believe so), but disposals weirdly made noise.

**Comment by EvilDragonfiend** [comment]
and the weird belt item was near the room, not in the room. I am not sure if they're related even.

**Comment by MNarath1** [comment]
Sadly i can't really get much from this then if we had the object in a live round behaving that way i could walk someone trough in finding out what is causing that movement (someone with admin rights) but now its a guessing game just one last was this in maint on delta near lower engineering and (just maybe engineers decided to build a singu?)
