### ISSUE TITLE
Obsessed received conflicting information about target 

### ISSUE THREAD

**Issue by 4rchibald** [BeeStation/BeeStation-Hornet#7057]
## Testmerges:

[#6966: 'Revert "Character-based gear loadouts"' by PowerfulBacon at commit f52a7c3238](https://www.github.com/beestation/beestation-hornet/pull/6966)

## Reproduction:

As you can see on the screen I received conflicting informations about who I am obsessed about, notes claimed it was Walter Field while information in status tab told me to stalk Toast. There's also moodlet about Toast but to be fair I'm not sure if it is related to obsession or just coincidence that it mentioned toast. 

![obsession](https://user-images.githubusercontent.com/54917446/173185944-719f0189-cf65-4a68-84e5-644918e119c6.png)

**Comment by Mails-z** [comment]
Not a bug this is how obsess objective work, you kill your victim at the end

**Comment by Mails-z** [comment]
You are a sadistic Yander
