### ISSUE TITLE
Space dragon can chomp itself to death?!?!

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#7058]
## Reproduction:

1. be dragon
2. chomp self??
3. die
![image](https://user-images.githubusercontent.com/10366817/173187547-00cd6441-67a5-474f-9b7e-6d2553c4e2ae.png)

Also you can get objective to assassinate someone who is:
- yourself
- already dead

Basically: this entire role hated me and it was my first time playing it

**Comment by ToasterBan** [comment]
I don't see the issue, every simplemob which deals damage hurts itself when clicking itself

**Comment by Dejaku51** [comment]
everything can damage itself, humans can also hit themself

**Comment by itsmeow** [comment]
I was robbed of my role because i accidentally clicked myself, it's hard to roll dragon, I really think this is an issue.

Also, I got objective to murder that was contradictory in TWO ways

**Comment by itsmeow** [comment]
At least make the dragon do SIGNIFICANTLY lower damage to itself, because I literally died from one click

**Comment by Dejaku51** [comment]
> At least make the dragon do SIGNIFICANTLY lower damage to itself, because I literally died from one click

because you already damaged yourself (You feel a powerful shock...)

**Comment by itsmeow** [comment]
Hm. It's not very clear when you take damage as dragon, there's no red outline like as a player character.

**Comment by RDS88-beeman** [comment]
Also, the "contradictory" objective is just to keep the body you once were dead.
It's basically free. The role loves you.

**Comment by RDS88-beeman** [comment]
> Hm. It's not very clear when you take damage as dragon, there's no red outline like as a player character.

Admittedly this is true. You can see your current health as a % in the status screen, though.

**Comment by itsmeow** [comment]
bleh, guess this is more of an ingame issue.
