### ISSUE TITLE
Medibots will never heal again if you move away from it mid-heal

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#7059]
## Reproduction:

Title. This has been a long standing issue, POSSIBLY since #5760 but I can't say for sure. Currently the only fix is to turn the medibot off and on again, which will fix the behaviour until someone moves out of range again. This is a consistent issue regardless of other circumstances as far as I can tell.

**Comment by williamcll** [comment]
Oddly enough this was fixed for awhile but some PR made it unusable again.

Occurs on NSV as well.

**Comment by williamcll** [comment]
Wait why is this problem back again?

**Comment by itsmeow** [comment]
It was never gone, supposedly
