### ISSUE TITLE
[Bounty] Space Mining Machine

### ISSUE THREAD

**Issue by jlsnow301** [BeeStation/BeeStation-Hornet#706]
I'm tied up with school and can't decipher the ore network for materials.
Thus, the ($50) request:

A craftable machine that requisitions a small amount of all materials over time and sends them over the network. An automatic, but slow ore refinement machine. 
The theme behind this was that it creates them out of bluespace or is mining nearby asteroids, and provides some income of materials. It requires only power to run, and functions as a replacement for the undoubtedly dead or missing miners that Bee has every round. This prevents low-pop and new miners from ruining the round of three other departments (or more).

My thoughts on the balance were this:
Iron: 1
Glass: 1
Copper: 0.7
Silver: 0.7
Gold: 0.7
Plasma: 0.5
Titanium: 0.3
Uranium: 0.3
Diamond: 0.1
Plastic: 0.1
Bluespace: 0.1

Tickrate: Trickling in at what one brand new miner would provide

**Itemized list of requested items:**
One machine board to build space miner.
One space mining machine that functions as above.
[optional] upgradeable parts increase total gain.
[optional] interface that requires fine tuning to optimize output, ie solar array directional output

edit: I don't know why beebot knocked off the payment on this

**Comment by St0rmC4st3r** [comment]
Hm. This thing may be for situations when all the miners are complete noobs. If you have at least one good miner, you will have so many materials that you can just shove them up your ass because you have already done all the other things you could with them.

**Comment by Kerbin-Fiber** [comment]
I'm going to start *looking* into this, but probably won't be able to pull it off

**Comment by MarkSuckerberg** [comment]
I didn't even know this was a thing with a bounty, throwing myself at this immediately

**Comment by Kerbin-Fiber** [comment]
u r welcome

**Comment by jlsnow301** [comment]
I’d love to see this done. While we’re here, going to add plastic to the resources generated. The passive cargo income pull request (now closed) might provide a similar format to how this would work, using proc to add to the ore silo - I don’t know. The ore network seemed like peak messy code

**Comment by qwertyquerty** [comment]
I don't especially like the idea of more automation, making miners even more useless.

**Comment by jlsnow301** [comment]
Definitely balance intensive. The idea isn’t to replace them- any miner that isn’t an idiot should double the outcome. Coupled with it requiring someone to build one (Ha). If there’s even a single miner I’m assuming they wouldn’t bother. The tick rate + building requirement should mean that science “might be able to build a few machines” not “every department gets a Durand”

**Comment by eLeCtrOssSnake** [comment]
Just making a remark, I think this is a bad idea. I am not approving this, we are ripping miners.

**Comment by ike709** [comment]
Mark hasn't touched this in a month and a half and he's asked me about doing a different bounty so I'm calling dibs.

**Comment by francinum** [comment]
Well this was a fucking mistake.

**Comment by jlsnow301** [comment]
> I'll have a companion PR out soon with a solution for the problem.

well this was a fucking lie
