### ISSUE TITLE
Temporarily remove/comment out romerol and his grace

### ISSUE THREAD

**Issue by ItsTisme** [BeeStation/BeeStation-Hornet#7061]
These as it stands right now will get you banned in most cases. Propably good idea to comment them out until a better solution can be made.

**Comment by ItsTisme** [comment]
Locking these items to only antags with murder bone objectives is prefered and better solution. so if that can be done that also solves this issue

**Comment by PowerfulBacon** [comment]
Or bring back the exception for these items, they are rare and fun to experience
