### ISSUE TITLE
Conveyor belts move stationary objects

### ISSUE THREAD

**Issue by 4rchibald** [BeeStation/BeeStation-Hornet#7066]
## Round ID: 
All of them

## Testmerges:

In rounds I noticed it [#6966: 'Revert "Character-based gear loadouts"' by PowerfulBacon at commit f52a7c3238](https://www.github.com/beestation/beestation-hornet/pull/6966)

## Reproduction: 
Conveyor belts are now able to move stationary objects. Few days ago I was building a loop in bar and they ripped apc, air alarm, lights and light switch from the wall (devices didn't break, they remain their functionality) . Today I went to observe a round and I noticed that in maint room with disposals tables were being thrown

![conveyortables](https://user-images.githubusercontent.com/54917446/173367924-5be95999-b509-4b97-abec-5de84884cd79.png)

I wasn't playing for a while so I have no idea when this started and to what PR it is related, maybe there was something tweaking conveyor belts or maybe it came with movement loop rework, no idea. 
Only other recently reported conveyor bug was #7047 but it is very different so I can't tell if those issues are connected, but maybe it will help with finding the source of the problem.

Ability to move APCs and Air Alarms has potential to be used for serious grief. While building a line of conveyor belts is hard to hide from people it is not impossible, especially since you would just need to lead them to disposal chute, that way power and air settings can be tweaked to mess with engine, gravity and tcomms while engineers can't do anything about it because you are not able to build new ones if original ones are not deconstructed

**Comment by MNarath1** [comment]
so it ignores anchored var for objects? thats indeed not right

**Comment by oo7craigmc** [comment]
I know this is stale, but I'm just bumping this because I still see this happen occasionally. I've seen plastic flaps and blast doors move in Cargo, spacing the area. I've even seen a really weird effect where the light on a tile itself seems to be moved, making a tile lighter or darker.
If this needs to be a new issue, let me know. I'm not a coder and am not super familiar with Github.

**Comment by MNarath1** [comment]
> I know this is stale, but I'm just bumping this because I still see this happen occasionally. I've seen plastic flaps and blast doors move in Cargo, spacing the area. I've even seen a really weird effect where the light on a tile itself seems to be moved, making a tile lighter or darker. If this needs to be a new issue, let me know. I'm not a coder and am not super familiar with Github.
> 
> Here's a screenshot that someone provided on the Discord of it happening: ![image](https://user-images.githubusercontent.com/48850629/190392436-1de0eda2-08ee-424e-b816-a09c1ebfd423.png)

i was a bit inactive for a while but i will take a look at it in then next week i think i know the area were the issue is

**Comment by MNarath1** [comment]
Tested this but i cannot reproduce like the tables above etc

**Comment by MNarath1** [comment]
No blastdoors and plastic flapd are fine too dunno where this comes from

**Comment by itsmeow** [comment]
Fixed by #7832
