### ISSUE TITLE
weird delay bug

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7070]
## Round ID:
around 38710

## Reproduction:

I think we have very weird delay bug. I can't exactly tell how it is...
- when you climb up on a table(or operation table), round time is frozen and you can't likely walk even if enough time is passed. (I was stopped like 60 seconds over)
- In that case, if you go rest, you can't get up. at 5% progress gauge, it's cancelled and it says 'you failed to get up'
- in that time, other people reported that they can't get up (they were resting too)
- once round time goes, the weird freezing issue solved.

```
OOC: EvilDragonfiend: people, have you ever noticed some weird delay bug? like that you can't get up for 30~60 seconds after climbing up a table or resting
OOC: Bebes_Kidz: Evildragonfiend
OOC: Bebes_Kidz: SAME
 OOC: Chiryn: yes sometimes @evildragonfiend
OOC: Bebes_Kidz: I had that happened last round
OOC: Sumianhi: Yes Ignites.
OOC: Bebes_Kidz: I'm not even sure what causes it
```

--------------------

![image](https://user-images.githubusercontent.com/87972842/173547635-0912acfa-5322-4ae9-8320-70585e799a46.png)

this might be related
my character has no name on examine
arrival shuttle deson't dock
my chat name tells 'my name (as my name)'

**Comment by PowerfulBacon** [comment]
Likely due to timers freezing due to MC freezing as a result of something that I'm not sure of the cause

**Comment by EvilDragonfiend** [comment]
at some round(can't remember), pod random drop didn't work, and I think this is related also.

**Comment by EvilDragonfiend** [comment]
![image](https://user-images.githubusercontent.com/87972842/173879243-9aa50a9a-eece-437e-b8b7-afc416f7ba8a.png)
Might be a clue to track the issue - time and round.

**Comment by PowerfulBacon** [comment]
This is something to do with atmos

**Comment by Coding-Grape** [comment]
This is time dilation/server load fuckery I think, not really a bug as it's not linked to table stun. it's *basically any timer*, including slip timer
