### ISSUE TITLE
Zombie powder fakedeath spams *deathgasp

### ISSUE THREAD

**Issue by OverwatchVoice** [BeeStation/BeeStation-Hornet#7082]
## Round ID:
None (discovered in private testing)

## Testmerges:
None

## Reproduction:
Inject a sufficent ammount of zombie powder into a mob. After the fakedeath treshold, the affected mob will spam *deathgasp on each lifetick.

**Comment by Rukofamicom** [comment]
There is a fix for this already included in #6759 

If someone wants to make a separate fix, change line 193 of toxin_reagents.dm to this
`if(M.getStaminaLoss() >= 145 && !HAS_TRAIT(M, TRAIT_FAKEDEATH))`
