### ISSUE TITLE
AI can see Syndicate Hud Icon On Start (Quick Log Dive to Confirm)

### ISSUE THREAD

**Issue by Programs-The-Station** [BeeStation/BeeStation-Hornet#7088]
Issue reported from  Round ID: 38788 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

Started this round... and found the robo.... 
![image](https://user-images.githubusercontent.com/100493881/174421822-089fdfa6-ec36-4499-aca8-a3f378ddc0c4.png)

And in fact.... round end....
![image](https://user-images.githubusercontent.com/100493881/174423058-7b6fb7f7-5830-41d5-917c-e449b490aa7a.png)

As far as I'm aware, I did nothing out of the ordinary. Turned on Loud Comms, spoke a few times, *shonk 'ed, and most importantly DID NOT TURN ON CAMERA SENSORS until after I saw the balloon. They were not on when I saw the Logo the first time.

**Comment by Programs-The-Station** [comment]
Just noticed the robo bought a syndicate balloon. Not sure if they purchased it round start or not. That might explain the indicator, and would be a quick log dive.

**Comment by BrumalLake** [comment]
it's clearly a balloon mate antag is in the right corner virus is left the balloon not in either corner

**Comment by mcmeiler** [comment]
Hi, the headmin who answered your ahelp here, I was only on for something quick and never even left the lobby screen.

That's just the balloon.

**Comment by Programs-The-Station** [comment]
Perfect, I'd never seen the balloon before, and didn't expect it to come out less than 30 seconds into the round. Startled me.

Closing now.
