### ISSUE TITLE
Dark purple warping rune twice as likely to spawn uranium.

### ISSUE THREAD

**Issue by ZombieNub** [BeeStation/BeeStation-Hornet#7101]
Apologies in advance for the somewhat unusual bug report.

## Issue:

When the dark purple rune is spawned, it is initialized with a list of materials. This list of materials has `/obj/item/stack/sheet/mineral/uranium` listed twice:
https://github.com/BeeStation/BeeStation-Hornet/blob/cc1b66f28188bf1bd792102ae004b662885ba672/code/modules/research/xenobiology/crossbreeding/warping.dm#L339-L346

This gives uranium a 20% chance of spawning, whereas all other materials have a 10% chance of spawning. Though overall inconsequential, I do believe this is an accident and should be fixed.

**Comment by EvilDragonfiend** [comment]
It's fixed, and it looks you forgot to link your PR to this.

try this format next time:
`closes #7101` or `fixes #7101` in your future pr. then it will automatically close your issue post once it's merged.

**Comment by ZombieNub** [comment]
Oh, sorry. Thank you. I will do that next time.
