### ISSUE TITLE
Hellwater Mix-up in Silver Extract

### ISSUE THREAD

**Issue by FortSumter** [BeeStation/BeeStation-Hornet#7121]
Issue reported from  Round ID: 38913 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

A xenobiologist used silver slime extract to make food and drinks. One of the drinks is a "Flask of holywater."

It does not contain holywater. It contains hellwater.

I found this out seconds before round end when I attempted to drink the flask and immediately bursted into flames as if I had touched the sun itself.

And so the bug in this case is either a) that the flask is miss-named as it certainly does not contain holywater or b) that the xenobiologists should not be able to create such an insanely dangerous chemical with a extract meant to create (questionably) edible food and drink.

**Comment by BrumalLake** [comment]
![image](https://user-images.githubusercontent.com/85033680/175757957-a7d07d3c-c5ab-4418-b721-474f532722ef.png)
read desc

**Comment by FortSumter** [comment]
I did read the description. It gave me the description of the normal flask when I examined it.
