### ISSUE TITLE
Endless Meat

### ISSUE THREAD

**Issue by Chumbl** [BeeStation/BeeStation-Hornet#7123]
Issue reported from  Round ID: 38927 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

As human, became full on food. Drank a potion and became a skeleton, carrying over full status. Step inside lipid extractor and encounter endless extraction. Exiting at will is available, but after exiting full status will still be maintained. Cycle is able to be repeated since full status does not go away.

**Comment by Dejaku51** [comment]
Will get fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/7109
