### ISSUE TITLE
Remove "Yiff In Hell" decal

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#7132]
I got noted for saying "clean the yiff" on common instead of "clean the yiff in hell decal" and I am now annoyed this ever happened and want it removed for "ERP". Funni not allowed.

**Comment by lordScrubling** [comment]
how code this?

**Comment by itsmeow** [comment]
No idea delete file? I did some searching in the repo and couldn't find it.

**Comment by itsmeow** [comment]
In all seriousness though, this decal is super LRP and also causes problems with the ERP policy and should've been removed a long time ago.

**Comment by PowerfulBacon** [comment]
It seems like a very weak note, I'll bing it up with the admins and see what they have to say it.
I am fine with removing the decal though, it is very obnoxious considering it is a multi-tile decal, or at least multi-tile decals should take like 1 second to spray.

**Comment by itsmeow** [comment]
The note isn't high severity and I do understand that it's a bit LRP to say it that way, so I'm not too worried about it, but I appreciate it.

**Comment by itsmeow** [comment]
Found it
https://github.com/BeeStation/BeeStation-Hornet/blob/master/icons/effects/96x32.dmi
