### ISSUE TITLE
Slime can pas trough closes valves while crawling through the atmospheric network

### ISSUE THREAD

**Issue by Mails-z** [BeeStation/BeeStation-Hornet#7139]
Issue reported from  Round ID: 38965 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

![image](https://user-images.githubusercontent.com/72167130/176040541-3b2f72f7-a600-4b0b-b070-647162b0e9dc.png)
As a sentient slime, I pass throw that close valve without any trouble.

**Comment by mystery3525** [comment]
This applies to anything ventcrawling, and they can also go through the incorrect pressure differential in pumps too.
