### ISSUE TITLE
Lavaland syndie turrets will shoot at humans inside the base

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#7142]
## Round ID:
38977

## Testmerges:
None I think

## Reproduction:
Spawn as lavaland syndie -> give mutadone to one of the test monkeys -> turret shoots at it despite it being inside, and likely damages the base, causing hull breaches and destroying machinery

Example:
![scrnshot1](https://user-images.githubusercontent.com/86113712/176208266-f9eeeaba-1530-4c0a-a6bd-a147d13985d2.png)

**Comment by DingleFlop** [comment]
Holy shit, is this the first person to ever actually test diseases on Syndie Lavaland...?
