### ISSUE TITLE
Older GUIs no longer compatible with WINE

### ISSUE THREAD

**Issue by VictorVow** [BeeStation/BeeStation-Hornet#715]
BYOND 512.1488
Tested with latest WINE and Proton 4.11

Since about a week ago now upon joining the server I'm greeted with this message: 
> An error has been detected in how your client is receiving resources. Attempting to correct.... (If you keep seeing these messages you might want to close byond and reconnect)

I've found that the dropdown menus for the following GUIs no longer do anything when clicked:
- View Variables
- Create Mob/object/turf  
- Banning Panel

**Comment by Crossedfall** [comment]
All of those UI elements are basic HTML, for the most part, and haven't been touched within your given time-frame. Try clearing your BYOND cache, if that doesn't work try reinstalling Wine completely.

**Comment by Crossedfall** [comment]
No response, assuming resolved. Feel free to re-open this if you're still having problems after doing my suggested steps.
