### ISSUE TITLE
Spicy pockets are craftable when they shouldnt be

### ISSUE THREAD

**Issue by LodedDiper69** [BeeStation/BeeStation-Hornet#7153]
## Round ID:
39004

## Reproduction:

Step 1: Acquire one (1) pastry base
Step 2: Have zero (0) chili anywhere in your crafting range
Step 3: ![image](https://user-images.githubusercontent.com/101019561/176554361-dbcae6fd-346d-4dfd-82bf-e9bdffca6a36.png)

**Comment by BrumalLake** [comment]
did it work

**Comment by LodedDiper69** [comment]
It did.
