### ISSUE TITLE
Balloon alerts are too large, too long and need general improvements (QoL)

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#7164]
Use any balloon alert sending item, such as a gun and change fire modes
The balloon alert will completely cover your character.

The animation needs a complete overhaul, a simple fix would be to have the alert spawn above the head to begin with, but it could also be changed to have a single balloon alert displayed at a time and have it as a static position above the head where it fades in, then fades away.

This mainly affects guns and miners.

In addition to this, balloon alert messages have way too much text, caused by https://github.com/BeeStation/BeeStation-Hornet/pull/6824 which should be reverted. If there is too much text, they become difficult to read and end up just being pointless wastes of screenspace.
Weapon firing modes literally just need to display "STUN", "KILL", "DESTROY" or whatever above the head for a short amount of time to indicate the mode you are on.

An example of too much text:
![image](https://user-images.githubusercontent.com/26465327/176957970-2487e073-8de5-4d93-82d0-9de12131975d.png)

This affects miners with the *click* of the gun.
![image](https://user-images.githubusercontent.com/26465327/176958028-95ce756e-3d20-424f-a1f4-d40018bcb2f3.png)

There are some examples of things that really should not use balloon alerts: For example, aiming component uses a balloon alert to represent speech, when in reality it should just use regular speech.

![image](https://user-images.githubusercontent.com/26465327/176958116-5ab3dc17-8a5a-46e1-98d0-539d1b474285.png)

**Comment by ivanmixo** [comment]
Thing is most of these also appear in chat. That's why I made them how they are. It just saying "STUN" in chat would be fucking terrible. The actual issue here is that they're so spammable, should probably limit them to one at a time so they don't overlap. 

...or just make the text that appears in chat seperate from bubble alerts. I frankly hate these.

**Comment by benbot16** [comment]
When I originally ported over aiming I got told to change it from speech to a balloon alert, but I can change it back if you want.

**Comment by itsmeow** [comment]
This can be closed now, right?
