### ISSUE TITLE
Braindead IPC's spam deadchat with revive messages

### ISSUE THREAD

**Issue by RDS88-beeman** [BeeStation/BeeStation-Hornet#7186]
## Reproduction:
Spawn an IPC.
Deliver the IPC 200 brain damage via your preferred method.
Deliver the IPC some brute damage, then heal with a welder.
The IPC will process exactly one life tick, then die again as intented.
The problem comes with the fact the IPC will still say the forced rebooting messages, but into deadchat.

**Comment by etherware-novice** [comment]
im pretty sure this is already fixed, @PowerfulBacon can you close this

![image](https://user-images.githubusercontent.com/73374039/186043173-61523da7-4a8a-42c5-bda3-7e94aa1c0f82.png)
