### ISSUE TITLE
Glowsticks don't emit light

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#7188]
## Reproduction:
Apologies for the lack of information, I made this bug report after the fact. On Corgstation neither the naturally spawned glowsticks or some found inside an abandoned crate seemed to emit any light. Examining does state that they are lit.

![image](https://user-images.githubusercontent.com/29107291/177056365-d75aa1a5-64aa-4150-b3df-578cc58246df.png)

**Comment by itsmeow** [comment]
Did you crack the glowstick by using it in hand?

**Comment by Pirill** [comment]
I believe so? Unless the glowsticks are meant to start lit in maintenance (frankly forgor :skull:) but examining them both (and the sprite) shows them as lit.

**Comment by itsmeow** [comment]
Can confirm, Corg's spawned glowsticks do not emit light.
