### ISSUE TITLE
Unusable chest drawer on Corg

### ISSUE THREAD

**Issue by Leshens** [BeeStation/BeeStation-Hornet#7215]
Issue reported from  Round ID: 39130 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583
Can't use chest drawer in QM office on Corg
![obraz_2022-07-06_213900264](https://user-images.githubusercontent.com/75252260/177629576-52811f18-6b7c-40c2-9561-a8f8f8b10318.png)

**Comment by JukeJukestar** [comment]
there are a few small issues like this.
There are also no clothing lockers in dorms, so getting a bandana or colored jumpsuit just isnt possible
