### ISSUE TITLE
overlays that added by `add_overlay()` proc aren't removed of its object on `cut_overlay()`

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7218]
`add_overlay()` proc doesn't remove its object on `cut_overlay()`

This means the overlay object is perma remained in the game memory as a garbage.

**Comment by MNarath1** [comment]
> `add_overlay()` proc doesn't remove its object on `cut_overlay()`
> 
> This means the overlay object is perma remained in the game memory as a garbage.

Not really why would you think that the only time i see a new object beeing made is a image under build-appearance_list and even then it doesn't even forward  the reference of the image object but only its apperance towards the calling proc/ a list with apperances but in no cases do i see it not handling the add_overlays /remove overlays list.

**Comment by MNarath1** [comment]
that gets called when the overlay subsystem fires.
