### ISSUE TITLE
Invisible mobs are deaf (including revenants)

### ISSUE THREAD

**Issue by Tyranicranger4** [BeeStation/BeeStation-Hornet#7219]
## Reproduction:

Be any type of mob with their invisibility variable set as anything higher than 0. Whether that be through VV, use of the invismin verb, or natural occurrence in the case of revenants. You will be unable to see any form of speech, although visible emotes can still be seen as normal.

**Comment by Tyranicranger4** [comment]
Nevermind... this only seems to be a problem when tested on admin spawned humans? What?

**Comment by Tyranicranger4** [comment]
Guess I'm going to close this until I can make sure it's an actual problem that happens normally.

**Comment by itsmeow** [comment]
Duplicate of #7053
