### ISSUE TITLE
Morph attacks whenever it uses Morph menu, rendering it effectively impossible to do stealth

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#7221]
## Round ID: 

39151

## Reproduction:

When playing Morph, whenever using the "morph menu" where you digest, disguise as and drop items, you automatically attack whenever you select something in the menu. This will always give you away when trying to be stealthy.

Because morphs are so rare it is hard to pin down when this started, but last time I played morph in August 2022 it was not yet an issue.

Additionally, the order in which "Use, drop, throw, use and throw, digest and disguise as" appear sometimes changes at random, which can make relying on muscle memory very tedious

**Comment by itsmeow** [comment]
Testing the morph, it doesn't appear to be attacking when I open the menu. Not sure what you mean. What circumstances did this occur in?

**Comment by JukeJukestar** [comment]
Stopped happening yesterday. Weird, maybe something broke temporarily

**Comment by itsmeow** [comment]
My morph refactor should fix this up anyway
