### ISSUE TITLE
it seems PR #7156 is forcing EVERYONE to wait 5 minutes and or compleatly breaking swarming type midrounds

### ISSUE THREAD

**Issue by kit-katz** [BeeStation/BeeStation-Hornet#7228]
## Round ID:

39166 and others

## Testmerges:

N/A

## Reproduction:

* in many rounds now ive noticed that some midrounds... do not show the "hireing promot"
* ive had multiple mhelps asking why they dont get the prompt either
* in this most recent shift it appeared that NO ghosts where able to enter the xeno embryos for 5 minutes compleatly ruining the xenoqueen's chances of survival
* antag spawns (larve in this case) also appear to not show in the spawners menu. leaving many of them to never hatch
* even a warden that died did not see any and mhelped weather or not sec roles are banned from midrounds
* i have died both by deathgaspin and by just normal death and both times i did not see any subequent prompts

this issue appeaars to be most obvious in swarming midrounds with multiple antags spwning all over
and some antags appear to not show to ANY ghost even if none of them have died the past 5 minutes
case and point this latest shift where again no ghost entered a single ready larva for 5 minutes. and even after that it was clear that most ghosts didnt know or where able to get in

**Comment by itsmeow** [comment]
Possible cause of this bug: The timer is in the ghost's Initialize method. If you were to recreate the ghost at all (e.g., entering your body, which removes your ghost) the timer might reset.

**Comment by Miliviu** [comment]
I'll fix it, today, sorry!

**Comment by PowerfulBacon** [comment]
I'm fine with people dying having to wait 5 mins before rolling xeno. If this is preventing people from rolling after 5 minutes or if the timer is shared then something is wrong

**Comment by Miliviu** [comment]
> I'm fine with people dying having to wait 5 mins before rolling xeno. If this is preventing people from rolling after 5 minutes or if the timer is shared then something is wrong

I think one of the problems is the one Meow says, when you enter your body and leave the timer resets
I'll start testing rn!

**Comment by PowerfulBacon** [comment]
Yup, that deletes your ghost and makes a new one.

**Comment by Miliviu** [comment]
> Yup, that deletes your ghost and makes a new one. A better solution might be to use a global death list and associate it with ckey.

Big oof, hmkey, I'll do that, hopefully today!

**Comment by PowerfulBacon** [comment]
Ping me on github if you make a fix, can't merge revert until later due to config changes.
