### ISSUE TITLE
Admins lost the ability to rename tickets 

### ISSUE THREAD

**Issue by Sinestia** [BeeStation/BeeStation-Hornet#7232]
/datum/admin_help/proc/Retitle exists but is inaccessible

 Probably from the tgui conversion

 If someone's bored as fuck that might be a nice feature to have again, sometimes when you're busy with tickets you have a list and they're all described by their first message. And some players legit write messages as dumb as "CHECK THIS OUT" as their ahelp

**Comment by EvilDragonfiend** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/7113

does that happen recently? if so, might the link be related?

**Comment by Sinestia** [comment]
no, this is ancient

**Comment by itsmeow** [comment]
This is still a feature?

![image](https://user-images.githubusercontent.com/10366817/188058709-ba2fe523-702d-4e20-9d61-956bbfe3c6d0.png)
![image](https://user-images.githubusercontent.com/10366817/188058725-b1ae58ac-27c8-47f9-b5c6-f2acb3fab52c.png)
