### ISSUE TITLE
Revenant instantly dies as soon as they use EMP, seemingly at random

### ISSUE THREAD

**Issue by Oscari-pog** [BeeStation/BeeStation-Hornet#7236]
## Reproduction:
1. Be revenant
2. Use malfunction a few times (EMP ability)
3. Instantly die

**Comment by EvilDragonfiend** [comment]
how was their lifeforce when they're using EMP ability? I think they used all lifeforce by using it then instantly died.

**Comment by Oscari-pog** [comment]
> how was their lifeforce when they're using EMP ability? I think they used all lifeforce by using it then instantly died.

Revenant cant use their abilities if they dont have the essence for it. Also I had 85 which is enough.

**Comment by PowerfulBacon** [comment]
Needs more information, could be anything like atmos pressure or breath

**Comment by Oscari-pog** [comment]
> Needs more information, could be anything like atmos pressure or breath

The only thing I can note is that it happened when I was near a window. Do electrified grilles arc when EMPed?

**Comment by AnCopper** [comment]
This seems to happen near the presence of grilles/electric grilles. Maybe give revenants shock immunity?
