### ISSUE TITLE
There are two "Pastries" crafting categories.

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#7237]
Issue reported from  Round ID: 39179 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

![image](https://user-images.githubusercontent.com/29107291/178112313-26e002df-ef99-44be-8502-7334af822c15.png)

Both direct to the same menu and I think one of them is meant to be Pastas.

**Comment by itsmeow** [comment]
Spaghettis is Pastas, actually

**Comment by itsmeow** [comment]
Caused by #6263
