### ISSUE TITLE
Wielded items are broken

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#7238]
Issue reported from  Round ID: 39179 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

![image](https://user-images.githubusercontent.com/29107291/178112366-5fd18b24-c1be-4019-80d6-b2f558e22234.png)
The "Off-Hand" indicator seems to be separated from the weapon itself and can be dropped independently of the weapon (or used to attack people) and the wielded weapon gets the adjective appended each time you pick it up that way.

**Comment by PowerfulBacon** [comment]
if(!isnull(force_multiplier))

**Comment by itsmeow** [comment]
Can be closed
