### ISSUE TITLE
escaping pod random drop isn't working

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7244]
## Round ID:
39195

## Reproduction:

https://youtu.be/YNmDm7thSbI

1. Red/delta alert to escape
2. the pod is arrived at lavaland
3. now proceed to drop on a random location - but not working

**Comment by PowerfulBacon** [comment]
Hm, it should just automatically choose a landing point.

**Comment by EvilDragonfiend** [comment]
Okay, then I will keep this ticket open since other people can post another one.
