### ISSUE TITLE
Hand to hand Giving an item had take button stick around

### ISSUE THREAD

**Issue by Programs-The-Station** [BeeStation/BeeStation-Hornet#7247]
Issue reported from  Round ID: 39208 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

Custom IDs Give buttons do not go away when given hand to hand, and produce Lots of "You moved out of range of X" errors.d

![image](https://user-images.githubusercontent.com/100493881/178174932-b49e234e-abc8-484c-b73a-7deeba141c6a.png)

I've got the ID that was handed over.

Recreation: Create new custom ID. Give it to another person. That person should have the button stick around.

I tested this out with Ignites on this round, but it was not reproduceable (at least with the Same ID).

**Comment by EvilDragonfiend** [comment]
I am not sure if it's even related with the custom ID card.

**Comment by Programs-The-Station** [comment]
I didn't see it with anything else, so that's the most likely spot, but I wouldn't be surprised if it was a certified Byond moment. Either way, was annoying to have the right of my chat spammed with motion every space I moved the entire shift.

**Comment by Programs-The-Station** [comment]
Probably a certified BYOND moment. Fired up a private server with latest, and I couldn't get it to reproduce.

**Comment by EvilDragonfiend** [comment]
@Penwin0 do you have any clue about this?

**Comment by Penwin0** [comment]
> @Penwin0 do you have any clue about this?

No idea, and no clue why I would have anything to do with it

**Comment by PowerfulBacon** [comment]
This happens to everything
