### ISSUE TITLE
Corporate sofas northern facing sprite is flipped

### ISSUE THREAD

**Issue by ToasterBan** [BeeStation/BeeStation-Hornet#7249]
## Reproduction: 
1. make a corporate sofa left side facing to the west
2. alt-click it
3. notice it's flipped

**Comment by itsmeow** [comment]
@PestoVerde322 did chair PR fix this? #7547

**Comment by PestoVerde322** [comment]
now all sofas have the right direction, corp sofa for some reason had an odd orientation and so I've updated it in #7547 

![immagine](https://user-images.githubusercontent.com/75247747/188109472-c95125c4-a8c1-45bd-8748-d50aa795047c.png)

now it's the same exact behaviour as the normal sofa, so basically yeah there's no bug really.
