### ISSUE TITLE
[idea] Language needs a speices tongue type

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7261]
talking in a language needs a required tongue type.

i.e.)
Draconic/Xenomorph needs a lizard/xeno tongue
Piratespeak needs a bone tongue

Wizard/Curator/Silicon/pAI can bypass this.

if you don't have a required tongue type:
1. you can't speak that language
2. or you say like a dumb (stammering? slurring?)
3. or you have 50% chance to say a broken sentence

**Comment by JukeJukestar** [comment]
Neat idea, but only for specific languages. certain languages should be reproducable by human tongues with no issues, but ones like voltaic i can see the appeal.
This would only affect someone in case they get the tendril book or have the multilingual quirk in normal circumstances
