### ISSUE TITLE
[BUG] Selling a hollow artifact while a person is inside ghosts the person

### ISSUE THREAD

**Issue by XeonMations** [BeeStation/BeeStation-Hornet#7273]
## Reproduction:
Step 1: Get a hollow artifact
Step 2: For person one, who wants to be ghosted, go inside the artifact
Step 3: Get person two to sell the hollow artifact, while first person is in artifact
Step 4: Person one is now a ghost

**Comment by DrDuckedGoose** [comment]
Thanks for submitting.

This was addressed and fixed a while ago, Bacon just hasn't updated the testmerge version. The current commit has all the fix for this, somewhere.
https://github.com/BeeStation/BeeStation-Hornet/pull/6718/commits/5e98843d8acaca92dafa37197e600136bd3160d0
