### ISSUE TITLE
monkey can move while they're sitting on a chair/roller bed

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7275]
## Round ID:
around 39239

## Reproduction:

https://youtu.be/kc9yuPRO1Es

https://youtu.be/RSor0X0UQtI

just let them sit on those and make them angry

**Comment by Mat05usz** [comment]
I'll take this one, cause I have the fix already just couldn't force myself to record videos of it working and not breaking buckling again.
