### ISSUE TITLE
Secbot stunlock glitch

### ISSUE THREAD

**Issue by BNGP0** [BeeStation/BeeStation-Hornet#7282]
## Round ID:
39319

## Reproduction:
Sergeant at Armsky that left the armory that was bombed found me in space near permabrig and started battoning me infinitely instead of properly arresting. I was on a latice tile, beepsky was on a space tile. I was wearing an explo hardsuit.

**Comment by BNGP0** [comment]
I couldn't move or do anything, it was stunning me faster than my stamina regenerated. Maybe it is somehow connected to explo hardsuit. Maybe it's stamina protection caused at armsky to think that i am not stunned enough.

**Comment by Dejaku51** [comment]
its not a bug, beepsky has two modes, arrest and detain. arrest just stuns you and cuffs, detain stuns you indefinitely. Armsky starts in detain mode, beepsky in arrest

**Comment by zeskorion** [comment]
> its not a bug, beepsky has two modes, arrest and detain. arrest just stuns you and cuffs, detain stuns you indefinitely. Armsky starts in detain mode, beepsky in arrest

it honestly should be removed, its kinda bad

**Comment by ivanmixo** [comment]
Not a bug.

**Comment by Dejaku51** [comment]
> > its not a bug, beepsky has two modes, arrest and detain. arrest just stuns you and cuffs, detain stuns you indefinitely. Armsky starts in detain mode, beepsky in arrest
> 
> it honestly should be removed, its kinda bad

¯\_(ツ)_/¯
remove it then

**Comment by BNGP0** [comment]
> > its not a bug, beepsky has two modes, arrest and detain. arrest just stuns you and cuffs, detain stuns you indefinitely. Armsky starts in detain mode, beepsky in arrest
> 
> it honestly should be removed, its kinda bad

Yeah i was stuck in space unable to move for like 10 minutes, until the round ended, because no one could resque me. The time is not limited by anything so you can just be stunlocked forever. Sec officer batongs have charge and they need to sometimes recharge them, but a secbot can hold anyone in constant stun until some outside factors interfere them, which is highly unlikely if you managed to get into such situation.

**Comment by ivanmixo** [comment]
Still not a bug.
