### ISSUE TITLE
Arrivals shuttle cut in half 

### ISSUE THREAD

**Issue by ToasterBan** [BeeStation/BeeStation-Hornet#7284]
## Reproduction: 
wait until around an hour and a half in
suddenly see message in radio that the arrivals shuttle is damaged and needs repairs
see that it's a vacumm
refill it
see it fly away but leave half of it behind, making the entire shuttle a vacuum again

**Comment by EvilDragonfiend** [comment]
![image](https://user-images.githubusercontent.com/87972842/179392923-53e8145e-22d3-4135-9d46-c17f0b1b746b.png)
![image](https://user-images.githubusercontent.com/87972842/179392924-95ed002a-1e6e-44df-899a-f26faa508568.png)
