### ISSUE TITLE
Holoparas can use Fugu Glands

### ISSUE THREAD

**Issue by Chirynnn** [BeeStation/BeeStation-Hornet#7287]
## Round ID:
None

## Testmerges:

None
## Reproduction:

I think being able to use fugu glands on holoparas is unintended, and should be fixed

Reproducting is as follows:
1. Get a fugu gland
2. Get a holopara
3. Feed the fugu gland to the holopara

**Comment by Liidero** [comment]
Definitely unintended. Asked about it in a VC with Crossed, some admins and other people in there and majority agreed on that it isn't intended

**Comment by RDS88-beeman** [comment]
I don't think this is intended, but I think it's very cool.

**Comment by Pirill** [comment]
The size increase is a cool gimmick (and arguably a drawback), but the gland also buffs the Holopara if I'm not mistaken.

**Comment by Liidero** [comment]
99.9999% sure Fugu gland makes the mob its given to be able to punch rwalls in one hit. Make a ranged holopara, give it fugu gland and it has great melee in addition to the already good ranged

**Comment by dwasint** [comment]
This should be a bug yea it literally doubles a mobs damage aswell so guardians do like 30 a hit  basically
