### ISSUE TITLE
Xeno infection HUD breaks sometimes

### ISSUE THREAD

**Issue by benbot16** [BeeStation/BeeStation-Hornet#7297]
## Round ID:
39345

## Testmerges:
#7041 
#7285 
#7072

## Reproduction:
I haven't really noticed this myself, so I'm not able to provide that much info, but I had it reported by someone who was playing as a xeno queen in this round.
Reproduction steps:
1. Egg someone
2. Have the larva surgically removed
3. See the person later and see that they still have one of the larva icons

**Comment by benbot16** [comment]
I'll take a look at finding out what causes this, though I'm not experienced at all with per-client images so no promises.

**Comment by EvilDragonfiend** [comment]
did it happen to every egged person?

**Comment by benbot16** [comment]
> did it happen to every egged person?

unsure since someone else reported it, but I've found the issue and I'm PRing a fix.
