### ISSUE TITLE
Cant make Blank paper drink...

### ISSUE THREAD

**Issue by heepox** [BeeStation/BeeStation-Hornet#7309]
Mixing Silencer, Nothing and Nuka cola no longer creates Blank paper (drink)

**Comment by St0rmC4st3r** [comment]
@PestoVerde322 you didn't do wiki changes for #6502

**Comment by PestoVerde322** [comment]
I have updated the recipe in the wiki in accordance to this: https://github.com/BeeStation/BeeStation-Hornet/pull/6502

Now the recipe is:

- 1 part Silencer
- 1 part nothing
- 1 part Nuka Cola
- 1 part clown's tears

https://wiki.beestation13.com/view/Guide_to_food_and_drinks
