### ISSUE TITLE
Changeling reviving stasis and last resort do not work in lesser form

### ISSUE THREAD

**Issue by AdamUrgol** [BeeStation/BeeStation-Hornet#7310]
Reporting client version: 514.1583
As in title, reviving stasis does not work in lesser form (monkey). I can enter reviving stasis, but I will never wake up. After I enter reviving stasis if I try enter reviving stasis it will say we are already reviving.
This is clearly a bug. 
Last resort I'm not sure if it's a bug, not being able to use it in lesser form, or is it intended behaviour?
Wiki does not state that this ability cannot be used in lesser form, but there's a lot that wiki doesn't cover.
I prefer to report it just in case.

![changelingbug](https://user-images.githubusercontent.com/74247690/179765575-ee9d0a20-ab82-40ae-98e4-555bc3c1d73a.PNG)

**Comment by Nosnek199** [comment]
I had the unfortunate experience of never-ending stasis as well. only this time, during my stasis I was revived. The whole entire stasis process could be bugged somehow.
