### ISSUE TITLE
Space dealing brute damage and not dealing burn damage

### ISSUE THREAD

**Issue by AdamUrgol** [BeeStation/BeeStation-Hornet#7314]
Reporting client version: 514.1583

So I'm not an expert, I was testing changeling stuff reviving stasis in space and it turns out space deals only brute damage and 0% burn damage. No burn damage at all. Some people said maintainers likely messed up and it should be majority burn damage and only some brute. 
As on the picture.
![spacenoburndamagebug](https://user-images.githubusercontent.com/74247690/179856989-8c95155b-bb5f-4246-af27-13268f6642b9.png)

**Comment by EvilDragonfiend** [comment]
as far as I am right, if you have too much brute damage, you can't take burn damage. I think that's because.

**Comment by ivanmixo** [comment]
Um, no. Space only should deal brute. The reason you get burn is because of the cold temperature, not because of space itself.

**Comment by EvilDragonfiend** [comment]
ah, right, ivanmixo is right. it looks to have very fine temperature.

**Comment by St0rmC4st3r** [comment]
Did the body have nanites?
