### ISSUE TITLE
Delta destruction should allow the pod launch regardless of the actual alert level

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7315]
appears to be related with
* https://github.com/BeeStation/BeeStation-Hornet/issues/7244

It appears you can't launch a pod when the true alert is not at a level proper.

**Comment by PowerfulBacon** [comment]
Delta is a real alert level that's higher than red

**Comment by EvilDragonfiend** [comment]
Ah, my bad. It looks AI doomsday destruction doesn't count as delta.

**Comment by St0rmC4st3r** [comment]
> Ah, my bad. It looks AI doomsday destruction doesn't count as delta.

Just tested on local. It seems it does?
