### ISSUE TITLE
Plasma failing to ignite

### ISSUE THREAD

**Issue by Tyranicranger4** [BeeStation/BeeStation-Hornet#7317]
## Round ID:
39381

## Testmerges:
N/A

## Reproduction:
Attempt to light a burnmix on fire. Watch as the fire immediately goes out and fails to spread at all.
Flamethrowers also immediately extinguish.
Gasses still updated as normal from what I observed, plasma spreads as expected and the small bursts of fire seem to still slightly heat the area.
![image](https://user-images.githubusercontent.com/80382633/179883914-de5c84d8-e1e0-4ddb-8a79-313d2b8deaf4.png)
![image](https://user-images.githubusercontent.com/80382633/179883933-68e4c626-35c8-4979-bca8-bc42ae49c3d4.png)
![image](https://user-images.githubusercontent.com/80382633/179883948-34e7c643-7eab-4b82-8101-852853794db0.png)

**Comment by itsmeow** [comment]
So the real bug here, no atmos could get over 1000K so no fires could sustain

**Comment by Tyranicranger4** [comment]
Seems to have just been a one off issue, wasn't able to replicate it on the next round.
