### ISSUE TITLE
a small request

### ISSUE THREAD

**Issue by etherware-novice** [BeeStation/BeeStation-Hornet#7337]
im not entirely sure if this is how youre supposed to do this but @Cuboos what did you use to generate sound/ambience/antag/ops.ogg? i would like to work on someting similar and it would be nice to have a similar audio style

**Comment by Cuboos** [comment]
The beeping was some tones generated in FL Studio, the voice was also done
in FL studio, using their TTS feature which was then passed through some
filters to give it a distorted radio sound.

The background ambience are two sounds from Video Copilot's Designer Sound
Effects bundle which you can buy here
https://www.videocopilot.net/products/dsfx/

It's some sort of ambience music with a bit of some radio static mixed in,
which both came from that pack.

**Comment by etherware-novice** [comment]
oh...it costs money

**Comment by Cuboos** [comment]
That particular pack does, yes.

However you don't need to be reliant on paid sound packs to make good
sounds. Most of my sounds inmade for TG came from freesounds.org. all you
have to do is play around and mix things together.  Search around, do a bit
of googling, download some free sound libraries, mix and edit. You'll get
what you want eventually, or well, close enough anyway.
