### ISSUE TITLE
Intern station announcer doesn't announce shuttle call reasons

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#7358]
Shuttle call reasons are required by admins to determine if the call was valid or not and if the shuttle should be recalled.
The shuttle call reason announcement should be marked as an important message, so it isn't hidden by the intern announcer.

**Comment by Miliviu** [comment]
@PowerfulBacon do you think that Logging and notifying the admins would be enough?

**Comment by PowerfulBacon** [comment]
It would be better, but I think for the shuttle call it should just be an @everyone
