### ISSUE TITLE
Box Station medbay maintenance storage door is unaffected by emergency access

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#7361]
## Round ID:
39510

## Testmerges:

N/A

## Reproduction:

1. Set emergency maints access at comms console
2. This door is not affected despite being maints
![image](https://user-images.githubusercontent.com/10366817/180695693-8760b527-7412-4b60-a338-92d3141a9397.png)

**Comment by itsmeow** [comment]
Not stale.

Maptainer moment

**Comment by Tyranicranger4** [comment]
Lowkey thought this was intended so people couldn't break in or something like that. ***But*** you can get into the Brig, Sec outposts, Xenobio, and also fucking ***Atmos*** maintenance doors, so...
