### ISSUE TITLE
Blood cult Conceal non functional.

### ISSUE THREAD

**Issue by Daridine** [BeeStation/BeeStation-Hornet#7389]
Issue reported from  Round ID: #39559 (BeeStation Sage - Roleplay)

Reporting client version: 514.1585

Few things wrong.
1. Conceal no longer unhides anything leaving everything uninteractable, including alters and such.
2. It now has unlimited uses.

**Comment by Penwin0** [comment]
Unable to reproduce, conceal seems to work fine
