### ISSUE TITLE
Ling chemicals not regenerating

### ISSUE THREAD

**Issue by CatoYang** [BeeStation/BeeStation-Hornet#7396]
Issue reported from Round ID: 39576 (BeeStation Sage - Roleplay)

Reporting client version: 514.1584

My chemicals were stuck at 1, using abilities tells me i do not have enough chemicals.
During the ahelp i was told i had 75 chems *(full) and was another variable..?
Reconnect to no avail

Possibly caused by transforming to someone else then back to my original form?
Possibly caused by spaming my abilities?

Resolved by bacon in game by setting chemicals to max then back to 75 i assume.

**Comment by PowerfulBacon** [comment]
Not sure what caused this, but it happened to all lings simultaneously, so most likely an issue with processing or a runtime in the life loop
