### ISSUE TITLE
Janitorial cyborg drying agent spray doesnt refill and is completely empty

### ISSUE THREAD

**Issue by constatinus** [BeeStation/BeeStation-Hornet#740]
Issue reported from  Round ID: 8968 (BeeStation Sage - MRP For Everyone!)

Reporting client version: 512.1479

Dunno about the round, but it doesnt refill at all. i managed only to refill it with water...

**Comment by constatinus** [comment]
Lube spray as well

**Comment by constatinus** [comment]
Oh! Ive just seen what the issue is! In robot_modules the lube and dryign agent spray reagents are under quotation marks, which is not the case in tg. Cant really test this now, but I would be grateful if someone could do that.

**Comment by Cenrus** [comment]
I'll look into this shortly
