### ISSUE TITLE
Clients that deny telemetry should be denied access

### ISSUE THREAD

**Issue by Crossedfall** [BeeStation/BeeStation-Hornet#7405]
Been seeing a string of hacked clients connecting to the server recently. The common trait between all of them being that they actively deny sending the server telemetry data. 

There is no circumstance where a normal client would do this, so we shouldn't accept new connections where this is the case. 

----

Addendum:

I would also like an admin log when a user is denied access due to telemetry data issues. Optionally, it would be nice if a secondary log was made should they return with telemetry data.

**Comment by PowerfulBacon** [comment]
Do clients that have TGUI chat failing to load send telemetry?

**Comment by Crossedfall** [comment]
To my knowledge, no.
