### ISSUE TITLE
Sometimes stuns last far longer than they should, possibly resulting in the victim's death.

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#7406]
## Round ID:
39589

## Testmerges:
[#6879: 'Clockcult updates' by PowerfulBacon at commit b2b6845477](https://www.github.com/beestation/beestation-hornet/pull/6879)
[#6927: 'Reworks the Assimilation (Hivemind) Gamemode and adds it back into rotation' by Penwin0 at commit 74bbcf1b53](https://www.github.com/beestation/beestation-hornet/pull/6927)

## Reproduction:
Get stunned. Any method except stamcrit seemingly works, climbing into tables, wallshoves etc, you are now possibly stunned for 30+ seconds, leaving you extremely vulnerable.

**Comment by RDS88-beeman** [comment]
Is it possible the time dilation of the server was high, or the timers subsystem was behind at the time? Effects like this tend to be the result of the server struggling to keep up with all the things happening, and thus the timer that counts down behind the scenes that tells the game when to get you up moves slower.

**Comment by mcmeiler** [comment]
Likely due to a subsystem being paused.
