### ISSUE TITLE
You can infinitely produce goldschlager bottles

### ISSUE THREAD

**Issue by RussianGenCoke** [BeeStation/BeeStation-Hornet#7416]
Issue reported from  Round ID: 39629 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

footage, audio is fucky I can't fix it: https://youtu.be/2li7loJN5VE

steps:

1. Have a glass bottle (regular) full of goldschlager
2. Craft the actual goldschlager bottle via menu

as seen in the video the actual bottle does not get converted, instead the finished product drops at your feet. Since the process skips conversion you can mass produce these.

**Comment by etherware-novice** [comment]
will work on

**Comment by etherware-novice** [comment]
never mind what is this code
