### ISSUE TITLE
Hand tele BREAKS the Custom vendor

### ISSUE THREAD

**Issue by etherware-novice** [BeeStation/BeeStation-Hornet#7427]
## Reproduction:

Hand tele sprite is broken in the vendors, ples fix

![brokenhandtele](https://user-images.githubusercontent.com/73374039/182515275-ce57d1cd-6d8a-4ef4-af1f-062f9278d186.png)

**Comment by itsmeow** [comment]
icon2base64 might not support animated sprites

**Comment by etherware-novice** [comment]
ye so is there any way to fix that?

**Comment by PowerfulBacon** [comment]
Yes, just use the first frame of it
