### ISSUE TITLE
Mesons / engi scanner goggles no longer protect from hallucinations

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#7431]
## Round ID:

39709

## Reproduction:

1. wear engi scanner goggles on meson mode
2. look at SM
3. get hallucinated

**Comment by Penwin0** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/7428

Way ahead of you

**Comment by itsmeow** [comment]
oh nice
