### ISSUE TITLE
another quick q

### ISSUE THREAD

**Issue by etherware-novice** [BeeStation/BeeStation-Hornet#7436]
hey @red031000 how did you generate the medibot lines? i already have dr sbaitso but i cant get it to sound right

**Comment by Dejaku51** [comment]
you know you can just ask them on discord..?

**Comment by etherware-novice** [comment]
i dont know their tag

**Comment by red031000** [comment]
The medbot lines were ported from tg, I'm not the right person to ask

**Comment by etherware-novice** [comment]
oh who do i ask then

**Comment by EvilDragonfiend** [comment]
> oh who do i ask then

go to TG discord then ask anyways, I guess
