### ISSUE TITLE
Bug: Chaplain Undead Summoning retracts 1.5k favor even if noone takes the ghost role

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#7443]
## Round ID:

/

## Testmerges:

/
## Reproduction:

The Chaplain necromancy cult can use 1,500 fervor to summon an undead by performint the rite, waiting for a ghost to take the role and then having a new undead servant.
However, if no ghost takes the role, the fervor is still subtracted and nothing happens at all!
This is especially frustrating since getting enough fervor takes roughly 4-6 monkeys to sacrifice which can take quite long.

**Comment by EvilDragonfiend** [comment]
@ro5490

**Comment by ro5490** [comment]
Fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/7343

**Comment by JukeJukestar** [comment]
fixed in #7343
