### ISSUE TITLE
AI cyborg connection menu shows incorrect information

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#7444]
## Round ID:

39732
## Reproduction:
Be an AI, have anything happen to a cyborg connection, watch as the menu showing connections either: does not remove emagged cyborgs, does not update for a long time, does not update the "connected cyborgs:" count entirely.

**Comment by itsmeow** [comment]
Do you mean the Status panel?

**Comment by WrillWasTaken** [comment]
> Do you mean the Status panel?

yes
