### ISSUE TITLE
[BOUNTY]: Viro Additions+Changes Base

### ISSUE THREAD

**Issue by zeskorion** [BeeStation/BeeStation-Hornet#749]
**This is part of a compiled bounty of separate parts qwert made me separate into several bits. see the full bounty here:**
https://docs.google.com/document/d/1OeWn7BJlNJ6lWvQ0Z-j3jSCKmzZMRQoIDpfhq5pAFKA/edit#heading=h.fsalu28no4nx

**What this specific bounty entails:**
-Add two new symptom levels. Tier 9 and tier 0/ “special”
-Add a new virus chem, Anomalous virus food, mixable at roundstart with chem or the clown’s laughter or something, which makes tier 0 symptom
-Tier nine symptoms only obtainable in randomly spawning diseases (Experimental diseases)
-Add two(or one) experimental disease cultures to virology, and one bottle to medivends when hacked
-Change the “Big Three” symptoms (Alkali Perspiration, Autophageocytosis Necrosis, and Acute Respiratory Distress Syndrome) to tier 9

**Comment by ike709** [comment]
I'll do most of these virus bounties this weekend.
