### ISSUE TITLE
When Two Pirate ships spawn, one controls both

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#7492]
One team of pirates complained that their ship was moving on their own, it was because the other pirate team was piloting
Round this happened: 39863
![Screenshot_1](https://user-images.githubusercontent.com/57050500/184438257-db372aef-c502-4de4-a50f-a53bcd1262f7.png)

Since this is probably shuttle-cruise related:  @PowerfulBacon

**Comment by PowerfulBacon** [comment]
Not even sure pirates are meant to spawn multiple times.

**Comment by Fronsis** [comment]
That's what we were talking about too, it certainly wasn't an admin spawn and we weren't on dynamic so.. that's very odd (Though in the round we had Incursion+traitor targets, pirates X2, cult, xenos but i say we weren't on dynamic since it didn't show the antag weights on the EOR tab)

**Comment by itsmeow** [comment]
Fixed by #8405
