### ISSUE TITLE
Camera Consoles show mapping random plant spawners 

### ISSUE THREAD

**Issue by llol111** [BeeStation/BeeStation-Hornet#7510]
## Reproduction:
Look around with a camera console.
![1Cy4QyjK0S](https://user-images.githubusercontent.com/86115086/184640704-bbfef1c5-3c64-4912-b663-2434691df240.png)

**Comment by PowerfulBacon** [comment]
All the icons for things show the initial icon now instead too. I think that was a byond update/optimisation, not sure about this
