### ISSUE TITLE
Verbs with ! in them can't be used from stat.

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#7518]
Verbs with ! in them can't be used in the stat panel.
This affects Boo! and Possess!

Easy solution: Remove ! from verb names

Hard solution: Fix it properly by trimming or replacing ! internally

**Comment by EvilDragonfiend** [comment]
I think it is replaced with #0??: something like that since it happens to quotes too

**Comment by itsmeow** [comment]
Just did some deep debugging.

BYOND does not support verbs with `!` in the name. It literally refuses to add such a verb to the verbs list.

**Comment by itsmeow** [comment]
![image](https://user-images.githubusercontent.com/10366817/188036929-841c45bc-80c8-48c0-bc5c-3233e306e97c.png)

**Comment by itsmeow** [comment]
Nevermind, deep in the stupid observer mob there is a var called "fun_verbs" that controls if you get it removed or not.
