### ISSUE TITLE
Cuffed monkeys/humans make the cuffs completelly dissapear upon getting humanized/monkeyfied

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#7519]
## Reproduction:
Cuff a monkey then either apply mutadone or stuff it into the DNA scanner (although mutadone makes it easier to see). Upon transforming, the cuffs will completely fade from existence. Same happens when you monkeyfi a human. 

Would be nice if the handcuffs at least dropped to the floor.

**Comment by Alpkant** [comment]
It is also the case for gibbing the monkeys. If you gib the cuffed monkey, cuffs disappear. I also think cuffs should be dropped.
