### ISSUE TITLE
[BOUNTY]: Viro Additions+Changes: Spiked Skin

### ISSUE THREAD

**Issue by zeskorion** [BeeStation/BeeStation-Hornet#754]
**What this specific bounty entails:**
Code the following virus symptom, following the description and symptom thresholds:
Spiked Skin
Hurts people when they grab you, hug you, or you walk into them or hug them.
Stealth: -3
Resistance: 3
Speed: -3
Transmission: 2
Level: 0 (or 8)
Thresholds:
resistance 6: does more damage
transmission 6: gives the host minor armor

**Comment by zeskorion** [comment]
posted a bounty on this but bot didnt do shit

**Comment by nikk735** [comment]
Ill have a go at it but dont have any high expectations

**Comment by nikk735** [comment]
done
