### ISSUE TITLE
Cant join

### ISSUE THREAD

**Issue by MightyMikeyy** [BeeStation/BeeStation-Hornet#7541]
Issue reported from  Round ID: 40023 (BeeStation Sage - Roleplay)

Reporting client version: 514.1585

**Comment by itsmeow** [comment]
Please describe the issue further or provide some type of information we can use to diagnose the issue.

Also try deleting your Documents/BYOND folder or clearing the cache in preferences.

Make sure you are on the supported version of BYOND and not the latest

**Comment by Crossedfall** [comment]
Checking through our logs it looks like you've been able to connect no problem over the last several days. Going to close this as unreproducible.
