### ISSUE TITLE
bug with the locking of the Headset uplink after the emerging of PR#7363

### ISSUE THREAD

**Issue by Wueue** [BeeStation/BeeStation-Hornet#7546]

**Comment by itsmeow** [comment]
@etherware-novice

**Comment by etherware-novice** [comment]
oh uh

how do you detect when the menu is closed?

also youre not explicitly locking it which is consistent with the other uplinks, so idk if its neccesary to change

**Comment by itsmeow** [comment]
make it so talking into it changes the UI to always pull up the uplink unless you press Lock.

if you press lock, it should open the normal UI

**Comment by etherware-novice** [comment]
right yea how tho

**Comment by itsmeow** [comment]
code dive, idk

**Comment by itsmeow** [comment]
I wasn't able to reproduce this. As a traitor, I used the uplink. It did not open the regular radio menu.

This functions as it should, no uplink should have full autolock without costing TC (see: implant)
