### ISSUE TITLE
Dynameme fails to spawn rulesets quite often / says it'll spawn something but it never does

### ISSUE THREAD

**Issue by Chirynnn** [BeeStation/BeeStation-Hornet#7554]
## Testmerges:
https://github.com/BeeStation/BeeStation-Hornet/pull/7438 

## Reproduction:
Be admin, notice how half the time most Dynamic rulesets fail to spawn because they're not light/heavy or some other similar reason. I believe this may have something to do with Kat's merged Dynamic PR, but I'm not sure. On round 40091, Malf AI was supposed to spawn, however it never did, and it never spat out any errors or a reason as to why it didn't trigger.

**Comment by itsmeow** [comment]
I need the dynamic logs from this round to diagnose the issue.

The likely cause is not enough "enemy players" (sec)

**Comment by itsmeow** [comment]
Got the dynamic logs, it appears "Executing Ruleset: Malfunctioning AI" ran, but no other output related to this happened.

Maybe there was a runtime? Most everyone is busy at the moment so I can't get more logs to check for that.

**Comment by itsmeow** [comment]
Got logs, there was some kind of runtime error, unfortunately the stacktrace is absent because byond is stupid

**Comment by Chirynnn** [comment]
Hey, sorry about no replies, I didn't think of checking GitHub until now. Glad you got the logs, I unfortunately don't have access to those as a Moderator
