### ISSUE TITLE
Plasma injected into blood killed Slimeperson

### ISSUE THREAD

**Issue by TzuInferno** [BeeStation/BeeStation-Hornet#7564]
## Round ID: 
40132

## Testmerges:
None AFAIK

## Reproduction:

When playing as xenobiologist who had turned themselves into a slime person, I tried injecting plasma straight into my veins. Rather than providing jelly and healing me, it did a shit ton of toxin damage, and then I died. This is inconsistent with breathing plasma (which causes you to gain jelly, though that acted up earlier too. Think that was time dilation though), as well as with drinking liquid plasma. If this is on purpose, it should be made consistent.

It also might have been because I had so much injected (60units, one bluespace syringe) but I did not think plasma had an OD effect.

1. Become a slimeperson, specifically the kind that splits i.e. actual slime person. This is worth testing with other jellyperson races and oozlings though in case they have similar issues.
2. Get at least 60u of liquid plasma in some kind of beaker.
3. Fill a bluespace syringe fully with liquid plasma from beaker.
4. Inject it into yourself.

Expected result:
Jelly gain, or at least nothing.

Actual result:
Massive amounts of toxin damage, jelly loss, loss of breathing ability, death.

**Comment by DrDuckedGoose** [comment]
Unable to recreate issue.
Was there something unique about your situation?

![image](https://user-images.githubusercontent.com/40559528/187062680-7394a873-2550-4b48-86b3-a392c3371bbc.png)

![image](https://user-images.githubusercontent.com/40559528/187062630-d92d5c8b-e964-4936-b1fd-a793672f99f6.png)

![image](https://user-images.githubusercontent.com/40559528/187062727-e4090779-a013-418b-9a83-8ad5e3030af6.png)

![image](https://user-images.githubusercontent.com/40559528/187062734-1f2b7981-c955-4695-af7f-9e323bad0cd5.png)

**Comment by TzuInferno** [comment]
Sorry for late reply to this, yes, it turns out the nanites don't instantly kill you, but instead when you have a toxin in you, they start trying to remove it constantly causing death. No bug.
