### ISSUE TITLE
[BOUNTY]: Viro Additions+Changes: Heart Disease

### ISSUE THREAD

**Issue by zeskorion** [BeeStation/BeeStation-Hornet#757]
**What this specific bounty entails:**
Code the following virus symptom, following the description and symptom thresholds. I will likely come by and fine-tune tickers for balance:
Heart Disease
The host's heart begins functioning poorly, causing them to take oxyloss randomly and may eventually lead to cardiac arrest.
Stealth: 2
Resistance: 2
Speed: -6
Transmission: -2
Level: 9 
Thresholds:
Transmission 9: When the disease would cause cardiac arrest, it instead causes the host's heart to come free of their chest and attack!
Resistance 10: Occasionally synthesizes intropidril, furthering the risk of cardiac arrest(edited)

**Comment by zeskorion** [comment]
posted a bounty on this but bot didnt do shit

**Comment by Crossedfall** [comment]
~~poor ol confused bot~~ Thar it goes
