### ISSUE TITLE
Genetic instability reactions that would turn you into a slime does not work properly

### ISSUE THREAD

**Issue by theqwat** [BeeStation/BeeStation-Hornet#7571]
## Reproduction:
make someone unstable  (100 instability) and wait for a reaction to do nothing... check to see if it put "Advanced Mutation Toxin" into the system probably 10 units and see that nothing happens i double checked to make sure it wasn't the chemical and it seems to be with how genetic instability is handled

**_other_** 
just want to bring up as far as i know throughout all of beestation since the time of squid in PR [#139](https://github.com/BeeStation/BeeStation-Hornet/pull/139) the removed the snails ability to make lube trails... so if you ever wondered why we dont have it thats why i know Kupa limbs changed things but im bringing it up... oh and speaking of old PR's tod'sie was made [[#71]](https://github.com/BeeStation/BeeStation-Hornet/pull/71)

**Comment by The-Moon-Itself** [comment]
dna melt has a 10% chance to just do nothing, are you sure that doing nothing wasn't rolled?

**Comment by theqwat** [comment]
For sure i thought it was nothing myself but my health analyzer was on chemical at the time and i saw 9.7 Advanced Mutation Toxin within there system
