### ISSUE TITLE
[BOUNTY]: Viro Additions+Changes: Blob Spores

### ISSUE THREAD

**Issue by zeskorion** [BeeStation/BeeStation-Hornet#758]
**What this specific bounty entails:**
Code the following virus symptom, following the description and symptom thresholds:

Blob Spores
The host synthesizes blob spores, spawning a blob tile of a random chemical on death, along with a few blob spores. High resistance, low speed, like a blob round.
Stealth: 1
Resistance: 6
Speed: -2
Transmission: 1
Level: 9
Thresholds:
Resistance 11: chance to spawn a factory blob instead of a normal blob, which does not require a node to function.
Transmissions 8: Spawns blob spores occasionally 
Resistance 14: chance to spawn a blob node instead of a normal blob or factory blob

**Note: Due to how blob tiles work, this will likely require a new subtype of blob tiles which does not require an overmind to function. That will probably be the main difficulty of this bounty, which is an otherwise quite easy symptom to code**

**Comment by zeskorion** [comment]
ugh, accidentally shoved an extra five bucks onto this

if someone ends up doing this and the cure ports, just assume that goes to the cure ports

**Comment by zeskorion** [comment]
disregard previous comment- ten buck in full to the one who completes this

**Comment by Arturlang** [comment]
I shall attempt this.
