### ISSUE TITLE
Falling out of transit may put you on levels you are not supposed to be on.

### ISSUE THREAD

**Issue by St0rmC4st3r** [BeeStation/BeeStation-Hornet#7601]
Issue reported from  Round ID: 40222 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

Be me. 
Fall out of the shuttle. (via bluespace interference teleporting or otherwise). 
Get teleported on a random loaded space Z-level.
What levels are valid?
Station level.
Weak Signal level.
Any loaded ruin level.
Arrival shuttle transit level.
Uh. Oh.
Get stuck forever because it is a system level you are not supposed to end up on, and thus nothing can land there.

**Comment by itsmeow** [comment]
Which shuttle were you on? Going from where to where? AFAIK it drops you on the Z-level the shuttle departed from.

**Comment by St0rmC4st3r** [comment]
> Which shuttle were you on? Going from where to where? AFAIK it drops you on the Z-level the shuttle departed from.

I dropped out of the exploration shuttle, but in an unusual way. I used the teleporter station to get on the explo shuttle, but I had a bag of holding with me, so I teleported into hyperspace.
Also I am sure this is connected to the #5843 that is still the case.

**Comment by St0rmC4st3r** [comment]
No, it is not.
