### ISSUE TITLE
Agent ID shows wrong HUD icon

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#7606]
## Round ID & Round Date:

N/A

## Testmerges:

Xenoarch

## Reproduction:

The Agent ID will show a Syndicate job HUD by default, it should show the job based on the name of the job assigned. I'm not sure if you manually pick the HUD too, but it should auto-change if you assign a job name that's in the list.

**Comment by Penwin0** [comment]
Caused by #7112 really should apply appearance automatically

**Comment by EvilDragonfiend** [comment]
the card item system doesn't show hud based on the title anymore. It's based on card style. they just forgot to change the card shape.

**Comment by EvilDragonfiend** [comment]
that's because you can be an assistant that would want to show your hud as non-assistant.

**Comment by EvilDragonfiend** [comment]
also, plus - if you pick a job shape from the chamelon list, you just get a job title automatically. they just used the wrong way.

**Comment by itsmeow** [comment]
Yeah but it seems a lot of players are getting confused by this and end up walking around with a syndicate ID HUD.

The agent ID specifically should be changed to auto-update the ITEM appearance when you change the job.

**Comment by EvilDragonfiend** [comment]
well, it isn't a bug at least. but might be not a good designed menu to lead people to have a proper hud.
