### ISSUE TITLE
Pirate event spawns 2 pirate ships (which aren't dynamic so break)

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#7607]
This is pretty important, the pirate event always triggers 2 pirate ships to spawn.

**Comment by itsmeow** [comment]
Pirate event vs pirate dynamic ruleset might be the issue, does the event do it, or only the ruleset?

**Comment by itsmeow** [comment]
Looks like it's always, found the cause. Fixing.
