### ISSUE TITLE
The character setup preview doesn't work properly for lizards.

### ISSUE THREAD

**Issue by sergeirocks100** [BeeStation/BeeStation-Hornet#7612]
Hello.

I'm not a Beestation regular, and i've never even connected to the server before today, but i noticed this issue when i was setting up my character, and i felt like i needed to report it.

I'm using BYOND 514.1585, if that matters.

Apologies if this has been reported before, i couldn't seem to find any relevant issues when i searched.

## Round ID & Round Date:

40236, 9/3/2022

## Testmerges:

#6718: '[New Science Sub-Department] Xenoarchaeology - Xenoartifact Research. ' by DrDuckedGoose at commit 73484a97c5](https://www.github.com/beestation/beestation-hornet/pull/6718)

## Reproduction:

.1: Select a lizard in the species menu.
.2: Notice how the underwear doesn't show up, and it uses the male body sprite, regardless of selected gender.

![Screenshot_14](https://user-images.githubusercontent.com/31294280/188293189-e93e9122-d087-4f74-be33-6678c7fa51de.png)

I changed the species around to human, moth, ethereal, and IPC, and the underwear and gender specific body types showed up on all of them. It just seems to be lizards that are affected.

I don't know if it affects your appearance once you're actually in-game, i never left the lobby screen.

**Comment by Dejaku51** [comment]
> underwear doesn't show up

you sure you had underwear selected?

**Comment by sergeirocks100** [comment]
> > underwear doesn't show up
> 
> you sure you had underwear selected?

I did have underwear selected. It showed up fine on the 4 other species i tried, just not for lizards.

**Comment by CydiaLamiales** [comment]
Byond version does matter, it's recommended to downgrade to 514.1583 if you want to continue to play on Bee.

**Comment by sergeirocks100** [comment]
I decided to do some further testing locally, and i found out two things.

1. It still occurs on 514.1583.
2. It affects how lizards appear in the game world.

I also managed to confirm that underwear shows up fine on every single species except for lizards, specifically.

I have precisely zero idea as to why this is happening for lizards, and lizards alone. Have there been any changes to lizards recently?

**Comment by sergeirocks100** [comment]
Upon further investigation, i found two things that seem to be the culprit:

1. #5611, for whatever reason, gave lizards the NO_UNDERWEAR flag.
2. Lizards don't seem to have separate male and female chest sprites. Lizard body markings do seem to have separate male and female sprites, strangely enough.

After i manage to get in contact with a maintainer for approval, i'm going to try and PR a fix for this. Or someone else can do it, i don't really care.

**Comment by dwasint** [comment]
Lizards aren't gendered species so there will be no difference in that.
and lizards can't wear underwear as the digi models aren't made and they clip if you use digi legs.

So i would say not a bug
