### ISSUE TITLE
Ghosts are able to spin chairs and such via ALT-Context menu

### ISSUE THREAD

**Issue by ro5490** [BeeStation/BeeStation-Hornet#7624]
## Round ID & Round Date:
402353
2022-09-05

## Testmerges:
[#7537: 'Deny access to clients that don't send telemetry' by itsmeow at commit 97b49e57a5](https://www.github.com/beestation/beestation-hornet/pull/7537)
[#7441: 'MRat V2' by itsmeow at commit 1f9240eb76](https://www.github.com/beestation/beestation-hornet/pull/7441)
[#7430: 'Refactor mentors to use admin ticketing system' by itsmeow at commit b8c4c2e23c](https://www.github.com/beestation/beestation-hornet/pull/7430)

## Reproduction:

Alt-click a tile that contains a chair while being a ghost/observer
open the context menu tab that appears
alt-click the chair
Watch it spin!

**Comment by ro5490** [comment]
![image](https://user-images.githubusercontent.com/17776299/188342934-ac83729f-b6dd-4a9f-adae-70467a1fd1b6.png)

**Comment by ro5490** [comment]
![image](https://user-images.githubusercontent.com/17776299/188342947-37be0939-d54c-40cc-b8b6-6b17cbc9ee36.png)

**Comment by itsmeow** [comment]
This appears to be intentional

![image](https://user-images.githubusercontent.com/10366817/189509379-e8b1c508-a24d-45ca-b8f8-35655ef3aa66.png)
![image](https://user-images.githubusercontent.com/10366817/189509387-46d3ccfc-9a21-45cc-919e-6e61a6e1eb4c.png)

**Comment by ro5490** [comment]
This config is disabled, otherwise observers would be able to rotate chairs normally, without using the Alt-Click context window
