### ISSUE TITLE
Cult halo without being a cultist

### ISSUE THREAD

**Issue by SuperPantsHero** [BeeStation/BeeStation-Hornet#7640]
## Round ID & Round Date:
**40283**
06/09/2022

## Reproduction:
Was converted to cultist (no halo). A while later, after being injected with holy water I drop to the ground and when I wake up I suddenly have a cultist halo but have lost all cultist abilities such as communicating, being able to cross through doors that were converted, or being able to see other cultist icons above their heads. 
I'm fairly certain cultist attained halos as soon as I was deconverted.
I'm also not sure if you're supposed to get a message when you get halos, but I never got any message, only the one indicating that I'd been deconverted.
Steps:
1. Get converted to cultist in early stages with no halo
2. Start getting deconverted
3. Finish deconversion as soon as cultist achieve halos

You should now be regular crew with but with a halo. Resulting in very confused cultists, because they can't see your icon. And security trying to kill you because they can't distinguish you from the others.

**Comment by boombaklops** [comment]
This happened to me in round 44622, but I had my halo long before I was deconverted. Very annoying bug.
