### ISSUE TITLE
Latejoin traitor only gets 3 objectives

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#7660]
## Round ID & Round Date:

Round ID : 40317
Round date : 09/09/2022
## Testmerges:
https://github.com/BeeStation/BeeStation-Hornet/pull/7537 Deny access to clients that don't send telemetry by itsmeow

## Reproduction:
I joined late as a detective, got the traitor pop-up but noticed that I only had three objectives. However, all the other sleeper agent traitors and the roundstart traitor had four objectives. I think this PR which made traitors have 4 objectives instead of 3 missed the Syndicate Infiltraitor. https://github.com/BeeStation/BeeStation-Hornet/pull/7576

**Comment by PowerfulBacon** [comment]
Potentially relevent to dynamic?

**Comment by itsmeow** [comment]
I looked at it and I see no reason this would happen.
Latejoin does the same exact thing that sleeper does and assigns the datum.

The datum controls the amount of objectives.

**Comment by CydiaLamiales** [comment]
Well I posted the round ID, could you maybe get logs and see why that happened?

**Comment by itsmeow** [comment]
We can look and see if #7670 fixes this maybe.

**Comment by itsmeow** [comment]
found bug

its not latejoin, it's hijack![Screenshot_20220913-185303.png](https://user-images.githubusercontent.com/10366817/190029357-da9b529c-477b-4969-a09d-9cdde39fbfa0.png)

**Comment by CydiaLamiales** [comment]
Except I did not have a hijack objective that time, only an "escape on the shuttle alive and without being in custody"

**Comment by itsmeow** [comment]
Should be good now
