### ISSUE TITLE
minor SPELLING issue with HERETICS (IMMERSION BREAKING)

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#7680]
## Round ID & Round Date: 
40358

## Reproduction:

BE A HERETIC AND SEE THIS EYE DESTROYING IMAGE
![7060b24a7ee811a5ad1c15ec41c8c902](https://user-images.githubusercontent.com/59359762/189590668-7d8c34ff-42b5-4f9f-a480-1b04e92b4b78.png)
IF YOU DO NOT HAVE EYES DON'T WORRY "SACRAFICE" IS SUPPOSED TO BE "SACRIFICE"

**Comment by hotimep** [comment]
![download (1)](https://user-images.githubusercontent.com/59359762/189590999-be3074eb-1a13-4b8d-b07f-fb3f3fb1218e.jpg)

**Comment by itsmeow** [comment]
heretic overhaul when @TeomanTheGreat

**Comment by TeomanTheGreat** [comment]
> heretic overhaul when @TeomanTheGreat 

When you code it

**Comment by EvilDragonfiend** [comment]
feature

**Comment by Tyranicranger4** [comment]
Literally unplayable.
