### ISSUE TITLE
my first report i dont know if it belongs here got killed over nothing from non murderbone

### ISSUE THREAD

**Issue by MightyMikeyy** [BeeStation/BeeStation-Hornet#7683]
i was playing chilled todayabout 20 minutes ago so i was first time trying botany when somehow a blue cloud of acid gas appeared and killed me and destroyed the whole botany , maybe i caused it but im not sure since im a noob at botany, dead chat told me it was a scientist if i remember correctly, after the round i checked the objectives of all antags, there was no murderbone antag and no one had the objective to kill me or destroy my botany so im pissed i got killed over nothing, there was no one else near me so i was the target, didnt see anyone though since i was focused on learning on wiki while staring at my plants ... also if it helps (round ID: 40375)

**Comment by St0rmC4st3r** [comment]
This is github, it is for code-related reports. You should make a player report on the forums at https://forums.beestation13.com/c/player-input/player-reports/19

**Comment by MightyMikeyy** [comment]
oh sorry thanks
