### ISSUE TITLE
Quantum Hair Dye only paints your hair white, Natural Hair Wig always remains white.

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#7740]
## Reproduction:
Spawn in a can of Quantum Hair Dye or make some yourself,  apply it to a human with hair and you'll see that the hair color will only be white. Same goes for natural wigs, they're supposed to adapt to your natural hair color but they never do and always remain white. I'm grouping these bugs into one report because the issue seems to be stemming from a common place.

**Comment by CydiaLamiales** [comment]
Discovered this like a month ago but only remembered to report it now.

**Comment by etherware-novice** [comment]
will work on
