### ISSUE TITLE
Corgium transformation makes player mute

### ISSUE THREAD

**Issue by Chessus** [BeeStation/BeeStation-Hornet#7742]
## Round ID & Round Date: 40641
40641

## Testmerges:

[#7016: '[Ready for TM] That PR where I refactor the entire preferences system' by AffectedArc07 at commit ce2f89c1ee](https://www.github.com/beestation/beestation-hornet/pull/7016)
## Reproduction:
Get corgium in your system, transform into corgi, die, get revived and be mute. Mutadone doesn't heal.

**Comment by PowerfulBacon** [comment]
I believe this will be fixed by the PR that removes corgium trait, as it just allows the corgis to talk

**Comment by itsmeow** [comment]
Corgium ded
