### ISSUE TITLE
lavaland random ruins stack together

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7754]
## Round ID & Round Date:

40657

![image](https://user-images.githubusercontent.com/87972842/193394205-7c8b4918-764d-4455-bd84-603924db5b21.png)

----------------------

![image](https://user-images.githubusercontent.com/87972842/193394214-f5ab4604-d822-4ce3-98ef-798a1fc433a3.png)

--------------------

![image](https://user-images.githubusercontent.com/87972842/193394275-f44bcdfa-be93-42a8-8a0e-9301a0527d7a.png)
![image](https://user-images.githubusercontent.com/87972842/193394286-3e3da09e-2b3f-49b1-97ef-a59f07aa7430.png)

## another unknown round one:

![image](https://user-images.githubusercontent.com/87972842/193394343-7d26f0dd-e974-4c15-907a-e722a6312241.png)

winter dome + clown ruin + alien ruin + present room

**Comment by Dejaku51** [comment]
also seems like plants and mobs can spawn in ruins

**Comment by h42-real** [comment]
Unknown round screenshot is from round 40653, but I've been noticing it happening since round 40649.

**Comment by PowerfulBacon** [comment]
This is related to my pull request

**Comment by PowerfulBacon** [comment]
Fixed
