### ISSUE TITLE
Improper formatting in the Cyborg Monitoring app when emagged.

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#7757]
## Round ID & Round Date:
Round ID: 40662 
Round Date: 10.01.2022

## Testmerges:
[#7659: 'Removes some major sleepers (100% lag free)' by PowerfulBacon 
[#7016: '[Ready for TM] That PR where I refactor the entire preferences system' by AffectedArc07 

## Reproduction:
Become borg, get emagged by someone, get wrong formatting in your Law 0
![image](https://user-images.githubusercontent.com/110184118/193416817-7eef6ad2-702b-4d1f-98f3-885246c91555.png)

**Comment by etherware-novice** [comment]
ah yes working on your own issue robbing newbies of a "good first issue" pr (which there are almost none) how noble

**Comment by Tyranicranger4** [comment]
> ah yes working on your own issue robbing newbies of a "good first issue" pr (which there are almost none) how noble
What 🤔

**Comment by itsmeow** [comment]
> ah yes working on your own issue robbing newbies of a "good first issue" pr (which there are almost none) how noble

I created a bug with my PR, so I fixed it. ?????
