### ISSUE TITLE
NO SUICIDE MESSAGE FOR GLUE (GAME BREAKING)

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#7798]
## Reproduction:

GLUE HAS NO SUICIDE MESSAGE. IT IS BORING.
![gluicide](https://user-images.githubusercontent.com/59359762/193522275-3d6fc987-17d7-4d7e-a497-ee0b708bcc26.png)
IT HAS BEEN TODO FOR ONE YEAR. FIX IT. MAKE IT FUNNY.

**Comment by itsmeow** [comment]
Literally unplayable, oh no what will I do

**Comment by hotimep** [comment]
coward

**Comment by PowerfulBacon** [comment]
the fact that it overrides the default suicide message to specifically do nothing is weird
