### ISSUE TITLE
shuttle bug

### ISSUE THREAD

**Issue by coronacat** [BeeStation/BeeStation-Hornet#7829]
## Round ID & Round Date: 
40705    2022 10 04

## Reproduction:
I'm not sure how to reproduce it as we accidentally found it, the shuttle floor launched without us and soon after, so did the rest of the shuttle, leaving me and my friend lost in open space.

**Comment by PowerfulBacon** [comment]
What shuttle?

**Comment by coronacat** [comment]
The exploration shuttle.

**Comment by itsmeow** [comment]
Bugs with shuttle turf loading have *mostly* been fixed, so I'm going to close this.
