### ISSUE TITLE
Various problems with the ORM

### ISSUE THREAD

**Issue by Sun-Soaked** [BeeStation/BeeStation-Hornet#783]
By various I mean two.
1: The ORM fails to do anything when it is requested to create (Some? Haven't tested all) alloys.
2: The ORM fails to transfer raw materials to other machines when they request them. 

## Reproduction:
Attempt to create alloys at any ORM. Attempt to draw materials at any linked machine.
This appears to be connected to a recent ORM update that changed the interface and added some quality-of-life changes, but I for the life of me cannot find it.

**Comment by Sun-Soaked** [comment]
quick addendum: I've found this messes with Cultists in particular, since they're denied any non-round-start source of Runic Metal

**Comment by St0rmC4st3r** [comment]
Use the damn department techfabs. Is it really that hard?

**Comment by Moccha-Bee** [comment]
Why ? Are we just going leave the ORM half broken because of techfabs?

**Comment by St0rmC4st3r** [comment]
Of course not! It's just that too many people for some reason have no idea that the techfab does that.

**Comment by Moccha-Bee** [comment]
Oh i mean resenable i myself forgot about the techfabs ability to print alloys. But this definetly should be fixed.

**Comment by Cenrus** [comment]
https://github.com/tgstation/tgstation/pull/47631

This fixes it

**Comment by MemedHams** [comment]
I had this Issue yesterday. And today. It's not fixed.

**Comment by Sun-Soaked** [comment]
Thank you for letting me know about the techfab alloys, but I'm not sure that'll work either, considering the techfabs can't pull materials.

**Comment by Sun-Soaked** [comment]
Whoops, missclick.

**Comment by Sun-Soaked** [comment]
Update: I've learned that the techfabs can, in fact, print materials. However, a techfab accessed through a computer cannot. (???)

**Comment by ike709** [comment]
Should be fixed by #820 ?
