### ISSUE TITLE
Arrivals Shuttle Cockpit area gets split in half

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#7838]
Round ID & Round Date:
40724 - 10/5/22 Server: Sage

I've noticed this happened three-four times these past weeks, i'm not sure if every incident took place on Box Station but two i remember it did, so.. yeah, it sucks because the arrivals shuttle loses all O2 and pressure, hell i arrived on top of a husked dude who was ssd

![Screenshot_2](https://user-images.githubusercontent.com/57050500/194181198-94157bc9-abad-4660-9510-e252c808cb92.png)

**Comment by PowerfulBacon** [comment]
Okay nice, it wasn't my PR that was bugged. The issue is it assuming a shuttle area on the hyperspace tiles but sometimes it's not

**Comment by itsmeow** [comment]
I haven't been playing much to tell, but does this seem fixed?

**Comment by itsmeow** [comment]
It seems this is not happening anymore.
