### ISSUE TITLE
Cant open beecoin shop if you are on your 4th/beecoin character slot

### ISSUE THREAD

**Issue by ToasterBan** [BeeStation/BeeStation-Hornet#7864]
## Reproduction:
1. acquire the beecoin character slot
2. select it
3. try go to the beecoin shop
4. realise it just doesn't go
5. swap to another character slot
6. successfully enter the beecoin shop

**Comment by itsmeow** [comment]
@AffectedArc07

**Comment by RussianGenCoke** [comment]
Weird, it's the third character slot that acts up for me

**Comment by itsmeow** [comment]
There's a runtime related to character slots that had loadouts prior to #6966 that can affect said characters.

**Comment by Crossedfall** [comment]
I am unable to reproduce this.

**Comment by Crossedfall** [comment]
@itsmeow managed to find me the likely runtime and I was able to reproduce it from there. Looks to have been an issue with the savefile importer.

**Comment by Crossedfall** [comment]
I have a preventative fix PR'd now. However, it wont resolve this issue on merge. We'll still need to do some modifications to the database directly to resolve that.

**Comment by Crossedfall** [comment]
Should be resolved now.

```sql
> SELECT ckey,slot,equipped_gear FROM SS13_characters WHERE equipped_gear NOT LIKE '[%]';
Empty set (0.023 sec)
```
