### ISSUE TITLE
Flandstation Robotics Windoor blocked by random RWall

### ISSUE THREAD

**Issue by RubberEyes** [BeeStation/BeeStation-Hornet#7866]
## Round ID & Round Date:
40800
Server revision compiled on: 2022-10-10T18:35:38+00:00

## Testmerges:

 
[#7375: 'Flandstation - Service Pack 5 (AKA Flandstation 2.0)' by PestoVerde322 at commit 77cacc0d7d](https://www.github.com/beestation/beestation-hornet/pull/7375)

## Reproduction:
Look at robotics, you'll see it

**Comment by PestoVerde322** [comment]
Bug found during TM of https://github.com/BeeStation/BeeStation-Hornet/pull/7375; Fixed it in the lastest issue of this Pr.
![immagine](https://user-images.githubusercontent.com/75247747/194957980-3af01f94-a95c-46a3-ac30-8c49a5eeb318.png)
