### ISSUE TITLE
Flandstation Runs out of Power too fast

### ISSUE THREAD

**Issue by RubberEyes** [BeeStation/BeeStation-Hornet#7867]
## Round ID & Round Date:
2022-10-10 
40800

## Testmerges:
[#7375: 'Flandstation - Service Pack 5 (AKA Flandstation 2.0)' by PestoVerde322 at commit 77cacc0d7d](https://www.github.com/beestation/beestation-hornet/pull/7375)

## Reproduction:
Wait 8 minutes, you'll start to see areas without power

**Comment by PestoVerde322** [comment]
Bug found during TM of https://github.com/BeeStation/BeeStation-Hornet/pull/7375; maybe fixed, need in-game test.

I've increased the quantity of APC back to 4, and gave it a bit more power on roundstart.

![immagine](https://user-images.githubusercontent.com/75247747/194958047-aa3e0f89-ccc5-40bf-93e1-44530dacf54c.png)

**Comment by PowerfulBacon** [comment]
This was on a testmerge
