### ISSUE TITLE
PIPE GAS ANALYZER CHAT POPUP LOOKS LIKE SHIT!!! FIX IT!!!

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#7874]
## Round ID & Round Date: 
40805, 10/10/2022

## Reproduction:
IT SHOULD NOT LOOK LIKE THIS!!! MY EYES!!!!
![fix](https://user-images.githubusercontent.com/59359762/194996762-ab4e7059-bbc6-4496-9868-b17f37c979ec.png)

**Comment by Tsar-Salat** [comment]
I have this issue as well. Very severe issue, most priority!

**Comment by itsmeow** [comment]
Ah shit, might've been me that did that. Will fix it
