### ISSUE TITLE
Lizard tribal scroll traitor item is too expensive

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7885]
14 TC is way too expensive when we consider its effectiveness. 6 TC might be fair.

If you made a PR to reflect this idea, please put this in your PR.
`* closes #7885`
Then it will automatically close my issue(feature request) here once it is merged.

**Comment by EvilDragonfiend** [comment]
Feel free take this as hectoberfest PR

**Comment by CydiaLamiales** [comment]
You know what's odd? People said the same thing in the comments to the original PR that added the martial art. And yet the price actually got increased from 12 to 14.

**Comment by cnleth** [comment]
I agree that it's way too expensive
