### ISSUE TITLE
Chaplain's ghost role sword shouldn't work during battle royal, because it traps ghosts

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7886]
When BR spawns a chaplain's ghost sword, it shows ghost pop up. If you click it, you're trapped in the sword.
This shouldn't happen as long as a round is finished.
There should be something like `SSround < ROUND_FINISHED`(I forgot the exact define and subsystem) that can make it prevented.

If you made a PR to reflect this idea, please put this in your PR.
`* closes #7886`
Then it will automatically close my issue here once it is merged.

**Comment by PowerfulBacon** [comment]
If this is bugged it just should be fixed rather than make it so people are less likely to use the bugged sword

**Comment by itsmeow** [comment]
Fixed by #8545
