### ISSUE TITLE
Make the Bounty Board from the Newcasters read the ID of the bounty creator

### ISSUE THREAD

**Issue by RubberEyes** [BeeStation/BeeStation-Hornet#7892]
Currently the bounty board does not care what ID you are wearing when you make a bounty; it automatically knows your true name and makes the bounties under that name.
Making it instead read the ID that the bounty maker is wearing will allow antags to create confusion by submitting bounties under the name of other people.

**Comment by itsmeow** [comment]
It goes off your bank account ID, because that is where the payment goes. You would actually need the ID of the other person.

**Comment by itsmeow** [comment]
Maybe if you emag it, it would allow you to enter a fake name when creating the bounty or newscaster channel
