### ISSUE TITLE
CANNOT CURBSTOP MONKEYS (SPEEDMERGE)

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#7914]
i have NOTICED that in a DESPERATE attempt to fulfill my UNBRIDLED RAGE AND BLOODLUST against a MONKEY that i was UNABLE to SMASH their STUPID SKULL IN!!! FIX THIS IMMEDIATELY!!!

**Comment by itsmeow** [comment]
how about you curbstomp yourself some bitches

**Comment by Fronsis** [comment]
Something that i've also noticed is that it's... fairly hard? to properly lift and carry a monke, i think doctors can do it fairly easy thanks to the gloves, but i swear i can't pick a monkey up into my shoulders
