### ISSUE TITLE
All particles target the Thermomachine 

### ISSUE THREAD

**Issue by Hatmagedon** [BeeStation/BeeStation-Hornet#7923]
I made a basic setup to get Stimulum on corg, but as it progressed and eventually became fusion by itself. I noticed that all the particles target the thermomachine.
![image](https://user-images.githubusercontent.com/115571566/196036099-23c1d3fd-0d0e-4b70-ad71-fee31b66fe50.png)
![image](https://user-images.githubusercontent.com/115571566/196036121-55ad6750-c1a9-4c0d-8b47-c76cb229d4b6.png)

Issue reported from  Round ID: 40884 (BeeStation Sage - Roleplay)
Reporting client version: 514.1585

**Comment by Septoxide** [comment]
that isn't fusion, it is the stim ball reaction which eats pluox, stim, nitryl, and plasma to make some energy and also a nuclear particle which only goes up.
