### ISSUE TITLE
Third character slot cannot access beecoin shop

### ISSUE THREAD

**Issue by RussianGenCoke** [BeeStation/BeeStation-Hornet#7925]
Issue reported from  Round ID: 40893 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

Step 1: open third character slot
Step 2: Try to open the shop

Even switching to the other slots then switching to the third in the beecoin shop won't work, it'll still read it as the other slot

**Comment by itsmeow** [comment]
Duplicate of #7864
It's the same issue as I said
