### ISSUE TITLE
Pubby Mining Shuttle disappearing and deleting miners on Pubby

### ISSUE THREAD

**Issue by dog132-ss13** [BeeStation/BeeStation-Hornet#7927]
## Round ID & Round Date: 
40898 on 17/10/2022

## Testmerges:
#7430
#7659
#7500

## Reproduction:

On Pubby, the mining shuttle spawns missing the entire floor and a few walls. (Screenshot is after attempted repairs and launching the shuttle)
![image](https://user-images.githubusercontent.com/76962592/196112700-f6780c50-0618-4b85-9b1f-669b0189d1c6.png)
(Screenshot after landing - the miner got deleted)
![image](https://user-images.githubusercontent.com/76962592/196112850-fc451a68-0930-49c7-8541-38498dc01fd1.png)
Upon further inspection, it looks like all of the other shuttles (apart from the exploration and labour shuttles) have suffered from the same problem.
![image](https://user-images.githubusercontent.com/76962592/196114045-15d1ff50-9469-4603-ac86-d958c1afa2c3.png)

**Comment by itsmeow** [comment]
@The-Moon-Itself @PowerfulBacon

**Comment by PowerfulBacon** [comment]
Hmmmmmm this is probably a combination of our 2 PRs merged

**Comment by PowerfulBacon** [comment]
This issue should be resolved.

**Comment by Denesta** [comment]
> This issue should be resolved.

It is not, just had a broken shuttle on Pubby.
