### ISSUE TITLE
Selecting fourth character slot does not persist

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#7930]
## Round ID & Round Date:
Round ID : 40902
Round date : 10-17-2022

## Testmerges:
[#7430: 'Refactor mentors to use admin ticketing system' by itsmeow at commit 7a827187c4](https://www.github.com/beestation/beestation-hornet/pull/7430)
[#7659: 'Removes some major sleepers (100% lag free)' by PowerfulBacon at commit 95bedebb38](https://www.github.com/beestation/beestation-hornet/pull/7659)
[#7500: '[TG PORT] Space Dragon Rework' by itsmeow at commit 9f14e2e749](https://www.github.com/beestation/beestation-hornet/pull/7500)

## Reproduction:
When finishing a round using the character in the 4th character slot, in the lobby of the next round you'll see that you were swapped over to another character slot.

**Comment by itsmeow** [comment]
Fixed by #8006
