### ISSUE TITLE
You can't leave Hilbert Hotel

### ISSUE THREAD

**Issue by Chirynnn** [BeeStation/BeeStation-Hornet#7950]
## Round ID & Round Date:
N/A

## Testmerges:
N/A

## Reproduction:
Enter Hilbert Hotel, the door does not work and you require an admin's intervention to get you out.

**Comment by Coding-Grape** [comment]
https://github.com/BeeStation/BeeStation-Hornet/blob/d045ce5a79b1b23b40a99d6d7a2a93f4f6c36e69/code/modules/ruins/spaceruin_code/hilbertshotel.dm#L135 

Borbop says explo broke this

**Comment by Chirynnn** [comment]
Bumping, nobody's taken any action on this.

**Comment by PowerfulBacon** [comment]
![image](https://user-images.githubusercontent.com/26465327/210251981-6d6db276-78bd-41e6-9012-25012a2e82f4.png)

**Comment by CydiaLamiales** [comment]
God bless Bacon for finding the actual fix.

**Comment by JukeJukestar** [comment]
![image](https://user-images.githubusercontent.com/76008882/213828960-074f2e58-61db-4114-8a10-eb61b83497aa.png)

its impossible to leave hilberts hotel still as of 21.01.2023

**Comment by CydiaLamiales** [comment]
> ![image](https://user-images.githubusercontent.com/76008882/213828960-074f2e58-61db-4114-8a10-eb61b83497aa.png)
> 
> its impossible to leave hilberts hotel still as of 21.01.2023

Well yes, the fix hasn't been merged yet.

**Comment by CydiaLamiales** [comment]
Well, now it is fixed
