### ISSUE TITLE
Disablening of the Revolution gamemode until it is either improved upon or changed entirely

### ISSUE THREAD

**Issue by Doktor-Wueue** [BeeStation/BeeStation-Hornet#7952]
i make this request , coming from a simple reason: the current revolution gamemode does not fit what Bee is supposed to be: a RP server.
It is a teamdeath match from the start thats  heavly favoured on one side. 
the revolution can recruit pretty auickly with a simple flash, can convert around 90% of the population and most of the time has the numbers advantage and  is allowed to use destructive means to eleminante the Heads of staff and security. this includes big bombs and the like, while security is  only able to react to this, is not allowed any high destructive weaponary and is also mostly under staffed.
another problem is the mindset most players go into: it becomes a basically unga unga rev kil kil  mindset. most rev rounds desolve quickly into chaos and just greytiding and murder.
there are some people who try to RP during a rev round and they mostly end up killed or cannot do anythign ebcause the other turned the station into a hellscape of chaos already were no side has the chance to even rp or be killed.

So i suggest a disbaling of the gamemode until either A. it has been improved to allow for RP  ( change of objective maybe, not just kill or exile heads) or be is reworked in another way to make it fit more into what Bee station wants to be.

**Comment by ImSynthex** [comment]
> It is a teamdeath match from the start thats heavly favoured on one side.

IIRC rev win chances are somewhere in the ball park of 50/50

> until either A. it has been improved to allow for RP ( change of objective maybe, not just kill or exile heads) or be is reworked in another way to make it fit more into what Bee station wants to be

why not just make a request and design doc on how to do this instead of what feels like an ided idea
