### ISSUE TITLE
PDA is not destroyed by Nightmare

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7954]
## Round ID & Round Date:
41003, 2022-10-23 13:58:59

## Reproduction:

Simple. just attack people with light-on PDAs, or just hit the light-on PDAs. It doesn't disappear.

**Comment by St0rmC4st3r** [comment]
Provide all light-emitting things with removable LED bulbs?

**Comment by itsmeow** [comment]
I cannot reproduce this. This PDA is removed.

**Comment by itsmeow** [comment]
Got it, it only happens on PDAs without a primary/secondary card slot due to a runtime
