### ISSUE TITLE
Unreproductable space dragon freezing bug

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#7955]
## Round ID & Round Date:
forgot it. It was around 40998? 40997??

## Testmerges:
Space dragon rework

## Reproduction:
When a Space Dragon tries a tail sweep, they become frozen. They can't move or do something else, and their animation is frozen too.I don't know if it's because of the tail sweep, but It seems.

**Comment by itsmeow** [comment]
For testmerges, the issues should be commented on the PR, not the general repo
