### ISSUE TITLE
Mask kept disappering

### ISSUE THREAD

**Issue by FacePluslll** [BeeStation/BeeStation-Hornet#796]
Issue reported from  Round ID: 9194 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 512.1488

While in the captain's spacesuit and in a burning environment, the gas mask would keep disappearing and seizing to exist after a few moments.

**Comment by zeskorion** [comment]
> Issue reported from Round ID: 9194 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)
> 
> Reporting client version: 512.1488
> 
> While in the captain's spacesuit and in a burning environment, the gas mask would keep disappearing and seizing to exist after a few moments.
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/84014596-mask-kept-disappering?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github).

found the issue
![image](https://user-images.githubusercontent.com/49600480/71640103-a1a5a680-2c38-11ea-8280-3fc29fe91bb8.png)

the hardsuit is coded to show your mask. WHICH HAPPENS TO ALLOW IT TO BURN OFF, ENTIRELY DEFEATING THE PURPOSE

making the fix pr now
