### ISSUE TITLE
spaced tiles rebuilt by an RCD still act as spaced

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#7960]
## reproduction: 
space a tile, rebuild the floor with an RCD, see as the gas in the room is still mysteriously being sucked out.

been a thing for a while, pretty annoying, probably isn't fixed yet since I've done this a while ago and the room i did it to had a case of mysterious gas being sucked out.

**Comment by MaltVinegar** [comment]
Tested this on my own

It only does this if you use the RCD on a lattice directly. On space directly it works as intended
