### ISSUE TITLE
Human monkey players still trip over other people, including ones you're carrying

### ISSUE THREAD

**Issue by RussianGenCoke** [BeeStation/BeeStation-Hornet#7962]
## Round ID & Round Date: 
Don't remember, this happened twice in two separate rounds 

## Reproduction:

A1: Die as a normal player
A2: Get brain transplanted into human monkey

B1: Be normal player
B2: get hit by wiz polymorph into monkey
B3: use mutadone to become human

This is awful, sure it may be funny at first but it'll make the game literally unplayable if you try to fireman carry someone. Fireman carrying another player will cause you to still trip and 'drop' them, but they're still buckled to you leaving you both as siamese twins until they unbuckle themselves. Good luck if you're carrying a soulless corpse.

**Comment by WrillWasTaken** [comment]
You also trip over simple bots like medbots, firebots etc, revenants can also ruin your day by repeatedly knocking you over while incorporeal.
