### ISSUE TITLE
Becoming a swarmer while adminned doesn't automatically deadmin you

### ISSUE THREAD

**Issue by Chirynnn** [BeeStation/BeeStation-Hornet#7963]
## Round ID & Round Date:
N/A

## Testmerges:
N/A

## Reproduction:
Be admin, see swarmer pop up, become swarmer, notice the game didn't automatically deadmin you like with other antags, happened twice to me already.

**Comment by mcmeiler** [comment]
Because swarmers don't have an antag datum associated with them.
