### ISSUE TITLE
Shuttles spawning horribly broken.

### ISSUE THREAD

**Issue by WhereAmO** [BeeStation/BeeStation-Hornet#7967]
## Round ID & Round Date:
Round ID: 41032
October 2022 25th

## Testmerges:

#7659: 'Removes some major sleepers (100% lag free)
#7500: '[TG PORT] Space Dragon Rework'

## Reproduction:

Unsure if can reproduced reliably. I've seen it happen I think three times now on low-pop, unsure on others. Sometimes, it seems shuttles, not all but sometimes a handful, bug out and decide not to fully spawn, instead spawning partially, with dirt and grime just floating on space tiles. When people use these shuttles they get launched into hyperspace and die a slow painful death that's very hard to recover from. 
![Screenshot (1248)](https://user-images.githubusercontent.com/81683771/197746604-507e1eb7-c67f-4e4a-b236-c0918b12ac17.png)
The only idea I have for what could be causing this would be the Sleepers Rework? I know that touched upon spawning things.

**Comment by PowerfulBacon** [comment]
I hate this, why is this happening

**Comment by PowerfulBacon** [comment]
This issue should be resolved.
