### ISSUE TITLE
"Your previous action was ignored because you've done too many in a second" Explorator console.

### ISSUE THREAD

**Issue by Kisiel2255** [BeeStation/BeeStation-Hornet#7969]
Issue reported from  Round ID: 41040 (BeeStation Sage - Roleplay)
Reporting client version: 514.1588

While I was playing as the explorer, and when we were coming back from a, let's say quite chaotic mission, it was my time to lead the shuttle back to our station. When I interacted with the shuttle, "Your previous action was ignored because you've done too many in a second" started spamming in my chat & severely lagging my game. Closing the console window and walking away hadn't solved the issue, only leaving & joining back solved it. If I remember, I think that spam started clogging my chat when I wanted to choose the destination. Not sure if it's something wrong on my side or the game's, but I want to make a report here just in case.

**Comment by EvilDragonfiend** [comment]
Standard TGUI issue. All TGUIs have the same issue. Restarting your client can fix this.
