### ISSUE TITLE
Autolathe materials duplication.

### ISSUE THREAD

**Issue by Shiraizawa** [BeeStation/BeeStation-Hornet#7972]
## Testmerges:
[#7959: 'Bumps Auxmos from 1.1.2 to 2.2.1 and BYOND to 514.1589' by Crossedfall at commit f2370befd6](https://www.github.com/beestation/beestation-hornet/pull/7959)
[#7826: 'Pumpkinpeople - A Halloween special' by DrDuckedGoose at commit fcd6ed1584](https://www.github.com/beestation/beestation-hornet/pull/7826)
[#7659: 'Removes some major sleepers (100% lag free)' by PowerfulBacon at commit 95bedebb38](https://www.github.com/beestation/beestation-hornet/pull/7659)

## Reproduction:

Put 50 iron and glass in the lathe. Try printing something with a lot of material needs, like a compressed matter cartridge. Hit Process and before it finished processing, remove 50 iron from the lathe. The item will still be processed, but your 50 materials remain. Put both the 50 iron and the compressed mat cartridge into the lathe. Free iron.

**Comment by itsmeow** [comment]
epic dupe glitch
