### ISSUE TITLE
Abductors speak out-loud when they get the Tourette's Syndrome mutation.

### ISSUE THREAD

**Issue by oo7craigmc** [BeeStation/BeeStation-Hornet#7980]
Issue reported from  Round ID: 41091 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

![image](https://user-images.githubusercontent.com/48850629/198827913-60f0760e-9ea1-44ed-b85a-c1af49a5b412.png)

**Comment by itsmeow** [comment]
Fixed by #8004
