### ISSUE TITLE
Malf AI can get conflicting objectives

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#7998]
## Round ID & Round Date:
Round ID : 41132
Round Date : 10-31-2022

## Testmerges:

[#7659: 'Removes some major sleepers (100% lag free)' by PowerfulBacon at commit 95bedebb38](https://www.github.com/beestation/beestation-hornet/pull/7659)
[#7826: 'Pumpkinpeople - A Halloween special' by DrDuckedGoose at commit 3a487bfb0f](https://www.github.com/beestation/beestation-hornet/pull/7826)
[#7989: 'Does something' by PowerfulBacon at commit 486a8c3571](https://www.github.com/beestation/beestation-hornet/pull/7989)

## Reproduction:
Become a malf AI and get conflicting objectives : 
One requires you to allow your target to escape on the shuttle, another has you preventing them from escaping.

![image](https://user-images.githubusercontent.com/110184118/199020839-751e9c23-6c9a-4a4c-b627-29398a2b9dbd.png)

**Comment by oo7craigmc** [comment]
Isn't the "protect" objective just to ensure they stay alive?

**Comment by CydiaLamiales** [comment]
> Isn't the "protect" objective just to ensure they stay alive?

Apparently not, they need to escape aswell.

**Comment by EvilDragonfiend** [comment]
This should be fixed as this way:
* pick a mission that needs a target
* get all objectives you have, and check if the target is in those objectives. if they are, pick a new target or make it free obj mission...

**Comment by EvilDragonfiend** [comment]
according to Ruko, it is a yandere combination of two objectives that AI should maroon the target, and is intentional.

**Comment by Fronsis** [comment]
Isn't this the same "protect" that old NT-Ninja(or maybe current) had that made them fail if they take a single damage point? I remember someone mentioned something like that

**Comment by CydiaLamiales** [comment]
Maybe. And, I seriously don't like the code that checks for its completion.
![Uploading unknown-164.png…]()

**Comment by tontyGH** [comment]
#8487 fixed this by the way
