### ISSUE TITLE
Detective is metaprotected on dynamic traitors

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#8009]
If the dynamic.json config actually works properly (config/dynamic.json), then detective is metaprotected on the traitor gamemode due to the example config.

**Comment by itsmeow** [comment]
We should remove the example config from the repo

**Comment by itsmeow** [comment]
I noticed this the other day but didn't spot that the detective shouldn't be there, I was like "hmm... I wonder if this traitor config here will be a problem"

**Comment by itsmeow** [comment]
The dynamic json was not enabled on the server so this was not an issue.

In-repo it could be
