### ISSUE TITLE
Asteroid mining is miserable (oversight, not bug)

### ISSUE THREAD

**Issue by Rukofamicom** [BeeStation/BeeStation-Hornet#8010]
#7552 made PKA much weaker in a total vacuum because miners like to roll for antag just to power fantasy on the whole station. This was a good PR overall, but as @benbot16 pointed out in the last comment before merging... asteroid mining got completely kneecapped. Asteroid miners can no longer fight the mobs that spawn on asteroids effectively at all. 

Not sure what the best way to resolve this might be without either reintroducing the problem #7552 aimed to fix, or introducing awkward z-level dependent physics.

**Comment by mystery3525** [comment]
I'm not sure what you mean, do you mean that if there is fauna on an asteroid, you cannot attack it really well? Or that you cannot physically mine on asteroids (see below)
![image](https://user-images.githubusercontent.com/30960302/199549834-3c056145-a4e7-4883-8535-1e73ebf48276.png)

**Comment by Coding-Grape** [comment]
> I'm not sure what you mean, do you mean that if there is fauna on an asteroid, you cannot attack it really well? 
this one. the asteroid fauna is tanky, and the PKA doing less vacuum damage on the station Z-level because uhhh.... internal pressure wave safeties? would be preferable to completely destroying its damage output for asteroid mining

**Comment by Rukofamicom** [comment]
> I'm not sure what you mean, do you mean that if there is fauna on an asteroid, you cannot attack it really well?

Yes, asteroid goliaths. I'm posting this on behalf of someone else who thought the issue was recognized and intentionally dismissed since it was posted on the original PR shortly before it was merged.

**Comment by benbot16** [comment]
don't forget basilisks, which are _really_ fun to deal with while in a slow mining suit.
