### ISSUE TITLE
Cargo Crew Mail lost the color!!

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#8013]
I've noticed cargo crew mail now has no longer color per department, they're all a single color (i think it's the cargo one), very sad

**Comment by EvilDragonfiend** [comment]
![Screenshot_20221103_201110](https://user-images.githubusercontent.com/87972842/199706394-55c34788-710d-4b64-884c-e6faa91e1e8e.jpg)

https://github.com/BeeStation/BeeStation-Hornet/pull/7559
Sorry, but going to be fixed soon!

**Comment by Penwin0** [comment]
Closing this since it belongs to a TM, author is aware and it was posted in the relevant PR, thanks for making an issue!
