### ISSUE TITLE
Clonepod is weird and has experimental cloner error

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#8017]
## Reproduction:

1. Try cloning someone on Deltastation
2. The clone pod has "Error 104: Experimental pod not connected"
3. Check vars on the pod
4. It doesn't have experimental = true
5. And yet it still wants it anyway
6. What the fuck

**Comment by EvilDragonfiend** [comment]
Experimental needs two experimental components: pod and computer. If any of them is normal one, it works like normal stuff.
Although this looks literally not connected to any pod that should be adjacent to it.

**Comment by EvilDragonfiend** [comment]
Oh, well, so, that's weird enough if two of them were not set to experimental...

**Comment by EvilDragonfiend** [comment]
I assume they scanned their data from experimental clone then copied it from it into the normal clone via a disk. It might be the reason...

**Comment by Fronsis** [comment]
Hmm, just the other day i saw someone complaining that the clonner didn't worked but it was on Meta

However today on a shift(i think i can provide ID round when i wake up) i was CMO and witnessed said failure(on Delta) i believe the only thing i did to the clonner was when a miner came to medbay, asked to have his body saved on a genetics clone disk, he got scanned and then saved into cloning disk, thdn i left the disk on my table and carried on, round passed and figured "maybe he died i'll try inserting the disk and see if it lets me clone him" it didn't(he was alive and tbh i'm not even sure if those backup-on-disk works) later on we really needed the cloner and it was broken as kat described, that's all the interaction the clonner saw iirc

**Comment by EvilDragonfiend** [comment]
![image](https://user-images.githubusercontent.com/87972842/200112070-387f7059-a70e-44f7-a7ce-fe41bf710614.png)

this is how the error 104 message `ERROR_MISSING_EXPERIMENTAL_POD` comes.
* you have synthflesh. `ERROR_NO_SYNTHFLESH` passed.
* pannel is fine. `ERROR_PANEL_OPENED` passed
* cloning pod is not occupied or in progression to clone. `ERROR_MESS_OR_ATTEMPTING` passed
* `experimental` is from computer, `experimental_pod` is from pod. your computer has the var as `1`, but the pod hasn't.

so, the only I can investigate for now is that it had the var turned on (somehow). maybe mapping issue? It's damn weird how the computer can have the var turned on.

**Comment by itsmeow** [comment]
I checked vars, it was off

**Comment by EvilDragonfiend** [comment]
it's really weird. even the code says only experimental var should be turned on to get the error message.
the only thing I saw it last time was:
* Pubby
* they were trying to clone a person who was disconnected recently - showing ? mark on their life hud

**Comment by EvilDragonfiend** [comment]
happened in glowstation. round ID is 41432 or 41431 (sage)
nobody was cloned, and a doctor tried to clone me.
