### ISSUE TITLE
viro door bolt buttons not working

### ISSUE THREAD

**Issue by coronacat** [BeeStation/BeeStation-Hornet#8028]

**Comment by zeskorion** [comment]
> ## Round ID & Round Date: ID: 41233 not sure round date as i crashed later that round
> ## Testmerges:
> ## Reproduction: use the door bolt buttons on i forget which map inside virology. i think the buttons turn on the bolt lights without turning on the bolts themselves because the red lights turned on but you could just open it. this ruined my cult brother round.

if the bolt lights turn on, the doors should be bolted. However, this can't completely lock virology, and medical doctors have access to the outer doors

**Comment by coronacat** [comment]
So the door bolts don't bolt the door if any doctor tries to open it? So why have bolt buttons?

**Comment by zeskorion** [comment]
> So the door bolts don't bolt the door if any doctor tries to open it? So why have bolt buttons?

the interior bolts prevent doctors from opening it. 

or, i may have been dumb and forgotten to access restrict the buttons

**Comment by coronacat** [comment]
the exterior doors to the little cells that viro has, they had the red bolt lights but doctors could just open it reguraly

**Comment by zeskorion** [comment]
doctors are intentionally able to use the exterior bolts

**Comment by coronacat** [comment]
no they just walked into the bolted doors and opened them, they didn't unbolt it or nothing like that
