### ISSUE TITLE
Abductor radio jammer blocks human observation retrieval

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#8029]
If you try to retrieve the agent, you can't, because the jammer in the baton blocks it. There's no way to turn it off either.

Also it seems the "unprocessed specimen" block is still not working 100%, because I tried going into a room with just a guy on the floor and the agent as scientist, it wouldn't let me. Maybe it's including observers or AI eye?

**Comment by PowerfulBacon** [comment]
Ah it includes unconscious people. Jammer fix shouldn't be too hard, just needs priority levels which I should have implemented anyway

**Comment by itsmeow** [comment]
Fixed by #8172
