### ISSUE TITLE
Send Admin Message on Message Monitor Console not working.

### ISSUE THREAD

**Issue by Nosnek199** [BeeStation/BeeStation-Hornet#8032]
Issue reported from  Round ID: 41255 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

The UI no longer switches over to the the admin message UI

**Comment by itsmeow** [comment]
ya I deleted it, I'm going to remake message monitor at some point entirely because it sucks

**Comment by Coding-Grape** [comment]
so you fucked over comms agent without actually fixing the issue you had with it?
very cool!

**Comment by itsmeow** [comment]
You rewrite the entire message monitor alongside rewriting the entire PDA system
It wasn't worth my time for a console that barely gets used.

**Comment by Nosnek199** [comment]
the console IS used by comms agents, which is one of the more popular spawners. you might wanna fix it.

> You rewrite the entire message monitor alongside rewriting the entire PDA system It wasn't worth my time for a console that barely gets used.

**Comment by itsmeow** [comment]
I have made a PR to fix this

**Comment by itsmeow** [comment]
Freedom finally

enjoy comms agent mains
