### ISSUE TITLE
TGChat NTOS bluescreen

### ISSUE THREAD

**Issue by benbot16** [BeeStation/BeeStation-Hornet#8036]
## Round ID & Round Date: 
41262, 11/7/2022

## Testmerges:
unknown, server froze and crashed

## Reproduction:
![image](https://user-images.githubusercontent.com/9423435/200474996-f18193cc-3b15-4e61-977f-4fd991d9603b.png)

People were reporting database failures at the time too.

**Comment by EvilDragonfiend** [comment]
all that thing was because of Dancing machine. I turned it on 3 times, and 3 of them crashed server. I wasn't sure if the machine was really doing it, so I dared it. :trollface:

**Comment by XeonMations** [comment]
The server had experience a total of three lag spikes, each time happened when the dance machine was turned on. The lag stopped once the dance machine was turned off. The fourth lag spike was when I had unwrenched the dance machine.

**Comment by EvilDragonfiend** [comment]
![image](https://user-images.githubusercontent.com/87972842/200475506-c7d6b887-1e7a-4088-a34a-147bb45b8aaa.png)

**Comment by XeonMations** [comment]
This issue happened the following round after the first issue. The dance machine was not involved this time, I do not think.
![image](https://user-images.githubusercontent.com/62395746/200476561-c11ff636-b141-48e0-a966-402ce78a8dd0.png)

**Comment by benbot16** [comment]
There's also some sort of parallax issues going on.** Epilepsy warning for the following:**

https://user-images.githubusercontent.com/9423435/200476741-388b4b24-93a8-4fb7-893b-be84c3b9f0bd.mp4

**Comment by itsmeow** [comment]
This is related to a BYOND bug, we have implemented steps to fix it and will not be disclosing details.
