### ISSUE TITLE
ai shell cannot store item

### ISSUE THREAD

**Issue by coronacat** [BeeStation/BeeStation-Hornet#8041]
## Round ID & Round Date: 
Round ID: 41279
Server Time: 2022-11-08 23:11:05

## Reproduction: 
Play as the ai, get a shell, become engineering borg, try to store items after equipping, fail.

**Comment by itsmeow** [comment]
"Store items"?

**Comment by coronacat** [comment]
No, i am pressing the "Store" button, and also tried pressing the hotkey B. And yes, the tool was selected.

It has worked in literally every other ai shift I have played except for this one. This made me useless when syndicates tried to kill the captain and all of security.
