### ISSUE TITLE
PAI issues

### ISSUE THREAD

**Issue by leif1239** [BeeStation/BeeStation-Hornet#8043]
Issue reported from  Round ID: 41295 (BeeStation Sage - Roleplay)

Reporting client version: 514.1584

![strange](https://user-images.githubusercontent.com/117795804/200991913-d7afe946-d389-4947-a7be-771e0a19f14e.PNG)

PAI issues
sec hud auto enabled without purchase.
med hud auto enabled without purchase.
host scan only works while in users pocket (not sure if thats meant to be or not but seeing as there is a slot on pda's i dont see why it wouldnt work whilst placed into them either)
can view/message all crew with the messenger without the crew manifest or digital messenger software.

i play PAI alot.

i had recently told admins but thought id post it here as well.

**Comment by itsmeow** [comment]
telling admins will not get any of the issues fixed btw

**Comment by leif1239** [comment]
i mean this is the first time ive ever had to bring something up issue wise,  so i didnt know who to ask.

**Comment by Dejaku51** [comment]
> sec hud auto enabled without purchase.
med hud auto enabled without purchase.

known issue, it will be fix in my #6071 

> host scan only works while in users pocket (not sure if thats meant to be or not but seeing as there is a slot on pda's i dont see why it wouldnt work whilst placed into them either)

i'll check it on my PR and fix if necessary 

> can view/message all crew with the messenger without the crew manifest or digital messenger software.

known issue

**Comment by TerryTehCoder** [comment]
> > host scan only works while in users pocket (not sure if thats meant to be or not but seeing as there is a slot on pda's i dont see why it wouldnt work whilst placed into them either)
> 

Whether it's intentional or not, this has been around for a very long time. I honestly can't remember when this wasn't a thing.

**Comment by itsmeow** [comment]
I think this was all fixed
