### ISSUE TITLE
Port Plane Cubes

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#8065]
We really need https://github.com/tgstation/tgstation/pull/69115
However it is a pretty large undertaking. ~~This also fixes problems with clients_by_zlevel not updating properly (which is what causes sound to break for a few seconds when swapping zlevels)~~ Addressed in #8044 
No bounty for this at the moment but if somebody wants to offer one that would be great as it's pretty important especially if we want to have more multi-z maps.

**Comment by Bobbanz1** [comment]
Can give it a shot after having finished the paper port

**Comment by itsmeow** [comment]
@Bobbanz1 sure

also https://github.com/tgstation/tgstation/pull/71668

**Comment by itsmeow** [comment]
Do note that https://github.com/BeeStation/BeeStation-Hornet/pull/8082 exists

**Comment by PowerfulBacon** [comment]
Closing in favour of #8480
