### ISSUE TITLE
Primal Lasso cannot tame Goliaths

### ISSUE THREAD

**Issue by MarMauZag** [BeeStation/BeeStation-Hornet#8073]
## Round ID & Round Date:

41394 - 17.11.2022

## Reproduction:
1. Gather 3 Goliath Hide Plates.
2. Craft Primal Lasso.
3. Use Primal Lasso on Goliath.

**Comment by MarMauZag** [comment]
The description of the primal lasso states that it can tame Goliaths. When used on a goliath it just says that they are a bit too big.

**Comment by benbot16** [comment]
Fixed in #8066, it's due to oview() fuckery with turfs.

**Comment by MarMauZag** [comment]
So i need to light up the area fully?

**Comment by benbot16** [comment]
That should help, but because it's trying to get the visibility from a turf it'll still be a bit finicky to actually make work.

**Comment by MarMauZag** [comment]
Wait no. it is not the light, my friend. I just tested it via server host.
I think that the goliaths that spawn on lavaland are not counting as the thing this is supposed to tame.
@benbot16

**Comment by benbot16** [comment]
ah sorry, forgot about that part of the code since I changed it to use typecaches in my PR.

**Comment by benbot16** [comment]
Just misunderstood the original issue, so I apologized since I gave you bad information. It's fine.
