### ISSUE TITLE
list of multi-z bugs.

### ISSUE THREAD

**Issue by kit-katz** [BeeStation/BeeStation-Hornet#8096]
## Round ID & Round Date:

list of multi-z bugs and issues found during the several glowstation testmerges so far. kat asked me to put this up here
- multiple z-levels bellow you look like one. The darken effect should idealy appear for every z bellow you
- tcomms and netnt do not cross the z levels but you know of this one
- the glowing bits of apcs firealarms and the sort sometimes render on -zs above them this can occur across many zs
- falling trough multiple zs causes runtimes. wue found a consistant way to float on openspace tiles with it. 
- when the ai moves a z the static fog dissapears until the ai moves
- ALEGEDLY - moving light sources on zs bellow you cause visual bugs on the border tile 
- alegedly the multideck power adapter does not initialize properly reqiring engies to manually reconnect it
- shuttles need to dock with roof generated above them if they are not on the topmost floor else they fill with cold air
- i dont think shuttle docking ui has zlevel buttons

## Testmerges:

NEW terrestrial map. Glowstation 0.9... and anything that involves multi-z

## Reproduction:
no

**Comment by itsmeow** [comment]
Move up and move down are jank

**Comment by kit-katz** [comment]
this is now the offical bully kat bug report

**Comment by Gilgaxx** [comment]
From the little I got to experience, it seemed that mesons allow you to see people in lower z-levels through walls. To be tested tho.
