### ISSUE TITLE
cargo balanced ruined a joke

### ISSUE THREAD

**Issue by theqwat** [BeeStation/BeeStation-Hornet#8102]
![its been bothering me](https://user-images.githubusercontent.com/95321941/202935105-19619e3e-ff16-4a40-af3b-91b8c9b59ce8.PNG)
see this^^^ well it was originally 3146... get it... its Pi
please revert so we can have a super funny joke thx (or make it take 3 pi so the math makes sense)

**Comment by EvilDragonfiend** [comment]
it is because SSeconomy multiplies everything by 3.
