### ISSUE TITLE
AI law stating randomly breaking (for just me?)

### ISSUE THREAD

**Issue by WhereAmO** [BeeStation/BeeStation-Hornet#8114]
## Round ID & Round Date:
41476, Nov 24 3:24 AM PST

## Testmerges:

[#7659: 'Removes some major sleepers (100% lag free)' by PowerfulBacon at commit 5ae4a8cfa6](https://www.github.com/beestation/beestation-hornet/pull/7659)

## Reproduction:

Unsure if re-producable, but. I've had this issue two rounds in a row now, where randomly when I click State Laws then State Laws again at a later date, I become unable to ever state my laws with the State Laws button. Reconnecting does not fix this, admins ghosting me does not fix this. Moving to a cyborg shell and stating from there DOES work, weirdly, but then it breaks again for the shell. I tried closing all tabs and reconnecting just in case that was causing it but nope, still borked. Other AI's in a round with multiple (the ID given above) did not seem to have this issue, just me.

**Comment by EvilDragonfiend** [comment]
that might be related to `var/currently_stating_laws`, but I don't see anything that can misbehave with it.

**Comment by EvilDragonfiend** [comment]
`statelaws()` might have gotten a runtime before `currently_stating_laws` becomes false.

**Comment by itsmeow** [comment]
All runtimes relating this appear to be caused by null clients.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/10366817/e28b826f-9eb3-4dae-bcec-280c021cfc75)
