### ISSUE TITLE
Bulk material selling pays barely anything

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#8124]
## Round ID & Round Date:
41506

## Testmerges:
Unknown

## Reproduction:
1. Sell 25,000 glass sheets. 
2. Watch as you get 150 credits for what should probably be worth a lot more than that.

**Comment by MrEloda** [comment]
![image](https://user-images.githubusercontent.com/39443434/229557010-41e92b28-9e55-4b87-8504-08d589c795db.png)
5 * 25000 = 125 000
Ouais petit problème.
