### ISSUE TITLE
Basic Circuits RCD upgrade doesn't apply

### ISSUE THREAD

**Issue by stutwoby** [BeeStation/BeeStation-Hornet#8139]
## Round ID & Round Date:
Not relevant

## Testmerges:
#7659 
#7870 
#7686 

## Reproduction:
Aquire an RCD, mine was printed. Apply a basic circuit RCD upgrade, apply it to the RCD, attempt to print any circuit and see the option doesn't exist.

**Comment by Dejaku51** [comment]
circuit upgrade on RCD works in a way that during construction of APC/air alarm/fire alarm etc you use it on the frame to insert the circuit. it doesn't add any options to the radial menu. its just useful so you don't need to have the boards on you

**Comment by CydiaLamiales** [comment]
What Dejaku said, it's not the modular circuits with programs. It basically works as the engineering borg's electroadaptive pseudocircuit.
