### ISSUE TITLE
modular computers issues

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#8145]
## Round ID & Round Date:
not relevant

## issues:
* Laptop will be automatically updated if a card is inserted.
* Laptop is not capable of downloading notepad program
* Laptop can accept physical scanner job disks, but it can't detect people
* Laptop will be tracked as a PDA message recipient if it is automatically updated.
* Tablet can send PDA message, but it won't be listed in messanger list.
* PDA can send messages even if a card is not inserted. if there's no card, it should be set to no-receive. (there's a related image in dev discord channel)
* opening Direct Messenger seems it can possibly cause MC frozen if it is opened first time. I think it happens when it is a new item.  (not sure how to reproduce... or even not sure if it's true)
* miniprinter has no cooldown
* You can open messainger even if you don't have Network card inside

and nitpicking: PDA chem detect was meant to investigate what's inside of an atom, not getting exact amount of each chemicals inside of a mob. It has no advantage than using health analyzer.

**Comment by itsmeow** [comment]
> Laptop is not capable of downloading notepad program

Intentional, it's meant to be PDA only

**Comment by itsmeow** [comment]
Laptops and tablets havin messengers is #7904

**Comment by EvilDragonfiend** [comment]
adds: you can add gimmick jobs regardless of how it is limited to a round

**Comment by itsmeow** [comment]
> Laptop will be automatically updated if a card is inserted.

Fixed in #8639

> Laptop is not capable of downloading notepad program

Fixed in #8240

> Laptop can accept physical scanner job disks, but it can't detect people

What

> Laptop will be tracked as a PDA message recipient if it is automatically updated.

Fixed in #8639

> Tablet can send PDA message, but it won't be listed in messanger list.

Fixed in #8240

> PDA can send messages even if a card is not inserted. if there's no card, it should be set to no-receive. (there's a related image in dev discord channel)

the image is lost to time, this might still be an issue though

> opening Direct Messenger seems it can possibly cause MC frozen if it is opened first time. I think it happens when it is a new item. (not sure how to reproduce... or even not sure if it's true)

don't think so

> miniprinter has no cooldown

ok

> You can open messainger even if you don't have Network card inside

Hmm.. they don't really use ntnet the same way as regular stuff does, since the app only should connect to the Messaging Server. The intention is to tie all the messaging stuff to that. So yes and no, it probably should check at minimum there is a network card but not if there is network connection
