### ISSUE TITLE
Bluespace Bodybag Duplication

### ISSUE THREAD

**Issue by Tyranicranger4** [BeeStation/BeeStation-Hornet#8155]
## Round ID & Round Date:
N/A

## Testmerges:
#7659 
#7870 
#7686 

Highly doubt it's the result of one of these.

## Reproduction:
Be inside of a ***folded*** bluespace bodybag that's been dropped onto the floor.
Pick up the body bag you're currently inside of with both of your hands.
Have someone else unfold the bag or resist out of it.

Now you should be able to 'use' an invisible bluespace bodybag in either of your hands to infinitely and rapidly duplicate bluespace bodybags.

**Comment by MrEloda** [comment]
This actualy feels like a cool mecanic. BS is what it is. BS
Complicated sciences like that remind me of quantum mecanic, where things really aren't what you think they are.
