### ISSUE TITLE
Syndicate bluespace shuttle capsules can be renamed by ghosts

### ISSUE THREAD

**Issue by Gilgaxx** [BeeStation/BeeStation-Hornet#8169]
## Round ID & Round Date:
N/A (I forgot the round ID, but it was yesterday and I managed to replicate it on my private server)

## Testmerges:
[#7959: 'Bumps Auxmos from 1.1.2 to 2.2.1 and BYOND to 514.1589' by Crossedfall at commit ff5d6f5e84](https://www.github.com/beestation/beestation-hornet/pull/7959)

## Reproduction:
Normally, Syndicate bluespace shuttle capsules are deployed, the traitor setups up the canister and pacman, interacts with the console once to name it, interacts with it again to pilot it.
Problem is that the first interaction, to rename it, doesn't check if the player is living.
![dreamseeker_2rSJ5C4MJY](https://user-images.githubusercontent.com/105242196/205707669-4451b6c3-2327-4772-ba5c-c1619317a8f5.png)
![0E4MMZ2oi9](https://user-images.githubusercontent.com/105242196/205707689-cfdb45f2-ef7b-455f-ade0-433270b93a58.png)
(The name editing box also doesn't have a character limit, while the actual shuttle name does)

**Comment by Tsar-Salat** [comment]
![centre console](https://user-images.githubusercontent.com/62388554/205715809-dcaaaa1d-22c3-44d0-b4c2-83e3bcc7914d.png)
Blueprint popup appears when interacting with centre console for the first time it seems

**Comment by Tsar-Salat** [comment]
I fixed this, close pls @Gilgaxx
