### ISSUE TITLE
Inform players if they are global or local banned

### ISSUE THREAD

**Issue by ike709** [BeeStation/BeeStation-Hornet#817]
We should inform users both when the ban is created and when they attempt to join a server they are banned from if it's global or local. Currently, the messages don't specify.

**Comment by ike709** [comment]
@MarkSuckerberg

**Comment by ike709** [comment]
This includes the admin logs.

**Comment by bloons3** [comment]
@ike709 Counterpoint: This is an administrative issue. The ban message should include if the ban is a server (LRP/MRP) ban or global ban

**Comment by CthulhuOnIce** [comment]
oh yeah ooh yeah lets do it

**Comment by Crossedfall** [comment]
Might be time to actually do this. I'll get something pushed out here soon.
