### ISSUE TITLE
Ability to change location on station in shuttle without launching

### ISSUE THREAD

**Issue by Tsar-Salat** [BeeStation/BeeStation-Hornet#8181]
Changing position would eat: (set moles of plasma * shipsize)

mostly because of how annoying it is to have to relaunch, move out of the silly bubble, then go back in just to move my ship a tile

**Comment by PowerfulBacon** [comment]
You dont have to move out the bubble, you just can immediately press "initiate docking" as soon as you launch

**Comment by Tsar-Salat** [comment]
> You dont have to move out the bubble, you just can immediately press "initiate docking" as soon as you launch

ah, yeah i tried that and it worked...

uh... pretend i didnt make this embarrassing issue
