### ISSUE TITLE
Graphical glitch with new gravitational anomaly effect

### ISSUE THREAD

**Issue by oo7craigmc** [BeeStation/BeeStation-Hornet#8184]
Issue reported from  Round ID: 41703 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

Graphical effect from gravitational anomaly stuck around after anomaly vanished.

![image](https://user-images.githubusercontent.com/48850629/206400992-88472057-3d2d-4074-8ece-4bdf0315a41e.png)

**Comment by CydiaLamiales** [comment]
It didn't vanish naturally, it was neutralized with a remote signaller.

**Comment by benbot16** [comment]
Related to #8082
