### ISSUE TITLE
Resin floor displays weirdly

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#8190]
## Round ID & Round Date:
Round ID : 41724
Round Date : 12.09.2022

## Testmerges:

[#8082: 'Updates our layers to get ready for plane cube, and weather effects' by dwasint at commit b43c4b917d](https://www.github.com/beestation/beestation-hornet/pull/8082)
[#8189: 'Removes some major sleepers, Refactors maploading to be async (100% lag free) 4' by PowerfulBacon at commit 884c35fcbd](https://www.github.com/beestation/beestation-hornet/pull/8189)
[#8123: '[Port-ish] Refactor icon smoothing to use 8-bit bitmasking + new tables and reworked glass icons!' by PestoVerde322 at commit 5740aa7afa](https://www.github.com/beestation/beestation-hornet/pull/8123)

## Reproduction:

Get Xeno turf one way or another, see this : 

![image](https://user-images.githubusercontent.com/110184118/206765646-d06ab65d-c557-4c40-a30e-d019f195d5c2.png)

**Comment by itsmeow** [comment]
probably 8183
