### ISSUE TITLE
Broken plasma thruster sprites

### ISSUE THREAD

**Issue by apple5382** [BeeStation/BeeStation-Hornet#8197]
Issue reported from  Round ID: 41734 (BeeStation Sage - Roleplay)

It would appear that plasma engines on the exploration shuttle have no sprite. it makes upgrading them very problematic.

![image](https://user-images.githubusercontent.com/77378796/206842540-f42fa6af-5772-4e10-ac4a-8bd1de186d2d.png)

Reporting client version: 514.1583

**Comment by PowerfulBacon** [comment]
![image](https://user-images.githubusercontent.com/26465327/206849068-b801653d-e564-41eb-95f1-0d1086f8af6e.png)

**Comment by Penwin0** [comment]
fixed by #8239
