### ISSUE TITLE
Nightmares and Borg Welding Tools

### ISSUE THREAD

**Issue by benbot16** [BeeStation/BeeStation-Hornet#8238]
## Round ID & Round Date:
Multiple

## Testmerges:
Atmos testmerge

## Reproduction:
1. Be borg with lit welding tool
2. Get hit by light eater
3. Entire welding tool goes poof
4. Be sad because you can't get a new one

**Comment by CydiaLamiales** [comment]
I don't think a borg's headlight can be repaired either.

**Comment by Sarchutar** [comment]
> I don't think a borg's headlight can be repaired either.

A borg's headlight can be repaired, just use a normal flashlight (craftable at autolathe) on the borg when its cover is open

**Comment by CydiaLamiales** [comment]
Huh, good to know, thanks.

**Comment by Tsar-Salat** [comment]
> I don't think a borg's headlight can be repaired either.

Go to a cyborg recharger that has had its manipulators upgraded to fix borgs
