### ISSUE TITLE
Bug: Revenants can walk over Salt tiles

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#8243]
Issue reported from  Round ID: 41926 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

![image](https://user-images.githubusercontent.com/76008882/209362931-dd9516a4-1bd8-4204-9e71-8319ec420ae7.png)

Revenants can freely move over piles that have been sprayed with sodium chloride. Needs replication wether they can walk over tiles with holy water.

**Comment by WrillWasTaken** [comment]
Worth pointing out that they can only do it while corporeal.

**Comment by JukeJukestar** [comment]
Thats good to know
