### ISSUE TITLE
APCs hacked by an AI do not look emagged.

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#8244]
## Round ID & Round Date:

41926
23/12/2022
## Testmerges:
[#8231: 'Revert "Bumps Auxmos from 1.1.2 to 2.2.1 and BYOND to 514.1589 (#7959)"' by KubeRoot at commit 96f7ae89d4](https://www.github.com/beestation/beestation-hornet/pull/8231)
[#8201: 'Adds the ability to see most poll types' by PowerfulBacon at commit fb25c679e4](https://www.github.com/beestation/beestation-hornet/pull/8201)

## Reproduction:
Get a combat upgraded or malfunctioning AI to hack an APC. 
Look at the APC.
It does not look emagged.

**Comment by itsmeow** [comment]
@dwasint I'm going to blame the emissives PR for this
