### ISSUE TITLE
Gulag Traps people forever

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#825]
Has been happening since the tgui-next port

## Round ID:

Any

## Reproduction:

1. Get gulagged for any amount of points.

2. Put your ID in the console on the labor shuttle

3. You can't take your ID out, meaning it's impossible to meet the quota and depart from the camp.

**Comment by ike709** [comment]
Does #820 fix this?

**Comment by ivanmixo** [comment]
Fixed. https://github.com/BeeStation/BeeStation-Hornet/pull/1517
