### ISSUE TITLE
Magicproof races cannot wield magic

### ISSUE THREAD

**Issue by gabrielckc** [BeeStation/BeeStation-Hornet#8271]
Issue reported from  Round ID: 42062 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

Attempted to cast Instant Summons (a robeless spell) and use a Staff of Change as an Adamantine golem (note: a magicproof race) wizard. Spell didn't work, and when I tried to use the staff, got a message saying "Something is interfering with the staff of change."

Neither robeless humans or a cardboard golem had any trouble using the staff, and changing to another race fixed both of these issues, so I believe the problem is with magicproof races (such as adamantine golem).

This behavior seems to be unintended since dchat said it used to be possible, and AFAIK magicproof doesn't mean incapable of magic

**Comment by Tsar-Salat** [comment]
Yeah, considering the existence of the heretic chaplain, I don't see why magicproof == unable to use magic. Especially considering how a wizard can turn into any race with the magic mirror

**Comment by EvilDragonfiend** [comment]
chaplain shouldn't be a heretic tbh
