### ISSUE TITLE
Goose "snacks"

### ISSUE THREAD

**Issue by theqwat** [BeeStation/BeeStation-Hornet#8275]
## Round ID & Round Date:42077
 2023-01-02 22:46:57

## Testmerges:
The following pull requests are currently test merged:
[#8264: 'Removes blocks_air' by PowerfulBacon at commit 5f623b4e60](https://www.github.com/beestation/beestation-hornet/pull/8264)
[#8245: 'Pre-generates ruins before explorers arrive' by PowerfulBacon at commit 1b177ec268](https://www.github.com/beestation/beestation-hornet/pull/8245)

## Reproduction:
Butcher a goose and look

![SNACKS 2](https://user-images.githubusercontent.com/95321941/210282884-5e2e8eed-eed4-4d38-ad8e-e821c146cdaa.PNG)
should be along the same lines as the mutant bread problem i reported a little while ago

**Comment by Tsar-Salat** [comment]
Monke fixed this: https://github.com/Monkestation/MonkeStation/issues/706

I'll port it when I get home
