### ISSUE TITLE
agrovated blobzombie AI does not dissable when taken over by a ghost

### ISSUE THREAD

**Issue by kit-katz** [BeeStation/BeeStation-Hornet#8279]
## Round ID & Round Date: 
42104
any blob round really

## Testmerges: 
[#8264: 'Removes blocks_air' by PowerfulBacon at commit 5f623b4e60](https://www.github.com/beestation/beestation-hornet/pull/8264)
[#8245: 'Pre-generates ruins before explorers arrive' by PowerfulBacon at commit 1b177ec268](https://www.github.com/beestation/beestation-hornet/pull/8245)

doubt they are related but you never know
## Reproduction:
enter a blobzombie after it gets agrovated by a crewmember. watch as the previous AI continues to chase that one target it locked on before you entered it

**Comment by kit-katz** [comment]
semirelated note but the blobspore ai is utterly braindead and extreemly unreliable... we should just let ghosts control them. 
at least for better pathfinding if nothing else. they are pathetically weak anyway

**Comment by Inari-Whitebear** [comment]
Might be related to the monkey AI still being there when you implant someone's head/brain to a monkey body?
