### ISSUE TITLE
Supply Console Window

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#83]
Issue reported from  Round ID: 3993 (BeeStation - For Beginners! Low RP Chaotic Fun!)

I the title bar is off screen every time I try to use it making it impossible to use not only in general but after one use. Please fix and I will love you <3 <3 <3 <3

Reporting client version: 512.1467

**Comment by Kerbin-Fiber** [comment]
We've moved over to TGUI-Next since this Issue was made, this probably doesn't happen anymore.

**Comment by yorii** [comment]
![image](https://user-images.githubusercontent.com/7960287/87306117-d95ea680-c517-11ea-992f-10ec7e33763b.png)
Confirmed as stale.
