### ISSUE TITLE
Items/Overlayed Items vanishing

### ISSUE THREAD

**Issue by AliiTea** [BeeStation/BeeStation-Hornet#8342]
## Round ID & Round Date:
42352 // 2023-01-21 06:19:13

## Reproduction:
Just walk around and you will have items/overlays randomly vanish and reappear around you.
https://i.imgur.com/cfxwHVP.mp4

I think it might be this PR but I could be wrong https://github.com/BeeStation/BeeStation-Hornet/pull/8082

**Comment by Memendia** [comment]
I would also like to add in that this can make buttons & other equipment vanish when you need to use it so kinda important to fix
