### ISSUE TITLE
pAI sprite broken

### ISSUE THREAD

**Issue by AliiTea** [BeeStation/BeeStation-Hornet#8353]
While holding a pAI that is using the snake/alien larva skin you get a large white square if you turn left or right depending on which hand its placed in.

![image](https://user-images.githubusercontent.com/11639828/213906386-13e677ec-66a9-418c-bf7d-e697c0ae84a7.png)

**Comment by CydiaLamiales** [comment]
Odd, it seems the icon files for held pets doesn't have icons for the snake facing a certain direction
![image](https://user-images.githubusercontent.com/110184118/213907939-22fbc87c-f34d-4723-b974-dcb3d18223e9.png)
![image](https://user-images.githubusercontent.com/110184118/213907945-a7d5c74b-c7e0-4f07-8ce4-7b29fc05ca41.png)

**Comment by CydiaLamiales** [comment]
There, I made  fix

**Comment by CydiaLamiales** [comment]
Well it's fixed now
