### ISSUE TITLE
Chat is tiny when sidebar loads correctly

### ISSUE THREAD

**Issue by Munsterlandr** [BeeStation/BeeStation-Hornet#8365]
## Reproduction:
Whenever the sidebar loads with the upper and lower segments, the chat area is extremely small. It can only fit about one line on it without scrolling up or down.

I feel this issue could just be because I am running the game on Linux using compatibility tools, but it still feels right to report. I used [This script specifically](https://github.com/Zero-Bits/ss13.sh) to install BYOND on wine. I did try to modify it by adding more fonts, but it didn't seem to work, and seems unimportant to the issue.

**Comment by itsmeow** [comment]
A screenshot please?

**Comment by Munsterlandr** [comment]
Shoot, sorry about that. Here: 
![image](https://user-images.githubusercontent.com/81447509/214054956-63c396b8-e83c-4c8c-b55e-ea413fe02bb8.png)
