### ISSUE TITLE
Remove random species from randomise() in /datum/character_save/proc/randomise

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#8369]
This is driving me insane, because plasmaman exists.

**Comment by EvilDragonfiend** [comment]
Would this solve your insanity? https://github.com/BeeStation/BeeStation-Hornet/pull/8315

**Comment by itsmeow** [comment]
No

**Comment by itsmeow** [comment]
Duplicate of #7863

he is truly driven insane by the plasma, he opens two identical issues
