### ISSUE TITLE
Goliath hide plates have "No Sprite" sprite

### ISSUE THREAD

**Issue by May-Rai** [BeeStation/BeeStation-Hornet#8375]
## Round ID & Round Date:
42410
2023-01-25 

## Testmerges:
None

## Reproduction:
Go to lavaland;
Kill Goliath;
Butcher it;
Goliath Hide Plate has "No Sprite" sprite.

![image](https://user-images.githubusercontent.com/95033055/214507687-cd5eaa7d-d184-4595-98c0-7b0aa9a514e5.png)

**Comment by PestoVerde322** [comment]
Being addressed in https://github.com/BeeStation/BeeStation-Hornet/pull/8374
