### ISSUE TITLE
Lizards can't use digitigrade legs

### ISSUE THREAD

**Issue by KnighTheThrasher** [BeeStation/BeeStation-Hornet#8386]
## Round ID & Round Date:

Don't remember the exact round IDs. (26.01.2023)

Tested it locally too

## Reproduction:
Pick a lizard and select digi legs:
![Untitled](https://user-images.githubusercontent.com/90279618/214931460-81faca2a-14bf-4cae-b654-1d02141ec26e.png)

Doesn't work when round starts:
![Untitled1](https://user-images.githubusercontent.com/90279618/214931913-f49595a4-5a04-42b8-9423-1d1d3f1c28a4.png)

Ashwalkers still use digitigrade legs.

**Comment by Tsar-Salat** [comment]
![click](https://user-images.githubusercontent.com/62388554/214934245-c10467e2-9d2c-4dc6-8aef-ab748633504a.png)

![fucky](https://user-images.githubusercontent.com/62388554/214934199-855c9650-92ae-4027-816a-a44ab79d63ca.png)
wow, yeah this is fucky

Our digi code is decrepit, but this seems like a preferences bug

**Comment by KnighTheThrasher** [comment]
It worked fine yesterday (at least to 4pm, that's when I stopped playing).

**Comment by Tsar-Salat** [comment]
> It worked fine yesterday (at least to 4pm, that's when I stopped playing).

Interesting. Unintentional side effect of #8221?

**Comment by KnighTheThrasher** [comment]
Yep

**Comment by Tsar-Salat** [comment]
Fuck.

**Comment by KnighTheThrasher** [comment]
![Untitled](https://user-images.githubusercontent.com/90279618/215291848-28e206fa-3b99-4390-802c-bcf418322584.png)
That fixes it but im not sure if this is the best way to do that :/

**Comment by itsmeow** [comment]
Fixed by #8505
