### ISSUE TITLE
Various Chaplain's Androids bugs

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#8388]
## Round ID & Round Date:
42430 | 26/01/2023

## Testmerges:
N/A

## Reproduction:

Inability to heal (except using medibots):
1. Be converted to an android using the technophile sect's "Synthetic Conversion"
2. Notice you have entirely human limbs.
3. Take damage
4. Attempt to heal. You cannot heal because bruisepacks/ointment do not work on androids, and you also do not process chems. You also cannot heal using a cablecoil/welder as your limbs are not mechanical.

Vulnerable to romerol despite being robots:
1. Be converted to an android using the technophile sect's "Synthetic Conversion"
2. Be attacked by an infectious zombie.
3. Die.
4. You are now an infectious zombie despite being a robot.

**Comment by Dejaku51** [comment]
> Attempt to heal. You cannot heal because bruisepacks/ointment do not work on androids, and you also do not process chems. You also cannot heal using a cablecoil/welder as your limbs are not mechanical.

pretty sure they are mechanical, even tho they don't look like it

**Comment by WrillWasTaken** [comment]
> they are mechanical

they're human limbs, you cannot repair them with a cable coil or welder.
