### ISSUE TITLE
apid wings are invisible

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#8399]
Round ID: 42448 1-28-23

## Testmerges:merged:
[#8387: 'Derelict shuttle ruins (Custom shuttles save and appear as ruins)' by PowerfulBacon at commit de67265d4b](https://www.github.com/beestation/beestation-hornet/pull/8387)

## Reproduction:
play apid, look at your back, see lack of wings, see that you can still dash, observe how *wing does not work

**Comment by KnighTheThrasher** [comment]
![Untitled](https://user-images.githubusercontent.com/90279618/215286118-6714cd33-4b27-4ef7-8ba8-f07583b32b58.png)
Looks like #8221 broke that too.

**Comment by itsmeow** [comment]
Should be fixed now
