### ISSUE TITLE
Improve Scrubber and Vent placement on GlowStation (In regards to ventcrawling)

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#8417]
Improve vent placement on GlowStation. At the moment its set up in a way where its really easy for vent crawlers to accidentially crawl out! See below an example for good and bad vent placement - Vents should be placed around corners to avoid slipping out due to lag or carelessness

![image](https://user-images.githubusercontent.com/76008882/215908981-9753e23c-3f5d-48f3-aaa3-f33ee8e8c3dc.png)

**Comment by itsmeow** [comment]
Hi, please redirect glowstation issues to the PR #7907 as it has not yet been merged!
