### ISSUE TITLE
deaf people can't see emotes

### ISSUE THREAD

**Issue by Luxlator** [BeeStation/BeeStation-Hornet#8421]
## Round ID & Round Date:

Round 42517 Date 2/1/23 on sage

## Reproduction:

Take the deaf quirk. You are unable to see all emotes except for *waves. *sighs does not show up in chat nor do any custom ones. Making the player have to rely on PDA messages and pen and paper. Never done a github report before so apologies for any jank. Could reword the *sighs and sound based emotes to "you see how [playername] [emote]s."

**Comment by EvilDragonfiend** [comment]
Its because emote has two types:
`*` emotes are vocal types
M key type emotes are visible types

**Comment by Luxlator** [comment]
I can only see some * type emotes and no m type emotes

**Comment by EvilDragonfiend** [comment]
Then I think I said it reversed

**Comment by Luxlator** [comment]
Why does it matter though because custom emotes can be used for "give a thumbs up" or "motions them to follow". Stuff that's vital for someone who can't hear or use ASL.

**Comment by Luxlator** [comment]
If someone could show me how to code it I don't mind writing each little audible emote as "You see how [character name] [emote]s."

**Comment by itsmeow** [comment]
Somewhere deep in the "custom emote" code, you can choose to make an audible or visible emote when you do it. I am not sure how though.

**Comment by itsmeow** [comment]
Ah.
If you do *me and put nothing after it, it appears you can create a custom emote, and it asks if you want a visible or audible emote.

**Comment by itsmeow** [comment]
It seems the default is "visible" however, so it might be a bug with visible_message
