### ISSUE TITLE
Space Sign Language for the deaf please

### ISSUE THREAD

**Issue by Luxlator** [BeeStation/BeeStation-Hornet#8422]
Feature requests are handled in the repository, but you could also discuss your ideas on beestation discord or forums here: https://forums.beestation13.com/

Could be redundant cause of emotes but eh. Space sign language for those who pick up the deaf trait and obviously not for mimes. Also as a language for those with the linguist or multilingual trait would be fun [unless they're a mime].

**Comment by EvilDragonfiend** [comment]
It will be just emote results if they don't know sign language. `xxx uses their hands to express a sign`
Which means it doesn't have to show a language icon for linguist.
If they know it, they will additionally get chat information what they understood.
Mime will not get sign language unless they have deaf quirk.
Mime will break their vow if they use sign language.
Multilingual to this might work.

**Comment by EvilDragonfiend** [comment]
I might want the execution format as `*sign hello, people`
Then it will be:
```
(Normal people) Mr.Deaf expresses unknown signs with their hands.
(Knows sign) Mr.Deaf expresses hand signs: 'Hello, people.'
```

**Comment by itsmeow** [comment]
Just port TG sign language
