### ISSUE TITLE
New Mobs and Changelings swapping disguises are blind for a second

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#8430]
## Round ID & Round Date:
None, tested on local

## Testmerges:
None, tested on local

## Reproduction:

Spawn into the game, see that you're blind for a second.
Or, become a ling and swap disguises.

https://user-images.githubusercontent.com/110184118/216463915-95b0ded2-150d-467e-a057-42656700df07.mp4

**Comment by Fronsis** [comment]
Yeah i started to notice it's very prevalent sometimes when arriving at shuttle(small duration) or when we load a map like Glow(we can't move + blindness) until it stabilizes and fixes itself

**Comment by CydiaLamiales** [comment]
Oh it absolutely is a thing still.
