### ISSUE TITLE
The Cybersun Eva banishes when it spawns or when interacted with

### ISSUE THREAD

**Issue by Rustyfoxb** [BeeStation/BeeStation-Hornet#8449]
The Syndicate officer (one of the hostile expo targets) spawns in with the cybersun eva instead of the one the others spawn in, it is very unique but currently when it spawns it will just banish or spawn only the head of the suit, but when you grab the head it will banish. It only seems to happen when it is spawned by the ruin gen, i spawned it on a private server and i could grab it and wear it fine.
[cybersun.webm](https://user-images.githubusercontent.com/124508780/216825010-935ada84-6f0f-4fb0-ae4a-c1cfe613861c.webm)

**Comment by Dejaku51** [comment]
helmet of the suit vanishing is normal because its not supposed to exist outside the suit itself, im guessing bacon (or someone else) made it helmet instead of the suit by mistake
