### ISSUE TITLE
Durathread crafting issue

### ISSUE THREAD

**Issue by ModestoFaquin** [BeeStation/BeeStation-Hornet#8450]
Durathread currently shows cloth crafting options

![image](https://user-images.githubusercontent.com/83990177/216830896-fbe187e8-30b1-47bf-a57a-e10afedf75fb.png)
![image](https://user-images.githubusercontent.com/83990177/216831353-896c6d52-86e6-4636-b3e5-e1009eb4d34f.png)

Issue reported from  Round ID: 42570 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

**Comment by imsynthex** [comment]
Unable to reproduce this, both with spawned in durathread and durathread spun at a loom
![image](https://user-images.githubusercontent.com/81387903/220461937-c91d8e29-65b4-4ee0-aa2c-506cd5eab3d6.png)
