### ISSUE TITLE
delimber anomly delimbs head and keeps the one alive

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#8473]
## Round ID & Round Date:
2023.2.10.

## Reproduction:
simple. get delimbed of your head by the anomaly

**Comment by Tsar-Salat** [comment]
I've seen this in arms as well. It will remove your arm, and the UI doll shows a missing arm, but you can still switch hands and pick shit up.

I think the delimber anomaly is missing a line or something that should make your body check if that limb is still attached
