### ISSUE TITLE
Sentience ghost roles don't use ghost role cooldown

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#8496]
Taking a sentience spawn (see spiders) does not use the ghost role cooldown that is used in /obj/effect/mob_spawn/attack_ghost(), allowing you to take a spider and then immediately spawn as another, however it should have a 5 minute cooldown after you die as a ghost role befoer you can become one again.
This also applies to the carp portal.

This exists to encourage ghost roles to consider their life and not rush into danger when they can just respawn in a few seconds, often wasting the roles.

**Comment by Rukofamicom** [comment]
I should be taking care of this one by tomorrow, if not tonight
