### ISSUE TITLE
bruise packs not working

### ISSUE THREAD

**Issue by Rukofamicom** [BeeStation/BeeStation-Hornet#8501]
## Round ID & Round Date: 
2-14-2023

## Testmerges:
#8413
#8371
#8404

## Reproduction:

Attempt to use bruise pack when injured and nothing happens. No error message, just straight up nothing. 
Also unable to use on another injured person with a complete lack of message.

**Comment by itsmeow** [comment]
I've had them work just fine very recently.. so not sure about that

**Comment by Rukofamicom** [comment]
Yeah, I'm not sure what was going on here. It affected both @CydiaLamiales and myself. 

We were at CentCom testing the TGUI chat by beating each other with baseball bats, and upon trying to heal damage we were not able to.

**Comment by oo7craigmc** [comment]
WilsonPH and I had the same issue but were only able to replicate it on characters that had been created in the Debug outfit using Select Equipment on a ghost.
The effect persisted even when clothes were removed.

**Comment by Rukofamicom** [comment]
Any runtimes @oo7craigmc?

If you didn't look, are you able to replicate it again and check for them?

**Comment by itsmeow** [comment]
> WilsonPH and I had the same issue but were only able to replicate it on characters that had been created in the Debug outfit using Select Equipment on a ghost. The effect persisted even when clothes were removed.

I think debug characters have their status_flags set to be invincible, which prevents all form of damage, even negative (healing) damage.
