### ISSUE TITLE
Changeling stealth sting removes alt + click function in inventory

### ISSUE THREAD

**Issue by XeonMations** [BeeStation/BeeStation-Hornet#8513]
## Round ID & Round Date: 
42754, 2023-Feb-17

## Testmerges:
https://github.com/beestation/beestation-hornet/pull/8506

## Reproduction:

Become a ling
Get your stealth DNA string extract ability ready
Attempt to alt click into box inside bag
Fail

**Comment by Tsar-Salat** [comment]
Yes. Activating the sting will override inventory hotkeys with the ability hotkey. Deactivate the ability to regain inv hotkey
