### ISSUE TITLE
Glowy and anti glow still doesnt work in genetics

### ISSUE THREAD

**Issue by xurxomario** [BeeStation/BeeStation-Hornet#8522]
## Round ID & Round Date:
Round ID: 42780, 18/02/2023

## Testmerges:
The following pull requests are currently test merged:
[#8506: 'Fixes polls' by PowerfulBacon at commit 9b58e75e01](https://www.github.com/beestation/beestation-hornet/pull/8506)
[#8507: 'Revert "Refactors reagent exposure code, makes exposure methods bitflags"' by Rukofamicom at commit c6c850b6cf](https://www.github.com/beestation/beestation-hornet/pull/8507)
[#7861: 'Resource limiting: cargo supply, roundstart stockpile reductions (Armoury & Med) and limited sleepers.' by PowerfulBacon at commit b2361f8fb5](https://www.github.com/beestation/beestation-hornet/pull/7861)

I am however pretty much certain this issue is way older and not a part of any current testmerge.

## Reproduction:
To reproduce, simply go to genetics and get glowy mutated or activated on you, it will not give any sort of glow. Same goes for anti glow. It has been broken for a while, if i recall correctly. Another commit that mentioned this was #7007 , i think the glitch is arround since then.

**Comment by xurxomario** [comment]
On further research, it appears this only happens if the first time that glowy is applied is via the genetics machine. So the steps to reproduce are, instead:

Get glowy or anti-glow mutated on you from the machine, nothing will happen on neither case. If you at any point use an activator or a mutator, glowy will then be properly applied, even if you disable and reactivate it from the machine directly, but you HAVE to have used either of those for the mutation to work, as activating it while inside the machine will break it.

**Comment by Tsar-Salat** [comment]
Can confirm. This has been in the game for as long as I can remember.

Inject yourself outside the machine if you want it to work properly.
