### ISSUE TITLE
Staff of Storms can stack ash storms on lavaland

### ISSUE THREAD

**Issue by benbot16** [BeeStation/BeeStation-Hornet#8539]
Issue reported from  Round ID: 42818 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

![image](https://user-images.githubusercontent.com/9423435/220198683-6c0e909e-d6b1-40f6-b7dd-811cbe09b50f.png)

Reproduction:
1. Have a storm in progress or starting
2. Use staff of storms
3. Staff spawns another storm instead of dispelling the first one
4. Sometimes, the animation will glitch because of this, making invisible storms

**Comment by Rukofamicom** [comment]
Encountered this myself somewhat recently. 
I'll be looking at fixing this one
