### ISSUE TITLE
Ethereals default to male for certain customization options and emotes.

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#8550]
## Round ID & Round Date:
N/A, Across multiple rounds.

## Testmerges:
[#8507: 'Revert "Refactors reagent exposure code, makes exposure methods bitflags"' by Rukofamicom at commit c6c850b6cf](https://www.github.com/beestation/beestation-hornet/pull/8507)
[#7861: 'Resource limiting: cargo supply, roundstart stockpile reductions (Armoury & Med) and limited sleepers.' by PowerfulBacon at commit cb805cb546](https://www.github.com/beestation/beestation-hornet/pull/7861)

## Reproduction:
Create an ethereal character.
Attempt to customize their underclothing, the options are all male.

Or:

Spawn as an ethereal character.
Use the *sigh emote. It uses the male sound. Ideally it would simply not make a sound.

**Comment by Pirill** [comment]
Seconded. It feels a little jarring to not have a choice in the matter.

**Comment by WrillWasTaken** [comment]
For underclothing customization it appears to be tied to whatever gender the character slot had before they were made ethereal, not always male.

**Comment by itsmeow** [comment]
Gender neutrality PR should fix the clothing options stuff.
