### ISSUE TITLE
Split personalities are returned to the lobby.

### ISSUE THREAD

**Issue by ghost** [BeeStation/BeeStation-Hornet#8560]
## Round ID & Round Date:
42863 | 23/02/2023

## Testmerges:
[#8507: 'Revert "Refactors reagent exposure code, makes exposure methods bitflags"' by Rukofamicom at commit c6c850b6cf](https://www.github.com/beestation/beestation-hornet/pull/8507)
[#7861: 'Resource limiting: cargo supply, roundstart stockpile reductions (Armoury & Med) and limited sleepers.' by PowerfulBacon at commit cb805cb546](https://www.github.com/beestation/beestation-hornet/pull/7861)

## Reproduction:
Roll someone's split personality.
Wait a bit.
Game freezes entirely.
Rejoin the server.
You are now in the lobby, able to join as a completely new or even the same character, which is for obvious reasons an issue.

**Comment by imsynthex** [comment]
Unable to reproduce on a private server, game doesn't freeze and everything works as intended, testmerges don't seem to have anything to do with it either

**Comment by WrillWasTaken** [comment]
odd, both times I rolled someone's split personality recently I had a game freeze and was returned to the lobby
