### ISSUE TITLE
Pools will display drowning messages on dead people

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#8563]
![image](https://user-images.githubusercontent.com/26465327/221020029-03642e34-ea63-47fc-9b4e-b0da259ad765.png)

**Comment by Tsar-Salat** [comment]
Could go for an unconscious/dead message spam fix in general, if you want to tackle this.

/tg/ has something related:
- https://github.com/tgstation/tgstation/pull/59311
