### ISSUE TITLE
Clockcult noise messages visible from the lobby

### ISSUE THREAD

**Issue by HowToLoLu** [BeeStation/BeeStation-Hornet#8570]
## Round ID & Round Date:
Date: 2023-02-24
ID: 42879

## Testmerges:
#7861 (Likely irrelevant to the bug)

## Reproduction:
The Clockcult noise messages, played towards the round end (when the war starts) were visible from the lobby.
![image](https://user-images.githubusercontent.com/22382345/221280122-9434ce9e-26a8-4979-b1de-fa908c83e126.png)

Untested reproduction: Likely all you need to do is be in the lobby by the time the clockwork war starts.

**Comment by HowToLoLu** [comment]
Closing this issue for now, will reopen if I manage to find a reliable reproduction method that can be done easily

**Comment by PowerfulBacon** [comment]
This is reproducible, it happens during the wfinal stages of the arc since it uses to_chat(world,...)
