### ISSUE TITLE
Monkey equipment worn icons are displaced/invisible

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#8573]
## Reproduction:
Become xeno, throw hugger on monke. Or become monke and put on a fashion show.
![image](https://user-images.githubusercontent.com/110184118/221360248-58c979b5-efa3-4a0a-bc27-db1b377f0e09.png)
![image](https://user-images.githubusercontent.com/110184118/221360254-b759e996-594b-44b5-bf8d-e6705a14d4e7.png)
![image](https://user-images.githubusercontent.com/110184118/221360269-aa08b9a2-0f35-456f-a6b3-76e815616656.png)
![image](https://user-images.githubusercontent.com/110184118/221360273-636f5dfc-a476-4227-99ec-1ac7fdc7bbc6.png)
![image](https://user-images.githubusercontent.com/110184118/221360274-0aaba203-eea9-4b3a-93c0-d8f7d60cacb0.png)

**Comment by itsmeow** [comment]
Did #7793 not fix the xeno face?

**Comment by itsmeow** [comment]
Misalignment fixed
