### ISSUE TITLE
RCL Not functioning

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#858]
## Reproduction:

1. Get a rapid cable layer.

2. Grab with both hands.

3. walk along plating, no wires will be layed down behind you.

**Comment by ike709** [comment]
I assume porting things eventually broke it because we're still using the old terrible wiring instead of the new, good wiring. So we need to change it back to the old wiring logic.

**Comment by MarkSuckerberg** [comment]
We've been through this issue about a billion and a half times. The handheld RCL doesn't lay cables automatically, you're thinking of the mech RCL.

**Comment by Cenrus** [comment]
I remember it laying cables behind me automatically, strange.

**Comment by Superyodeler** [comment]
I remember it laying cables automatically in the past.

**Comment by Kerbin-Fiber** [comment]
It was supposed to rapidly lay cables behind you, automatically

[(https://github.com/tgstation/tgstation/pull/29119)](url)

**Comment by Kerbin-Fiber** [comment]
After looking into it, it was changed to be using the Select GUI. I guess someone decided it was too OP with placing wires automatically and now you have to use a GUI that updates depending on the tile under you.

**Comment by eLeCtrOssSnake** [comment]
Idk, it seem as a good thing to wire a lot of stuff, capacity is neet and that's what makes this thing usefull.
