### ISSUE TITLE
Supermatter seemingly delaminates on its own

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#8581]
Issue reported from  Round ID: 42923 (and others) (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

This is going to be incredibly unspecific, so bear with me. On multiple rounds, even a safe straight pipe N2 set-up will run safely for an hour or so before randomly catching on fire with no changes to the system or sabotage involved. O2 levels skyrocket to the point where even with an extended cooling loop, extra scrubbers for oxygen, spacing the crystal, extinguishing it or adding fresh N2 into the loop, it's seemingly impossible to save it from delaminating anymore.

I would very much appreciate any info on this from other Engineers this happened to.

**Comment by Crossedfall** [comment]
Current working theory is that the atmos subsystem paused while the SM subsystem kept processing. Linking the two so the SM doesn't process when atmos is paused could alleviate this issue.

**Comment by Absolucy** [comment]
I thought the current theory was that auxmos made it so scrubbers were more powerful than vents, and when people set the vents to expanded-siphon, they'll eventually overpower the vents and create a psuedo-vaccum?

**Comment by Pirill** [comment]
The scrubber theory MIGHT have to do with it but it's odd that the SM can run fine for an hour before that suddenly breaks. A bit more info from observation shows that the gases behave a bit abnormally too. O2 is generated at a rapid pace, climbing until it becomes the majority gas by far, before starting short and intense burn, then the O2 levels go back down and start climbing again. It's rather weird to see.

O2 climbing during the delam:
![image](https://user-images.githubusercontent.com/29107291/222609692-8a434dad-1580-499d-adf1-1c2cab9dcdb6.png)

O2 reaching the peak intensity before "resetting":
![image](https://user-images.githubusercontent.com/29107291/222609707-96e30c80-8d4b-4a1c-984b-234008126900.png)

**Comment by Crossedfall** [comment]
> I thought the current theory was that auxmos made it so scrubbers were more powerful than vents, and when people set the scrubbers to expanded-siphon, they'll eventually overpower the vents and create a psuedo-vaccum?

There's two parts. If I were asked to arbitrarily assign percentages on the problem, I'd say it's 75% scrubber buff and 25% atmos pausing while the SM SS continues to process what's there, causing a feedback loop.

**Comment by Pirill** [comment]
Alright, new round (43023), new delam, except this time I had so many precautions in place it was possible to stop it...sort of.
The set-up: N2, 5x filters, 2x maxxed out freezers, triple cooling loop. Basic 3 filters set to scrubbing but NOT extended, two extra scrubbers set to extended but only for O2 and plasma. 
![image](https://user-images.githubusercontent.com/29107291/223140191-7798e5b8-9954-410f-bd34-1cd5a031e9b3.png)

I'm not entirely sure what caused it to reach the delam state (possibly messing with scrubbers after adding the extra two), but once it did, turning off the emitters would not stop a slow delam and constant gas generation. Eventually managed to calm it down by dumping a full canister of cold N2 into it, BUT it remained unstable for the entire rest of the shift, making it unusable.

Turning on even a single emitter for a few shots would delam it again. Spacing the SM tile entirely did not help, it just caught on fire again as soon as the floor was replaced. Furthermore, even when it was calm, the numbers were way too unstable for that ridiculous amount of extra cooling. 
![image](https://user-images.githubusercontent.com/29107291/223140840-ad4a5447-37a1-4512-930d-cdcbc419d9b5.png)
It only reached somewhat normal levels after about 10 minutes of being idle, plus scrubbing some of the N2 out and even then, turning on a single emitter would cause it to start burning again.

**Comment by Pirill** [comment]
Round 43139, pretty quick delam this time. Air alarm was never changed to expanded range (in fact we even turned a scrubber off for a while), still caught on fire even with far more cooling than required. Spaced and flooded it with N2 to fix the fire but by the end it could only sustain ONE emitter temporarily even with this utterly excessive cooling set-up and it was still trying to catch on fire. 
![image](https://user-images.githubusercontent.com/29107291/225005812-d8f5cad4-a31f-46ea-99fd-8cdcd9f3b006.png)

At this point I have no idea if these reports even help at all but here we go.

**Comment by HowToLoLu** [comment]
I have found the cause; Gas Miners.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/e837c4c1-6982-474b-b0d2-4d3f4cbd4b06)

Every single time a gas miner mines for gas it forced the system to recalculate turf adjacency due to passing TRUE to `air_update_turf`
