### ISSUE TITLE
Some of the RPD functionality is broken.

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#8590]
## Reproduction:
Pick up an RPD, try to paint an already placed down pipe, realize you can't. Try to place a heat exchanger pipe by clicking on another pipe, realize you can't. Insert the RPD unwrenching upgrade, realize it does nothing.

**Comment by CydiaLamiales** [comment]
Did some testing, if I revered the code for the RPD introduced here
https://github.com/BeeStation/BeeStation-Hornet/pull/8315
Everything worked fine.

**Comment by EvilDragonfiend** [comment]
Going to fix possible within this weekend
