### ISSUE TITLE
Chemical Piping Systems do not accept Space Beer

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#8622]
The chemical piping system does not accept space beer.
You can put it into an input gate/ tank, but it cannot be used in reactions - the game will refuse to pull the chemical.

## Reproduction:

Pour Beer into a chem pipe input, try to use it in a reaction chamber

**Comment by Rukofamicom** [comment]
I bet this is related to to the fact there are two different reagents with the same name. 
The same thing happens with black powder (explosive) and black powder (the dye)

**Comment by Rukofamicom** [comment]
'get_chem_id()' has a problem and I'm not sure how to fix it exactly

```
/proc/get_chem_id(chem_name)
    for(var/X in GLOB.chemical_reagents_list)
        var/datum/reagent/R = GLOB.chemical_reagents_list[X]
        if(ckey(chem_name) == ckey(lowertext(R.name)))
            return X
```

As soon as it finds a matching reagent in the list, it stops searching and returns it. 
We have two chems that have identical names - in both cases one of them will never be found. 

Black Powder `/datum/reagent/colorful_reagent/powder/black`
Black Powder `/datum/reagent/blackpowder` (explosive)

Beer `/datum/reagent/toxin/fakebeer` (hacked cyborg)
Beer `/datum/reagent/consumable/ethanol/beer`
