### ISSUE TITLE
Implement automatic restart vote after a set amount of time

### ISSUE THREAD

**Issue by ike709** [BeeStation/BeeStation-Hornet#864]
For the MRP server only. Also, disguise it as a "change shift" vote like on bay servers to not ruin immersion.

**Comment by qwertyquerty** [comment]
Must be a config option

**Comment by 123chess456** [comment]
Possibly configure it to only work automatically when no admins are on? This shouldn't affect gameplay if it doesn't have to. Shuttle calls are important and fighting over shuttle calls can be a big part of some rounds. Automatic shuttle call votes should be a remedy to a round that should've ended 40 minutes ago but nobody alive can or wants to bother to call the shuttle. It shouldn't be a gameplay mechanic that allows a majority of players (including dead ones) to forcecall the shuttle in a way that would affect the round. IMHO any situation where any automatic shuttle call would be appropriate would be able to be handled by an admin in a better way w/r/t RP instead. E.g. a singulo eats the station and any way to produce a comms console, centcom sends ERT to rescue the remaining people.

**Comment by MCterra10** [comment]
Will port austation's autotransfer subsystem some time today

**Comment by eLeCtrOssSnake** [comment]
I would actually vote no. Why? Oh, yeah admins are busy doing adminbus. no...
