### ISSUE TITLE
Shuttle vote doesn't work

### ISSUE THREAD

**Issue by Tamumus** [BeeStation/BeeStation-Hornet#8657]
## Reproduction:

Crew transfer vote passed, yet the shuttle wasn't called. Happened in other rounds too (but I didn't think of grabbing the IDs).

**Comment by WrillWasTaken** [comment]
this was TMed
[#8586: 'Update to Python 3.11.2, Node 18.14.2, Inferno 8, Typescript 4.9, Yarn 3.4' by itsmeow at commit 18c0c2e124](https://www.github.com/beestation/beestation-hornet/pull/8586)

**Comment by itsmeow** [comment]
Fixed by #8664
