### ISSUE TITLE
Ghost menu duplicate weirdness

### ISSUE THREAD

**Issue by imsynthex** [BeeStation/BeeStation-Hornet#8679]
## Round ID & Round Date:

Multiple, also present on the current round as of writing the ticket: 43099

## Testmerges:

None

## Reproduction:

The issue is duplicates of mobs visible in both the 'orbit' and 'observe' ghost menus, my theory is that this only happens to mobs created after roundstart (midround antags and latejoin crew), if this is the case, reproduction is as follows:

1. Join as latejoin crew
2. Aghost
3. Check the observe menu

I have noticed some inconsistencies however, like it happening to alien larvae in one round, then not happening to a revenant in another. Alternatively I have also seen the bug show up exclusively on the observe menu, as pictured below:

![image](https://user-images.githubusercontent.com/81387903/224515039-6498b00e-f125-4a07-a17b-c92f27f6c74f.png)

Here we can see it happening to someone, selecting the top one will result in you getting a completely black screen short of the ghost HUD while the bottom one works as intended
![1example](https://user-images.githubusercontent.com/81387903/224515103-7e08c898-e70e-4142-b0e4-511f8109d283.png)

![blackscreen](https://user-images.githubusercontent.com/81387903/224515106-2f623622-755b-4e07-b80c-a794843ab96c.png)

Here it is happening in the orbit menu to midround antagonists
![orbitmenu](https://user-images.githubusercontent.com/81387903/224515136-cd7859ce-a3d5-44ef-9e8f-17404c256527.png)

**Comment by imsynthex** [comment]
Also happened 3 times here, round ID: 43101, latejoin
![image](https://user-images.githubusercontent.com/81387903/224515316-a92ae3e9-7628-4c1d-b585-31beef40c969.png)

**Comment by Penwin0** [comment]
This one is awfully common

**Comment by Tsar-Salat** [comment]
fixed in #9615 I believe
