### ISSUE TITLE
Blood duplication with unstable mutagen still makes reaction noise despite being removed

### ISSUE THREAD

**Issue by MrEloda** [BeeStation/BeeStation-Hornet#8710]
When i try to duplicate blood by adding unstable mutagen it instead take the ammount of blood it makes the unstable mutagen diseappear. There is the sound of a reaction but it adds nothing.

So if i inject 5u with a seryngue into a beaker with 20u unstable mutagen, the reaction sound happen and i end up with 5u of blood in the beaker, all the unstable mutagen is gone.

Please be sure that the duplicated blood keeps its blood group, i want to duplicate O- blood ! :(

**Comment by Tsar-Salat** [comment]
#6304

Prospective mentors should be aware of git changes.

**Comment by Penwin0** [comment]
This isn't an issue, the reaction happens because it creates a virus symptom, it just doesn't make additional blood

**Comment by MrEloda** [comment]
I'm an idiot
