### ISSUE TITLE
Unable to splash beakers on safes

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#8731]
## Round ID & Round Date:

Issue reported from  Round ID: 43216 (BeeStation Sage - Roleplay)
Reporting client version: 514.1589
## Reproduction:

Attempting to splash a beaker of acid, thermite or what-have-you on the spare safe in this case only produces a message about the safe being locked. Attempting to throw a beaker at it will splash it on the floor or whatever item is on that tile.

![image](https://user-images.githubusercontent.com/29107291/226359296-e630a44f-bb3a-4139-aa43-c70805a7aa08.png)

**Comment by itsmeow** [comment]
If you splash it on the floor in front of the safe without the computer there it will destroy the safe btw

**Comment by HowToLoLu** [comment]
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/42824f41-b140-4e5c-9392-05b1a61b8e61)
Well, it's also still a problem- and apparently lies in storage code; and was only exposed by #8643

While throwing still works, the safe having to be empty before splashing it by hand is just an annoying bug.
