### ISSUE TITLE
Ghosts able to interact with cryo pods

### ISSUE THREAD

**Issue by imsynthex** [BeeStation/BeeStation-Hornet#8744]
## Round ID & Round Date:
43241
2023-03-22

## Reproduction:

1. Spawn as a ghost
2. Alt click cryo pod while **standing next to it**

![dreamseeker_oqax2j5mc2](https://user-images.githubusercontent.com/81387903/226866822-08abe20b-3e5b-49be-9f40-5f0a2230cfc3.gif)

**Comment by itsmeow** [comment]
yeah this is intended, they can also spin chairs

**Comment by imsynthex** [comment]
I know chair spinning is intended, but opening cryo pods has actual round impact considering you can't escape from them if you're inside and need someone else to let you out

**Comment by itsmeow** [comment]
True. Might actually be a bug

**Comment by Miliviu** [comment]
This was fixed in https://github.com/BeeStation/BeeStation-Hornet/pull/10476
