### ISSUE TITLE
Pubbystation layer adapters are mapped under the floor layer

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#8746]
## Reproduction:
- Go into Engineering
- See pipes
- Frown like :(
![image](https://user-images.githubusercontent.com/29107291/226904878-e517d5a3-698c-4faa-9d4c-4a560556c9f5.png)
![image](https://user-images.githubusercontent.com/29107291/226904901-4896d263-6ed7-458d-b724-e8dd7b729f6f.png)
(I pried out and placed the tile back on the second pic but you get the idea)

**Comment by Tsar-Salat** [comment]
Oops
