### ISSUE TITLE
Supercharged yellow cannot be used in SMES, but normal yellow extract cells can be used in the SMES.

### ISSUE THREAD

**Issue by Bastian0930** [BeeStation/BeeStation-Hornet#8757]

**Comment by Dejaku51** [comment]
Are you sure you activated the crossbreed extract? Like normal yellow extract they need plasma injected (and used in hand i think)

**Comment by Bastian0930** [comment]
This totally could be a issue - I'd have to check later if I did forget it. (I likely did!)

**Comment by Tsar-Salat** [comment]
Can confirm this has been a bug for years.

**Comment by CydiaLamiales** [comment]
Either it was fixed somewhere along the way or @Bastian0930  just forgot to inject the extract with plasma, but it's not an issue atm.
