### ISSUE TITLE
Cult shards can bypass Do not resusicate

### ISSUE THREAD

**Issue by LodedDiper69** [BeeStation/BeeStation-Hornet#8765]
## Round ID & Round Date:
43299, 03-26-2023

## Reproduction:
Step 1: Die
Step 2: Press "Do not resusicate"
Step 3: Get revived anyways
![image](https://user-images.githubusercontent.com/101019561/227785637-3ed7b34e-bb78-4e7a-a01b-f7949cb8f5d2.png)

**Comment by itsmeow** [comment]
using DNR to avoid being cult constructed is cringe

**Comment by Tsar-Salat** [comment]
participating in conversion stuff should be mandatory imo.

I'll look into fixing this within the next month or so
