### ISSUE TITLE
TGUI Botany Seed Extractor window does not autorefresh for certain actions

### ISSUE THREAD

**Issue by mystery3525** [BeeStation/BeeStation-Hornet#8772]
## Testmerges:

https://github.com/BeeStation/BeeStation-Hornet/pull/8404, but its been going on for a while so ignore.

## Reproduction:

1. Open a seed extractor window
2. Put in any seed
3. You need to close and re-open the window for the changes to be reflected

Should be easy to reproduce and track.

**Comment by EvilDragonfiend** [comment]
I will take a look in this
