### ISSUE TITLE
Nuclear disk gets left behind when shuttle launches, always  causing minor nukies victory

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#8787]
As title says, even if you evac safely with the disk on your posession, the nuke disk gets teleported back to station and if there's still a nuclear operative alive it's a minor victory, i remember reading in discord recently some people talking about that weird behaviour and i've experienced it myself

Also something that might be of similar nature

When the explorer nuke goes off the nuclear pinpointer starts going delta a.k.a blinking red and white that wasn't happening before

**Comment by Absolucy** [comment]
This will be fixed by https://github.com/BeeStation/BeeStation-Hornet/issues/8787
