### ISSUE TITLE
Plumbing machinery have invisible input/output ducts

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#8807]
## Occurance Details

Most likely caused by this : https://github.com/BeeStation/BeeStation-Hornet/pull/8266

### Expected Behaviour:
The machines should have red/blue ducts sticking out of them to indicate input and output.

### Actual Behaviour:
![image](https://user-images.githubusercontent.com/110184118/229882946-c3e03655-e1e9-4c13-8a42-81e5b9dd87c8.png)
![image](https://user-images.githubusercontent.com/110184118/229882956-defefdb1-3b8b-4a48-9266-c1e3dcfe8553.png)

### Reproduction:
Place down a plumbing machine, wrench it down, see that it doesn't have any ducts connecting to it.

**Comment by imsynthex** [comment]
Duplicate of https://github.com/BeeStation/BeeStation-Hornet/issues/8766

**Comment by CydiaLamiales** [comment]
oh alright I'll close this then.
