### ISSUE TITLE
Shielded armours break projectile blocking.

### ISSUE THREAD

**Issue by NotACoderSorry** [BeeStation/BeeStation-Hornet#8814]
As the title says, items that should block projectiles, like shields and deswords, don’t when wearing shielded gear like shielded hardsuits or shielded robes, which feels like a bug.

**Comment by PowerfulBacon** [comment]
As in, when the energy shield breaks the desword doesn't deflect lasers or doesn't block bullets?

**Comment by NotACoderSorry** [comment]
Idk about lasers, but neither deswords or mirror shields can block bullets when you have a suit shield, and I know deswords at least are supposed to unless something changed recently.
