### ISSUE TITLE
Fugitives cannot access their own consoles if their IDs are changed

### ISSUE THREAD

**Issue by LodedDiper69** [BeeStation/BeeStation-Hornet#8815]
## Occurance Details

**Round Date:** 06-04-2022

**Round ID:** [43463]

**Testmerges**:
- None

### Expected Behaviour:

I expected that fugitive hunter IDs would still work after putting them into the HOP console, or that they would be able to not need the IDs in the first place.

### Actual Behaviour:

They did not work and they did not have access to their own consoles.

### Reproduction:

Step 1: Be a fugitive hunter
Step 2: Change your ID
Step 3: Lose access to your own consoles

**Comment by itsmeow** [comment]
lmao, why does the ID console remove access that aren't in its list, that's dumb as hell

**Comment by EvilDragonfiend** [comment]
It's because HoP console access overrides the access list of a card - and it can make your access of non-station ID fucked up.

**Comment by EvilDragonfiend** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/6063

kinda closed before
