### ISSUE TITLE
Omae wa shinderu: You can insta-kill people with North Star Gloves from any distance by setting your battlecry to *me

### ISSUE THREAD

**Issue by 123chess456** [BeeStation/BeeStation-Hornet#882]
## Reproduction:

If you set your battlecry on North Star gloves to the emote *me, you can walk up to someone, hit them 40 times, then walk away. The hits do not actually occur until you click through the *me prompts asking you to select an emote. Since North Star Gloves don't have a maximum range, clicking through the prompts will cause you to punch the person no matter where you have gone.

Step by step:

1. Get north star gloves

2. Set battlecry to *me

3. Click on a person ad nauseam

4. Walk away into maint or something

5. Click through prompts

6. Person is dead from north star punches.

**Comment by MarkSuckerberg** [comment]
Working on it already

**Comment by hackerjsimon** [comment]
had to ruin the fun jk thanks

**Comment by Oshibkka** [comment]
had to ruin the fun, this isnt a joke
