### ISSUE TITLE
Turrets are stupid and try firing through walls

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#8836]
### Expected Behaviour:

Turrets should not fire at things they should not be able to see

### Actual Behaviour:

![image](https://user-images.githubusercontent.com/10366817/230776983-2253450d-5e8c-4c52-baa1-2fb6c11f5de3.png)

### Reproduction:

Have AI turret
It tries to fire through walls

**Comment by Absolucy** [comment]
view() seems to be broken with the 515 builds

**Comment by itsmeow** [comment]
Fixed by BYOND
