### ISSUE TITLE
Fland Station maintenance area improperly mapped

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#8844]
## Occurance Details

**Round Date:** N/A
**Round ID:** N/A
**Testmerges**: N/A

### Expected Behaviour:

Avoid a radstorm.

### Actual Behaviour:

Get caught in a radstorm.
### Reproduction:
![image](https://user-images.githubusercontent.com/29107291/230999344-608018b0-c235-4a58-b75d-3645d23a03b9.png)
This small section of "maintenance" just to the left of the surgery room does NOT in fact, count as maintenance for radiation storm protection.

**Comment by PestoVerde322** [comment]
Currently addressing it, closing it when i open up the relative PR.

**Comment by PestoVerde322** [comment]
fixed in #8987
