### ISSUE TITLE
Organ manipulation surgery attempts to feed the inserted organ to the patient

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#8845]
## Occurance Details

**Round Date:** 11/04/2023
**Round ID:** 43542
**Testmerges**: N/A

### Expected Behaviour:

Inserting the organ inside the body.

### Actual Behaviour:

After the organ is successfully inserted, a new progress bar begins which attempts to feed the already-inserted organ to the patient, presumably failing if it's left to complete.

### Reproduction:
Do organ manipulation surgery on the chest. Insert organs.

**Comment by CydiaLamiales** [comment]
Might just be a consequence of this and it won't be the first one
https://github.com/BeeStation/BeeStation-Hornet/pull/8371

**Comment by CydiaLamiales** [comment]
No, nevermind, adding an ISWEAPON flag to the organ doesn't stop the interaction
only other relevant and recent PR I can see is this one
https://github.com/BeeStation/BeeStation-Hornet/pull/8631

**Comment by Tsar-Salat** [comment]
Can confirm it's the edible component.

I'm heavily rehauling that in newfood port. Don't worry about it.
