### ISSUE TITLE
TGUI chat and windows unresponsive.

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#8855]
## Occurance Details

**Round Date:** 12/04/2023
**Round ID:** 43568 (Sage)
**Testmerges**:
- #8784

### Expected Behaviour:

TGUI features working.

### Actual Behaviour:

In hotkey mode, using the Say hotkey resulted in nothing popping up. Using the action bar or reverting the Say Engine to Classic did work. Furthermore, none of the TGUI windows were functioning properly, unable to be moved, resized or closed. This extended to stuff like the orbit menu post-cryo. Someone else in dchat also mentioned their TGUI Say not working so I'm not alone in this at least.

### Reproduction:

No clue, it was just broken the moment I joined the server and I never had any sort of issue like that before.

**Comment by EvilDragonfiend** [comment]
solved now

**Comment by Pirill** [comment]
All fixed by #8856, thank you!
