### ISSUE TITLE
In-game issue report button doesn't follow the bug report template

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#8857]
See https://github.com/BeeStation/BeeStation-Hornet/issues/8848
This seems like it was made with the in-game issue report button.
Any issue reported from a round should follow the bug report template, as it is associated with a round.

**Comment by EvilDragonfiend** [comment]
![image](https://user-images.githubusercontent.com/87972842/231500009-2600de7f-0108-452c-a692-3ec5dcc47a89.png)

window size is cringe too

**Comment by Pirill** [comment]
Brought this up before and I thought the ingame one was updated to match when the Github one got changed but I guess not...

I also didn't notice the ingame issue reporter including the active testmerges, which I thought it did.
