### ISSUE TITLE
Breaking out of a locked hardsuit locker renders it unusable.

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#8858]
## Occurance Details

**Round Date:** 12/04/2023
**Round ID:** 43571
**Testmerges**: N/A

### Expected Behaviour:

Being able to interact with the suit locker normally after resisting out of it.

### Actual Behaviour:

![image](https://user-images.githubusercontent.com/29107291/231495279-ba609383-98a3-4cc6-9dc7-a836a48ccbcd.png)

### Reproduction:
- Have a suit locker locked (in this case by a silicon) while inside.
- Resist out of it.
- Neither the silicon nor the person can use the locker anymore.
- Trying to destroy it fails because the game attempts to place the item inside the open locker, which is full.

**Comment by Tyranicranger4** [comment]
Fixed as of #8970
