### ISSUE TITLE
Emagged cyborgs shouldn't get their MMIs deleted on detonation

### ISSUE THREAD

**Issue by tontyGH** [BeeStation/BeeStation-Hornet#8862]
## How to round remove a cyborg you don't like (as traitor/malf ai)
1. Emag them
2. Order/Force them to self-destruct
3. Their brain is now qdel'd :trollface: 
##
Why? This is incredibly unfair for the cyborg who very likely had no say in either of these things happening to them

**Comment by CydiaLamiales** [comment]
Borg self-destruction was reintroduced with this PR
https://github.com/BeeStation/BeeStation-Hornet/pull/7622

**Comment by itsmeow** [comment]
emagged cyborg specifically have a wayyy higher self detonate explosion power than syndies
