### ISSUE TITLE
Make pirate shuttle console and selling pad indestructible

### ISSUE THREAD

**Issue by Rustyfoxb** [BeeStation/BeeStation-Hornet#8885]
Currently if someone dicides to break the console or pad the pirates get screwed over since not only are they a sitting duck in station z level if they destroy the console (or get stuck in space forever if they were mid transit), if they destroy the pad the pirates lose thier main gameplay feature that is stealing and now are forced to use the data siphon, if thats broken then they can't do anything other then kill and survive.

**Comment by PowerfulBacon** [comment]
Should also note that if the pad is destroyed, they lose everything they sold so cannot win at that point
