### ISSUE TITLE
Deconstructing a Sleeper deletes the medications inside instead of dropping them.

### ISSUE THREAD

**Issue by oo7craigmc** [BeeStation/BeeStation-Hornet#8889]
Issue reported from  Round ID: 43640 (BeeStation Sage - Roleplay)

Reporting client version: 514.1583

See title.

**Comment by oo7craigmc** [comment]
Also, if the chem bags could be able to be placed into the fridges, that would be super.
![image](https://user-images.githubusercontent.com/48850629/232607532-bf33bf5b-3c81-4135-a44f-65ca88b045bc.png)

**Comment by CydiaLamiales** [comment]
Here's the sleeper PR
https://github.com/BeeStation/BeeStation-Hornet/pull/8890

**Comment by CydiaLamiales** [comment]
> Also, if the chem bags could be able to be placed into the fridges, that would be super. ![image](https://user-images.githubusercontent.com/48850629/232607532-bf33bf5b-3c81-4135-a44f-65ca88b045bc.png)

Sure, here
https://github.com/BeeStation/BeeStation-Hornet/pull/8891
