### ISSUE TITLE
The colored lighting of High-Luminosity Eyes is broken

### ISSUE THREAD

**Issue by Absolucy** [BeeStation/BeeStation-Hornet#8917]
## Occurance Details

**Round Date:** 21/04/2023

**Round ID:** 43697

**Testmerges**:
- [#8784: 'SendMaps Beta Test (DO NOT MERGE)' by itsmeow at commit fc13665792](https://www.github.com/beestation/beestation-hornet/pull/8784)

### Expected Behaviour:

A beam of colored light to appear in front of you when the eyes are on

### Actual Behaviour:

Colorless circular lights appear in front of you instead

![23-04-21-1682107753-dreamseeker](https://user-images.githubusercontent.com/65794972/233731623-e80c6dd9-fc73-48df-9497-3679c3f68888.png)

### Reproduction:

Implant High-Luminosity Eyes, set color, turn them on

**Comment by Absolucy** [comment]
I have somewhat of a hunch this is related to https://github.com/BeeStation/BeeStation-Hornet/pull/8785

**Comment by Absolucy** [comment]
it is NOT stale

**Comment by itsmeow** [comment]
Fixed by #9601
