### ISSUE TITLE
Fland station RND Server issue

### ISSUE THREAD

**Issue by Gaddox-The-Destroyer** [BeeStation/BeeStation-Hornet#8936]
Beestation Sage

Round Date: 2023-04-26 
Round Date: 2023-04-26 

Round ID: 43754

On Fland the Server room in science isn't wired properly stopping the general research, from looc chat i learned that this has happened before, the wire from the apc turns to the right one block too far in front of the window instead of the door.

**Comment by PestoVerde322** [comment]
![immagine](https://user-images.githubusercontent.com/75247747/235071177-593cd09c-0b03-4929-b3b2-ee08f50e4163.png)

Currently addressing it, closing it when i open up the relative PR.

**Comment by PestoVerde322** [comment]
fixed in #8987
