### ISSUE TITLE
Ballistic guns missing attached seclite icon

### ISSUE THREAD

**Issue by someone543** [BeeStation/BeeStation-Hornet#8949]
## Occurance Details

**Round Date:** N/A (Local tested)

**Round ID:** N/A (Local tested)

**Testmerges**:
- None

## Bug Details
Attaching a seclite to any ballistic gun will not have its icon updated with the seclite. All other functions with the seclite still work, the only issue is with the attached seclite icon. 
While this isn't a big issue at the moment, it may be a issue in the future if a ballistic gun is added with the can_flashlight var set to true.
### Expected Behaviour:
Seclite icon to appear on gun upon attachment

### Actual Behaviour:
Ballistic gun did not have a seclite icon 

### Reproduction:
1. Due to the fact that beestation currently doesn't have any ballistic weapons with can_flashlight set to true, var edit any ballistic gun to set can_flashlight to true.
2. Attach a seclite to the ballistic gun
3. See no change 

All guns below have their can_flashlight set to true, and should appear in the bottom left corner of the item, like the xray rifle. All ballistics have a seclite attached, but the icon for the seclite is missing.
![NoSeclite](https://user-images.githubusercontent.com/95106800/235118886-6f9348dd-ae61-4693-ba90-1a70f89c7309.PNG)

**Comment by Tsar-Salat** [comment]
If someone ever wants to fix this, pretty sure TG's component did it

- https://github.com/tgstation/tgstation/pull/67517
