### ISSUE TITLE
Rolled incursion an excom at the same time

### ISSUE THREAD

**Issue by JixS4v** [BeeStation/BeeStation-Hornet#8953]
## Occurance Details

**Round Date:** 30/04/2023

**Round ID:** 43832

**Testmerges**:
[#8784: 'Enable serverside 515.1606' by itsmeow at commit 46d9791265](https://www.github.com/beestation/beestation-hornet/pull/8784)
[#8237: 'Refactoring job system, role system, gimmick system, and etc' by EvilDragonfiend at commit f661f8c1b5](https://www.github.com/beestation/beestation-hornet/pull/8237)
[#8950: 'Pepperspray rework (Peppercloud Deployer)' by PowerfulBacon at commit 103a219f14](https://www.github.com/beestation/beestation-hornet/pull/8950)
### Expected Behaviour:

Rolling incursion or excom

### Actual Behaviour:

Rolled incursion and excom simultaneously
![image](https://user-images.githubusercontent.com/61665800/235327473-fb80c576-a605-407b-9911-ea1f72aaba5a.png)
Image at roundend report

### Reproduction:
Irreproductible

**Comment by EvilDragonfiend** [comment]
TM issue. I am working on it. Thank you for the report!

**Comment by EvilDragonfiend** [comment]
I pushed a new commit. It will solve the issue now.
