### ISSUE TITLE
Crew Manifest Borked, related to 8237?

### ISSUE THREAD

**Issue by WhereAmO** [BeeStation/BeeStation-Hornet#8959]
Issue reported from  Round ID: 43839 (BeeStation Sage - Roleplay)
Reporting client version: 514.1589

[#8784: 'Enable serverside 515.1606' by itsmeow at commit 46d9791265](https://www.github.com/beestation/beestation-hornet/pull/8784)
[#8237: 'Refactoring job system, role system, gimmick system, and etc' by EvilDragonfiend at commit 3cb7104f8f](https://www.github.com/beestation/beestation-hornet/pull/8237)
[#8950: 'Pepperspray rework (Peppercloud Deployer)' by PowerfulBacon at commit 103a219f14](https://www.github.com/beestation/beestation-hornet/pull/8950)

Round-start Crew appear to not appear on the manifest, but late-joins pop up properly, probably related to the Job Refactor.

![Screenshot (26)](https://user-images.githubusercontent.com/81683771/235342777-eed8756d-c46c-4167-b6be-28048646dfc6.png)
![Screenshot (28)](https://user-images.githubusercontent.com/81683771/235342779-31659118-32f4-4424-9fdd-2ba0e0d28369.png)

**Comment by EvilDragonfiend** [comment]
yeah I did something wrong again from fixing nuki thing. I am on it.

**Comment by WhereAmO** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/81683771/235342858-31b0715f-e490-4091-aed9-ad3792ec9568.png)

Also Medical and Security records!

**Comment by itsmeow** [comment]
Very obviously TM related issues should probably go in the Discord

**Comment by WhereAmO** [comment]
Bacon told me to make an issue >:(

**Comment by PowerfulBacon** [comment]
I said post or on the PR page if its related to the TM. Very obvious TM related issues should go on the PR
