### ISSUE TITLE
Player panel throws a weird runtime

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#8978]
![image](https://user-images.githubusercontent.com/87972842/235812602-244580b8-8366-416d-b64a-515a55865c52.png)
![image](https://user-images.githubusercontent.com/87972842/235813367-5e2d9daf-b0d0-42d9-b5a1-de6f54ab49f1.png)

runtime screenshot is given by Cydia (WilsonPH)

a mindless mob seems to be occupied by a player

**Comment by Absolucy** [comment]
> The logic shouldn't allow ghosts to pass line 48 if check becasue they're not literally human, but somehow it seems they made to pass it.

the pink circle is `user`, not `player`, that's how.

**Comment by EvilDragonfiend** [comment]
> > The logic shouldn't allow ghosts to pass line 48 if check becasue they're not literally human, but somehow it seems they made to pass it.
> 
> the pink circle is `user`, not `player`, that's how.

Ah, right, you're right.
but I still can't follow the logic. It means a player had a mob but that's mindless. quite something wrong

**Comment by EvilDragonfiend** [comment]
well, might not be an issue for now...
