### ISSUE TITLE
Records cant be edited through hudglasses

### ISSUE THREAD

**Issue by Tsar-Salat** [BeeStation/BeeStation-Hornet#8985]
## Bug Details
Ususally you are able to edit people's records like sanity or arrest status and whatnot through hudglasses, it doesnt function right anymore.

### Expected Behaviour:

Being able to modify records through hudglasses

### Actual Behaviour:

"Too much time has passed"

Basically, this is something I messed up in #8797 

I was calling worldtime wrong or somethin

Working on a fix rn

**Comment by EvilDragonfiend** [comment]
I think you only missed it in medical records. Only medical stuff seems not working.

**Comment by EvilDragonfiend** [comment]
![image](https://user-images.githubusercontent.com/87972842/236387686-6810fbbf-236a-4a80-895f-3b8690e730a3.png)

**Comment by EvilDragonfiend** [comment]
It sends 0 second examine time, and you can do that until 1 minute is passed which is possible on early-roundstart in your local server.
