### ISSUE TITLE
Sentient Beepsky is unable to stun.

### ISSUE THREAD

**Issue by MalevolentBacon** [BeeStation/BeeStation-Hornet#9012]
## Occurance Details

**Round Date:** 11/05/2023

**Round ID:** 43999

**Testmerges**:
- #8784 
- #8748 

### Expected Behaviour:

Sentient Beepsky should function similarly to simplemob beepsky. It should apply stamina damage similarly.

### Actual Behaviour:

Sentient Beepsky is entirely unable to utilize its baton functions. While it remains able to cuff a stunned individual, it cannot actually stun anyone.

### Reproduction:

While I assume any form of sentient beepsky likely has this issue, the instance that I witnessed was the result of a random animal intelligence event. Triggering a random animal intelligence event that puts a player into a beepsky should replicate this issue.

**Comment by imsynthex** [comment]
My b, I'll probably get on fixing this tomorrow

![TkRsc1OHNl](https://github.com/BeeStation/BeeStation-Hornet/assets/81387903/5116d80f-fa7d-4c42-89ec-ecedcd67be44)
![U6kfZLkjAq](https://github.com/BeeStation/BeeStation-Hornet/assets/81387903/488eed67-570f-4e77-80fc-26f980eac789)
