### ISSUE TITLE
Voice of God doesn't work

### ISSUE THREAD

**Issue by CydiaLamiales** [BeeStation/BeeStation-Hornet#9042]
## Bug Details
Have the Voice of God inserted into your mouth, try saying any of the key words, get nothing.
### Expected Behaviour:
Different effects occuring based on the keywords + text being in big red font and a loud sound playig.

### Actual Behaviour:
You just say things normally.

### Reproduction:
Obtain Voice of God through any means, have it inserted into you, try speaking any of the key words, get no results.

**Comment by St0rmC4st3r** [comment]
Did you use .x or whatever the tag is?

**Comment by CydiaLamiales** [comment]
Is a tag needed now? It wasn't needed before.

**Comment by PowerfulBacon** [comment]
There should be an action button at the top left of the screen, rather than using chat

**Comment by CydiaLamiales** [comment]
Yep, that button's there, I'm a blind idiot.
