### ISSUE TITLE
a chat message sometimes doesn't appear on TGUI chat, but appears on runechat

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#9050]
title.

It's not reproducible.

When you say a chat message, a runechat appears on you, but you see no chat log in your TGUI chat log. It's unsure if it's only applied to your chat, or it happens to other people's chat too.

It happens rarely but sometimes happens.

**Comment by Tyranicranger4** [comment]
This isn't exclusive to runechat in my experience. Sometimes I'll Asay/Dsay something and the message doesn't show up in my chat, but it's clear that it's displayed for other people and it still shows up in logs and everything.

**Comment by EvilDragonfiend** [comment]
> This isn't exclusive to runechat in my experience. Sometimes I'll Asay/Dsay something and the message doesn't show up in my chat, but it's clear that it's displayed for other people and it still shows up in logs and everything.

at least it's not a worst scenario then, just disrupting.

**Comment by itsmeow** [comment]
Probably related to react rehydration key collisions in the chat view.

I think the chat keys are randomly generated, so very rarely they can share the same key as something in the history and react will fail to render it because it matches an existing key.

**Comment by itsmeow** [comment]
Looking at the chat renderer there's no way it's that since it doesn't use react to render traditionally I think? It appends html to a node manager thing

**Comment by PowerfulBacon** [comment]
This is a byond issue

**Comment by EvilDragonfiend** [comment]
Lucy is handling.
