### ISSUE TITLE
CTD when using universal recorder

### ISSUE THREAD

**Issue by DarnTheMarn** [BeeStation/BeeStation-Hornet#9058]
## Occurance Details

**Round Date:** 20/05/2023

**Round ID:** 44110

**Testmerges**:
- None

## Bug Details
Opening up a printed universal recorder transcript crashes the game. If I had to guess, the recording I had went on for a few minutes and might have passed the 5,000 character limit imposed on paper which causes the crash.
### Expected Behaviour:
I expected to pull up the paper transcript of the audio.

### Actual Behaviour:
The game locks up permanently, I have to ALT F4 and reconnect.

### Reproduction:

1. Right click start transcript on a universal recorder
2. Let it run for around a minute in a somewhat noisy area, in my case it was the brig
3. Right click stop the recording
4. Right click print transcript
5. Activate the transcript, and voila your game has been crashed.

**Comment by itsmeow** [comment]
Port https://github.com/tgstation/tgstation/pull/69121
