### ISSUE TITLE
Void heretic cloak not hiding correctly

### ISSUE THREAD

**Issue by XeonMations** [BeeStation/BeeStation-Hornet#9063]
## Occurance Details

**Round Date:** N/A

**Round ID:** N/A

**Testmerges**:
- None

### Expected Behaviour:

Once the hood is pulled up, both the hood and cloak are not visible in the strip menu.

### Actual Behaviour:

Once the hood is pulled up, only the cloak is hidden, the hood is fully visible in the strip menu.

### Reproduction:

Put on void cloak, pull hood up. Cloak is hidden from strip menu, hood stays.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/f51b14dd-7aaa-40b2-a458-a49611d3f7d7)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/8aad2750-453e-4568-a189-e24d13667e91)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/62395746/ba41c65b-1896-44c2-945d-14ed3e107820)

**Comment by DatBoiTim** [comment]
Waiting on reviews. I've provided testing evidence for the fix. It's in maint's hands now.
