### ISSUE TITLE
Cult Pylons do not affect IPC's 

### ISSUE THREAD

**Issue by Sun-Soaked** [BeeStation/BeeStation-Hornet#907]
## Reproduction:
Become a cultist as an IPC, stand near a pylon while wounded(damaged?)

I asked an admin and they stated it was a code issue, and not intentional, so i'm going to make this on the assumption it isn't . IPC cultists do not heal(repair?) automatically when near a pylon, despite it seemingly being a non-contextual magical effect, which I discovered to my chagrin. They seem to additionally not benefit from other normally non-discerning general healing effects(most of which also normally effect synths and fully-augmented humans), such as Medgun beams.

**Comment by St0rmC4st3r** [comment]
Well, they have no blood to conduct the blood magic, so it seems logical. Blood draining spells don't work either.

**Comment by Sun-Soaked** [comment]
Issue is, by that logic, technically IPC's shouldn't be able to cast cult spells, either. Or perhaps should explode into a filled shard like other synthetics when converted in an offering rune.

**Comment by Sun-Soaked** [comment]
Hmm... that might be a better fix, now that i think about it. Though IPC players will probably be salty.

**Comment by Guestratem** [comment]
as a replacement you could make IPC cult members be repairable by the artificiers
