### ISSUE TITLE
Custom, Mining and Exploration vendors do not vend into hand

### ISSUE THREAD

**Issue by imsynthex** [BeeStation/BeeStation-Hornet#9072]
### Expected Behaviour:

Buying something from these vendors should put the item in your hand

### Actual Behaviour:

The bought item spawns on top of the vendor

### Reproduction:

Buy something from one of the aforementioned vendors

**Comment by St0rmC4st3r** [comment]
Ah. Yes. Those. The only vendors that aren't actually vendors at all. Yeah, this should be fixed. Ideally merged into normal, decent vendors.
