### ISSUE TITLE
Pun Pun

### ISSUE THREAD

**Issue by Bleueue** [BeeStation/BeeStation-Hornet#9096]
Issue reported from  Round ID: 44221 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Pun Pun is stuck in the surgery room and keeps going to the same corner even while asleep

**Comment by itsmeow** [comment]
Can you please give more context. What is the issue? Why is it happening/when? How is it a bug? What is supposed to happen? Has this occurred more than once?

**Comment by katelynf05** [comment]
We fixed it, so it isn't really required anyways. Pun pun was unable to be dragged while asleep or awake and repeatedly moved back to the same tile when they shouldn't have been able to (they were asleep). We weren't sure why it was happening, but we figured it was a bug as, again, the monkey was asleep. I believe when you drag the monkey that is asleep, it is supposed to move. It happened about 10 times. I woke them up and put them back to sleep and it was fixed.

**Comment by Fronsis** [comment]
Oh i don't think this is particullary anissue with Pun Pun, iirc this is an old bug regarding monkey/humanized monkey ai where they get FIXATED on moving on a particular direction no matter what, if i remember correctly it even happened while the bodies of the monkey/humanized monkey were dead, like i remember we even delimbed one into a nugget with no head and it still kept crawling it was a fun time for a ''haunted body'' moment but yeah it must be a weird bug with ai pathing and behaviour

**Comment by HowToLoLu** [comment]
> Can you please give more context. What is the issue? Why is it happening/when? How is it a bug? What is supposed to happen? Has this occurred more than once?

I found the same issue as well a week or two ago- monkey killed for heart donation, anesthetics and a stasis bed involved. Then suddenly *wham*, monkey's running for their life into the corner and somehow living without a heart. Not sure whether we used the regular N2O tank or morphine (Leaning towards morphine though)
