### ISSUE TITLE
Luminiscent Eyes Implant Light pathing bug + color selection bug

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#9105]
I was a spawned Fugitive which starts with that as a base implant, upon turning it on this is how it illuminated: 
![Screenshot_17](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/4facd349-1efd-4d5f-b189-6f007aa53f0a)

Also you can't change the color of the light, the only thing the color selector thing does is to change your eye-color but.. i guess it's supposed to also change the light color akin to how the borgs can do it?

**Comment by Fronsis** [comment]
Apparently @PowerfulBacon pr about underlay lighting broke it

**Comment by Fronsis** [comment]
Talked about it yesterday and i think this only got flagged as stale because it didn't had the triaged tag @PowerfulBacon Kat told me your light pr caused it

**Comment by PowerfulBacon** [comment]
This is fixed now
