### ISSUE TITLE
Replace roundstart cyborg with positronic brains on join menu

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#9133]
The late-join menu should show positronic brains.
This should replace being able to late join as a cyborg.

**Comment by JixS4v** [comment]
Not a bad idea actually, but it relies too much on there being a roboticist

**Comment by Crossedfall** [comment]
> Not a bad idea actually, but it relies too much on there being a roboticist

I find that to be a non-issue.

**Comment by MarkusLarsson421** [comment]
> Not a bad idea actually, but it relies too much on there being a roboticist

If there is no roboticists there would be no positronic brains.

**Comment by Programs-The-Station** [comment]
Implementation Question / Theory: Would we put one button on the join menu labeled "Positronic Brains"?

I see a slight potential issue. 

There is at least one Exploration ruin that spawns with a positronic brain. Additionally, free golems can also create positronics. If we have one button, would it be random in which positronic you enter? Getting stuck in a positronic brain in an explorer room sounds like hell, unless you absolutely know that the explorers are nearby.

Or, we could limit it to only on-station positronics.

What if we added a "ghost roles" section, which showed all positronics available as a count? Clicking the button would prompt you to observe to select a positronic.

Rambling/spitballing below:

Theoretically, you could expand it to show ghost roles above the normal amount of spawns (I.E. Number of Ashwalker Eggs - 3 starting ones or Number of Free Golem Shells - 4 starting shells), as that would keep the normal spawns hidden unless they are active, allowing for in-game ghosts to get higher priority. If there are more than the starting, then obviously they are active,  so there will be enough spawns to go around.

This would cause a metagaming issue though, in seeing what potential antags are active (IE, Ashwalkers, Swarmers, Man-eaters)...  Hmmm... 

I guess leaving off the other ghost spawns would still work though, and leaving that framework in place would allow for other crew-aligned ghost spawns...

**Comment by MarkusLarsson421** [comment]
Limiting it to station Z-level positronics would probably be the simplest and best solution.

**Comment by Programs-The-Station** [comment]
(This should probably be closed with the merging of #11162 )
