### ISSUE TITLE
Thrown mobs are not properly logged

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#9153]
#8587 changes [thrown_thing] to [I]

https://github.com/BeeStation/BeeStation-Hornet/pull/8587/files#diff-165e6ab6f4cc50403ccafadb2b65598b85da558d23254a2e6a43f9dcea34d367L173

This causes a bug where if a mob is thrown it logs a null thrown entry

Fix is simple, change it back

**Comment by itsmeow** [comment]
@CydiaLamiales

**Comment by CydiaLamiales** [comment]
fug
