### ISSUE TITLE
ic_filter_regex should be separated into two types: ic filter & netspeak

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#9168]
netspeaks like lol lmao etc should only be prohibited in actual sayings, and sometimes be allowed to some geek/nerd characters or clowns.

netspeaks are actually filtered by `ic_filter_regex `, and you even can't use netspeaks in papers or PDA message stuff. It doesn't make sense.

related macro `CHAT_FILTER_CHECK`

**Comment by PowerfulBacon** [comment]
Paper and PDAs use the OOC filter I believe rather than the IC filter, which filters banned words rather than immersion breaking words.

**Comment by EvilDragonfiend** [comment]
> Paper and PDAs use the OOC filter I believe rather than the IC filter, which filters banned words rather than immersion breaking words.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/8a332251-9b66-462c-89da-7e0283f5a58e)

It seems it's a bit inconsistent

**Comment by itsmeow** [comment]
It's quite consistently set to IC filter on anything your character writes text into.

A second filter for speech vs messaging is needed, and something I have discussed. It would be fine, just needs a bit of collaboration with the admin team, so we would be open to such a PR.
