### ISSUE TITLE
Radiation Storm is not visible in some areas

### ISSUE THREAD

**Issue by BriggsIDP** [BeeStation/BeeStation-Hornet#9171]
## Occurance Details

**Round Date:** 04/06/2023

**Round ID:** 44336

**Testmerges**:
- None

## Bug Details

radiation not visible in the brig, yet still caused ill effects. I don't believe this is a map issue since the effects still applied.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/107176252/41d5ede4-ebf0-4d7b-bbc2-6ecb7be93cf2)

### Expected Behaviour:

the greens radiation visual to appear in brig

### Actual Behaviour:

no visible indication 

### Reproduction:

unknown

**Comment by HowToLoLu** [comment]
I noticed this as a ghost as well- it seems to be an area by area basis, and moving into the areas made the lingering effect go away. Still not entirely sure what causes it to not be removed in the first place though.

**Comment by HowToLoLu** [comment]
I've looked at it- and this is probably an issue with BYOND itself since all that's done for visuals in code is changing the icon state of areas affected.

**Comment by PowerfulBacon** [comment]
This happened with the new system and was entirely client sided. Removing overlays from an area on the server caused those changes not to be communicated to clients that were inside of that area. This appears to be a Byond issue.
