### ISSUE TITLE
Infinite 'ghetti

### ISSUE THREAD

**Issue by theqwat** [BeeStation/BeeStation-Hornet#9173]
## Occurance Details

**Round Date:** 6/4/2023

**Round ID:** 44338

**Testmerges**:
i think we have some... i need to double check my chat log doesnt go that far back

## Bug Details
Information that may be important is that this is done with the spawned spaghetti on fland station
### Expected Behaviour:
put the spawned in spaghetti into the microwave... cook it... get cooked ghetti

### Actual Behaviour:
put the spawned in speghetti into the microwave... cook it... get cooked ghetti and uncook spaghetti out

### Reproduction:
do nothing but cook speghetti for 3 days

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/95321941/9ff02a7b-527e-41a1-bb93-70e2821a56bb)
i will now cook speghetti until this stops and post the end later

**Comment by theqwat** [comment]
Update 
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/95321941/c2eb9b5a-8c09-412f-a24c-193fa537acb0)
its with all ghetti... so im going to do this exponetially now

**Comment by theqwat** [comment]
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/95321941/985d4521-b097-4dcf-be19-7054b447d388)
more experimenting it seems like the cook proc is just broken or something because even fires can cause the dupe to happen

**Comment by Tsar-Salat** [comment]
fixed in #9066
