### ISSUE TITLE
Incursion Radio not granted

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#9179]
## Occurance Details

**Round Date:** June 5 2023

**Round ID:** 44355

**Testmerges**:
- None

### Expected Behaviour:

Having syndi radio on :t

### Actual Behaviour:

Not having it

### Reproduction:

N/A

**Comment by Absolucy** [comment]
https://github.com/BeeStation/BeeStation-Hornet/pull/9090

**Comment by itsmeow** [comment]
Why did they merge this
