### ISSUE TITLE
Power alarms are showing up in places that are fine, power-wise.

### ISSUE THREAD

**Issue by oo7craigmc** [BeeStation/BeeStation-Hornet#9230]
Issue reported from  Round ID: 44473 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/48850629/be3ce70a-e3d7-42b6-bb65-da2c36a3a6b1)

**Comment by Pirill** [comment]
In my experience the alarm monitor on the whole tends to be rather unreliable with updating for alarms but I can't really pinpoint a consistent cause.
