### ISSUE TITLE
Ethereals without a biological battery display the wrong tooltip

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#9233]
## Occurance Details

**Round Date:** N/A
**Round ID:** N/A
**Testmerges**: N/A

### Expected Behaviour:

Something different I guess.

### Actual Behaviour:

See title:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/29107291/9add5999-f947-4e9b-b358-bb7561145d70)

### Reproduction:

- Lose your battery (in this case through faulty cloning);
- Look at the tooltip that comes up;
- 🐈

**Comment by CydiaLamiales** [comment]
Ethereals are secretly robots
deepest lore
