### ISSUE TITLE
Removing titanium floor tile variant creates a wrong tile item

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#9251]
## Occurance Details

**Round Date:** N/A
**Round ID:** N/A
**Testmerges**: N/A

### Expected Behaviour:

- Getting a white titanium floor tile item.

### Actual Behaviour:

- Midas' touch.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/29107291/e28af499-eb7d-4591-8f3f-57549559a2f3)

### Reproduction:

- Crowbar out the smooth white titanium tiles.
- This issue _might_ apply to other variants as well but I haven't tested them, hence the vague title.
- 🐈

**Comment by CydiaLamiales** [comment]
Is it a custom shuttle or a bought one?

**Comment by Pirill** [comment]
> Is it a custom shuttle or a bought one?

It was a BYOS, but the floor tiles were created and placed manually so it's not a shuttle thing.
