### ISSUE TITLE
[Bug]: Unencoded text input in ID console

### ISSUE THREAD

**Issue by DrPepperIsSpicy** [BeeStation/BeeStation-Hornet#9286]
### Describe the feature request

When creating a new account it doesn't encode the text provided by the input proc. The paper that comes about as a result is safe, but the list of bank accounts isn't.

**Comment by EvilDragonfiend** [comment]
You are really good at finding out all these issues.

**Comment by DrPepperIsSpicy** [comment]
> You are really good at finding out all these issues.

its fun, like solving leetcode problems
