### ISSUE TITLE
[Bug]: Crew transfer votes can be held while just in the lobby

### ISSUE THREAD

**Issue by LodedDiper69** [BeeStation/BeeStation-Hornet#9293]
### BYOND Version

514.1589

### Round Date

2023/06/23

### Round ID

44603

### Test merges

- #9124: 'Enable serverside 515.1609 (new)' by Crossedfall at commit 43f695e9a4

### Describe the bug

There was a shuttle vote prompt where I could vote in while I was still in the lobby.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/101019561/93b1a117-9f09-4394-84b1-785b9491cfcd)

### What did you expect?

Didnt expect it to work, and it probably shouldnt since ghosts cant hold shuttle votes.

### Reproducible steps

Step 1: Be in the lobby
Step 2: Wait for the shuttle vote
Step 3: Vote

**Comment by PowerfulBacon** [comment]
Ghosts are exempt from the config option that prevents them from participating in votes. Whether or not new players should be able to is questionable.
