### ISSUE TITLE
Emagged airlocks can't have their electronics removed with Jaws of Life but can with a crowbar.

### ISSUE THREAD

**Issue by oo7craigmc** [BeeStation/BeeStation-Hornet#9312]
Issue reported from  Round ID: 44678 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/48850629/e324fb49-6a99-4670-9397-2ce4cedb5c19)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/48850629/80529c43-663f-46ac-97af-258aab645d2d)

I don't know how to title things without just writing out the whole problem.

**Comment by Pirill** [comment]
I thought I was being crazy and forgot how to do it but I did notice that as well...

**Comment by HowToLoLu** [comment]
This explains why... oh my gaaaaaawd.... 

Okay- I think this is an easy enough fix. (Extremely Oblivious)

**Comment by HowToLoLu** [comment]
Okay, something interesting I just found- you're not supposed to be able to use a crowbar like that- you're actually supposed to weld the door first and leave the bolts *up*. The actual bug here is the crowbar prying out the electronics without doing that.
