### ISSUE TITLE
[Bug]: randomize_human breaks in a few cases related to other species

### ISSUE THREAD

**Issue by HowToLoLu** [BeeStation/BeeStation-Hornet#9326]
### BYOND Version

514.1589

### Round Date

N/A

### Round ID

N/A

### Describe the bug

I was looking at mulligan toxin code- then noticed a couple of problems related to the `randomize_human` proc used by mulligan toxin code. And then I realized that the proc is extremely broken when applied to a character of non-human race.

There's a few things going wrong here-
1. The name randomly given is human based- and not based on the species of the character.
2. Blood type is changed to a random human one without even checking for mutant blood.
3. Limbs aren't accounted for at all (See reproduction steps below for an example case.)

### What did you expect?

The proc should be more reinforced against cases like this- especially since it is coded to acknowledge non-human traits and features already. In fact, the proc has if statements at all currently.

### Reproducible steps

1. Start a game as a non-human race; a good example for this case is a lizardperson.
2. Inject yourself with Mulligan Toxin, easily spawnable as `/obj/item/reagent_containers/syringe/mulligan`
3. Observe that quite a few things are messed up.

##### Before:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/16e7a5e6-36dd-435b-b4cb-4ee009f05f6b)

##### After:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/7333068f-494f-4a10-8a45-94bf17e131ff)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/4662a745-95f4-40cc-8737-02c056e063ab)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/8975d2d2-d713-4b7f-82bd-1083e23a5525)

**Comment by EvilDragonfiend** [comment]
* related fix: https://github.com/BeeStation/BeeStation-Hornet/pull/7033

**Comment by HowToLoLu** [comment]
There are still the issues regarding the name and blood type- since `randomize_human` touches those directly
