### ISSUE TITLE
[New Feature]: Give heretics the ability to break their knives from anywhere.

### ISSUE THREAD

**Issue by lowwy** [BeeStation/BeeStation-Hornet#9327]
### Describe the feature request

If a heretic loses his knives he cannot make more due to the limit. (Think of getting stunned, cuffed and then being robbed from the knives from sec)
Would be nice if a heretic can break the knives (from anywhere) to make new ones instead of being forced to raid the armory to get them back.

A plus would be if the knives would go out in the style of the main path:

- Ash: create a 1x1 fire
- Flesh: throw some gibs around
- Rust: hits the tile below it with rust

**Comment by CydiaLamiales** [comment]
Honestly? Nah, too good.

**Comment by St0rmC4st3r** [comment]
> Honestly? Nah, too good, heretics are restricted by knife counts for a reason.

So you are supposed to make a limited number of knives, then have them confiscated, and then "Welp! No more knives for me for the round!"?

**Comment by CydiaLamiales** [comment]
> So you are supposed to make a limited number of knives, then have them confiscated, and then "Welp! No more knives for me for the round!"?

What's stopping you from stealing them back?

**Comment by St0rmC4st3r** [comment]
> > So you are supposed to make a limited number of knives, then have them confiscated, and then "Welp! No more knives for me for the round!"?
> 
> What's stopping you from stealing them back?

Sergant-At-Armsky, Warden being mad that someone besides him is in the armoury, having barely any weapons and possible backup arriving to the armoury.
