### ISSUE TITLE
[Bug]: switchblade crafting recipe only works with regular welders

### ISSUE THREAD

**Issue by boombaklops** [BeeStation/BeeStation-Hornet#9328]
### BYOND Version

514.1589

### Round Date

N/A

### Round ID

N/A

### Test merges

- #9124

### Describe the bug

trying to make a switchblade with the CE welder or an industrial welder won't work

### What did you expect?

i expect any welder to be valid for making a switchblade

### Reproducible steps

1. gather the ingredients to make a switchblade, but use a special welder
2. try to craft it

**Comment by Pirill** [comment]
For what it's worth I believe this extends to a lot of recipes that need tools and only specifically function with the basic tools.

**Comment by boombaklops** [comment]
i think the welder requirement was quietly removed at some point after this issue was opened

**Comment by boombaklops** [comment]
this was fixed at some point. closing the issue
