### ISSUE TITLE
[Bug]: Mutations: Antiglow is no different than Glow

### ISSUE THREAD

**Issue by HowToLoLu** [BeeStation/BeeStation-Hornet#9340]
### BYOND Version

514.1589

### Round Date

N/A

### Round ID

Local Test Server

### Describe the bug

Giving myself antiglow seems to *not* create darkness- in fact, it's just a stronger version of glow at the moment (probably because somewhere down the line, -3.5 turns into positive 3.5)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/735fe7a9-56e9-4cad-9586-0a10ddd5dd52)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/a2fdf370-11a4-4792-90b1-fea6885fb841)

**UPDATE:**
After some further testing; I have found that the mutation still relies on mcolor because of the proc not being overriden.
In fact; antiglow at the moment is just a complete copy of glow. The is no difference in light between the two.

### What did you expect?

I expected to not light up like a discoball in the darkness with something that should create more darkness instead.

### Reproducible steps

1. Give a human/monkey the antiglow mutation using a DNA chamber or `/obj/item/dnainjector/antiglow`
2. Observe results
3. Remove the mutation with `/obj/item/dnainjector/removeantiglow` or any other method to get rid of the mutation
4. Give yourself the glow mutation `/obj/item/dnainjector/glow` or your preferred method at this point.
5. Compare the results before and after; and you should find that there is no significant difference between the two.
6. Repeat the 1-5 on a different human, and notice that it is reliant on the human's DNA `mcolor` value.

**Comment by Tsar-Salat** [comment]
Did you inject it inside or outside of the DNA chamber

**Comment by HowToLoLu** [comment]
> Did you inject it inside or outside of the DNA chamber

For the initial issue report, I had used the DNA injector that can be obtained from the Game-Panel; specifically `/obj/item/dnainjector/antiglow` (Will now revise the issue to include that.)

However, now upon injecting it via the chamber- there is ***zero*** difference in light. While I don't know why there's a difference here, it still feels like something is wrong with the amount of light still present.
No Mutation:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/b59ff922-8d85-4a68-8559-65b041524aad)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/d044a71a-d295-4380-bc63-abf4d7c36742)

Mutation:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/b585d5a0-80e1-41d6-a58c-812c5342cde6)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/7f109a04-a1d4-40f6-855f-6640a1f72ff0)

**Comment by HowToLoLu** [comment]
Update: now noticing that somehow it works- but it only works if something is south of the other thing
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/1f3b72f6-d066-4d0f-b701-8f916d30fda6)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/dfcf7f63-f763-418b-a04a-3cffc1a0d578)

(Also, for some reason using the aforementioned `/obj/item/dnainjector/antiglow` just breaks all instances of anti glow until a server restart)
