### ISSUE TITLE
[Bug]: Can't take off from an escape pod during Delta Alert

### ISSUE THREAD

**Issue by Pirill** [BeeStation/BeeStation-Hornet#9341]
### BYOND Version

514.1589

### Round Date

2023/07/06

### Round ID

44781

### Test merges

N/A

### Describe the bug

On CorgStation, we were unable to use the escape override on the asteroid pod after Delta Alert caused by cult summoning. The escape pod just stood there until the end of the round.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/29107291/64f3acdb-e00a-4c55-afd1-6d692d576e5e)

### What did you expect?

A grand escape at the last moment from cataclysmic destruction.

### Reproducible steps

- Press button;
- Receive ~~bacon~~ error;
- 🥓🐈

**Comment by HowToLoLu** [comment]
So, for this to happen- a shuttle's console (`/obj/machinery/computer/shuttle_flight`) has a set `recall_docking_port_id`. Yet- when trying to locate the actual docking port (a `/obj/docking_port/stationary` in `SSshuttle.stationary`), the ID doesn't match any of the docks in the list; causing this to happen.
