### ISSUE TITLE
Briefcase Launchpad Controller Not working

### ISSUE THREAD

**Issue by grimmmy** [BeeStation/BeeStation-Hornet#936]
## Round ID
9907

## Testmerges:
N/A
## Reproduction:
Buy Briefcase Launchpad
Get the folder controller from inside
Try to use the controller to use the launchpad.

(https://i.gyazo.com/bdb19c4e7ad2f1827c7f59478308b938.png) - Image of Error message

**Comment by zeskorion** [comment]
a lot of gui are having this error, including the virology machine. I hear ike is rollin out a fix tommorow
