### ISSUE TITLE
[Bug]: Attacking creates an effect "temp" that can 

### ISSUE THREAD

**Issue by HowToLoLu** [BeeStation/BeeStation-Hornet#9363]
### BYOND Version

514.1589

### Round Date

N/A

### Round ID

N/A

### Describe the bug

When attacking someone, a `/obj/effect/icon/temp` is created; it's clickable and blocks clicks like a shield.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/24581ab0-df15-48e7-aec9-cc27c05f6b18)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/23eabf01-b89f-4270-aa5c-916ff50f0711)

From what I can tell, #9265 caused this unintentionally.

### What did you expect?

When attacking, I expect a minor visual effect to *not* interfere with combat.

### Reproducible steps

1. Attack something.
2. Notice the white thing appear.
3. You can click it; and it can block your clicks on the mob.

**Comment by PowerfulBacon** [comment]
The fix is simply making the effect it spawns name just ""
