### ISSUE TITLE
[Bug]: you can't still use escape pod when narsie has been summoned and be force-delta

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#9365]
### Round Date

2023/07/09

### Round ID

448XX

### Describe the bug

When cultists successfuly summoned Narsie, people should be capable of launching escape pods, but they can't. It's still not usable even if becomes force-delta.

It was rad station

### What did you expect?

The thing you know

**Comment by HowToLoLu** [comment]
Which map is this on? I know rad and corg are broken due to improper escape shuttle configuration.

**Comment by EvilDragonfiend** [comment]
> Which map is this on? I know rad and corg are broken due to improper escape shuttle configuration.

It was rad station. It might be because the pod bug, but it's hardly reproducible.

**Comment by HowToLoLu** [comment]
There's a specific thing you have to do for setting up escape pods to go to lavaland; currently rad and corg are missing these objects; which causes the bug of "no port found" (because a port is literally missing)
