### ISSUE TITLE
[Bug]: Infinite credits holochip reuse

### ISSUE THREAD

**Issue by aramix273** [BeeStation/BeeStation-Hornet#9383]
### Round Date

-

### Round ID

-

### Test merges

-

### Describe the bug

when I was space walking, I threw 1 credit holochips to propel myself should I have lost grip on station
one of them bounced back from a wall and I tried to grab it, leading to a perhaps known but separate bug where the item is now both in your hand and in world, still moving from being bounced back in no gravity
I inserted the holochip into the card to free my hand, making it disappear from both in world and hand, but then I noticed that my hand still wasn't empty, despite inspection with right click not showing anything in hand
believing this was the holochip, I inserted it into the bank account again... and again... and again... meaning that I could have effectively gotten as many credits as I wanted
dropping the item, despite not having any apparently selected, fixed the bug

### What did you expect?

I expected that when I inserted the holochip into the bank account, for it to be properly removed from my hand, especially after repeated use
though this is probably a side effect of the aforementioned bug where if you pick something that bounced off from a wall after being in no gravity might lead to it not being properly added to inventory/removed from world

### Reproducible steps

1. go to a place with no gravity (space or disabled station gravity)
2. prepare the area such that when you throw a holochip, it bounces back (in space, it works with grilles)
3. move in to pick up the holochip as it flies after bouncing back
4. insert the holochip into bank account
5. repeat 4 as many times as you'd like
6. ???
7. profit

Reproduction video:

https://github.com/BeeStation/BeeStation-Hornet/assets/27755442/eac5e535-f66b-4b87-a4b2-54645605a8d0

**Comment by HowToLoLu** [comment]
I'm pretty sure that's not how money works at all...

**Comment by HowToLoLu** [comment]
Okay, so amazingly upon even further testing; the move_loop somehow survives the movement_packet being destroyed (which controls the move_loop); resulting in the move_loop being a parentless datum that is loose in memory (read as "This is a very, very bad, no good can come of this thing in programming")

**Comment by Tsar-Salat** [comment]
I fixed it ❤️
