### ISSUE TITLE
[Bug]: nameless in deadchat,when observing as ghost since roundstart

### ISSUE THREAD

**Issue by fierycomet** [BeeStation/BeeStation-Hornet#9394]
### BYOND Version

514.5189

### Round Date

12 july 2023

### Round ID

44880

### Describe the bug

i observed as ghost i tried to chat to dead chat i noticed i had no name

### What did you expect?

i expect the bug to be fixed so that i do not end up being nameless again in future

### Reproducible steps

load beestation in byond
make sure the round has just begun
then click observe
then  type hi dead chat in the chatbox

**Comment by HowToLoLu** [comment]
You're actually missing one step to reproduce this bug- This option right here in preferences:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/e0a6f31e-ea10-4f53-957e-6d817df5786f)

Has to be 
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/04cab578-353f-4712-9ebd-121548dbf381)
For this to happen.

**Comment by HowToLoLu** [comment]
I honestly thought this was fixed- but I'll make a fix for it now; since it should be a really easy fix.
