### ISSUE TITLE
cant close pop ups, such as pda, terminals, votes and vending machines

### ISSUE THREAD

**Issue by Ezevater** [BeeStation/BeeStation-Hornet#9400]
Issue reported from  Round ID: 44890 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

i have been playing for a few days, and this problem started today, it persists through multiple things such as a computer restart, clearing cache, manually clearing cache, deleting all files, and doing a clean reinstall,  

example on another server, able to move and close
![image_2023-07-13_182239089](https://github.com/BeeStation/BeeStation-Hornet/assets/139442559/268aa62e-9c61-41bf-a218-0647a92129f2)

beestation, stuck in place and no option to close
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/139442559/2dc4eae5-0bbb-4b1c-ae05-9d781282fd17)

im not exactly sure what shows the right windows version so heres a screenshot of it incase thats important, because it was mentioned to me that it might have something to potentially do with windows and its newer updates
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/139442559/22170b98-1aa5-45f7-95ba-4f645e0450c4)

**Comment by itsmeow** [comment]
@Ezevater Sorry I didn't reply to this earlier. It's possible that you disabled "Fancy TGUI" in your preferences, if you could check that? Maybe it'll fix your issue.

**Comment by itsmeow** [comment]
Was that it?

**Comment by Ezevater** [comment]
yes lol, fixed it ages ago with some other help should have closed it back then haha, thanks tho
