### ISSUE TITLE
[Bug]: Changeling tentacle can't disarm from right hand

### ISSUE THREAD

**Issue by GanimaHornet** [BeeStation/BeeStation-Hornet#9421]
### Describe the bug

Changeling tentacle ability can only disarm item in left hand. Using the ability on a target that has an item in the right hand produces and warning stating that the target has nothing that can be disarmed.

### What did you expect?

I expected to be able to disarm targets from both hands, not just the left hand.

### Reproducible steps

1. Use changeling tentacle ability on target holding item in right hand.

**Comment by CydiaLamiales** [comment]
Looks like the tentacle grabs the item from the active hand of the mob, and not from whatever hand you're aiming at

**Comment by GanimaHornet** [comment]
You don't need to aim at the arms to disarm. I guess this is a compromise between that and needing to manual aim it. Less control, but easier to use.
