### ISSUE TITLE
[Bug]: Energy Saw Implant disappears when augmenting arms

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#9423]
### Round Date

16.07.2023

### Round ID

44941

### Describe the bug

I was playing roboticist traitor and got myself an energy saw implant.
When my partner later augmented my arm, the energy saw seems to have disappeared - i no longer had the option of using it at the top of the screen.

Im fairly sure it didnt drop on the floor

### What did you expect?

The implant to work

### Reproducible steps

1. Get an energy saw implant
2. Use the energy saw implant
3. augment your arm with a metal one

**Comment by HowToLoLu** [comment]
If I had to guess without looking at code- it sounds like augmenting just deletes the old arm without transferring things properly.

Probably could try replicating with a toolset instead of an energy saw and see if that yields the same issue.

**Comment by HowToLoLu** [comment]
Alright, I tried replicating this using the steps provided; and I can't seem to get this to happen at all. Was there anything else during the circumstances you could think have aided in causing this?

**Comment by JukeJukestar** [comment]
> 

Heyo!
If you cant replicate it thats odd. 
I could think of one other possibility - being that the other roboticist removed it without me noticing, but this is highly unlikely as Im pretty sure I'd have noticed. Would he have been told that the implant is there during the aug surgery? If not he had no way to know
