### ISSUE TITLE
[Bug]: Hardsuit Jetpacks do not work

### ISSUE THREAD

**Issue by YuriVitch** [BeeStation/BeeStation-Hornet#9425]
### BYOND Version

514.1589

### Round Date

2023/7/16

### Round ID

44943

### Test merges

-#9124

### Describe the bug

When I tried to turn on my built in hardsuit jetpack, I noticed it does not turn on

### What did you expect?

I expected the jetpack to turn on and allow me to move

### Reproducible steps

1. Grab hardsuit with jetpack (HOS,CE,etc)
2. Put air in designated slot
3. Go into space
4. Attempt to turn on jetpack

**Comment by HowToLoLu** [comment]
This is probably due to jetpack code being somewhat unnessecarily complicated... (the jetpack suit alone adds 3 variables; one of them is even a duplicate of an existing variable from the jetpack parent type itself)
