### ISSUE TITLE
[Bug] Holodeck objects do not disappear

### ISSUE THREAD

**Issue by h42-real** [BeeStation/BeeStation-Hornet#9485]
Issue reported from  Round ID: 45027 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Changing the holodeck program or removing an item from the holodeck does not make the item disappear.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/104878598/e1266c3d-5130-492d-9e52-6119c0f89ddd)

**Comment by HowToLoLu** [comment]
On top of that- all of those wood tables were indestructable for some reason, which makes *zero* sense.

**Comment by Tsar-Salat** [comment]
> all of those wood tables were indestructable for some reason, which makes _zero_ sense.

were you trying to harvest them or somethin?

**Comment by HowToLoLu** [comment]
> > all of those wood tables were indestructable for some reason, which makes _zero_ sense.
> 
> were you trying to harvest them or somethin?

No, I saw an engineer try to even fireaxe it; they even survived hellfire. Zero damage.
