### ISSUE TITLE
[Bug]:  bubblegum doesn't fully complete a charge

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#9497]
### BYOND Version

_No re
sponse_

### Round Date

7/24/2023

### Round ID

45047

### Test merges

none

### Describe the bug

bubblegum doesn't fully charge towards the marks he makes on the ground, only instead going towards half the distance towards it, he does this with every move that involves charging

### What did you expect?

it SUCKS because it TELLS you where BUBBLEGUM is going to BE AT but instead you have to GUESS WHERE BUBBLEGUM IS GOING TO STOP which STINKS!!! also im pretty sure you can dodge the 6 bubblegum hallucination charge by just standing in the middle of it

example ignore my awesome boss fighting music its spaceship gurl - dream fiend remix by stayloose and dream fiend also i compressed 100 mb into 4 mb 

https://github.com/BeeStation/BeeStation-Hornet/assets/59359762/e28ae7dd-09da-4bf1-8de1-c858dd7a5570

### Reproducible steps

1. fight bubblegum

**Comment by Tsar-Salat** [comment]
your epic beats made him slower obv
