### ISSUE TITLE
[Bug]: Pulled people's pixel is not reset when they're buckled

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#9506]
### Round Date

2023-07-25

### Round ID

45060

### Describe the bug

1. pull someone (pulling someone twice will make the dramatic effect)
2. buckle them
3. do not pull any longer
4. see their pixel became glitchy (they're not centered)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/bcec667d-ae22-4e25-9efd-5506da677338)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/e30d0c67-91e6-4b9f-9e4c-9493df4c1bb3)

they're not centered until they're pulled again.

### What did you expect?

not pixel glitch

**Comment by EvilDragonfiend** [comment]
@Tsar-Salat :trollface:

**Comment by Tsar-Salat** [comment]
fuck
