### ISSUE TITLE
[Bug]: Pride mirror sends to zlevels which can't be reached through space flight.

### ISSUE THREAD

**Issue by swatblack** [BeeStation/BeeStation-Hornet#9511]
### Round Date

2023.07.25

### Round ID

45064

### Describe the bug

My fellow miner used a pride mirror on lavaland without a fulton beacon, and got promptly sent to space. The only reason I noticed that and started my rescue efforts was because they changed their GPS name into cries for help:
![abandoned](https://github.com/BeeStation/BeeStation-Hornet/assets/129751071/9af2d589-67e8-4371-ae12-19244ea2d4d3)

I spent around 1.5 hours flying around the map on my mining shuttle, scouring every possible zlevel to no success (asteroids, signals, anything i could fly to).

In the end, I had to resort to using the pride mirror myself to no avail, as I was sent to the wrong Zlevel, so I couldn't even comfort the poor guy in his last moment of boredom (as the round was coming to a close)

While this may just be a game design issue instead of a bug, I still don't think it was intended for a miner to be completely irrecoverable after they used a pride mirror without a fulton beacon, however, the fact that the zlevel they're sent to is unreachable makes it so that they cannot be helped through outside means, effectively round removing them.

### What did you expect?

I expected to be able to recover a miner that used a pride mirror.

**Comment by Tsar-Salat** [comment]
> My fellow miner used a pride mirror on lavaland without a fulton beacon, and got promptly sent to space.

Pride goeth before the fall. This is the reason this ruin exists in its current state, and its how being able to change into any race in the game is balanced. You must be prepared when you go through, or you have a very possible chance of dying.

**Comment by swatblack** [comment]
Well, if that's a feature, then I will not argue for it's removal.
Though on that round the miner in question actually survived by deploying bluespace shelters, and was actually alive and conscious for the rest of the shift. This made them stay in some sort of... limbo zlevel i think? Which was unreachable as I mentioned earlier.

**Comment by Tsar-Salat** [comment]
> Though on that round the miner in question actually survived by deploying bluespace shelters

Mhm, if you survive then the failsafe never actually brings you to the objective, and you will remain in the unreachable z-level.

**Comment by PowerfulBacon** [comment]
You get sent to the beacon named weak signal but there is no way to know this in game

**Comment by Penwin0** [comment]
I'm pretty sure this working as intended

**Comment by Pockets-byte** [comment]
originally space was continuous. I was curious, and I changed my FREAKING EYE COLOR to see if it worked, and I'm stuck in an empty space-level with no way to get back to the station (was a cargo tech checking on the miner) 
as designed I'm certain it wasn't supposed to essentially be a round removal

**Comment by Pockets-byte** [comment]
was this actually fixed?
