### ISSUE TITLE
[Bug]: When using a AZERTY keyboard, the intent hotkeys do not work when remapped.

### ISSUE THREAD

**Issue by Howluinb** [BeeStation/BeeStation-Hornet#9520]
### Round Date

26/07/2023

### Round ID

45077

### Describe the bug

I play on bee with an AZERTY keyboard due to my french upbringing, and playing with anything else while having to talk is really hard for me.
Trying to rebind all the keys to fit my keyboard and have the original layout I am used to causes me to be unable to use the intent hotkeys.
The only one that works is harm intent.

### What did you expect?

I expected the hotkeys to work, obviously

### Reproducible steps

1. Set hotkeys to ![image](https://github.com/BeeStation/BeeStation-Hornet/assets/24866230/57f00898-f761-40d9-a7da-89ba21c8772c) (which correspond to 1, 2, 3 and 4 on a azerty keyboard)
2. Only the fourth one works

**Comment by PowerfulBacon** [comment]
This is likely due to the hotkey whitelist due to an old bug in byond

**Comment by Howluinb** [comment]
Would it be possible to un-stale this issue ? It's like, the last thing ever needed for me to be able to use emotes and use ?,! and other special characters without suffering
