### ISSUE TITLE
Blood Brother TGUI Menu not displaying objectives

### ISSUE THREAD

**Issue by WhereAmO** [BeeStation/BeeStation-Hornet#9527]
Issue reported from  Round ID: 45087 (BeeStation Sage - Roleplay)
Reporting client version: 514.1589

Who deleted the issue format..?

Anyhow! As a Blood Brother, we spawned in and thought we had no objectives because the little TGUI menu that popped up has quite literally nothing on it save for the Blood Brother, apologies but didn't think to take a screenshot.

Probably a thingy that slipped through in this PR? https://github.com/BeeStation/BeeStation-Hornet/pull/9205

To reproduce, probably just be a bloodbrother and see the lack of objectives, they pop up in Notes rather than anywhere else visible as far as I can tell. (Might've been in the textbox but can't scroll that far back and didn't notice them)

**Comment by itsmeow** [comment]
> Who deleted the issue format..?

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/10366817/ae4d1433-3c5e-4016-9d7d-d7a7375599ae)

hm?

**Comment by Tsar-Salat** [comment]
> Who deleted the issue format..?

I think its opt-in?

**Comment by WhereAmO** [comment]
I clicked the "report issue" in game and this is where it took me and gave me, no format from there.

**Comment by itsmeow** [comment]
in-game issue reporter is outdated
