### ISSUE TITLE
[Bug]: problem with how a resting person interacts with people around

### ISSUE THREAD

**Issue by pixelman77** [BeeStation/BeeStation-Hornet#9532]
### BYOND Version

514.1589

### Round Date

7/27/2023

### Round ID

irrelevant also I forgor

### Test merges

[#9124: 'Enable serverside 515.1609 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#9308: '[Debug] Reboot failure debugging log' by EvilDragonfiend at commit e547622a11](https://www.github.com/beestation/beestation-hornet/pull/9308)

### Describe the bug

when lying down, you sometimes don't pass through people and instead push them or switch places depending on your intent.
Also, lying down to not get hit by emitters is broken.

I suspect this was caused by #9349, I do not have proof because I haven't got to check the code but I didn't find any other PR that manipulated the rest code.

### What did you expect?

I expected to weasel my way through the seccie blocking my way and to not get hit by he emitter laser.

### Reproducible steps

1. rest
2. walk into someone or stand in path of emitter.

**Comment by Tsar-Salat** [comment]
Thinking I put an incorrect if check. Something like `(!(LM.mobility_flags & MOBILITY_STAND)` instead of (LM.mobility_flags & MOBILITY_STAND).

Ill look into it

**Comment by Tsar-Salat** [comment]
> when lying down, you sometimes don't pass through people and instead push them or switch places depending on your intent.

You could, you just had to move a turf whilst resting so it would update properly. 

Merging the fix will close this issue
