### ISSUE TITLE
Character Data not retrievable

### ISSUE THREAD

**Issue by ThunderScoot15** [BeeStation/BeeStation-Hornet#9578]
Issue reported from  Round ID: 45168 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

This is the error message. When I went to setup my character this is what popped up.

![ss13errorreport](https://github.com/BeeStation/BeeStation-Hornet/assets/141189259/f39eaf23-43df-4564-bfce-18ac6e1f2669)

Error Details:
SyntaxError: Invalid character
   at Y (http://127.0.0.1:56308/tmp15772/tgui.bundle.js:1:124043)
   at Anonymous function (http://127.0.0.1:56308/tmp15772/tgui.bundle.js:1:125681)
   at k (http://127.0.0.1:56308/tmp15772/tgui.bundle.js:1:73426)
Asset Mappings: {
  "fa-regular-400.eot": "fa-regular-400.eot",
  "fa-regular-400.woff": "fa-regular-400.woff",
  "fa-solid-900.eot": "fa-solid-900.eot",
  "fa-solid-900.woff": "fa-solid-900.woff",
  "font-awesome.css": "font-awesome.css",
  "tgfont.eot": "tgfont.eot",
  "tgfont.woff2": "tgfont.woff2",
  "tgfont.css": "asset.8ef6a8121bbcd5f10fb4a1a159588377.css",
  "spritesheet_preferences.css": "asset.faa309f87f9097064bdc41d36fa2ddb5.css",
  "preferences_32x32.png": "asset.fded3e37befbb9346f885a05f39e73df.png",
  "preferences_64x32.png": "asset.1c237a157be7d8c44a10d36c710611c8.png",
  "spritesheet_preferences_l.css": "asset.bcd82fecaf59cd5956d094bd2b74a8e3.css",
  "preferences_l_32x32.png": "asset.facbb3529606a172a69eb95ff810833d.png",
  "spritesheet_preferences_h.css": "asset.cf7ff7e53d5c8ccc4a9a6b3c0238a524.css",
  "preferences_h_32x32.png": "asset.2e798e65124df1b836d27e5e5426b00e.png",
  "spritesheet_preferences_loadout.css": "asset.2e38e461ea5dc917ae3caa54dcc03932.css",
  "preferences_loadout_32x32.png": "asset.c767c826c3590a8e1506682038343de1.png",
  "preferences.json": "asset.071bda019a1f99fa579f95de80bf0ad1.json",
  "spritesheet_antagonists.css": "asset.80d11f837d4abe04e82a4eabc84be126.css",
  "antagonists_96x96.png": "asset.65e75239a7b49a605968f46d292427fa.png",
  "keybindings.json": "asset.58195699a8f63a686d0b62eeac2d4173.json",
  "spritesheet_species.css": "asset.6c4a90321e89c9cf3b88c8eb37f6e7a4.css",
  "species_64x64.png": "asset.33324056c7d501b64350436a3e8f949b.png"
}

**Comment by itsmeow** [comment]
Hi! Thanks for reporting this. It looks like according to the debug data offered you did actually get sent the proper data, so I'm not entirely sure why this error is happening.

Does rejoining or running the "Refresh-TGUI" verb work?

If not, can you try clearing your BYOND cache? (Do note this will probably wipe your chat tabs / filters if you have any, so keep note of those)

Clearing the BYOND cache:
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/10366817/89e6b19b-7b58-45fc-afd3-930bfacc53f7)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/10366817/c19a2f90-217e-4939-a40e-2949f4a8a1e3)

**Comment by ThunderScoot15** [comment]
Rejoining seems to have fixed it, since I can not set up it while in the round. If it happens again during a new round/game I will try the other options and bring new info if any arises.

**Comment by itsmeow** [comment]
> Rejoining seems to have fixed it, since I can not set up it while in the round. If it happens again during a new round/game I will try the other options and bring new info if any arises.

You can actually open it anytime during a round with the `Character-Preferences` verb, or from the button at the top left (Preferences menu)

**Comment by itsmeow** [comment]
Considering this seems to have been a one time occurance and the error was caught as expected, I'm going to go ahead and close this.
