### ISSUE TITLE
[Bug]: Bluespace Launchpad USB does not work.

### ISSUE THREAD

**Issue by dannydonk** [BeeStation/BeeStation-Hornet#9579]
### BYOND Version

514.1589

### Round Date

2023/1/8

### Round ID

45170

### Test merges

[#9124: 'Enable serverside 515.1609 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#9308: '[Debug] Reboot failure debugging log' by EvilDragonfiend at commit f43139111a](https://www.github.com/beestation/beestation-hornet/pull/9308)
[#8776: 'Preferences: Redux' by itsmeow at commit 75eef4173c](https://www.github.com/beestation/beestation-hornet/pull/8776)

### Describe the bug

Circuits are unable to interact with bluespace launchpads with USB. Trying to send signals or data to the bluespace launchpad doesn't change any of the values. 

### What did you expect?

I expected the bluespace launchpad to change it's X and Y coordinates and retrieve when I signal it to do so.

### Reproducible steps

1. Create a bluespace launchpad setup.
2. Create a bot shell with circuit.
3. Connect it with a USB to the launchpad.
4. Attach button signal to retrieve.
5. Interact with the bot shell.

**Comment by dannydonk** [comment]
TG seems to have had the same issue and fixed it with https://github.com/tgstation/tgstation/pull/69920

**Comment by JixS4v** [comment]
common issue, you need to put a cell in your circuit

**Comment by dannydonk** [comment]
> common issue, you need to put a cell in your circuit
this isn't the issue, the circuit I used was fully charged and I've tested it once more with a charged circuit for the same results.

**Comment by dannydonk** [comment]
![image_2023-08-03_185413458](https://github.com/BeeStation/BeeStation-Hornet/assets/87622216/962482b8-97fb-41d9-8611-78692a9fd6b9)

**Comment by JixS4v** [comment]
that's weird, the retrieve function has worked for me when i've tried it, and i've done quite a few BS launchpad circuit setups

**Comment by dannydonk** [comment]
i believe it was broken recently by https://github.com/BeeStation/BeeStation-Hornet/pull/9536
