### ISSUE TITLE
Wizarditis causes NPC mobs to talk in dchat

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#9606]
### Round Date

04/08/2023

### Round ID

45206

### Describe the bug

It makes dead monkeys talk in dchat even when NPCs.

### What did you expect?

It shouldn't talk in dchat.

**Comment by EvilDragonfiend** [comment]
feature

**Comment by CydiaLamiales** [comment]
Might be similar? Dying mid-cluwne smite makes you force talk in dchat too
