### ISSUE TITLE
MetaStation disposals allows easy entry into cap's office

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#9607]
### BYOND Version

514.1589

### Round Date

2023/08/05

### Round ID

45212

### Test merges

[#9124: 'Enable serverside 515.1609 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#8776: 'Preferences: Redux' by itsmeow at commit 947fc9ffb1](https://www.github.com/beestation/beestation-hornet/pull/8776)
[#9043: ''Soft'-tracked objectives& Replacement of gimmick objectives' by PowerfulBacon at commit fee83cf66f](https://www.github.com/beestation/beestation-hornet/pull/9043)

### Describe the bug

Going in the disposals tube northeast in the hall outside's Cap's office will blast you into the captain's office. Providing easy access into a secure area.

### What did you expect?

I expected it to go to the disposals processing area.

### Reproducible steps

1. Enter disposals northeast of the captain's office in the hall

**Comment by mystery3525** [comment]
Did someone re-pipe the disposals split here to go into the captain's office that round? It is a **VERY** easy thing to do and has been possible for years, since it is accessible with just maintenance access.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/30960302/01e7e443-f986-40c1-ad1e-670bd1b13620)

**Comment by itsmeow** [comment]
I dunno. they might've repiped. I was under the impression it started that way. but yes, it's actually quite likely that is what happened since they had an RPD in their bag.
