### ISSUE TITLE
[Bug]: Syndicate lavaland base lost self-destruct explosion size

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#9608]
### Describe the bug

Basically ever since the introduction of the bombs rework, the lavaland syndicate outpost lost the explosion size capable of destroying the entire base, which it's... the main purpose of the self destruct device

Currently it only destroys the vault area, a little bit of the unused cargo section and some minor damages to medbay-atmos-backof the bar it's very dissapointed because it misses the whole point of ''self destruct'' specially because most of the ''goodies'' such as the warehouse, the laboratory, chemistry, telecomms are left intact

Some people told me that the base had ''invisible bombs'' under their tiles that caused the massive wipe-out but since the bombs rework got merged we're only left with a regular syndicate bomb that doesn't trigger the chain-detonation of the others

### What did you expect?

For the entire base to be wiped as it was always the case before the bomb reworks

### Reproducible steps

Spawn as an scientist, arm the bomb, wait, admire the small hole left behind, you can even be alive to see it just by stepping into medbay or watching from the cargo warehouse

**Comment by Tsar-Salat** [comment]
> Some people told me that the base had ''invisible bombs'' under their tiles that caused the massive wipe-out

The walls are explosive.

I got permission to make the wall explosions bigger/make more explosive walls from bacon a few months back, I just forgot about it lol.

Ill check it out later.
