### ISSUE TITLE
Unable to get cookies from consuming blue

### ISSUE THREAD

**Issue by randal-the-vandal** [BeeStation/BeeStation-Hornet#9625]
### BYOND Version

latest version

### Round Date

2023/08/08

### Round ID

45259

### Describe the bug

When I was trying to feed a "Consuming Blue" extract with food items cakes,pizza slices and breads I it did not execpt the food and no text appeared too saying it did not work.

### What did you expect?

I expceted to get my cookie from the silver slime crossbreed extract.

### Reproducible steps

Get Consuming Blue (feed ten sliver slime extracts to a adult blue slime)

make food or steal food

Try to feed the food to the extract

get nothing

**Comment by Penwin0** [comment]
![Screenshot_1725](https://github.com/BeeStation/BeeStation-Hornet/assets/53474257/10992459-25b2-4b33-baa7-08007875dd9e)

Unable to reproduce
