### ISSUE TITLE
bad poster

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#9632]
Issue reported from  Round ID: 45281 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/f5070493-3a5e-43e9-87ad-6b82a7f9b91f)

**Comment by itsmeow** [comment]
Guess who added this (extremely high quality, well tested PR, that has worked since it was merged)

**Comment by itsmeow** [comment]
#7812

**Comment by Tyranicranger4** [comment]
Surely I'm not the only person that incorrectly assumed the missing texture poster was an intentional joke, right?

**Comment by itsmeow** [comment]
I considered this but I am also the one who merged the PR so I very quickly realized it was entirely unintentional
