### ISSUE TITLE
[Bug]: Heretic issues

### ISSUE THREAD

**Issue by SnailIssues** [BeeStation/BeeStation-Hornet#9634]
### BYOND Version

514.1589

### Round Date

2023/08/08

### Describe the bug

Noticed a few bugs while playing heretic, don't have round ID or screenshots, but i think it's easily recreatable

1. Changing a race via dying (ex: podpeople) results in losing the "Forbidden Knowledge" button
2. If the sacrifice target has changed a race in any way (most likely, since the target turned into a living skeleton) - they are no longer sacrificable

### What did you expect?

I expected that it wouldn't do that and let me use the "Forbidden Knowledge" and sacrifice my targets even after they changed races normally.

### Reproducible steps

For the "Forbidden Knowledge" button missing:
1. Inject a pod seed with your blood
2. Plant it
3. Die
4. Resurrect as podman
For not being able to sacrifice changed race targets:
1. Acquire a sacrifice target
2. Change their race (ex: chaplain becoming a lesser lich)
3. Attempt to sacrifice them

**Comment by CydiaLamiales** [comment]
Both issues are likely caused by race changing creating a new mob and transferring all the data to it.
Sacrifice target is a mob reference, old mob is deleted on race swap - bug happens
