### ISSUE TITLE
[Bug]: Podpeople get attacked by killer tomatoes

### ISSUE THREAD

**Issue by SnailIssues** [BeeStation/BeeStation-Hornet#9635]
### BYOND Version

514.1589

### Round Date

2023/08/08

### Describe the bug

Podpeople will still get attacked by killer tomatoes even after awakening them, so becoming a podman is basically useless for antags.

### What did you expect?

I expected the killer tomatoes to not attack me as a podman.

### Reproducible steps

1. Become a podman
2. Awaken a killer tomato
3. Get attacked by it

**Comment by PowerfulBacon** [comment]
Not an issue
