### ISSUE TITLE
Floating Camera in Corg Janitor's Closet

### ISSUE THREAD

**Issue by Programs-The-Station** [BeeStation/BeeStation-Hornet#9645]
Issue reported from  Round ID: 45304 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/54768ec1-cf95-4640-8496-68f22c626f40)

**Comment by Penwin0** [comment]
Thank you for the report!
