### ISSUE TITLE
Trial Admins cannot restart the server after delaying the end of the round

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#966]
Round ID: 10003

Reported by Average_Joe22

## Reproduction:

1. Be trial admin

2. Delay round end

3. Attempt to restart the server.

**Comment by Moccha-Bee** [comment]
Already working on a fix for this

**Comment by ike709** [comment]
@MarkSuckerberg

**Comment by Moccha-Bee** [comment]
Issue has been dealt with. It was a perm's thing not a code one.
