### ISSUE TITLE
Traitors do not spawn with the kits needed to steal the sm sliver or the plutonium core.

### ISSUE THREAD

**Issue by Haliris** [BeeStation/BeeStation-Hornet#9660]
Issue reported from Round ID: 45299 (ticket#3)
Check the admin tickets for both of these.

Reproduction steps:
Spawn as traitor with the objective to steal either the SM sliver or the nuke core.
No kits spawn.

The kit doesn't spawn regardless of if the player is created at roundstart or later.

Expected behaviour:
Traitors should spawn with those kits as they cannot be obtained through any other mean, requiring admin intervention to correct.

Reporting client version: 514.1589

**Comment by St0rmC4st3r** [comment]
Did you make sure to check your notes for the location of the kit? They are supposed to be spawned in a secret stash.

**Comment by Haliris** [comment]
Yeah I was just made aware of this now.

**Comment by CydiaLamiales** [comment]
Yeah, https://github.com/BeeStation/BeeStation-Hornet/pull/9043 made it so those kits spawn in stashes around the station to collect.

**Comment by Haliris** [comment]
I just asked the player and they just didn't read their notes, so you can close this.

**Comment by Penwin0** [comment]
Intended behaviour

**Comment by Penwin0** [comment]
Though, it should show in TGUI menu as well, Bacon was told
