### ISSUE TITLE
Pod Emergency Space Suit freezing me to death

### ISSUE THREAD

**Issue by RainBoom1234** [BeeStation/BeeStation-Hornet#9672]
### BYOND Version

514.1589

### Round Date

13.08.2023

### Round ID

45343

### Test merges

Round ID: 45343
BYOND Version: 515.1610
Server revision compiled on: 2023-08-13T09:49:46+00:00
Master commit: [8296eb03c6b06b2ae9dfcc20f111a7fbe5c3c24a](https://www.github.com/beestation/beestation-hornet/commit/8296eb03c6b06b2ae9dfcc20f111a7fbe5c3c24a)
The following pull requests are currently test merged:
[#9124: 'Enable serverside 515.1610 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)

Local commit: e4d47435b6d75d42ac67f3dc626046c0200fa089
TGS version: 5.13.5
DMAPI version: 5.6.1

Current Informational Settings:
Protect Authority Roles From Traitor: 1
Protect Assistant Role From Traitor: 0
Protect Command Roles From Traitor: 1
Enforce Human Authority: 0
Allow Latejoin Antagonists: 1
Enforce Continuous Rounds: 15 of 27 roundtypes
Allow Midround Antagonists: 7 of 27 roundtypes

lol idk what im doing. this showed when i clicked show server revision

### Describe the bug

[Bug]: i was in a pod when escape pod launched. i put on the emergecy space suit, gas mask, space helmet and gas mask provided in the safe in the pod. upon launch i started freezing to death despite having internals on. the door to space was not open and i did not notice any breaches to space

### What did you expect?

assuming beestation space suits isolate you from space and cold without the need of a implanted cell or heating systems, then to be safe in the pod. i do not think i would even have needed a space suit to protect me as i observed no leaks to space in the pod

### Reproducible steps

umm... go to the pod i was at (escape pod one(2) on ghost teleporting menu)
then... try using the equipment? to me it looked like a bug and to the mentors it looked like a bug but im not trained in bug reporting.

**Comment by HowToLoLu** [comment]
> lol idk what im doing. this showed when i clicked show server revision

For future reference, you only need the stuff under the part that says this:
`The following pull requests are currently test merged:`
`#9124: 'Enable serverside 515.1610 (new)' by Crossedfall at commit 43f695e9a4`
