### ISSUE TITLE
bot loops in rad station

### ISSUE THREAD

**Issue by airlines7** [BeeStation/BeeStation-Hornet#9687]
Issue reported from  Round ID: 45375 (BeeStation Sage - Roleplay)

Testmerges: 9124 and 9659

Reporting client version: 514.1589

Not a serious problem, but medibots and beepsky are stuck in a loop between two spots. each on the other side of evac on Rad station.

![image](https://github.com/BeeStation/BeeStation-Hornet/assets/98609667/cce62351-7d4b-4adc-92f1-43a32abfeaf8)

**Comment by Tsar-Salat** [comment]
Fixed by #8929, if that is resumed
