### ISSUE TITLE
AI Internal Affairs cannot greentext

### ISSUE THREAD

**Issue by Cenrus** [BeeStation/BeeStation-Hornet#969]
## Reproduction:

1. Become an IAA AI.

2. Assassinate your target.

3. Survive in your core until the end of the round.

4. The roundend report will say you failed objective 2, survive until the end.

**Comment by zeskorion** [comment]
> ## Round ID: 10007
> ## Reproduction:
> 1. Become an IAA AI.
> 2. Assassinate your target.
> 3. Survive in your core until the end of the round.
> 4. The roundend report will say you failed objective 2, survive until the end.
> 
> Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/85104882-ai-internal-affairs-cannot-greentext?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F120077027&utm_medium=issues&utm_source=github).

this is because the objective "Survive until the end" is glitched, and is just a normal shuttle escape objective. AI IAA can greentext- they need a borg to do it, however

OR, this is because AIs count as dead. but i know survive till the end doesnt work on, say, wizards either
