### ISSUE TITLE
Sugg: Handwriting on notes

### ISSUE THREAD

**Issue by CthulhuOnIce** [BeeStation/BeeStation-Hornet#974]
I could make it so that notes and letters penned by crew members have a handwriting font.

Would that be epic or cringe?

![image](https://user-images.githubusercontent.com/41597119/70441664-6b6e7000-1a5a-11ea-8bcb-c35b908d0c98.png)

**Comment by Moccha-Bee** [comment]
It's a well known fact that people can't write on beestation, such changes would break my immersion

**Comment by CthulhuOnIce** [comment]
oh yeah i could also use a cursive font for signatures, instead of them just being italics
![image](https://user-images.githubusercontent.com/41597119/70442201-770e6680-1a5b-11ea-9a4b-40984f6b869c.png)

**Comment by St0rmC4st3r** [comment]
We already have fountain pens for that, to my knowledge.

**Comment by Superyodeler** [comment]
I like the idea as long the font is readable. I think the left font looks good.

**Comment by CthulhuOnIce** [comment]
epic cool

**Comment by Kerbin-Fiber** [comment]
It would be better if there were multiple fonts and people got a random "style" each round. Tying handwriting "syles" to people's Unique Identifiers in Genetics. That would make a hell of a lot of immersion with hand-writing tests for the detective to conduct

**Comment by ike709** [comment]
This kills tactical forms.

**Comment by CthulhuOnIce** [comment]
> This kills tactical forms.

how?

**Comment by CthulhuOnIce** [comment]
> It would be better if there were multiple fonts and people got a random "style" each round. Tying handwriting "syles" to people's Unique Identifiers in Genetics. That would make a hell of a lot of immersion with hand-writing tests for the detective to conduct

i may do this, this sounds redpilled

**Comment by ike709** [comment]
Can't quickly make a professional-looking HoP/QM form anymore.

**Comment by CthulhuOnIce** [comment]
> Can't quickly make a professional-looking HoP/QM form anymore.

Why not? Handwriting exists irl, and it doesn't affect professional looks.

**Comment by 123chess456** [comment]
Use a typewriter or printer?

**Comment by ike709** [comment]
I want an easy way to quickly make forms that look like they were typed.

**Comment by ike709** [comment]
Perfect opportunity to make modular computers suck less.

**Comment by eLeCtrOssSnake** [comment]
I want it

**Comment by eLeCtrOssSnake** [comment]
Wtf, if nobody's gonna continue then am doing it.
