### ISSUE TITLE
Bluespace anchors are too weak

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#9742]
### Describe the feature request

It would be nice if a bluespace anchor spawned in the armoury.
Remove the shock on attempted teleport.
Reduce the power consumption for low powered batteries and make them use less power when blocking consecutive teleports (spam teleports are cheap to block but single teleports are expensive.)
Make them quicker to deploy
Make them susceptible to EMPs
Would be nice if their radius was visible somehow, either with like a shield effect overlay or a border

**Comment by boombaklops** [comment]
i like all of this, especially the roundstart armory anchor
