### ISSUE TITLE
you can remove unremovable items by frying them in suit storage

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#9749]
1. put a brain into a suit storage of a suit
2. fry the suit
3. brain gone

I 100% suspect it can remove all undeletable items like nuke disk.
reported by Lucy.

**Comment by HowToLoLu** [comment]
You can't delete the nuke disk without proc calls. (And if you can find a way without advanced proc calls; someone really messed up. Thankfully that isn't the case here.)

However, that doesn't excuse the fact that this is code wise the equivalent of throwing something into the SM; and frying shouldn't be able to just do that.

**Comment by VickiMorris** [comment]
I just tested this out on a private server running the latest downstream and, uhh
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/97719613/9984fcff-ee1e-4c0e-8a78-9981bca35ad7)

**Comment by HowToLoLu** [comment]
> I just tested this out on a private server running the latest downstream and, uhh

That's the specific intervention on the nuke disk that prevents deletion, you can especially see it if you even throw it directly into the SM engine. 

The big concern I had when I saw "deleting the nuke disk" was if someone *really* screwed up and used qdel(force=true)

**Comment by Tsar-Salat** [comment]
I added a blacklist to fried items when I refactored frying into an element in #10130 

This bug is no longer the case.
