### ISSUE TITLE
[Bug]: Bluespace Capsule missing description

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#9764]
### Round Date

2023/30/08

### Round ID

45626

### Describe the bug

All items have a small description when you mouse over them on the lathe, but BS Capsule doesn't! (you can't see my cursor but it's over it)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/57050500/195fe503-347b-497f-8424-6f06f9380cc7)

@Rukofamicom ping so you can do it when you have time

### What did you expect?

I expected to see a small description detailing how it works/limitations/flavor text/etc

### Reproducible steps

1- Go to Lathe when the research is done
2- Type BS Capsule
3- Mouse over and find no text
4- bug!

**Comment by Rukofamicom** [comment]
I have no idea, I forgot it existed

**Comment by Fronsis** [comment]
The fate of many of my bug-stale reports :tragedy: But afail it's still present
