### ISSUE TITLE
Virology jobrole removal

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#9774]
Virology doesn't have enough content to exist as a standard job role, as most of the content in virology will result in a ban if it gets out.
Virus creation should be made into a part of medbay that is accessible to any decently ranking medical staff (doctors, chemists, geneticists, CMO) (paramedic doesn't need it as they work outside of medbay and should give people to heal over to medical staff except on skeleton crews).
The person who works the most on virology has expressed that they are fine with the job role being removed as it is better than the alternative of virology being changed dramatically.

**Comment by zeskorion** [comment]
I am, to be clear, entirely fine with the mechanic of virus creation being removed in its entirety, along with associated mechanics.

**Comment by EvilDragonfiend** [comment]
Solved by
* https://github.com/BeeStation/BeeStation-Hornet/pull/10153
