### ISSUE TITLE
[Bug]: New atmos resin upgrade doesnt let you shoot normal resin

### ISSUE THREAD

**Issue by wikimody** [BeeStation/BeeStation-Hornet#9782]
### BYOND Version

514.1589

### Round Date

2023.09.04

### Round ID

45698

### Test merges

[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

New atmos pack misses half of the sprite on character model
![Zrzut ekranu (17)](https://github.com/BeeStation/BeeStation-Hornet/assets/58008547/3fee0ba5-80cd-4d82-8ff1-78983ac36e0a)
New resine goes thou normal resine from before the upgrade (migth be intentional)
![Zrzut ekranu (18)](https://github.com/BeeStation/BeeStation-Hornet/assets/58008547/88a47d11-2345-4ff7-9d41-c77565725fa4)
![Zrzut ekranu (19)](https://github.com/BeeStation/BeeStation-Hornet/assets/58008547/0054c44b-6524-4733-ab40-904b80d3c6be)

Launcher set on old resine still shoots new version 
![Zrzut ekranu (20)](https://github.com/BeeStation/BeeStation-Hornet/assets/58008547/51ae799c-f8cc-4576-afbd-c406ac705009)
![Zrzut ekranu (21)](https://github.com/BeeStation/BeeStation-Hornet/assets/58008547/26322ce1-a1d4-4296-9bc9-a86ee9f4d336)

When set on old resine using nozle set on launcher on harm intend on block of new resine,  it shots globe of resine in compleatly random direction if the hit destroed resine you were hiting 
![Zrzut ekranu (22)](https://github.com/BeeStation/BeeStation-Hornet/assets/58008547/836ad6c2-18ac-4b37-bff9-93f93eb7d862)
![Zrzut ekranu (24)](https://github.com/BeeStation/BeeStation-Hornet/assets/58008547/8a8a1258-ecf2-4c5a-9c66-4e79232be503)
![Zrzut ekranu (25)](https://github.com/BeeStation/BeeStation-Hornet/assets/58008547/a5f1b3f3-2da0-47b2-8945-508c95acf70e)

### What did you expect?

Normal working

### Reproducible steps

Upgrade atmos bacpack with advance resine upgrade
Test the things i talked abaut

**Comment by CydiaLamiales** [comment]
Oh fuck, I'll make a fix tomorrow

**Comment by CydiaLamiales** [comment]
> New atmos pack misses half of the sprite on character model

Figured out why, it's because the item icon changes but there's no alt worn icon.

> New resine goes thou normal resine from before the upgrade (migth be intentional)

Yes, advanced resin capsule passes through both norma ans advanced resin.

> When set on old resine using nozle set on launcher on harm intend on block of new resine, it shots globe of resine in compleatly random direction if the hit destroed resine you were hiting

Looks like I'll need to cancel afterattack if the nozzle destroys resin on it.

**Comment by CydiaLamiales** [comment]
Fix is up
