### ISSUE TITLE
[Bug]: Holopads can be unwrenched, leaving the Hologram Behind

### ISSUE THREAD

**Issue by Programs-The-Station** [BeeStation/BeeStation-Hornet#9785]
### Round Date

2023/09/23

### Round ID

Sage round before 45702 (Forgot to grab the Round Number)

### Describe the bug

It is possible to unsecure a holopad while it is replaying a holograph. This causes it to leave the recording behind. The holograms cannot be shut off, until the original pad is found.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/c2a6ff1b-7f46-4a2f-bdac-de100bba1cb2)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/e57e0f7b-ccfa-43c7-a87f-6dc6122a4fab)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/100493881/5a6879c2-80df-4c6a-9259-5baa46a47747)

This was used to soft-grief the Sage round before 45703.

### What did you expect?

The hologram should either disappear, or holopads should not be able to be unanchored.

Why are holopads even able to be unanchored?

### Reproducible steps

1. Record Holodisk, insert into holopad
2. Loop Holopad
3. Unsecure Holopad
4. Drag away
5. Spam radio

**Comment by EvilDragonfiend** [comment]
Damn VIP

**Comment by Programs-The-Station** [comment]
Whoops. That's another way to deal with it. Now, the question is, why didn't I get a notification that you had linked that PR.... Thanks, Github.
