### ISSUE TITLE
[Bug]: UI action buttons (top left) cannot be dragged and rearranged

### ISSUE THREAD

**Issue by aramix273** [BeeStation/BeeStation-Hornet#9790]
### BYOND Version

515.1614 (as shown by show-server-revision)

### Round Date

-

### Round ID

-

### Test merges

(unsure if relevant - bug's been active for a while)
[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

since relatively recently, you cannot click and drag action buttons (top left - imagine PDA flashlight button) to rearrange them on your screen as needed
this can mess up some antags or other scenarios that have plenty of action buttons, such as BCIs - where I could rearrange buttons into a WASD configuration for example so I can more intuitively understand which button does what

### What did you expect?

I expected to be able to rearrange them on the screen, because even the tooltip on the "hide/show buttons" button hints at this functionality, yet it doesn't work regardless of whether the button is locked or not

### Reproducible steps

pre: check that button you're trying this on is not locked (ctrl-click)
1. click and hold on a button
2. drag the mouse somewhere else
3. release
=> the button is not relocated

**Comment by HowToLoLu** [comment]
Apparently due to a PR (#9224) using the wrong defines (Using `LAZYACCESS` where `LAZYACCESSASSOC` should've been used.) Gonna fix that now.
