### ISSUE TITLE
[Bug]: Jetpack speed is still mega fast

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#9801]
### Round Date

2023/09/07

### Round ID

45730

### Test merges

In theory this was solved on #9106

### Describe the bug

A traitor atmosian blood brother grabbed one of the jetpacks from engi(or eva storage) loaded it up with 2000 pressure (saw it myself since they happened to show it in my hand though i don't think it matters) and went around doing antag stuff, upon starting the chase in space i tried to use the HoS jetpack but it didn't work(already made the issue) and i went with another Officer using a regular jetpack from eva storage and we spent quite a long time chasing time and tbh i didn't even realized until the round ended that the jetpacks were behaving like pre #9106 in terms of speed so.. yeah we were moving extremely fast

This was on Corg

### What did you expect?

I expected the effects of #9106 to still be in place, but for some reason... Jetpacks were behaving full speed

### Reproducible steps

Grab jetpack
Go to space
Go zoomies!

**Comment by PowerfulBacon** [comment]
Hm, there must be other sources of slowdown involved since I see nothing in jetpack that should allow for anything more than doubling the movement speed

**Comment by boombaklops** [comment]
atmos traitor here. it was 2000 moles, not kpa
