### ISSUE TITLE
[Bug]: Cannot randomize cyborg name or reset to default

### ISSUE THREAD

**Issue by Cartlord** [BeeStation/BeeStation-Hornet#9805]
### BYOND Version

514.1589

### Round Date

2023/09/07

### Round ID

45741

### Test merges

[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)

### Describe the bug

When I opened the name menu (the alternate name menu that affects things like "Backup human name" and "Clown name"), I noticed that there is no dice-roll icon next to the cyborg name field. In addition, if you clear the field, it refills with whatever was in it. These two things, together, mean that - if you ever put a custom cyborg name in there - you cannot remove it without putting in another custom name, you can't just go back to using the default cyborg names.

### What did you expect?

I expected to be able to get rid of the dumb borg name I put in years ago, leaving it blank so I'd just get the normal "Default Cyborg-141"-style names.

### Reproducible steps

1. Open the Character Preferences menu.
2. Click the button next to your character name to open the detailed naming menu.
3. Add something into your cyborg name field.
4. Try to clear it.
5. Despair.

**Comment by Tsar-Salat** [comment]
Successfully reproduced on live sage.

https://github.com/BeeStation/BeeStation-Hornet/assets/62388554/81c62517-f6a0-4124-a35b-2a10d4983d1b

There is no randomize name button, nor does it allow you to default to the base preferences randomized naming by clearing your Cyborg's name.
