### ISSUE TITLE
[BOUNTY]: Viro Additions+Changes: Necropolis Seed

### ISSUE THREAD

**Issue by zeskorion** [BeeStation/BeeStation-Hornet#981]
**What this specific bounty entails:**
Code the following virus symptom, following the description and symptom thresholds. If you need help with some of the numbers, ask me. I will likely come by and edit some flavor text in the code
Add the following virus symptom in a culture bottle to the necropolis chest loot pool, though make it somewhat rare:

**Necropolis Seed**
*level 9*
*stealth: 0*
*resistance: 3*
*stage speed: -10*
*transmission: -3*
An infantile form of the root of Lavaland's tendrils. Forms a symbiotic bond with the host, making them stronger and giving them armor, at the cost of speed 
(the host gains damage resistance and punches similar to a golem, as well as a similar, but not quite as debilitating, speed penalty)

15 resistance: small tendrils  continously roil through the ground near the host like those of an ancient goliath. These * shouldnt * damage or stun the host, and, if possible, make them not destroy walls as normal tendrils do
20 resistance: the host becomes immune to damage from being too hot(being on fire) and walking on lava. this does not make the host inflammable
8 stealth: host is gibbed and drops a tendril chest on death (This should either leave something on the mob's mind data so they cannot spawn more chests, or render them soulless. It should not work on mindless humans)

**Comment by zeskorion** [comment]
now to wait for beebot to post that thingummy

**Comment by zeskorion** [comment]
fucking christ, bot didnt change the moneydollars or put the link on. this is a ten buck bounty atm.

**Comment by ATH1909** [comment]
> stage speed: -10

bruh moment

**Comment by Bastian0930** [comment]
I would like to try this, but i'm not skilled enough to meme on this. Hopefully, this gets added.
