### ISSUE TITLE
Illegal tech not unlockable

### ISSUE THREAD

**Issue by EdwardBlazin420** [BeeStation/BeeStation-Hornet#9810]
### Round ID

45754

### Describe the bug

Destroying syndicate gear in the destructive analyzer just doesn't unlock the tech. I tried with three different things I bought from an uplink and it never worked

### What did you expect?

It to unlock, dawg

### Reproducible steps

>Put syndicate gear into destructive analyzer
>Destroy to discover node
>Node doesn't appear on research consul and tech isn't unlocked

**Comment by St0rmC4st3r** [comment]
What kind of gear did you try to deconstruct?

**Comment by EdwardBlazin420** [comment]
Chameleon Gear Box, AI detector, and Syndicate Soap

**Comment by PowerfulBacon** [comment]
Only items from the uplink can be deconstructed. Doesn't matter what item it is, it just has to be from an uplink.

**Comment by St0rmC4st3r** [comment]
> Only items from the uplink can be deconstructed. Doesn't matter what item it is, it just has to be from an uplink.

This is not true. That is an additional variable that dictates whether the item can be used for researching illegal tech.
Although the AI detector should have provided the research.

**Comment by PowerfulBacon** [comment]
No, only the syndicate hardsuit has this since it can spawn in the nukie ship and not from an uplink.
