### ISSUE TITLE
Gang war not set for centcomm.

### ISSUE THREAD

**Issue by Orange-jpg** [BeeStation/BeeStation-Hornet#983]
Issue reported from  Round ID: 10127 (BeeStation Golden - For Beginners! Low RP Chaotic Fun!)

Reporting client version: 513.1501

https://media.discordapp.net/attachments/427337870844362755/654422589552197635/unknown.png

Gang War doesn't have a report for gamemode.
-By Damien

**Comment by yorii** [comment]
This is fixed.
