### ISSUE TITLE
[BUG] Living Heart Replacement for Heretics fails if a dead monkey watches.

### ISSUE THREAD

**Issue by CatoYang** [BeeStation/BeeStation-Hornet#9841]
### Describe the bug

As heretic with his living heart replaced with a cybernetic one.
Using the living heart ritual to replace his cybernetic heart with a organic one will cause you to die if theres a dead monkey on the circle.
the bug does not recognise that the heretic has a heart even though a post scan indicates that the heart is replaced sending you into a crit and death.

![dreamseeker_RKnGXZSawL](https://github.com/BeeStation/BeeStation-Hornet/assets/78978345/30a9ba83-db17-499e-955f-ff361dd2b290)

### What did you expect?

I expected the monkey not to interfere with the ritual.
Living monkeys do not cause the bug

### Reproducible steps

1. Create heretic,
2. Replace Heart
3. Put heart on circle
4. Put dead monkey on circle
Transmute.
5.Suffer the effects of lack of heart.

**Comment by Tyranicranger4** [comment]
Unable to replicat; ritual performed as expected. The replacement heart in your image doesn't seem to be beating, perhaps there was something wrong with it that the ritual doesn't check for?

**Comment by CatoYang** [comment]
I tried replicating this again and found it to bug out reliably when i have 2 hearts (originally believed it was 2 monkies)

![dreamseeker_GF2wzDl6xi](https://github.com/BeeStation/BeeStation-Hornet/assets/78978345/897e1f5f-6058-4a62-abd2-6b9e5595a013)

![dreamseeker_YGtrnVvDah](https://github.com/BeeStation/BeeStation-Hornet/assets/78978345/1131a15a-f880-4cc2-9431-89576b070c0a)
