### ISSUE TITLE
[Bug]: Saline Canisters "beakers" (5000u) can be obtained (unintentional?)

### ISSUE THREAD

**Issue by aramix273** [BeeStation/BeeStation-Hornet#9854]
### BYOND Version

515.1614

### Round Date

2023-09-18

### Round ID

45882

### Test merges

not sure if relevant but

[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#9826: 'Fix Z-Clear not properly removing baseturfs' by itsmeow at commit 8829fe27e3](https://www.github.com/beestation/beestation-hornet/pull/9826)

### Describe the bug

Heavy-Duty Saline Canisters, ordered from cargo, are basically resprited IV drip stands that are spawned with a 5000u saline-glucose solution beaker
for comparison: bluespace beakers have 300u capacity and carbons have 1000u capacity per reagent
these beakers don't seem to be intended to be obtainable (the proc to get off the beaker is overwritten to do nothing and the beaker itself has no sprite), but they can be obtained by breaking the IV drip, which drops it (behavior inherited from the normal IV drip but not overwritten)

consequences: you can now make a large grenade with 10000 units of chemical explosives, far exceeding the destructive capacity of TTVs with better theoretical values
https://www.youtube.com/watch?v=kiJO8STMTDA

### What did you expect?

I expect Heavy-Duty Saline Canisters not to allow their beaker to drop when being destroyed (taking beaker off is overwritten to do nothing, for example)

### Reproducible steps

1. order a heavy-duty saline glucose from cargo
2. break it using some tool (circular saw for example)
3. use right click or alt click menu to get the spriteless beaker
4. ??? (do whatever you want with at least one 5000 units capacity "beaker" (cannot be inserted in chemical payloads))

**Comment by EvilDragonfiend** [comment]
wtf it had an invisible sprite lmao
