### ISSUE TITLE
[Bug]: Simplified Targeting cannot start surgery to take out Appendix

### ISSUE THREAD

**Issue by lowwy** [BeeStation/BeeStation-Hornet#9885]
### BYOND Version

514.1589

### Round Date

23-sep-2023

### Round ID

45967,45968

### Test merges

[#9124](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#9845](https://www.github.com/beestation/beestation-hornet/pull/9845)

### Describe the bug

use Simplified Targeting
use drapes on patient
choose chest
choose groin
>nothing happens

EDIT: this also is the same for eye surgeries

Additional request:
If someone wears armor and you want to put a bandaid on him it blocks you when aiming for chest, could it still show the arms/legs (anything that can be bandaided) instead?

### What did you expect?

I expected it to start or give the option for organ manipulation

**Comment by HowToLoLu** [comment]
The relevant PR: #9845
(Remember to include testmerges so we can fix things)

**Comment by PowerfulBacon** [comment]
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/26465327/8e775595-ed4f-4ab6-b07f-ce7e6d3d3a09)
