### ISSUE TITLE
IPC Monkey Leader Breaks Mode

### ISSUE THREAD

**Issue by LordZanos** [BeeStation/BeeStation-Hornet#989]
## Reproduction:
IPC is assigned monkey leader.
IPC is immune to disease.
Mode effectively never happens, since IPC never actually turns into a monkey.

**Comment by zeskorion** [comment]
Same for blasmems. Its been a thing fer awhile now

**Comment by honkhonkclown** [comment]
yet another reason to just remove monkey as a mode already

**Comment by PowerfulBacon** [comment]
Monkey mode is no longer ran on the servers.
