### ISSUE TITLE
Cyborg cloned as human with IPC name

### ISSUE THREAD

**Issue by DeanYktRu** [BeeStation/BeeStation-Hornet#9900]
Issue reported from  Round ID: 45988 (BeeStation Sage - Roleplay)

Reporting client version: 514.1589

Strange thing happened but here what follows:

Selected IPC character(With robotic name, obviously)
Choosed Cyborg
Later that round, got obliterated by Ash Drake(Accidentally provoked)
Die as MMI in Lavaland due to ash storm(First time seeing it, or was on purpose due to brain decay)
Reactivated by doctor(Still being MMI)
Failed attempt of inserting MMI into cyborg shell(They said that brain is dead or too damaged)
Doctor and roboticist found out that brain inside the MMI was organic human brain, not positronic IPC brain!
Failed attempt to repair the brain with mannitol(Examining the brain said that brain is lifeless)
Initiated cloning attempt... success!
Came out as human with IPC name(And with no gender, as upon examination it says they, not he/she)

I say that it might have been overlooked with some bit of late join IPC cyborg.

**Comment by tontyGH** [comment]
I have the fix for this
