### ISSUE TITLE
Rev can be trapped in a chapel forever

### ISSUE THREAD

**Issue by EvilDragonfiend** [BeeStation/BeeStation-Hornet#9903]
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/0e92f908-a8e7-4cc6-85c4-77fbe0a2869e)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/87972842/515c94d0-04e9-4cd6-86ba-7e5aa463822d)

**Comment by JixS4v** [comment]
@EvilDragonfiend pretty sure you fixed this in #10779
