### ISSUE TITLE
[Bug]:  revenants being able to drag stuff

### ISSUE THREAD

**Issue by hotimep** [BeeStation/BeeStation-Hornet#9916]
### BYOND Version

514.1589

### Round Date

2023/9/26

### Round ID

46010

### Describe the bug

half a salt bug report and half someone asked me to make it, revenants being able to drag stuff is only a thing on bee, and seeing a revenant drag an emagged medibot into maint during a radstorm, cmon

### What did you expect?

i expected not 

### Reproducible steps

1. be a revenant
2. Phase Shift (become corporeal)
3. control+click drag

**Comment by EvilDragonfiend** [comment]
We really don't restrict revenant ability that much. As long as it's not that revs can grab things even while they're incorporeal, I don't think it's not that an issue.
You'd be surprised revs even can strip people.

**Comment by hotimep** [comment]
this is what i get for doing what people tell me to do

**Comment by Tsar-Salat** [comment]
> ### Reproducible steps
> 1. be a revenant
> 2. click drag

This is incorrect.

You have to deliberately put yourself into a corporeal state, in which you are highly vulnerable. It's not something revenants can just do.

**Comment by hotimep** [comment]
> > ### Reproducible steps
> > 
> > 1. be a revenant
> > 2. click drag
> 
> This is incorrect.
> 
> You have to deliberately put yourself into a corporeal state, in which you are highly vulnerable. It's not something revenants can just do.

fixed

**Comment by PowerfulBacon** [comment]
Revenants can drag stuff while in corporeal form which is intentional
