### ISSUE TITLE
[Bug]: Crew transfer vote interval doesn't seem to work properly.

### ISSUE THREAD

**Issue by PowerfulBacon** [BeeStation/BeeStation-Hornet#9917]
### BYOND Version

N/A

### Round Date

N/A

### Round ID

N/A

### Describe the bug

The crew transfer vote interval is set at 30 minutes. Once the 90 minutes have passed and the first crew transfer vote has started, the next one usually takes about 90 minutes to trigger (I'm not sure if there are any more after that).

### What did you expect?

After 90 minutes has passed, a shuttle transfer vote should be triggered every 30 minutes.

### Reproducible steps

1. Wait for the first shuttle transfer vote to trigger.
2. Wait for the shuttle vote interval to pass.
3. The next shuttle vote won't start.

**Comment by PowerfulBacon** [comment]
I think this may be breaking when the server passes midnight, since realtime of day is clamped between 0 and 864,000

**Comment by HowToLoLu** [comment]
> I think this may be breaking when the server passes midnight, since realtime of day is clamped between 0 and 864,000, meaning that if the vote time is past midnight it will never re-trigger

I looked at it and the `REALTIMEOFDAY` definition used shouldn't be clamped

code/__DEFINES/maths.dm
```dm
#define REALTIMEOFDAY (world.timeofday + (MIDNIGHT_ROLLOVER * MIDNIGHT_ROLLOVER_CHECK))
#define MIDNIGHT_ROLLOVER_CHECK ( GLOB.rollovercheck_last_timeofday != world.timeofday ? update_midnight_rollover() : GLOB.midnight_rollovers )
```

code/__DEFINES/time.dm
```dm
#define MIDNIGHT_ROLLOVER		864000
```

**Comment by PowerfulBacon** [comment]
Yea, but the shuttle timer simply just adds to the previous shuttle call timer and doesn't do a rollover check

**Comment by HowToLoLu** [comment]
The rollover check is done anytime the defition is used, no?

**Comment by PowerfulBacon** [comment]
I'm not sure what's happening then since I'm sure I've been in rounds that have passed the 2 hour mark without a second transfer vote popping up. The code doe sseem like it should handle that
