### ISSUE TITLE
[Bug]: Express Supply Console Boards can't be multitooled to enable contraband

### ISSUE THREAD

**Issue by boombaklops** [BeeStation/BeeStation-Hornet#9933]
### Round Date

N/A

### Round ID

N/A

### Describe the bug

When I multitooled an express supply console board, it gave this message in the chat.

![console_bug](https://github.com/BeeStation/BeeStation-Hornet/assets/116023863/fdb15f60-ab3a-4d9b-abd5-ae5bfe8c8851)

It wasn't possible to enable contraband options with the multitool.

### What did you expect?

I expected the multitool to be able to toggle contraband availability on the board.

### Reproducible steps

1. Use a multitool on an express supply console board.

**Comment by CydiaLamiales** [comment]
Seems like you *can't* hack the express supply console for contraband with a multitool, and instead only remove the emag effect of allowing the drop pod to land anywhere on the station.
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/110184118/21a2d04f-f22c-4f38-864c-004d833067b1)
