### ISSUE TITLE
[Bug]: cargo bay door on rad station has grey door bits sticking out,i made a video of this

### ISSUE THREAD

**Issue by fierycomet** [BeeStation/BeeStation-Hornet#9969]
### BYOND Version

514.1589

### Round Date

2023-10-05-18:42:24

### Round ID

46118

### Test merges

-9124
-9815

### Describe the bug

I was ghosting and saw that the cargo door was showing bits of grey every few moments

### What did you expect?

I expect it to be fixed as this is some sort of bug

### Reproducible steps

1. Load radstation map
2. Go to the cargo bay section the one with the lamar poster
3. Wait and watch till the cargo door has grey bits showing

**Comment by fierycomet** [comment]
Video link of the 

> [_`bug```_](url)https://yourimageshare.com/ib/T84X0BPRyL

**Comment by PowerfulBacon** [comment]
This is most likely a byond rendering issue / GPU incompatability issue with byond.

**Comment by PestoVerde322** [comment]
Yeah, seconding bacon, since all the icons are loaded directly, would've made more sense with certain combinations (grey door with brown inner parts or vice versa), but in this case I strongly suggest you to check your computer's hardware!

**Comment by Rukofamicom** [comment]
Your video card or video drivers are either failing or incompatible with byond.
