### ISSUE TITLE
[Bug]: Custom Food Not Working

### ISSUE THREAD

**Issue by NormalAnomaly** [BeeStation/BeeStation-Hornet#9983]
### Round Date

2023/10/07

### Round ID

46144 and other recent rounds

### Test merges

The following pull requests are currently test merged:
[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#9815: 'Standardises ByondUI rendering + Emissive Refactor + Emissive energy guns & Huds & IPCs' by PowerfulBacon at commit 55b4646293](https://www.github.com/beestation/beestation-hornet/pull/9815)

### Describe the bug

Attempted to apply food items like cheese or meatballs to buns, bread slices, pizza crusts, and boiled noodles to make custom foods.  This did not work.  Within the scope of what I tested, only custom kebabs still work as expected.

Thinking about it, all of the food + food custom foods failed.  The kebab is jabbing a rod into a food item to start the custom food creating, so I'd wager that has something to do with why it works and the others don't

### What did you expect?

Putting foods together to create custom foods as has nearly always been possible.

### Reproducible steps

1. Create food item base (noodles, bun, crust)
2. Attempt to slap a component onto it (cooked cutlet for example)
3. Marvel as nothing happens.

**Comment by Tsar-Salat** [comment]
> Thinking about it, all of the food + food custom foods failed. The kebab is jabbing a rod into a food item to start the custom food creating, so I'd wager that has something to do with why it works and the others don't

Theres nothing to wager. We are in the middle of a newfood port. The majority of customfood is incompatible during this due to the way reagent transfer works.

Please check previous issues. #9199

**Comment by Rukofamicom** [comment]
Thank you for reporting this, and don't be afraid to post in the future. 

Maints appreciate reports on anything that seems to be a bug, even if it is something we already know about.

**Comment by Rukofamicom** [comment]
This is now properly "fixed" as well, even if it was known and/or intended. 

#10026
