### ISSUE TITLE
Computer smoothing broken

### ISSUE THREAD

**Issue by itsmeow** [BeeStation/BeeStation-Hornet#9986]
### BYOND Version

514.1589

### Round Date

2023/10/07

### Round ID

46149

### Test merges

Master commit: [61d1889649d9a805e6cc76f0d409c6aafb4ea0eb](https://www.github.com/beestation/beestation-hornet/commit/61d1889649d9a805e6cc76f0d409c6aafb4ea0eb)
The following pull requests are currently test merged:
[#9124: 'Enable serverside 515.1614 (new)' by Crossedfall at commit 43f695e9a4](https://www.github.com/beestation/beestation-hornet/pull/9124)
[#9815: 'Standardises ByondUI rendering + Emissive Refactor + Emissive energy guns & Huds & IPCs' by PowerfulBacon at commit 55b4646293](https://www.github.com/beestation/beestation-hornet/pull/9815)

### Describe the bug

![273420201-2be31332-8c41-467f-ba1a-66d2fc249981](https://github.com/BeeStation/BeeStation-Hornet/assets/10366817/a6ea5e96-5ce1-486e-aa38-b773211c0863)

### What did you expect?

It to smooth properly

### Reproducible steps

KiloStation, bridge.

**Comment by HowToLoLu** [comment]
Looks like the icon was improperly refactored to fit the smooth groups- I'll do that real fast (honestly need a better smoothing system- look at all of these duplicate icons:)
![image](https://github.com/BeeStation/BeeStation-Hornet/assets/22382345/fb3bc169-87ca-4a45-883b-520cfb78632a)
