### ISSUE TITLE
[Bug]: You don't revive as a zombie if you succumb or #last wordwhisper

### ISSUE THREAD

**Issue by Fronsis** [BeeStation/BeeStation-Hornet#9994]
### Round Date

2023/10/08

### Round ID

46161

### Describe the bug

Apparently this is an old bug that's still around, basically if you succumb or whisper while in crit as a zombie and eventually perish, you're unable to revive, your zombie does not heal and it stays dead forever

### What did you expect?

To revive after a period of time and continue doing zombie stuff

### Reproducible steps

1. Be a zombie, midround event (unsure if this also applies to romerol, probably)
2. Get hit up to hardcrit by anything
3. Do a #funny last word 
4. Observe how your body does not heal and you remain dead, you never stand up and your zombie remains dead forever!

**Comment by Tsar-Salat** [comment]
Im refactoring the way succumb works in a future atomization of #8965, so I can will most likely fix this along the way

**Comment by Fronsis** [comment]
Hm given that #8965 got closed for now guess the bug remains active

**Comment by Tsar-Salat** [comment]
> got closed for now guess the bug remains active

Check that PRs description, I'm atomizing it, ya goof.
