### ISSUE TITLE
[New Feature]: Remove the appendix from Felinids

### ISSUE THREAD

**Issue by JukeJukestar** [BeeStation/BeeStation-Hornet#9995]
### Describe the feature request
Remove the appendix organ from felinids.

## The "Lore Justification"
In youtuber Daszombes' recent Nekopara lore video, he pointed out the fact that catpeople (in the nekopara universe) likely do not have appendixes (Because they are cats mutated to be humanlike, as opposed to humans mutated to be catlike). Not having an appendix is a catlike feature, similar to better eyesight (which beestation felinids have).
<details>
  <summary>The video in question</summary>

https://youtu.be/zwWL_DE7wOk?t=792
</details>

This isnt nessecarily relevant to ss13 lore, but would be a fun minor way to differenciate felinids from humans regardless. The appendix does not do anything ingame, exept give you a very small chance to contract appendixitis, so it would technically be a buff, though such a minor one that it probably doesnt matter.

**Comment by Absolucy** [comment]
I like any sort of small detail to further differentiate felinids from "humans with cat ears and tails" 👍🏻
